### ISSUE TITLE
Authentication: DAWSON Account Login 

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#10007]
As a DAWSON user, so that I can have a less confusing and better tailored sign-in process, I want to sign in to DAWSON from a DAWSON URL/domain.

Currently the DAWSON sign-in process is hosted directly on Amazon servers. This is an experiential and technical disconnect from a user experience point of view; the DAWSON link on the USTC website doesn't actually take the user to DAWSON, but a cryptic Amazon URL from which they are presented with a page with none of the DAWSON/USTC stylings and which we have very little control over the look and feel.  This has also presented technical problems on occasion as seen with tickets reporting issues with jumping domains during the process and browser behavior.

To streamline this overall experience and open up avenues for customizing the DAWSON sign in process, we would like to move the front-end authentication UI to be within DAWSON itself.

This story will address the sign in process for the user.

## Acceptance Criteria
* User can log in with credentials from a DAWSON-hosted login page
* Login page has links to direct users to current flows for reclaiming forgotten passwords and signing up for new accounts
* Errors encountered in logging in are returned and displayed on the same DAWSON-hosted login page

## Post Deployment Tasks
- [x] Extract application.getCognito() into application.getUserGateway() (Abstract away from cognito specific syntax in interactors)
- [x] Remove switch-cognito-triggers-color.js as we do not have cognito triggers - Rachel (https://github.com/flexion/ef-cms/pull/10277)
- [x] Remove cognito triggers from terraform - Rachel (https://github.com/flexion/ef-cms/pull/10277)
- [x] Search for `TODO 10007` - Rachel (https://github.com/flexion/ef-cms/pull/10277)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Questions/comments from pre-refinement:
Look at login.gov for reference. Jenna may be able to help with questions.

**Comment by katiecissell** [comment]
Utilize the [USWDS sign in template](https://designsystem.digital.gov/templates/authentication-pages/sign-in/) as a good jumping off point.
- Use Dawson's header and Footer
- Add text below the sign in header that says "Email address and password are case sensitive."
- Use the Figma file for specific font size, color and spacing.

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/e2b94595-687f-49a0-8bcb-de3ccb06cc2a) 


Validation
- Do not enable the sign in button until both email and password fields have something in them (Disabled button should be #c9c9c9)
- Follow existing validation behavior and display an alert when an invalid email or password is used. The alert will need to be shortened width wise to match the sign in box's width.
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/e9132bdc-ada1-4160-b59c-6741cc3c2d90)

Mobile
- Fields/text should maintain their spacing and respond as the width of the page shrinks
 ![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/b563b893-e9cb-4572-95ff-fdc0d56ea974)
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/667c255c-5191-4f48-9e9b-cc5177979d7f)

[Figma File ](https://www.figma.com/file/PNfYdFe4uA5iQPvqP8Qjvc/USTC-%7C-Authentication%3A-DAWSON-Sign-In-UI-%7C-10007?type=design&node-id=26%3A498&t=gGpxMbPcozQnIPvt-1)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User navigates to DAWSON login page; Page has look and feel as per design, link to the page is no longer a cognito url.

- Navigate to the DAWSON Login Page (devs will provide this link)
- Review the Page

Expected Results: 
- [ ] Page matches what is in the mockups above
- [ ] The URL is no longer for cognito, but rather a DAWSON login page.



#### 2) User views DAWSON login page; links to Forgot your password and sign up are present, but direct users to the cognito page.

- Continuing from the previous test
- Confirm that there are links to the forgot password and for Create your account now.
- Click on each of those links

Expected Results:
- [ ] User is routed to the existing cognito pages for the user to either update their password or create a new account



#### 3) Sign in button on the DAWSON login page is not active until there is both an email and password entered.

Part 1
- Continuing from the previous test
- Ensure that the Sign In button is not enabled
- Input an email, but do not input any password

Expected Results:
- [ ] The sign in button is still disabled

Part 2
- Input a password

Expected results
- [ ] The sign in button is enabled after both fields have inputs in them

*Repeat this test, but add in a password first, followed by the email.  
*Repeat this test, but after the button is enabled, delete either the email or password - the sign in button should disable if both fields are not filled in.



#### 4) User attempts to login with an email or password that does not exist (or that are in the wrong case); error message is displayed.

**Part 1**
- Continuing from the previous test
- Input an email and password that does not exist in DAWSON
- click sign in

Expected Results:
- [ ] Validation error message that states "The email address or password you entered is invalid"

**Part 2**

- Input an email that DOES exist in DAWSON, but change the case.
- Click Sign in

Expected Results:
- [ ] Validation error message that states "The email address or password you entered is invalid"



#### 5) User enters a valid email address and password; User is logged in to DAWSON as per normal.

- Continuing from the previous test
- Input a valid email and password
- Click Sign in

Expected Results
- [ ] User is logged in as per normal with their appropriate role

*Repeat this test with various users (internal/external)



#### 6) Test on Mobile

- [ ] Tests 1-5 pass on various mobile devices, and the content on the screen is readable and has an overall nice user experience.

**Comment by TomElliottFlexion** [comment]
Email normalization has been moved from #10011 to this story: see comments in 10011

**Comment by swongCO** [comment]
Added mockups from 10011 re email verification banners on the sign in page.

**Comment by rachelschneiderman** [comment]
@ttlenard As a part of this story we have changed just slightly how maintenance mode works. When you have time, let's get together so we can show you what has changed and see if any documentation or screenshots need to be updated.

**Comment by ttlenard** [comment]
There are a few more things to consider with this story.  Not sure if this handing the things below should be a separate story or included.  @cholly75 @rachelschneiderman @zRogersFlexion @pixiwyn @TomElliottFlexion 

1 - Practitioner changes employers. Admissions clerk goes into practitioner profile in DAWSON, ensures that they are not associated with any open cases, then changes the employer.  This works fine, but we had an instance where the practitioner was logged in on their DAWSON account when the employer change occurred, and they subsequently filed an EA on a case. This filed the EA incorrectly (said Resp. instead of private), and even if they logged out/back in, the privatePractitioner record on the case wasn't created, and the practitioner was not associated with the case (they were not listed as counsel for petitioner). Furthermore, the Practitioner didn't have access to the case documents on the case. Need to be able to gracefully handle this scenario.

2 - Another scenario to think about is when an Admissions clerk creates an account for someone (can be admitting a practitioner or adding in an eAccess email to a Petitioner).  When they do this, DAWSON currently generates a temporary password for the user that is valid for 7 days.   We have multiple instances per week where the user doesn't log in with the temp pw within the 7 days, and they have to email dawson support and request a new temp pw.  Mike has created a Zendesk automation that will resend the user an email with a new temp PW.  The Court would like to be able to let the user get a new temp PW themselves, rather than having them submit an email to dawson support.  Can this be considered with this ticket?

**Comment by cholly75** [comment]
I think we need separate stories on both of these.

**Comment by swongCO** [comment]
**UX feedback on exp2**

The title font should be Source Sans Pro:
<img width="1576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4346c8ca3e4c984be45149db94fcb375d41aecd/Screenshot%202024-02-02%20at%2012.14.49%E2%80%AFPM.png" alt="Screenshot 2024-02-02 at 12.14.49 PM.png" />
 
In mobile and smaller screens, I'm getting the menu in the right corner. That should not be there:
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab70a7ad3f2e0a47916ab52d5d2c175a25c01348/Screenshot%202024-02-02%20at%2012.22.18%E2%80%AFPM.png" alt="Screenshot 2024-02-02 at 12.22.18 PM.png" />
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUltQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--858df71df8b97f8e35437531e48249a502d36b7a/Screenshot%202024-02-02%20at%2012.25.00%E2%80%AFPM.png" alt="Screenshot 2024-02-02 at 12.25.00 PM.png" />

**Comment by zRogersFlexion** [comment]
@ttlenard @cholly75 FYI we have addressed scenario #2 that Tenille mentioned a few comments above (practitioner does not verify their account within 7 day time limit) as a part of this story. We have NOT addressed scenario #1 as a part of this story.

**Comment by ttlenard** [comment]
Thanks @zRogersFlexion. Looking forward to seeing a demo of this!

**Comment by ttlenard** [comment]
Testing Feedback:

Getting a 400 error in the following scenario:

1. Petitioner creates a new account, but does not verify their email address
2. As an Admissions Clerk, navigate to a case with a paper service Petitioner and click on case info/parties tab
3. Click edit for the paper service petitioner
4. Add in the email that you created in step 1 (the one in pending status - has not been verified)
5. Click save
6. You will get the "matching email found" pop-up
7. Click ok
8. Receive a 400 error

**Comment by swongCO** [comment]
**UX feedback (on Dev)**
- Hide password links: change to lowercase p for password (on Create acct, Log in and Reset password flows)
- Success alert for email verified: change second sentence to "You can now log in to DAWSON."
- Reduce side padding in mobile view for Create acct flow to match Log in:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d00f18e76e4fd2f7d96daa1584634645b447ad52/Screenshot%202024-02-27%20at%209.59.33%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 9.59.33 AM.png" />

<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5951e44bb7718004f1ddc998ec8f9998c000a74f/Screenshot%202024-02-27%20at%209.59.55%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 9.59.55 AM.png" />


- Look into changing cognito email sender name to "U.S. Tax Court" instead of "noreply" for account verification email (sender email will remain "noreply@xxxxx.ustaxcourt.gov":

<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21UQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52fb40a13fa5ee8717a7b48b0760ada4674d47f4/Screenshot%202024-02-27%20at%209.43.21%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 9.43.21 AM.png" />

**Comment by ttlenard** [comment]
Some testing Feedback:

@rachelschneiderman @zRogersFlexion @pixiwyn @TomElliottFlexion 

1. Looks like the DAWSON icon is now pointing to the login page instead of the DAWSON home page. Please update.
<img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cd435dbccf440e4c9d1ade2a89c88f55eaec47e/image.png" alt="image.png" />

2.  Looks like the validation has changed for the PW.  I'm now getting validation errors when I have a space in the middle of my PW. It does not do this on TEST.
<img width="524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d8f151c3fc7e5cd930f6b176b1c7a7b3546a590/image.png" alt="image.png" />

<img width="1193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVduQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5f71c4a35d4194d891c4c719ca6dceb52b18630/image.png" alt="image.png" />

<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e8e6a9786c908b034d229e431c09118bcf47223/image.png" alt="image.png" />

3.  Some comments regarding the emails.  See comments in screen grabs:

<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--505fd28eb1039ef682fd40476f16c4f6d0efe2b2/image.png" alt="image.png" />

<img width="1266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--293abab33efd5e522f874138442d9eb6a88f3ff0/image.png" alt="image.png" />

**Comment by swongCO** [comment]
UX is fine with all of the above changes. For the alert banner, in Dawson Test, the header is 17px and the body is 16px. Please match the font sizes for this story. Thank you!

**Comment by ttlenard** [comment]
@pixiwyn @rachelschneiderman @zRogersFlexion @TomElliottFlexion 

I've created a quick video of a small issue I found.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecc5fbc1a900aa45002e3b67e80f011463da6ad1/newAccountPWIssue.mp4)

**Comment by ttlenard** [comment]
@rachelschneiderman @zRogersFlexion @pixiwyn @TomElliottFlexion 

More testing feedback:

1. User has a DAWSON account and then they go into my account and update their own email
2. They receive the email in their inbox and they verify it. They can log into DAWSON just fine with their new email.
3. Then, at some point they go back into their email and click on the verify email button again.
4. They get this error:

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUN0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f648ee5e19c9ce327f3a202c82166c6d0823f47d/image.png" alt="image.png" />

5. We might want to enhance the messaging on this error?  In this scenario, the email address is already verified which is why the link isn't working, but the error message doesn't really say that.  Not sure if we want it to be that specific? Are there other scenarios where a user would receive this error message? If so, we could at least add in the "dawson.support@ustaxcourt.gov" instead of the generic DAWSON support.  What are your thoughts on this error?

**Comment by swongCO** [comment]
Update alert in Tenille's comment above:

Unable to complete your request
Your request cannot be completed. Contact dawson.support@ustaxcourt.gov for help.

**Comment by ttlenard** [comment]
Based off of our conversation at Standup this morning, I've added in number 6 in the above comment to mention logs.

**Comment by ttlenard** [comment]
@cholly75  For your consideration on either this story or a follow up story. This issue that is existing in production today and is still present in Dev causes so much confusion to the public users. 

This has to do with the verify email link that a user receives when they change their email. If the user isn't logged in on another tab with their previous email, the user get's a 401 error. When helpdesk staff respond to tickets, and in our training materials, we have to bold/capitalize all over the place that the user must remain logged in on their other tab. Sure would be nice to not have to explain this constantly.

Steps to reproduce:
1. Log in as a Petitioner
2. Click on My account 
3. Update the email to a different email address
4. You will see that the new email is pending.
5. Log out of DAWSON
6. Navigate to your email, and click on the verify email button in the email that you received
7. The user will get the Unable to complete your request error:
8.<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0c3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2106393d626fdbf128e3494cae665162de93f863/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Some more testing feedback: @rachelschneiderman @pixiwyn 

cc: @cholly75 

**Issue 1**
1. User with an account clicks the forgot password button.
2. Input the valid email address that you have access to
3. You should receive the email with the password reset code
4. On the DAWSON screen, input an incorrect password reset code
5. You should get the Invalid Verification code error.
6. Click on the link to request a new code.
7. Notice that nothing happens when clicking on this link. 
<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2k4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bdce92f10b56f4de41ca3e95e78d0feb56d6c84/image.png" alt="image.png" />

**Issue 2**
1. The formatting for the "Welcome to DAWSON" header and the USTC icon in the upper left side of the screen is off when viewing the Account creating and Log in screens.  Note that this is not currently formatted this way on any of the other environments. Seems to only be occurring on DEV.

Dev Environment:
Create Petitioner Account page
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3k4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5decbce1d19c7453c5ada0025ef6bbdbcf62a04f/image.png" alt="image.png" />

Log in page:
<img width="1548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzI4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39876238279d8eaef0a05c1d07adcebe1cfa26c3/image.png" alt="image.png" />

IRS Environment:
<img width="1204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzY4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0acd73b8b639d03e7bb36b94114957881c8913f8/image.png" alt="image.png" />

**Comment by katiecissell** [comment]
Updated account created email mock:
<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0237db65b687471574cd98da96e7a87fba928f9/image.png" alt="image.png" />

**Comment by swongCO** [comment]
**New alert text for expired temp password**

Header: Temporary password has expired

Body: The temporary password you entered has expired. We sent an email with a new temporary password that expires in 7 days. If you don’t see it, check your spam folder. If you’re still having trouble, email dawson.support@ustaxcourt.gov.

**Comment by rachelschneiderman** [comment]
@cholly75 @ttlenard

If an external user (petitioner/practitioner) changes their login and service email, they will receive an email that they need to click a link to verify the change. The email states the verification link will expire in 24 hours, right now that is NOT true, the link will never expire. 

At some point we need a story to address the expiration of that link.

**Comment by cholly75** [comment]
@rachelschneiderman - documented verification link behavior as #10313
