### ISSUE TITLE
Consolidation: QC of Multidocketed Filings

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#10103]
As a _______, so that ________, I need ________.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by cholly75** [comment]
[consolidation_cover_sheet_proposal.docx](https://github.com/user-attachments/files/18352972/consolidation_cover_sheet_proposal.docx)

**Comment by katiecissell** [comment]
UX Notes:

[Figma File ](https://www.figma.com/design/Xn6a8dRy2DTA3P0o2MVTFm/USTC-%7C-10103-Consolidation%3A-Cover-Sheets-for-E-filed-Documents?node-id=62-930&t=dazMXF4wNzgC8lKY-1)

Only one row per consolidate case filing. Display all docket numbers with appropriate consolidated icon.
<img width="1039" alt="Image" src="https://github.com/user-attachments/assets/7f7fc9ae-2bab-48e5-8794-f6ad1b9070b4" />

When QCing the document from the lead case, display an alert.

<img width="1038" alt="Image" src="https://github.com/user-attachments/assets/6acb3f1c-4cc8-418f-868f-bfb4ed35b9f4" />

When editing the document from the lead case, display an alert.

<img width="805" alt="Image" src="https://github.com/user-attachments/assets/bca26e2a-723f-4eed-b255-bbbe4b187e60" />

When editing the document from a member case, display an alert and disable all fields on the document info tab. 

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/42d0ac85-5f2b-4620-86fa-010972c8a897" />

**Comment by ttlenard** [comment]
Note: This story resolves the QC issues described in Scenario 1 above, but does not solve the multiple coversheets that occur when serving simultaneous documents.  Another story will address the serving component.

**Comment by ttlenard** [comment]
## Test Cases

**Preconditions**
- Log in to DAWSON as a Petitioner associated with a Consolidated case
- File a document and be sure that you filed it in all cases in the group (test this with filing from a member case and a lead case). 
- Be sure that some of the docs you file are simultaneous
- Repeat the steps above, but with a Private Practitioner and an IRS Practitioner.
- You should not have multiple documents available now in Document QC.


#### 1) Docket clerk accesses the Section QC inbox; Filings made across a consolidated group now display as a singular QC item with all the cases the document was filed in also displayed.

- Log in as a Docket clerk
- Click on Document QC
- Click on Switch to Section QC
- Scroll down to find the Petitioner filing from the Preconditions above.
- Review the QC item

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Inbox view for the filing made across the group. (check both My Document QC and Section QC Inbox tabs)
- [ ] **NEW FUNCTIONALITY** - Each docket number that the document was filed in is displayed in the singular QC item in the display (see mock) 
- [ ] **NEW FUNCTIONALITY** - Lead Case and Member case icons are displayed, with the lead case docket number listed first.
- [ ] **NEW FUNCTIONALITY** - Each case in the group displays the docket number as a link, and the user can click on the docket number link to be navigated to each cases docket record.
- [ ] **NEW FUNCTIONALITY** - Looking in Postgres, dev discretion on how we implement this
- [ ] **NEW FUNCTIONALITY** - Each case in the consolidated group has a document filed displayed as not QC'ed as per normal (red star) when viewed on the docket record.



#### 2) Docket clerk assigns the Consolidated Case QC item to another Clerk; QC item is assigned appropriately.

- Continuing from the previous test
- Check the box next to the Work item from the Section QC box
- Scroll up to the top of the QC page, and assign it to a different docket clerk

Expected Results:
- [ ] QC work item for the consolidated case gets assigned as per normal
- [ ] **NEW FUNCTIONALITY** - Looking in Postgres, dev discretion on how we implement this and it is now assigned to the Docket Clerk.



#### 3) Docket clerk clicks on the document title from the My Document QC inbox; QC item opens to the QC page on the Lead Case in the Consolidated group.

**Part 1**
- Continuing from the previous test 
- Log in as the docket clerk that the work item was assigned to
- Click on the Document QC header
- Find the QC item for the consolidated case filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Inbox view for the filing made across the group. (Check both My Document QC and Section QC Inbox tabs)

- [ ] **NEW FUNCTIONALITY** - Each docket number that the document was filed in is displayed in the singular QC item in the display (see mock)
- [ ] **NEW FUNCTIONALITY** - Lead Case and Member case icons are displayed, with the lead case docket number listed first.


**Part 2**
- Click on the document title link

Expected Results:
- [ ] **NEW FUNCTIONALITY** - QC item opens as per normal and is the Lead Case in the group
- [ ] **NEW FUNCTIONALITY** - New alert displays at the top of the page (see mock).
- [ ] **NEW FUNCTIONALITY** - Alert includes a bulleted list of all cases in the consolidated group along with the Petitioner names
- [ ] **NEW FUNCTIONALITY** - Alert includes reminder about Notice of Docket change.



#### 4) Docket clerk completes the QC (does not update the filing info and does not send a message); Document QC is completed for all documents that were filed in the group.

- Continuing from the previous test
- Do not make any edits to the QC work item
- Click Complete

Expected Results:
- [ ] Standard confirmation message that QC was completed
- [ ] **NEW FUNCTIONALITY** - On the Processed tab, the singular work item displays all of the docket numbers in the group, and displays the correct processed date. (Check both My Document QC and Section QC Processed tabs)

- [ ] **NEW FUNCTIONALITY** - When accessing the docket record for each case in the group, all of the documents are now QC completed 
- [ ] **NEW FUNCTIONALITY** - Looking in Postgres, dev discretion on how we implement this, but the work item has been completed.


#### 5) Repeat tests 1-4, but instead Click Complete and Send Message.

- [ ] Tests 1 - 4 pass


#### 6) Docket Clerk Edits the document info during QC for a document that was filed across a consolidated group; Notice of Docket change is generated and docketed in each case in the Consolidated group.

- Repeat the steps for test cases 1-3 and the preconditions if needed
- Click on the document title for a document that was filed in a consolidated group
- On the QC screen, Edit the document title
- Click Complete

Expected Results:
- [ ] Standard confirmation message that QC was completed
- [ ] **NEW FUNCTIONALITY** - On the Processed tab, the singular work item displays all of the docket numbers in the group, displays the correct processed date, and the updated Document Title (Check both My Document QC and Section QC Processed tabs)
- [ ] **NEW FUNCTIONALITY** - When accessing the docket record for each case in the group, all of the documents are now QC completed and display the updated Document title and Event code
- [ ] **NEW FUNCTIONALITY** - There is only one new coversheet on each of the documents, reflecting the one change that was made (no more duplicative coversheets) for each case in the consolidated group.
- [ ] **NEW FUNCTIONALITY** - When accessing the docket record for each case in the group, the standard Notice of Docket Change has been generated in each case and the information in the NODC is correct.
- [ ] **NEW FUNCTIONALITY** - When there are multiple paper petitioners in the consolidated group, the Print for paper service page now combines each NODC + address coversheet for each case into one document for printing on the print for paper service page. 


*Repeat this test but edit the other fields on the QC screen generate a NODC 
- [ ] Lodged
- [ ] Additional info 1
- [ ] Additional info 1 + the Add to coversheet checkbox
- [ ] Additional info 2
- [ ] Attachments
- [ ] Certificate of Service
- [ ] Filed By
- [ ] Add to Pending Report (this checkbox/section will be on any document besides proposed stips, motions, applications) - Pending item is created in each member case and displays on Pending report.

*Repeat this test but click Complete and Send Message button.



#### 7) Docket clerk accesses a member case where a Petitioner has filed a document across the group, No "Complete QC" link is available from the document preview.

- Make sure that you have filed a document across a consolidated group as a petitioner user 
- Log in as a Docket Clerk
- Click on the Document QC Header
- Click on Section Document QC
- Click on the docket number for one of the member cases on one of the Petitioner filings that filed across a consolidated group (not the document title)

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The document that was filed across the group has a red star next to it, indicating that it has not yet been QC'd
- [ ] After clicking on the document link, the document preview page opens
- [ ] **NEW FUNCTIONALITY** - There is no "Complete QC" link at the top of the Document Preview for the member case.

*Repeat the steps above by checking all of the member cases in the group to ensure that there is no "Complete QC link."



#### 8) Petitioner files a document in a consolidated group that is assigned to a Judge; Judge views their Document QC tab; Filings made across a consolidated group now display as a singular QC item with all the cases the document was filed in also displayed. 

**Preconditions**
- Be sure that a Petitioner user has filed a document across a consolidated group that is assigned to a Judge


- Log in as a Judge User
- Click on the Document QC tab
- Review the Petitioner's consolidated case filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Document QC view for the filing made across the group. (Check this on the My Document QC and Section QC Inbox views)
- [ ] **NEW FUNCTIONALITY** - Each docket number that the document was filed in is displayed in the singular QC item in the display (see mock) (Check this on the My Document QC and Section QC Inbox views)
- [ ] **NEW FUNCTIONALITY** - Lead Case and Member case icons are displayed, with the lead case docket number listed first.
- [ ] **NEW FUNCTIONALITY** - Each case in the consolidated group has a document filed displayed as not QC'ed as per normal (red star) when viewed on the docket record.


*Repeat the test above, but with a Chambers user



#### 9) Docket clerk edits a document in a lead case that was multi-docketed; New alert is displayed on the Edit Docket Entry screen.

- Navigate to a lead case that had a document that was multi-docketed, and that you already QC'd.
- Click on the Edit link from the docket record

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new alert at the top of the page (see mock)
- [ ] **NEW FUNCTIONALITY** - Alert includes all the cases + petitioner names that the document will be edited for.

*Note: If you are editing a multi-docketed Simultaneous doc, you will have to Serve the document first. (this will still generate multiple coversheets (see other story that addresses this behavior). After they are all served, THEN you can edit the document



#### 10) Docket clerk makes an edit to the Document information on a document in the lead case; Edits made are reflected on all cases in the consolidated group.

- Continuing from the previous test
- Make an edit to the filed Date 
- Click Save
- Review the Docket Record

Expected Results:
- [ ] The date Filed on the Lead case's docket record has been updated to reflect the date that you updated
- [ ] The document has a new coversheet with the new date filed
- [ ] **NEW FUNCTIONALITY** - The document filed date on each member case's docket record has also been updated to match the edit made on the Lead case.
- [ ] The page count for each document on each case in the group has been updated appropriately
- [ ] No notice of docket change created for editing as per normal

*Repeat the test above, but edit the other fields on the Document Info tab and review the data on the docket record

- [ ] Document Type
- [ ] Additional info 1
- [ ] Additional info 1 + the Add to coversheet checkbox
- [ ] Additional info 2
- [ ] Attachments
- [ ] Certificate of Service
- [ ] Filed by
- [ ] Add to Pending Report (this checkbox/section will be on any document besides proposed stips, motions, applications) - Pending item is created in each member case and displays on Pending report.
- [ ] Change the filing status from Lodged to Filed and you should have the Expected Results from above
     - Note that changing from Filed to Lodged does not currently add a new coversheet, but changing the filing status from Lodged to Filed DOES

**DEV Question**
- what would we expect to happen if we make an edit to a document on a lead case that was filed across the group? Do we see this new alert and the behavior outlined in the above test case?



#### 11) Docket Clerk makes an edit on the Service tab on a document in the lead case; Edits made are ONLY in the lead case and are NOT reflected on the member cases in the consolidated group.

- Navigate to a lead case that had a document that was multi-docketed, and that you already QC'd.
- Click on the Edit link from the docket record
- Ensure that there is the new alert as described in test case 9
- Click on the Service tab
- Change the service party
- Click Save

Expected Results:
- [ ] The Served parties code on the docket record of the lead case has been updated to reflect the changes that you made
- [ ] The Served parties code on the docket record of all of the member cases has NOT been updated, and remains as it was from the original filing.





#### 12) Docket Clerk clicks the edit link for a document that was multi-docketed on a member case in a consolidated group; New alert is displayed and the data fields on the Document Info tab are disabled.

- Navigate to a member case that had a document that was multi-docketed, and that you already QC'd.
- Click on the Edit link from the docket record

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new alert at the top of the page that indicates Edits to the Document info can only be done from the lead case. (see mock)
- [ ] **NEW FUNCTIONALITY** - The data fields on the Service tab and Action(s) tab are still active and can be edited.




#### 13) Docket Clerk makes an edit on the Service tab on a document in a member case; Edits made are ONLY in the member case and are NOT reflected on any of the other member cases or the lead case in the consolidated group.

- Continuing from the previous test
- Click on the Service tab
- Change the service party
- Click Save

Expected Results:
- [ ] The Served parties code on the docket record of the member case has been updated to reflect the changes that you made.
- [ ] The Served parties code on the docket record of all of the other member cases have NOT been updated, and remains as it was from the original filing.



#### 14) Docket Clerk makes an edit on the Action(s) tab on a document in the lead case; Edits made are ONLY in the lead case and are NOT reflected on the member cases in the consolidated group.

- Navigate to a lead case that had a document that was multi-docketed, and that you already QC'd.
- Click on the Edit link from the docket record
- Ensure that there is the new alert as described in test case 9
- Click on the Action(s) tab
- Add in some Action text.
- Click Save

Expected Results:
- [ ] The information that you typed now displays in the action column on the docket record of the lead case.
- [ ] The information that you typed in the Action field does NOT display on the docket record of all of the member cases, and remains as it was from the original filing.



#### 15) Docket Clerk makes an edit on the Action(s) tab on a document in a member case; Edits made are ONLY in the member case and are NOT reflected on any of the other member cases or the lead case in the consolidated group.

- Navigate to a member case that had a document that was multi-docketed, and that you already QC'd.
- Click on the Edit link from the docket record
- Ensure that the alert is present as described in Test Case 12.
- Click on the Action(s) tab
- Add in some Action text.
- Click Save

Expected Results:
- [ ] The information that you typed now displays in the action column on the docket record of the member case.
- [ ] The information that you typed in the Action field does NOT display on the docket record of any of the other member cases or the Lead case, and remains as it was from the original filing in the other cases.



#### 16) Docket clerk processes an Order in the lead case in the Consolidated group and serves it across the group; Filings made across a consolidated group now display as a singular QC item with all the cases the document was filed in displayed on the Processed tab of the QC display.

- Log in as a Judge or ADC user
- Navigate to the Lead case in a consolidated group 
- Click on Create and Select Order or Notice
- Select Order and click ok
- Click on the Add docket numbers and select all in the group
- Draft an order
- Save it and add a signature
- Log in as a Docket Clerk
- Navigate to the Lead case in a consolidated group that you just drafted the order in.
- Click Add Docket Entry
- Select Served radio button
- Click Save and Serve
- Select all cases in the group

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Document QC processed view for the Order that was filed across the group. (Check this on the My Document QC and Section QC Processed views)
- [ ] **NEW FUNCTIONALITY** - Each docket number that the Order was filed in is displayed in the singular QC item in the display (see mock). (Check this on the My Document QC and Section QC Processed views)
- [ ] **NEW FUNCTIONALITY** - Lead Case and Member case icons are displayed, with the lead case docket number listed first.
- [ ] **NEW FUNCTIONALITY** - Each case in the consolidated group has the Order filed. 



#### 17) Docket clerk processes an Order in the lead case in the Consolidated group and saves (does not serve); A singular row is displayed on the In Progress tab, and only displays the Lead case docket number; Order is not displayed on any member case in the group as per normal.

- Log in as a Judge or ADC user
- Navigate to the Lead case in a consolidated group 
- Click on Create and Select Order or Notice
- Select Order and click ok
- Click on the Add docket numbers and select all in the group
- Draft an order
- Save it and add a signature
- Log in as a Docket Clerk
- Navigate to the Lead case in a consolidated group that you just drafted the order in.
- Click Add Docket Entry
- Select Served radio button
- Click Save (do not serve)

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Document QC In Progress view for the Order that was saved to the Lead Case. (Check this on the My Document QC and Section QC in Progress views)
- [ ] **NEW FUNCTIONALITY** - Only the Singular docket number that the Order was saved in is displayed on the In Progress view. (Check this on the My Document QC and Section QC in Progress views)
- [ ] **NEW FUNCTIONALITY** - Lead Case icon is displayed, no other icons
- [ ] **NEW FUNCTIONALITY** - The Order is only saved to the Lead case, it is not saved to the docket record of any of the member cases.



#### 18) Docket clerk processes a paper filing in the lead case in the Consolidated group and serves it across the group; Filings made across a consolidated group now display as a singular QC item with all the cases the document was filed in displayed on the Processed tab of the QC display.

- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group
- Click the Create button
- Select Paper Filing
- Upload a document and fill out the required fields
- Click Save and Serve
- Select all cases in the group
- Click Serve
- Print for paper service if appropriate
- Click on the Document QC Tab
- Click on the Processed Tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is now only a singular QC item in the Document QC processed view for the paper filing that was filed across the group. (Check this on the My Document QC and Section QC in Progress views)
- [ ] **NEW FUNCTIONALITY** - Each docket number that the paper filing was filed in is displayed in the singular QC item in the display (see mock). (Check this on the My Document QC and Section QC in Progress views)
- [ ] **NEW FUNCTIONALITY** - Lead Case and Member case icons are displayed, with the lead case docket number listed first.
- [ ] Each case in the consolidated group has the paper filing filed. 




#### 19) Docket clerk processes a paper filing in the lead case in the Consolidated group and saves (does not serve); A singular row is displayed on the In Progress tab, and only displays the Lead case docket number; paper filing is not displayed on any member case in the group as per normal.

- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group
- Click the Create button
- Select Paper Filing
- Upload a document and fill out the required fields
- Click Save for later
- Click on the Document QC Header
- Click on the In Progress tab

Expected Results:
- [ ]There is only a singular QC item in the Document QC In Progress view for the paper filing that was saved to the Lead Case (Check this on the My Document QC and Section QC in Progress views)
- [ ] Only the Singular docket number that the Paper filing was saved in is displayed on the In Progress view.(Check this on the My Document QC and Section QC in Progress views)
- [ ] Lead Case icon is displayed, no other icons
- [ ] The paper filing is only saved to the Lead case, it is not saved to the docket record of any of the member cases.



#### 20) Test with other users

- [ ] Tests above pass when filings are from Private Practitioners
- [ ] Tests above pass when filings are from IRS Practitioners/DOJ Practitioners
- [ ] Tests above pass when QC/Edits are completed by CotC user
- [ ] Tests above pass when QC/Edits are completed by CSS user



#### 21) Regression stuff

- [ ] Sealing documents must still be done on an individual case/document basis
- [ ] Check the Postgres database for all consolidated filings - ensure things are created/updated/completed as they should be.

**Comment by zachrog** [comment]
Putting back to In Progress to focus on Postgres migration
