### ISSUE TITLE
Custom Case Report: Add "All Cases" Option 

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#10172]
As a Court user, to make it simpler to ensure I'm searching all cases in the system, I want an option to indicate that I need to search all cases.

The CCR has proven to be invaluable to Court users in datamining our case inventory in DAWSON. Currently, if one wishes to search the set of all cases in the system they must enter a date range that ensures the Start Date predates the earliest case filing date in DAWSON.

To make this search simpler to execute, we would like a way for the user to indicate that they want to search the entire collection rather than have to input a date range.
 
## Acceptance Criteria
* Instead of inputting a date range prior to running the Custom Case Report, a user can indicate that they wish to search all cases in DAWSON
* User can de-select indicator and enter a date range as usual prior to running the report
* When a user indicates they wish to search all cases in DAWSON they cannot input a Start/End date - either the indicator is set OR a date range is entered
* User can select additional report criteria after indicating they wish to search all cases prior to clicking Run Report
* When running a report after indicating they wish to search all cases, report captures result set using all cases in the system combined with any additional selected or defaulted criteria

## Tasks
- [x] Add radio button for all dates (UI adjustments)
- [x] Adjust API to work without date ranges
- [x] Verify validation works for when entering dates
- [x] Add/Update appropriate tests
- [x] Question(s) for UX: Do we need to add a "All Dates" radio button because we can search for all cases without the date ranges prescribed

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement 
- All cases is default?
- Why are they searching all cases? versus a subset?  Is the problem more a 'they're usually searching for all so having to click into the date range selector is a lot of extra clicks' or 'we don't understand how to use the date range selector'?
-

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Custom Case Report; Search date range and Search all dates radio buttons are present at the top of the page.

- Log in as any Court User
- Click on the Reports menu
- Select Custom Case Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - There are now two radio buttons at the top of the page
 - [ ] **NEW FUNCTIONALITY** - One radio button states "Search date range" and has the case created start date field and Case created end date field next to it
 - [ ] **NEW FUNCTIONALITY** - One radio button displays "Search all dates"
 - [ ] **NEW FUNCTIONALITY** - The Search date range is selected by default


#### 2) Court user selects for "Search all cases" radio button; Runs report; results include all cases.

- Continuing from the previous test
- Click on the "Search all dates" radio button

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - User cannot input dates in the date fields (dev determination on this one - can the fields be disabled? Also, need to determine how this reacts with a screen reader if fields are disabled)



#### 3) Court user adds filters; Runs Report; results list displays filtered list appropriately.

- Continuing from the previous test
- Select a filter (or not) and click run report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays all cases appropriately (depending on the filters (or no filters) selected



#### 4) Court user selects the Search date range radio button and adds a date range; Runs Report; results list displays cases within the date range appropriately.

- Continuing from the previous test
- Click on the Search date range radio button
- Add valid dates
- Select a filter (or not)
- Click Run Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays all cases appropriately (depending on the filters (or no filters) selected).


#### 5) Court user selects the Search all dates; dates that were previously entered in the date range fields clears from display.

- Continuing from the previous test
- Click on the Search all dates radio button.


Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The dates that were input in the date fields are cleared from display.
 - [ ] **NEW FUNCTIONALITY** - User can add filters or run the report and the results are displayed appropriately.

**Comment by swongCO** [comment]
Updated UX notes based on convo with devs re complexity of previous design.

**Comment by cholly75** [comment]
@swongCO @katiecissell @ttlenard - court users liked the functionality but agreed that the instructions/design felt a little "off". If we're going to go with this solution in place of the original AC to reduce complexity then we want to either position the date fields as optional or filters in line with the rest of the UI or rationalize the UI/mechanism with the other date field selection options in the app.

**Comment by ttlenard** [comment]
Test cases in this story were written for the original design, so I was unable to complete the test cases above. I did test functionality as deployed, and it appears that the search is functioning appropriately.

I was able to search all dates (by not inputting anything), with only a start date, with only an end date, or with a date range.  I was also able to trigger validation errors on the date fields as appropriate.
