### ISSUE TITLE
Ignore Username Case Sensitivity On Login

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#10208]
As a DAWSON user, so that I can easily access DAWSON, I need the username field to ignore case sensitivity when logging in.

In #10007 we established a new hosting page for logins to DAWSON. To complete this functionality we would like to make logging into the system smart enough to recognize and authenticate a user when the only difference between the input name and the stored name is the character case.

To this end, we would like to parse usernames logging into the system in a manner that allows us to retrieve and log in a user who types in a valid username and password even if there are differences in the capitalization between the input name and the stored name.

## Pre-Conditions
#10007

## Acceptance Criteria
* User can log into DAWSON with valid username/password combination even when there are differences in capitalized characters between the input username and the stored username
* Users entering an exact match between input username and stored username with the correct password are logged in as normal
* Ensure data is normalized as per notes section below

## Notes
* Do we need to figure out how to resolve the following scenario?
TESTUSER@example.com/12345 exists
testuser@example.com/12345 exists

User enters TestUser@example.com/12345

* Feedback from @mmarcotte :

1. We need to perform cleanup outside of the scope of this story. I know I've run a full report on every user that has a duplicate account.
2. From that report, I'm optimistic that we can remove all but a very small handful of duplicate accounts that were created in error. These would be accounts where there is a Practitioner record and a Petitioner record, and there really should be no practitioner record.
3. If there happens to be two of the same type of record that both have cases, we should consolidate those.

User gets logged into whichever one of those it attempts to authenticate first.
Attempt to login TestUser@example.com/12345
Fail
Get users matching TestUser@example.com
Found 2, TESTUSER@example.com, testuser@example.com
Attempt to login TESTUSER@example.com/12345
Success!

## Tasks
- [ ] Refactor cognito so every account has and can be looked up by custom:userId. 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] Code that resides in the shared folder that only runs on the API or browser has been moved to either /web-client or /web-api.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User creates and verifies a new petitioner account; On login, user types in different capitalization for the email, User can log in successfully.

**PART 1**
- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all lower-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all capital letters (this is different than when you signed up - you should have used all lowercase.)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**PART 2**
- Repeat the above steps, but instead of all capital letters, use a combination of lower case/upper case.

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.



#### 2) Regression test - User creates and verifies a new petitioner account; On login, user types in the same capitalization for the email, User can log in successfully.

- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all lower-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all lowercase (matching how you input it on account creation)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [ ] User can log in to DAWSON successfully


#### 2) Regression test - Ensure that Passwords are still case sensitive.

- Repeat test 1 but at the Password step, input a password that is in a different case
- Click Log in

Expected Results:
- [ ] User cannot log in.



#### 3) Regression test - User creates a new account, Inputs their username with all capital letters; On log in, user can log in to DAWSON capitalization.

**PART 1**
- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all upper-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all lower-case letters (this is different than when you signed up - you should have used all uppercase.)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**PART 2**
- Repeat the above steps, but instead of all capital letters during account creation, use a combination of lower case/upper case.

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**Comment by jtdevos** [comment]
I've researched the cognito documentation and had a couple conversations w/ Tom & Jim about the issue.  Capturing my notes here so I don't forget.

- Regarding migrating to new cognito user pool 
	- Our cognito user pools are case-sensitive, which was the default when we created them.  
	- There is no way to enable/disable case sensitivity on existing pool.  The only option is to create a new pool with the desired configuration and then to migrate accounts from the old pool to the new pool.
	- To my knowledge, these are the only ways to perform a migration:
		- using a "Migrate user lambda trigger". (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html). AWS invokes this lambda when a user atttempts to log in but cognito does not find the requested user in the user pool. Upside: AWS retains credentials and user does not need to reset password.   Downside: There is no way to perform this type of migration in bulk. So we would presumably double the number of cognito user pools: one set of new case insensitive pools, and a legacy set that only serves as a reference for the migrate lambda.
		- Bulk import CSV into cognito. Upside: can be done as one-time operation.  Downside: effectively resets all user account passwords.
		- Bulk import using Cognito API/SDK. Here we would just be using API calls to get the list of users from the old pool and then using API calls to add them to the new pool.  Same downside: effectively resets user account passwords.
	- Given the above, in my opinion the best bet is to simply implement case-insensitivity in-app (as described by the ticket).  But I don't have strong feelings about it yet as I have more to learn about this ticket.
	- Per a chat w/ Jim L., I beleive that some work has already been done in terms of identifying "dupe" accounts (i.e. accounts that resolve to the same down-cased value).  But I'm less clear if we have performed any de-duping yet.

**Comment by jhansen-flexion** [comment]
Per Chris on 4/7:  proceed with implementing the lower-case solution on the front end and keeping our existing Cognito user pool.

**Comment by zRogersFlexion** [comment]
## Deployment Steps:
- Use the environment switcher to point to the deploying environment.
- Run an account specific deploy:
`npm run deploy:account-specific`
- Run the migration script:
`npx ts-node --transpile-only scripts/run-once-scripts/cognitoUserIdAndEmailMigration.ts`
- Kick off Circle deploy

**Comment by rachelschneiderman** [comment]
@cholly75 @ttlenard @mmarcotte Reminder that ZenDesk automations need to be updated to remove "usernames are case sensitive" language before this story is deployed

**Comment by mmarcotte** [comment]
Hey just a quick note that we have a mixed case caseServicesSupervisor1 in `users.json` that you will likely need to lowercase
