### ISSUE TITLE
SPIKE::  Petitions & Docket: Ability for court users to scan paper documents directly into the system 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1066]
As a Petitions Clerk or Docket Clerk, in order to make sure the right document gets uploaded, I need the ability to scan paper documents directly infor the system.

The Court will continue to receive paper Petitions and other paper filings.  As a result, Petitions Clerk and Docket Clerks will need the ability to get those paper documents into the system.  The idea that a clerk would scan, save, and upload the document leaves a lot of room for error that the wrong document will be uploaded.  Plus, it involves multiple steps.  To avoid this, the Petitions Clerks and Docket Clerks will need the ability to directly scan a document into the system.

## Pre-Conditions:
* Petitions Clerk or Docket Clerk has paper filing

## Acceptance Criteria:
* Petitions Clerk or Docket Clerk has the ability to scan paper documents directly into the system without having to perform a separate scan, save and upload function. [See note re: multiple scans for large documents]
* The Petitions Clerk or Docket Clerk can see that the document has been scanned successfully into the system

## Notes:
* Implementation/design will be handled in other stories: #1895 for Petitions Clerk and #1896 for Docket Clerk
* Cody recommended a web-based solution during our 3/12/19 design meeting.
https://www.dynamsoft.com/Products/WebTWAIN_Overview.aspx
* If Flexion recommends that the Court use a COTS product for this functionality, that will need to get Court approval.  The Court would need Flexion to provide a recommendation that includes: (1) that Flexion is recommending a certain COTS product and why (i.e., it performs the exact functionality we need; the time it would take to build it is cost-prohibitive, etc.); (2) a statement that there is no equivilant product available from open source software; and (3) the expected expense to the Court for the COTS product.

## Tasks ##
- [x] Research licensing for third-party software (Matt)
- [x] Proposal to Court for purchasing of software (Matt - GoogleDocs)
- [x] Replacing/hosting files (standing up server to serve third-party files) (Cody #1909)
- [x] Deploy method for third party files  (Cody #1909)
- [x] Scanner library implementation in the web app (Matt #1919)
- [x] Generation of PDF from scanner data (Matt #1919)
- [x] Store scanner device preference (Matt #1919)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**Engineering**
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by matthopson** [comment]
@sarahridgway Here are soome screenshots / notes around scanning documents into the system:

If you've never installed the desktop application that allows the communication to take place, this modal will show up. This is loaded via Dynasoft, so we aren't really in direct control re: how it looks or when it pops up - this is something I would like to learn more about, though.
![Screen Shot 2019-05-27 at 12.32.17 PM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/e9ad60f2-c8da-4903-87b5-3791eb124201)

It's really nice to treat the scanning function just as we treat the file upload input for now. The rest of the form and underlying code doesn't really have to change if we go with this approach, as the the application will treat the data in the form the same whether it came from the file system or a scanner. For this initial implementation, this simplifies things, and keeps dev effort in implementing this quite lean.
![Screen Shot 2019-05-27 at 12.33.51 PM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/ce16ddc9-077c-49b9-9744-2747b3de852e)

You will need to select a scanner when you start a new job. We should be able to store some kind of preference on the user's browser, so they'll only have to select their scanner once (unless they clear their cache). If we automatically persist their selection, we may need to think about giving them a way to change it.
![Screen Shot 2019-05-27 at 1.24.10 PM.png](https://images.zenhubusercontent.com/5cadf
168c7e4b91e9a637015/9a48a116-3ba4-4c74-b350-8335c4a59cde)

I'm including this screenshot because it raises a very large concern (of mine) with using this software. We're giving them access to the DOM where they can show popups we have no control over. I can't disable this modal - I can't close it. All I can do is refresh the page, which could cause this modal to show again.
![Screen Shot 2019-05-27 at 1.24.36 PM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/667c29de-9ed3-4835-9979-370db536a932)
