### ISSUE TITLE
Court: Each party needs to have a service indicator

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1072]
As the Court, in order to make sure each party is getting served in the appropriate manner, each party needs to have a service indicator.

Each party to a case should have a service indicator (Electronic, Paper, None).  When a party initiates a case electronically, their default service should be electronic service.  When a party initiates a case in paper, their default service should be paper service.  

## Pre-Conditions
* A case has been created with a party associated to it

## Acceptance Criteria
* Each party to a case needs to have a service indicator at all times 
* The service indicator options are Electronic, Paper, or None.
* When a Petitioner starts a case in paper, their service indicator should default to Paper.
* When a Petitioner starts a case electronically, their service indicator should default to Electronic.
* When a Practitioner starts a case electronically, their service indicator should default to Electronic and the Taxpayer's service indicator should default to None.
* When a Practitioner starts a case in paper, their service indicator should default to Electronic (if they have an account) and Paper (if not)  and the Taxpayer's service indicator should default to None. 
* The service indicator for IRS attorneys should always default to Electronic. 
* The service indicator needs to be easily viewable to all other parties.

## Notes
* This story doesn't not include editing the indicator, which is handled in #1130.

## Tasks
 - [x]  Encapsulate SI logic into function with tests (Matt #2837)
 - [x]  Implement SI Logic in Case Detail (Joe #2838)
 - [x]  Update UI (Joe #2838) 

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo #2842)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by sarahridgway** [comment]
## Service Indicator

The service indicator displays a party's service method preference.

For more examples, see the USTC For Devs Figma File

### Internal View

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/261301a4-ec66-4b97-8e5f-5f981413b389)

### Petitioners View

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/47479495-df48-4400-9efa-e03740299097)


### Determining the Service Type

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/0d2b9535-2add-46d5-925d-3138f874cbe9)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/f99308d2-5cad-41e8-9763-145c2eedfff7)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/cf8302e4-b456-4b9a-9e67-7c496ed00d66)

**Comment by sarahridgway** [comment]
Test Scenario

* Docket Clerk / Petitioner / Practitioner / Respondent logs in
* Sees dashboard
* Navigates to a case
* Sees case detail page
* Clicks Case information tab
* Sees service preference for all parties

All petitioner / practitioner relationship scenarios will have to be tested

**Comment by sarahridgway** [comment]
Cases to Create:

* Paper | 1 Petitioner (Paper)
* Paper | 2 Petitioners (Paper | Paper)
* Paper | 1 Petitioner (None) | 1 Practitioner (Electronic)
* Paper | 2 Petitioners (None | None) | 1 Practitioner (Electronic) (representing both parties)
* Paper | 2 Petitioners (None | Paper) | 1 Practitioner (Electronic) (representing primary party)
* Paper | 2 Petitioners (Paper | None) | 1 Practitioner (Electronic) (representing secondary party)
* Paper | 2 Petitioners (None | None) | 2 Practitioners (Electronic | Electronic) (representing 1 party each)

* Electronic | 1 Petitioner (Electronic)
* Electronic | 2 Petitioners (Electronic | Paper)
* Electronic | 1 Petitioner (None) | 1 Practitioner (Electronic)
* Electronic | 2 Petitioners (None | None) | 1 Practitioner (Electronic) (representing both parties)
* Electronic | 2 Petitioners (None | Paper) | 1 Practitioner (Electronic) (representing primary party)
* Electronic | 2 Petitioners (Electronic | None) | 1 Practitioner (Electronic) (representing secondary party)
* Electronic | 2 Petitioners | 2 Practitioners (Electronic | Electronic) (representing 1 party each)

* Add respondent to any case, should always be electronic
