### ISSUE TITLE
Docket Clerk: Edit Case Information

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1129]
As a Docket Clerk, in order to change case metadata, I need the ability to edit the information in the Case Information tab.

When a Docket Clerk is reviewing an incoming document, there might be the need to update case metadata based on the filing.  The Docket Clerk needs the ability to edit all case metadata on the Case Information tab.

## Pre-Conditions:
* Incoming filing (other than a Petition) has been routed to Docket Section.

## Acceptance Criteria
* Docket Clerk [permissions based] must have the ability to modify any case metadata on the Case Information tab: Notice/Case Type, Case Procedure, IRS Notice Date, Requested Place of Trial, Party Type, Petitioner's Contact Information.  Note: Changing Service Preference is addressed in #1130
* If the Docket Clerk changes the Notice/Case Type or Case Procedure type, the Docket number should automatically update, if necessary [NOTE: this should *not* create a Minute Entry on the docket record; that logic should be broken after Petition QC process; this will be preceded by an Order after the Petitions QC process #3920]
* If the Docket Clerk changes the contact information for any petitioner in the case, that updated contact information should be viewable to all parties and internal users.
* If the Docket Clerk changes the contact information for any petitioner in the case, that should automatically generate a Notice of Change of Address/Phone Number/Both. [Note: consider how to handle attorneys who may be in more than 1 case] 

## Notes
* If court changes address, also needs to generate a change of address
* For MVP, we don't need the ability to change practitioner's, attorney's or respondent's information at the case level

## Tasks
- [x] 1 Remove "Party Type" field from Case Detail > Case Information > Overview and add to Case Information -> Petitioner tab (Rachael #4052)
- [x] 2 Update Edit Petition Details screen with new fields (Rachael #4052)
- [x] 3 Modify existing interactor/sequence (updatePetitionFeePaymentSequence/Interactor) to modify new fields (Rachael #4053)
  - [x] 3a If case type or case procedure are updated, the docket number should automatically update if needed (Rachael #4053)
- [x] 4 Check form validation (see error messages in story comment) (Rachael)
- [x] 5 Add Edit button to Petitioner Information card for internal users (Cody #4056)
- [x] 6 Create Edit Petitioner Information route and view (Cody #4056)
- [x] 7 Endpoint to submit petitioner information (Kris)
  - [x] 7a If address and/or phone was updated, generate Notice of Change of Address
- [x] 8 Sequences and actions to submit petitioner information (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Case Detail > Case Information > Overview 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bfd11f29-ca65-41ba-ac45-4e5ba241a44f)

* Remove "Party Type" field 

### Updated- Edit Petition Details screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7832d2dd-bb2f-4daf-a305-2f67e63368ac)

**Type of Case**
* Field is populated with current case type 
* Field is required 
* Error message if incomplete: "Select a case type" 

**Date of Notice**
* Field is populated with current date of notice (from Petition QC) 
* Field is optional 
* Date cannot be in the future: Error message "The IRS notice date cannot be in the future. Enter a valid date."

**Case Procedure**
* Field is populated with current case procedure 
* Field is required : Error message if incomplete: "Select a case procedure" 

**Requested place of trial**
* Field is populated with current requested place of trial 
* Field is optional 

**On Save**
* Navigate back to Case Information > Case Overview tab 
* Success message displays 
* If Case Type was updated, docket number is automatically updated accordingly 
* If Case Procedure was updated, the Docket number should automatically update accordingly 

**On Cancel**
* Navigates back to Case Information > Case Overview tab 

### Updated Case Information > Petitioner tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e64ddd40-9001-4cf3-a5cb-fdd6b5eec343)

* Add "Party Type" field to Petitioner Information card 

### Edit Petitioner Information (new screen) 
* On click of Edit from Petitioner card, navigate to Edit Petitioner Info screen 

**Party Type**
* Field is populated with current party type
* Field is required - Error message : "Select a party type" 
* Party type drives the petitioner contact fields (refer to Create Case form) 

**On Save**
* Navigate back to Case Information > Petitioner tab with success message "Your changes have been saved"
* Updated contact information is displayed 
* If address and/or phone was updated, generate Notice of Change of Address (refer to #2146 https://github.com/flexion/ef-cms/issues/2146)

**Comment by klohman** [comment]
### 1129 Test Scenarios 

Create Case 1 as petitioner 1 
* Case procedure - Regular 
* Case type - Deficiency 
* Requested place of trial - Denver, CO 
* Party type - Petitioner 

#### 1) Docket clerk edits petition details 
* Login as docket clerk 
* Navigate to Case Detail > Case Info > Overview 
* Click Edit 
* Change Requested place of trial to Washington, DC 
* Click Save 
Expected results 
- [ ] Navigates to Case Info > Overview tab with success message displayed 
- [ ] Requested place of trial displays as Washington, DC 

#### 2) Docket clerk edits case type 
* Login as docket clerk 
* Navigate to Case 1
* Click Edit 
* Update Case type to Whistleblower 
* Save 
Expected results 
- [ ] Navigates to Case Info > Overview tab with success message displayed 
- [ ] Case type displays as Whistleblower 
- [ ] Docket number displays as xxx-20W


#### 3) Docket clerk edits case procedure 
* Login as docket clerk 
* Navigate to case 1 > Case Information > Overview 
* Click Edit 
* Update case procedure to Small 
* Save 
Expected results 
- [ ] Navigates to Case Info > Overview tab with success message displayed 
- [ ] Case procedure displays as “Small” 
- [ ] Docket number displays as xxxx-20S


#### 4) Docket clerk edits party type 
* Login as docket clerk 
* Navigate to case 1 > Case Information > Petitioner 
* Click edit 
* Update party type to petitioner and spouse 
* Complete form 
* Save 
Expected results 
- [ ] Navigates back to case 1 > Case Information > Petitioner with success message displayed 
- [ ] Party type displays as Petitioner and Spouse 
- [ ] Updated petitioner and spouse contact information displays 

#### 5) Docket clerk edits petitioner address
* Login as docket clerk 
* Navigate to case 1 > Case Information > Petitioner 
* Click edit 
* Change petitioner address 
* Save 
Expected results 
- [ ] Navigates back to case 1 > Case Information > Petitioner with success message displayed 
- [ ] Updated petitioner address displays 
- [ ] Notice of Change of Address is generated on docket record 

#### 6) Docket clerk edits petitioner phone number 
* Login as docket clerk 
* Navigate to case 1 > Case Information > Petitioner 
* Click edit 
* Change petitioner telephone number 
* Save 
Expected results 
- [ ] Navigates back to case 1 > Case Information > Petitioner with success message displayed 
- [ ] Updated petitioner address displays 
- [ ] Notice of Change of Telephone Number is generated on docket record 

#### 7) Docket clerk edits petitioner address and phone number 
* Login as docket clerk 
* Navigate to case 1 > Case Information > Petitioner 
* Click edit 
* Change petitioner address and phone number
* Save 
Expected results 
- [ ] Navigates back to case 1 > Case Information > Petitioner with success message displayed 
- [ ] Updated petitioner address displays 
- [ ] Notice of Change of Address and Telephone Number is generated on docket record

**Comment by Tinabuck5** [comment]
We have tested  cases 118-20 and 119-20.  We changed the place of trial, changed both petrs. address and phone number and the appropriate docket entries and cover sheets appeared,  changed the type of case from Regular to Small, added a IRS notice date date, added the payment of a filing fee, changed the deficiency type, and changed the party type.  All of these worked fine.  
We were not able to change the service preference.  We would need to do this if we are ordered to do so or if petitioner is banned from electronic service. We couldn't test adding IRS counsel bar number because I believe that there are no valid bar numbers in the test system yet.

**Comment by klohman** [comment]
@Tinabuck5 Changing the service preference is part of a separate story.

**Comment by Tinabuck5** [comment]
Oh okay.  Then everything looks good! :)

**Comment by Tinabuck5** [comment]
Kristin,

   Could you refresh my memory, how long do the messages stay in my box after I complete them.  I know that there was some mention of this.  The number of messages reduces once completed but the message remains.  I think that here was a set number of days or something.  Please advise.  Thanks
