### ISSUE TITLE
Docket Clerk: Edit Service Indicator

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1130]
As a Docket Clerk, in order to make sure that each party gets served in an appropriate manner, I need to be able to update a party’s service indicator.

When a party initiates a case electronically, their default service is electronic service.  When a party initiates a case in paper, their default service will be paper service.  However, over the life-cycle of a case, a party may want to change how they get service.  In order to make sure that each party is getting served in an appropriate manner, a Docket Clerk needs the ability to update a party’s service indicator.

## Pre-Condition:
•	Each party has a service indicator (#1072)

## Acceptance Criteria:
* The Docket Clerk must be able to change the service indicator on each party (from electronic to paper or electronic/paper to non only; paper to electronic will be post MVP.)
* Changing the service indicator for one party does not affect service indicator for other parties
* The options for service indicator for each party should be Electronic, Paper, None

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Changing service indicator from paper to electronic out of scope? concerns with party registration and jurisdiction. 

## Tasks
- [x] 1 Add Service Information to Edit Petitioner Information screen (Rachael #4223)
- [x] 2 Update interactor to edit petitioner’s service information (Rachael #4223)
- [x] 3 Create action to validate that they are not going from paper/none to electronic (All #4230)
- [x] 4 Allow service indicators to be stored on the user objects (petitioner, practitioner, and respondents) (Cody, Rachael)
- [x] 5 Update setServiceIndicatorsForCase to check for a service indicator for each user (Cody, Rachael)
- [x] 6 Add Service preference to Add/Edit Petitioner/Respondent counsel modals  (Cody #4222)
- [x] 7 Update interactor for adding/editing counsel to set service indicator (Cody #4222)
- [x] 8 Create Service preference component (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Edit Petitioner Information 

**Service Information** 
* Add Service preference field 
* Field is required 
* If clerk changes service preference from paper to electronic, display error message: "You cannot change from paper to electronic service. Select a valid service preference." 
* On Save, navigates to Case Detail > Case Information and success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e3ec0a7c-4a1e-4734-b7b0-e3fa844973d2)


#### Add Petitioner Counsel 

* Add Service preference field 
* Field is required 
* If clerk changes service preference from paper to electronic, display error message: "You cannot change from paper to electronic service. Select a valid service preference." 
* On Add to Case, modal closes and success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/084ab5a6-3faa-4cbf-91da-e4137d6cc791)

#### Add Respondent Counsel 

* Add Service preference field 
* Field is required 
* If clerk changes service preference from paper to electronic, display error message: "You cannot change from paper to electronic service. Select a valid service preference." 
* On Add to Case, modal closes and success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0381b49a-528e-47e3-9663-afd721219866)

#### Edit Petitioner Counsel 

* Add Service preference field 
* Field is required 
* If clerk changes service preference from paper to electronic, display error message: "You cannot change from paper to electronic service. Select a valid service preference." 
* On Apply Changes, modal closes and success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/169720a9-bb54-4d2c-8d28-73eca264f62f)

#### Edit Respondent Counsel 

* Add Service preference field 
* Field is required 
* If clerk changes service preference from paper to electronic, display error message: "You cannot change from paper to electronic service. Select a valid service preference." 
* On Apply Changes, modal closes and success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fbbc0ad0-efa6-4c2c-85ac-423699109f3a)

**Comment by klohman** [comment]
- Can we currently have all parties with service = none? 

- Should we be able to change counsel service to electronic since we should have accounts for them? 


### 1130 Edit Service Indicator 

Test data 
- Case 1 
    - Petitioner - e-filed petition 
    - Add practitioner 
    - Add respondent 

- Case 2 
    - Petitioner - paper filed petition 



#### 1) Docket clerk changes petitioner service indicator from electronic to paper 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner info 
* Update service preference to paper 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner displays as “Paper” 
- [ ] petitioner no longer receives email service for future filings 

#### 2) Docket clerk changes petitioner service indicator from electronic to none 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner info 
* Update service preference to paper 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner displays as “None” 
- [ ] petitioner no longer receives email service for future filings 

#### 3) Docket clerk changes petitioner service indicator from paper to none 
* Login as docket clerk 
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit Petitioner info 
* Update service preference to none 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner displays as “None” 

#### 4) Docket clerk cannot change petitioner service indicator to electronic 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner info 
* Update service preference to electronic  
* Click Save 
Expected results 
- [ ] Error message displays on service indicator field 

#### 5) Docket clerk changes petitioner counsel service indicator from electronic to paper 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner Counsel 
* Update service preference to paper 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner counsel displays as “Paper” 
- [ ] petitioner counsel no longer receives email service for future filings 

#### 6) Docket clerk changes petitioner counsel service indicator from electronic to none 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner Counsel
* Update service preference to none 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner counsel displays as “None” 
- [ ] petitioner no longer receives email service for future filings 


#### 7) Docket clerk changes petitioner counsel service indicator from paper to none 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner Counsel 
* Update service preference from paper to none 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for petitioner displays as “None” 


#### 8) Docket clerk changes respondent counsel service indicator from electronic to paper
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Respondent 
* Click Edit Respondent Counsel 
* Update service preference to paper 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for respondent counsel displays as “Paper” 
- [ ] respondent counsel no longer receives email service for future filings 

#### 9) Docket clerk changes respondent counsel service indicator from electronic to none 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Respondent Counsel
* Update service preference to none 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for respondent counsel displays as “None” 
- [ ] respondent counsel no longer receives email service for future filings 

#### 10) Docket clerk changes respondent counsel service indicator from paper to none 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Respondent 
* Click Edit Respondent Counsel 
* Update service preference from paper to none 
* Click Save 
Expected results 
- [ ] App navigates to Case Detail > Case Information with success message displayed 
- [ ] Service indicator for respondent counsel displays as “None” 

#### 11) Docket clerk cannot change counsel service to electronic (TBD) 
* Login as docket clerk 
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit Petitioner Counsel 
* Update service preference from paper to electronic  
* Click Save 
Expected results 
- [ ] Error message displays on service indicator field 

#### 12) Docket clerk updates counsel service indicator when adding counsel to case 
* Login as docket clerk 
* Navigate to Case 2 > Case Information > Petitioner 
* Search for Test practitioner 
* Select paper service 
* Add to case 
Expected results 
- [ ] Modal closes and success message displays 
- [ ] Petitioner counsel service displays as “Paper” 
- [ ] Petitioner counsel does not receive email service for filings
