### ISSUE TITLE
Court: Maximum Upload Size for External Users

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1166]
As the Court, in order to avoid very large documents from being uploaded, we need to set the maximum upload size for external users at 500MB.

The Court may, from time to time, receive *VERY* large documents in a case.  In order to avoid any degradation in service (i.e., opening PDF) and to allow an external filer to upload a document within the 1 hour time-out period, the Court needs to set some reasonable upper-limit for file size limitations.  The Court has decided that limit should be 500MB.

## Pre-Conditions
* External party is filing/uploading a document.

## Acceptance Criteria
* All file uploads by external filers should be limited to 500MB
* The system should prevent the user of uploading a file that is over 500MB
* The system should warn the user if they try to upload something larger than 500MB
* The file upload is not bound by the user activity timeout function (#837)
* User can track the progress of upload
* User can see the estimated time remaining for file upload
* User can cancel upload at any time before the upload is complete
* If a user cancels a document upload or the document upload is unsuccessful, no part of the document or data associated with the document should be saved in the system
* If a user cancels an "Start a Case" upload or the upload is unsuccessful, no case should be generated.

## Notes
* Progress indicator applies to external uploads (petitioner and practitioner) ONLY at this time.

## Tasks
- [x] Add final decision UX wiki regarding global file size, file type and help text requirements
- [x] Make text changes, coming from @sarahridgway
- [x] Add 500 MB limit in the petition entity validation (Joe #1577)
- [x] Add 500 MB limit in the stin entity validation (Joe #1593)
- [x] Add 500 MB limit in the external documents entity validation (Eric)
- [x] Add 500 MB limit in the petition from paper entity validation (Joe #1599)
- [x] add validation error message to all file input views (Eric #1601)
- [x] Limit external file size uploads with S3 policy (Joe #1577)
- [x] trigger sequence to update state with number of bytes uploaded (Cody #1587)
- [x] trigger sequence to update state with time of upload start
- [x] calculate % upload complete (Cody #1587)
- [x] calculate time remaining based on % complete vs time spent uploading (Cody #1587)
- [x] sequence for cancelling an upload (Matt #1606)
- [x] preparing upload modal (Matt #1586)
- [x] % complete upload modal (Matt #1586)
- [x] all done modal (Matt #1586)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by sarahridgway** [comment]
*Progress Indicator*

When an external user initiates a file upload, the user will be presented with an upload progress indicator to show them how much of the file has been uploaded and the estimated time remaining to complete the upload. 

- Appears as a modal overlaid on the user's last actionable page (such as the Filing Review page)
- Background - color: #0071BC $color-primary
- Status message - font: source sans pro; size: 48px; weight: semibold; color: #FFFFFF $color-white
- Percent complete - font: source sans pro; size:32px; weight: bold; color: #FFFFFF $color-white
- Progress bar - bg color: #FFFFFF $color-white | fill color: #4AA564 $color-green-light
- Cancel Upload Link - font: source sans pro; size: 17px; weight: semibold; color: #FFFFFF $color-white; decoration: underline | hover color: TBD decoration: underline

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/8781d9ed-a2da-4228-806b-8cfaff79c3ce)

While the system is calculating the time remaining and otherwise preparing to upload the file(s), the progress indicator shall show the user a "Preparing Upload" status message:

- Status message reads "Preparing Upload"
- Percent complete reads "0%"
- Progress bar is empty
- "Cancel Upload" link ends the upload, closes the modal, shows user last actionable page (for example, the Filing Review page)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/fffa7cbc-cba6-4d6c-91cd-6a78353c16ce)

While the system is uploading the file(s), the progress indicator shall show the user the estimated time remaining to complete the upload and the percent complete:

- Status message reads "[time to complete]" in friendly terms:
-- 1s - 59s = "Less than 1 Minute Left"
-- 60s - 59m = "[x] Minutes Left"
-- 1h+ = "[x] Hours [y] Minutes Left"
- Percent complete reads "[percent_complete]%"
- Progress bar reflects the percent complete
- "Cancel Upload" link persists

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/076aef49-4c1e-4bcf-b36b-8a6df951eb9b)

When the upload(s) have completed, the progress indicator shall show the user the completed status of the file(s): 

- Status message reads "All Done!"
- Percent complete reads "100%"
- Progress bar is full
- "Cancel Upload" link is no longer available
- Show the completed state for 3s then close the modal and load the next page in the flow
-- For Petitions: load dashboard and show success message
-- For other Filings: load the docket record and show success message

(Note: success messages have already been implemented)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/2ff2ef7f-ab94-429a-a7c8-2d85aab9371c)

If an error occurs during the upload process, the progress indicator shall be replaced by an error modal to inform the user of the status of their upload:

- Background - color: #FDB81E $color-gold
- Header - font: source sans pro; size: 48px; weight: semibold; color: #212121 $color-base
- Body - font: source scans pro; size: 30px; weight: semibold; color: #212121 $color-base
- Button Left - primary button style
- Button Right - primary button style

- Header reads "Uh oh!"
- Body reads "An error occurred while uploading your document and it wasn't completed."
- Button Left reads "Try Again" - close error modal, open progress modal and try upload again
- Button Right reads "Cancel Upload" - close modal and return user to the last actionable page

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/bbb19ca2-05ae-4adb-af78-e0d065262c1a)

**Comment by sarahridgway** [comment]
*File Size Limit*

Inform the user the file size limit is 500MB at the time of upload.

- Add text to "Upload Your Document" label: "(Max file size 500MB)" 
- font: source sans pro; size: 15px; weight: regular; color: #323A45 (help text style)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3ff41728-8aac-4fa9-bcb3-a6836709082a)

**Comment by sarahridgway** [comment]
*File Size Limit*

Inform the user the file size limit is 500MB within the instructions for petition upload.

- New text in red

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/1e9ade0b-5f11-49c6-b388-a24fd14626fe)

**Comment by sarahridgway** [comment]
*File Is Too Large Warning*

If a user selects a file that is too large, display a browser alert to inform them.

- Message text: "Your file size is too big. The maximum file size is 500MB."
- Use default browser alert. No design required.

**Comment by sarahridgway** [comment]
Added note: Progress indicator applies to external uploads (petitioner and practitioner) ONLY at this time. Approved by Jessica 5/1/19. Progress indicators for internal uploads (if applicable) will be addressed at a later time, perhaps in tandem with the scanning story.

**Comment by sarahridgway** [comment]
Show a single progress indicator, including overall percentage and time, for all files combined.

**Comment by uxforgood** [comment]
@ericsorenson @JessicaMarine Looks great! Just a couple minor things: 

- On Before starting a case, added text about upload limit should be regular text color (212121) and not red. The red in the file was only to indicate what is NEW to add to the screen. 
- When indicator says "Less than... " capitalize "Than" 

May have an adjustment on font sizes on the modal, but talking to @JessicaMarine first.

**Comment by JessicaMarine** [comment]
5/10/19 QA comments:
1. When I cancel "File a document" function in the middle of the upload, it should not create a docket entry.  Docket entry #7 on 222-19 is an example.
2. My upload speed is too fast that I can't test the AC of "Upload function is not subject to time-out feature". Can someone who can throttle their upload speed please confirm that the time-out message doesn't come up at 5mins?
