### ISSUE TITLE
Petitions: QC  - changes to QC section based upon Petitions Section feedback

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1171]
During grooming, discuss with team whether to split story.

## Acceptance Criteria
Work Queues:
* Hyperlink docket numbers in queues
* Provide a success message after petitions have been assigned from Section to Individual indicating completion as expected.

QC Form
~~Alter the QC tab designs to draw attention to navigation and workflow.~~
~~* Co-locate the ratification order checkbox with the second party on the Parties tab for better context and clarity when considering and requesting ratification orders. Consider having space to free-text the party that needs to ratify~~
* Recall: show editable fields immediately to act faster
* ~Provide zoom in/out tool in the viewer's top toolbar for PDF views (confirm)~ (this is browser-specific)
* Only record a change to docket number or case caption upon hitting "Serve on IRS" [Note: this is intended to only capture one change to these items during the QC process; if another user makes multiple, successive changes, it will result in multiple docket entries]
* Update the required/optional fields on the QC screen to be consistent with new Paper-filed Petition form
* Verify that new contact fields have been implemented
* Remove the statistics stuff -- will be added in another story (likely post-MVP)
* Remove Trial Location field on QC form
* Add order to "Designate Place of Trial"

**Start a Case Form (internal)*
* Add Trial Location field, required only when a Request for Place of Trial is uploaded 

## Tasks
- [x] 1) hyperlink docket numbers in all work queues (Kris #2893)
- [x] 2) remove all IRS Notice Year Amounts from schema, UI, persistence, seed data, tests (Kris #2901)
- [x] 3) Prevent changes to "case caption" from recording change event to case if not 'Served to IRS' (see above) (Kris, William #2920)
- [x] 4) Add trial location field to internal start a case form (paper filed petition) with proper validation (Rachael #2902)
- [x] 5) Work queues - Provide a success message after petitions have been assigned from Section to Individual indicating completion as expected (Rachael #2906)
- [x] 6) Navigate to petition QC form on success when recalling a petition (Kris #2909)
- [x] 7) Update the required/optional fields on the QC screen to be consistent with new Paper-filed Petition form (William #2918)
- [x] 8) Verify that new contact fields have been implemented on the QC form (William #2903)
- [x] 9) Remove Trial Location field on QC form (Rachael #2906)
- [x] 10) Add order to "Designate Place of Trial" on QC form (Rachael #2906)
- [x] 11) UX review bugs
  - [x] 11a - bug 1 - assigned column too narrow (Rachael #2934)
  - [x] ~11b - bug 2 - when case type is changed, petition is no longer appearing in batched box~ works for new cases - Natalie is retesting
  - [x] ~11c - bug 3 - when case caption is changed, petition is no longer appearing in batched box~ works for new cases - Natalie is retesting
  - [x] ~11d - bug 4 - judge user doc qc box not loading data~ holding for later
  - [x] 11e - bug 2 - update error messages on start case internal form (Rachael #2940)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (William #2921)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William #2921)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
Note from clean up story 
* Case detail page > do we want the recalled tag in header to be more prominent? Recalled icons in docket record or messages? (TBD)

**Comment by klohman** [comment]
### Work Queue Updates 

#### Docket Number Link
In all work queues and message boxes, the docker number should be a link to the Case Detail page 

**Docket Clerks**
* Section Document QC 
    * Inbox 
    * In Progress 
    * Processed 
* My Document QC 
    * Inbox 
    * In Progress 
    * Processed 

**Petitions Clerks**
* Section Document QC 
   * Inbox 
   * Batched for IRS 
   * Served 
* My Document QC 
   * Inbox 
   * Batched for IRS 
   * Served 

**All Other User Roles**
* Docket Document QC Inbox

**Messages (All User Roles) 
* My Messages 
   * Inbox 
  * Sent 
*Section Messages
  * Inbox 
  * Sent 


### Section Document QC Updates 

* On assignment of unassigned work items, display success message on Section Document QC screen: " Selected documents were successfully assigned"

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/75446b11-ae09-4d7b-b207-f4bf5532dca1)

### Petition QC Updates 

#### Party Information 

For Party Type Petitioner and Deceased Spouse 
* Update primary contact name field label to "Name of Petitioner/Surviving Spouse" 
* Update secondary contact name field label to "Name of Deceased Spouse" 

#### Required Fields on QC 
* Update required fields for party types to match the Create Case form 
* Remove helper text (required) from all QC fields 
* Add helper text (optional) to optional field labels
    * Trial Location 
    * Fee Payment Date 
    * Fee Payment ID 
    * Date of Notice 
    * Other Orders Needed 

### Statistics 
* Remove Year and Amount fields 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4acacbf0-3c76-490a-a9bf-e71509dcd801)


### Recalled Petition Flow Update 
* On click of "Recall" button, open recall confirmation modal 
* on click of "Yes, recall" 
    * Modal closes 
    * Navigate to Petition QC (editable state) 
    * Success message displays " The petition is now recalled. It will need to be re-served to the IRS."
* Recalled Petition no longer appears in the "Batched for IRS tab"
* Recalled Petition appears in Petitions Section QC Inbox with recall icon 
* Recalled Petition appears in the My Document QC with recall icon for the petition clerk who recalled it 

### Updates to Docket Number and Case Caption 
* No design changes 
* On change to Case Type- update docket record dynamically 
* On manual change of Case Caption for cases with "NEW" status, update case caption text dynamically 
* On Click of "Serve to IRS": 
    * create the docket entry to capture a change to case caption 
    * Create docket entry to capture a change to the docket number

**Comment by klohman** [comment]
### 1171 Petition Clean Up Tests 

### 1) Docket numbers in Docket queues link to Case Detail 
* Login as Docket Clerk 
* Navigate to Section QC - Inbox 
* Click on docket number 
* Navigate to Section QC - In Progress 
* Click on docket number 
* Navigate to Section QC - Processed 
* Click on docket number 
* Navigate to My Document QC - Inbox
* Click on docket number 
* Navigate to My Document QC -In Progress 
* Click on docket number 
* Navigate to My Document QC - Processed  
* Click on docket number 
Results 
- [ ] Docket number link in Section QC Inbox links to Case Detail page 
- [ ] Docket number link in Section QC In Progress links to Case Detail page
- [ ] Docket number link in Section QC Processed links to Case Detail page 
- [ ] Docket number link in My Document QC Inbox links to Case Detail page 
- [ ] Docket number link in My Document QC In Progress links to Case Detail page
- [ ] Docket number link in My Document QC Processed links to Case Detail page 


### 2) Docket numbers in Petition queues link to Case Detail 
* Login as Petition Clerk 
* Navigate to Section QC - Inbox 
* Click on docket number 
* Navigate to Section QC - Batched for IRS 
* Click on docket number 
* Navigate to Section QC - Served 
* Click on docket number 
* Navigate to My Document QC - Inbox
* Click on docket number 
* Navigate to My Document QC - Batched for IRS 
* Click on docket number 
* Navigate to My Document QC - Served  
* Click on docket number 
Results 
- [ ] Docket number link in Section QC Inbox links to Case Detail page 
- [ ] Docket number link in Section QC Batched for IRS links to Case Detail page
- [ ] Docket number link in Section QC Served links to Case Detail page 
- [ ] Docket number link in My Document QC Inbox links to Case Detail page 
- [ ] Docket number link in My Document QC Batched for IRS links to Case Detail page
- [ ] Docket number link in My Document QC Served links to Case Detail page 
- 

### 3) Docket numbers in all other user queues link to Case Detail 
* Login as judge 
* Navigate to Docket Section QC Inbox
* Click on document number 
* Login as Senior Attorney 
* Navigate to Docket Section QC Inbox
* Click on document number 
Results 
- [ ] As judge, Docket number link in Docket Section QC Inbox links to Case Detail page 
- [ ] As senior attorney, Docket number link in Docket Section QC Inbox links to Case Detail page 
- 

### 4) A success message displays when work item is assigned to user from Petitions Section Queue
* Login as petitionsclerk1
* Navigate to Petitions Section Document QC 
* Assign a work item to petition clerk2 
Results 
- [ ] Success message displays  “Selected documents were successfully assigned”
- [ ] Selected work item displays as assigned to petitionclerk2 
- [ ] Selected work item displays in My Document QC Inbox for petitionclerk2


### 5) A success message displays when work item is assigned to user from Docket Section Queue
* Login as docketclerk1
* Navigate to Docket Section Document QC 
* Assign a work item to docketclerk2 
Results 
- [ ] Success message displays  “Selected documents were successfully assigned”
- [ ] Selected work item displays as assigned to docketclerk2 
- [ ] Selected work item displays in My Document QC Inbox for docketclerk2

### 6) Petition clerk recalls a batched petition 
* Login as petition clerk1 
* Click of petition from Document QC Inbox 
* Click Serve to IRS - confirm service 
* Navigate to Document QC - Batched for IRS 
* Click on batched petition 
* Click “Recall” and confirm 
Results 
- [ ] User navigates to Petition Document QC screen for the recalled petition
- [ ] Success message displayed on Petition Document QC screen “The petition is now recalled. It will need to be re-served to the IRS.”
- [ ] Case status is updated to “Recalled” 
- [ ] Recalled petition is removed from Batched for IRS box 
- [ ] Recalled Petition appears in Petitions Section QC Inbox with recall icon
- [ ] Recalled Petition appears in the My Document QC with recall icon for the petition clerk who recalled it

### 7) Petition clerk updates a docket number for a new petition 
* Login as petitionsclerk1
* Navigate to Document Section QC 
* Click on new petition with case type = deficiency 
* Change case type to CDP/Lien/Levy
* Navigate to Case Detail page 
Results 
- [ ] on change of case type to CDP, displayed Docket number appends “L”  
- [ ] Docket Record does not display a new entry for the updated docket number

### 8) Petition clerk updates a docket number for a new petition and serves to IRS 
* [ scenario 7]
* Click on Petition document link 
* Click on Serve to IRS and confirm 
* Navigate to Case Detail page 
Results 
- [ ] Docket record displays a new entry for the updated docket number 

### 9) Petition clerk updates a case caption for a new petition  
* Login as petitionsclerk1
* Navigate to Document Section QC 
* Click on new petition with party type = Petitioner
* Change case caption to “Jessica Marine & Brent Marine, Petitioners”
* Navigate to Case Detail page 
Results 
- [ ] on change of case caption, displayed Caption updates to “Jessica Marine & Brent Marine, Petitioners” 
- [ ] Docket Record does not display a new entry for the updated case caption

### 10) Petition clerk updates a docket number for a new petition and serves to IRS 
* [ scenario 9]
* Click on Petition document link 
* Click on Serve to IRS and confirm 
* Navigate to Case Detail page 
Results 
- [ ] Docket record displays a new entry for the updated case caption - “Caption of case is amended from ‘[original case caption]’ to 'Jessica Marine & Brent Marine, Petitioners v. Commissioner of Internal Revenue, Respondent'

**Comment by uxforgood** [comment]
UX Review Bugs 8/30/19

- [ ] 1 Log in as Petition clerk, assigning a document QC item to a user should trigger a success message. There is no success message.

**Comment by uxforgood** [comment]
## UX review bugs 8/30/19

- [ ] 1 Docket clerk Doc QC Section Inbox - the assigned to column is too narrow and is causing wrapping on most names. If you look at the spacing on In Progress it's much better. Change spacing of Assigned to better accommodate longer names. 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/977549fa-c2db-40e1-8782-4baba1035799)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/57560075-1b8d-400d-a3d1-b5865f2decc6)
