### ISSUE TITLE
Court User: "White Card" a case

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1189]
As a Court User, in order to make sure that a case definitely gets scheduled for trial, I need the ability to "white card" the case.

The Court usually schedules cases for trial on a first-in, first-out (FIFO) basis.  However, there may be an instance where a particular case needs to jump to the top of the priority for some reason.  In those events, a Court User needs the ability to indicate somewhere in the case that it needs to be scheduled for trial at the next available trial date at the selected place of trial.  This will effectively force a case to be picked up during the scheduling of a trial session even though it does not fall sequentially in the order to be scheduled. The Court currently calls this practice "white-carding" a case.

## Pre-Conditions
* A case exists in the system.

## Acceptance Criteria
* A Court User can notate in a case that this case should be forced (white card) to be picked up during the scheduling of a trial session even though it does not fall sequentially in the order to be scheduled. 
* When the automatic scheduling is run, the system will pick up a "white card" case make it first to get prioritized among all of the other cases being scheduled. 
* Note: Making a case a "white card" does not force it to get picked up for a session that's already been scheduled. It would get picked up and prioritized during the next automated scheduling process. 
* Case cannot be white carded and on hold at the same time. When on hold, the case can't be white carded. 
* Once scheduled, doesn't need to be designated as a white card any longer

## Tasks
- [x] 1 entity updates, endpoint to set a case as high priority (Rachael #3355)
- [x] 2 Add Mark High Priority button to case detail trial session card (Cody #3357)
- [x] 3 Mark as High Priority modal (Cody #3357)
- [x] 4 High Priority state for case detail trial card (Cody #3358)
- [x] 5 entity updates, endpoint to remove high priority from a case (Rachael #3355)
- [x] 6 Remove High Priority modal (Cody #3358)
- [x] 7 Move some of the serverless-cases endpoints to serverless-case-documents so we have enough space for the new endpoints (Rachael #3354)
- [x] 8 Update eligible trial sessions list to show/pick high priority cases first (Rachael #3359)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Case Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bd89b403-ee73-4100-92d7-4232158cee4b)

**Default Trial card - Not Scheduled**
* Add "Mark as High Priority" button to Trial Card 
* On click of "Mark as High Priority", display modal

#### Mark as High Priority Modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8d3c89a6-1fbe-413b-a10a-b81f9d32a655)

- "Why are you prioritizing this case" field is required 
* Error message if blank : Provide a reason 
* On click of Cancel, modal closes, no changes to case 

On click of "Mark as High Priority button" 
* modal closes 
* Case is added to the Eligible cases for the next available trial session in the "Requested Place of Trial" location 
* Case displays at top of Eligible Case list for existing trial session
* Trial card displays as High Priority 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4dbc4c53-8e0f-474d-8b3a-d79fa4f408b9)

* Place of Trial displays location of Requested Place of Trial 
* Trial Date displays as Not scheduled 
* Assigned Judge displays as "Not assigned"
* Reason displays text entered in modal 
* Remove High Priority button displays 

#### Removing High Priority 
* on click of Remove High Priority button, modal displays 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/41273b19-7b6e-4bb5-93a1-06a3fc9d05e8)

on click of Yes, remove high priority, 
* modal closes 
* Case priority returns to normal (should be eligible for trial based on standard rules) 
* Trial card displays as Default Trial Card- Not Scheduled

**Comment by klohman** [comment]
### 1189 White Card a case 

Test Data: 
* Create trial session 
    * Baltimore, MD 
    * Start date 12/07/19
    * Regular 
    * Judge Buch 
* Case 1 
    * Requested Place of Trial = Baltimore, MD 
    * Case Type - CDP
    * Regular procedure 
    * Status -  General Docket (At Issue) Ready for Trial 
* Case 2 
    * Requested Place of Trial = Baltimore, MD 
    * Case Type - Deficiency
    * Regular procedure 
    * Status -  General Docket (At Issue) Ready for Trial 
* Case 3
    * Requested Place of Trial = Baltimore, MD 
    * Case Type - Deficiency
    * Regular procedure 
    * Status -  General Docket - Not at Issue 
* Case 4
    * Requested Place of Trial = Detroit, MI
    * Case Type - Deficiency
    * Regular procedure 
    * Status -  Calendared 
* Case 5
    * Requested Place of Trial = Lubbock, TX
    * Case Type - CDP
    * Regular procedure 
    * Status -  General Docket (At Issue) Ready for Trial 
    * Blocked From Trial  
* Case 6
    * Requested Place of Trial = Lubbock, TX
    * Case Type - Deficiency
    * Regular procedure 
    * Status -  General Docket (At Issue) Ready for Trial 

#### 1) User can assign a case with status General Docket (At Issue) Ready for Trial as high priority 
* Login as docket clerk 
* Navigate to Case 2 
* Click “Mark as High Priority” and confirm 
Expected results 
- [ ] On click of Mark as High Priority, modal displays 
On click of “Mark High Priority" button in modal 
- [ ] Modal closes 
- [ ] Case status remains General Docket (At Issue) Ready for Tria
- [ ] Trial Card displays as “Trial - Not Scheduled - High Priority 
- [ ] Place of Trial field displays as “Baltimore, MD” 
- [ ] Trial date field displays “Not Scheduled”
- [ ] assigned judge field displays “Not assigned” 
- [ ] Reason field displays text entered in modal 
- [ ] Remove High Priority button displays 

#### 2) User can assign a case with status General Docket - Not at Issue as high priority 
* Login as docket clerk 
* Navigate to Case 3 
* Click “Mark as High Priority” and confirm 
Expected results 
- [ ] On click of Mark as High Priority, modal displays 
On click of “Mark High Priority" button in modal 
- [ ] Modal closes 
- [ ] Case status remains General Docket Not at Issue 
- [ ] Trial Card displays as “Trial - Not Scheduled - High Priority 
- [ ] Place of Trial field displays as “Baltimore, MD” 
- [ ] Trial date field displays “Not Scheduled”
- [ ] assigned judge field displays “Not assigned” 
- [ ] Reason field displays text entered in modal 
- [ ] Remove High Priority button displays 

#### 3) User cannot assign a case with status Calendared as high priority 
* Login as docket clerk 
* Navigate to Case 4 
* View Case Information
Expected results 
- [ ] Trial card displays as Calendared 
- [ ] Mark as High Priority button is hidden 

#### 4) User cannot assign a case with flagged as Blocked from Trial as high priority 
* Login as docket clerk 
* Navigate to Case 5 
* View Case Information
Expected results 
- [ ] Trial card displays as Blocked From Trial  
- [ ] Mark as High Priority button is hidden 

#### 5) User assigns high priority case to an existing trial session 
* Scenario 1
* Navigate to Baltimore, MD session start date 12/07/19
Expected results 
- [ ] Case 2 displays as first case in Eligible Cases 
- [ ] Case 1 displays under Case 2 In priority 

#### 6a) User assigns high priority case to a trial location with no existing sessions 
* Login as docket clerk 
* Navigate to Case 5
* Remove block 
* Navigate to Case 6
* Mark Case 6 as high priority 
Expected results 
- [ ] When block is removed, Trial card displays as “Not Scheduled” and mark as high priority button is displays 
- [ ] Case status remains General Docket (At Issue) Ready for Trial
- [ ] Trial Card displays as “Trial - Not Scheduled - High Priority 
- [ ] Place of Trial field displays as “Lubbock, TX” 
- [ ] Trial date field displays “Not Scheduled”
- [ ] assigned judge field displays “Not assigned” 
- [ ] Reason field displays text entered in modal 
- [ ] Remove High Priority button displays 

#### 6b) User assigns high priority case to a trial location with no existing sessions 
* Create trial session
    * for Lubbock, TX
    * Start date - 12/15/19 
    * Regular procedure 
    * Session max = 1 case
    * Judge Ashford
* View Eligible cases 
Expected results: 
- [ ] Case 6 displays as first case in Eligible Cases 
- [ ] Case 5 displays under Case 6 in priority 

#### 7) High priority case is picked up for trial session before standard priority cases 
* Scenario 6b
* Set Calendar for Lubbock, TX session 
* View Open Cases 
* View Case Information for Case 6 
Expected results 
- [ ] Case 6 displays under Open Cases 
- [ ] Case 6 status updates to Calendared 
- [ ] Case 6 - Trial Card displays as Calendared 
- [ ] Place of Trial field displays as “Lubbock, TX” 
- [ ] Trial date field displays “12/15/19 ”
- [ ] assigned judge field displays “Judge Ashford” 
- [ ] Reason field displays text entered in modal 
- [ ] Remove High Priority button displays 

#### ) User removes high priority from a case 
* Scenario 1 
* Click “Remove High Priority” and confirm 
* Navigate to Baltimore, MD 12/07/19 trial session 
Expected results 
- [ ] Case 2 Trial card displays as “Not Scheduled” 
- [ ] Mark as high priority button displays 
- [ ] Case 1 Is listed above Case 2 in Eligible Cases for Baltimore, MD 12/07/19 session
