### ISSUE TITLE
Court User: Print a report  to help Court determine trial locations

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1190]
As a Court User, in order to determine which cities the Court needs to schedule trial sessions in, I need the system to provide me with a report I can print that shows me the number of cases ready for trial in each city, what type of cases they are (small vs. regular), and information about prior sessions in that city. 

The Court schedules trial sessions in cities as needed.  This means, as there are enough cases ready for trial (100-125) for a city, the Court wants to schedule a trial session.  For cities that have a lot of cases, the Court may go to that city several times throughout the course of a year.  For cities that do not have alot of cases, the Court may only go once a year.  The Court goes to EVERY city at least once a year, even if there are less than 100-125 cases for trial.  In order to determine which cities the Court needs to go to and when, Court Users (espcially the Calendar Section) need to be able to run a report at any time that tells them the number of cases ready for trial in each of the 75 trial cities.  That number should further be broken down into regular cases versus small cases.  The report should also provide some information about prior trial sessions in each of the cities: date(s) of last three sessions and name of Judge who presided at each session.

## Pre-Conditions
* Cases are in the system with designated Places of Trial

## Acceptance Criteria
* Ability for Court Users to generate and print a report at any time which will help them determine which cities to schedule trial sessions in; and how many sessions to schedule and what type of sessions they need.
* User must indicate which future session they are trying to plan for
* Report must include the number of cases ready for trial for each trial location; what type of cases they are (small vs. regular); the dates of previous three (3) trial sessions in each trial location; whether it was a regular, small or hybrid session; and who the presiding judge was for each session. 

## Tasks
- [x] 1 Run Trial Session Planning Report modal, sequences, validation, button in header for Trial Session Planning (Cody #3460)
- [x] 2 Endpoint (lambda, interactor, proxy, persistence methods) for generating PDF (Team mob #3471 #3475)
- [x] 3 Route, view for Trial Session Planning Report, submit sequence from the modal to call the endpoint and change the route (Team mob #3471)
- [x] 4 Create template for PDF (Matt #3467)
- [x] 5 Fix footer issue on generated PDF - cutting off last row in the table (Rachael #3477)
- [x] 6 Show multiple judge names on the past trial sessions if there was more than one session (Rachael, Cody #3482)
- [x] 7 Filter out special and motion/hearing sessions from trial session list (Rachael, Cody #3482)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Cody)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Rachael)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### User Permissions 
* functionality applies to all internal users 

### Updated Trial Sessions screen 
* Add "Trial Session Planning Report" button 
* On click, display " Run Trial Session Planning Report" modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/23fd0ccb-3b03-491e-b2de-e29a73ce0295)


### Updated Navigation 
* Add "Trial Session Planning" as submenu under "Reports" 
* On select of Trial Session Planning, display "Run Trial Session Planning Report" modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4e678457-6a6b-4109-9c63-412288acd658)

### Run Trial Session Planning Report Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/64eba9e4-c220-4f56-93ca-55f542127879)

**Which trial term are you planning for?**
* Field is required 
* Error message if incomplete: "Select a term"
* Dropdown contains 
   - Winter  
   - Spring 
   - Fall 

**Select Year**
* Field is required 
* Error message if incomplete: "Select a year"
* Dropdown contains current year and two future years 

**Run Report**
* on click of Run Report button, modal closes and user is navigate to Trial Session Planning Report pdf view page 
* Selected Term and Year are combined to generate the report 
* On click of "Back to Trial Sessions" button, navigate to Trial Sessions page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1592f6df-9345-4f56-ad20-d94e03117579)

### Trial Session Planning Report 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9ae62e5e-c950-4c55-a4f0-f32d011d734b)

**State**
* Display state of trial location (abbreviation) 
* List is sorted alphabetically by state, then city 

**Location**
* Display trial location 

**All**
* Display total number of cases eligible for trial for trial location 
* Eligible cases include 
   - Cases with status General Docket - Ready for Trial 
   - Cases marked "High priority" for that trial location 
 
**Small**
* Display total number of cases eligible for trial for trial location with Small Case Procedure 

**Regular**
* Display total number of cases eligible for trial for trial location with Regular Case Procedure 

**Term 1 ("Term 1" is placeholder text in design)**
* Display previous term ([Selected Trial Term/Year] - 1 term)
* Display the previous term in the following format [Term] [Year], example Spring 2020

If a trial session for this term exists:
* display Session Type 
   - Regular = (R)
   - Small = (S)
   - Hybrid = (H)
   - Special = (SP)
   - Motion/Hearing = (M/H)
* display the judge assigned - last name only 

If a trial session for this term does not exists: 
* Display far.fa-calendar-times icon 

**Display printed date (standard for all printable PDFs)**

**Comment by klohman** [comment]
### 1190 Test Scenarios 

Test Data 
* Trial Sessions
    * Birmingham, AL 
        * 1/14/2020
        * Judge Buch
        * Small 
    * Birmingham, AL 
        * 11/14/2019
        * Judge Ashford 
        * Regular
    * Birmingham, AL 
        * 4/20/2020
        * Judge Cohen
        * Hybrid 
    * Portland, ME
        * 12/12/2019
        * Judge Pugh 
        * Small
    * Portland, ME 
        * 4/6/2020
        * Judge Urda 
        * Regular
* Cases 
    * 100 Cases - Birmingham, AL 
        * Status = General Docket (At Issue) - Ready for Trial 
        * Regular procedure 
    * 100 Cases - Birmingham, AL 
        * Status = General Docket (At Issue) - Ready for Trial 
        * Small procedure 
    * 1 Case - Birmingham, AL 
        * Status - General Docket (Not at Issue) 
        * Regular
        * Marked High Priority 
    * 51 Cases - Portland, ME 
        * Status = General Docket (At Issue) - Ready for Trial 
        * Regular procedure  
    * 49 Cases - Portland, ME 
        * Status = General Docket (At Issue) - Ready for Trial 
        * Small procedure  

#### 1) User navigates to report from Trial Sessions screen 
* Login as internal user 
* Click trial Sessions from main nav
* Click Trial Session Planning report button 
Expected results
- [ ] Run Trial Session Planning Report modal displays 

#### 2) User navigates to report from Global Navigation 
* Login as internal user 
* Select Reports from main nav
* Select Trial Session Planning from submenu
Expected results
- [ ] Run Trial Session Planning Report modal displays 

#### 3) User selects term and year for report 
* Scenario 1 
* Select “Fall” in term field 
* Select “2020” from year field 
Expected results
- [ ] Term dropdown options include Winter, Spring, and Fall 
- [ ] Year dropdown includes 2019, 2020, 2021 

#### 4) User sees trial session information for 3 previous terms for all trial locations
* Scenario 3
* Click “Run report” button on modal 
Expected results 
- [ ] Report lists all trial locations 
- [ ] Term 1 column header displays as “Spring 2020”
- [ ] Term 2 column header displays as “Winter 2020”
- [ ] Term 3 column header displays as “Fall 2019”  

#### 5) User sees indicator when a trial location did not have a session for a term 
* Scenario 4 
Expected Results 
- [ ] Calendar icon displays in Portland, ME - Winter 2020 

#### 6) User sees total number of eligible cases (small, regular and all) for a trial location
* Scenario 4 
Expected results 
- [ ] “201” displays in Birmingham, AL - All 
- [ ] “100” displays in Birmingham, AL - Small 
- [ ] “101” displays in Birmingham, AL - Regular 
- [ ] “100” displays in Portland, ME - All
- [ ] “51” displays in Portland, ME - Small 
- [ ] “49” displays in Portland, ME - Regular 

#### 7) User sees session type and assigned judge for a trial session 
* Scenario 4 
Expected results
- [ ] “(H) Cohen” displays in Birmingham, AL - Spring 2020
- [ ] “(S) Buch” displays in Birmingham, AL - Winter 2020 
- [ ] “(R) Ashford” displays in Birmingham, AL - Fall 2019
- [ ] “(S) Pugh” displays in Portland, ME - Fall 2019
- [ ] “(R) Urda” displays in Portland, ME - Spring 2020 

#### 8) User prints report 
* Scenario 4 
* Select Print option from PDF viewer 
Expected results 
- [ ] Printed PDF displays as designed 
- [ ] “Printed XX/XX/XX” date is displayed in footer
