### ISSUE TITLE
Court User: Enter trial session details into the system

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1191]
As a Court User, in order to start scheduling cases for trial, I need to enter trial session details into the system.

Once the Court prints the report (#1190), it uses an off-line process to decide which cities in should hold trial sessions in and when.  Once the Court has decided on a tentative schedule of trial sessions to be added to the system, a Court User needs to be able to "create" the trial session by entering trial session details into the system.  That information includes: the date range of the trial session (usually 1 week), trial city, session type (Small, Regular, Hybrid, Special), Name of Judge, Max number of cases for the session. 

## Acceptance Criteria
* Court User needs to the ability to enter trial session details: 
         - date range of the trial session (usually 1 week), REQUIRED
         - trial city, REQUIRED
         - session type (Small, Regular, Hybrid, Special), REQUIRED
         - Name of Judge, 
         - Max number of cases for the session REQUIRED
         - Term (Spring. Fall, Winter). REQUIRED
         - Courthouse Location
         - Time
         - Trial Clerk
         - Court Reporter
         - IRS Calendar Administrator
         - Free text for any other Trial Session Notes
* Session types should include:
         - Regular -- trial session includes only Regular cases
         - Small -- trial session includes only Small cases
         - Hybrid -- trial session includes a combination and Regular and Small cases
        - Special -- a trial session that is set by a Judge to hear 1 or more cases that cannot be heard during a regular trial session; can happen anytime, anywhere
         - Motion/Hearing -- a session where a Judge will hold a hearing on a motion or small issue (something other than an entire case)
* User can visually see when two swing sessions are scheduled together.
      - Note: A Swing session = a trial session that is shorter than a week and often times combined with another shorter session.
* ~~Trial session details can be edited after it's been put into the system~~ (making another story)
* View a list of sessions that have been scheduled, including dates and locations [See Note below]

## Notes
* From a design perspective, I see this as a three-level drill down:
(1) #1191 creates the list of all trial sessions 
* Should be able to filter between Upcoming, Closed, All
* Judges should also have the ability to view/filter only their trial sessions (POST-MVP?)
* List should include the following for each trial session -- Session Location | Type | Date | Time | Judge
* Ability to sort on any column (Session Location | Type | Date | Time | Judge)
* City name is hyperlink into the specifc trial session -- When you click into a specific trial session, you get a list of all the cases on that trial session
(2) #1194 creates the list of all cases on a trial session
* Should be able to filter between Open, Closed, All
* List should include the following information for each case -- Docket No. | Case Caption | Petitioner's Counsel Respondent's Counsel | Disposition
* Ability to sort on any column (Docket No. | Case Caption | Petitioner's Counsel | Respondent's Counsel | Disposition)
* List also provides information about trial session -- Courthouse Location, Judge, Time, Trial Clerk (and anything else we want to add)
* List should be printable
* Docket number for each case is hyperlink -- When you click into a case on a trial session list (by clicking on hyperlink on Docket number), it should take you into the case detail page of that case
(3) Case Detail Page (already exists)

## Tasks
- [x] 1 create trial session entity with validation rules (Rachael #1933)
- [x] 2 create endpoint, interactor, and persistence method to submit a trial session (William #1951)
- [x] 3 create view and route for trial session data entry form (Rachael, Kris #1955)
  ~3a create users in chambers and trial clerk sections to fill Judge/Trial Clerk dropdowns on form~ - these are going to be hardcoded for this story
  - [x] note: trial location dropdown should populate with all possible trial locations regardless of the session type selected
- [x] 4 create sequences and actions to submit a trial session (William #1951)
- [x] 5 integrate validation into UI for trial session form (Rachael, Kris #1960)
- [x] 6 create endpoint, interactor, and persistence method to retrieve list of trial sessions (Rachael #1935)
- [x] 7 create view and route for trial session list/table (Kris, Rachael #1950)
  - [x] note: create tab container for Upcoming/Closed/All, but Upcoming will be the only tab for this story - others will be added in later stories
  - [x] also note: filtering will be done as part of a separate story
- [x] 8 create sequences and actions to retrieve list of trial sessions (Rachael #1940)
- [x] 9 add global navigation header for Trial Sessions (all internal users will have access to this) (Rachael #1934)
- [x] 10 add trial session seed data (#1935, #1950)
- [x] 11 create sequences and actions to validate a trial session (William #1951)
- [x] 12 Look into trial session data modeling. pk should be uuid (William #1965)
- [x] 13 remove defaults from form (#1970)
- [x] 14 remove Term field from form; calculate from entered startDate (#1970)
- [x] 15 store term year either separately or with term field (#1974)
- [x] 16 fill swing session dropdown with other sessions in selected term (#1970)
- [x] 17 set both sessions to swingSession=true when linking a swing session to another session (Rachael #1981)
- [x] 18 validation on Time field (XX:XX am/pm) - and store this as a string (needs to be added to entity) (#1974)
- [x] 19 secondary sort on trial sessions table alphabetically by trialLocation (#1974)
- [x] 20 update form cancel modal sequence to redirect to the trial session table (William #1992)
- [x] 21 fix trial session table sorting (date storage issues) (Kris, Rachael #1991)
- [x] 22 add helper text to time field "Enter time as hour : minutes (e.g. 10:30 am)." (Kris, Rachael #1991)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [ ] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael #1984)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (Rachael #1984)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (William #1985)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised (Rachael #1984)

**Comment by klohman** [comment]
## Updated Global Navigation

* Add "Trial Sessions" link to global navigation for all users 
* On click, navigate to the Trial Sessions screen 

## Trial Sessions screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7551f34a-a5e5-4cdf-ae59-a33c1fafd9e8)

### Upcoming tab 
* If there are no upcoming trial sessions, hide table and filters 

**Add Trial Session button**
* On click, navigate to "Add Trial Session" screen

**Date**
* Trial sessions include a "Start Date"; sessions with the same start date are displayed as a group with a blue header 
* Date group header labels are displayed as "Month DD, YYYY"
* Table is sorted chronologically by date (default) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/29454c7f-4386-4653-bc0d-c9d261641d32)

**Location**
* Location is displayed as City, State and hyperlinked to the Trial Session Detail screen (not implemented in this story)

**Swing Sessions**
* Swing sessions include a link icon indicator to the left of the location 
* Both sessions associated with a swing session will include the icon 
* Swing sessions should be the last sessions listed within a date group and should be sorted in chronological order 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4e7ec611-00e4-46d4-b4ec-397e051024a6)

### Filters 
* Able to sort by Session Type, Location, Judge 
* Filtered table does not show the date group headers 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2f5933b2-6f75-421f-854b-4ced7a175136)

**Comment by klohman** [comment]
## Add Trial Session screen 

### Session Information 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9ba0d800-26cc-4d83-9eaa-2e15d0b2f1f6)

**Term**
* Field is REQUIRED
* There are three terms per year: Winter, Spring, Fall 
* Selected term should be associated with the year entered in the date field 
* Error message if incomplete: "Term is required."  

**Start Date**
* Field is REQUIRED 
* Validation: Date must be in correct format (same as other form validation) 
* Validation: Date must be in the future 

**Time**
* Field is optional 
* Entered time will be saved as EST 

**Swing Sessions**
* Checkbox - if unselected, hide "Which Trial Session is This Associated With" dropdown
* Checkbox - if selected, show "Which Trial Session is This Associated With" dropdown
* "Which Trial Session is This Associated With" dropdown - needs to populate with all existing trial sessions within the same term (determined by entered term and date) 
* The selected trial session from dropdown AND the newly created session should be flagged as swing session and show the link icon on the Trial Sessions- Upcoming table. 

**Session Type**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/964ad7ea-1386-4543-aaaa-e8cb6f3a5e4c)

* Field is REQUIRED 
* Logic based around each session type will be built in upcoming story 
* Error message if incomplete: "Session type is required"

**Max Number of Cases**
* Field is REQUIRED
* Error message if incomplete: "Enter the maximum number of cases allowed for this session"

### Location Information
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7f0835e7-bb75-4a39-9ee8-37425efefd3e)

**Trial Location**
* Field is REQUIRED 
* Dropdown is populated with list of ALL trial locations, alphabetical by state
* Error message if incomplete: "Trial Location is required"

**Address Fields**
* Fields are optional 
* Entered addresses need to be associated with the Trial Location in database (for future functionality) 

### Sessions Assignments 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/825e3528-532d-4b5b-9dab-efc199116e21)

**Judge**
* Field is optional 
* Dropdown is populated with all users with "Judge" role 

**Trial Clerk**
* Field is optional 
* Dropdown is populated with all users in Trial Clerk section 

**Court Reporter**
* Field is optional 
* Free text field 

**IRS Calendar Administrator**
* Field is optional 
* Free text field 

### Session Notes 

* Field is optional 
* Text-area component 

### Buttons 
**Add Session**
on click
* session is created
* Trial Session Detail screen is populated with metadata from form 
* Session is added to the Upcoming tab on the Trial Sessions screen 
* User returns to Trial Sessions screen with success message displayed 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7b0cb87f-f7da-4eea-82f5-6c2d1319a5c5)

**Cancel**
on click, display Cancel modal 
* on click of Yes, cancel, discard form selections and navigate back to Trial Sessions screen 
* on click of No, continue, close modal and remain on parent page
