### ISSUE TITLE
Calendar Clerk: Run automated scheduling of trial sessions

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1192]
As a Calendar Clerk, in order to schedule specific cases for trial on a trial session, I need to run an automated scheduling of the trial sessions.

Once all of the trial sessions (dates and cities) have been agreed upon, the Court needs to actually populate each trial session with cases ready for trial.  The Calendar Section is in charge of doing this function.  The trial session is actually populated with cases 5 months before the trial session is scheduled to commence by the Calendar Clerk.  When a trial session is ready to be populated with cases, the Calendar Section should be able to run an automated scheduling program that will link specific cases with a trial session.  This automated scheduling program should take several things into account: (1) Only cases with the status of "General Docket - At Issue (Ready for Trial)" and that designated place of trial are eligible to be scheduled on a particular trial session; (2) Only regular cases get scheduled to regular session; (3) only small cases get scheduled to small sessions; (4) both regular and small cases can get scheduled to hybrid sessions; (5) "L" cases, and "P" cases get prioritized for scheduling over any other type of case regardless of when they were filed vis-a-vis other cases; (6) cases are otherwised scheduling on a FIFO basis, up to the maximum number of cases allowed for a specific trial session (this was defined when the trial session was created in the system).

## Pre-Conditions
* Cases are in the system with various case statuses, including "General Docket - At Issue (Ready for Trial)"
* Cases have a designated place of trial
* A trial session has been created

## Acceptance Criteria
* Calendar section can initiate the generation of a trial session calendar at any time
* For each trial session, only cases with the status of "General Docket - At Issue (Ready for Trial)" and a requested trial location for that designated place of trial are eligible to be scheduled on that particular trial session, up to the max number that has been set for the trial session when it was entered.
* Only small cases get scheduled to the trial session that's has a small type
* Only regular cases get scheduled to the trial session that's has a regular type
* Both small and regular cases get scheduled to the trial session that's has a hybrid type
* Cases are scheduled sequentially based up on the date and time the petition was filed (FIFO)
* L and P case types get prioritized before any other type of case; and then sequentially based upon the date petition was filed (FIFO)
* Case status is automatically set to "Calendared for Trial" once a case is scheduled to a specific trial session
* Trial details display on the case detail page (case info tab)

## Tasks
- [x] 0 Mechanism for setting cases 'ready for trial' manually (Rachael #2035)
- [x] 1 Trial Session Details Page
  - [x] 1a route, sequence, actions for trial session detail page (Kris #2033)
  - [x] 1b Set Calendar Button (Kris #2047)
  - [x] 1c Confirm Modal for Set Calendar (Kris #2047)
  - [x] 1d Eligible Cases View (Dependent on 2) (Rachael #2046)
  - [x] 1e Link to the detail page from the trial session list (Rachael #2045)
  - [x] 1f Trial session detail cards, finish building out getTrialSessionDetails endpoint (Rachael #2051)
  - [x] 1g Update header on trial session detail page with trial location, term tag, and start date (Rachael #2053)
  - [x] 1h Computed for formatting trial session details (Rachael #2055)
  - [x] 1i Call the setCalendar sequence as the confirm on the modal and hide the eligible case list when session is calendared (Rachael #2056)
  - [x] 1j Show associated swing session on the trial session details view (Rachael #2063)
  - [x] 1k Hide eligible cases table and set calendar button on Motion/Hearing and Special sessions (Rachael #2063)
- [x] 2 Update #1187 Lambda process to create mapping records for case to be used for sorting (William #2018)
  - [x] 2a Get Eligible Cases http Endpoint / Use Case (William #2018)
  - [x] ~2b For 'Special' or 'Motion/Hearing' Trial Sessions what should happen?~
  - [x] 2c update sort key when case is updated (Rachael #2036)
  - [x] 2d Eligible Cases Endpoint should have limit + 50 extra returned (William #2066)
- [x] 3 Set Calendar Sequence (William #2034)
  - [x] 3a remove mapping records for cases (William #2034)
  - [x] 3b update calendared cases with trial details and set status to "Calendared" (See: [USTC Case Statuses](https://docs.google.com/document/d/1qhxASEKuzcPp99rTfCVkYbi6hVKS1pPPIgn5MvEWFPM/edit)) (William #2034)
  - [x] 3c update trail session status and case list (William #2034)
  - [x] 3d verify trail details display on case details page for calendared cases (William #2034)
  - [x] ~3e "Not selected" defaults for trial information on case detail page~
  - [x] 3f make sure that concatenated date is provided as trial date to case details (William #2050)
  - [x] 3g Case Journey Test (William #2058)
- [x] 4 Test Scenarios
    - [x] 4a Scenario 1 - https://github.com/flexion/ef-cms/issues/1192#issuecomment-502137868 (William #2068)
    - [x] 4b Scenario 2 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (William, Rachael #2070)
    - [x] 4c Scenario 3 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (William, Rachael #2071)
    - [x] 4d Scenario 4 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528  (Rachael #2073)
    - [x] 4e Scenario 5 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael #2075)
    - [x] 4f Scenario 6 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael #2077)
    - [x] 4g Scenario 7 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael #2078)
    - [x] 4h Scenario 8 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael #2080)
- [x] 5 fixes
  - [x] 5a prioritize L cases over P cases, regardless of date (scenario 6) (Rachael, William #2082)
  - [x] 5b set isCalendared to true for Motion/Hearing and Special sessions (Rachael, William #2082)

## Post Demo Tasks
- [ ] Eligible Cases Use Case should return limit + 50 (Currently 2) (William #2239)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael #2090 #2086)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Trial Sessions screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/512aa416-f96c-4ffa-bce4-fe67c2bfbfd2)

* On click of the trial location link, navigate to the Trial Session Detail page for that session

## Trial Session Detail 

### Page Title/Header
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aab2dce4-52cd-4549-9fdf-f5738045126b)

* Display the City, State of the trial location 
* Label displays the "Term: Trial Session status" : example - Spring 19: Upcoming 

### Session Information 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6f0790ed-14e4-4505-9abb-c761cd088f3b)

* All metadata entered in the Add Trial Session form will display read-only
* Date field should display date AND time (if entered), example: 12/09/19 10:00 am 
* Any blank fields in the Assignments section should display "Not assigned" 

### Eligible Cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e8e8f3fd-4465-489c-b38a-d6d61c31ba69)
* Cases should be listed in their priority order (see AC) 

* Docket Number - link to Case Detail page 
* Case Caption - display all information in the case caption before the "Petitioner(s)" 
* Petitioner Counsel - display any associated Petitioner Counsel
* Respondent Counsel - display any associated Respondent Counsel
* Case Type - Display Case Type 
* Disposition- field will be blank for now 

### Set Calendar button 

* On click, display the Set Calendar Confirmation Modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8560988f-cd07-4093-99dc-3fdb6305ae97)

**From Modal**
* On click of "No, cancel", close modal and return to parent page 
* On click of "Yes, set calendar" - all eligible cases are set for that trial session, modal closes, parent page refreshes, and success message is displayed 

### Trial Session Detail - Success 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f3f70d23-27e-405b-b159-09592f4b0528)

* Set Calendar button is no longer visible 
* Eligible Cases is no longer visible 

### Case Detail 
* Trial date and Assigned Judge information is populated 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fdb2e253-6e70-4dae-8697-901a10a031a7)

**Comment by klohman** [comment]
## Swing Sessions 

* When two sessions have been associated with one another on the Add a Trial Session form, display the Swing Session field under Session Details 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/da01b314-5a34-4d08-a30e-c582dc45808d)

* The associated trial session location link should open the Session Detail page for that session 
* Both sessions associated should display the swing session field - with the link to the associated session 
* If a session is not associated as a swing session, hide this field

**Comment by klohman** [comment]
## Test Scenarios 

Scenario 1 
AC - Only cases with status “General Docket - At Issue (Ready for Trial)” with a designated place of trial are eligible to be auto scheduled for trial for that city’s session 

- Create trial session for [trial location]

- Create cases 
    1. Case with status “General Docket - Not at Issue” for [trial location]
    2. Case with Status “General Docket - At Issue” for [trial location]
    3. Case with status “General Docket - At Issue” for [another trial location] 

Result: Case #2 should show up as eligible for [trial location] session

**Comment by klohman** [comment]
## Test Scenarios 

### Scenario 2 
AC: Only small cases get scheduled to small trial sessions 

- Create trial session with Small session type for [trial location] with max case count = 1 

- Create cases 
    1. Case with status “General Docket - At Issue” for [trial location] with Small case type with filed date 1/1/2019
    2. Case with status “General Docket - At Issue” for [trial location] with Small case type with filed date 1/2/2019 
    3. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/1/2019

Result: Case #1 and #2 should show as eligible for [trial location] session

- Set calendar for session 

Result: Case #1 is assigned to [trial location] session 


### Scenario 3 
AC: Only regular cases get scheduled to the trial session that has a regular case session type 

- Create trial session with Regular session type for [trial location]  with max case = 1

- Create cases 
    1. Case with status “General Docket - At Issue” for [trial location] with Small case type with filed date 1/1/2019
    2. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/1/2019
    3. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/2/2019

Result: Case #2 and #3 should show as eligible for [trial location] session

- Set calendar for session 

Result: Case #2 is assigned to [trial location] session 

### Scenario 4 
AC: Both small and regular cases get scheduled to the trial session that’s a hybrid session

- Create trial session with “Hybrid” session type for [trial location] with max cases =2 

- Create cases 
    1. Case with status General Docket - At Issue” for [trial location] with Small case type with filed by date 1/1/2019
    2. Case with status “General Docket - At Issue” for [trial location] with Regular case type  with filed by date 1/1/2019
    3. Case with status General Docket - At Issue” for [trial location] with Small case type with filed by date 2/1/2019

Result: Case #1, #2 and #3 should show as eligible for [trial location] session 

- Set calendar for session 

Result: Case #1 and #2 are assigned to [trial location] session 

### Scenario 5 
AC: Cases are scheduled sequentially based upon the date and time the petition was filed (FIFO) 

- Create trial session with “Regular” session type for [trial location] with a max case count of 2

- Create cases 
    1. Case with status “General Docket- At Issue” for [trial location] with Regular case type filed on 1/1/2019
    2. Case with status “General Docket- At Issue” for [trial location] with Regular case type filed on 2/1/2019
    3. Case with status “General Docket- At Issue” for [trial location] with Regular case type filed on 3/1/2019

Result: Case #1, #2, and #3 should show as eligible for [trial location] session 

- Set calendar for session 

Result: Case #1 and #2 are assigned to [trial location] session


### Scenario 6 
AC: L and P case types get prioritized before any other type of case; and then sequentially based  upon the date petition was filed (FIFO) 

- Create trial session with “Regular” session type for [trial location] with a max case count of 3 

- Create cases 
    1. Case “L” type with status “General Docket- At Issue” for [trial location] with Regular case type filed on 5/1/2019
    2. Case “P” type with status “General Docket- At Issue” for [trial location] with Regular case type filed on 3/1/2019
    3. Case with deficiency type with status “General Docket- At Issue” for [trial location] with Regular case type filed on 1/1/2019
    4. Case with deficiency type with status “General Docket- At Issue” for [trial location] with Regular case type filed on 2/1/2019

Result: Cases #1, #2, #3, #4 will show as eligible for [trial location] session in sequential order (1,2,3,4)

- Set calendar for session 

Result: Cases #1, #2, #3 are assigned to [trial session] 


### Scenario 7 
AC: Case status is automatically set to “Calendared for Trial once a case is scheduled to a session 

- Create trial session with “Regular” session type for [trial location] with a max case count of 1 

- Create cases
    1. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/1/2019
    2. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/2/2019

- Set calendar for session 

Results: 
- Case #1 is assigned to [trial session]. 
- Case #1 case status is updated to “Calendared for Trial” 
- Case #2 is not assigned to [trial session]
- Case #2 case status is “General Docket - At Issue”

### Scenario 8 
AC: Trial details display on the case detail page 

AC: Case status is automatically set to “Calendared for Trial once a case is scheduled to a session 

- Create trial session with “Regular” session type for [trial location] with start date 10/14/19, Judge Buch assigned, and a max case count of 1 

- Create cases
    1. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/1/2019
    2. Case with status “General Docket - At Issue” for [trial location] with Regular case type with filed date 1/2/2019

- Set calendar for session 

Results: 
- Case #1 is assigned to [trial session] 
- Case #1 case status is updated to “Calendared for Trial” 
- Case #1 case detail displays 
    - Place of Trial - [trial location]
    - Trial Date - 10/14/19
    - Assigned Judge: Judge Buch 
- Case #2 is not assigned to [trial session]
- Case #2 case details displays 
    - Place of Trial - [trial location]
    - Trial Date- not scheduled 
    - Assigned Judge - not assigned
