### ISSUE TITLE
Court User: Manually add a case after a trial session has been scheduled

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1195]
As a Court User, in order to add a case to a trial session after the trial session has already been populated with cases, I need the ability to manually add a case to a trial session.

After a trial session has been created and cases have been scheduled to that trial session, there may be a need to add one or two cases to the session.  If a case needs to be added to a trial session after the session is scheduled, it will have to be manually added to the session.  This manual addition of more cases does *not* affect any of the cases that were already scheduled to the trial session. A case manually scheduled for a trial session that is already at its max limit will not bump out another case. (e.g. If 100 cases was the limit that was set when the session was created and that session had 100 cases scheduled, the manually added case would allow for 101 cases)

## Pre-Conditions
* Trial session has already been created and cases are scheduled to the trial session

## Acceptance Criteria
* At any time after a trial session has been scheduled (up until the date of the trial session), a court user can manually add a case to a trial session
* Once a case is manually scheduled to a trial session, that case is associated with the trial session and should show up on the list of cases Active and All on the trial session
* Manual scheduling of a case does not affect any of the cases that were automatically scheduled for the session.
* Case can be scheduled for a session that is already at its max limit and other cases don't get bumped out. (e.g. If 100 cases was the limit that was set when the session was created and that session had 100 cases scheduled, the manually added case would allow for 101 cases)
* Once a case is automatically added to a trial session, the case status should change to "Calendared" 
* When a case is manually added, the judge and court need an indicator so that they can see what items were manually added to the trial session
* When a case is manually added to a trial session, it should show up in the trial session list sequentially based on docket number
* Replace wording on "Closed" tab with "Inactive"

## Notes
* Jessica's design thoughts on this: Docket Clerk would change the trial information on the Case Info tab to match a trial session and that would associate the case to that trial session and the case would now show up on the trial session list.
* No need to bubble manually added item to the top of the list

## Tasks
- [x] 1 Create endpoint for adding case to a trial session (interactor, lambda, proxy, serverless) (Cody #3336)
- [x] 2 Add to Trial Session modal, add to trial button on trial info card (Rachael #3338)
  - [x] 2a confirm sequence to call addCaseToTrialSession endpoint (Rachael #3341)
  - [x] 2b modal validation (Rachael #3341)
- [x] 3 Add icon to trial session tables to indicate the case was manually added (Cody #3337)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Case Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9bae8f96-a8a3-4e39-82e4-c243f84e1695)

**Add to Trial button**
* Display when a case 
    - is in ANY case status except "Calendared" 
    -does not have a Blocked flag 
* on click of Add to Trial button, display "Add to Trial" modal

#### Add to Trial Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ace42d58-b895-4d82-958f-d3695615cd38)

**Requested City Only** 
* is selected by default 
* if selected, trial session dropdown is populated with all upcoming trial sessions in the requested trial location on the case 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e4bbfe0c-c9c8-41e9-99d0-79b204159045)

**All Locations** 
* is selected by default 
* if selected, trial session dropdown is populated with all upcoming trial sessions for all trial locations 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6f195e56-66d6-4f15-a544-3410088beb7d)

**Select a Trial Session* 
* sessions display in the format [Trial Location] [Start Date] ([Session Type])
   example : Birmingham, Alabama 10/28/19 (R)
* Sessions types 
 - Regular = (R)
  - Small = (S)
  - Hybrid = (H) 
  - Special = (SP)
  - Motion/Hearing = (M/H)

* Sessions display sorted by location (alphabetically) and then by start date (chronologically)

**On Click of Add case**
* Modal closes 
* Success message displays 
* Case status updates to "Calendared" 
* Case is added to Open Cases under the selected trial session with indicator 
* trial information is populated on Case Detail page 
* "Add to Trial" and "Block from Trial" buttons are hidden on Case Detail 
* "Remove from Trial" button displays on Case detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1a9d52bc-1629-44a3-8263-72a60dcdbd7e)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/49bce103-cc85-495b-bc8a-72763ead567b)

#### Trial Session Detail 

* Case is added under Open Cases with indicator (green calendar icon) 
* Update label on "Closed Cases" tab to "Inactive Cases" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/69ff57f2-1345-4149-ae32-648afe954f41)

**Comment by klohman** [comment]
### 1195 Manually add a case to set trial session

Test Data:
    * CreateTrial Session
        * Birmingham, AL 
            * Start Date - 11/28/19
            * Regular case 
            * Judge Buch
        * Birmingham, AL 
            * Start Date - 2/14/20
            * Regular case 
        * Phoenix, AR 
            * Start Date 12/22/19
            * Regular 
            * Judge Ashford
        * Boston, MA
            * Start date 1/20/20
            * Small case 
    * Create Cases (all regular case procedure, all Birmingham, AL as requested place of trial)
        * Case 1 - General Docket (At Issue Ready for Trial) 
        * Case 2 - “General Docket - Not at issue” 
        * Case 3 - General Docket - Calendared (for Birmingham, AL session)
        * Case 4 - Blocked 

####  1) User sees “Add to Trial button when case status “General Docket (At Issue) Ready for Trial 
* Login as docket clerk 
* Navigate to Case 1 
* View Trial Info card 
Expected Results: 
- [ ] Trial Card displays as “Not Scheduled”
- [ ] “Add to Trial” button is displayed

####  2) User sees “Add to Trial button when case status “General Docket - Not at issue “
* Login as docket clerk 
* Navigate to Case 2 
* View Trial Info card 
Expected Results: 
- [ ] Trial Card displays as “Not Scheduled”
- [ ] “Add to Trial” button is displayed

#### 3) User cannot see “Add to Trial” button when case is Calendared 
* Login as docket clerk 
* Navigate to Case 3 
* View Trial Info card 
Expected Results: 
- [ ] Trial card displays as Calendared 
- [ ] “Add to Trial” button is not displayed

#### 4) User cannot see “Add to Trial” button when a case is blocked 
* Login as docket clerk 
* Navigate to Case 4 
* View Trial Info card 
Expected Results: 
- [ ] Trial card displays as Calendared 
- [ ] “Add to Trial” button is not displayed

#### 5a) User can select from all existing trial sessions 
* Scenario 1 
* Click Add to Trial button 
* Click Select Trial Location and view options  
Expected results 
- [ ] “Requested City Only” radio button is selected by default 
- [ ] Dropdown contains two options 
    - Birmingham, Alabama 11/28/19 (R)
    - Birmingham, Alabama 2/14/20 (S)

#### 5b) User can select from all existing trial sessions, sorted alphabetically by state, then city, then sorted chronologically by start date 
* Scenario 1 
* Click Add to Trial button 
* Select “All Locations” radio button 
* Click Select Trial Location and view options  
Expected results 
- [ ] Dropdown contains4 options 
    - Birmingham, Alabama 11/28/19 (R)
    - Birmingham, Alabama 2/14/20 (S)
    - Phoenix, Arizona 12/22/19 (R)
    - Boston, Massachusetts 1/20/20 (R)

#### 6) User adds case to a trial session in the Requested Trial Location 
* Scenario 1 
* Click Add to Trial location 
* Select Birmingham, Alabama 11/28/19 (R)
* Click Add case 
Expected results 
- [ ] Modal closes 
- [ ] Success message displays 
- [ ] Case status updates to “Calendared” 
- [ ] Trial information is populated 
    - Trial Date - 11/28/19
    - Assigned Judge - Buch
- [ ] Add to Trial button is hidden 
- [ ] Remove from trial button is displayed 

#### 7) User adds case to a trial session outside of the Requested Trial Location 
* Scenario 2
* Click Add to Trial location 
* Select Phoenix, Arizona 12/22/19 (R)
* Click Add case 
Expected results 
- [ ] Modal closes 
- [ ] Success message displays 
- [ ] Case status updates to “Calendared” 
- [ ] Trial card displays as Calendared 
    - Trial Date  - 12/22/19
    - Assigned Judge - Ashford
    - [ ] Place of Trial displays as Phoenix, Arizona 
- [ ] Requested Place of Trial field displays “Birmingham, Alabama” 
- [ ] Remove from trial button is displayed 

#### ) User sees manually added cases on trial session detail screen 
* Scenario 6
* Navigate to Birmingham, Alabama 11/28/19 session 
* View open cases 
Expected results 
- [ ] Case 1 is listed in Open Cases (in docket record order) 
- [ ] Case 1 has calendar icon displayed

**Comment by klohman** [comment]
UX Review comments

- Modal style is off? Do we ignore until the Modal Cleanup story? 
- Modal - Trial Session field retains the previously selected session - do we ignore until Modal Cleanup story? 

- Cannot add case to a trial session 
- Tried adding 112-19 to Birmingham, AL 11/28/19 - got “Unexpected Error” message and could not add 
- Tried adding 115-19 to Phoenix session - got “Unexpected Error” message and could not add
