### ISSUE TITLE
Court User: Manually remove a case from a trial session

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1196]
As a Court User, in order to appropriately account for cases that are closed or continued, I need the ability to remove a case from a trial session.

Once a case is scheduled for trial on a trial session, there may be a few reasons that case needs to be removed from the trial session.  The first reason is that the case settled.  In this instance, the case status would be changed to "Closed" and the case would automatically fall off/be removed from the trial session.  The second reason is if a case is continued.  If the parties are not ready to go to trial on the date the Court scheduled, they may ask the Court to "continue" the case.  If granted, this involves removing the case from the trial session and putting the case back into the general pool of cases ready to be scheduled for trial the next time the Court goes to that trial city, or moving the case to another trail session that has already been scheduled.

## Pre-Conditions
* A case is scheduled for trial on a trial session.

## Acceptance Criteria
* Court User should have the ability to manually remove a case from a trial session
*Once removed the status of the case needs to be set back to "General Docket - Ready for Trial" [Note: The case would get scheduled during the next automated scheduling or if it were manually scheduled]
* Even though a case gets removed, nothing is automatically scheduled to replace it [Note: Once a session is automatically scheduled, everything is manually added or removed after that]
* Court user needs the ability to type in the reason the case was removed from the trial session
* The reason the case was removed displays under disposition with the date. 
* Court user needs the ability to see all cases (both active and removed), see all active cases and see all cases that were removed

CREATE A NEW STORY: (#3351)
* Case is automatically removed from a trial session when it is closed. 
* Once a case is removed from a trial session, it shows up under "closed cases" for that trial session
* The reason the case was removed displays under disposition with the date. 
* Court user needs the ability to see all cases that were originally on trial calendar, see all active cases and see all cases that were removed

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* A case will automatically get removed from a trial session when it is closed. However, that functionality is being handled in the stip decision story (#114)

## Tasks
- [x] 1 Case detail layout updates (Rachael #3327)
  - [x] move Requested Place of Trial to petition details card (Rachael #3327)
  - [x] update trial card (Rachael #3327)
- [x] 2 Create Remove from Trial modal, sequence for opening (Cody #3326)
  - [x] sequence for opening
  - [x] validation
  - [x] submit sequence
- [x] 3 Endpoint for removing case from trial (interactor, lambda, proxy, serverless) (Rachael #3324)
- [x] 4 Add removeFromTrial method to case entity and disposition, removedFromTrial, removedFromTrialDate to trial session case order (Rachael #3324)
- [x] 5 Trial session tables layout updates (Rachael, Cody #3329)
- [x] 6 show spinners on modal submit for slow networks

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Case Detail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7d01fcde-71ae-40f9-b5ae-ed0164feb5b1)

* Add "Remove from Trial Session" button 
* Button is displayed only when case status = Calendared 
* Button is displayed only for internal users 
* on click of button, display Remove From Trial modal 

#### Remove From Trial modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/27fe3aab-b8d3-4750-a8eb-4673597becd5)

* Disposition field is required 
* Error message if left blank: "Enter a disposition" 
* On click of cancel, modal closes with no changes 

On click of "Remove case" 
* Modal closes and success message is displayed 
* Case status changes to "General Docket (At Issue) - Ready for Trial 
* Case is no longer displayed under Open Cases for trial session 
* Case is displayed under Closed Cases and All Cases on trial session detail 
* Trial session info is removed from Case Detail 
   - Trial Date  = Not scheduled 
   - Assigned Judge = Not assigned 
* "Remove from Trial Session" button is hidden 
* "Block from Trial" button is displayed 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1fbf8b1c-ecb1-47af-b560-073b2b6be382)

#### Trial Session detail 

**Update Closed Cases tab**
* Columns include Docket, Case name, Disposition, Disposition date 
* Disposition column is populated by "Disposition" field 
* Disposition date is populated with date case was removed from session 
* Cases are sorted by docket number (oldest to newest)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7cac882f-a23d-49af-9904-97b308cea805)

**Update All Cases tab**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4584290e-5475-4f51-81a6-07a676eea71a)
* Columns include Docket, Case name, Case status, Disposition, Disposition date 
* Disposition column is populated by "Disposition" field 
* Disposition date is populated with date case was removed from session 
* Cases are sorted by docket number (oldest to newest)

**Comment by klohman** [comment]
## 1196 Test Scenarios 

#### Scenario 1) User manually removes case from trial session 
* Login as docket clerk 
* Create 2 cases (Case 1 and case 2)
    * Place of Trial = Washington, DC 
    * Regular case 
    * Status = General Docket (At Issue) Ready for Trial 
* Create Trial session 
    * Washington, DC 
    * Regular case 
    * Start date 11/01/19
    * Judge Buch
* Set Calendar for Washington DC session
* Navigate to case 1 
* Click Remove From Trial, add disposition and save
Expected Results 
- [ ] Case 1 status changes from Calendared to General Docket (At Issue) Ready for Trial 
- [ ] Remove from trial button is hidden
- [ ] Block From Trial button is displayed 
- [ ] Trial date field updates to “Not scheduled” 
- [ ] Assigned judge field updates to “Not assigned” 

#### Scenario 2) User sees that removed cases do not appear on the Open Cases tab for trial session   
* [Scenario 1] 
* Navigate to Washington DC trial session 
* View Open Cases 
Expected results 
- [ ] Case 1 does not display under Open Cases 
- [ ] case 2 displays under Open Cases 

#### Scenario 3) User sees removed case displayed on trial session 
* Scenario 2
* Click on Closed Cases 
* Click on All Cases 
Expected Results 
- [ ] Case 1 displays on Closed Cases tab
- [ ] Case 1 and 2 display on All Cases tab


#### Scenario 4) User views disposition and date for removed cases 
* Scenario 1
* Navigate to Washington DC session 
* View Closed Cases 
* View All Cases 
Expected results 
- [ ] Case 1 disposition with today’s date is displayed in table 

#### Scenario x) Users sees that removed cases do not appear on the Judge’s Working Copy 
* Scenario 1
* Log in as Judge Buch
* Navigate to Washington DC Working Copy
Expected results 
- [ ] Case 1 does not display on Working Copy 
- [ ] Case 2 displays on Working Copy

**Comment by klohman** [comment]
#### Updates to "Block from Trial" designs 

**Default Trial card- Not Scheduled**
* Display when case status = all statuses EXCEPT Calendared 
* Display when case does not have a block flag 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6606b82c-1009-4e8d-a056-6931dfffa7b7)

* On click of Block from Trial, open modal (no changes) 

**Updated Trial card - Blocked From Trial**
When case is blocked: 
* Display updated Trial card 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e4ab54b5-3577-4fa5-bd7b-a19225c52482)

* On click of "remove block" - open Remove Block modal (no changes)
* When block is removed, display Default Trial Card

**Comment by klohman** [comment]
## 1196 Remove a Case from Trial Session 

#### Scenario 1) User sees trial information 
* Login as docket clerk 
* Create 2 cases (Case 1 and case 2)
    * Place of Trial = Washington, DC 
    * Regular case 
    * Status = General Docket (At Issue) Ready for Trial 
* Create Trial session 
    * Washington, DC 
    * Regular case 
    * Start date 11/01/19
    * Judge Buch
* Set Calendar for Washington DC session
* Navigate to case 1 
Expected results 
- [ ] Requested Place of Trial field = Washington, DC
- [ ] Trial card displays as “Calendared” 
- [ ] Trial date displays 11/01/19
- [ ] Assigned Judge displays Judge Buch 
- [ ] Place of Trial displays Washington, DC 
- [ ] Remove from Trial Session button displays 


#### Scenario 2) User manually removes case from trial session 
* Scenario 1 
* Click Remove From Trial Session, add disposition and save
Expected Results 
- [ ] Case 1 status changes from Calendared to General Docket (At Issue) Ready for Trial 
- [ ] Trial card displays as “Not Scheduled” 
- [ ] Block From Trial button is displayed 
- [ ] Trial date field is hidden
- [ ] Assigned judge field is hidden 
- [ ] Place of Trial field is hidden 

#### Scenario 3) User sees that removed cases do not appear on the Open Cases tab for trial session   
* [Scenario 2] 
* Navigate to Washington DC trial session 
* View Open Cases 
Expected results 
- [ ] Case 1 does not display under Open Cases 
- [ ] case 2 displays under Open Cases 

#### Scenario 4) User sees removed case displayed on trial session 
* Scenario 3
* Click on Closed Cases 
* Click on All Cases 
Expected Results 
- [ ] Case 1 displays on Closed Cases tab
- [ ] Case 1 and 2 display on All Cases tab

#### Scenario 5) User views disposition and date for removed cases 
* Scenario 2
* Navigate to Washington DC session 
* View Closed Cases 
* View All Cases 
Expected results 
- [ ] Case 1 disposition with today’s date is displayed in table 

#### Scenario 6) Users sees that removed cases do not appear on the Judge’s Working Copy 
* Scenario 2
* Log in as Judge Buch
* Navigate to Washington DC Working Copy
Expected results 
- [ ] Case 1 does not display on Working Copy 
- [ ] Case 2 displays on Working Copy

#### Scenario 7) User sees updated Blocked from Trial information 
* Scenario 2 
* Click Block from Trial and confirm 
* View Case Information 
Expected results 
- [ ] Trial card displays as “Blocked from Trial” 
- [ ] Reason for block displays 
- [ ] date of block displays 
- [ ] Remove block button displays
