### ISSUE TITLE
Practitioner: Filing a document for a client

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1213]
As a Practitioner, in order to file documents on behalf of my client, I need the ability to electronically file all of the same documents that a Petitioner can file, as well as some related to my representation.

A Practitioner stands in the place of a Petitioner.  As a result, a Practitioner needs the ability to file any document that a Petitioner can file.  In addition, a Practitioner needs the ability to file additional documents related to representation: Entry of Appearance, Substitution of Counsel, Motion to Withdrawal as Counsel.

## Pre-Conditions
* A case exists in the system.

## Acceptance Criteria
* A Practitioner can file all of the same documents (#269) and provide the same requested information for each document as a Petitioner.
* When filing by a Practitioner, the Practitioner has the ability to select who is filing, including themselves

## Tasks
- [x] 1. Change view of Parties Filing section based on user's role (Rachael #1471)
  - [x] 1a. Don't select a default party for practitioners (Rachael #1473)
- [x] 2. Update validation to allow partyPractitioner (William #1470)
- [x] 3. Add "Counsel" to docket record entry Filed By string (Rachael #1474)
- [x] 4. UX review notes
  - [x] 4a. Nonstandard document types are showing up in previous document dropdown and docket record document title without fully concatenated document title (Rachael #1487)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
@JessicaMarine 

## Document Category / Types for Practitioner and Respondent 

Practitioners have access to all document types in the second tab of the Event Code googlesheet- https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing

In addition to all of the document types that pro se petitioners can file, the practitioner and respondent user will be able to see the Appearance and Representation category. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/474b0a48-3742-4ecf-9238-4eaa713e97f4)

## FIle a Document form 

Practitioners will follow the same flow as pro se when filing a document in a case

### Party Information 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d964bf95-bb21-4b1e-9e9d-ea598fe42e03)

* Parties field is required. User must select at least one of these options  

For practitioner users, the parties should have the following options. 

- Myself as Petitioner's Counsel - this is the practitioner (user) associated with the case
- [Primary Contact Name] - display the name of the Primary Contact (same as on Case Info tab)
- [Secondary Contact Name] - display the secondary contact's name. If the case does not have a secondary contact, hide this option. 
- Respondent - this is the IRS attorney associated with the case. if there is no IRS attorney associated with the case yet, hide this option

**Comment by klohman** [comment]
## UX Review Notes 
### Document Type Selection 
For the nonstandard document types that require selecting a previous document, the document list should include the full concatenated document name
* Dropdown seems to only be showing the document type 

![Screen Shot 2019-04-23 at 3.04.53 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/65d0a669-d654-4fa5-8415-0376467248ec)

* When selecting the previous document, we need to display the full concatenated document name of the previous document as part of the document name 
(for example in screenshot below- the last document's name should be "Affidavit in Support of Statement **Stuffs**"

![Screen Shot 2019-04-23 at 3.04.40 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc267ced-fa87-405d-9055-3f869b54abd4)


### Respondent 
* When I logged in as respondent and filed an answer, it showed that the petitioner's counsel had  filed the answer, and did not show a Respondent associated with the case 
* The previous mechanism to associate a Respondent with a case after filing an answer was likely removed as part of the new filing process- we'll need to add this back in (perhaps as part of another story)
