### ISSUE TITLE
Judge: Manage work from Dashboard

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1272]
As a Judge, in order to manage my workload, I need to easily access everything from a central location.

A Judge will need to access and manage the trial sessions he/she has assigned to them.  They will also need to see any pending messages that they have that need attention.  It would be preferable for the Judge to be able to easily access all of this information from a central point.

## Pre-Conditions:
•	A Judge is a registered user in the system

## Acceptance Criteria:
•	Each Judge needs to easily see and access all of the work requiring his/her attention from a centralized point.

## Tasks
- [x] 1 create 'judge' role, seed data with role, cognito users with 'judge' role (Kris, Rachael #2641)
  - [x] 1a add actual judges to seed data (Kris, Rachael #2657)
  - [x] 1b pull in real judge users in messaging functionality (Kris, Rachael #2657)
  - [x] 1c pull in real judge users in trial session creation form (Rachael, #2658 )
  - [x] 1d Fix judge names on dev (they are currently all `Test judge`) (Rachael #2662)
  - [x] 1e Refactor `setup-cognito-users.sh` (Rachael #2678)
- [x] 2 Create Judge's Dashboard (Kris, Rachael #2641)
  - [x] 2a Create judge dashboard sequence & actions (Kris, Rachael, #2661)
  - [x] 2b Create "Recent Messages" table (Kris, Rachael #2661)
  - [x] 2c Create Upcoming/Recent Trial Sessions list (dashboard view) (Kris, Rachael, #2661)
  - [x] 2d Create messages in seed data for user `judgeArmen` (Rachael #2663)
- [x] 3 Create Upcoming Sessions Table (William #2649 #2653 #2655)
   - [x] 3a add filtering features to sessions table
   - [x] 3b trial sessions helpers to apply filters
- [x] 4 write computed to filter upcoming OR recent sessions (five each) (William #2671)
- [x] 5 create seed data to ensure we have some sessions both in the past and in the future to be displayed in the session summary lists (Kris #2667)
- [x] 6 Send judges messages in a few integration tests to further build out data for testing (Rachael #2677)
- [x] 7 Link to the full message inbox from the `View All Messages` link on the dashboard (Kris #2667)
- [x] 8 Filter recent messages to show only the most recent 5 messages (William #2675)
- [x] 9 App header/routing updates (Kris, William #2679)
  - [x] 9a Refactor messages route to separate dashboards from messages (Kris, William #2679)
  - [x] 9b Add home button to main app header for judges only (Kris, William #2679)
  - [x] 9c Update `headerHelper.js` to work with new routing updates and verify that the correct tab is selected on the judge's dashboard (Kris, William #2679)
- [x] 10 remove the underline from the home icon (William #2682)
- [x] 11 home messages don't show up when going from document qc to messages (William #2683)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by klohman** [comment]
### Judge's Dashboard 

* When user with the role of judge logs in, load Dashboard 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a44603f-f891-446b-8937-2754b7fb09cc)

#### Recent Messages 
* display 5 most recently received messages 
* On click of message document link, navigate to Document Detail with selected message highlighted 
* On click of View All Messages, navigate to "My Messages" screen 

#### Upcoming Trial Sessions 
* Display five upcoming trial sessions with user assigned as judge 
* On click of city link, open Session Working Copy (not developed yet) 
* On click of "View All" - navigate to Trial Sessions screen, Upcoming tab with judge filtered to the user 

#### Recent Trial Sessions 
* Display five most recent (past) trial sessions with user assigned as judge 
* On click of city link, open Session Working Copy (not developed yet) 
* On click of "View All" - navigate to Trial Sessions screen, Past tab with judge filtered to the user 
(tab not developed yet - will be part of #2155)

**Comment by rachaelparris** [comment]
Judge users created on dev:

```
judgeArmen@example.com
judgeAshford@example.com
judgeBuch@example.com
judgeCarluzzo@example.com
judgeCohen@example.com
```

**Comment by klohman** [comment]
### UX Review 

- [ ] Upcoming Trial Sessions is showing all upcoming - should only show next five

**Comment by klohman** [comment]
#### 1) Judge views new messages on Dashboard 
- Login as docketclerk1 
- Send 5 messages to judgeAshford 
- Login as judgeAshford
Expected Results 
- [x] Five new messages from docketclerk1 display on Dashboard 

#### 2) Judge views ONLY five most recent messages on Dashboard  
- [ Scenario 1] 
- Login as docket clerk1
- Send 1 message to judgeAshford 
- Login as judgeAshford 
Expected Results 
- [x] Five new messages from docketclerk1 display on Dashboard 
- [x] First (oldest) message is removed from dashboard 
- [x] All six messages are displays in the Messages > Inbox 


#### 3) Judge views 5 upcoming trial sessions
- Login as docketclerk1
- Create 6 upcoming trial sessions with judgeAshford assigned 
- Login as judgeAshford 
Expected results 
- [x] Five next upcoming trial sessions display on Dashboard 

#### 4) Judge accesses specific messages from Dashboard 
- [Scenario 1)
- Login as judgeAshford 
- Click on document message link  
Expected results 
- [x] Navigates to Document Detail screen for selected document 
- [x] Selected message is highlighted in In Progress messages 

#### 5) Judge accesses all messages from Dashboard 
- [Scenario 1)
- Login as judgeAshford 
- Click on View All Messages 
Expected results 
- [x] Navigates to Messages > Individual Inbox 

#### 6) Judge access all upcoming trial sessions from Dashboard 
- [ Scenario 3] 
- Login as judgeAshford 
- Click on “view All” link in Upcoming Trial Sessions section 
Expected Results 
- [x] Navigates to Upcoming Trial session screen 
- [x] Table is filtered by Judge Ashford 
- [x] 6 trial sessions display 


#### 7) Judge does not see completed /sent messages on Dashboard 
- [ Scenario 1 ] 
- Login as judgeAshford 
- Click on message 1 from Dashboard 
- Complete message 1 
- Return to Dashboard 
Expected Results 
- [x] Message 1 is removed from Dashboard
