### ISSUE TITLE
Judge/Trial Clerk: Case list-level notes 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1280]
As a Judge, in order to keep record of specific things related to a case, I need the ability to take notes at a case-level.

Before a Judge leaves DC to travel to a trial session, they may hold conference calls with the parties or have other notes that they want to make related to a specific case. The Judge needs these notes to be viewable to him/her and to whomever else he/she gives permission to.  These notes should display on the Judge's trial session list and be associated with the case to which they relate.

## Pre-Conditions
* A case has been calendared for trial on a trial session.
* A judge has been assigned to a trial session

## Acceptance Criteria
* Judge assigned to a trial session can take notes on the their working copy of the trial session (#1272) at the case level and the notes would also appear on the case detail page
* Judge can take notes at the case detail page and if they are the judge assigned to the trial session, the notes would also appear on the working copy 
* Any judge can take notes on any case detail page at any time but only ever see their own notes on the case detail page

## Notes
* Permissions are not part of this story. Just judge can see it on their working copy. They will be addressed in #1685
* Consider WYSIWYG editor from order generation? 

## Tasks
- [x] 1 add Notes to caseMetadata on TrialSessionWorkingCopy entity (Rachael #2774)
  - [x] 1a entity validation and tests (Rachael #2774)
- [x] 2 Create modal for adding/editing notes (William #2795)
  - [x] 2a sequences and actions for opening modal, handling change events (William #2795)
  - [x] 2b add validation for empty note (William #2795)
- [x] 3 Create modal for deleting notes (William #2795)
  - [x] 3a actions, sequences to delete note (William #2795)
- [x] 4 Table updates: "has note" and "does not have note" status (Kris, Rachael #2796)
  - [x] 4a actions and sequences connected to buttons for add note, delete note, edit note (William #2795)
- [x] 5 update Case Detail component with Judges Notes and add, edit, delete (Kris, #2800 )
  - [x] 5a actions, sequences connected to modal as in 2, 3 (William #2795)
- [x] 6 Action to retrieve notes from current case (Rachael #2793)
  - [x] 6a add to sequence leading to Case Details component (Rachael #2793)
 - [x] 7 Create seed data for Trial Session Working Copy for `judgeArmen` with at least one case in order to show things in the working copy table (Rachael #2801)
- [x] 8 Update to allow judges that are not associated with a trial session to create notes for cases on that trial session 
  - [x] 8a persistence methods for create, get, update, delete case notes (Rachael #2832)
  - [x] 8b endpoints, lambdas, interactors, proxies for case notes (Rachael #2834)
  - [x] 8c actions/sequences and frontend changes for case notes (William #2834)
  - [x] 8d update TrialSessionWorkingCopy and CaseNote entities (Rachael #2834)
  - [x] 8e create SessionNote entity with action, sequences, and interactor for validating session notes (Rachael #2834)

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William #2807)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Trial Session Working Copy 

#### Case Without Note 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/10778bbd-5c93-4fba-b3eb-75962b66bcc5)

* If no note has been added, display "Add Note" button 
* Hide note read-only field 
* on click of Add Note, display Add/Edit Note modal 

#### Case with Note 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e349462b-4788-4856-b77f-58c973c4dbab)
* Display note read-only in row below case information 
* Display "Edit Note" button 


#### Add/Edit Note Modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a511b0da-9bd8-419b-be55-e77f8c069799)

**Case Identifier**
* Display docket number and caption as sub-heading - [Docket Number]:[caseName]

**Judge's Notes**
* text area field 
* If note exists, populate existing note in text field 

**on Save**
* Modal closes 
* Note is displayed read-only below case info 
* "Add Note" button is hidden for case 
* "Edit Note" button displays on case row 
* Note displays on both Working Copy case row and on the Case Detail page under Notes tab

**on Cancel**
*Modal closes, returns to parent page with no changes

**on Delete Note**
* Modal closes 
* Note is removed from case row 
* "Add Note" button is displayed 

### Case Detail screen 
* add new "Notes" tab to docket record tab set 

#### Case without Note 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dca6462c-2804-47cd-b64a-66c06fce8836)
* Display "Add Note" button 
* On click of "Add Note" , display Add/Edit Note modal 

#### Case With Note 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6d0f1dce-1e19-41d8-9234-ce24932e1612)

* Display read-only note 
* Display "Edit Note" button 
* On click of "Edit Note", display Add/Edit Note modal

**Comment by klohman** [comment]
### 1280 Judge- Case list Level Notes - Test Scenarios 

#### 1) Judge adds a note on a case from the Working Copy 
- Login as docketclerk1
- Create trial session with Judge Cohen assigned 
- Set 4 cases for trial session 
- Login as judgeCohen 
- Navigate to trial session Working Copy
- Click add note on case 1 
- Enter text in note field 
- Click save  
Expected Results 
- [ ] On click of Add Note, modal displays 
- [ ] On click of Save, modal closes 
- [ ] Saved note is displayed on Working Copy 

#### 2) Judge adds a note on a case from the Case Detail screen 
- [ Scenario 1] 
- Click docket number from case 2 on Working Copy 
- Click Notes tab 
- Click Add Note 
- Enter text in note field 
- Click save 
Results 
- [ ] On click of Add Note, modal displays 
- [ ] On click of Save, modal closes 
- [ ] Saved note is displayed on Case Detail 

#### 3) Judge edits note on a case from the Working Copy 
- [ Scenario 1]
- Click on Edit Note for case 1 
- Enter additional text in note field
- Click save 
Results 
- [ ] On click of Edit, modal displays 
- [ ] Existing note is populated in the notes field 
- [ ] On Save, modal closes 
- [ ] Saved note is displayed on Working Copy 

#### 4) Judge edits a note on a case from the Case Detail screen 
- [ Scenario 2] 
- Click Edit Note 
- Enter additional text to notes field 
- Click save 
Results 
- [ ] On click of Edit Note, modal displays 
- [ ] Existing note is populated in the notes field 
- [ ] On Save, modal closes 
- [ ] Saved note is displayed on Case Detail screen 

#### 5) Judge views note entered on Case Detail on Working Copy 
- Login as judgeCohen
- Navigate to Working Copy 
- Click docket number for case 3 
- Open Notes tab 
- Click Add Note 
- Enter note text 
- Save
- Navigate to Working Copy  
Results 
- [ ] Saved note is displayed on Case Detail screen
- [ ] Save note is displayed on Working Copy

#### 6) Judge views note entered on Working Copy on Case Detail screen 
- Login as judgeCohen
- Navigate to Working Copy
- Click Add Note on case 4
- Enter note text 
- Save
- Click on docket number on case 4 
Results 
- [ ] Saved note is displayed on Case Detail screen
- [ ] Saved note is displayed on Working Copy

#### 7) Judge cannot view notes added by another judge 
- Login as judgeBuch
- Search for case 1 by docket number 
- Navigate to Case Detail page for case 1
- Open Notes 
Results 
- [ ] Judge’s note card is hidden 

#### 8) Cancel note changes 
- Judge navigates to Working Copy 
- Click Add Note 
- Click Cancel 
Results 
- [ ] On click of Cancel, modal closes 
- [ ] no changes to notes field are saved 

#### 9) Delete note from Working Copy 
- Judge navigates to Working Copy 
- Click Delete Note 
- Click “yes, delete” button 
Results 
- On click of “Delete Note” , modal displays 
- On click of “yes, delete”, modal closes 
- Note is removed from Working Copy 
- Add Note button is displayed on Working Copy
- Note is removed from Case Detail Notes tab
- Add Note button is displayed on Case Detail Notes tab

#### 10) Delete note from Case Detail screen 
- Judge navigates to Case Detail  
- Click Delete Note 
- Click “yes, delete” button 
Results 
- On click of “Delete Note” , modal displays 
- On click of “yes, delete”, modal closes 
- Note is removed from Case Detail Notes tab
- Add Note button is displayed on Case Detail Notes tab
- Note is removed from Working Copy 
- Add Note button is displayed on Working Copy

**Comment by klohman** [comment]
UX Review Comments 

- [ ] Add/Edit Modal should not close when you click outside - should only close on click of the action button or "close" link 
- [ ] Getting Error 404 page when clicking on docket number or searching for cases that are assigned to another judge (Example- click on 556-19W when logged in as Judge Cohen and it takes me to Case Detail; when I log in as Judge Buch and click on 556-19W- I get 404 Error)
