### ISSUE TITLE
Judge: Session-related logistical notes

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1281]
As a Judge, in order to capture information related to the trial session (and not a specific case), I need the ability to add session-related logistical notes to the trial session list (the working copy of the trail session will be worked out in #1272).

In addition to taking notes on specific cases, a Judge may also need to include logistical notes at the session level (i.e. travel plans, hotel, note about the trial location - anything you don't want to forget).  These notes should only be viewable to the Judge.

## Pre-Conditions
* Trial session has been created and assigned to a Judge.

## Acceptance Criteria
* Judge has ability to take logistical notes at the session level (i.e. travel plans, hotel, note about the trial location - anything you don't want to forget)

## Notes
* Permissions is not part of this story.  It will be handled in #1685

## Tasks
- [x] 1 Session Notes Card (Rachael #2822)
  - [x] 1a Connect Sequences to Buttons (William #2826)
- [x] 2 Session Notes Modal (William #2826)
  - [x] 2a Sequences for opening modal / updating sessions working copy. (William #2826)
- [x] 3 add session notes to working copy entity (Rachael #2815)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by klohman** [comment]
### Session Working Copy 

**No Judge Session Note**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7db6e88f-efc4-419a-8bfd-21efd103772f)

* Display note card above the case table filters 
* On click of "Add Note" button, open Add / Edit Session Note modal 

**With Judge Session Notes**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cdb72f3e-1511-4760-aeff-f4a60d67a9d0)

* Hide "Add Note" button
* Display "Edit Note" and "Delete Note" buttons
* On click of "Edit Note" button, open Add/Edit Session Note modal 
* On click of "Delete Note", display Delete confirmation modal

**Add / Edit Session Note Modal**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/10b260e9-82bc-4c04-b113-6352d0f260b1)

**Session Identifier**
* Display session start date and location(format [mm/dd/yy]: [City, State]

**Judge's Notes**
* text area field
* If note exists, populate existing note in text field

**on Save**
* Modal closes
* Note is displayed read-only in Session Notes card 
* "Add Note" button is hidden 
* "Edit Note" button displays 
* "Delete Note" button displays

**on Cancel**
*Modal closes, returns to parent page with no changes

**Comment by klohman** [comment]
### 1281 Session Notes Test Scenarios 

**1) Judge sees option to add a session note to an assigned trial session**
* Create Washington, DC trial session with Judge Cohen assigned 
* Set calendar for trial session 
* Login as Judge Cohen 
* Click on Washington, DC session from dashboard
Results 
- [ ] on click of Washington, DC, navigates to Working Copy 
- [ ] Session notes card is visible with “Add Note” button 

**2)Judge Adds a Session Note**
* [ scenario 1] 
* Click Add Note 
* Enter text in Judge’s Notes  
* Click Save 
Results 
- [ ] Add Note modal displays
- [ ] Judge’s notes field is empty 
- [ ] On save, modal closes, returning to Working Copy  
- [ ] On save, note displays read-only in Session Notes card 
- [ ] Add Note button is hidden on Session Note card 
- [ ] Edit Note button is shown on Session notes card
- [ ] Delete note button is shown on Session notes card 

**3) Judge cancels out of note form**
* [ scenario 1] 
* Click “Add Note” 
* Enter text in “Judge’s Note”
* Click Cancel
Results
- [ ] On cancel, modal closes 
- [ ] No note is displayed 
- [ ] Add Note button is still displayed

**4)Judge Edits a Session Note**
* [scenario 2]
* Click “Edit Note” 
* Make change to text in “judge’s note” 
* Click Save 
Results 
- [ ] On click of “edit note”, Add/ Edit Note modal opens
- [ ] Existing note text is populated in the Judge’s Notes field 
- [ ] On save, modal closes, returning to Working Copy 
- [ ] On save, updated note text displays read-only in session notes card
- [ ] Add Note button is hidden on Session Note card 
- [ ] Edit Note button is shown on Session notes card
- [ ] Delete note button is shown on Session notes card 


**5)Judge deletes Session Note** 
* [scenario 2]
* Click on Delete Note 
* Click “yes, delete” 
Results 
- [ ] On click of Delete Note button, delete confirmation modal display s
- [ ] On click of yes, delete, modal closes, returning to Working Copy 
- [ ] On click of yes, No note is displayed 
- [ ] On click of yes, Add Note button is still displayed

**6) Judge cannot view session note from an unassigned trial session**
* [scenario 1] 
* Log out as Judge Cohen
* Log in as Judge Buch 
* Click on Trial Sessions 
* Click on Washington, DC session 
Results 
- [ ] on click of Washington, DC session, standard Trial Session Detail page displays 
- [ ] Judge Cohen’s note is not visible
