### ISSUE TITLE
Petitions Clerk: New Flow for Paper Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1299]
As a Petitions Clerk, so that I may have record of the Petitioner's original petition data, I need the ability to enter data for a paper-filing petitioner as it appears on the paper petitions and then correct it in the system.
 Possibly combine with #1895

## Pre-Conditions
* Petitioner submitted a paper Petition 

## Acceptance Criteria
* Petitions Clerk can enter and save original paper petition data into the system before the QC process.
* Original paper petition data is retained for record (in audit logs, which is already being done)
* New Petition appears in the Petitions Section Document QC after all metadata is entered AND petition has been scanned (#1895)
* Any petitions Clerk can change the entered data as part of the QC process

## Tasks
- [x] 1 Move Create Case button (Kris #2451)
- [x] 2 Update form on create case page (Rachael #2453)
- [x] 3 Update validation for creating case from paper (William #2459)
- [x] 4 Verify that cancel modal appears when cancelling the form (Kris)
- [x] 5 Verify that work items appear where they should after submit (Rachael)
- [x] 6 Update submit sequence for creating case from paper (William #2459)
- [x] 7 Update Filed By to use the contact primary name or business name instead of case caption (Rachael #2465)
- [x] 8 Update integration test (William #2467)
- [x] 9 Switch Filed By back to use the case caption entered (Rachael #2469)
- [x] 10 Filed date and received date should be Date Received from form (Rachael #2469)
- [x] 11 Optional phone number (William #2481)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael #2484)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by uxforgood** [comment]
Bug Note: Found two bugs in the current paper petition filing flow when entering them from Europe (since they are time-based the issue may be a time zone thing, though both were created when it was 06/18/19 in both Europe and the US)

-

**Comment by uxforgood** [comment]
## Design Notes

### Dashboard
- Add "Create Case" button to Section and Individual QC screens for Petitions and Docket (remove from Messages screens)
- User presses button and navigates to Create Case form 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/a6d51791-1e7b-4f91-8f53-12b6f6f405a9)

### Create Case page
- User must complete all required fields (all optional fields are marked as such in the design) 
- If user clicks on "Cancel" link, display "are you sure you want to cancel?" model 
- When user clicks "Finish": 
    - Case is created and docket number assigned
    - Docket entry is created for Petition and any other document uploaded (STIN, ODS, Request for Place of Trial each have their own docket entry)
    - The time and date the user clicked "Finish" is what populates in the Received column in the QC table
    - User is taken to the document detail page for that Petition 
- All case metadata entered on the Create Case form appears in the Petition Doc Detail 
- Petition appears in the Petitions Section Document QC and is assigned to the initiating petitions clerk
- Petition appears in the initiating petitions clerk My Document QC 
- On Petition Document Detail page, the "Filed by..." metadata in the page header should populate with the data from either the Name or Business Name field

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c7d680c7-791a-40d7-98b0-7b23044d80c4)

**Comment by klohman** [comment]
Updates from design call 7/23 

- Filed by date is the Date Received (time set to midnight EST)
- Filed by "party" will populate with whatever is manually entered in the case caption field on the Petition form

**Comment by klohman** [comment]
### 1299 Testing 

#### 1)  Petitions Clerk can enter and save original paper petition data into the system before the QC process.
- Log in as petitionsclerk1
- Click Create Case 
- Enter all required fields 
    - Upload petition 
    - Enter date received 07/19/2019
    - Enter case caption - John Smith, Petitioner 
    - Enter case type - CDP 
    - Regular case procedure 
    - Party type - Petitioner and Spouse 
    - Enter all required contact fields 
- Submit form 

Expected Results 
- [ ] On submit of petition form, app navigates to Petition QC Document Detail screen 
- [ ] Filed by displays as “Filed 07/19/2019 by John Smith, Petitioner” 
- [ ] Case Caption displays as John Smith, Petitioner 
- [ ] Docket number displays “L” 
- [ ] Petition metadata appears as entered on petition form 

#### 2) New Petition appears in the Petitions Section Document QC after all metadata is entered AND petition has been scanned (#1895)
- Follow scenario 1 
- Navigate to Petitions Section Document QC 
- Navigate to My Document QC 

Expected Results 
- [ ] New petition displays in Petitions Section Document QC 
- [ ] New petition Filed By displays as “John Smith, Petitioner” 
- [ ] New petition received date displays as “07/19/2019”
- [ ] New petition “ Assigned To” displays as petitionsclerk1 
- [ ] New petition displays in My Document QC 


#### 3) Any petitions Clerk can change the entered data as part of the QC process
- Follow scenario 1 
- Log out as petitionsclerk1
- Log in as petitionsclerk2 
- Navigate to Petitions Section Document QC 
- Click on the newly created petition 
- Change case from Regular to Small case 
- Change case type to Deficiency 
- Change case caption to “John Smith & Nicole Smith, Petitioners
- Save changes  
- Log out as petitions clerk2 
- Log in as petitions clerk 3
- Navigate to Petitions Section Document QC 
- Click on the newly created petition 
 Expected Results 
- [ ] petitions clerk2 is able to access the paper petition created by petitionsclerk1 from the Petitions Section Document QC 
- [ ] petitionsclerk2 is able to make and save changes to the paper petition created by petitions clerk1
- [ ] petitionsclerk3 is able to view saved changes made by petitionsclerk2 


#### 4) Original paper petition data is retained for record (in audit logs, which is already being done)
- Follow scenario 3 
- View audit logs 

Expected Results 
- [ ] Entered petition metadata is saved to case when petition form is submitted 
- [ ] Changes to petition metadata is captured in audit log 

#### 5) Petition clerk cannot submit petition form with errors 
- Log in as petitionsclerk1
- Navigate to Document QC
- Click Create Case 
- Select “Petitioner” as Party type 
- Click Finish  

Expected results 
- [ ] Errors trigger on all required fields 
    - Upload Your Petition 
    - Date Received 
    - Case Caption 
    - Notice/Case Type
    - Case procedure 
    - Name 
    - Mailing Address Line 1 
    - City 
    - State 
    - ZIP Code
