### ISSUE TITLE
Internal User: Manually add attorney to case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1324]
As an Internal User, in order to make sure all of the counsel of record are properly associated with the case, I need the ability to add Practitioners to a case.

If a Practitioner files a Petition for a Petitioner, only the Practitioner logged into the system will be recognized as the attorney of record and be associated with the case.  However, there are many times when *multiple* attorneys have signed a petition (usually multiple attorneys from the same law firm).  In those cases, the Petitions Clerk needs a way to manually add the other attorneys to the case.

Additionally, other Court users may need to manually add a Practitioner to a case at other times.

## Pre-Conditions
* The Practitioner has been admitted to the Tax Court Bar and has a CMS account

## Acceptance Criteria
* Internal User can search for and select an attorney from a list of practitioners
* Once identified, Internal user can add that attorney to a case
* The CMS needs the ability for more than 1 attorney to be associated with a single party
* If there is more than one Petitioner, the Internal User should be able to notate which petitioner(s) each Practitioner is representing.
* When a practitioner is added to a case:
   * the practitioner can see/access the documents in the case
   * the practitioner's data is viewable to other parties and internal Court Users on the Case Info tab 
   * the case should show up on the Practitioner's dashboard.
   * Practitioner receives any future electronic service

## Notes:
* Need to create some more practitioners in Cognito and Dynamo to test this

## Tasks:
- [x] 1 Build out some users locally and in cognito with different bar numbers and names for practitioners and respondents (Rachael #2560)
- [x] 2 Persistence methods, interactors, and endpoints for searching for practitioners/respondents by bar number or name (Rachael #2591 #2593)
- [x] 3 Actions and sequences for searching for practitioners/respondents (Rachael #2597)
- [x] 4 Persistence methods, interactors, and endpoints for associating practitioners/respondents to case (William #2570 #2583 #2578)
- [x] 5 Actions and sequences for associating practitioners/respondents to case (William #2583 #2578)
- [x] 6 Update case detail case information tab upper portion with new card setup (Rachael #2569)
- [x] 7 Add views for Petitioner Counsel and Respondent Counsel sections (Rachael #2569)
- [x] 8 Create modal for adding counsel (Rachael #2573)
- [x] 9 Create association between practitioners and individual parties on the case (they are currently just associated with an entire case) (Rachael #2602)
- [x] 10 Update printable case detail view (Rachael #2581)
- [x] 11 Validation for add counsel modals (William #2615)
- [x] 12 Show error state on search box when no matches are found (Rachael #2599)
- [x] 13 Journey/integration tests (Rachael #2604 #2611)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by tjcurington** [comment]
Copied from 1071
* Docket Clerk can manually associate a Practitioner with a case [similar to functionality #1324]
* Once a Practitioner is associated with a case, the Practitioner can see everything in the case and their data is viewable to other parties and internal Court Users on the Case Info tab, and that case should show up on the Practitioner's dashboard.

**Comment by klohman** [comment]
## Practitioner Data
* Fields needed for practitioner 
    * Name 
    * Bar Number 
    * Firm (optional)
    * Address Line 1 
    * Address Line 2 (optional)
    * City
    * State
    * Zip
    * Phone
    * Email - this is the cognate username/id 
    * Flag identifying attorney as practitioner (petitioner counsel)

## Respondent Counsel Data
* Fields needed for practitioner 
    * Name 
    * Bar Number 
    * Firm (optional)
    * Address Line 1 
    * Address Line 2 (optional)
    * City
    * State
    * Zip
    * Phone
    * Email - this is the cognate username/id 
    * Flag identifying attorney as respondent counsel 

## Updated Case Detail - Case Information tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c000a390-c102-4004-8e7c-1a1e2f2d7741)

#### Petitioner Info Section
* Display party type as section (e.g. “Petitioner and Spouse” shown in design) 

#### Petitioner Counsel section
If petitioner has no counsel 
* display header, with “Add Counsel” and search bar, no edit link

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0920b623-0297-40ff-b79c-c15a7c5d9416)

If petitioner has counsel 
* Display practitioner contact information 
    * Append bar number in parentheses behind practitioner name
* Display “Representing” with unordered list of all parties the counsel is representing 

**Add Counsel**
* Ability to search by attorney bar number or attorney name 
* Scope search to practitioner data only 
* If no matches found, display error: “No matching counsel was found. Check your information and try again.”
* If one or more matches are found, display “Add Petitioner Counsel” modal


#### Respondent Counsel** 
If no respondent is associated, 
* Display header with “Add Counsel” and search bar, no edit link

If respondent is associated, 
* Display practitioner contact information 
    * Append bar number in parentheses behind practitioner name

****Add Counsel**
* Ability to search by attorney bar number or attorney name 
* Scope search to respondent data only 
* If no matches found, display error: “No matching counsel was found. Check your information and try again.”
* If one or more matches are found, display “Add Respondent Counsel” modal

#### Add Petitioner Counsel modal 
**Matching Counsel** 
    * If one match was found 
        * Display counsel information (read-only)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d55db918-64d7-498b-9355-12bc4f41b7f7)

    * If two or more matches are found 
        * Display radio button options for each counsel 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/65c88b96-932a-4437-9491-e084ace4510a)
        * Note: Modal should have vertical scroll
* Who is This Counsel Representing 
    * Required field 
    * Options include all petitioners 
        * Primary Contact 
        * Secondary Contact (ONLY for party type - “petitioner and spouse” and “petitioner and deceased spouse” 
    * If no party is selected, on click of “Add to Case” display error “You must select a party to represent.”
* Add to Case button 
    * On click, if all required fields are completed
        * Modal closes, and parent page refreshes with new counsel displayed under Petitioner Counsel section 
        * Selected practitioner is associated with the case AND the parties selected 
        * Success message is displayed : “Petitioner Counsel has been added to this case. You can view counsel information below. 
* Cancel button
    * On click, changes are discarded, modal closes

#### Add Respondent Counsel modal 

** Matching Counsel**
    * If one match was found 
        * Display counsel information (read-only)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0d25708c-eaff-441c-bde8-1950eb8efe9b)

    * If two or more matches are found 
        * Display radio button options for each counsel 
        * Required field 
        * Note: Modal should have vertical scroll

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/27c447b4-ec1c-4356-a18d-5f93978a4412)

* Add to Case button 
    * On click, if all required fields are completed
        * Modal closes, and parent page refreshes with new counsel displayed under Respondent Counsel section 
        * Selected respondent counsel is associated with the case as IRS attorney
        * Success message is displayed : “Respondent Counsel has been added to this case. You can view counsel information below. 
* Cancel button
    * On click, changes are discarded, modal closes

#### Success Message 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5e242ad3-b87b-4d54-a7c7-747328f0882d)

#### No results error
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/91db5d82-e53f-4f13-9c93-a21e5f08211a)

#### Updated Case Detail - External Party Views 
* see figma file for updated design 

#### Printable Docket Sheet - Update Party Information Section 
* see figma for updated design

**Comment by rachaelparris** [comment]
Test users on dev:
```
practitioner1@example.com  Test Practitioner1  PT1234
practitioner2@example.com  Test Practitioner2  PT5432
practitioner3@example.com  Test Practitioner3  PT1111
practitioner4@example.com  Test Practitioner4  PT2222
practitioner5@example.com  Test Practitioner5  PT3333

respondent1@example.com  Test Respondent1  RT6789
respondent2@example.com  Test Respondent2  RT0987
respondent3@example.com  Test Respondent3  RT7777
respondent4@example.com  Test Respondent4  RT8888
respondent5@example.com  Test Respondent5  RT9999
```

**Comment by klohman** [comment]
UX Notes 
- [ ] Change placeholder text to “Bar number or Name” 
- [ ] Can we clear the search bar when counsel has been added?
