### ISSUE TITLE
Internal User: Manually remove practitioner from case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1325]
As a Court user, in order to make sure the appropriate Practitioners are associated with a case, I need the ability to manually remove Practitioners from a case. 

An internal user needs the ability to manually remove an attorney/practitioner from a case at any time.  This most often happens when a Substitution of Counsel is filed or there are disciplinary actions.

## Pre-Conditions
*  A Practitioner is associated with a case and a court user needs to disassociate them

## Acceptance Criteria
* Internal court user can manually remove a practitioner from a case.
* User can edit the parties they are representing (see note)
* When a practitioner is removed, the practitioner can no longer access the documents in the case and the practitioner's data is no longer viewable to other parties or internal Court Users on the Case Info tab.
* After a Practitioner is disassociated with a case, that case should no longer show up on the Practitioner's dashboard.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes 
* Bug to fix: If you add a practitioner to a case representing 1 of 2 petitioners, then try to add the same practitioner for the 2nd petitioner, the success message displays but the representing info does not update to include petitioner 2. I would expect that if I search for the same practitioner, any currently represented parties would be pre-checked and that checking unrepresented parties would add them to the practitioners representation info
* Make sure service info still functions when practitioner is removed, so that no data is sent to a removed practitioner.

## Tasks
- [x] 1 Add Edit link to petitioner counsel and respondent counsel cards on case detail page (Rachael #3263)
- [x] 2 Edit Petitioner/Respondent Counsel modal views (Rachael #3270)
  - [x] 2a Sequences, actions to handle opening and closing the modals (Rachael #3270)
- [x] 3 Add methods to Case entity for removing and updating respondents and practitioners (see `attachRespondent`) (Matt #3261)
- [x] 4 Create persistence method to remove the user/case mapping record (see `associateUserWithCase`) (Matt #3264)
- [x] 5 Create endpoint to handle submitting the edit counsel modals, calling the correct methods on the entity, updating the case, and calling disassociateUserWithCase method when appropriate (Matt #3269)
- [x] 6 Sequences and actions to handle validating and submitting the modals (Rachael, Cody #3272)
~- [ ] 7 Refactor updateCounselOnCaseInteractor to only update practitioners (respondents can't be updated, only deleted)~
- [x] 8 Validation for edit practitioner modal (Rachael #3273)
- [x] 9 Update Add Counsel modals to disable selecting a counsel that has already been added to the case (Cody)
- [x] 10 Edit counsel in journey tests (Rachael #3275)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Petitioner Counsel 
* On click of “Edit” link , open Edit Petitioner Counsel modal 
￼![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/60c75dd1-4c84-4694-93f3-6c6ccb0a4b2a)

### Edit Petitioner Counsel modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2f24bfd8-cc72-495c-bcf1-d6468cc7b8aa)

Display all petitioner counsel associated with case 
* Name (bar number) 
* Representing 
    * List parties on the case (excluding respondent) 
        * Petitioner - primary contact  
        * Petitioner - secondary contact ONLY when the party type is “petitioner and spouse” or “petitioner and deceased spouse” 
    * Parties currently associated with the counsel should be checked by default 
    * Field is required - at least ONE party must be selected
* Remove From Case checkbox
    * Optional
    * If checked, when Apply Changes is clicked, the selected counsel will be removed from the case 
* Apply Changes button 
    * On click, validate no required fields are missing 
    * Updates to parties selected will be applied to counsel 
    * If “Remove from Case” checkbox is selected
        * the counsel should be removed from the case
        * Counsel will no longer be displayed under Petitioner Counsel section
        * Case will no longer display on practitioner’s dashboard 
        * Practitioner will no longer have full access to case 
    * Modal closes, and parent page refreshes with success message 
        * Success Message “ Petitioner Counsel has been updated. You can view your changes below.” 


### Respondent Counsel 
* On click of “Edit” link , open Edit Respondent Counsel modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97beaf75-b545-4227-94fc-41b54ba08473)

### Edit Respondent Counsel modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fe77dd4a-18d7-49d6-9e6a-a3970b584ba8)

Display all petitioner counsel associated with case 
* Name (bar number) 

* Remove From Case checkbox
    * Optional
    * If checked, when Apply Changes is clicked, the selected counsel will be removed from the case 
* Apply Changes button 
    * On click, validate no required fields are missing 
    * If “Remove from Case” checkbox is selected
        * the counsel should be removed from the case
        * Counsel will no longer be displayed under Respondent Counsel section
        * Case will no longer display on practitioner’s dashboard 
        * Respondent counsel will no longer have full access to case 
    * Modal closes, and parent page refreshes with success message 
        * Success Message “ Respondent Counsel has been updated. You can view your changes below.”

**Comment by klohman** [comment]
### 1325 Test Scenarios 

#### 1) Clerk removes petitioner counsel from case 
* Assumption: Case xxx-xx has 1 petitioner counsel (practitioner1)
* Login as docket clerk 
* Navigate to case xxx-xx
* Remove petitioner counsel 
Expected Results 
- [ ] On click of “Edit” petitioner counsel, Edit Petitioner Counsel modal displays 
On click of Apply Changes
- [ ] , modal closes 
- [ ] success message displays
- [ ] Petitioner counsel is not displayed under Petitioner Counsel Information 

#### 2) Clerk removes respondent counsel from case (respondent1)
* Assumption: Case xxx-xx has 1 respondent counsel 
* Login as docket clerk 
* Navigate to case xxx-xx
* Remove respondent counsel 
Expected Results 
- [ ] On click of “Edit” petitioner counsel, Edit Respondent Counsel modal displays 
On click of Apply Changes
- [ ] , modal closes 
- [ ] success message displays
- [ ] Respondent counsel is not displayed under Respondent Counsel Information 

#### 3) Clerk updates parties represented for petitioner counsel 
* Assumption: Case xxx-xx
    * Petitioner & Spouse - Joe and Mary Lloyd 
    * Petitioner Counsel 1 - representing Joe Lloyd
    * Petitioner Counsel 2 - representing Mary Lloyd 
* Login as docket clerk 
* Navigate to case xxx-xx
* Update Petitioner Counsel 1 to represent both petitioners 
Expected results: 
On click of Apply Changes
- [ ] , modal closes 
- [ ] success message displays 
- [ ] Petitioner counsel 1 is displayed, representing Joe and Mary Lloyd 
- [ ] Petitioner Counsel 2 is displayed, representing Mary Lloyd 

#### 4a) Petitioner counsel is removed 
* Login as practitioner 1 
* Click on case xxx-xx
Expected results 
- [ ] users sees case xxx-xx listed on their dashboard 
- [ ] user has access to all filings in case xxx-xx

#### 4b)
* [Scenario 1] 
* Login as practitioner1
* Search for case-xxx-xx
Expected results 
- [ ] Case xxx-xx is not in  case list on practitioner dashboard 
- [ ] user sees “Request Access” button on Case Detail page 
- [ ] User does not have access to case filings 
 
#### 5a) Respondent counsel is removed from case 
* Login as respondent 1 
* Click on case xxx-xx
Expected results 
- [ ] users sees case xxx-xx listed on their dashboard 
- [ ] user has access to all filings in case xxx-xx

#### 5b)
* [Scenario 2] 
* Login as respondent1
* Search for case-xxx-xx
Expected results 
- [ ] Case xxx-xx is not in  case list on dashboard 
- [ ] user sees “Request Access” button on Case Detail page 
- [ ] User does not have access to case filings

**Comment by klohman** [comment]
UX Review 

* When modals close and success message displays, the screen is not scrolling back to top 
(should apply to all add and edit - anything with a success message)
