### ISSUE TITLE
Petition & Docket Sections: Different inbox for external messages

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1335]
As a Docket or Petition Clerk, in order to manage the volume of external messages generated by external filings, I need a place to manage these external filings that is separate from internal messages. 

The Docket Section is the main traffic controller for all documents coming into and out of the Court.  Every externally-filed document (except a Petition) is routed through docket, and all internally-created documents (Orders, Notices, Opinions, Decisions) are routed through docket.  In order to manage the internal versus external message, especially in light of the high volume of each, it is important that the internal and external messages are kept separate.  As a result, the Docket Section needs to manage external messages separately from the rest of their work. Petition Section also needs a way to see petitions that need QC separately from internal messages they receive. 

MARIAH'S TEST SCENARIOS DOC: https://docs.google.com/document/d/1GH3SRt5-vD2rXAzCzlvQLT97BjfvXYa7WVRMwXds22M/edit?usp=sharing

## Pre-Conditions:
* A party has filed a Petition to start a new case or document in an existing case

### QC Box
* The external document is routed to: Petition Section if it's a petition, the Docket Section if it's any other type of external document
* The external document displays in the Document QC queue that is separate from the queue for internal messages
* Once the QC is complete, the document should move out of QC "inbox" and to: For Petitions goes to "Batched for IRS" tab; for Docket goes to "Processed" tab (Docket QC and "processed" requirements to be completed in #991)
* Documents pending in the Docket Section QC Inbox need to be viewable to other Court users (Judges, Senior Attys, etc.)
* Petitions and Docket clerks can see if QC items in their personal QC inbox are read/unread
* Petitions and Docket clerks can see if a QC item is unassigned in the section QC inbox 
* Petitions and Docket clerks can bulk assign QC items in the Section QC box to another clerk in their section 
* Petitions and Docket clerks can toggle between their personal QC box and Section QC box
* Petitions and Docket clerks can see how many "unread" QC items are in their personal inbox and how many TOTAL items are in the QC section inbox
* Other court users only see the count for the TOTAL items in the QC section inbox

### Messages
* Message box should only show internal messages from other court users
* Messages always display the message text in the table (no show/hide function) 
* User can click anywhere on the row and be taken to the message in the document detail page
* User can see count of TOTAL number of items in their section message box 
* User can see an indication of when they have a new unread message no matter where in the system they are. 

## Notes:
* Implement this with high-priority indicator story (#1432)

## Tasks ##
~NOTE: All tasks are currently completed and merged to develop, but are awaiting resolution on a deploy issue.~

- [x] Add isInternal flag to document work items on creation (Cody #1956)
- [x] Add QC Route and assoc. view (Matt #1939, #1956)
- [x] Document QC: Batched for IRS tab (Cody #1956)
- [x] Document QC: Dynamically Change the Sent tab name "Served / Processed / Sent" (Cody #1956)
- [x] Filter messages between "My" and "Section" Document QC (Cody #1956)
- [x] Verify all table column names match design (Joe #1956)
- [x] Refactor My Messages to only display internal messages (Cody #1956)
- [x] Served should not displayed the "Batched for IRS" messages (Joe #1956)
- [x] Work on the "Other Court Users" design (Cody #1956)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by uxforgood** [comment]
# For Petitions Section Document QC Box

**Comment by uxforgood** [comment]
# For Petitions Section 

## My Document QC
- Only shows external filings (petitions) 
- 3 tabs - Inbox, Batched for IRS, Served
- Add a Paper Petition button launches that workflow
- Do not display system messages in table
- Number count indicates # of unread items in the My Document Inbox
- When petition gets sent to IRS, moves to Batched to IRS tab
- After it's actually been served to IRS, moves to Served tab

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/cc843757-f913-47ba-91bd-f37c61b6e290)

## Section Document QC

- Show yellow ? icon if the item is unassigned 
- Number count indicates # of TOTAL documents in the Section Inbox

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/59f1bef6-97c7-4793-802d-a720d46d06e5)

## My Messages 

- Only shows internal messages from other court users
- Display all messages in the table (truncate messages at 2 line with ...) 
- When user has ANY unread messages, show envelope icon in the global header. Goes away when unread messages is zero

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/64f03f8d-cb09-40b9-8e26-893283077034) 

## Section Messages

- Number count indicates # of TOTAL messages in the Section Inbox

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e05ed5bc-55eb-41db-ac9e-00486e873c25)

**Comment by uxforgood** [comment]
# For Docket Section 

## My Document QC
- Only shows external filings (petitions) 
- 2 tabs - Inbox, Processed
- Do not display system messages in table
- Number count indicates # of unread items in the My Document Inbox

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/bd0de675-89e8-4af4-99f1-74c512af8555)

## Section Document QC

- Show yellow ? icon if the item is unassigned 
- Number count indicates # of TOTAL documents in the Section Inbox

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/8268790a-8bf1-44ad-8c71-6129976ca2c4)

## My Messages 

- Only shows internal messages from other court users
- Display all messages in the table (truncate messages at 2 line with ...) 
- When user has ANY unread messages, show envelope icon in the global header. Goes away when unread messages is zero

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/a2ed0870-8b5d-4792-9eb4-50ed5d1ddb09)

## Section Messages

- Number count indicates # of TOTAL messages in the Section Inbox

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e19d8d8c-b1d0-4769-8308-d8fcbd7761ad)

**Comment by uxforgood** [comment]
# Other Court Users Document QC View

- Takes them to Docket Section view of QC box with total count
- No way to toggle to "My Documents QC" 
- No way to bulk assign (no checkboxes) 
- No Processed tab

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/52ce6b98-7d42-417a-8ee9-8f083cf76232)

**Comment by mariahkannenberg** [comment]
1335:
	• Column alignment, there's an extra space on the left
	• Run IRS Batch Process button- make more aesthetically pleasing
	• Too much space between button and document link. Take right padding off the table cell of icon. Just that icon.
	• Full bold - document link - change to semi-bold; across the board - all case links bold to 600 on all tables. 

My Document QC:
 - When user clicks on Batched for IRS, table columns are out of order; Same for Served. 
	Figma file is source of truth for column order
	Removes our ability to create abstract components. Now we need to create custom components. 
	
Messages:
- Check message for column order
- Checkbox off center in messages

**Comment by mariahkannenberg** [comment]
* All users who AREN'T docket or petition have a THIRD view of Document QC, which is documented on Figma file as "Other users." If you log in as seniorattorney1 you can simulate what this should look like (the only other user we have created).

They should NOT have a "My document" box at all, and only see the Section Inbox (no served box).

**Comment by mariahkannenberg** [comment]
* Bulk assigning work queue items from section to individual is throwing an error
     * Message didn't go away when it did work
* When I sent a message from petitions to docket, the success message says, "Your message was created successfully. You can view it in the Sent tab on your Work Queue." With new changes that isn't correct. 
* Message count icon next to Messages in main nav is not displaying
* I filed an external doc as a petitioner (Application for Waiver of Filing Fee) and it showed up twice in the petitioner view of docket record. Also showed up twice in the Docket Clerk view of docket record.
* When petition was assigned from the section queue to individual queue for petitionsclerk2, it didn't show up in clerk's individual work queue. 
* For Documents and Message QC time fields, use new design (shown in figma).
* Logged in as clerk, recalled icon should only display in petitions. Docket clerk doesn't need to see it (see icon rules in Figma)

Sarah's feedback (6/10, 2:50 p.m.):
* Petitions Clerk > Doc QC > Clicking on an "unread" state message does not change the state to "read"
* Petitions Clerk > Doc QC > Clicking on an "unread" state message does not change the state to "read"
* Petitions Clerk > Section Messages > Sent tab > 'Completed' message text displays message text of first message in thread (fixed in My messages but not in section) 

Natalie's feedback (6/10):
* the blue hover bar - On the Messages/Inbox the hover blue bar is much wider/thicker than it is on the Sent box, for instance. The wider one on Inbox is correct
* The non petitions/docket user (in this case sr attorney) should be seeing the DOCKET section Inbox. Right now it's blank.
* The only time the doc name is bolded is when it's unread. After it's read it goes back to 400/regular. Can see this on the served tab, for instance.

**Comment by sarahridgway** [comment]
All of the above comments have been verified as complete except the following which need minor adjustments:

*My notes first followed by original comment and original PR#)*

@matthopson 

* Tighten up section document QC batched tab icons >> Too much space between button and document link. Take right padding off the table cell of icon. Just that icon. (Matt #1997)
* Section Messages Sent, Section QC Sent, Individual Message Inbox and Sent - Docket number is 1-2px misaligned with the header >> Column alignment, there's an extra space on the left (Matt #1997)

**Comment by sarahridgway** [comment]
New findings as of June 13 5:00 pm:

*Contact me for more information*

QC > Misc > 
* Batched for IRS > Recalled item is duplicated in batch and served. Steps to replicate: Submit QC > Recall > Resubmit > check batch tab @ericsorenson @codyseibert 
* Batched for IRS > Run batch does not auto refresh list on tab but on reload list will update

QC > Section > 
* Recalled items have no icon

QC > Individual >
* Paper doc filed 01/01/1990 shows received 12/31/89 in QC

Messages > Misc >
* Completed messages are to: [assigned clerk] on individual queue no matter who completes it
* Completed messages are to: [assigned] / from: [assigned] on section queue no matter who completes it
* Completed messages on queue showing sent time of original message in thread
* In Section messages, original and completed messages are both next to each other despite having been sent at different times, both showing up as sent at same time: see 131-19R 12:28pm

Messages > Section
* Items which are batched do not show icon unless manual refresh (same with recalled?)
* Clicking on an item links to the document info tab

Messages / QC > Section
* No Select header on check box column needed

Messages / QC > Misc
* Check all success messages for language update. “Work queue” is no longer a term in the system. Pair with @sarahridgway for updates

Sr Attny / Other User > Doc QC
* Drop icon and assigned to col

**Comment by uxforgood** [comment]
Additional things I'm seeing: 

- [ ]  1 When logged in as senior attorney on My Messages, I click on Section Messages and the header says "Docket Section" - it should say "Section Messages" 
- [ ] 2 After message is

**Comment by sarahridgway** [comment]
I organized the comments from June 10 so status is clear

**Comment by sarahridgway** [comment]
**Clarification Required _ Hold for Monday Design Call** 

Messages > Misc > 
* Completed messages are to: [assigned clerk] on individual queue no matter who completes it
* Completed messages are to: [assigned] / from: [assigned] on section queue no matter who completes it
* Completed messages on queue showing sent time of original message in thread
* In Section messages, original and completed messages are both next to each other despite having been sent at different times, both showing up as sent at same time: see 131-19R 12:28pm

**Comment by sarahridgway** [comment]
*All checked items above and below have passed UX review*

New findings as of 6:41pm June 14

- [ ] Doc QC > Batched for IRS > adding a petition to the batch changes the batched time for all batched items in the list to the time of the most recent submission

- [ ] Doc QC > Section | My > Inbox > newly assigned petitions are disappearing from the section Iist and are not appearing on the individual list. Counter is off as well. Lets try clearing the data and checking that first.

**Comment by matthopson** [comment]
Testing.

**Comment by sarahridgway** [comment]
Note: As of June 18 all new clean up items moved to trello
