### ISSUE TITLE
Feedback from Practitioner Interviews

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1448]
Usability Study | Practitioner Case Form: https://docs.google.com/presentation/d/1HcjhQ3_nKtgIR-9hh8uqKMS4yB02XGwznEKfFrx6SyA/edit?usp=sharing

("Recommendations" section moved to the bottom of this comment)

## Acceptance Criteria:

**Petitioner and Practitioner Dashboard:**
* Change "Petitioner Name" to "Case Name" 

**Petitioner and Practitioner "Start a Case" Forms:**
* Change `Start a Case`  to `File a Petition` (make sure that this change is applied throughout the application)
* Add reminder to redact information on the IRS notice to the helper text 
* Consider adding guidance to party options to make it clear there are additional choices in each category 
* Revise party contact fields & use new fields to populate "Filed by" options on File a Petition form (https://docs.google.com/document/d/1_pv9J_RnUGVdEM8HOdX4iikx3rKbgQXyXd_OG8BVC_I/edit?usp=sharing)
* Add Judge Buch's comment about "next closest place of trial may not be in your state"
* Remove IRS notice date from "Start a Case" form; info should be entered by Petitions Clerk during QC
* Add clarification that redaction does not apply to the STIN document  
* Soften language for these instructions; update to “Reminders

**Docket Record for All Users:**
* Make sure any document uploaded during the petition filing process (Petition, Request for Place of Trial, ODS) has a corresponding code for the docket table
* When practitioner files a petition, update the petition "Filed By" to display with petitioner's name (not practitioner)

## Tasks 
- [x] 1 Change "Petitioner Name" to "Case Name" (Kristen #2335) 
- [x] 2 Update Before You Begin screen (Kristen #2335)
- [x]  3 Add Judge Buch's comment about "next closest place of trial may not be in your state" (Kristen #2335/#2354)
- [x]  4 Add clarification that redaction does not apply to the STIN document (Kristen #2335/#2354)
- [x] 5 Create wizard for starting a case and split views into separate steps (Rachael #2494)
- [x] 6 Multi-step validation for wizard (Rachael #2502 #2504)
  - [x] 6a Remove irsNoticeDate from validation (it's no longer on the form) (Rachael #2509)
- [x] 7 Step 1 view updates (STIN) (Rachael #2494)
- [x] 8 Step 2 view updates (Tell Us About Your Petition) (Rachael #2497)
   - [x] 8a Remove Date of Notice from UI (Rachael #2497)
- [x] 9 Step 3 view updates (Who are you filing this petition for?) (William #2511)
   - [x] 9a Update party contact fields (William #2511)
   - [x] 9b Update case info space (William #2511)
   - [x] 9c Remove email field and hint (William #2511)
   - [x] 9d Update labels on QC page for new combined contacts (William #2511)
   - [x] 9e Update case caption generation for combined contacts (William #2511)
- [x] 10 Step 4 view updates (How do you want this case handled?) (Rachael #2497)
   - [x] 10a Add U.S. Tax Court Locations subsection (Rachael #2497)
   - [x] 10b Update small case vs regular case accordion (Rachael #2497)
- [x] 11 Call submit sequence from step 4 continue button and verify that it submits correctly (Rachael #2509)
- [x] 12 Verify that all form values are retained when clicking the back buttons (Rachael #2509)
- [x] 13 Clean up old code that is no longer used (Rachael #2516)
- [x] 14 Add event codes for initially filed docs (Rachael #2515)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (William)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Rachael)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William #2521)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (William #2521)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
## Recommendations:
* Dashboard 
   * Emphasize “Start a Case” button and consider updating language to “File Petition” - DONE
* Petition Upload 
    * Add reminder to redact information on the IRS notice to the helper text - #1448 
* Party Information  
   * Consider adding guidance to party options to make it clear there are additional choices in each category - #1448 
   * Consider redefining the required contact fields (telephone, email), especially when the petitioner is represented by counsel - #1448 
* Case Type 
   * Update language to account for cases that are not initiated by a “notice” (specifically Declaratory Judgment) - DONE
   * Update Notice Date field to optional - #1448 
* Submission Instructions 
    * Add clarification that redaction does not apply to the STIN document - #1448   
    * Soften language for these instructions; update to “Reminders” - #1448 
* Review Case Form 
   * Add PDF preview option before submission - #1402 
   * Add a review screen to view all entered information before submission - #1402 
* Document Type Selections 
   * Make the type-ahead search for document type available to practitioners - #1508 
   * Revise the “browse” document type presentation and flow - #1508
   * Revisit the flow of the document selection - #1508
* Inclusions 
   * Add helper text language for the different types of inclusions, with examples (specifically Attachments) - #1508
* Filing Parties  
   * Revise options to clarify that counsel is filing on behalf of the petitioner and not themselves - #1508 
   ~* Consider removing the “Counsel” option unless the document type is Motion to Withdraw~ 
* Review and Submission 
   * Add PDF preview feature before document submission - #1566 
* Case Management 
   ~* Maintain visibility into closed cases; consider capping access to closed cases after 5 years~  
   ~* Define and display an external-facing case status (may be a subset of internal statuses, or mapped to specific internal statuses)~ 
   * Display pending due dates for active cases (for example, due date for pre-trial memorandum 14 days before trial date) - #2041
* Service Emails 
   * Consider including case caption and document title in the service notifications (if privacy laws allow) - #1921 
* Dashboard 
   * Display recent/new filings for active cases on the dashboard - #2040
   * Display pending due dates for cases on dashboard - #2041
* Search  
   * Add ability to search by petitioner name (MVP) #2038
   * Add ability to search by attorney name (Post-MVP) - #2039
* Messaging 
   ~* Consider communication options between practitioners and judges (i.e. could practitioners be able to send a system message to a judge’s inbox to request a conference call)~
* Account Management 
   ~* Consider a student access role to allow law students visibility into their cases without full rights~ 
   * Allow practitioners to add multiple service addresses for different client types - #1944

**Comment by klohman** [comment]
### Before you begin (updated screen - wizard step 1)

* Added  new block of content "are you authorized...." (

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/07a1b899-628a-4c1a-b09f-0e77a6b876eb)

### 1. Provide Statement of Identity 
* Added hint (#2335) 
* Updated header (#2335)
* Field is required 
* on click of "Continue to step 2 of 5" navigate to "Tell Us about your petition" 
*On click of back, navigate to Before you Begin page 

### 2. Tell Us About Your Petition 
* Updated hint text and location (#2335)
* Date of Notice field - REMOVE field from form 

* on click of "Continue to step 3 of 5" navigate to "Who are you filing this petition for?" 
*On click of back, navigate to "Provide your statement of identity" screen 

### 3. Who are you filing this petition for? 
* Removed hint 
* Updated contact fields (See Figma and google sheet in notes) 
* Remove email from all contacts
* Remove email hint from all contacts

* on click of "Continue to step 4 of 5" navigate to "How do you want this case handled?" 
*On click of back, navigate to "Tell Us About Your Petition" screen 

### 4. How do you want this case handled? 
* Updated language on help accordion (#2335)
* Updated helper text on trial location field ((#2335)
* Updated small case helper accordion styling (partially #2335)

* on click of "Submit to U.S. Tax Court" submit petition (current functionality)  
*On click of back, navigate to "Who are you filing this petition for" screen 

### On submit of petition 
* Make sure any document uploaded during the petition filing process (Petition, Request for Place of Trial, ODS) has a corresponding code for the docket table
* When practitioner files a petition, update the petition "Filed By" to display with petitioner's name (not practitioner)

**Comment by klohman** [comment]
### Mobile Variation 

#### Which case procedure should I choose? 
 
* on select, navigate to mobile screen "Which case procedure should I choose?"

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f109ed2-3c58-41ec-9d52-8dadc4326e35)

* On select of "Back to File a Petition" breadcrumb- navigate back to "How do you want this case handled"

**Comment by klohman** [comment]
### Case Detail > Case Information > Party Information 
- updates to the contact fields displayed in the party information section 

**Petitioner & Spouse AND Petitioner & Deceased Spouse**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/48e70054-b3f1-465a-b46a-72866a21dd60)

**Corporation AND Estate without Executor**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ffde504-e23d-486c-8ca3-681aacd2ea7f) 

* display the case caption (everything up to "Petitioner" - same format as on dashboard) 
* display c/o <In Care of field> 

**All Other Party Types**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b852bbc5-466c-45c2-b280-c83907f946fd)

* display the case caption (everything up to "Petitioner" - same format as on dashboard)

**Comment by klohman** [comment]
### Test Scenarios 

1448 Test Scenarios 


**Petitioner files petition as an individual petitioner** 
- Petitioner logs in 
- Petitioner files case selecting “myself” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name 
    * Mailing Address Line 1 
    * Address Line 2 
    * Address Line 3 
    * City
    * State 
    * Zip Code 
    * Country
    * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as party 1


**Petitioner files petition as petitioner and spouse**
- Petitioner logs in 
- Petitioner files case selecting “myself and spouse (living)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
    - Spouse’s Name 
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as party 1 and party 2 
- [ ] Case Caption displays as {Name of Petitioner} & {Name of Spouse}, Petitioners v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as petitioner and deceased spouse** 
- Petitioner logs in 
- Petitioner files case selecting “myself and spouse (living)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
    - Spouse’s Name 
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Petitioner} & {Name of Spouse}, Petitioners v. Commissioner of Internal Revenue, Respondent




**Petitioner files petition as estate without executor** 
- Petitioner logs in 
- Petitioner files case selecting “estate without executor” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Decedent 
    - In Care Of
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as Estate of {Decedent’s Name}, Deceased, Petitioner v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as estate with executor** 
**Petitioner files petition as estate without executor** 
- Petitioner logs in 
- Petitioner files case selecting “estate with executor” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Decedent 
    - Name of Executor/Personal Representative
    - Title
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as Estate of {Decedent’s Name}, Deceased, {Name of Executor, PR, Etc.}, {Title}, Petitioner(s) v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as corporation** 
- Petitioner logs in 
- Petitioner files case selecting “corporation” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Business Name 
    - In Care Of
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Business}, Petitioner v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as tax matters partner** 
- Petitioner logs in 
- Petitioner files case selecting “partnership (tax matters partner)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Partnership Name 
    - Name of Tax Matters Partner (TMP)
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Partnership}, {Name of TMP}, Tax Matters Partner, Petitioner v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as partner other than tax matters partner** 
- Petitioner logs in 
- Petitioner files case selecting “partnership (other than tax matters partner)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Partnership Name 
    - Name of Partner (other than TMP)
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Business}, {Name of Partner (Other Than TMP)}, A Partner Other Than the Tax Matters Partner, Petitioner v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as partner (BBA regime)** 
- Petitioner logs in 
- Petitioner files case selecting “partnership (BBA regime)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Business  
    - Name of Partnership Representative
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Business}, {Name of Partnership Representative}, Partnership Representative, Petitioner(s) v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as trustee** 
- Petitioner logs in 
- Petitioner files case selecting “trust & trustee” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Trust  
    - Name of Trustee
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Trust}, {Name of Trustee}, Trustee, Petitioner(s) v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as conservator** 
- Petitioner logs in 
- Petitioner files case selecting “conservator” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Taxpayer  
    - Name of Conservator
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Taxpayer}, {Name of Conservator}, Conservator v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as guardian**
- Petitioner logs in 
- Petitioner files case selecting “guardian” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Taxpayer  
    - Name of Guardian
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Taxpayer}, {Name of Guardian}, Guardian, Petitioner v. Commissioner of Internal Revenue


**Petitioner files petition as custodian** 
- Petitioner logs in 
- Petitioner files case selecting “custodian” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Taxpayer  
    - Name of Custodian
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Taxpayer}, {Name of Custodian}, Custodian, Petitioner v. Commissioner of Internal Revenue


**Petitioner files petition as next friend for a minor** 
- Petitioner logs in 
- Petitioner files case selecting “minor (Without Guardian, Conservator, or other like Fiduciary)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Minor  
    - Name of Next Friend
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Minor}, Minor, {Name of Next Friend}, Next Friend, Petitioner v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as next friend for incompetent person**
- Petitioner logs in 
- Petitioner files case selecting “Incompetent person (Without Guardian, Conservator, or other like Fiduciary)” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Legally Incompetent Person  
    - Name of Next Friend
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Incompetent Person], Incompetent, {Name of Next Friend}, Next Friend, Petitioner v. Commissioner of Internal Revenue, Respondent

**Petitioner files petition as surviving spouse** 
- Petitioner logs in 
- Petitioner files case selecting “surviving spouse” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Deceased Spouse
    - Name of Surviving Spouse
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Deceased Spouse}, Deceased, {Name of Surviving Spouse}, Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent
- 


**Petitioner files petition as donor** 
- Petitioner logs in 
- Petitioner files case selecting “donor” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Petitioner
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Petitioner}, Donor, Petitioner v. Commissioner of Internal Revenue, Respondent


**Petitioner files petition as transferee** 
 Petitioner logs in 
- Petitioner files case selecting “transferee” as party type 

Expected results 
- [ ] Contact fields on form include: 
    - Name of Petitioner
        * Mailing Address Line 1 
        * Address Line 2 
        * Address Line 3 
        * City
        * State 
        * Zip Code 
        * Country
        * Phone
- [ ] Case Detail > Case Info tab displays petitioner info as in template
- [ ] Case Caption displays as {Name of Petitioner}, Transferee, Petitioner v. Commissioner of Internal Revenue, Respondent


 **Petitioner cannot advance from step 1 to step 2 without completing all required fields**
- Petitioner logs in
- Petitioner clicks “Got it, let’s start my case” 
- Petitioner clicks Continue to Step 2 of 5 

Expected Results 
- [ ] Errors for “Upload Your STIN” field display 
- [ ] User cannot advance to step 2 without uploading a file 

 **Petitioner cannot advance from step 2 to step 3 without completing all required fields**
- Petitioner logs in
- Petitioner clicks “Got it, let’s start my case” 
- Petitioner uploads STIN file 
- Petitioner clicks Continue to Step 2 of 5 
- Petitioner clicks Continue to Step 3 of 5

Expected Results 
- [ ] Errors for incomplete fields display 
- [ ] User cannot advance to step 3 without completing all required fields, including
    - Upload Petition file
    - Did you receive a notice from IRS 
    - Type of Notice/Case 

 **Petitioner cannot advance from step 3 to step 4 without completing all required fields**
- Petitioner logs in
- Petitioner clicks “Got it, let’s start my case” 
- Petitioner completes all required fields for step 1 
- Petitioner clicks Continue to Step 2 of 5 
- Petitioner completes all required fields for step 2 
- Petitioner clicks Continue to Step 3 of 5 
- Petitioner does not complete all required fields for step 3 
- Petitioner clicks Continue to Step 4 of 5 

Expected Results 
- [ ] Errors for incomplete fields display 
- [ ] User cannot advance to step 4 without completing all required fields, including
    - Varies dependent on party type 

**Petitioner cannot submit form without completing all required fields** 
- Petitioner logs in
- Petitioner clicks “Got it, let’s start my case” 
- Petitioner completes all required fields for step 1 
- Petitioner clicks Continue to Step 2 of 5 
- Petitioner completes all required fields for step 2 
- Petitioner clicks Continue to Step 3 of 5 
- Petitioner does completes all required fields for step 3 
- Petitioner clicks Continue to Step 4 of 5 
- Petitioner clicks “Submit to U.S. Tax Court” 

Expected Results 

- [ ] Errors for incomplete fields display 
- [ ] User cannot submit form without completing all required fields, including
    - Case procedure 
    - Trial Location 

**Petitioner can submit form** 
- Petitioner logs in
- Petitioner clicks “Got it, let’s start my case” 
- Petitioner completes all required fields for step 1 
- Petitioner clicks Continue to Step 2 of 5 
- Petitioner completes all required fields for step 2 
- Petitioner clicks Continue to Step 3 of 5 
- Petitioner does completes all required fields for step 3 
- Petitioner clicks Continue to Step 4 of 5 
- Petitioner completes all required fields for step 4 
- Petitioner clicks “Submit to U.S. Tax Court” 

Expected Results 

- [ ] PDF upload modal displays while pdf is processing 
- [ ] Petitioner returns to Dashboard with success message displayed 
- [ ] New case is displayed in “Your Cases” table 
- [ ] New petition is added as work item in Petitions Section Document QC inbox
- 


**All documents submitted have associated event code displayed on docket record ** 
- Petitioner logs in
- Petitioner completes File a Petition form with party type “business” 
- Petitioner selects “Baltimore, Maryland” as trial location
- Petitioner submits form 
- Petitioner clicks on new docket number from Your Cases table

Expected Results 

- [ ] A Docket entry is displayed as Petition with event code P
- [ ] A Docket entry is displayed as Ownership Disclosure statement with event code ODS
- [ ] A Docket entry is displayed as Request for Place of Trial at Baltimore, Maryland with event code RQT

**Comment by JessicaMarine** [comment]
Small case expandable:
* Deficiency: The amount of deficiency (including any additions to tax and penalties) cannot exceed $50,000 for any one year.
* Collection (Lien/Levy): The total amount of unpaid tax cannot exceed $50,000 for all years combined.
* Innocent Spouse Relief: the amount of spousal relief sought cannot exceed $50,000 for all years combined.
* Worker Classification: The amount in dispute cannot exceed $50,000 for any calendar quarter.
* Interest Abatement: The amount of the abatement  sought cannot exceed $50,000.  
* Partnership cases: Not eligible for "S" status
* Whistleblower cases: Not eligible for “S” status
* Passport cases: Not eligible for “S” status
* Declaratory Judgment cases: Not eligible for “S” status

**Comment by klohman** [comment]
### UX Review Notes 

- [ ] 1   I was on Step 3 and did not complete all the contact fields, clicked “back. On Step 2, when I tried to Continue to Step 3 - error triggered on the incomplete field in Step 3 and I could not go back to Step 3 to complete 
- [ ] 2 Got an “Error with your upload” several times- may be deploy issue 
- [ ] 3 Remove the email from the contact info for all party types on the Case Detail > Case Info tab 
- [ ] 4 Both “Primary contact” and “secondary contact” labels should be changed to “Petitioner” for all party types on Case Detail > Case Info tab 
- [ ] 5 For  Estate with Executor, remove the separate line item for title field on Case Detail> Case Info 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9eb54f3c-0625-4492-9782-82a5162018e4)

￼
