### ISSUE TITLE
CMS User: Sortable Docket Record

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1451]
As a CMS User, in order to view the docket record in a way that's most useful to me, I need each column to be sortable.

## Pre-Conditions:
* CMS User is viewing docket record

## Acceptance Criteria:
* The docket record should be sortable by the index entry number (column 1) and the date filed (column 2)
* Default sort on the date column

## Tasks
- [x] 1. create select menus
  - [x] 1a. with four options for use on large screens (Rachael #1645)
  - [x] 1b. as toggle-button (with two options for date asc, date desc) on mobile (Rachael #1645)
  - [x] 1c. create sequences & actions to store sorting preferences in state (William #1643)
- [x] 2. alter `formattedCaseDetail` (around line 155) to identify the desired sorting method and apply it (kris #1644)
  - [x] 2a. create sort functions for 'date asc', 'date desc', 'index asc', 'index desc' (kris #1644)
- [x] 3. clear sessionMetadata sort option when navigating to a different case or when logging out/in (Rachael)
- [x] 4. Persist sort option per case over the session (William #1650)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by tjcurington** [comment]
Jessica will add additional sort criteria.

**Comment by klohman** [comment]
@JessicaMarine 

## Desktop View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eae9da43-b01a-49d8-85db-6f334f5d4eb1)

- Add sort component (select menu) 
- Default sort is "Sort By Oldest" - sorted chronologically by date 
- Select menu options 
* Sort By Oldest (default) 
* Sort By Newest - reverse chronologically by date 
* Sort By Index (Ascending)- sort on "No." column
* Sort By Index (Descending)- sort on "No." column 


 ## Mobile View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1b521df1-945a-4ef6-82f6-83ffc037db24)

Add sort toggle 
- Oldest to Newest (default) 
- Newest to Oldest 

Icon ![image.png] is clickable 
(https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/81240104-6ee9-4022-a993-2dee8a422e8b)
* on click, toggle sort selection
