### ISSUE TITLE
Mobile Docket View

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1472]
As a mobile user, so that I can easily access the docket on my mobile device, I need a docket table that is mobile friendly. 

## Pre-Conditions:
* CMS user is trying to view docket table on mobile device

## Acceptance Criteria:
* Implement mobile-friendly view of docket record
* Apply new mobile style to all mobile views.

## Tasks
- [x] 1. Dashboard - update table mobile design (William #1496)
- [x] 2. Case Detail - update table mobile design (Rachael #1483)
  - [x] 2a. Call sequences created in 3a to open/close overlay (Kris #1492 )
- [x] 3. Document detail mobile view overlay (Kris #1492 )
  - [x] 3a. Create sequences to open/close overlay (Kris #1492)
- [x] 4. Responsive tab design (style guide reminder) (William #1494)
~~5. Refactor document detail links on DocketRecord.jsx to refine logic~~ (devex task)
- [x] 6. Make sure styles extend for tablet width (William #1505)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (#1507)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Updated Dashboard - Mobile View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/03a8980a-8b3b-41ce-95e1-eb3d1a19ffe9)

## Updated Case Detail Docket Record- Mobile View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2a6cbd75-29aa-4861-9863-9b40e5b5c969)

- For each docket entry, display ONLY 
* Date 
* Document Title - displayed the same as on desktop 

On click of the Document Title link, display mobile Document Detail view 

## Mobile Document Detail View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/87f140c1-9a72-49d0-88ba-c2435def0241)

* Document Title displayed - but does not include a link 

**View PDF button** 
- on click, open PDF document 

On click of the back icon ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7f3b7f75-8b67-4755-895b-535a021fc782)
- close Document Detail view 
- Return to Case Detail - anchored to docket entry user had clicked on
