### ISSUE TITLE
Usability Testing: File a Document Form Clean-Up

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1508]
As a Petitioner, Practitioner and IRS Attorney, so that I may have a clear and organized user experience, I need the File a Document form updated. 

## Acceptance Criteria 

For all external users (petitioners, practitioners and IRS attorneys) in the File a Document Form:
 * Allow type-ahead document selection (same as currently built for internal users)
 * Update the "browse" document type presentation and flow to allow users to more easily navigate ("drill down") and select the correct document
* On the File Your Documents Screen:
     * Display full concatenated document title
     * Allow user to add multiple supporting documents
     * _For multiple supporting documents test/ensure:_ that each creates a separate docket entry w/court-formatting rules; If the supporting document is filed in support of a "Filed" document, the supporting document will also be "Filed"; if the supporting document is filed in support of a "Lodged" document, the supporting document will also be "Lodged"
* Provide users with more details about what can be included with their document (exhibits, attachments and certificate of service)
* In Supporting Documents section, add questions re: C/S, Attachments, Exhibits, Objections (if relevant) to each document on File a Doc form (Primary, Supporting Doc to Primary, Secondary, Supporting Doc to Secondary) 
* In the Tell Us about Parties Filing section, dynamically display petitioner's and counsel's names instead of static field labels; always include respondent (static) as an option
* In the Review Your Filing section:
     * Show what inclusions were selected; show objections as well
     * Content Edit: Does this document have Exhibits? should be Exhibit(s).  Same with Attachment(s) 
* Ensure all above changes are mobile friendly (responsive); with slight variations between desktop and mobile as needed.

## Tasks
- [x] 1 Add `Before you file` screen to file doc wizard (desktop and mobile) (Kris #2298)
- [x] 2 Update Desktop document type select screen (William #2322)
  - [x] 2a Desktop doc type select view using type-ahead menu  (William #2322)
  ~2c Use typeahead doc type select menu created for internal users~
  - [x] 2d Add accordion section on right side of screen on desktop (William #2299 #2301 #2315)
- [x] 3 Create Desktop `All Document Categories` view (William #2315 #2322)
  - [x] 3a Create modal for nonstandard form  (William #2322)
  - [x] 3b Accordion Component (William #2299)
- [x] 4 Update mobile type select screen (William #2344 #2351)
  - [x] 4a Mobile doc type select view  (William #2344)
  - [x] 4b Create mobile wizard for selecting a document type when `I Need Help Selecting a Document` (William #2344)
- [x] 5 Create Mobile `All Document Categories` view (William #2344)
- [x] 6 Update file document form view (desktop and mobile) (Rachael #2328 #2346)
  - [x] 6a Create `What can I include with my document?` view (William #2387)
  - [x] 6b Modify file document actions and interactors to add multiple supporting documents (Rachael #2370)
  - [x] 6c Create view for multiple supporting documents (Rachael #2370)
  - [x] 6d Generalize inclusions form to be used on primary, secondary, and supporting docs (Rachael #2349)
  - [x] 6e Validation for multiple supporting docs (Rachael #2395)
  - [x] 6f Add inclusions form to supporting docs (Rachael #2385)
  - [x] 6g Review validation messages that are shown in UI for multiple supporting docs (Rachael #2425)
    - [x] supportingDocuments #1 - supportingDocument field - Enter selection for Supporting Document. (Rachael #2425)
    - [x] cert of service date on supporting docs not validating (Rachael #2425)
- [x] 7 Update review screen (desktop and mobile) (William #2363)
  - [x] 7a Incorporate Document Preview links (Clarion #2391)
  - [x] 7b Handle Optional forms (William #2392)
  - [x] 7c Update review page for multiple supporting docs (Rachael #2396)
  - [x] 7d Update review page to show inclusions for all docs (Rachael)
- [x] 8 Add `File a Document` button to mobile case detail page (Rachael #2306)
- [x] 9 Update pa11y test (Rachael #2431)
- [x] 10 Remove exhibits from entities, form, and review page (Rachael #2398)
- [x] 11 UX fixes
  - [x] cancel button on mobile on step 1 (William #2410)
  - [x] change document button next to uploaded files on doc form (mobile) (Rachael #2427)
  - [x] add text to replace button if they add 5 supporting docs - "You can only add 5 supporting documents at a time. You may file another supporting document in a separate filing." (Rachael #2427)
  - [x] hook up supporting doc what can I include modal (Rachael #2414)
  - [x] ~space below review filing button on mobile file doc page~ looks like this is already fixed
  - [x] add margin-bottom-2 div around file area on review page for supporting docs ONLY on mobile (margin-bottom-0 on desktop) (Rachael #2414)
  - [x] add ,Petitioner to parties on review page (display the same as on File a Doc form page for all parties) (Rachael #2427)
  - [x] hide inclusions and Add Secondary Supporting button on secondary doc unless they upload a doc for optional (only for Motion for Leave to File) (Rachael #2414)
- [x] 12 add "Back" button on File a Document form on mobile and desktop  (William #2424)
- [x] 13 anchor back to top when navigating to modal on mobile (William #2437)
- [x] 14 resolve issues with multiple practitioner parties on form and review page (Rachael #2429)
- [x] 15 Per feedback from Jessica, whenever a document is lodged, the code should always be MISL. Currently it's getting the code for the document for which is was filed (incorrect) - When a party files a Motion for Leave to File -- the secondary document and any supporting docs for that secondary doc are "lodged" not filed. Those secondary and supporting docs should have MISL as code. (William #2432)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael #2433)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) 
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael #2444)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael #2433)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Rachael #2433)
 - [x] Deployed to the dev environment

**Comment by klohman** [comment]
### Desktop - Case Detail screen 

* On click of File a Document button, open "Before you file a document" screen

#### Before you file a document 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/32dd824a-2609-4d13-86b9-3a2fe2022c87)

* On click of Cancel button, display "Cancel" modal (use current modal)
* On click of "OK I'm ready to file" button, navigate to "What document are your filing" 

#### "What document are you filing" (updated) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2f6b351c-32b1-43f2-901d-110c667478c1)

**Document Type**
* required field 
* use the type-ahead dropdown being used for internal users 
* if non-standard document is selected, display required fields below (same functionality used for internal users) 
* Error message: "You must select a document type."  
* On click of Continue, navigate to "File Your Document(s)" screen 
* On click of Cancel button, display "Cancel" modal (use current modal)

**Need help selecting a document**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/88af4847-fe2d-4810-97bb-ecfe4da229cb)

* USWDS borderless accordion- standard functionality 
* Static content displayed under each accordion 
* Request  Something From the Court 
  - Application 
  - Motion 
  - Petition 
* Notify the Court of a Change 
  -  Brief 
  -  Memorandum
  - Notice  
  - Statement 
  - Stipulation  
* Update or Add to a Previous Document 
- Miscellaneous 
- Supporting Documents 
* Respond to a Previous Document 
  - Answer 
  - Response, Opposition, or Objection 
  - Reply 

* On click of "View All Document Categories" button, navigate to All Document Categories screen (new) 

#### All Document Categories (new screen) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/33d26d9e-bf28-426e-8f2a-618b2f2b3a36)
* Each document category is label of an accordion 
* Document categories should be listed in alphabetical order EXCEPT "Answer" should be the last accordion 
* Accordion is populated with all document types within that category in alphabetical order 

**On click of a document type**
* For standard doc types, navigate to the "File Your Document(s)" form 
* For nonstandard doc types, display modal 

#### Nonstandard Doc Type Modal (new)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ba33193a-d0ee-40be-bef8-f50802cf23cd)

* Display document type as header : "You Selected: <Document Type>"
* Display required fields associated with the selected doc type 
* on click of cancel, close modal and return to parent page 
* On click of Continue, navigate to "File Your Document(s)" form 

#### File Your Document(s) screen (updated)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0c25de97-6c16-432b-afea-f669814aa481)

* Display full concatenated document title as header of the first section 
* Add Select Extra Items Included with Document field 
- Certificate of Service - if selected, display Service Date field (required) 
* On click of link "What can I include with my document", display modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/df89be61-f994-4fb6-a233-50251eef9d21)

**Supporting Document**
 * On click of Add Supporting Document button, display Supporting Document section below 
* allow up to 5 supporting documents to be added, then hide button

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a328f913-a14d-4f56-8b0d-d16935830030)

* Add Select Supporting Document field 
* Display additional required fields depending on the selected doc type (current functionality) 
Add Select Extra Items Included with Document field 
- Certificate of Service - if selected, display Service Date field (required) 
* On click of link "What can I include with my document", display modal

**Tell Us About the Parties Filing The Document**
* Update section header "Tell Us About the Parties Filing The Document(s)"
* Update field label to "Who are you filing the document for?" 
* Display petitioners as "Petitioner Name, Petitioner"
* Display petitioner counsel (if applicable) as "Petitioner Counsel Name, Counsel"  
* Always display "Respondent" as option 

*On click of Cancel, display cancel modal (current functionality)
* On click of "Back" button, return to "What document are you filng" screen with selected document populated 
* On click of Review Filing, navigate to Review Your Filing screen 

#### Review Your Filing 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/927ed0fa-22e8-4d43-b840-e19b8bd86814)

**Document Includes** 
* show section with any items selected on form (Exhibits, Attachments, Certificate) 
* Hide if no inclusions were selected 
* show objections 

*On click of Cancel, display cancel modal (current functionality)
* On click of "Back" button, return to "File Your Document(s)" screen with form selections populated
* On click of Submit Your Filing
   - docket entries are created for each document 
   - documents appear in the Docket Section QC 
   - User is navigated to Case Detail page with success message displayed 


![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/800a5414-8e21-47f7-8492-3f1299be73e9)

**Comment by klohman** [comment]
### Mobile 

**See USTC Web Style Guide figma for Mobile font updates 

#### Case Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/006fe7d9-a585-43a7-ac36-6403cca23af3)

* Add File a Document button 
* On click, of File a Document, navigate to Before you file screen 

#### Before you file 
**Change from desktop** 
* Hide icons 

#### What document are you filing? 
**Change from desktop**
* Hide the "Need Help Selecting a Document Type" accordions
* Show "I Need Help Selecting a Document" button 
* On click of "I Need Help Selecting a Document" button, navigate to "What is this document for" screen 

#### What is this document for? 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a66f0e80-5523-44a5-8031-3cc64ef24700)

* On click of breadcrumb, return to "What document are you filing" screen 
* On click of a document category, navigate to the Document Category screen 
*On click of View All Document Categories, navigate to All Document Categories screen 

#### All Document Categories 
* Display all document categories alphabetically EXCEPT Answer should be the last category 
* On click of breadcrumb, return to "What is this document for" screen 
* On click of a document category, navigate to the Document Category screen 

#### Document Category screen 
* display document category as header 
* display all document types in this category alphabetically 

* On click of breadcrumb, return to "All Document Categories" screen  

**On click of a document type** 
  * For standard document types, navigate to the File a Document form 
  * For nonstandard document types
    - navigate to "What document are you filing" screen with the selected document type populated 
    - display additional required fields for the nonstandard doc type selected 

#### File Your Document(s) screen 
**Change from desktop**
* On click of "What can I include with my document? link, open new "What can i include with my document" screen

#### What can i include with my document 
* On click of breadcrumb, navigate back to File a Document form 

#### Review Your Filing
* no changes from desktop

**Comment by klohman** [comment]
## Test Scenarios 

### AC: Allow type ahead document selection 
### AC: On File a Document Form, Display full concatenated document title


**Scenario 1**

Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Enter [summary] in document type dropdown field 
* Select Motion for Summary Judgment 

Expected Results 
- [ ] filtered dropdown displays the following documents: 
    - Motion for Partial Summary Judgment 
    - Motion for Summary Judgment
- [ ] When selected, Motion for Summary Judgment is displayed as selected in document type field 

**Scenario 2**

Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Click into Document type dropdown field and scroll to select [Motion for Extension of Time]  

Expected Results 
- [ ] All documents are displayed in alphabetical order in dropdown 
- [ ] Document [Motion for Extension of Time] is displayed as selected in document type field 

**Scenario 3**

Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Select [Affidavit in Support] from Document Type field

Expected Results 
- [ ] Document [Affidavit in Support] is displayed as selected in document type field 
- [ ] Required fields for [Affidavit in Support] are displayed 
    - Who Signed This 
    - Which Document is This Affidavit in support of

**Scenario 4**

Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Select Motion for Leave to File from document type dropdown
* Select “Response” from the Which Document is This Motion for Leave for field 
* Select a [previous document] from Which Document Are You Responding To?
* Click continue  

Expected Results 
- [ ] On select of Motion for Leave to File, Which Document is This Motion for Leave field displays 
- [ ] On select of Response, Which Document Are You Responding To field displays 
- [ ] on click of continue, app navigates to File a Document form 
- [ ] Motion for Leave to File Response [previous document] displays as selected document on form

### AC: Update the "browse" document type presentation and flow to allow users to more easily navigate ("drill down") and select the correct document
### AC: On File a Document Form, Display full concatenated document title


**Scenario 5**

Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Click View All Document Categories 
* Select the Notice accordion 
* Click Notice of Change of Telephone Number

Expected Results 
- [ ] On click of “View all Document Categories” button, app navigates to All Document Categories screen 
- [ ] Selected accordion expands on click 
- [ ] All doc types in the [Notice] category display in expanded accordion 
- [ ] on click of [Notice of Change of Telephone Number] doc type, app navigates to File a Document form 
- [ ] Notice of Change of Telephone Number displays as selected document on File a Document form 

**Scenario 6**
Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Click View All Document Categories 
* Select the Notice accordion 
* Click Notice of Change of Telephone Number

Expected Results 
- [ ] On click of “View all Document Categories” button, app navigates to All Document Categories screen 
- [ ] Selected accordion expands on click 
- [ ] All doc types in the [Notice] category display in expanded accordion 
- [ ] on click of [Notice of Change of Telephone Number] doc type, app navigates to File a Document form 
- [ ] Notice of Change of Telephone Number displays as selected document on File a Document form 


**Scenario 7**
Test Steps 
* Login as 1) petitioner 2) practitioner 3) IRS attorney 
* Navigate to case 
* Click File a document 
* Click OK, I’m ready to File
* Click View All Document Categories 
* Select the Motion accordion 
* Click Motion for Leave to File Out of Time 
* Select Request for Place of Trial from Which Document is this motion for leave for field 
* Select Baltimore from Requested Location field 
* Click continue  

Expected Results 
- [ ] On select of Motion for Leave to File Out of Time, modal opens displaying Which Document is This Motion for Leave field 
- [ ] On select of Request for Place of Trial, Which Document Are You Responding To field displays 
- [ ] on click of continue, modal closes and app navigates to File a Document form 
- [ ] Motion for Leave to File Out of Time Request for Place of Trial Baltimore, Maryland displays as selected document on form


### AC: Allow user to add multiple supporting documents
### AC: For multiple supporting documents test/ensure: that each creates a separate docket entry w/court-formatting rules; If the supporting document is filed in support of a "Filed" document, the 				supporting document will also be "Filed"; if the supporting document is filed in support of a "Lodged" document, the supporting document will also be "Lodged"
### AC: 	In Supporting Documents section, add questions re: C/S, Attachments, Exhibits, Objections (if relevant) to each document on File a Doc form (Primary, Supporting Doc to Primary, Secondary, Supporting Doc to Secondary)


**Scenario 8**

Test Steps 
* Follow Scenario 8 standard doc 
* Under “Notice to Change Telephone Number” section, select file for Upload Your Document 
* On File a Document Form, click Add Supporting Document button 
* Select Brief from Select Supporting Document dropdown 
* Select file for Upload Your Supporting Document 
* Click Add Supporting Document button
* Select Memorandum from Select Supporting Document dropdown 
* Select file for Upload Your Supporting Document 
* Select filing party (any) 
* Click Review Your Filing 
* Click Submit Your Filing

Expected Results 
* Docket record displays 3 entries 
    * Notice to Change Telephone Number 
    * Brief in Support of Notice to Change Telephone Number
    * Memorandum in Support of Notice to Change Telephone Number

**Scenario 9**
 
Test Steps 
* Follow Scenario 7
* Under “Motion for Leave to File Out of Time Request for Place of Trial Baltimore, Maryland” section, select file for Upload Your Document 
* On File a Document Form, click Add Supporting Document button 
* Select Brief from Select Supporting Document dropdown 
* Select file for Upload Your Supporting Document 
* Under Request for Place of Trial Baltimore, Maryland  section, select file for Upload Your Document 
* Click “Add Secondary Supporting Document” button 
* Select Memorandum from Select Supporting Document dropdown 
* Select file for Upload Your Supporting Document
* Select a filing party (any) 
* Click Review Your Filing 
* Click Submit Your Filing 

Expected Results 
- [ ] Request for Place of Trial Baltimore, Maryland section displays Inclusions field 
- [ ] On click of Add Supporting Document, Supporting Document section displays 
- [ ] Supporting Document section displays Inclusions field 
- [ ] On click of Add Secondary Supporting Document, Secondary Supporting Document section displays 
- [ ] “Select Secondary supporting document field” and Inclusions field is hidden until secondary supporting document is uploaded 
- [ ] Secondary Supporting Document section displays Inclusions field 
- [ ] Docket record displays 4 entries 
    - Motion for Leave to File Out of Time Request for Place of Trial Baltimore, Maryland - displays as FILED in record 
    - Brief in Support of Motion for Leave to File Out of Time Request for Place of Trial Baltimore, Maryland - displays as FILED in record 
    - Request for Place of Trial Baltimore, Maryland - displays as LODGED in record 
    - Memorandum in Support of Request for Place of Trial Baltimore, Maryland - displays as LODGED in record


### AC: In the Tell Us about Parties Filing section, dynamically display petitioner's and counsel's names instead of static field labels; always include respondent (static) as an option

**Scenario 10**
Test Steps 
* Follow Scenario 1 standard doc 

Expected Results 
- [ ] Respondent checkbox displays under Filing Parties 

### AC: Show what inclusions were selected; show objections as well

**Scenario 11**
Test Steps 
* Follow Scenario 1 
* For Inclusions field, check the Exhibits option 
* Select “Yes” in the “Are there any objections to this document?” 
* Complete the File a Document Form 
* Click Review Filing 

Expected Results 
- [ ] Exhibit(s) displays under “Document Includes” on Review Your Filing screen 
- [ ] “Yes” displays under “Are there any objections to this document” on Review Your Filing screen

### Wizard Functionality Testing 

**Scenario 12**

Test Steps 
* Follow Scenario 11
* On Review Filing, click “Back” button

Expected Results 
- [ ] On click of Back button, app navigates to File a Document form
- [ ] File a Document form is populated with the previous selections 

**Scenario 13**
* Follow Scenario 1 
* Click Continue 
* On File a Document form, click “Back” button 

Expected Results 
- [ ] On click of back, app navigates to “What Document are you filing” screen 
- [ ] Motion for Summary judgment is populated in Document Type field

**Comment by klohman** [comment]
## Mobile 

### Document Browse functionality 

**Scenario 15** 
* From Mobile Case Detail page, select File a Document button 
* Select OK, I’m Ready to File 
* Select “I Need Help Selecting a Document” 
* Select “Response, Opposition, or Objection” 
* Select Response 

Expected Results 
- [ ] On What document are you filing screen, “I Need Help Selecting a Document” button is displayed 
- [ ] On What document are you filing screen, Need Help Selecting a Document accordion (displayed on desktop) is hidden 
- [ ] On click of “I need Help Selecting a Document”, app navigates to “What is this document for” screen
- [ ] On click of “Response, Opposition, or Objection”, app navigates to “Response, Opposition, or Objection” document category screen 
- [ ]“Response, Opposition, or Objection” screen displays all document types under that category in alphabetical order 
- [ ] On click of “Response”, app navigates to “What document are you filing” screen with “Response” displayed as selected doc type 
- [ ] On “What document are you filing” screen, “Which document are you responding to” field is displayed  


**Scenario 16**
* From Mobile Case Detail page, select File a Document button 
* Select OK, I’m Ready to File 
* Select “I Need Help Selecting a Document” 
* Select “View All Document Categories” button 
* Select Stipulation from document category list 
* Select Stipulation of Settled Issues as document type 

Expected Results 
- [ ] On click of “View All Document Categories button, app navigates to “All Document Categories” screen
- [ ] “All Document Categories” screen displays all document categories in alphabetical order (except Answer is listed last)
- [ ] On click of Stipulation, app navigates to Stipulation Document category screen 
- [ ] Stipulation document category screen displays all document types under that category in alphabetical order 
- [ ] On click of Stipulation of Settled Issues, app navigates to File a Document form 

**Scenario 17**
* Navigate to  [Brief] document category screen 
* Click “View All Document Categories 
* Click “What is this document for” 
* Click “What document are you filing” 

Expected Results 
- [ ] On click of “View All Document Categories”, app navigates to All Document Categories screen 
- [ ] On click of “What is this document for”, app navigates to “What is this document for” screen 
- [ ] on click of “What document are you filing, app navigates to “what document are you filing” screen  


### What can I include with my document 

**Scenario 18**
* From File a Document form, select What can I include with my document link 
* Click “Back to File a Document Form 

Expected Results 
- [ ] On click of “What can I include with my document link “,  app navigates to What can I include with my document 
- [ ] On click of “Back to File a Document form” , app navigates to File a Document form

**Comment by uxforgood** [comment]
@rachaelparris Error messages for File a Doc 

File Upload 
"You must upload a document"

Certificate of Service 
"Enter date for Certificate of Service"

Objections 
"Enter selection for Objections" 

Supporting Document Type
[Supporting Document #X] - Choose a Document Type 

Supporting Document Signed BY
"[Supporting Document #X] - Enter name"

Upload Supporting Document
"[Supporting Document #X] - You must upload a document"

Secondary File Upload 
"[Secondary Document #X] - You must upload a document"

Filing Parties 
"Select a filing party"

Secondary Supporting Document Type 
"[Secondary Supporting Document #X] - Choose a Document Type"

Secondary Supporting Document Signed By
"[Secondary Supporting Document #X] - Enter name"

Upload Secondary Supporting Document
"[Secondary Supporting Document #X] - You must upload a document"

**Comment by uxforgood** [comment]
UX review from 7/22/19 discovered the following UI bugs @JessicaMarine @rachaelparris @wbyoko @kkoskelin 

- [ ] 1 Need to update the error state on the What document are you filing page
      - [ ] a) Update error language on "who signed" to read "Enter name" 
      - [ ] b) Update error language on "which doc in support of" to read "Choose a document"  
      - [ ] c) Add the error summary at the box of the page

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/70f237f1-3870-4574-85e9-20d77200cfa4)

- [ ] 2 On desktop sidebar "need help selecting doc" - add more space above View All Document Categories" button - should total 40px above button

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c01480d0-2153-4fd5-b953-44c3e081c1fd)

- [ ] 3 Update text under All Document Categories to read "Expand a document category and select the document type you wish to file." 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/d2b41213-692b-4455-9d98-ce525d9f27af)

- [ ] 4 On the File Your Document page - the objections question should be sentence case

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/2a69b795-2b4d-4f7a-bd8f-8045b0fb9e75)

- [ ] 5 GLOBAL CHANGE - On the "Are you sure you want to cancel" modal, the "No, continue" text is confusing. Could be read as "continue with cancel action." Change text on that button to read "No, take me back" 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e86cfa7f-6070-45c2-a72d-a5b000178a6d)

- [ ] 6 On MOBILE - on the case detail page, reduce the space between the oldest/newest sort and the top of the table

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/5c71d46d-4cc7-4bee-8076-5c36d2db7f5d)

- [ ] 7 On MOBILE - on the case detail page, increase the line height of mobile text links to be 20px and reduce the line height of mobile body copy to be 20px  @rachaelparris may already be addressing this with global mobile font stylings

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ccc2f80d-d967-4104-80da-f5d55b0ef800)

- [ ] 8 On MOBILE - docket heading during the file document pages looks like it's scaled down the 700px content container. Text should expand all the way across on mobile, so this text wouldn't be wrapping this way

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c6ce9f69-6128-4a72-8293-c42c4e986fc5)

- [ ] 9 on MOBILE - "What can I include" link - the 2nd line should wrap left aligned with the first line, so that the icon appears in its own "column" 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/5c9a7e0c-2075-4cac-8781-a93a476e8ab0)

**Comment by klohman** [comment]
UX Review 

- [ ] 10) Fix wrapping on helper text 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d92827f9-6f47-453f-a639-309a155e3b89)


- [ ] 11) Remove page-level error summary for errors on modal form for nonstandard docs 

![Screen Shot 2019-07-23 at 10.57.14 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/72df4cfc-9cb2-47a8-b938-f206e57c5f12)

**Comment by JessicaMarine** [comment]
7/25/19 PO Review:
* On `Motion for Leave to File` and `Motion for Leave to File Out of Time` document types, if the secondary document is a motion, we either need to make the question about Objections required
* Need ability to remove supporting doc (once selected) -- already added to a clean-up story

**Comment by JessicaMarine** [comment]
7/25/19 (5pm) PO Review:
* The secondary document for a `Motion for Leave to File` is optional.  It's only if a filer uploads the actual secondary document _and_ it's a motion that the Objection question needs to be required. I'm getting an error message on the secondary document's Objection question when I didn't upload a secondary document
* If I am trying to file a simple document (say a Motion for Summary Judgment) - if I click on Attachments and Certificate of Service, but then decide I have neither and unclick both, when I proceed to the review screen, the C/S information is showing there.  However, if I follow the same flow and only click and then unclick the Certificate of Service box, it doesn't carry through to the review screen.  There appears to be something funny going on when you click and then unclick both buttons.

**Comment by JessicaMarine** [comment]
7/24/19 PO Review:
*  In 402-19L, I tried to file a `Motion for Leave to File a Motion for Summary Judgment` and was lodging the `Motion for Summary Judgment`.  I only selected Nicole Smith as the filing party.  She showed up fine as the filing party on the review screen, but there wasn't anyone listed as the filing party on the docket record once I completed the transaction.
