### ISSUE TITLE
Global navigation

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1510]
As a user, so that I can easily navigate within the system, I need global navigation.

## Pre-Conditions
* User is logged in

## Acceptance Criteria
* Users can easily navigate around the system
* Users have a way to sign out of the system

## Tasks
- [x] add logo (Matt #1641)
- [x] primary links with styling (Matt #1641)
- [x] computed to show / hide primary links based on roles (Matt #1641)
- [x] user dropdown (Matt #1641)
- [x] mobile? (Matt? #1641)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by uxforgood** [comment]
# Global Header

- All logged in users see this global header


![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ac8398e2-e24d-4661-a787-4b641bf5c372)

**Comment by matthopson** [comment]
@uxforgood Will there be a mobile / small screen view?

**Comment by uxforgood** [comment]
@matthopson @ericsorenson 

## Mobile views

### Default
- User taps on Menu and opens menu drawer
- Pressed state of Menu button is #205493 background

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/58da20aa-ee2f-48a2-8f01-972e5961b97e)

### Open
- When user taps on navigation item, drawer closes and user is taken to that page
- User can close drawer by tapping on "Close" label or icon or tapping outside of the menu area
- Pressed state for navigation items is underline (indicated by hover hand in mockup)
- Pressed state for search button is #205493 background

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/bf617f5c-9e5a-4fbf-a8d9-6e6e4c38f168)

**Comment by klohman** [comment]
UX Review Notes 

- Font should use our H2 style
- Icon on dropdown is small - design has 25w/25h
- “My Cases” link should show“on-state” when on the dashboard (external users)
- “Messages” should show“on-state” when on Work Queue (for internal users)
- Search bar should be wider (see design)
- Need hover state on the dropdown  (see design)
- Hover state on text link - link should change color to #1a4480
- Logged Out version - the “Log In” - should be semi-bold
- the Respondent role needs to have the My Cases link in header

**Comment by matthopson** [comment]
@klohman These have been addressed.
