### ISSUE TITLE
External User: View documents uploads before they are associated with case/docket entry (Orphan Documents)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1566]
As an external user (Petitioner, Practitioner, IRS attorney), in order to make sure the correct document is being uploaded, I need to the ability to view documents before they are associated with a case/docket entry.

There are several instances where an external user needs the ability to view documents before they are associated with a case/docket entry:
* As an external filer, I need the ability to review the documents I am trying to submit as my petition package before the case is created.
* As an external filer, I need the ability to review the documents I am trying to file before they are filed in an existing case.

## Pre-Conditions:
* External user (Petitioner, Practitioner, IRS attorney) is in the process of uploading a document

## Acceptance Criteria:
* External user (Petitioner, Practitioner, IRS attorney) has the ability to view documents before they are associated with a case/docket entry
* External user (Petitioner, Practitioner, IRS attorney) can perform this task on mobile device

## Notes
* This story does not address Start a Case review page. This will be handled in #1402 when we work on the review story. 
* Concurrent work on these pages. Themis working on File a Doc page in same sprint. 
* No housing of documents in temporary state for this story

## Tasks
 - [x]  Finalize test scenarios and inform team they're ready (Mariah to pair w/Sarah)
 - [x] POC modal vs. tab for document display (Eric and Matt #2374)
 - [x] Testing modal vs. tab on tablets/phone (Cody)
 - [x] Add spinner (Joe #2388)
 - [x] Update UX design (Sarah)
 - [x] Adding links to all review pages (Matt)
- [x] Error message on failure to load document

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
 - [ ] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Eric)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt #2408)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Cody)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Joe)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by sarahridgway** [comment]
*Preview Document on Review*

When reviewing a "File a Document" submission, the user shall be able to preview the selected documents to ensure the file they selected is the right one.

- File name is a link
- When clicked, the link opens a new tab / window with the selected document

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/7f863449-400c-4784-a04d-a68db0ac5f9e)

Approval for this approach provided June 4th.

**Comment by sarahridgway** [comment]
Select comments from review:

From CS to Everyone: (09:46 AM)
 we can have separate s3 buckets an unvalidated bucket and validated bucket Probably have a TTL on the unvalidated bucket to delete them after a couple of hours as well 

From MH to Everyone: (09:48 AM)
 I feel like the link should be session based in some way . So it can only be used by that user 

From WJ to Everyone: (09:53 AM)
 I think the risk is that an executable is given a “.pdf” extension, and then some privilege-escalation exploit allows it to be executed. When we allow people to upload PDFs, we’re allowing arbitrary payloads to be stored on our server, until such time as we examine the payload to see if it’s malicious. So we really need to treat all PDFs, pre-scan, as if they’re rootkits. Since Lambdas don’t restart fresh on each use, every subsequent user of the Lambda could be infected by that poisoned upload.

From JS to Everyone: (09:55 AM)
 We can stream files remotely through Lambda to a ClamAV daemon to EC2 in that case. It’d be faster, too, lol.

From WJ to Everyone: (09:58 AM)
 What I like about using a quarantine bucket is that the total number of exposed files is reduced, *and* if they’re infected by a malicious upload, they’re infected *prior* to a flattening and a scan, which reduces the risk that they spread further.

From JS to Everyone: (10:00 AM)
 Two buckets isn’t a bad idear, because you’re treating all files as “guilty” until they’re proven innocent through an extrapolated database of virus signatures. Then, and only then, they can be moved to a “clean” bucket.

From WJ to Everyone: (10:01 AM)
 I’d be surprised if the CISO didn’t insist on that approach.

**Comment by mariahkannenberg** [comment]
### Test Scenarios (DRAFT)

**Petitioner Views Uploaded Document Before Submitting Case**

Petitioner logs in
Petitioner selects File a Petition
Petitioner selects “Got it, Let’s Start My Case”
Petitioner uploads all documents 
Petitioner sees document name is a link
Petitioner selects document link and document opens in a new page
Petitioner fills out all metadata associated with the case
Petitioner selects “Review and Sign” checkbox
Petitioner selects “Submit to US Tax Court”
Petitioner logs out


**Practitioner Views Uploaded Document Before Submitting Case**

Practitioner logs in
Practitioner selects File a Petition
Practitioner selects “Got it, Let’s Start My Case”
Practitioner uploads all documents 
Practitioner sees document name is a link
Practitioner selects document link and document opens in a new page
Practitioner fills out all metadata associated with the case
Practitioner selects “Review and Sign” checkbox
Practitioner selects “Submit to US Tax Court”
Practitioner logs out
IRS Attorney Uploads Document To Existing Case
IRS Attorney logs in
Practitioner selects File a Petition
Practitioner selects “Got it, Let’s Start My Case”
Practitioner uploads all documents 
Practitioner sees document name is a link
Practitioner selects document link and document opens in a new page
Practitioner fills out all metadata associated with the case
Practitioner selects “Review and Sign” checkbox
Practitioner selects “Submit to US Tax Court”
Practitioner logs out

**Petitioner Uploads Document To Existing Case**



**Practitioner Uploads Document To Existing Case**
