### ISSUE TITLE
Docket Clerk: Ability to scan/upload document after docket entry is created

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1567]
As a Docket Clerk, in order to manage my work flow, I need the ability to scan/upload a document after the docket entry is created.

When a Docket Clerk is processing a paper document, they may choose to scan/upload the document at the same time that they are creating the docket entry.  However, a Docket Clerk may also choose to create several docket entries and then come back and scan/upload the documents for each docket entry.  The Docket Clerk needs the flexibility to do both.

## Pre-Conditions:
* Docket clerk has a paper-filed document
* Docket Clerk can create a docket entry without a document (#1896)

## Acceptance Criteria:
* Docket Clerk must have the ability to scan/upload document to a previously created docket entry
* Court users and parties must be able to see which docket entries are incomplete on the docket record (missing scanned doc)
* Docket Clerks must be able to see which docket entries are incomplete in a way other than on the docket record (so they don't forget)
* Docket Clerks must be able to select a docket entry for which to scan/upload a document
* Incomplete docket entries on the docket record are viewable

## Notes:
* Docket clerk may have a section on dashboard that lists incomplete docket entries
* Comprehensive tests required - when things are valid vs not valid
* Story #1896 will change the add docket entry page so user can add an entry without a document
* Docket entry without a document will appear on the docket entry but will not have a hyperlink (or could have a hyperlink that links to doc detail to complete)
* Start with all potential states of a document / docket entry
* Docket Clerks normally complete these on the same day (working box on their desk)
* Possibilities for displaying incomplete docket entries include on the QC for the user who made the entry (as well as in the section), probably shown separately from other QC items
* Court currently tells parties that an entry is "pending" when there is no doc attached yet
* No links are provided to public / parties on docket record as standard

## Tasks
 - [x]  Test scenarios around docket entry states
 - [x]  Validation for docket entry that does not include adding a document as required
 - [x]  Show incomplete entries on the docket record
 - [x]  Assign work item to creator (Docket Clerk)
 - [x]  In Progress Tab on Docket Clerk - My Document QC
 - [x]  In Progress Tab on Docket Clerk - Section QC
 - [x]  Edit docket entry route
 - [x]  Editable docket entry view (reuse create view) for incomplete docket entries
 - [x]  Update docket record interactor

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (#2749 Cody Jojo)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (#2749 Cody Jojo)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (#2749 Cody Jojo)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by sarahridgway** [comment]
## Scanning with Existing Docket Entry

### Docket Clerk - My / Section Document QC - In Progress tab

The Docket Clerk's "In Progress" tab displays docket entries which do not have a document associated with them. 

* "My" In Progress tab shows existing docket entries which are assigned to the user
* "Section" In Progress tab shows docket entries assigned to any user
* Docket entries are, by default, assigned upon creation to the Docket Clerk who created them
* Docket entries can be re-assigned through the "Section" In Progress tab to another DC
* Docket entries cannot have a state of "unassigned" (there is no way to remove an assignment)
* In Progress table has a docket number, filing date, document title, and case status columns
* In Progress table is sorted by filing date from oldest to newest
* In Progress tab does not have "read" and "unread" states
* Clicking on the document name takes user to the document's editable entry detail page
* Items drop off the table when a document has been saved to the entry

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/fa420e30-e865-44ec-a88e-7530e97de5ac)

### In Progress Docket Entries on the Docket Record

* Existing docket entries without an associated document are shown on the docket record
* Docket entries without a document are shown with a yellow row highlight and yellow pin icon
* External users see the docket entry on the docket record without a link

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/1ea3373a-cc39-419d-9ad6-09364e58f5b2)

### Editable Entry Detail Page

The entry detail page allows users to edit existing entry metadata and scan or upload a document to the entry. 

* Entry detail page uses the same form and scan / upload utility as new docket entries
* Entry forms are pre-populated with existing information entered by clerks during creation
* A yellow alert appears above the scan / upload utility panel to notify users of incomplete state 
* Clicking "Save" attaches the document to the entry, removes any "in progress" flags
* User is sent to case detail page upon saving

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/42fd26ee-7f86-4c57-9edc-295dc5b5c4e4)

### Completed Docket Entry

* A confirmation message is displayed on the case detail page
* Docket entry should not appear on any In Progress tabs
* Docket entry should not have "in progress" style on docket record

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/3e1ef461-1d04-4217-bcc2-df38f780649f)

**Comment by sarahridgway** [comment]
## Test Scenarios: Published 8/2

The following test scenarios from #1895 apply. Details provided where the scenario differs materially from the counterpart from #1895.

#### Set-Up Flow - Case Detail Page
* Docket clerk logs in
* Navigates to Case Detail page
* Sees Docket Entries on docket record with incomplete style (yellow background and pin icon)
* Clicks an existing Docket Entry for which a document has not yet been associated
* Sees "Add Docket Entry" page
* Sees incomplete entry alert
* Scan radio button is selected by default

#### Set-Up Flow - In Progress Tab
* Docket clerk logs in
* ClicksDocket QC
* Sees Docket QC Inbox tab
* Clicks In Progress tab
* Sees Docket Entries to which they have been assigned which have no documents
* Sees Docket number column
* Sees Docket Entry filing date column (sorted by oldest to newest)
* Sees Document name column
* Sees Case Status column
* Does not see read or unread states
* Clicks section toggle (section, in progress)
* Sees Docket Entries to which all clerks have been assigned which have no documents
* Sees Docket number column
* Sees Docket Entry filing date column (sorted by oldest to newest)
* Sees Document name column
* Sees Assigned To column
* Sees Case Status column
* Does not see read or unread states
* Clicks an existing Docket Entry for which a document has not yet been associated
* Sees "Add Docket Entry" page
* Sees incomplete entry alert
* Scan radio button is selected by default

#### First Use - Install Flow

#### First Use - Cancel Install Flow

#### Select Scanner Flow

#### Document Upload Flow

#### Add First Batch Flow

#### Hopper is Empty Flow

#### Preview Multiple Batches Flow

#### Rescan a Batch Flow

#### Delete a Batch Flow (multiple batches)

#### Delete a Batch Flow (single batch)

#### Create PDF Flow

#### Delete PDF Flow

#### Save without Errors Flow
* [scan flow]
* [create PDF flow]
* Enter metadata
* Click Save
* Sees Case Detail page with confirmation message
* Sees Docket Entry "incomplete" style in docket record has been removed
* Sees Docket Entry has a paper filing icon in docket record
* Clicks on same Docket Entry in docket record
* Sees Docket Entry's Document Detail Page
* Sees Correct PDF
* Sees original filing date - date the clerk entered, not date the document was added
* Clicks Document QC
* Clicks In Progress Tab (my)
* Sees that Docket Entry is not present
* Clicks Processed Tab (my)
* Sees that Docket Entry is present
* Clicks Section toggle (section, processed)
* Sees that Docket Entry is present
* Clicks In Progress Tab (section)
* Sees that Docket entry is not present

#### Save with Errors Flow
* [scan flow]
* [create PDF flow]
* Enter metadata
* Click Save
* Sees page and field level error messages

#### Cancel Docket Entry Flow
* Sees Add Docket Entry Page
* Clicks Cancel
* Sees Case Detail Page, no action taken

#### Scanning Error Flow

#### Unfinished Scans Flow (see Non-Petitions Document Not Finished)

**Comment by JessicaMarine** [comment]
PO review 8/21/19:
 Once the docket clerk goes back in and adds the document, it looks like it is auto-generating a message:
image.png 
image.png

However, that message isn't going to anyone and isn't in the docketclerk's sent box
