### ISSUE TITLE
High Priority Indicator for External Filings (automated)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1584]
As a Court user, in order to easily identify items that are high priority and need immediate attention, I need a high priority indicator on certain messages in my work queues. 

There are 10,000s of documents that get filed each year with the Court.  In general, the Court processes things on a first-in-first-out basis.  However, when documents get filed in cases that are set for trial, those documents must be processed ASAP.  For external filings, there needs to be the ability to automatically set something as high priority based on Court-provided parameters.  This will apply whenever a document is filed in a case that is calendared for a trial on trial session.   

## Pre-Conditions:
* External document is filed in a case that is scheduled for trial.
* External document is routed to Docket QC box.

## Acceptance Criteria:
* External filings should automatically be marked as high priority based on Court-provided logic
* High priority items should appear at the top of the QC box and should be displayed in descending order based on trial date. 
      * Any document filed in a case that is calendared for trial should automatically be tagged as high-priority.  The high-priority items should be further prioritized by trial/hearing date.  Closest trial/hearing date first then second closest etc.

## Notes:

* We may have design for this already in Figma

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add high priority to work item entity (Rachael #4199)
- [x] 2 Set high priority to true when creating a work item for an external document filing if the case is calendared for trial (Rachael #4199)
- [x] 3 Add high priority indicator to work items in document QC inboxes (individual and section inboxes only) (Rachael #4199)
- [x] 4 Sort work items in document QC inboxes with high priority items at the top (individual and section inboxes only) (Cody #4204)
- [x] 5 Sort high priority work items in trial date order (oldest to newest), then by date received (oldest to newest)  (Cody #4204)
- [x] 6 Add trial date to work items and update it when the trial date is updated (same way we update the docket number suffix) (Rachael/Kris #4205)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Docket - My Document QC Inbox 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c54bf9c7-31b7-4b44-8186-f4db62ec9fcb)

**High Priority Icon**
* Displays for all documents in cases with case status = Calendared 
* If case is unread and high priority, display high priority icon 
* If case is read and high priority, display high priority icon 

**High Priority Inbox Order**
* Display High Priority documents at top of QC Inbox regardless of date received 
* High Priority documents should display sorted in trial date order (oldest to newest), then by date received (oldest to newest)
* High Priority indicator does not display in In Progress or Completed lists

#### Docket Section - Document QC Inbox 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f5ba0647-6553-4def-a220-c75d59c42f77)

**High Priority Icon**
* Displays for all documents in cases with case status = Calendared 
* If case is unassigned and high priority, display high priority icon 

**High Priority Inbox Order**
* Display High Priority documents at top of QC Inbox regardless of date received 
* High Priority documents should display sorted in trial date order (oldest to newest), then by date received (oldest to newest)
* High Priority indicator does not display in In Progress or Completed lists

**Comment by klohman** [comment]
### 1584 Test Scenarios 

E-file documents 

* Case 1 
    * Case Status - General Docket Not At issue 
    * eFile - Motion for New Trial 
* Case 2 
    * Case Status - Calendared 
    * Trial Date : 04/01/2020
    * eFile Motion for Summary Judgement 
* Case 3 
    * Case Status - Calendared 
    * Trial date: 03/01/2020
    * eFile Answer 


#### 1) Docket clerk sees document in Calendared case with high priority indicator in Section Document QC Inbox 
* Login as docket clerk1 
* View Section Document QC 
Expected results 
- [ ] Motion for New Trial for Case 1 does not display high priority indicator 
- [ ] Motion for Summary Judgement for Case 2 displays high priority icon 
- [ ] Answer for Case 3 displays high priority icon 

#### 2) Docket clerk sees document in Calendared case with high priority icon in My Document QC Inbox 
* Scenario 1 
* Assign documents for Case 1, 2, 3 to docket clerk 1 
* View My Document QC 
Expected results 
- [ ] Motion for New Trial for Case 1 does not display high priority indicator 
- [ ] Motion for Summary Judgement for Case 2 displays high priority icon 
- [ ] Answer for Case 3 displays high priority icon 

#### 3) Docket clerk sees documents in Calendared case at top of list in My Document QC Inbox 
* Scenario 2 
* View My Document QC 
Expected results 
- [ ] Documents for Case 2 and 3 display above documents for cases without Calendared status

#### 4) Docket clerk sees high priority documents listed in order of trial date at top of list in My Document QC Inbox 
* Scenario 2 
* View My Document QC 
Expected results 
- [ ] Sort order for QC is as follows 
    - Answer for Case 3 
    - Motion for Summary Judgement for Case 2
    - Motion for New Trial for Case 1  

#### 5) Docket clerk sees high priority documents listed in order of trial date at top of list in Section Document QC Inbox 
* View Section Document QC 
Expected results 
- [ ] Sort order for QC is as follows 
    - Answer for Case 3 
    - Motion for Summary Judgement for Case 2
    - Motion for New Trial for Case 1  

#### 6) Docket clerk sees high priority indicator when document is unread in My Document QC Inbox 
* Scenario 2
Expected results 
- [ ] High priority icon displays on Motion for Summary Judgement for Case 2
- [ ] High priority icon displays on Answer for Case 3 

#### 7) Docket clerk sees high priority indicator when document is read in My Document QC Inbox 
* Scenario 2 
* Click into Answer for Case 3 
* View My Document QC 
Expected result:
- [ ] High priority icon displays on Motion for Summary Judgement for Case 2
- [ ] High priority icon displays on Answer for Case 3 

#### 8) Docket clerk sees high priority indicator when document is unassigned in Section Document QC Inbox 
* Scenario 1 
Expected results 
- [ ] High priority icon displays on Motion for Summary Judgement for Case 2
- [ ] High priority icon displays on Answer for Case 3 

#### 9) Docket clerk sees high priority indicator when document is assigned in Section Document QC Inbox 
* Scenario 2 
Expected results 
- [ ] High priority icon displays on Motion for Summary Judgement for Case 2
- [ ] High priority icon displays on Answer for Case 3

**Comment by klohman** [comment]
UX Review 

- [ ] If document is unread and high priority, the high priority icon should display; document name should still be bolded 
![Screen Shot 2020-01-24 at 10.54.10 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/36a715f2-240f-40cb-b6cd-05dcddc01f9d)

- [ ] If document is read and high priority,  the high priority icon should display
![Screen Shot 2020-01-24 at 10.57.49 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/56d6808f-e7a9-430e-b076-b6283d664db9)
