### ISSUE TITLE
Removing executables from documents

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1614]
As the Court, in order to protect the CMS from unnecessary risk, I need all executables to be removed from incoming documents.

## Acceptance Criteria:
* All executables must be removed from all incoming documents.

## Notes 
How to add binaries to Lambdas: https://instil.co/2017/08/07/using-native-dependencies-with-aws-lambda/

## Tasks
- [x] 1 create use-case interactor for sanitizing PDFs (Kris, William, Rachael) #1890
- [x] 2 integrate sanitizing use-case into workflow that adds cover sheet (Kris)
- [x] 3 add docker updates for ghostscript4js #1890
- [x] 4 write tests producing image diff artifacts with pixel differences under a given threshold (Rachael, Kris, William - in branch `pdf-comparison-demo`)
- [x] 5 figure out the `no-cache` docker issue (Rachael #1902)
- [x] 6 add interactor to Lambda with native ghostscript library (Rachael)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael #1929)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by kkoskelin** [comment]
This is a thin node wrapper library around your platform's native install of ghostscript.  It requires writing to/reading from the disk, as far as I can tell.  It produces pretty good output. 
`/* eslint-disable no-console */
const gs = require('ghostscript4js');

/*

Follow the Ghostscript4JS prerequisite installation steps at
https://www.npmjs.com/package/ghostscript4js#prerequisites
Or for MacOS:
`brew install ghostscript`
Add the following to your ~/.bash_profile or ~/.bashrc
`export GS4JS_HOME="/usr/local/lib"` 
const gs = require('ghostscript4js');

consult GS docs at https://www.ghostscript.com/doc/current/VectorDevices.htm#Extensions

command-line experiments:
Convert PDF to PNG:
gs -dBATCH -dSAFER -dNOPAUSE -q -sDEVICE=png48 -sOutputFile=1-%02d.png -r144 1.pdf 
(creates 1-01.png, 1-02.png, etc)

Convert PDF to PS:
gs -dBATCH -dSAFER -dNOPAUSE -q -sDEVICE=ps2write -sOutputFile=intermediate.ps -f FILENAME

Convert PS to PDF:
gs -dBATCH -dSAFER -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=pdf-from-ps.pdf -dPDFSETTINGS=/prepress -dHaveTrueTypes=true -dEmbedAllFonts=true -dSubsetFonts=false -f example.ps
*/

const args = process.argv.slice(2);
const [inputFile, outputFile='output.pdf'] = args;
if(!inputFile) {
  throw Error('Usage: node pdf-roundtrip.js myinput.pdf myoutput.pdf');
}

const pdf2psArgs = ['-dBATCH',
  '-dSAFER',
  '-dNOPAUSE',
  '-q',
  '-sDEVICE=ps2write',
  '-sOutputFile=intermediate.ps',
  `-f ${inputFile}`,
];

const ps2pdfArgs = [
  '-dQUIET',
  '-dBATCH',
  '-dSAFER',
  '-dNOPAUSE',
  '-dNOCACHE',
  '-sDEVICE=pdfwrite',
  '-dPDFSETTINGS=/prepress',
  '-sColorConversionStrategy=/LeaveColorUnchanged',
  '-dAutoFilterColorImages=true',
  '-dAutoFilterGrayImages=true',
  '-dDownsampleMonoImages=true',
  '-dDownsampleGrayImages=true',
  '-dDownsampleColorImages=true',
  `-sOutputFile=${outputFile}`,
  '-f intermediate.ps',
];

const ps2pdf_cmd = ps2pdfArgs.join(' ');
const pdf2ps_cmd = pdf2psArgs.join(' ');

try {
  gs.executeSync(pdf2ps_cmd);
  console.log('Created PS intermediate.ps');

  gs.executeSync(ps2pdf_cmd);
  console.log(`Created PDF ${outputFile}`);

} catch (err) {
  console.log(err, err.message);
  throw err;
}
`

**Comment by wbyoko** [comment]
This could be an option: https://github.com/sina-masnadi/lambda-ghostscript
