### ISSUE TITLE
New Design: All Messages/QC Review

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1658]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update all messages/QC review pages. 

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* Messages/QC Review design for all sections and users are updated with newest changes to our style guide

## Tasks
- [x] Convert messages header to blue bar design, with message context toggle (Matt #1698)
- [x] Show message icon in global nav when message count is greater than zero (Cody #1689)
- [x] Pull table controls out of the table (selected, actions, etc.) (Cody #1693)
- [x] Main table design (Joseph #1706)
- [x] Case status label text should be bold (Kris)
- [x] "Switch to X" toggle link should be underlined by default (stays underlined and changes color on hover) (Rachael #1735)
- [x] Hyperlinked document title should show uniform blue outline (Kris #1750)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated

**Comment by uxforgood** [comment]
## My Messages (page type - changes also apply to My Document QC)

Changes to Note: 
* Toggle between my/section in blue header bar
* Updated tab design
* Updated table design (table fonts are 17px, except message text is still 15px) 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/f37ab656-37e6-408a-a115-dc03ad724fcb)

## Section Messages (page type - changes also apply to Section Document QC)

Changes to Note: 
* Assign to actions moved outside of table

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/66176da8-c2cf-40ba-9be9-8786654a1183)

**Comment by sutt0n** [comment]
@uxforgood Are we removing the expand message functionality?

**Comment by uxforgood** [comment]
@sutt0n Yes, remove all open/close message functionality.

**Comment by klohman** [comment]
UX comments on 1658: 
Header
- on-state border should be 3px 
- Need more space between profile icon and caret 

Table
- Header row bottom border should be 1px 
- Need row hover state on My Messages inbox and sent box 
- Hover state on Section Messages inbox needs to be updated with new style 
- Need row hover state on Section sent box
