### ISSUE TITLE
New Design: Document Detail Page

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1660]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update Document Detail Page

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* Document Detail Page design is updated with newest changes to our style guide

## Notes
* (From 1652 review)-  Required fields on Send Message form not showing field level errors 

## Tasks
- [x] 1) update card styles in messages (Cody #1720)
- [x] 2) realign the filed by (Matt #1736)
- [x] 3) buttons on messages / header (Cody)
- [x] 4) align pdf view with tabs on left (Kris #1742)
- [x] 5) fix tab styles (blue background on selected) (Cody)
- [x] 6) subtab styles (Cody)
- [x] 7) fix field level errors for send message (Cody #1749)
- [x] 8 H3 tabs should be split evenly and centered across the horizontal space (Cody #1756) 
- [x] 9 H3 tabs onstate/hover state underline should be closer to text (update padding-bottom to 5px for .ustc-ui-tabs.container-tabs nav ul li button span) (Cody #1756) 
- [x] 10 Space between document name and filed by should be 15px (William #1758)
- [x] 11 Field borders should be #71767a bg-base (Rachael #1761)
- [x] 12 Doc Info Parties tab (for Petition doc type) - Remove "Mailing Address" (this might be global, if so, remove in all cases) and change "Address Line 1" to "Mailing Address Line 1"  (Rachael #1761)
- [x] 13 Notice Attached to Petition + Type of Case - should be 15px between label and field (Rachael #1761)
- [x] 14 toggle group buttons missing hover state (Kris #1777  )
- [x] 15 Side by side boxes should top align and tabs sit above that in horizontal plane. Currently tabs are aligning with the doc (Cody #1765)
- [x] 16 Add Message (under Complete) needs correct styling for "optional" (Kris #1769)
- [x] 17 Blue background for H3 tabs isn't extending all the way to the right - there's a weird gray box sitting behind it (Kris #1760)
- [x] 18 Serve to IRS button should right align with PDF box (Kris #1760)
- [x] 19 Update disabled style of "Select Recipient" dropdown on Sent to toggle group button in Messages tab (Kris #1788)
- [x] 20 SG - divider line between messages under View History needs to be bg-base-lighter (Rachael #1784)
- [x] 21 SG - completed messages- text needs to be updated to base color
- [x] 22 SG - completed message card - border should be bg-base-lighter 
- [x] 23 in case header, space between docket number and case status label should be 15px  (Matt #1763)
- [x] 24 in case header, space between caption and edit link should be 15px  (Matt #1763)
- [x] 25 Document Info and Messages tab set should be 24px (Matt)
- [x] 26 Petition- Batched for IRS- doc detail view - space between label and read only field should be same as on case info tab (15px?) (William #1779)
- [x] 27 The Batched for IRS + recall button needs to be styled completely on Petition Doc Detail - Batched for IRS screen (William #1762)
- [x] ~~28  serve to irs button needs to right align to the pdf viewer chrome~~ (duplicate of 18)
- [x] 29 Parties Tab- increase padding above  v. commissioner line (Matt)
- [x] 30 Case Info tab - space between fields should be 20px (Rachael #1807)
- [x] 31  Parties tab- when no party is selected - too much space between bottom of party type drop list  and bounding box bottom border - should be 20px (Rachael)
- [x] 32 Checkboxes and radios should have 1px border (see style guide) 
- [x] 33 Trial Location and Fee Payment ID labels too close to their respective fields
- [x] 34 Tab bounding box (general) should have 20px spacing between the last field and the border (Matt #1775) 
- [x] 35 Radio buttons/check boxes should have hover state of 1px primary-darker
- [x] 36 Parties tab- styling of "optional" on field label should be bg-base, 15px, regular weight 
- [x] 37 Save success message next to save button should be #2e8540 success-green (Rachael)
- [x] 38 Align check box with text on Order for ownership disclosure statement under corporation and partnerships categories, Party Info tab (William #1785)
- [x] 39 No period on "No file uploaded" for ODS in corp and partnerships categories, Party Info tab (Joe)
- [x] 40 Help text colors throughout the taxpayer categories on Party Info tab (Joe)
- [ ] ~41 (your name) vs (optional) applied inconsistently on C/O fields in several categories in Parry Info tab - @uxforgood do they make sense as-is or should we make them uniform? (Joe)~
- [x] 42 Update Fee Payment Date style to Internal Date Field on Petition QC page - Case Info (Rachael #1783)
- [x] 43 Messages - the check icon next to Complete should be fas.fa-check-circle (Rachael #1818)
(https://fontawesome.com/icons/check-circle?style=solid)
- [x] 44 Complete message - Need 40px spacing between Add Message field and Complete button (Rachael #1814)
- [x] 45 Send Message- Decrease spacing between fields to 30px total - looks like there is 30px space (15 margin, 15 padding) on the field itself and another 30px bottom padding on the group (Rachael #1818)
- [x] 46 F/u #21 - Completed message text should be #1b1b1b theme-color-ink (Rachael #1814)
- [x] 47 F/U #27 - Batched for IRS label section (with Recall button) should bottom align with the H3 tabs. On this screen, the PDF and form sections are misaligned- need to top align (William #1816)
- [x] 48 F/U #30 - Date Received looks like has 30px bottom on margin and on field set- need to decrease (should look like the Fee Payment Date field spacing) (Rachael #1814)
- ~[ ] 49 F/U #35 - checkbox/radio hover state - looks like dev has 2px, should be 1px (Rachael)~ should be 2px
- [x] 50 - Parties tab - need to add 30px spacing between address fields (City, State, Zip, Phone number) -throughout (Rachael #1814)
- [x] 51 F/U #39 - Still seeing period after “No file uploaded” (Natalie #1815)
- [x] 52 Parties Tab- Estate with Executor- need 10px spacing above helper text on “Title” field (Rachael #1814)
- [x] 53 Parties Tab- Estate without Executor - In Care of Field needs spacing under label (Rachael #1814)
- [x] 54 Remove dropshadow from global search box in header (#1815 Natalie)
- [x] 55 On document detail other than the Petition, the PDF iframe needs to align with the H3 tabs (Rachel)
- [x] 56 The space under Date Received need to be decreased - should be 30px (Rachel)
- [x] 57 Update spacing between label and helper text (Kristen #1837)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated

**Comment by uxforgood** [comment]
## Document Info

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/3aa80128-7878-4211-b5f3-10612e12f344)


## Messages

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/3c551ab7-6f3a-4770-b39d-ce3d6a72759b)

**Comment by klohman** [comment]
* 55  On document detail other than the Petition, the PDF iframe needs to align with the H3 tabs 

* 56 The space under Date Received need to be decreased - should be 30px

**Comment by sarahridgway** [comment]
Spacing on "Add another" link 

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/9e76b3f1-7d4e-4491-8a4c-29e09fccd6fe)

**Comment by sarahridgway** [comment]
- [ ] Field hover state is invoked on mouse-in to field label in dev. Field hover state should be invoked on mouse-in to the field itself and only the field. Same is true for for check box groups and radio groups, with the exception of the individual check box labels and the radio labels which can invoke the hover state of their respective check boxes or radio buttons.

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/2623eab0-e30e-4d1d-a54c-74fd79644f99)

Documented in slack on 05/21

@codyseibert is this with you?
