### ISSUE TITLE
New Design: File an External Document Flow

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1661]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the External Document Flow.

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* External Document Flow is  updated with newest changes to our style guide

## Tasks
- [x] 1: Margin between sections with H3 - file document form (Matt #1786)
- [x] 2: Margin between sections with H3 - review (Matt #1786)
- [x] 3: Wrap Frequently Used Docs in blue-container and hide after doc type is selected (Rachael #1789)
- [x] 4: Add Card layout to Frequently Used Docs (Rachael #1789)
- [x] 5: Document Icon should be black not blue (William #1792)
- [x] 6: Remove "back" link above the docket number header (Matt #1796)
- [x] 7: Docket number header blue background should span full width (Matt #1796)
- [x] 8: Add space between the question mark icon and the text (in accordion) (William #1792)
- [x] 9: File Document should be H1 (William #1792)
- [x] 10: Accordion link needs hover state - text change to #1a4480 on hover added to style guide (Matt)
- [x] 11: Buttons should have 20px top margin (Rachael #1791)
- [x] 12: Upload fields have odd border around them- on Chrome (Kris #1799)
- [x] 13: Fields with helper text (upload document, who is filing) should have 10px between label and helper text (Rachael #1804)
- [x]  14: Change green on file upload icon to #2e8540 (Rachael #1794)
- [x] 15: Update field level error spacing - should be 15px below field (William #1803)
- [x] 16: Update spacing in Cancel modal -see Figma (Kris #1811)
- [x] 17: Update alert message on Review Page - icon color should be #ffbe2e; message header text should use H3 style (Rachael #1802)
- [x] 18: on Review page, need 40px spacing above buttons (Rachael #1797)
- [x] 19. Continue button needs 40px spacing above (Rachael #1797)
- [x] 20: Review page, Edit link should be bottom aligned with section header (Rachael #1800)
- [x] 21: Update spacing between "What Type of Document Are You Filing?", helper text below, and accordion button (Rachael #1808)
- [x] 22: Accordion content styling updates (see Figma) (Rachael #1810)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [ ] Usability has been validated

**Comment by uxforgood** [comment]
## Desktop

Key changes to note: 
* Freq used documents sidebar disappears after user has selected a document

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/cae49313-8fa9-4678-8782-3667917c7594)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/b47cb3cc-ce18-41de-b23d-933667b3c4a3)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/5d47195c-6a9e-4ca2-8747-3c7b44c657b6)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/577de8b4-52dd-44b1-84ea-74fde3debce1)

**Comment by sarahridgway** [comment]
Form

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/9e96a899-a0f4-4ff5-b3b5-82d7fd579de3)

Review

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/f1968961-136c-4489-9674-c4ed750e8090)

**Comment by matthopson** [comment]
@uxforgood Could you confirm the sidebar still disappears when selecting a document? I don't see this behavior. If you do still see it, could you elaborate on steps to reproduce?

**Comment by klohman** [comment]
Additional Tasks 

* 23 Certificate of Service Date - needs 15px space above date fields. When date is displayed, there is double spacing between date field and the “who is filing” field

* 24 Success message - Text is running into dismiss link

* 25 Secondary Document form, Additional Info fields are not styled

* 26 Supporting Document form - additional info fields and document type fields need to be styled same as primary form

* 27 Supporting Doc form- “Previous Document” Field needs to be styled

**Comment by matthopson** [comment]
@klohman ☝️all fixes merged to Dev

**Comment by sarahridgway** [comment]
- [ ] 32 Line height for wrapping lines needs to be specified in Frequently used docs section
- [ ] 33 Form Page > "Type of Document You're Filing" Section > New icon in figma
- [ ] 34 Form Page > "Tell Us About The ..." Section > tip shouldn't have a gap on the right side
- [ ] 35 Form Page > Upload file > Add padding between file name and Change link
- [ ] 36 Form Page > Upload file > Add padding between file upload label and green check mark
- [ ] 37 Review Page > Warning message > Add padding between bottom of header and top of body, refer to other messages in dev style guide and UX style guide
- [ ] 38 Progress indicator > When text is long (eg. "less than one minute left") there's no space on either side of the text - make modal width wider.
- [ ] 39 Progress Indicator > Progress bar green is new USWDS green. Revert? Tag @uxforgood 
- [ ] 40 Success message > Style updated by Cody for 1660, validate change is reflected here too
- [ ] 41 Bug? Form Page > Supporting doc section > Select a doc type, select a file, change doc type, file upload "change" link disappears and reverts to previous select doc control with file selected. If you try to submit the form at this point, the field errors. Continue to use the doc they selected regardless if doc type is changed.
- [ ] 42 Form Page > Error state > Error message is too far away from field

**Comment by sarahridgway** [comment]
- [ ] 46 File a Doc Form > Type of Doc Section > Icon as shown below

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/846f892c-6de0-4d47-948e-fc62bceb14fa)

- [ ] 47 File a Doc Form > Upload Your Supporting Doc > Upload field help text spacing

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/31191168-2716-40f7-830f-b56ba1a43743)

- [ ] 48 File a Doc Form > Selected file reset glitch (see 41 above) also present on secondary supporting document upload field (ping me - I can guide you)

- [ ] 49 File a Doc Form > Secondary Supporting Doc > Green check mark padding on upload field (same section as 48)

- [ ] 50 Review Page > Edit button position on first section header

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/9a25e634-3e52-4443-b43a-c3f9563a6e63)

- [ ] 51 Review Page > Extra space after last field in **every** section.

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/736d35dd-a3d2-4bc7-aaa0-cbf98b27886f)

- [ ] 52 Internal File a Doc Form > Who is filing this document, blank? 

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/6c3c3b90-df41-4714-b835-b0c0f6f300b2)

- [ ] 53 Internal File a Doc Form > Add document upload field label for secondary document doesnt have a green check mark when document has been selected. (I can guide you or use Motion for Leave to File as doc type to get there).

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/c54a8369-d763-4f6a-acac-9c999c4133ff)

- [ ] 54 Internal File a Doc Form > extra space at the end of each section. Must use Motion for Leave to File to access secondary doc section.

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/b6217c0b-f698-43e7-af09-4531b943a8e9)

**Comment by sarahridgway** [comment]
UX review of 1661 is complete! Moving to done :) Great job everyone!
