### ISSUE TITLE
New Design: File a Petition - "Before You Begin" Page

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1662]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the File a Petition - Before You Begin Page

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*File a Petition - Before You Begin Page is updated with newest changes to our style guide

## Tasks
- [x] 1. Update grid view (William #1809)
- [x] 2. Update Icons (William #1809)
- [x] 3. Top Bar Header (William #1809)
- [x] 4. Mobile Layout (William #1825)
- [x] 5 Replace PDF "Petition Filing Guide" version (Kristen #1845)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated

**Comment by uxforgood** [comment]
## Desktop

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e45b1b67-25fc-4598-8c54-584e35cd6044)

## Mobile

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c826a3b6-cadb-4655-93f0-4fe31952fd7e)
