### ISSUE TITLE
New Design: External User Dashboard and Error Pages

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1663]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update External User Dashboard and Error Pages

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*External User Dashboard and Error Pages is updated with newest changes to our style guide

## Tasks
- [x] 1 Update sidebar on petitioner dashboard - gray instead of blue box, separate Other Filing Options (Rachael #1819)
- [x] 2 Change Start a New Case button to File a Petition with icon and align with table (Rachael #1820)
- [x] 3 Update header of dashboard table (Rachael #1823)
- [x] 4 Update Search for a Case box styling on practitioner dashboard (Rachael #1823)
- [x] 5 Practitioner/petitioner dashboard view with no cases (Rachael #1826)
- [x] 6 Change header to full width big blue header (Rachael #1828)
- [x] 7 Error page updates (Rachael #1836)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated

**Comment by uxforgood** [comment]
## Things to note
* Icon on File a Petition button
* New sidebar style
* Updated table style

## Practitioner dashboard

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ea9aaa39-fa3d-4c2d-b702-7acd66718254)

## Petitioner dashboard

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/746dc299-62bf-4358-a63f-e99524125750)

## Mobile view (example is practitioner but petitioner works the same) 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/9437e1ad-7e53-4105-846b-d860d965b96a)

## 400 Error Page

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e0fcea2c-87f1-4dc3-a0b6-3e0d692a1b03)

**Comment by klohman** [comment]
UX Comments 

- [ ] Dashboard My Cases table - left align text (Kristen) 
- [ ] My Cases (mobile) view - "File Petition" button needs a left margin, text is not centered 
- [ ] My Cases (mobile view) - Need to reorder and align the table data for Petitioner (should match the design for practitioner)
