### ISSUE TITLE
New Design: Start a Case Form

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1664]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the Start a Case form

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*Start a Case Form is updated with newest changes to our style guide

## Tasks

- [x] 1 Add blue header “File a Petition” (William #1842)
- [x] 2 Set width of blue boxes to width of application (William #1851)
- [x] 3 Address padding at bottom of blue boxes (William #1854)
- [x] 4 “How do you want this case handled” intro paragraph width set to body-copy (Jojo #1849)
- [x] 5 Small/regular accordion should also be full-width (Jojo)
- [x] 6 Body-copy should be used for “review your information” paragraph, “Select trial location” paragraph, and “review and sign” checkbox label (Jojo #1849)
- [x] 7 Ensure correct font size and weights compared to figma (Cody)
- [x] 8 Green checkmark-dots for file uploads are correct size and shade of green (Jojo #1850)
- [x] 9 Text area on "Your Case is Ready to Submit If..." should expand to 700px max width (currently at 68ex) (Natalie #1852)
- [x] 10 Text for Review and Sign - add line height to that checkbox label for 24px and max width of 700px (this is true for any checkbox label that extends to 2 lines so can be a global change) (Natalie #1852)
- [x] 11 Update title to "Tell us about your case" (William #1854)
- [x] 12 Remove Question icon on accordion (William #1854)
- [x] 13 Contacts header margin update (William #1854)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated

**Comment by sarahridgway** [comment]
![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/01287213-73cb-47f9-8ced-756fdf1fe767)

**Comment by klohman** [comment]
- [ ] 14 H1 - change to Start a Case - add 15px margin bottom 
- [ ] 15 Hint - text color should be #1b1b1b 
- [ ] 16 Contact Information fields - are all spanning full width - should have max-width 30rem 
- [ ] 17 Need 30px margin between field sets for Party Type 
- [ ] 18 Text under section headers should have max width-700px
- [ ] 19 ODS file upload field needs to be moved below the helper text
- [ ] 20 Accordion missing question icon (fas.fa-question-circle - #005ea2)
- [ ] 21 “Do I qualify for a small tax case procedure?” - should be sentence case 
- [ ] 22 Table header text in accordion should be 600 (semi-bold)
- [ ] 23 Too much space below text in the small case features boxes 
- [ ] 24 Helper text needs max-width 700px (Select Trial Location)
- Spacing between buttons - 20px

**Comment by klohman** [comment]
- [ ]  Caption in header - the edit button is wrapping 
- [ ] Secondary question radio labels wrapping 
- [ ] ODS - blue container needs to span full width 
- [ ] ODS - paragraph text below header should span 700px
