### ISSUE TITLE
Fix respondent association

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1889]
As an IRS attorney, when I file the first IRS document in a case, I need to be automatically associated with the case.

The IRS is the respondent in every Tax Court case.  After a case is started by a Petitioner, an IRS attorney will file an Answer or a motion in that case.  Upon the filing of the first IRS document in a particular case, the IRS attorney needs to be associated with the case.

## Pre-Conditions:
* A case has been started.
* IRS attorney can find the case by searching for the docket number.

## Acceptance Criteria:
* When an IRS attorney files the first IRS document (see note below), they are immediately associated to the case.
* Once associated with a case, the IRS attorney can see everything in the case
* Before association, the IRS attorney should be able to see documents in a case, but not open/access them.
* Once associated with the case, the IRS attorney's data is viewable to other parties and internal Court Users on the Case Info tab
* Once associated with a case, the case should show up on the IRS attorney's dashboard.
* Once the document is filed it is routed to docket for processing

## Notes:
* First IRS Document: Any IRS practitioner could eFile any document in a case that does not have an IRS practitioner already assigned to it. When the first responsive document is eFiled, if it is being eFiled by multiple counsel for respondent (multiple counsel have signed the document), the eFiler could indicate the other IRS practitioners by entering the Tax Court Bar# for each. Only valid, active, IRS practitioners could be added to the case.
* Kristen & Jessica should talk before any design work is done -- need to make sure we're accounting for association by filing 1st document as well as association by regular means (Entry of Appearance, Substitution of Counsel, etc.)

## Tasks:
- [x] 1 Update respondent dashboard view with side search box (Rachael #2118)
- [x] 2 Add button to file first IRS doc/request access to case to case detail page header; disable linked documents in docket record before respondent is associated with case (Rachael #2119)
- [x] 3 Update fileExternalDoc interactor to associate respondent when they file a document (William #2128)
- [x] 4 Add hardcoded Respondent option to parties filing on file a doc form (Rachael #2124)
- [x] 5 Show different doc type options on request access form based on user role (Rachael #2127)
- [x] 6 Allow multiple respondents to be stored on the case, similar to the way practitioners are stored (William  #2132)
- [x] 7 Refactor caseDetailHelper (Rachael, Kris #2126)
- [x] 8 Fix bottom margin styling on sections on request access form (Rachael #2129)
- [x] 9 Set partyRespondent to true by default for user role respondent on request access form (Rachael #2130)
- [x] 10 Verify that association is checked for respondent to a case (William  #2132)
- [x] 11 Once associated with a case, the case should show up on the IRS attorney's dashboard. (William #2141) 
- [x] 12 Journey tests for respondent filing first doc/requesting access to case (Rachael #2144)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Updated Respondent Dashboard 

* Remove search bar from global header 
* Add search widget (same as Practitioner dashboard)

**Default (No cases)**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bbb9c15b-fd99-45b1-9f7a-6ea090eb83a1)

**Dashboard with Cases**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2929b8d7-88e9-4fe4-8399-d38aed1c0e20)

**Comment by klohman** [comment]
##Case Detail 

Scenario:
* Case has NO respondent counsel associated 

**File First IRS Document button**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc1941b4-ee9d-410e-963b-64ac138492aa)

* Button is displayed ONLY when the case has no respondent counsel associated 
* Button is only visible to IRS Attorney users 
* On click, navigate to the File a Document form 

##File a Document form updates
**Tell Us About the Parties Filing this Document** 

*For ALL users, the Respondent option should be displayed regardless of whether a respondent counsel has been associated with the case 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e9316380-0cf1-425b-9cd0-aeb52cff70ea)

**On Submit of Document**
When the first IRS Counsel file a document in a case:
* Document is visible in the Docket Section Document QC 
* IRS attorney becomes associated with the case as respondent counsel 
* Case is visible on the IRS Attorney's dashboard 
* IRS Attorney information is visible on the Case Detail page/ Case Information tab 
* IRS attorney has full external access to the case information and docket record

**Comment by klohman** [comment]
## Case Detail 

Scenario: 
* Case has a respondent counsel associated 
* Logged in user is NOT the associated respondent counsel for the case 

**Request Access to Case**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/effe64c4-c2c2-4755-8705-422b8f90cf44)

* Display "Request Access to Case" button 
* On click, open "Request Access to Case form 

## Request Access to Case 

**Type of Document**
* For IRS Attorney users, dropdown should include ONLY Entry of Appearance and Substitution of Counsel 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b108ee73-555e-4dce-a1ce-74c5f97e4077)

**Parties You Are Representing**
* This entire section should be hidden for IRS attorney users 
* IRS Attorney user will always be representing the respondent 

**On Submit of Form**
* Document filed is visible in the Docket Section Document QC inbox 
* Case is visible on the IRS Attorney's dashboard
* IRS Attorney information is visible on the Case Detail page/ Case Information tab
* IRS attorney has full external access to the case information and docket record
