### ISSUE TITLE
Petitions Clerk: Direct Scan of Paper filings, preview and associate with case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1895]
As a Petitions Clerk, in order to make sure the right document gets uploaded, I need the ability to scan paper documents directly into the system and review the document before it is associated with a case/docket entry.

The Court will continue to receive paper Petitions.  As a result, Petitions Clerks will need the ability to get those paper documents into the system.  The idea that a clerk would scan, save, and upload the document leaves a lot of room for error that the wrong document will be uploaded.  Plus, it involves multiple steps.  To avoid this, the Petitions Clerks will need the ability to directly scan a document into the system (#1066) and be provided a review feature (#1566) before doc is associated with case/docket entry

## Pre-Conditions:
* Petitions Clerk has paper filing

## Acceptance Criteria:
* we would need to apply a cover sheet
* Petitions Clerk has the ability to scan paper documents directly into the system without having to perform a separate scan, save and upload function.
* The Petitions Clerk can see that the document has been scanned successfully into the system
* Petitions Clerk can preview the content of the document that was uploaded to confirm it's correct
* Petitions Clerk can delete the document if it's incorrect or scanned poorly
* upon submission, scans become associated with the case
* Once associated with the case, the scanned petition is available for the Petitions Clerk to start the QC process. 
* ~ Remove scan button once the scan is complete. we're going to keep this button for now~
* Reduce chances of user accidentally clearing a scan

## Notes:
* ~should we include CLAM AV virus scans for internal users as well? no~
* Some documents require multiple scans (more than 50 pages) to create one document
* Design note 6/10/19 - consider removing scan button once the document has been uploaded

## Tasks:
In Trello: https://trello.com/b/hCZ0JD3v/efcms-one-team

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written (Jojo #2558)

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Cody #2596)
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt #2582, #2592)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt #2631)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Matt)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (JoJo #2630)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt #2600)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt #2594)
 - [x] Code refactored for clarity and to remove any known technical debt (Cody #2596)
 - [x] Deployed to the dev environment

**Comment by sarahridgway** [comment]
## DRAFT Flow / Test Scenarios 

@klohman @ericsorenson 

Set-Up
* Petition clerk logs in
* Navigates to Document QC
* Selects “Create Case”
* Sees “Create Case” page
* Sees file selection utility is open with “Petition” pre-selected

First Use Flow
* Clicks “Select Scanner”
* Sees modal window requesting installation of software
* Clicks “Install”
* [TBD Software installation process]
* [Select Scanner Flow]

Cancel install / close flow
    * Clicks “Cancel” / “Close” button
    * Modal closes without action

Select Scanner Flow
* Sees modal window with list of attached scanners
* Selects a scanner
* Clicks “OK”
* Modal closes
* Sees selected scanner name

Cancel scanner selection / close flow
    * Clicks “Cancel” / “Close” button
    * Modal closes without action

Petition Upload Flow
* Selects “Upload” radio button
* [no change in upload flow]

Petition Scan Flow
* Selects “Scan” radio button
* Loads scanner hopper
* Clicks “Scan” button
* [Hopper begins to scan]
* [TBD interaction with real-time preview or post-scan preview]
* [Hopper completes scan]
* Sees “Batch 1” with page count appear with preview of batch
* [TBD interaction with batch preview navigation]

Hopper is Empty Flow
* [Hopper is empty]
* Sees Modal communicating the hopper is empty
* Loads hopper
* Clicks “Scan”
* [Scan]

	Cancel scan / close flow
    * Clicks “Cancel” / “Close” button
    * Modal closes without action

Add a Batch Flow
* Clicks “Add batch” button
* [Scan]

Preview a Batch Flow
* Clicks “Batch 1”
* Sees Batch 1 preview in preview pane
* Uses navigation to view PDF page-by-page

Rescan a Batch Flow
* Clicks “Rescan”
* Sees Modal window requesting confirmation of action
* Clicks “Yes, rescan”
* [Scan]

	Cancel scan / close flow
    * Clicks “No, cancel” / “Close” button
    * Modal closes without action

Remove a Batch Flow
* Clicks “Remove”
* Sees Modal requesting confirmation of batch removal
* Clicks “Yes, remove”
* Modal closes
* Sees batch has been removed

	Cancel remove / close flow
    * Clicks “No, cancel” / “Close” button
    * Modal closes without action

Scan Another Document Flow
* Has uploaded / generated a PDF document
* Sees list of available documents
* Clicks “Add”
* Sees document tab highlighted
* [Scan flow]

Preview Generated PDF
* Clicks “View PDF” button
* Sees PDF preview appear in preview pane

Complete Case Creation without Errors
* Clicks “Finish” button
* [no change to current flow]

Complete Case Creation with Errors - Metadata
* Clicks “Finish” button
* [no change to error handling for metadata]

Complete Case Creation with Errors - Petition
* Clicks “Finish” button
* Sees error message to indicate petition is required

Cancels Case Creation
* Clicks “Cancel” button
* Sees modal window requesting confirmation of cancel action
* [no change to current flow]

Scanning Error
* Sees Modal communicating scanning error and resolution options
* Clicks “OK”
* Modal closes without action

Unfinished Scans Flow
* [Scanned batches exist for a document but PDF has not been created]
* Clicks on “Add” another document or “Finish”
* Sees Modal communicating that scanning has not been completed yet
* Clicks “OK”
* Modal closes without action

**Comment by klohman** [comment]
## **UPDATED 7/27** Flow / Test Scenarios 

#### Set-Up
* Petition clerk logs in
* Navigates to Document QC
* Selects “Create Case”
* Sees “Create Case” page
* Petition Document tab is selected by default

#### First Use Flow
* Clicks “Select Scanner” or “Add Batch” 
* Sees modal window requesting installation of software
* Clicks “Install”
* [TBD Software installation process]
* [Select Scanner Flow]

#### Cancel install / close flow
* Clicks “Cancel” / “Close” button
* Modal closes without action

#### Select Scanner Flow
* Clicks “Select Scanner” link
* Sees modal window with list of attached scanners
* Selects a scanner
* Clicks “OK”
* Modal closes
* Sees selected scanner name 
* “Select Scanner” link is hidden; “Change” link displays

#### Cancel scanner selection / close flow
* Clicks “Cancel” / “Close” button
* Modal closes without action

#### Petition Upload Flow
* Selects “Upload” radio button
* [no change in upload flow]
* Uploaded PDF displays in full pdf preview window 

#### Add First Batch Flow
* Selects “Scan” radio button
* Loads scanner hopper
* Clicks “Add batch” button
* [Hopper begins to scan]
* [TBD interaction with real-time preview or post-scan preview]
* [Hopper completes scan]
* Sees “Batch 1” under Scanned Documents, including page number and “Rescan” and “Delete” buttons 
* Sees image preview of Batch 1 

#### Hopper is Empty Flow
* Clicks Add Batch with empty hopper 
* Sees Modal communicating the hopper is empty
* Loads hopper
* Clicks “Scan”
* [Scan]

#### Cancel scan / close flow
* Clicks “Cancel” / “Close” button
* Modal closes without action


#### Preview a Batch Flow
* [scan] Batch 1 
* Batch 1 appears under Scanned Document and displays in batch preview
* Click Add Batch
* [scan] Batch 2
* Batch 2 appears under Scanned Documents and displays in batch preview 
* Batch 1 text becomes a link 
* Clicks “Batch 1”
* Sees Batch 1 preview in batch preview
* Batch 1 text link removed (shown as selected) 
* Batch 2 text becomes a link 
* Uses navigation to view PDF page-by-page
* Clicks “Batch 2”
* Sees Batch 1 preview in batch preview
* Uses navigation to view PDF page-by-page

#### Rescan a Batch Flow
* Clicks “Rescan”
* Sees Modal window requesting confirmation of action
* Clicks “Yes, rescan”
* [Scan]
* New scanned batch page count updates under Scanned Documents
* New scanned batch images appear in batch preview 

#### Cancel rescan / close flow
* Clicks “No, cancel” / “Close” button
* Modal closes without action

#### Delete a Batch Flow (multiple batches) 
* Clicks “Delete”
* Sees Modal requesting confirmation of batch removal
* Clicks “Yes, delete”
* Modal closes
* Selected batch is removed from Scanned Documents list 
* Batch order and naming remains persistent 
* Batch preview displays previous batch (if batch 2 was deleted, preview displays batch 1)  
* Previous batch displays as selected 

#### Delete a Batch Flow (single batches) 
* Clicks “Delete”
* Sees Modal requesting confirmation of batch removal
* Clicks “Yes, delete”
* Modal closes
* Selected batch is deleted 
* Scanned documents section is hidden 
* Batch preview is hidden


#### Cancel delete a batch flow / close flow
* Clicks “No, cancel” / “Close” button
* Modal closes without action

#### Create PDF flow 
* [scan} 
* Click Create PDF 
* PDF is generated from scanned images 
* Full PDF preview displays in preview panel 
* PDF is associated with document field and green check displays next to document name in H3 tabs
* “Delete PDF” button displays


#### Scan Another Document Flow
* Click Document tab 
* [Scan flow]

#### Preview Generated PDF
* [ scan] document and [create PDF] for Petition
* Click to another document tab 
* Click on Petition tab 
* Sees full PDF preview in preview panel 
* “Delete PDF” button display

#### Delete PDF 
* [ preview generated pdf]
* Click “Delete PDF“ 
* Confirmation modal displays 
* If yes to confirm, PDF is deleted and document returns to default state [no file attached]
* If no to confirm, modal closes with PDF preview displayed

#### Complete Case Creation without Errors
* Clicks “Create Case” button
* [no change to current flow]

#### Complete Case Creation with Errors - Metadata
* Clicks “Create Case” button
* [no change to error handling for metadata]

#### Complete Case Creation with Errors - Petition is required
* Clicks “Create Case ” button
* Petition tab is selected 
* Sees error message to indicate petition is required

#### Cancels Case Creation
* Clicks “Cancel” button
* Sees modal window requesting confirmation of cancel action
* [no change to current flow]

#### Scanning Error
* Sees Modal communicating scanning error and resolution options
* Clicks “OK”
* Modal closes without action

#### Unfinished Scans Flow 
* Petition PDF has been uploaded or generated
* [Scanned batches exist for a document but PDF has not been created]
* Clicks on “Create Case” 
* Sees Modal communicating that scanning has not been completed yet
* Clicks “OK, discard scans” 
* Modal closes, unfinished scans are deleted 
* [ form is submitted] 

#### Unfinished Scans Flow - no Petition 
* [ Scanned batches for petition but no pdf is created]
* [Scanned batches exist for optional document but PDF has not been created]
* Clicks on “Create Case” 
* Petition tab is selected 
* Sees error message to indicate petition is required

#### Multiple Scan Sessions 
* [ Scan] batch 1 for Petition 
* Select “STIN” tab 
* [Scan] batch 1 for STIN 
* Select RQT tab 
* [scan] batch 1 for RQT 
* Select Petition tab 
* Sees batch 1 for petition under Scanned Documents and petition batch 1 displays in batch preview 
* Select STIN tab 
* Sees batch 1 for STIN under Scanned Documents and STIN batch 1 displays in batch preview 
* Select RQT tab 
* Sees batch 1 for RQT under Scanned Documents and RQT batch 1 displays in batch preview

**Comment by sarahridgway** [comment]
- Hold for documentation -

**Comment by sarahridgway** [comment]
## Common issues with using dynamsoft

The following issues have been noticed while working with dynamsoft scan utility. We should provide support documentation to the court on how to resolve these issues if they reoccur. 

### Product key is empty or invalid

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/b9c70d80-3a81-4f42-9732-fff8b1205f6e)

* Why it happens: Provided the license is current, this issue occurs when the cache on an individual computer does not have a valid key stored
* Resolution: clear the browser cache, reload the page, and try again

### Scanner is not showing up on available scanners list

* Why it happens: the list of available scanners is stored in the browser cache and does not automatically update when a new device has been installed
* Resolution: clear the browser cache, reload the page, and try again. Be sure the scanner is plugged in and turned on after clearing the cache and before reloading the page.

### Scanner appears on available scanners list

* Why it happens: Scanners may use more than one protocol. Each protocol may show up on the list as a separate scanner.
* Resolution: Choose the TWAIN compatible option. Dynamsoft requires TWAIN compatible scanners.

### Selecting the source when scanner has both flat bed and hopper options

* TBD

**Comment by JessicaMarine** [comment]
PO review 8/8/19:
* Green check fails to display by ODS in H3 tabs
* Could not submit case -- got error -- discussed w/ Matt and Cody
