### ISSUE TITLE
Court User: Editing Trial Session details

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1900]
As a Court User, in order to make sure the trial session details are accurate, I need the ability to edit trial session details at any time before the date of the trial session.

## Pre-Conditions:
* A trial session has been created

## Acceptance Criteria:
* Court user can edit and save trial session details at any time before the date of the trial session
* after trial session date has passed, edit and delete functions are unavailable
* Court user can delete trial session at any time before it is automatically scheduled
* Changes should overwrite original details
*  If the Judge assigned to the trial session changes, the Judge associated (#3407) with each case on that trial session should automatically update to the new Judge assigned to the session 

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] create "edit trial session" endpoint (lambda, interactor, proxy) (Rachael #3943)
 - [x] create 'delete trial session' endpoint (lambda, interactor, proxy) (Cody #3944)
 - [x] create sequences to open "trial session edit" view, actual view to edit session, "trial session update" sequence (Rachael #3949)
 - [x] "delete trial session" confirmation modal, delete trial session sequence (Kris #3941)
 - [x] Add edit/delete buttons to view (Kris #3941)
- [x] fix issues on trial session working copy (can't save trial statuses) (Rachael #3949)

### Question:
 - [ ] should edit/delete buttons be concealed in some way AFTER trial session date has passed?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
# Draft Design 

#### Updated Trial Session Details 
* Add "Edit" button 
* Add "Delete Session" button 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e56e9779-b41b-4ea0-bb80-eb8587149f90)

#### Edit Trial Session 
* On click of "Edit", navigate to Edit Trial Session screen 
* Form is populated with inputs from Create Trial session form/ current session details 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f317e62f-f600-4c48-b471-eb738b10d105)


* On Save, navigate to Trial Session Detail screen with success message displayed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1b79e2e8-edfa-4db1-89c0-28c2737db9dc)

### Delete Session 
* on click of Delete Session, display Delete confirmation modal 
* On Yes, Delete, modal closes, session is deleted, and user navigates to Trial Sessions screen

**Comment by klohman** [comment]
### test scenarios #1900 

Create trial session 
- Location : Washington, DC 
- Date : 1/15/20 
- Regular cases 
- Judge Buch 

Create trial session 
- Location: Denver, CO 
- Date 1/15/20
- Regular cases 
- Judge Pugh 
- Set Calendar 

Create Case 
- Case 1 

#### 1) Internal user edits trial session that has not been calendared 
* Login as calendar clerk 
* Navigate to Washington, DC 1/15/20 session 
* Click Edit 
* Change trial start date to 2/10/20 
* Click Save 
Expected results 
On click of Edit 
- [ ] User navigates to Edit Trial Session screen 
On click of Save 
- [ ] User navigates to Trial Session Detail with success message displayed 
- [ ] start date displays as 2/10/20

#### 2) Internal user edits trial session that has been calendared 
* Login as calendar clerk 
* Navigate to Denver, CO session 
* Click Edit 
* Add session note 
* Click Save 
On click of Edit 
- [ ] User navigates to Edit Trial Session screen 
- [ ] Delete button is hidden 
On click of Save 
- [ ] User navigates to Trial Session Detail with success message displayed 
- [ ] Add note displays 

#### 3) Internal user deletes trial session that has not been calendared 
* Scenario 1 
* Click Delete and confirm 
Expected results 
- [ ] Delete button is displayed on Washington, DC Trial Session Detail 
On click of Delete, 
- [ ] Delete confirmation modal displays 
On click of “Yes, Delete” 
- [ ] User navigates back to Trial Sessions screen 
- [ ] Washington, DC session is no longer in trial sessions list 

#### 4) Internal user cannot delete trial session that has been calendared 
* Navigate to Denver, CO session  
Expected results 
- [ ] Delete button is hidden 

#### 5) Internal user edits judge on calendared trial session 
* Login as calendar clerk 
* Navigate to Case 1 
* Add Case 1 to Denver, CO trial session 
* Navigate to Denver, CO session 
* Update judge to Judge Cohen 
* Save 
Expected results
When Case 1 is added to Denver, CO session 
- [ ] Case 1 displays as associated with Judge Pugh 
- [ ] Judge Pugh displays in Case 1 Trial Card 
On Save of trial session updates 
- [ ] Case 1 displays as associated with Judge Cohen 
- [ ] Judge Cohen displays in Case 1 Trial Card

**Comment by JessicaMarine** [comment]
PO Review 12.28.19:
* the edit functionality disappeared once I scheduled the trial session (Birmingham, AL for 2/1/20 -- that should remain until the start date of the session -- only the delete functionality is supposed to disappear upon scheduling
* nothing on DOD is checked off
