### ISSUE TITLE
Closing a Trial Session

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#1912]
As a court, so that we don't have to manually close every trial session, we need the trial session status to change to closed when certain criteria are present. 

## Acceptance Criteria
* A trial session should move from "Open" to "Closed" when the following criteria are present:
        * All cases on the trial session have been moved to inactive

Other AC:
* Add "Ability to filter sessions by All, Closed, Open or New" 
* All and Closed tab also need Session Type, Location and Judge filter
* Reconsider the judge's quick links on their dashboard (Jessica to touch base w/Judges on what's needed) - need to consider trial session calendar screen and how it relates to judges' dashboard.
* Trial sessions that have not been set need to be displayed in a separate tab (New)
* Once the calendar has been set, the trial session moves from New to Open
* Need ability in the New tab to filter by session type and location

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Not related to date
* Minimal logic in router

## Tasks
- [x] 1 Create full set of tabs for open, closed, all, new (Kris, Matt) - #4334
- [x] 2 Create corresponding routes & sequences for each (Kris, Matt) - #4338
~~- [ ] 3 update TrialSession entity STATUS_TYPES (?)~~
- [x] 4 Expose tab-sorting business logic with a simple test / method - #4334
~~- [ ] 5 Update Trial Session status type once calendared~~
- [x] 6 sort Closed and All tabs by newest to oldest (Kris #4346)
- [x] 7 update labels on trial session detail page for new/open/closed (Rachael #4341)
- [x] 8 updated design for judge’s dashboard (Matt #4349)
- [x] 9 update closed session detail page to only show Cases table (Rachael #4341)
- [x] Add status column to ALL sessions table (Matt #4349)
- [x] Fix sorting (set to opposite for each table view) (Matt #4349)

Refactoring: 
- [x] Remove status from trial session entity (verify that this isn't used anywhere else) (Rachael #4348)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt #4359)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Matt #4359)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Design 

**Definitions**
* New Trial Session = trial session that has not been ‘set’
* Open Trial Session = trial session that has been set and contains any “Open” cases independent of date 
* Closed Trial Session = trial session with no “Open cases (all cases are inactive) independent of date

#### Trial Sessions screen 

**New tab**
* Display trial sessions that have not been set 
- Default sort - oldest to newest
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d45db9e5-5d55-40d3-99e8-435d1f0034bb)

**Open tab**
* Display all trial sessions = Open 
* Default sort = oldest to newest 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/226662fe-f543-430c-9bdc-b09d6129a7de)

**Closed tab**
* Display all trial sessions = Closed 
* Default sort = newest to oldest 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/42b761f7-5607-4952-932c-4f69fdcf4717)

**All tab**
* Display all trial sessions = Upcoming, Open, Closed  
* Default sort = newest to oldest 
* Add "Status" column

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a3a0fa3c-7195-41fc-8488-d75cf391766a)

#### Judge's Dashboard 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/993b55d6-d15a-42b6-9e34-d8695a357567)

**Upcoming Sessions**
* Display next 5 open sessions with future dates 
* Display oldest to newest 

**Recent Sessions**
* Display last 5 open sessions with past dates 
* Display oldest to newest 

* View All link - on click, navigate to Trial Session screen, Open tab, pre-filtered by Judge 

#### Trial Session Detail 

**New** 
* If calendar has not been set, label should read "NEW" 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/809aab03-4baf-4025-a0b3-171b37fb9c4e)

**Open**
* If status of session is Open, label should read "OPEN" 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/792b0947-f37c-47ad-bcdd-27c9db847b26)

**Closed**
* If status of session is Closed, label should read "CLOSED" 
* Display single table of cases with label "Cases" 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/31fead2e-c328-4a61-92b2-b00e5f6970de)

**Comment by klohman** [comment]
### 1912 Closing a Trial Session 

Test Data 
* Session 1 
    * Birmingham, AL 
    * 01/26/20
    * Judge Ashford
    * Has open cases 
* Session 2 
    * Washington, DC 
    * 01/16/20
    * Judge Ashford
    * Has open cases 
* Session 3 
    * New York, NY 
    * 01/6/20
    * Judge Ashford
    * Has open cases 
* Session 4
    * San Francisco, CA 
    * 12/30/19
    * Judge Ashford
    * Has open cases 
* Session 5
    * Dallas, TX 
    * 12/17/20
    * Judge Ashford
    * Has open cases 
* Session 6 
    * Baltimore, MD
    * 02/17/20
    * Judge Ashford
    * Has open cases 
* Session 7
    * San Diego, CA
    * 02/25/20
    * Judge Ashford
    * Has open cases 
* Session 8
    * Atlanta, GA
    * 03/16/20
    * Judge Ashford
    * Has open cases 
* Session 9 
    * Chicago, IL
    * 03/24/20
    * Judge Ashford
    * Has open cases 
* Session 10 
    * Columbus, OH 
    * 04/01/20
    * Judge Ashford
    * Not set  
* Session 11 
    * Denver, CO
    * 05/10/20
    * Judge Ashford 
    * Not set 
* Session 12 
    * Miami, FL
    * 05/20/20
    * Judge Ashford 
    * Not set 
* Session 13 
    * Tampa, FL 
    * 01/25/20
    * Judge Ashford 
    * All cases inactive 
* Session 14
    * Boston, MA
    * 01/25/20
    * Judge Ashford 
    * Contains open cases 

#### Scenario 1) New sessions (that have not been calendared) display in New tab, sorted oldest to newest 
* Login as calendar clerk 
* Navigate to Trial sessions > New tab
Expected results 
- [ ] Session 10, 11 and 12 display in New tab 
- [ ] Sessions are sorted oldest to newest 

#### Scenario 2) When a calendar is set for a session and contains open cases, the session displays in the Open tab, sorted oldest to newest 
* Login as calendar clerk 
* Navigate to Trial sessions > New tab 
* Set Calendar for Session 10 (Columbus, OH)
* Navigate to Open tab

Expected results 
- [ ] Before being set, Session 10 displays in New tab
- [ ] After being set, Session 10 displays in Open tab
- [ ] Sessions 1-10 display in Open tab
- [ ] Sessions are sorted oldest to newest 

#### Scenario 3) When all cases in a session are “inactive”, the session displays in the Closed tab, sorted newest to oldest 
* Login as calendar 
* Navigate to Session 14 
* Close all open cases 
* Navigate to Trial Sessions > Closed 
 Expected results 
- [ ] Before cases are closed, Session 14 displays in Open tab 
- [ ] After all cases are closed, Session 14 displays in Closed  
- [ ] Session 13 and 14 display in Closed tab sorted by newest to oldest

#### Scenario 4) New, Open, and Closed sessions display in All tab, sorted newest to oldest 
* Navigate to All tab 

Expected results 
- [ ] Session 1-14 display in All tab 
- [ ] Sessions are sorted newest to oldest 

#### Scenario 4) Users can filter Open sessions by judge, location, and type 
* Scenario 2
* Filter by judge, location, and type  

Expected results 
- [ ] Open tab displays sessions based on selected filter options 

#### Scenario 5) Users can filter Closed sessions by judge, location, and type 
* Scenario 3
* Filter by judge, location, and type  

Expected results 
- [ ] Closed tab displays sessions based on selected filter options 

#### Scenario 6) Users can filter All sessions by judge, location, and type 
* Navigate to All tab 
* Filter by judge, location, and type  

Expected results 
[ ] All tab displays sessions based on selected filter options  

#### Scenario 7) Judge sees next 5 upcoming open sessions on the dashboard, sorted oldest to newest 
* Login as Judge Ashford 
* View dashboard 

Expected results 
- [ ] Sessions 1-5 display under Upcoming Sessions 
- [ ] Sessions are sorted oldest to newest 

#### Scenario 8) Judge sees last 5 past open sessions on the dashboard, sorted oldest to newest 
* Login as Judge Ashford 
* View dashboard 

Expected results 
- [ ] Sessions 6-10 display under Recent Sessions 
- [ ] Sessions are sorted oldest to newest 

#### Scenario 9) Users see New label on session detail screen when a session has not been calendared 
* Login as Judge Ashford 
* Navigate to Session 12 
* View Session Detail screen

Expected results 
- [ ] New label displays in header 

#### Scenario 10) Users see Open label on session detail screen when a session has been calendared and contains open cases 
* Login as Judge Ashford 
* Navigate to Session 1 
* View Judge’s Copy
* Navigate to Session Detail screen

Expected results 
- [ ] Open label displays in header on Judge’s Copy
- [ ] Open label displays in header of Session Detail 

#### Scenario 11) Users see Closed label on session detail screen when a session has no open cases 
* Login as Judge Ashford 
* Navigate to Session 13 
* View Judge’s Copy
* Navigate to Session Detail screen

Expected results 
- [ ] Closed label displays in header on Judge’s Copy
- [ ] Closed label displays in header of Session Detail
