### ISSUE TITLE
Draft state for orders

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1942]
As a Court User, so that I may have someone review my order before it is served on a party, I need the ability to save an in-progress order. 

## Pre-conditions
* Court users have the ability to create an order

## Acceptance Criteria
* Court user can save an in-progress order
* Court user can edit and save changes to an in-progress order
* Any court user can review an in-progress order that was created by another court user (preview PDF)
* Court user can save an in-progress order, return at a later date, continue drafting the order and save again
* Court user can change data that they previously entered in their draft order

* Note - that in the system's current state only a Petitions clerk has the "Create Order" button but this story should not be limited by permissions at all in terms of how it's implemented. All Court users should have the ability to interact with draft states

## Notes
* Need to discuss what to do if user applies a signature to a doc, sees an error, then wants to go back, correct and reapply signature. When does the document become a PDF?
* No version control needed. Only latest version of document should be retained (MVP)
* This story includes creation of draft documents tab, which is the space where signed stip decisions and orders will be held until they are linked to a docket entry and served. 
* Can user see an aggregated list of "in progress" orders or do they have to go back into that case first?
* Can user delete an in progress order?
* Can other users see the drafted order?
* Draft state for orders/decisions don't have work item

## Tasks
 - [x]  Add Draft Documents tab to case detail (Matt #2969)
 - [x] "draft" state on document object (Matt #3004)
 - [x]  Add draftDocuments array on formattedCaseDetail (Cody #2992)
 - [x] Edit Proposed Stip Decision view (Cody #2992)
 - [x] Edit Order / Decision view (Matt #3004)
 - [x] Logic to generate an "edit" link (Cody #2992)
 - [x] Add endpoint for deleting draft documents (Cody #2980)
 - [x] Modal for deleting document (JoJo #2986)
 - [x] ~Filings and Proceedings display in Draft Tab~ (removing per discussion with Kristen)
 - [x] Draft order Document Detail UI (Matt #3011)
- [x] Update success message when order is created 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by sarahridgway** [comment]
Task flow:

Court user creates a document
Document is saved
Document appears in Drafts tab (Case Detail page between Docket Record and Case Info tabs)
From draft tab, user can 
* Preview draft document
* Edit draft document > confirmation modal > success message
* Sign draft document > success message
* Re-sign draft document > confirmation modal > success message
* Delete draft document > confirmation modal > success message
* Serve signed draft document > confirmation modal > success message > document moves to docket record

**Comment by uxforgood** [comment]
### Create order

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/72187800-6714-4104-8df0-a0b66a6c3cee)

- [ ] Update text on button to "Save Order" 

### Case detail page - draft documents tab

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/7eab2ad2-1dfc-4d38-9823-0d168a25a924)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c31778cd-7e76-4171-8240-a52dcb301533)

- [ ] Add Draft Documents tab to the case detail page between Docket Record and Case Info
- Draft docs table should have the following columns: 
    - Date (this is the document was created) 
    - Doc name 
    - Who created the doc (user name) 
    - 2 actions to edit or delete
- Draft docs table should be sorted by Date with oldest on top
- Clicking on doc name takes user to doc detail page (view page, not edit) 
- Clicking on Edit takes user to Edit page
- Clicking on Delete launches "Are you sure?" modal 
- Null state - if there are no draft documents display "There are no draft documents." in semi bold body copy style

### Delete are you sure modal & success message

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/38fc365d-bd9e-4cd9-a9ee-3e9a221a76f1)

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/b596225f-fa10-447e-a482-e5d553e19312)

- If user selects Yes: 
   - Close modal and return to case detail page with draft tab selected
   - Display success message on case detail page that draft was deleted successfully 

- If user selects No: 
   - Close modal and return to previous screen

### Document detail page of a draft Order

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/68899e5e-be86-4b2c-86ea-48cbb57ea7c8)

- [ ] add actions to edit and delete order
- [ ] Add "DRAFT" after the order name
    -  [ ] This DRAFT label should NOT appear attached to the doc name in other places (so not in message table, draft docs table, etc.) 

### Document detail page of a draft Signed stip decision

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/e0a57d90-9b35-41f4-83a1-1bcfb0247ae4)

- [ ] Add "DRAFT" after the order name
    -  [ ] This DRAFT label should NOT appear attached to the doc name in other places (so not in message table, draft docs table, etc.)

**Comment by mariahkannenberg** [comment]
TEST CASES (Draft)
Draft State for Signed Stip Decision
Practitioner or IRS Attorney uploads a proposed stipulated decision
Docket clerk sees proposed stipulated decision in Section Document QC
Docket clerk clicks on proposed stipulated decision, reviews the doc, FORWARDS (“send”) the message to the Sr. Attorney and clicks save, which sends the message to the Sr. Attorney and removes the item from the QC inbox.
Sr. Attorney logs in and sees the Proposed Stipulate Decision message in their message box. 
Route1 - Save and Send:
Sr. Attorney clicks on the proposed stipulated decision, review and signs the doc, crafts a message to the docket clerk (which becomes a new message thread), then clicks “Save and Send,” which closes out the original message thread for the proposed stipulated decision (all users), generates a new signed stipulated decision message.
The signed stipulated decision is saved in draft format and viewable from both the new message thread **and the draft tab on the case detail page.**
Route 2 - Save
Sr. Attorney clicks on proposed stipulated decision, reviews and signs the doc and clicks “Save,” which generates a new signed stipulated decision.
The signed stipulated decision is saved in draft format **and is viewable in the draft tab on the case detail page.**
Docket Clerk navigates to My Messages>Inbox and sees Signed Stipulated Decision message from Sr. Attorney
Docket Clerk select Signed Stipulated Decision and sees the document in draft form
From the draft form Docket Clerk serves the Signed Stipulated Decision
Service of the Signed Stip Decision is recorded in the docket record
Create Draft Orders
Petitions Clerk navigates to case detail page and clicks Create Order
Petitions Clerk creates order and selects Save Order, which **creates a draft of the order**
**Draft Order is viewable from the case detail page draft tab**
Edit a Draft Signed Stipulated Decision
**Court user navigates to case detail page/draft tab**
**Court user selects signed stipulated decision draft**
(Then what? Remove and reapply signature? This is not in the AC. )
Edit a Draft Order (Without Signature)
Court user navigates to case detail page/draft tab
Court user selects draft order and is taken to the Document Detail page for a Draft Order
Court user selects “Edit” edits the order and clicks save
Court confirms that their changes have saved

Edit a Draft Order (With Signature)
Draft order with signature, not yet done.

**Comment by klohman** [comment]
## Updated Test Scenarios 

**Scenario 1 - Petitions clerk saves a draft order** 
- Login as petitions clerk 
- Navigate to Case Detail 
- Click Create Order 
- Select Order of Dismissal and continue
- Enter order text and click “Save Order” 
Expected Results 
- [ ] User navigates back to Case Detail page 
- [ ] Success message is displayed 
- [ ] Order of Dismissal is NOT displayed on the Docket Record 
- [ ] Order of Dismissal is displayed on the Draft Documents tab 
- [ ] “Order of Dismissal” is displayed as a link on the Draft Documents tab
- [ ] Petitions clerk name is displayed under “Created by” in Drafts Document tab
- [ ] Today’s date displays in the Date column in the Drafts Document tab

**Scenario 2 - Petitions clerk can access a draft order from the Drafts Document tab**
- [Scenario 1]
- Click “Edit” link for the Order of Dismissal on the Drafts Documents table 
Expected Results 
- [ ] On click of Edit, user is navigated to “Edit [Order Name]” screen 
- [ ] Original order text is visible in the text editor 
- [ ] Original order text is visible in the Quick Preview 

**Scenario 3: Petitions clerk can save edits to a draft order** 
- [Scenario 2]
- Edit Order text 
- Click “Save Order” 
- Click “Edit” link on the Drafts Document table
Expected Results 
- [ ] On Save, navigate back to Case Detail page
- [ ] On Save, success message is displayed 
- [ ] On Edit, navigates to Edit Order screen with updated order text visible in text editor and Quick Preview 

**Scenario 4: Petitions clerk can access a draft order Document Detail page**
- [Scenario 1]
-Click on “Order of Dismissal” from Drafts Document tab 
Expected Results 
- [ ] Navigates to Document Detail for the draft Order of Dismissal 
- [ ] Document Detail title displays as “[Order Name] - Draft” 
- [ ] Current order text displays in the PDF preview 
- [ ] “Edit” and “delete” options display 

**Scenario 5: Petitions clerk can edit a draft order from the Document Detail page** 
- [Scenario 4] 
- Click on “Edit” link from the Document Detail page 
Expected Results 
- [ ] On click of Edit, user is navigated to “Edit [Order Name]” screen 
- [ ] Original order text is visible in the text editor 
- [ ] Original order text is visible in the Quick Preview 

**Scenario 6: Petitions clerk deletes a draft order from the Draft Document tab** 
- [Scenario 1]
- Click on “Delete” 
- Click on “Yes, Delete” 
Expected Results  
- [ ] On “Delete”, confirmation modal displays 
On click of “yes, Delete”: 
- [ ] confirmation modal closes
- [ ] draft order is removed from Draft Document table
- [ ] Success message displays 

**Scenario 7: Petitions clerk deletes a draft order from the Document Detail page**
- [Scenario 1] 
- Click on the “Order of Dismissal” link
- Click on “Delete” 
- Click on “Yes, Delete” 
- Navigate to Case Detail page > Draft Documents tab
Expected Results 
- [ ] On click of Order of Dismissal, navigates to Document Detail page 
- [ ] On “Delete”, confirmation modal displays 
On click of “yes, Delete”
- [ ] confirmation modal closes
- [ ] System navigates back to Case Detail page 
- [ ] Success message is displayed 
- [ ] Draft order is removed from Draft Document table

**Scenario 8: Petition clerk views blank state on Draft Documents tab when there are no draft documents** 
- [Scenario 8]
- Navigate to Draft Documents tab
Expected Results 
- [ ] No draft orders are displayed 
- [ ] Message : “There are no draft documents” displays

**Comment by mariahkannenberg** [comment]
On 9/9, team decided to split this story into two - draft orders and draft signed stip decision. 

All AC related to stip decisions were added to #3010
