### ISSUE TITLE
Printable PDF of calendar/trial session list

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#1976]
As a court user, so that I may work offline, I need the ability to print a PDF view of the calendar/trial session list. 

## Pre-Conditions
Calendar/trial session list exists in the system.

## Acceptance Criteria
* Court user can generate a printable / downloadable PDF of the calendar/trial session list with related session details
* Printed version of the calendar/trial session list is designed to print on 8.5.x11 paper
* Related session details include: 
   * City/State of Trial Session
   * Term
   * Session Type (Regular, Small, Hybrid, Special, Motion/Hearing)
   * Assignments -- Judge, Trial Clerk, Court Reporter, IRS Calendar Administrator
   * Courthouse Location
   * Notes
* List of cases should only include open cases by default sort order (oldest to newest by case filing date)
* Any internal user can print from within the trial session detail page (not the Judge's working copy)
* Subsequent pages should include page numbers, trial session info (city/session start date)

## Notes
* Date of print should be captured somewhere on the document #2698 
* No mobile capability needed
* Possible design - only show print button after trial session has been "Set" -- no need to print eligible case list
* Page header for all but first page shall include document title / detail in the top left and page number / count [format: Page 2 of 3] in the top right. Other PDFs, such as the Docket Record, shall match this header. Orders shall match format but not in typeface / size.

## Tasks

- [x] a) UX Design complete and documented (Sarah - done)
- [x] 1) front end
  - [x] 2) add button to session list for print called "print trail calendar" (cody #2757)
  - [x] 3) create a new page for viewing the printable trial session (similar to PrintableDocketRecord)  (cody #2757)
  - [x] 4) create sequence for print trail calendar  (cody #2757)
  - [x] 5) add a route for this print view which runs the sequence  (cody #2757)
  - [x] 6) create action used for creating the PDF html (follow printDocketRecordAction example) (Cody & Joe #2775)

- [x] 7) backend work (used already-existing endpoint from printable docket record)
  - [ ] ~8) create UI proxy for interactor~
  - [ ] ~9) add serverless endpoint in api (copy generateDocketRecordPdfLambda & other stuff related)~
  - [ ] ~10) create lambda~
  - [ ] ~11) create interactor for generating the pdf from html~

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo #2817)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo #2817)
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
All of the highlighted information should be displayed in some manner on the printable PDF:
![image](https://user-images.githubusercontent.com/40871081/62574586-d9b1e480-b866-11e9-97a0-1b3a5ad15356.png)

**Comment by sarahridgway** [comment]
## Trial Calendar PDF

### First Page

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/e8942471-7d65-421f-b1eb-60bccabf98fb)

### Subsequent Pages

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/aae413b5-db9d-40c2-8100-b5a7fa196ce1)

**Comment by sarahridgway** [comment]
Test Scenario

- Docket Clerk logs in
- Sees dashboard / inbox
- Navigates to Trial Sessions section
- Sees list of Trial sessions
- Clicks on a Trial Session
- Sees Trial Session detail page
- Clicks Printable Trial Calendar link
- Sees Printable Trial Calendar page appear with trial calendar PDF in viewer

**Comment by JessicaMarine** [comment]
PO review 8/20/19:
* The margin at the bottom of the page -- i think it needs to be set to something to prevent the text from getting that close to the edge of the page.
