### ISSUE TITLE
UX - Random Design Updates

### ISSUE THREAD

**Issue by uxforgood** [flexion/ef-cms#2101]
Random Design Updates

## Acceptance Criteria

**Form Field Updates**
- [ ] Decrease width of Zip Code field 
- [ ] On Doc detail Doc Info tab, the state field should right align with the rest of the boxes

**Browser**
* ~~Consider adding helper text on browser-level message re: file size too big~~ (Removed, edge case) 
* Page title does not include docket number or document name. Unhelpful browsing history. See image in comments (SLR).
 ![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/840a4e89-8648-49ac-94ad-819fd64360cb)

**Navigation**
- [ ]  Mobile view on global navigation -- menu should auto-close upon selection; ~~search icon should be next to search bar~~
- [ ] Tab state - should always reset to default tab on page load 

**External Parties Case Detail View**
- [ ] Remove / replace? the Petition Details card on Case Info tab for external users (petitioner, specifically) 

**Tables**
- [ ] Need empty state for all tables (see comment for text)
- [ ] Table row heights should be min 50 (currently 65)
- [ ] Update Filed By entries in Docket record (Petition shows as [Petitioner name]; subsequent entries show as [Petr. Petitioner's name]

**Hover States**
- [ ] Add hover state for page navigation on preview scanned pages and preview selected document during review modals

**Keyboard Navigation**
- [ ] bring back the focus styles for the tabs component throughout the application

Feedback to User
- [ ] add some kind of messaging/behavior after practitioner updates contact info to inform them it may take a while

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
~- [ ] 1 Decrease width of zip code field; this has been corrected on some forms and not others; size on File a Petition for external users is correct~ looks like this has already been taken care of
- [x] 2 On Doc detail Doc Info tab, the state field should right align with the rest of the boxes (Rachael #3215)
- [x] 3 Add docket number and/or document name to page title where appropriate (Rachael #3219)
- [x] 4 Mobile view on global navigation -- menu should auto-close upon selection (Rachael #3222)
- [x] 5 Tab state - should always reset to default tab on page load (throughout the app) (Kris / William #3224)
- [x] 6 Remove the Petition Details card on Case Info tab for all external users (see design in comments below) (Rachael #3215)
- [x] 7 Table updates
  - [x] 7a Need empty state for all tables (see comment for text); some of these have been done, but double check them; they should all be body copy instead of h2/h3 (William #3227 #3229)
  - [x] 7b Table row heights should be min 50 (currently 65) (Kristen #2808)
  - [x] 7c Update Filed By entries in Docket record (Petition shows as [Petitioner name]; subsequent entries show as [Petr. Petitioner's name]) - always use "Petr." before name (Rachael #3225)
- [x] 8 Add hover state for prev/next buttons on scan preview pane (create case from paper) - same color as hover state on primary button (Rachael #3215)
- [x] 9 Bring back the focus styles for the tabs component throughout the application (William #3223)
- [x] 10 Add some kind of messaging/behavior after practitioner updates contact info to inform them it may take a while - see design in comments below (Rachael #3215)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by sarahridgway** [comment]
- [ ] Consider adding filing time in ET to filed date on petitioner and practitioner case list (+other views?) so it is clear for filers east of ET that their filings were received by the court on ET. Use ET instead of EST or EDT so we don't have to make it dynamic.

Example: Filer in GMT submits filing at 4am 06/14 local time, which is received by the court at 11pm ET on 6/13. Case list shows filing date as 06/13 which could be confusing for the GMT filer.

**Comment by uxforgood** [comment]
- [ ] Revisit sentence/title case for field labels since most of ours are ending up being questions (which are sentence case)

**Comment by uxforgood** [comment]
Consider adding wayfinding when a user goes from a trial session page to a case detail page so they can easily get back to the trial session page

**Comment by klohman** [comment]
Completed tasks 
- [x] Change Onstate of global nav text to #1b1b1b to match H1 tabs (Kristen #2687)
- [x] Look into State dropdown - currently sized for state abbreviations but showing full state name and getting cut off
- [x] Normalize heading sizes and treatments (H1 now looks like it has extra space on some forms - need to be consistent) (Kristen #2687)  
- [x] Add padding below tabs (descenders running into tab underline)(Kristen #2687)


No Longer Relevant 
~~- [ ] On Case Info tab, add right gutter between columns of information so there is a space between columns~~

**Comment by uxforgood** [comment]
- [ ] add some kind of messaging/behavior after practitioner updates contact info to inform them it may take a while 

- [ ] revisit design/behavior of "in progress/done" indicator for uploading documents/filing petition

**Comment by klohman** [comment]
### 2102 Design 

#### Empty table states 

**Styling** - body copy 

* Messages (Individual) Inbox - done 
* Messages (Individual) Sent - done 
* Messages (Section) Inbox  
* Messages (Section) Sent   
* My Document QC - Inbox - “There are no documents”
* My Document QC - In Progress - “There are no documents”
* My Document QC - Processed - “There are no documents”
* Section Document QC - Inbox - “There are no documents”
* Section Document QC - In Progress - “There are no documents”
* Section Document QC - Processed - “There are no documents”
* My Document QC - Batched for IRS- “There are no documents”
* My Document QC - Served - “There are no documents”
* Section Document QC - Batched for IRS - “There are no documents”
* Section Document QC - Served - “There are no documents”
* Trial Sessions - Upcoming - “There are no trial sessions”
* Trial Session Detail - Open Cases - “There are no open cases”
* Trial Session Detail - Closed Cases - “There are no closed cases”
* Trial Session Detail - All Cases - “There are no cases”
* Trial Session Detail - Eligible Cases - “There are no eligible cases”
* Reports > Deadlines - “There are no deadlines for the selected date(s)”
* Case Detail > Deadlines “There are no deadlines for this case.” - DONE 
* Case Detail - Messages in Progress - “There are no messages.” 
* Case Detail - Draft Documents - “There are no draft documents.”
* Dashboard (Judge) - Recent Messages - “There are no messages.”

**Comment by klohman** [comment]
### 2101 Test Scenarios 

#### 1) User selects option from global navigation on mobile 
* Login as petitioner on mobile device 
* Select File a Petition 
* Select global nav menu 
* Select My Cases 
Expected Results 
- [ ] Navigation window closes on select of My Cases 
- [ ] App navigates to My Cases (Petitioner Dashboard) 

#### 2) User always sees Docket Record tab on Case Detail as the default on load 
* Login as docketclerk1 
* Navigate to case 123-19
* Click on Case Information 
* Navigate to case 124-19
Expected results 
- [ ] Docket Record is default tab for case 123-19
- [ ] Docket Record is default tab for case 124-19

#### 3) User always sees Inbox tab on Messages (Individual and Section) as the default on load 
* Login as docketclerk1
* Click on Sent tab 
* Click on “Switch to Section Messages” 
* Click on “Switch to My Messages” 
Expected results 
- [ ] Inbox is default tab on My Messages 
- [ ] Inbox is default tab on Section Messages 

#### 4) Docket Clerk User always sees Inbox tab on Document QC (Individual and Section) as the default on load 
* Login as docketclerk1
* Click on Processed tab 
* Click on “Switch to Section Document QC” 
* Click on “Switch to My Document QC” 
Expected results 
- [ ] Inbox is default tab on My Document QC 
- [ ] Inbox is default tab on Section Document QC 

#### 5) Petition Clerk User always sees Inbox tab on Document QC (Individual and Section) as the default on load 
* Login as petitionsclerk1
* Click on Batched for IRS tab 
* Click on “Switch to Section Document QC” 
* Click on “Switch to My Document QC” 
Expected results 
- [ ] Inbox is default tab on My Document QC 
- [ ] Inbox is default tab on Section Document QC 

#### 6) User always sees “Document Info” and “Parties” tabs on Petition QC as the default on load 
* Login as petitionsclerk1
* Go to Section Document QC and click on  a new Petition XX1-19
* Click on Case Info tab under Document Info 
* Click on “Messages” tab on Petition QC form 
* Go to Section Document QC and click on a different new Petition XX2-19
Expected results 
- [ ] on load of Petition QC page for XX1-19, Document Info tab is selected as default 
- [ ] on load of Petition QC page for XX1-19, Parties tab is selected as default 
- [ ] on load of Petition QC page for XX2-19, Document Info tab is selected as default 
- [ ] on load of Petition QC page for XX2-19, Parties tab is selected as default 


#### 7) User always sees “Messages” and “In Progress” tabs on Document Detail as the default on load 
* Login as docket clerk1
* Go to Document QC and select a filing (filing 1)
* Click on Completed under the Messages tab 
* Go to Document QC and select a different filing (filing 2)
Expected results 
- [ ] on load of Document Detail page for filing 1, Messages> In Progress is selected as default
- [ ] on load of Document Detail page for filing 2, Messages> In Progress is selected as default


#### 8) User always sees “Open Cases” tab on Trial Session Detail as the default on load 
* Login as docket clerk1
* Navigate to Trial Sessions 
* Select trial session [ trial location 1]
* Click on Closed Cases tab 
* Navigate to Trial Sessions 
* Select trial session [ trial location 2]
Expected results 
- [ ] on load of Trial Session detail  [trial location 1], Open Cases is selected as default tab
- [ ] on load of Trial Session detail  [trial location 2], Open Cases is selected as default tab

#### 9) External user does not see Petition Details on the Case Detail screen 
* Login as petitioner 
* Select [case xxx-19]
* Click on Case Information tab 
Expected results 
- [ ] Petition detail card is hidden 


#### 10) User sees empty state message for all blank tables 
* (See empty table state messaging)
- [ ] Confirm all tables have correct empty state messaging 

#### 11) User sees “Filed By” entries as “Petr. Petitioner Name” on all documents filed by petitioner 
* Login as petitioner2
* File a new petition 
* File a document [document 2]
* Navigate to Docket Record 
Expected results 
- [ ] Petition entry shows Filed by as “Petr. Petitioner Name”
- [ ] Document [document 2] entry shows Filed by as “Petr. Petitioner Name”


#### 12) User sees hover state on page navigation on Review Document modals 
* Login as petitioner 
* Complete steps 1-4 on petition form 
* Preview petition pdf from review screen and page through document
* Submit petition
* Click on File a Document
*  Preview document pdf from review screen and page through document
Expected results 
- [ ] Hover state is displayed on page navigation on review filing modals  

#### 13) Practitioner user sees success message after updating their contact information 
* Login as practitioner 
* Click “edit” under My Contact Information 
* Update address and click Save 
Expected results 
- [ ] App navigates to Dashboard with success message displayed

**Comment by klohman** [comment]
## UX Comments 

* On mobile, navigation menu is not closing when selecting the current screen 

* Empty state for "Draft Documents" needs to be in body copy
