### ISSUE TITLE
Petitioner: Edit email address

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2223]
As a Petitioner, in order to keep my contact information current with the Court and continue to receive service emails, I need the ability to update my email address.

Related to #7406: Edit Practitioner's email

## Pre-Conditions: ##
* Petitioner exists in DAWSON with an email address

## Acceptance Criteria:
* Petitioner has the ability to edit his/her email address
* Petitioner is provided new credentials to access DAWSON with the new email address [See note below]
* When the email has changed, the petitioner is required to verify their new email address. 
* Petitioner is able to log-in and access their cases
   * Ensure that the petitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
   * Petitioner can eFile documents in cases
* Petitioner's service preference remains as electronic
* Petitioner receives service emails at the new service email address
* ~~Change generates a Notice of Change of Email Address (create as own user story)~~
* When user updates their email address, it updates in all the cases they're in. [Note: need to change the edit info from case level to account level]

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider whether we have to create and link a new Cognito account or whether Cognito may allow an admin to just change email address
* Consider having ability to edit info at a more global level
* We can customize the email user receives to verify their address.
https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/signing-up-users-in-your-app.html#verifying-when-users-change-their-email-or-phone-number

## Tasks
- [x] 1 Add My Account to menu dropdown for petitioners - Team mob #7710
- [x] 2 Create My Account view for petitioners (probably reuse the one for practitioners) - Team mob #7710
- [x] 3 Create Change Login & Service Email Address for petitioners (probably reuse the one for practitioners)  Team mob #7712
- [x] 4 Add permissions in all interactors related to updating email for petitioners - Team mob  Team mob #7712
- [x] 5 Display success message after submitting email change 
- [x] 6 Display pending email warning in header for petitioner
- [x] 7 Updates to Change Login & Service Email page - add Pending email address section if the user has already attempted to update their email - Team mob #7713
- [x] 8 After email verification, use same behavior as practitioner flow - go to success page or instruction page depending on if user is logged in - Team mob #7713
- [x] 9 Update email address in all cases for a petitioner when updating their email address - Team mob #7713

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Petitioner Dashboard 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c19f14fc-13dd-4518-9a31-71508b3529e7)

#### Email Address Card 
* Display user  email address
* Display Edit link 

**On click of Edit**
* App routes to Edit Email screen 


## Edit Email Information
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/38e24752-089c-4563-91ac-e28a05dd7e76)

**Email Address field**
* is populated with current user email 

**On Save**
* If email has been updated, display confirmation modal 


## Confirm email update modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6db3b68c-d207-449e-bf3a-e90d41147384)

* display Re-Enter email address field 
* Field is requried 
* Field value must equal the email address field 

**On click of Cancel**
* Modal closes and remains on Edit screen 

**On click of Continue**

* Validate email 
      - if errors occur, display error message on email field
   
        - Check if re-enter email field equals email address field - “Email addresses do not match.” 
        - check for valid email format - Error message : “Enter a valid email address” 
        - check for duplicate email in Cognito - Error message: “An account with this email already exists. Enter a new email address.”

 *  Run Cognito workflow (TBD) 
 *  App routes to Dashboard with success message displayed  “Email updated” 
 *  updated email displays in Email Address card 
 * petitioner will recieve service at updated email address

**Comment by klohman** [comment]
### 2223 Test Scenarios 

#### 1) Petitioner sees email on dashboard 
* Login as petitioner 
    * flexionustc+petitioner@gmail.com
Expected results 
- [ ] Email Address card displays on dashboard 
- [ ] Email address displays as “flexonustc+petitioner@gmail.com”


#### 2) Petitioner updates email and saves form with valid email address 
* Login as petitioner 
* Click Edit on Email Address 
* Update email address 
    * flexionustc+petitionerupdated@gmail.com
* Click Save 
* Re-enter matching email 
* Click Continue on modal 
Expected results 
On click of Save 
- [ ] Confirmation modal displays 
On click of Continue 
- [ ] App routes to Dashboard with success message displayed “Email saved.” 
- [ ] Email address card displays updated email 
- [ ] All Open and Closed cases associated with petitioner display on the dashboard 

#### 3) Petitioner updates email and saves form with invalid email address 
* Login as petitioner 
* Click Edit on Email Address card
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field - “Enter a valid email address” 

#### 4) Petitioner updates email and saves form with duplicate email address 
* Login as petitioner
* Click Edit on Email address card 
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 5) Petitioner updates email and files a document 
* Scenario 2
* Go to case 
* File a Motion for New Trial 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address receives service email - flexionustc+petitionerupdated@gmail.com
- [ ] Old email does not receive service email - flexionustc+petitioner@gmail.com

#### 6) Petitioner updates email and cannot login with old email address
* Scenario 2 
* Login as petitioner - flexionustc+petitioner@gmail.com

Expected results 
- [ ] User sees error on login for invalid credentials 

#### 7) Petitioner updates email and logs in with new email 
* Scenario 2 
* Login as petitioner 
    * flexionustc+petitionerupdated@gmail.com
Expected results 
- [ ] Login is successful 
- [ ] App displays Petitioner dashboard with all associated cases 
- [ ] Updated email is displayed in Email Address card

#### 8) Petitioner updates email and receives service for court-issued document 
* Scenario 2
* Login as docket clerk 
* Go to case 
    * Case has petitioner - flexionustc+petitionerupdated@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address receives service email 
    - flexionustc+petitionerupdated@gmail.com
- [ ] Old email does not receive service email 
    * flexionustc+petitioner@gmail.com

#### 9) Petitioner updates email and enters non-matching email on confirmation 
* Login as petitioner  
* Click Edit on Email Address card 
* Update email address = firstemail@email.com
* Click Save 
* Re-enter non-matching email = secondemail@email.com
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field -  “Email addresses do not match.”

**Comment by klohman** [comment]
## Petitioner Dashboard 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1216278e-aafe-4c72-bc42-726d4b08d88b)

**Login &Service Email card**
* display current email 
* Display Change Email link 

#### On click of Change Email
* navigate to Change Email 


## Change Login & Contact Email Address 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6ba39d13-32de-4800-bdc1-b95d3132eab8)

**Current email address**
* display current email in read-only format 

#### Change Login & Contact Email 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display verify email modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* Old email is still valid
* New email is not yet valid 


## Verify Email Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2583b7aa-1fb8-4f07-80be-370616679531)

* On click of OK, route to dashboard with success message 


## Dashboard - Email verification required 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a577205b-78f9-42e9-8aa7-829944f462e9)

* app routes back to Dashboard with success message displayed

* display warning message under page header globally 

* old email still displays under My Contact Information 



## Change Login & Contact Email Address  with pending email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a695b0fb-fc0e-45ec-a329-1eac959eeedc)

* Display warning message 

**Current email**
* display current (old) email in read-only format 

**Pending email**
* display new email in read-only format 

#### Change Login & Contact Email
* same functionality as before 


## User clicks Verify Email link while logged in 

* Route to Email Verified Success screen
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1d55a31b-a9af-4dce-8e0f-b3e4d1abcb36)

* old email is now invalid; user cannot log in with old email; service emails do not go to old email 
* new email is valid and user can log in with new email; service emails now go to new email 
* New email displays in UI on dashboard and in all cases

**Comment by klohman** [comment]
## 2223 Test Scenarios 


#### 1) Petitioner updates email and saves form with valid email address 
* Login as practitioner - flexionustc+petitioner@gmail.com
* Update email address - flexionustc+petitionerupdated@gmail.com
* Click Save 
* Click OK
Expected results 
On click of Save 
- [ ] Verify email modal displays 
- [ ] On click of OK on modal, App routes to Dashboard with success message displayed “New email has been added and is awaiting verification.”
- [ ] Verification email is sent to new email 
- [ ] Old email is still valid 
- [ ] old email still displays under My Contact Information 
- [ ] old email still displays under all cases
- [ ] Global warning message displays 

#### 2) Petitioner updates email and saves form with invalid email address 
* Login as petitioner
* Click Change Email link on dashboard
* Update email address = notvalid@
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [ ] Error displays on email field - “Enter a valid email address” 

#### 3) Petitioner updates email and saves form with duplicate email address 
* Login as petitioner
* Click Change Email
* Update email address = petitioner1@example.com
* Re-enter matching email = petitioner1@example.com
* Click Save
Expected results 
- [ ] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Petitioner updates email files a document before verifying new email 
* Login as petitioner - flexionustc+petitioner2@gmail.com
* Click Change Email
* Update email address - flexionustc+petitionerupdated2@gmail.com
* Go to case 
* File a Motion for New Trial 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address does not receives service email 
- [ ] Old email does receives service email 

#### 5) Petitioner updates email and cannot login with new email address before verifying email
* Scenario 4 
* Login as petitioner with new email 
    * flexionustc+petitionerupdated2@gmail.com
Expected results 
- [ ] User sees error on login for invalid credentials 

#### 6) Petitioner updates email and can login with old email address before verifying new email
* Scenario 4 
* Login as petitioner with old email 
    * flexionustc+petitioner2@gmail.com
Expected results 
- [ ] User is able to login 
- [ ] Global warning to verify email is displayed 
- [ ] Old email displays under contact info on dashboard and in all cases

#### 7) Petitioner updates email and receives service for court-issued document at old email before verifying new email 
* Scenario 4 
* Login as docket clerk 
* Go to case 
    * Case has petitioner - flexionustc+petitioner2@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [ ] order to show cause is added to Docket Record 
- [ ] New email address does not receive service email 
    - flexionustc+petitionerupdated2@gmail.com
- [ ] Old email receives service email 
    * flexionustc+petitioner2@gmail.com

#### 8) Petitioner updates email and enters non-matching email on confirmation 
* Login as petitioner
* Click Change Email
* Update email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save 
Expected results 
- [ ] Error displays on email field -  “Email addresses do not match.”

#### 9) Petitioner verifies new email and logs in with new email 
* Scenario 4 
* Go to gmail 
* Click Verify Email link 
* Click login on success page
* Login as petitioner
    * flexionustc+petitionerupdated2@gmail.com
Expected results 
On click of verification link:
- [ ] User is routed to Email Verified success page 
On login: 
- [ ] Login is successful 
- [ ] App displays new email on dashboard with all associated cases 
- [ ] Global warning message is not displayed

#### 10) Petitioner verifies new email and files a document 
* Scenario 9 
* Go to case
* File a Document 
    * Administrative Record 
* Submit document
Expected results 
- [ ] Administrative Record is added to the docket record 
- [ ] new email receives service email 
- [ ] Old email does not receive service email 

#### 11) Practitioner verifies new email and receives service email for court-issued document 
* Scenario 9 
* Login as docket clerk 
* Go to case 
    * Case has petitioner - flexionustc+petitionerupdated2@gmail.com
* Create, sign and serve Decision 
Expected results 
- [ ] Decision is added to the docket record 
- [ ] new email receives service email 
- [ ] Old email does not receive service email 

#### 12) Petitioner verifies new email and cannot log in with old email 
* Scenario 9 
* Login to system with old email - flexionustcpetitioner2@gmail.com
Expected results 
- [ ] Login is unsuccessful and error message is displayed

**Comment by JessicaMarine** [comment]
Closing -- after retesting with a new case and a document qc item (that wasn't messed up on Flexion's prod via the deploy mishap regarding 7673), we were unable to replicate 7672, and it seems that since this isn't on the court's environment, it's related to 7673 as initially assumed. should 7672 be closed since its problem is the same as 7673?
