### ISSUE TITLE
Docket Clerk: Ability to Manually change case status 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2377]
As a Docket Clerk, so that I may have the flexibility to change a case status, I need the ability to manually change a case status that has already been set. 

## Pre-Conditions
* A case exists in the system and has a case status.
* Complete #3407 -- add Judge association to each case

## Acceptance Criteria
* Docket Clerk can manually change the status of the case [Note: this should be role based; Docket Clerks only]
* When status of case is changed, all logic tied to a system-generated status is applied to the manually generated status.
* Case must always have a case status

## Notes
* Since we don't have time to program automated case statuses for every document, we're allowing user to change manually. 
* A case always has a case status based on Court-defined rules. (#1594) See https://docs.google.com/document/d/1qhxASEKuzcPp99rTfCVkYbi6hVKS1pPPIgn5MvEWFPM/edit?usp=sharing
* Once a status is manually changed, all other actions follow the same logic
* In addition to case status, each case should also have a Judge associated with it at all times -- to be handled in a different story (#3407)

## Tasks
- [x] 1 Update case detail page - move Create Order button, add Edit Case button, remove Edit link next to case caption (Rachael #3515)
- [x] 2 Modify Edit Case Caption modal to be the new Edit Case modal (Team mob #3521)
  - [x] 2a Update validation, submit sequences for modal (Team mob #3521)
- [x] 3 Create endpoint for submitting the modal - edit case? manually edit case? change case status? (serverless, lambda, interactor, proxy, persistence if needed) (Team mob #3521)
- [x] 4 Add new case statuses to Case entity (Cody #3514)
- [x] 5 Validation for Edit Case modal (Rachael, Matt #3529)
- [x] 6 Show associated judge dropdown in Edit Case modal for certain statuses, and update associated judge on the case when needed (Team mob #3524)
- [x] 7 Show alert on the modal when the case status is currently Calendared (Matt #3526)
- [x] 8 Filter case status options in the modal - some should not be shown (see comments below) (Rachael, Matt #3529)
- [x] 9 The current status of the case should be selected in the dropdown when the modal opens (Team mob #3524)
- [x] 10 Show success message after modal is submitted and closed (Rachael, Matt #3529)
- [x] 11 Restrict interactors to only docket clerks/clerk of court and hide Edit button for all other users (Rachael #3533)
- [x] 12 Integration test (Rachael #3535)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by klohman** [comment]
### Updates to Case Detail Page  
* internal view of Case Detail page only 
* Move "Create Order button" to Draft Documents tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cfab3be4-e93c-469d-81de-035b732057bc)

* Add "Edit Case" button to docket header 
* Remove "Edit" link next to case caption

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b1dcaf68-77b8-450d-9aec-85ed719c3398)

* On click of "Edit Case" button, display Edit Case Modal 

### Edit Case Modal 

* Modal includes case caption field (current functionality) 

**"Case status" field**
* Dropdown defaults to the current case status 
* Dropdown is required 
* Dropdown includes all case statuses EXCEPT "Calendared" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e94d9432-dcac-44dc-a364-875854b59cc3)


**Associated Judge**
* Field is shown when these case statuses are selected: 
   * Submitted 
   * CAV 
   * Rule 155
   * Jurisdiction Retained 
   * Assigned - Case 
   * Assigned - Motion
* Field is required when shown 
* Dropdown is defaulted to the current associated judge
* Dropdown includes all judge users AND a Chief Judge option 

* Field is hidden when these statuses are selected and the associated judge is automatically selected by system depending on the selected case status 
    * New - Chief Judge is selected 
    * Batched for IRS  - Chief Judge is selected 
    * Recalled - Chief Judge is selected 
    * General Docket -Not At Issue - Chief Judge is selected 
    * General Docket - At Issue (Ready for Trial) - Chief Judge is selected 
    * Closed - Current judge assigned is selected  
   * On Appeal - Current judge assigned is selected  

**Calendared cases**
* When case status is updated to Calendared, the trial session judge is automatically selected as the associated judge 

**On click of Save button**
* modal closes 
* changes are displayed in header 
* success message displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/125194c2-5b42-442d-b8ea-4a9515f7faf1)

**Comment by klohman** [comment]
### 2377 Test Scenarios

#### 1) Docket clerk sees Edit Case option 
- Login as docket clerk 
- Navigate to case detail page 
Expected results 
- [ ] Edit Case button displays in docket header 

#### 2) Internal user (not docket clerk) does not see Edit Case option
- Login as petitions clerk 
- Navigate to case detail page 
Expected results 
- [ ] Edit Case button does not display in docket header 


#### 3) Docket clerk changes case status to General Docket - Not At Issue 
- Scenario 1
- Click Edit Case button
- Select General Docket - not At Issue” from Case status dropdown 
- Save 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “General Docket - not At Issue” 
- [ ] Associated judge displayed as “Chief Judge” 


#### 4) Docket clerk changes case status to General Docket - At Issue (Ready for Trial)
- Scenario 1
- Click Edit Case button
- Select General Docket - At Issue (Ready for Trial)” from Case status dropdown 
- Save 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “General Docket - At Issue (Ready for Trial)” 
[ ] Associated judge displayed as “Chief Judge”  

#### 5) Docket clerk changes case status to Submitted 
- Scenario 1
- Click Edit case button 
- Select Submitted as case status 
- Select Judge Buch as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Submitted” 
- [ ] Associated judge displayed as “Judge Buch”  

#### 6) Docket clerk changes case status to CAV 
- Scenario 1 
- Click Edit case button 
- Select CAV as case status 
- Select Judge Cohen as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “CAV” 
- [ ] Associated judge displayed as “Judge Cohen”  

#### 7) Docket clerk changes case status to Rule 155
- Scenario 1
- Click Edit case button 
- Select Rule 155 as case status 
- Select Judge Urda as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Rule 155” 
- [ ] Associated judge displayed as “Judge Urda”  

#### 8) Docket clerk changes case status to Jurisdiction Retained 
- Scenario 1
- Click Edit case button 
- Select Jurisdiction Retained as case status 
- Select Judge Pugh as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Jurisdiction Retained” 
- [ ] Associated judge displayed as “Judge Pugh”  

#### 9) Docket clerk changes case status to Assigned-Case
- Scenario 1
- Click Edit case button 
- Select Assigned - Case as case status 
- Select Judge Gustafson as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Assigned- Case” 
- [ ] Associated judge displayed as “Judge Gustafson”  

#### 10) Docket clerk changes case status to Assigned-Motion
- Scenario 1
- Click Edit case button 
- Select Assigned - motion as case status 
- Select Judge Foley as associated judge 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Assigned - Motion” 
- [ ] Associated judge displayed as “Judge Foley”  

#### 11) Docket clerk changes case status to Closed 
- Scenario 10 
- Click Edit case button 
- Select Closed as case status 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “Closed” 
- [ ] Associated judge displayed as “Judge Foley”  

#### 12) Docket clerk changes case status to On Appeal 
- Scenario 9
- Click Edit case button 
- Select On Appeal as case status 
Expected results 
On click of Edit Case
- [ ] modal displays 
On click of Save
- [ ] modal closes and success message displays 
- [ ] Case status tag displays as “On Appeal” 
- [ ] Associated judge displayed as “Judge Gustafson”  

#### 13) Docket clerk changes case status for a Calendared case 
- Login as docket clerk 
- Navigate to case detail page for a Calendared case 
- Click on Edit case button 
- Change status to “General Docket (At Issue)- Ready for Trial 
- Save 
Expected results 
- [ ] Edit Case modal displays alert message related to calendared status
On Save 
- [ ] Modal closes and success message displays 
- [ ] Case is removed from the trial session 
- [ ] Case displays in Inactive Cases tab and All Cases tab of trial session 
- [ ] Case disposition displays as “Status was changed to General Docket (at Issue) Ready for Trial” Inactive Cases tab and All Cases tab
- [ ] Case status displays as “General Docket (At Issue)- Ready for Trial 
- [ ] Associated judge displays as “Chief Judge”
