### ISSUE TITLE
Docket Clerks: Service of Internal Documents (electronic)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2378]
As a Docket Clerk, in order to serve internal documents parties, I need the ability to electronically serve the documents to parties with an electronic service indicator.

## Pre-Conditions
* An internal document is ready to be served to parties in a case (docket entry is created, image linked to docket entry)

## Acceptance Criteria
* Docket clerk can electronically serve any court-issued document to parties that require electronic service
* Docket will need the ability to select between “Served” or “Entered and Served” for specific documents
   * The following documents will always be "Entered and Served"
      * Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
      * Order of Dismissal (Code = OD)
      * Order of Dismissal and Decision (Code = ODD)
      * Order and Decision (Code = OAD)
      * Decision (Code = DEC)
      * Stipulated Decision (Code = SDEC)
   * Generic Orders (Code = O) need the option to be "Served" or "Entered and Served"
   * Any other Order (see https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing) would always be "Served"
* Document is served electronically only to those parties who have an electronic service indicator (Per Rhonda - court-issued document are always served on all parties)
* When a document is served, either the “Served” or “Entered and Served” dates, is applied to the document 
* Whenever the following documents are "Entered and Served", the case status is automatically changed to `Closed`
      * Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
      * Order of Dismissal (Code = OD)
      * Order of Dismissal and Decision (Code = ODD)
      * Order and Decision (Code = OAD)
      * Decision (Code = DEC)
      * Stipulated Decision (Code = SDEC)
* Service date and time, and who was served, are captured on docket record (Displays a "B" for "both")
* Parties receives an email notifying them to log into the system because there's been activity in the case.
* Parties can log in and see the court-issued document in the system
* The docket entry should link to the PDF
* Party can see served date on first page at the bottom center of the document

## Notes
* Cover pages are not added to court-issued documents

## Tasks
- [x] 1 Add Service Stamp field to court-issued docket entry form, entities, validation updates (Rachael #3635)
  - [x] 1a Add served/entered and served doc type options to entity (Rachael #3635)
- [x] 2 Create Serve to Parties modal, open/close sequences (Matt #3631)
- [x] 3 Endpoint (interactor, serverless, lambda, proxy) for serving court-issued document (Matt, Cody #3644)
  - [x] 3a Add Served/Entered and Served (based on doc type) stamp to bottom center of first page of PDF (Rachael #3648)
  - [x] 3b Send email to parties when document is served (Matt #3644, #3658)
  - [x] 3c Case status automatically changes to “Closed” for some doc types - see list below (Matt #3647)
- [x] 4 Sequences, actions to submit the modal and call endpoint (Cody)
  - [x] 4a Navigate to Case Detail page with success message
- [x] 5 Move in-progress work item to processed after document is served (Rachael #3653)
- [x] 6 After a document is served, the docket clerk link to the document on the docket record/work queue should go to the document detail instead of edit docket entry (Cody #3649)
- [x] 7 If a case is closed but was previously ready for trial, it should no longer show up on trial session eligible cases (Cody #3652)
~- [ ] 8 If a case is closed but was previously calendared, it should be moved to the inactive cases for the trial session~ this is already working
- [x] 9 Update docket record view for unserved court-issued doc (see https://github.com/flexion/ef-cms/issues/2378#issuecomment-556058359) (Rachael #3656)
- [x] 10 Can't create a user account with email - error during email verification step (Cody) 
~- [ ] 11 Allow signing of Proposed Stipulated Decisions for only docket clerks, ADC, judges, and chambers - new permission needed?~ holding this for a future story
- [x] 12 Remove high priority and block when a case is closed (Rachael #3667)
- [x] 13 Signed Stipulated Decision in draft documents tab should go to the doc detail page with Add Docket Entry button and no Serve Document button - they should go through the same flow as any court-issued document (Rachael #3670)
- [x] 14 Sign document is erroring/going to a blank screen (Rachael #3670)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Add Docket Entry (Court-issued documents) screen 

**Event code = "O"**

* Display Service Stamp radio set field 
* Field is required when "O" is the document type selected 
* Error message when incomplete: "Select a service stamp"
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d56f945d-a5fc-4a64-9240-d0656f5149c9)

* If "Served" is selected, ON SERVE, add "Served mm/dd/yy" to the first page of PDF 
* If "Entered and Served" is selected, ON SERVE, add "Entered and Served mm/dd/yy" to the first page of PDF 

**Serve button**
* on click of Serve to Parties, display confirmation modal 

Example 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3bc8a8dd-3850-4559-9cca-17c77b92d0a2)

Example with placeholder 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c536e5b4-af10-4fed-b19b-67bf84637795)

#### On Serve 
On click of Yes, Serve from modal 

* modal closes, and app navigates to Case Detail page with success message displayed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6d972fa4-a2bb-4bad-a9a4-17f00aaa421d)

**Docket entry**
* displays as complete (no pin icon, no background color)
* Filed date displays as current date 
* Served column displays with current date 
* Parties column displays "B"
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8740756d-cf39-42e4-8111-2d304b3bc62c)

**Served stamp on PDF**
* Served stamp is applied to PDF on bottom center of first page 
* see spreadsheet for logic per document type: https://docs.google.com/spreadsheets/d/1et69WCFOlanKsO56Kd7MeP18tw162ZrtTW48SVy-QBE/edit?usp=sharing

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4751f8d1-7477-4f66-9691-af69436e9da3)

**Service Email**
* email is generated for all parties with electronic service indicator 
* email template 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9fedf747-3b31-4821-9c92-a06b09312bd2)


**Automatic Case Status Change**
Case status automatically changes to "Closed" if the document type is any of the following: 
* Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
* Order of Dismissal (Code = OD)
* Order of Dismissal and Decision (Code = ODD)
* Order and Decision (Code = OAD)
* Decision (Code = DEC)
* Stipulated Decision (Code = SDEC)

**Comment by klohman** [comment]
### 2378 Test Scenarios 

Test data
- Create Case 1 as petitioner 1
    - Party type: Petitioner and Spouse 
    - Create Order for Case 1- Document type - O-Order 
- Create Case 2 as practitioner 1 
    - Create Order for Case 2 - Order of Dismissal 

#### 1) Docket clerk can select between “Served” and “Entered and Served” for “O-Order” 
- Login as docket clerk 
- Navigate to Case xxx-xx 
- Click on Draft Documents, and click Order 1 
- Click Add Docket Entry  
Expected results 
- [ ] Navigates to “Add Docket Entry scree 
- [ ] Document Type is repopulated with O-Order 
- [ ] Service stamp radio set is displayed 

#### 2) Docket clerk sees “Entered and Served” stamp on served Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
- Scenario 1 
- Change document type to ODJ-Order of Dismissal for Lack of Jurisdiction
- Click Serve to Parties and confirm
- Navigate to Docket record and click on ODJ link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 3) Docket clerk sees “Entered and Served” stamp on served Order of Dismissal (Code = OD)
- Navigate to Case 2 
- Click Draft Documents tab and click on Order of Dismissal 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Order of Dismissal link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 4) Docket clerk sees “Entered and Served” stamp on served Order of Dismissal and Decision (Code = ODD)
- Scenario 1 
- Change document type to ODD-Order of Dismissal and Decision 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Order of Dismissal and Decision link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 5) Docket clerk sees “Entered and Served” stamp on served Order and Decision (Code = OAD)
- Scenario 1 
- Change document type to OAD-Order and Decision 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Order and Decision link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 6) Docket clerk sees “Entered and Served” stamp on served Decision (Code = DEC)
- Scenario 1 
- Change document type to DEC-Decision 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Decision link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 7) Docket clerk sees “Entered and Served” stamp on served Stipulated Decision (Code = SDEC)
- Scenario 1 
- Change document type to DEC-Decision 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Decision link 
- View PDF 
Expected results 
- [ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF 

#### 8) Docket clerk sees “Served” stamp on served OAR - Order that the letter "R" is added to the Docket Number 
- Scenario 1 
- Change document type to OAR - Order that the letter "R" is added to the Docket Number 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on OAR link 
- View PDF 
Expected results 
- [ ] “Served [today’s date] is displays bottom center of the first page of the PDF 

#### 9) Docket clerk sees “Served” stamp on served O - Order when “Served” is selected 
- Scenario 1 
- Select “Served” from the Service stamp radio set 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Order link 
- View PDF 
Expected results 
- [ ] “Served [today’s date] is displays bottom center of the first page of the PDF 

#### 10) Docket clerk sees “Entered and Served” stamp on served O - Order when “Entered and Served” is selected
- Scenario 1 
- Select “Entered and Served” from the Service stamp radio set 
- Click Serve to Parties and confirm
- Navigate to Docket record and click on Order link 
- View PDF 
Expected results 
[ ] “Entered and Served [today’s date] is displays bottom center of the first page of the PDF  

#### 11a) Parties with electronic service receive email notification when document is served 
- Scenario 10
- Check email for petitioner 1 
Expected results 
- [ ] Petitioner 1 receives automated email that O - Order has been served 

#### 11b) Parties with electronic service receive email notification when document is served 
- Scenario 3
- Check email for practitioner 1 
Expected results 
- [ ] Practitioner 1 receives automated email that Order of Dismissal has been served 

#### 12) Docket clerk sees filed date, served and parties information populated on docket record when document is served 
- Scenario 8
- Navigate to Docket Record 
- View record for Order that the letter "R" is added to the Docket Number
Expected results 
- [ ] Filed date displays [today’s date]
- [ ] Served column displays [today’s date]
- [ ] Parties column displays “B”

#### 13) Other internal court user can access served document from docket record 
- Login as calendar clerk 
- Navigate to Case 1
- Click on Order that the letter "R" is added to the Docket Number  
Expected results 
- [ ] Navigates to document detail page for Order that the letter "R" is added to the Docket Number 
- [ ] Concatenated Document title displays as page title 
- [ ] Document with Served stamp displays in PDF viewer 

#### 14) External parties can access served document from docket record 
- Login as petitioner 1 
- Navigate to Case 1
- Click on Order from docket record 
Expected results 
- [ ] PDF opens in new tab 
- [ ] PDF of order displays served stamp and date 

#### 15) Docket clerk sees case status change to Closed when Order of Dismissal for Lack of Jurisdiction (Code = ODJ) is served
- Scenario 2 
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed 

#### 16) Docket clerk sees case status change to Closed when Order of Dismissal (Code = OD) is served
- Scenario 3 
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed 


#### 17) Docket clerk sees case status change to Closed when Order of Dismissal and Decision (Code = ODD) is served
- Scenario 4 
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed 

#### 18) Docket clerk sees case status change to Closed when Order and Decision (Code = OAD) is served
- Scenario 5
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed 


#### 19) Docket clerk sees case status change to Closed when Decision (Code = DEC) is served
- Scenario 6
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed 


#### 20) Docket clerk sees case status change to Closed when Stipulated Decision (Code = SDEC) is served
- Scenario 7
- View case status 
Expected results 
- [ ] Case status is updated automatically to Closed

**Comment by klohman** [comment]
# Update to Saved Order Docket Entry 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/726526cf-bb7a-4b6f-83f7-7f924fadb449)

* When order is saved (but not served) - display "Not served" in Served column

**Comment by klohman** [comment]
## UX Review comments 

- [ ] When case is Calendared and closed due to an order, the case should display in Inactive Cases (which it does) but the Case Detail > Trial Info card should display as “Trial - Not Scheduled” 
- [ ] When case is Scheduled for a trial session that is not yet set, the case should be removed from the trial session eligible list and the Case Detail > Trial Info card should display as “Trial - Not Scheduled” 
- [ ] Petitioner not receiving service emails - 121-19 testpetitionerustc1@gmail.com

**Comment by JessicaMarine** [comment]
PO Review 11.26.19:
* On staging in 105-19, I created and served an Order to Show Cause.  The docket entry language created as part of adding that document to the docket record was not carried through and displayed to party (Petitioner1).  If I log in as the party, I see "Order[anything]" instead of the actual docket entry language.  Interestingly, when I created an Order and Decision in 102-19, the correct language DID come through to the party

**Comment by JessicaMarine** [comment]
PO Review 11.30.19:
* In 123-19 in Staging, I created an Order to Show Cause and served it on the parties.  However, the item is still showing under the "In Progress" QC tab and if you click into the doc detail page from there, it says it has not been served:
image.png 
image.png

However, if you click into the same document through the Docket Record, it shows that it has been served:
image.png 
image.png
It doesn't look like things are moving from the "In Progress" tab to the "Processed" tab correctly.
* Also, the document name that comes through on the service email should be the fully concatenated docket entry.  For example, "OSC- Order" should be "Order for Petitioner to Show Cause by 12/1/19 why Respondent's motion should not be granted" and "ODJ- Order of Dismissal for Lack of Jurisdiction, Entered" should be "Order of Dismissal for Lack of Jurisdiction, Entered Judge Buch"
image.png 
image.png
