### ISSUE TITLE
Docket Clerk: Ability to add court-issued documents to the docket record

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2380]
## Pre-Conditions
* Court-issued documents exist in a draft state

## Acceptance Criteria
* Docket Clerk needs the ability to add Court-issued documents to the Docket Record [Note: This functionality should only exist for Docket]
* Docket Clerk will use unique codes for various types of Orders/Notices/Opinions/Decisions -- code will drive language generated for docket entry  (https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing)
* Once Order is associated with docket entry, it is viewable by parties

## Notes
* After order is created, sent to docket, docket takes from draft tab, creates a docket entry and links the document to the docket entry; then service comes after this. 
* Similar to docket entry creation for external documents, with the exception of some fields
* Instead of "magic" document selector, more free form. Court can issue orders for anything, so there's no way to pre-populate it

## Tasks
- [x] 1 Update Draft Order screen (Matt #3565)
- [x] 2 Create Add Docket Entry view for court-issued docs (Cody #3562)
  - [x] 2a Dynamically generate concatenated docket entry on user input (Rachael #3576)
  - [x] 2b Use typeahead document type selector (Cody #3562)
  - [x] 2c Add document types (see document) to mapping generator (Cody #3562)
  - [x] 2d Ensure additional fields are displayed per document type (Rachael #3568)
  - [x] 2e Truncate concatenated docket entry after 2 lines and add attachments text if selected (Rachael #3586)
- [x] 3 Create entity for non-standard document types (Rachael #3552)
- [x] 4 Cancel modal / sequence / actions (Cody #3562)
- [x] 5 Link Add Docket Entry sequence (Matt #3567)
- [x] 6 Cancel Add Docket Entry sequence (Matt #3567)
- [x] 7 Save docket entry sequence / actions (Matt #3589)
- [x] 8 Save court issued docket entry interactor (Matt #3585)
- [x] 9 Form validation (Rachael #3578)
  - [x] 9a Select original order type when page is loaded (Rachael #3578)
- [x] 10 Refactor isDraftDocument computed to exclude SAVED court-issued doc after docket entry is created (Team mob #3594)
- [x] 11 Create `inProgress` state for newly created docket entry (Matt #3592)
- [x] 12 Link to Edit Docket Entry page from docket record for in-progress court-issued doc (Team mob #3594)
- [x] 13 Create endpoint for editing court-issued document docket entry (Team mob #3600)
  - [x] 13a Call correct interactor for updating docket entry when submitting from the edit docket screen (Team mob #3600)
- [x] 14 In-progress work item after docket entry is created (Team mob #3600)
- [x] 15 (Attachment(s)) text is showing up twice on the created docket entry (Cody #3599)
- [x] 16 Update document detail view for internal users other than docket clerks for saved court-issued docs (Rachael #3601)
- [x] 17 Fix for Scenario 4a - "What is this order for" field is repopulated with "Order to do something" (Rachael #3603)
- [x] 18 Fix for Scenario 12 - "Filed" date is blank (Rachael #3603)
- [x] 19 Fix for Scenario 15 - Saved order link is not clickable (and the title looks wrong — templated) (Rachael #3605)
- [x] 20 Cancel add docket entry modal not clearing (Rachael #3605)
  - Create order
  - Go to draft documents and click on order
  - Add docket entry
  - Cancel - confirm cancel
  - Go back to order, create draft document
  - *Modal still displays* (but should not)
- [x] 21 When you change the document type - the text entered in “What is this order for” field persists- this should clear when a different document type is selected (Rachael #3605)
- [x] 22 Link to Edit Docket from work item for docketclerk users; link to document detail for non-docketclerk users (Rachael #3606)
- [x] 23 Currently logged-in user should be assigned to the work item created when the docket entry is created (and it should also be updated if the docket entry is updated) (Rachael #3606)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt #3629)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Rachael)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
## Research Notes 
**Document Creation**
* Judge/ADC creates internal document 
* Draft documents exist in the “Pending order” (= Draft Documents)
* Judge/ ADC sends message to Docket to QC the pending document
* All Court users have access to the draft documents from the case page 

**Docket QC**
* Docket reads the entire text of the order for quality assurance 
* If something is wrong with the document, they send a message to whoever created the order with a note of what to fix 
* If the document is correct, docket adds it to the docket record and serve 

**Adding Docket Entry** 
**Document Title (Filings and Proceedings)**
* They enter the document title with whatever is being ordered (from the text of the order document) 
* The event code for 90% of Orders is the generic “O” 

**Filed Date**
* This date is whatever date is on the order itself 
* Could be a past date 
* Only have served date?  Or record date? - JESSICA ??

**PDF** 
* Currently all documents are created in Word and copy pasted into the system 
* Docket views the PDF in the system and links it to the docket entry - same as paper filings - drag and drop 

**Attachments** 
* Need the ability to indicate iif any attachments are included with the document
* If attachments are included, this information [Attachment(s)] is added to the concatenated Document Title 
* Sometimes they have attachments that go into the Correspondence file but are not added to the docket record 

**Complete Entry**
* Docket adds the new docket entry in the system after they have read the order 
* They currently have the ability to “unlink” an image from a docket entry and return the document to pending 
* They would like to have the option to pull an entry back before it’s served 

**Single Document - Multiple Docket Entries (HOLD - need priority from Jessica)**
* May need to add an order and apply it to multiple cases 
* This happens a few times a month

**Comment by klohman** [comment]
### Update to Draft Order screen 

**For Internal Users (NOT Docket Clerk role)**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eb24845d-93f3-49ad-bdf8-ae92bed79c06)

* Change label of "Edit" link to "Edit Order" (this link takes user to the Edit Order screen  
* Move "Edit Order" and "Delete" links 

**For Docket Clerk role**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cc1ed8cd-0df2-4691-bd02-aa4439abf91d)

* Add button "Add Docket Entry" 

#### Add Docket Entry (Court-Issued Documents)
On click of "Add Docket Entry" button 
* Navigate to new "Add Docket Entry" screen for court-issued documents 
* Order PDF is displays in PDF viewer

**Comment by klohman** [comment]
### 2380 test scenarios 

Test Data 
- Create Case xxxx-xx as petitioner 1
    - Create Draft Orders
        - Order 1
            - Select “Order” from dropdown
            - Enter “Order to do something” in What is this order for field
        - Order 2
            - Select “Order for Dismissal” from dropdown

#### 1) Internal user other than docket cannot view Add Docket button on Draft Order page 
* Login as petitions clerk 
* Navigate to Case xxx-xx
* Click on Draft Documents tab 
* Click on Order 
Expected results 
* [ ] User does not see “Add Docket Entry” button

#### 2) Docket Clerk views Add Docket button on Draft Order page 
* Login as docket clerk 
* Navigate to Case xxx-xx
* Click on Draft Documents tab 
* Click on Order 1
Expected results 
- [ ] User sees “Add Docket Entry” button

#### 3) Docket clerk views final Order PDF on Add Docket screen 
* Scenario 2
* Click “Add Docket Entry” button 
* View Order PDF 
Expected results 
- [ ] PDF viewer on Add Docket Entry screen displays the same PDF as the Edit Order page  

#### 4a) Docket clerk views previously entered document type and title for “O” order type
* Scenario 3
* View document type 
Expected results 
- [ ] Document Type field is repopulated with “O” code 
- [ ] “What is this order for” field is repopulated with “Order to do something”
- [ ] “What is this order for” field is editable

#### 4b) Docket clerk views previously entered document type and title for other order types
* Navigate to Case xxx-xx
* Click on Draft Documents tab
* Click on Order 2 
* View document type 
Expected results 
- [ ] Document Type field is repopulated with “OD” code 
- [ ] “Judge Name” field is displayed with empty state
- [ ] “What is this order for” field is displayed with empty state

#### 5) Docket clerk adds Type A document type 
* Scenario 3
* Change Document Type to OCA
Expected results 
- [ ] Docket clerk sees all order codes listed in dropdown 
- [ ] On select of OCA, “What is this order field” is blank 

#### 6) Docket clerk adds Type B document type 
* Scenario 3
* Change Document type to OAJ
Expected results 
- [ ] “JUdge’s Name” field displays with empty state 
- [ ] “What is this order for” field displays with empty state

#### 7) Docket clerk adds Type C document type 
* Scenario 3
* Change Document type to OAL
Expected results 
- [ ] “Docket Number(s)” field displays with empty state 
- [ ] “What is this order for” field is hidden

#### 8) Docket clerk adds Type D document type 
* Scenario 3
* Change Document type to OAP
Expected results 
- [ ] “Date” field displays with empty state 
- [ ] “What is this order for” field displays with empty state

#### 9) Docket clerk adds Type E document type 
* Scenario 3
* Change Document type to OOD
Expected results 
- [ ] “Date” field displays with empty state 
- [ ] “What is this order for” field is hidden

#### 10) Docket clerk selects inclusion 
* Scenario 4b
* Select Judge Buch as Judge
* Enter “for Something” in the “What is this order for” field
* Check “Attachments” checkbox 
* Save order 
Expected results 
- [ ] Incomplete docket entry concatenation is Order of Dismissal entered, Judge Buch for Something (Attachment(s)) 

#### 11) Docket clerk cancels new docket entry 
* Scenario 3
* Click “Cancel” and confirm
Expected results 
- [ ] On click of Cancel, confirmation modal displays 
On confirm
- [ ] modal closes
- [ ] user is navigated back to Case Detail page
- [ ] Order 1 is displayed in draft documents tab 

#### 12) Docket clerk saves new docket entry 
* Scenario 4a
* Click “Save” button
Expected results 
- [ ] User is navigated back to Case Detail page with success message displayed 
- [ ] New docket entry displays as incomplete 
- [ ] “Filed” date is blank 
- [ ] Concatenated title is “Order to do something”

#### 13) Docket clerk views saved docket entry 
* Scenario 12 
* Click on “Order to do something” document link
Expected results 
- [ ] Navigates to “Edit Docket Entry” screen 
- [ ] Alert message displays on Edit Docket Entry screen
- [ ] Document type is repopulated with “O” code 
- [ ] What is this order for field is repopulated with “Order to do something”

#### 14) Internal user other than docket clerk views saved entry 
* Login as calendar clerk 
* Navigate to case xxx-xx
* View docket record 
* Click on “Order to do something” 
Expected results
- [ ] Calendar clerk views “Order to do something” on docket record with incomplete indicator 
- [ ] Saved order link is not clickable 

#### 15) External party views saved entry on docket record 
* Login as petitioner 1 
* Navigate to case xxx-xx
* View docket record 
Expected results 
- [ ] Saved Order is visible on the docket record 
- [ ] Saved order link is not clickable

**Comment by klohman** [comment]
### Update to Document Detail 
**For all internal documents** 
  * Display "Created mm/dd/yy by [User] 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e9b640a7-4595-4d47-a991-1cfbef1dd4aa)


**For external documents**
* Display "Filed mm/dd/yy by [Filing Party] 
![Screen Shot 2019-11-12 at 11.05.24 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/976ea6dc-f1be-420b-a379-c3db8c83bc03)

**Comment by klohman** [comment]
# 2380 UX Review 

- [ ] [Anything] field (“what is this order for?”)- needs to be optional for all event codes EXCEPT “O” - for event code “O” - field is required

- [ ] Date field cannot be in the past (current and future dates are valid) - currently validation seems to be catching future dates but allowing past dates

- [ ] When Docket Entry is saved - it’s creating a Message thread that is appearing on the Case Detail > In Progress message and on Document Detail
    - no system message should be created - the document should appear in Document QC In-Progress tab 

- [ ] Service parties - font size should be 17px (same as body copy)

- [ ] When entry is saved - Filed By column in docket record should be blank (currently populating with username who saved the entry)
