### ISSUE TITLE
Revamp content of service emails for documents other than a Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#2383]
As the Court, in order to make sure that the parties are getting sufficient information, the content of the service emails needs to be updated.

## Acceptance Criteria
* Service email for all other documents (other than a Petition) must include the following information:
   * Case name 
   * Docket Number
   * Document Name
   * Docket Index Entry No.
   * Document Type (Code)
   * Filing party
   * Served Date/Time
   * Hyperlink to log into the system
* Service email must also include the following machine readable data: [Note: needs to be added to design]

------------------------ COMPUTER-READABLE DATA -------------------
docketNumber: [docketNumber]
docketEntryNo: [XX]
documentId: [documentId]
eventCode: [eventCode]

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update service email content (Rachael #5182)
- [x] 2 Send IRS superuser emails for non-petition initial case documents when served (Rachael #5183)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [ ] Deployed to the stage environment

**Comment by alsmith1** [comment]
![e178fe25-14a8-4096-a4d7-2d9d9426dd7a.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c4cc837b-32d6-478f-b0e1-28b58df01966)

**Comment by alsmith1** [comment]
####DRAFT TEST SCENARIOS####

## Test scenarios
#### Scenario 1 - (petitioner) Service email for all other documents (other than a Petition) must include the following information:
* Case name
* Docket Number
* Document Name
* Docket Index Entry No.
* Document Type (Code)
* Filing party
* Served Date/Time
* Hyperlink to log into the system

1. As a petitioner log into your email account associated with your USTC account
2. Verify there is a new email in your inbox informing service of a document in your case
3. Verify subject is listed as: eService Notification from US Tax Court
4. Verify that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
5. Click the link from your email
6. Log into the system
7. Verify that you are directed to the docket record
8. Verify that the document you were emailed about appears on the docket record
9. Click on the document link and verify the document just added

Expected result
- [ ] there is a new email in your inbox informing service of a document in your case
- [ ] subject is listed as: eService Notification from US Tax Court
- [ ] that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
- [ ] directed to the docket record
- [ ] the document you were emailed about appears on the docket record
- [ ] the document just added is displayed and has the content that it should

#### Scenario 2 - (practitioner) Service email for all other documents (other than a Petition) must include the following information:
* Case name
* Docket Number
* Document Name
* Docket Index Entry No.
* Document Type (Code)
* Filing party
* Served Date/Time
* Hyperlink to log into the system

1. As a practitioner log into your email account associated with your USTC account
2. Verify there is a new email in your inbox informing service of a document in your case
3. Verify subject is listed as: eService Notification from US Tax Court
4. Verify that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
5. Click the link from your email
6. Log into the system
7. Navigate to the case listed in the email
8. Verify that the document you were emailed about appears on the docket record
9. Click on the document link and verify the document just added

Expected result
- [ ] there is a new email in your inbox informing service of a document in your case
- [ ] subject is listed as: eService Notification from US Tax Court
- [ ] that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
- [ ] docket record page loads
- [ ] the document you were emailed about appears on the docket record
- [ ] the document just added is displayed and has the content that it should
- 

#### Scenario 3 - (respondent) Service email for all other documents (other than a Petition) must include the following information:
* Case name
* Docket Number
* Document Name
* Docket Index Entry No.
* Document Type (Code)
* Filing party
* Served Date/Time
* Hyperlink to log into the system

1. As a respondent log into your email account associated with your USTC account
2. Verify there is a new email in your inbox informing service of a document in your case
3. Verify subject is listed as: eService Notification from US Tax Court
4. Verify that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
5. Click the link from your email
6. Log into the system
7. Navigate to the case listed in the email
8. Verify that the document you were emailed about appears on the docket record
9. Click on the document link and verify the document just added

Expected result
- [ ] there is a new email in your inbox informing service of a document in your case
- [ ] subject is listed as: eService Notification from US Tax Court
- [ ] that the following information displays in the email:
    * Case Name
    * Docket Number
    * Document Name
    * Docket Index Entry No.
    * Document Type (Code)
    * Filing party
    * Served Date/Time
    * Hyperlink to log into the system
- [ ] docket record page loads
- [ ] the document you were emailed about appears on the docket record
- [ ] the document just added is displayed and has the content that it should

**Comment by mariahkannenberg** [comment]
Not including Court's logo.

**Comment by klohman** [comment]
## Document Service Email 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f277119d-e6ca-4760-84d8-0b21a3a2629e)

**Comment by klohman** [comment]
## Test scenarios

#### Scenario 1: IRS super user only receives service email for documents served with the Petition 
* Login as petitioner 
* File a petition with ODS
* Login as petitions clerk 
* QC and serve petition 
* Login to IRS super user email 
* Login to petitioner email 
Expected results 
- [ ] IRS super user receives service email for Petition 
- [ ] IRS super user receives service email for ODS 
- [ ] Petitioner does not receive service email for Petition 
- [ ] Petitioner does not receive service email for ODS 

#### Scenario 2: IRS super user receive service emails with all required information (per template) for documents other than the Petition 
* Login as petition clerk 
* Create case (from paper petition) 
* Upload petition, ODS, RQT, APW
* Serve petition 
* Login to IRS super user email 
Expected results
- [ ] IRS super user receives service email for Petition containing all required information (from Petition service template #3923)
- [ ] IRS super user receives service email for ODS containing all required information (from document service template) 
- [ ] IRS super user receives service email for RQT containing all required information(from document service template) 
- [ ] IRS super user receives service email for APW containing all required information(from document service template) 

#### Scenario 3: Parties receive service email containing all required information (per template) for served documents (other than petition) 
* Scenario 1 
* Login as docket clerk 
* Create, sign, save, and serve Order for Dismissal 
* Login to IRS super user email 
* Login to petitioner email 
Expected results 
- [ ] IRS super user receives service email for Order for Dismissal containing all required information(from document service template) 
- [ ] Petitioner receives service email for Order for Dismissal containing all required information(from document service template)

**Comment by klohman** [comment]
UX Notes 

# 2383![Screen Shot 2020-05-18 at 9.37.11 AM.png]
- We can removed the document code from the main body text and only include event code under the IRS only section (updated in Figma) 
- Seeing a duplicate time zone on documents other than petition 
![Screen Shot 2020-05-18 at 9.37.11 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4a9b11e2-74cf-49a3-8d78-bf918c15c406)



- IRS super user is not receiving service for documents served not associated with Petition; examples:
    -  162-20SL - IRS superuser should have received service for Computation for Entry of Decision
    - 163-20 - IRS superuser should have received service for Order
