### ISSUE TITLE
Judge: Working copy of trial session

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2565]
As a Judge, in order to manage the cases scheduled on a trial session, I need the ability to access and manage the cases from a centralized report.

Once a Judge is assigned to a trial session, they will start reviewing the cases on that session.  They need a working copy of the trial session list (#1194) that they can work from.  That working copy is only viewable by the Judge and needs to be quickly and easily accessible.

## Pre-Conditions:
•	A trial session exists in the system
•	A Judge has been assigned to that trial session

## Acceptance Criteria:
•	 A Judge has a working copy of the trial session list (#1194) for each trial session the Judge is assigned to
•	The working copy of the trial session list should be quickly and easily accessible from the Judge’s dashboard (#1272)
•	The Judge should be able to access both upcoming and old working copies
*  Only the judge assigned has access to the working copy
* Judge should still be able to see the full "court copy" of the trial session

## Tasks:
- [x] 1 Verify that a judge is associated to a Trial Session (Rachael #2709) 
- [x] 2 Link session summary links to Judge Session Working Copy of trial session — if assigned — else to standard trial session detail screen (also link to working copy from the main trial session list if the user is assigned to the session) (Rachael #2709)
- [x] 3 Add “switch to working copy / session detail” link in header of Trial Session Detail / Trial Session Working Copy pages; separate routing! Only visible if session assigned to judge (Kris #2711)
- [x] 4 Trial Session Working copy routing / page / init sequence / helper (William #2702)
- [x] 5 Trial Session Working Copy Table (William #2707)
	- [x] 5a Sort session working copy by newest docket number first
	- [x] 5b List petitioner counsels oldest to newest
	- [x] 5c List respondent counsel, oldest to newest

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael #2713)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael #2713)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by klohman** [comment]
### Accessing the Working Copy 

#### Dashboard 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aeb9cc12-c313-459b-b708-af0c6b729036)

* Clicking on the trial session link from the Judge's dashboard navigates user to the judge's Session Working Copy for that trial session 

#### Trial Sessions Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8b741e8b-862d-4070-9fea-83f8bfff5ec1)

* If a judge user clicks on a trial session link from the Trial Sessions page, navigate to their working copy 
* Judge's should always navigate to their Working Copy for trial sessions they are assigned to; if they are not assigned to a trial session, navigate to the standard Trial Session Detail screen 

#### Trial Session Detail screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/493acec3-6534-4586-afe0-c45482507990)

* Add to header - "Switch to Working Copy" link 
* On click of "Switch to Working Copy" - navigate to Working Copy 

### Session Working Copy 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5d2fe9fc-e906-444b-95b2-189762c77cdf)

* Use the same header as on Trial Session Detail - link should change to "Switch to Session Detail" 
* On click of "Switch to Session Detail" - navigate to Trial Session Detail screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57d465d9-b6dd-4a12-8362-a9f109ce0fdb)

**Docket Number**
* Sort by docket number - oldest to newest
* This is will be a sortable field (#2567)
**Case Caption**

**Petitioner Counsel**
* List all petitioner counsel associated with case - ordered oldest to newest
*This will be a sortable field (#2567)

**Respondent Counsel**
* List all respondent counsel associated with case - ordered oldest to newest

** Trial Status**
* Leave blank- will add functionality in #2567)

**Comment by klohman** [comment]
### 2565 Test Scenarios  

#### 1) Judge is assigned to a trial session 
* Login as Calendar Clerk 
* Create Trial Session with Judge Ashford assigned [ location Mobile, Alabama]
Expected Results 
- [ ] Judge Ashford displays as judge for the new trial session on Trial Sessions screen and Trial Session Detail screen 


#### 2) Judge is assigned to all cases on a trial session he is assigned to 
* Login as Calendar Clerk 
* Create Trial Session with Judge Ashford assigned 
* Set 2 eligible cases to new trial session 
Expected Results 
- [ ] Judge Ashford displays as judge on Case Detail screen for 2 cases assigned to the new trial session 


#### 3) Judge views Working Copy for assigned sessions from dashboard 
* [ Test Scenario 1] 
* Login as Judge Ashford 
* Click on Mobile, Alabama trial session from the dashboard 
Expected Results 
- [ ] Navigates to Judge’s Working Copy for Mobile, Alabama 

#### 4) Judge views Working Copy for assigned sessions from Trial Sessions screen
* [ Test Scenario 1] 
* Login as Judge Ashford 
* Click on Trial Sessions from global navigation
* Click on Mobile, Alabama 
Expected Results 
- [ ] Navigates to Judge’s Working Copy for Mobile, Alabama 

#### 5)Judge cannot view Working Copy for unassigned sessions 
* [Test Scenario 1 ] 
* Login as Judge Carluzzo 
* Click on Trial Sessions from global navigation 
* Click on Mobile, Alabama session link 
Expected Results 
- [ ] Mobile, Alabama session does not display on Judge Carluzzo’s dashboard 
- [ ] On click of Mobile, Alabama link, navigates to the standard Trial Session Detail screen 
- [ ] Option to “Switch to Working Copy” is hidden 

#### 6) Judge can toggle between Working Copy and standard Trial Session detail for assigned cases 
* [ Test Scenario 1] 
* Login as Judge Ashford 
* Navigate to Working Copy for Mobile, Alabama
* Click “Switch to Session Detail”
* Click “Switch to Working Copy” 
Expected Results 
- [ ] On click of “Switch to Session Detail, navigates to standard Trial Session Detail screen for Mobile, Alabama
- [ ] Trial Session Detail screen displayed option to “Switch to Working Copy” 
- [ ] On click of “Switch to Working Copy”, navigates to Working Copy 

#### 7) Judge’s Working Copy has all cases included in Trial Session 
* [ Test Scenario 1] 
* Login as Judge Ashford 
* Navigate to Working Copy for Mobile, Alabama
Expected Results 
- [ ] Cases on working copy match cases on Trial Session Detail for Mobile, Alabama session

#### 8) Judge can access Working Copy for a past trial session 
* Create trial session [Baltimore, MD] assigned to Judge Armen with date in the past (needs to be done on the backend)
* Login as Judge Armen 
* Click on Baltimore, MD trial session from dashboard
Expected Results 
- [ ] Baltimore, MD displays under Recent Sessions
- [ ] On click, navigates to Working Copy for Baltimore, MD session
