### ISSUE TITLE
Judge: Manage calendar call

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2567]
As a Judge, in order to manage the cases on a trial session during the Calendar Call, I need the ability to quickly add information and manipulate my working copy of the trial session list.

When a Judge arrives on site for a trial session, one of the first things he/she does is to have a "Calendar Call." During a calendar call, the parties for each case that is scheduled for the trial session is present in the court room. To perform the calendar call, the trial clerk calls before the Court every case that scheduled for the session. As each case is called, the parties tell the Judge the trial status (not to be confused with the case status) of the case and whether a trial is necessary. As each case is called, in addition to making notes about the case, the Judge also needs the ability to quickly mark the "trial status" of the case.  Some standard trial statuses are: Set for Trial, Dismissed, Continued, Rule 122, A Basis Reached, Settled, Recall, Taken Under Advisement.  The Judge needs the ability to sort and/or filter the list of cases on the trial session list based on "trial status".  The Judge also needs the ability to hide cases that they don't want to see any longer - this may be on an individual case-by-case basis or auto-hide based on "trial status".  If the Judge takes action on an item(case) in the list, they need the ability to easily move on to take action on the next item in the list, without losing one's place.

## Pre-Conditions
* A Judge has a working copy of a trial session list (#2565)

## Acceptance Criteria
* Judge needs the ability to assign a trial status (not to be confused with case status) to a case scheduled for a trial session
   * Ability to select a "trial status" from pre-defined statuses 
   * Trial Statuses: Set for Trial, Dismissed, Continued, Rule 122, A Basis Reached, Settled, Recall, Taken Under Advisement
* Judge needs the ability to sort and/or filter the cases on the working copy based on "trial status"
* Judge needs the ability to hide cases on the working copy that they don't want to see any longer based on "trial status"
* Judge needs to take action on an item on the working copy and easily move on to take action on the next case, without losing one's place
* Judge needs the ability to access/hyperlink into each case detail page from the working copy

## Tasks
- [x] 1 Add trial statuses to trial session or case entity? (Rachael, Kris #2728)
- [x] 2 Add trial status dropdown to each case row on the working copy (William #2727)
- [x] 3 Add filtering view to the working copy page (Rachael #2736)
- [x] 4 Add filtering functionality to the computed (along with count of cases shown) (Rachael #2752)
- [x] 5 Add sorting options to the UI on the working copy case table (William #2727)
  - [x] 5a Add sorting functionality to the computed 
- [x] 6 Functionality for storing/updating trial session working copy (including sort/filter options selected and case trial statuses) (Rachael #2731 #2735)
- [x] 7 Create TrialSessionWorkingCopy entity (Rachael, Kris #2728)
- [x] 8 Verify that a judge is associated with the session before allowing them to see the working copy (Rachael #2721)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (William #2760)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael #2758)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (William #2756)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment

**Comment by klohman** [comment]
### Trial Status 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6daac310-75c9-4864-a9ed-e79720295dc7)

* Add Trial Status dropdown for each case row  
* Dropdown has no option selected by default
* Dropdown options include: 
     - Set for Trial 
     - Dismissed 
     - Continued
     - Rule 122
     - A Basis Reached 
    - Settled
    - Recall  
    - Taken Under Advisement

### Filter by Trial Status 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f39c4e0f-ba06-41fa-a05e-ce998037b0e2)

* Display filter options (see Figma) 
* Display count of total number of cases displayed (with filters) as "Total Shown: XX"

**Show All**
* Checked by default 
   - All cases on trial session are displayed
   - Count of cases = total number of cases on the trial session
* If unchecked 
   - All cases are "filtered out" 
   - Display message "Please select a trial status to show cases"  
* If another option is unchecked while "Show All" is checked 
   - The unchecked option is filtered out of the case list 
   - Show All is unchecked 
   - The remaining checked options are still included in the case list 
   - Count of cases is updated = number of cases with statuses matching checked filter options 

**Other Trial Status Filters**
* If checked 
   - Cases with that trial status set are included in the displayed case list 
*If unchecked 
  - Cases with that trial status are filtered out of the case list 

**Status unassigned**
* Refers to the unselected state of the Trial Session dropdown 

* If checked 
   - Cases with no trial status selected are included in the displayed case list 
* If unchecked 
- Cases with no trial status selected are filtered out of the case list 

**No cases matching the selected filter criteria**
- If no cases match the trial status filters selected, display message "Please select a a trial status to show cases" 


### Sorting Cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ee2d1b74-37df-487a-8c6b-c08cdc3e33c9)

**Docket Number**
* Default sort order is docket number (oldest to newest) 
* Display sorted column with blue underline on-state (see figma) and icon color as #565c65 bg-base-dark
* Display off-state on sortable columns with icon color #005ea2 primary
* On click of "caret-down" icon
    - update sort to docket number newest to oldest 
    - icon is changed to "caret-up" 
    - on-state remains on Docket column 
* On click of "caret-up" icon
    - update sort to docket number oldest to newest 
    - icon is changed to "caret-down" 
    - on-state remains on Docket column 

**Petitioner Counsel**
* Column includes all petitioner counsel associated with the case 
* If no petitioner counsel, column is empty
* On click of "caret-down" icon
    - update sort to cases with petitioner counsel to cases with no counsel 
    - icon is changed to "caret-up" 
    - on-state is on Petitioner Counsel column 
* On click of "caret-up" icon
    - update sort to cases with no counsel to cases with petitioner counsel 
    - icon is changed to "caret-down" 
    - on-state is on Petitioner Counsel column 

### Cases 
* on click of Docket number, navigate to the Case Detail page for the selected case

**Comment by klohman** [comment]
### 2567 Judge - Manage Calendar Call - Test Scenarios 

#### 1) Judge assigns trial status to a case 
- Login as docket clerk 
- Create trial session with Judge Buch assigned 
- Set Calendar for trial session with 10 cases 
- Login as judgeBuch
- Navigate to trial session working copy 
- Set the trial status for case 1 to “Continued” 
- Set the trial status for case 2 to “Set for Trial”
- Set the trial status for case 3 to “Dismissed”
- Set trial status for case 4 to “Rule 122” 
- Set trial status for case 5 to “A Basis Reached”
- Set trial status for case 6 to “Settled” 
- Set trial status for case 7 to “Recall” 
- Set trial status for case 8 to “Taken Under advisement” 

Expected Results 
- [ ] On load of Working Copy, all cases have a trial status as unselected 
- [ ] Case 1 displays as “Continued” 
- [ ] Case 2 displays as “Set for Trial”
- [ ] Case 3 displays as “Dismissed”
- [ ] Case 4 displays as “Rule 122”
- [ ] Case 5 displays as “A Basis Reached” 
- [ ] Case 6 displays as “Settled” 
- [ ] Case 7 displays as “Recall” 
- [ ] Case 8 displays as “Taken Under Advisement” 
- [ ] Case 9 and 10 displays as unselected 


#### 2) Judge sees all cases with all trial statuses 
- [Scenario 1] 
Expected Results 
- [ ] Show All checkbox is checked 
- [ ] All trial status checkboxes are checked 
- [ ] Cases 1-10 display in table   

#### 3) Judge can hide all cases 
- [ Scenario 1] 
- Uncheck “Show All” 
Expected results 
- [ ] All trial status checkboxes are unchecked 
- [ ] Table is empty 
- [ ] Message displays “Please select a trial status to show cases.”

#### 4) Judge filters out cases with specific trial statuses
- [ Scenario 1 ] 
- Uncheck “Set for Trial” 
- Uncheck “Continued” 
- Uncheck “Dismissed”

Expected Results 
- [ ] Show All checkbox is automatically unchecked
- [ ] Case 1 is removed from list 
- [ ] Case 2 is removed from list 
- [ ] Case 3 is removed from list 
- [ ] Cases 4-10 display in list


#### 5) Judge views cases with no trial status assigned 
- [ Scenario 3 ]
- Check “Status unassigned” 
Expected results 
- [ ] Cases 1-8 are removed from table 
- [ ] Cases 9 and 10 (with status unselected) display in table


#### 6) Judge hides cases with no trial status assigned 
- [ Scenario 1] 
- Uncheck “Status unassigned” 
Expected Results 
- [ ] “Show All” checkboxes automatically unchecked 
- [ ] Cases 1-8 are displayed in table 
- [ ] Cases 9 and 10 (with status unselected) are removed from table


#### 7) Judge views cases sorted by docket number (oldest to newest) by default 
- Login as judgeBuch
- Navigate to trial session working copy 
Expected Results 
- [ ] Cases are sorted in docket number order (oldest to newest) 

#### 8) Judge sorts cases by docket number (newest to oldest) 
- Login as judgeBuch
- Navigate to trial session working copy 
- Click docket number sort icon 
Expected results 
- [ ] Case table sort order updates to display by docket number newest to oldest
- [ ] Docket record sort icon updates to “ caret up” 


#### 9) Judge sorts cases by petitioner counsel (with counsel to no counsel)
- Login as docket clerk 
- Create trial session with Judge Buch assigned 
- Set Calendar for trial session with 2 cases 
    - Case 1 - Pro Se petitioner 
    - Case 2 - Petitioner represented by counsel 
- Login as judgeBuch
- Navigate to trial session Working Copy 
- Click on Petitioner counsel “caret down” icon 

Expected Results 
- [ ] Default sort order of cases is docket number (Case 1, Case 2) 
- [ ] On click of Petitioner counsel sort icon, case order updates to Case 2, Case 1 
- [ ] Petitioner counsel column header displays on-state

#### 10) Judge sorts cases by petitioner counsel (no counsel to with counsel) 
- [ Scenario 9] 
- Click on Petitioner counsel “caret up” icon  
Expected Results 
- [ ] Case order updates to Case 1, Case 2 

#### 11) Judge sees the total number of cases being displayed 
- [ Scenario 1] 
- Uncheck “Show All” 
- Check “Status unassigned” 
- Check “Set for Trial” 
Expected results 
- [ ] With Show All checked, total number of cases shows as “10” 
- [ ] On uncheck of Show All, total number of cases shows as “0” 
- [ ] On check of Status Unassigned, total number of cases shows as “2” 
- [ ] On check of Set for Trial, total number of cases shows as “3” 

#### 12) Judge views saved changes to the Working Copy 
- [ Scenario 11]
- Sort case table by docket number (newest to oldest)
- Log out as judgeBuch 
- Log in as judgeBuch 
- Navigate to trial session Working Copy 
Expected results 
- [ ] Table filters are retailed - “Status unassigned” and “Set for Trial” are checked 
- [ ] Three cases display sorted by docket number (newest to oldest)

#### 13) Judge accesses the Case Detail screen 
- [ Scenario 1]
- Click on Docket number from case table 
Expected results 
- [ ] Navigate to Case Detail page for the selected docket number
-
