### ISSUE TITLE
Applying and editing signatures on uploaded PDF drafts

### ISSUE THREAD

**Issue by akuny** [flexion/ef-cms#2688]
_Originally opened by `@mariahkannenberg` on 2020-07-10 as ustaxcourt/ef-cms#7199._

## Acceptance Criteria

- Internal user can apply a signature to an uploaded pdf draft (current functionality)
- Internal user can edit a signature on an uploaded pdf draft and apply a new signature to the original uploaded PDF
- Internal user can edit the uploaded pdf draft, which will remove any existing signatures to the original uploaded PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 New endpoint for removing signature - Rachael & Mrin & rae ustaxcourt/ef-cms-flexion#5937
  - [x] Unset `signedAt`
  - [x] Set `documentId` back to `documentIdBeforeSigning`  
- [x] 2 Change "Edit Signature" buttons to say "Remove Signature" - (Matt ustaxcourt/ef-cms-flexion#5942)
- [x] 3 Edit uploaded PDF after signature is applied (Matt ustaxcourt/ef-cms-flexion#5944)
  - [x] From Drafts view
  - [x] From Case Messages view

Refactoring
- [x] 1 draftState - look at cleaning up - Rae ustaxcourt/ef-cms-flexion#5943
- [x] 2 Clean up - use isDraft in helpers instead of looking through the docket record - Mrin & Rachael & rae & Matt ustaxcourt/ef-cms-flexion#5945

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
