### ISSUE TITLE
Parties: Assign Doc Type for External Filing

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#269]
As a Petitioner, Practitioner and IRS Attorney, in order to correctly identify my document, I need to select my document type from a list of court-approved document types. 

For consistency in naming of documents filed with the Court, only Court-approved document types can be filed.  When a Petitioner wants to file a document in their case, they must select from the options provided by the Court.

## Pre-Conditions:
* Petitioner has indicated they want to file a document

## Acceptance Criteria:
* Parties are able to select a document type from a list of Court-approved documents. https://docs.google.com/document/d/1BIDQcmkZIql3w0alX8Skku5J-EgaS7SlVYTBTNtb2sc/edit?usp=sharing

## Notes:
* When we load the doc types into the system, we need to correspond them to the doc codes. Even though external parties won't use them, internal court users will. 
* We'll use this story to build out the tiered doctype design. 
* Pages 55-61 of Guide to eFiling (publicly available) shows how the Court currently does this: https://ustaxcourt.gov/eaccess/Petitioners_Guide_to_eAccess_and_eFiling.pdf
* There are some special circumstances (pages 61-74) that require special handling. However, they will handled in another story (#980). 
     *  Motion for leave to file per Rule 41(a) require motion and other document. Two separate upload spaces.
     *  Amended _____
     *  First/Second/Third Stipulation of Facts; etc.

## Tasks
- [x] Add File Document Button for petitioners, practitioners, and respondent (cody, #1254)
- [x] Create document type map with categories and titles (kris #1250  )
- [x] Update File Document screen with doc categories, helper text accordion, and button to open modal (Rachael #1255)
- [x] Import document type data into the app somehow (cody #1253)
- [x] Create modal for doc type selection with special modal styling (kris #1264 )
- [x] Make File Document its own page instead of a hidden section of the case detail page (Rachael #1258)
- [x] Refactor/combine case detail views (Rachael)

## Definition of Done

**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
@JessicaMarine 

options for the document type selection. 

The user will start with one dropdown populated with the top level document categories. This includes a type-ahead feature to bring them immediately to a specific category and a scroll. 

![Modal- Progressive Dropdown.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3127244e-f011-410a-9e7b-2a8c2eeabe86)


![Screen Shot 2018-12-05 at 5.05.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d4551b07-52d8-485e-b2ca-c1bd6a6f9624)

Based on the input into the first dropdown, a second dropdown displays populated with documents within the selected category. This is also searchable with a type-ahead feature and would include a scroll.  

![Modal- Answer Type.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/99123679-1e94-4f73-8605-d276c1d6bd9f)

Depending on the taxonomy, we can group documents under a second level category (showing the second category in blue here). 

![Screen Shot 2018-12-05 at 5.05.51 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ddcb7dc-b250-4e94-9ba8-7f8cf87731fb)

**Comment by klohman** [comment]
## Case Detail page 
- all external parties (petitioner, practitioner, and respondent) should see a File Document button on the case detail page of their cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e3b52d92-3baf-4242-a19c-4a43fc21d207)

On click of "File Document" button, open the File a Document default page 

## File a Document page 
- all visible fields are required 
- some fields will be displayed/hidden based on prior selections (noted in detail below) 

### Default View 

- Upload Your Document - required field 
- Document Category 
  - required field 
  - list is populated with all possible document categories (see spreadsheet)

- Document Name  
   - is required 
   - list is populated with all document types based on the selected document category 
   - if no document category is selected, show message " Select a Document Category to view documents"

- Frequently Used Documents 
   - list is TBD 
   - link will function as selecting the document type 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/46c51b08-9e3b-435c-a846-688a73d051e7)

### Expanded Accordion 
- on click of the link "Need help determining which type of document to file?", open the helper text accordion 
- on click of link again, close accordion 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7d79294a-fe3c-4c4a-a139-7aae13e67e5a)

### Selected Document - Standard 
- if a standard document is selected, display the document name (read-only) below the document category and document name fields 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fafc9987-07fb-4b0d-89ec-b940299a3418)

### Selected Document - Nonstandard A 
- If a nonstandard A document is selected, display the document name (read-only)
- display a document selection dropdown field 
   - dropdown field is required 
    - dropdown will be populated with all documents from the case's docket record
   - dropdown field label will be dependent on the document type (see spreadsheet) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/481d58be-88dc-4873-9472-25831bd3d17a)

### Selected Document - Nonstandard B (with text field) 
-if a nonstandard B document is selected, display the document name (read-only) 
- display a second text field 
   - field is required 
   - text field label is dependent on the document type (see spreadsheet) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1dbaf550-707d-4fc2-b80d-817a6e061692)

#### Nonstandard B (with trial location dropdown) 
- if one of the following nonstandard B documents is selected, 
   - MOTION TO CHANGE PLACE OF SUBMISSION OF DECLARATORY 
      JUDGMENT CASE TO [place]
   - MOTION TO CHANGE PLACE OF TRIAL TO [place]
   - REQUEST FOR PLACE OF TRIAL AT [place]

- display a dropdown field 
  - dropdown list will be populated with the available trial locations based on the 
    case procedure type (small v. regular)
  - dropdown field is required 

### Selected Document - Nonstandard C 
- if a nonstandard C document is selected, display the name of the document (read-only) 

- display a text field 
  - text field is required 
  - field label is "Name" 

- display a dropdown 
   - dropdown is required 
   - dropdown list is populated with all documents in the case's docket record 
   - dropdown field label is dependent on the document type (see spreadsheet) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d1b1ea77-7e12-47ec-84d4-6b18bc61450f)

**Comment by klohman** [comment]
# Document Categorization 

## Document Scenarios 
Different document types have different field requirements. This table shows the different scenarios we identified. 

This story handles Standard documents and Nonstandard A - 
![Screen Shot 2019-03-27 at 12.13.03 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/48992170-446d-4460-be78-7dd1e4ebf461)

### Document Categories and Types 
There are 18 document categories relevant to pro se petitioners who are efiling a document. 
	1. Answer 
	2. Application 
	3. Computation 
	4. Decision 
	5. Miscellaneous 
	6. Motion
	7. Notice 
	8. Opposition or Objection 
	9. Petition
	10. Pretrial Memorandum
	11. Reply Request 
	12. Response 
	13. Seriatim Brief 
	14. Simultaneous Brief 
	15. Statement
	16. Stipulation
	17. Supplement 
	18. Supporting Document 

All document types available to pro se petitioners are listed with their category and scenario in this google sheet: https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing

**Comment by klohman** [comment]
# Updated Designs 3/27/19

## Case Detail Page 

For pro se petitioners, practitioners, and respondent roles:

- Add "File a Document" button to the Docket Record tab on the Case Detail page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/16a58b47-6a65-4da3-a40b-c14741f30a06)

On click of "File Document" button, open the "File a Document" default screen 

## File a Document default screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b4ffe6bc-b4d1-4d2c-94d1-338506266658)

### "Need Help..." Accordion 

On click of the accordion " Need help determining what document category to select?", open the accordion. The open accordion should push down the content below.  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97c8a6e7-59de-482f-b9f8-326743b9455b)

### Selecting a Document 

On page load, the document category dropdown has nothing selected. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/36a0bc5c-962c-4141-87ee-ed24cf215bbb)

- Dropdown is populated with the 18 document categories 
- User selects a document category and clicks "Next, Choose Document Type" button - modal displays 

#### Select Document Type Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5773a669-c588-4f12-a6f3-e2dbcd550cb5)

Document Category field 
* Document Category selected on parent page is selected on modal 
* Field is required 

Document Type field 
* Field is required 
* Document Type is populated with all document types within the selected category 
* If user selects a different document category from the dropdown, the Document Type list should populate with documents based on the category selected 
* List should scroll within the field panel 

Modal Behavior 
* On click of Cancel or Close, the modal should close with no saved changes 
* Modal should NOT close if the user clicks outside of the modal 

Mobile Version of Document Select 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/56693d3f-9c37-4d3a-bb11-fd519d643bd1)

On mobile screens, the modal should be replaced with a separate screen. 
* on click of the document type link, the user should return the File a Document screen with changes saved 

On click of Select, the information is saved, modal closes, and the parent page refreshes

**Comment by klohman** [comment]
# Updated Designs 3/27 (Continued) 

## File a Document Page - When Document Type has been selected 

Once document type is selected, the File a Document page should refresh to display the selected document. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ecacf55e-0ec6-4d6f-a26e-4e01c8f35855)

Selected Document Type field 
* Read-only 
* Displays the text of the selected document type 
* On click of Edit, the modal should open again with document category and document type editable

**Comment by JessicaMarine** [comment]
@klohman These design look good to me.  If nothing else is needed from your perspective, I think it's okay to change to "Ready for Engineering"

**Comment by klohman** [comment]
# Frequently Used Documents 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7cc76f3b-5954-496c-aad0-a806689f9df9)

* Use placeholder text from design for now 
* Actual documents and functionality TBD

**Comment by klohman** [comment]
@JessicaMarine @codyseibert @ericsorenson @rachaelparris @kkoskelin 

# Updated Document Type Selection Flow (04/01/2019)

## Default Screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3135f0d6-7b10-4f45-8f1e-c0782a9ca622)

- On load, display Document Category dropdown field 
- Document Category is a required field 

On select of a Document Category, display the Document Type dropdown field 

## Document Type Field 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a4eb242e-d6c4-4695-b4fd-f8dd668d3cd9)

- Document Type dropdown is populated with the document types for the selected category 
- Document Type is required '
- if no Document Category is selected, hide the Document Type field
