### ISSUE TITLE
Court User: Search for Case by Docket Number or Keyword

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2828]
As a court user of the site, so that I can find cases within the system, I need a place where I can search for and view cases that meet my search criteria.

A Court user have various reasons that they may need to find a case within the system.  The person performing the search may have limited information.  They will need the ability to search for a case by docket number or by a key word search (name).  The system should return all cases matching the search.  If there are no cases that match the search criteria, the system should tell the user that "no results found".

## Acceptance Criteria
* Court users can perform search by a docket number (already done)
* Court users can perform search by keyword (Petitioner's name) search
* Court user should be able to add additional search term or filter by Petitioner's state
* System should display all cases that match the search criteria entered
* Results should display: Docket Number, Case Filing Date, and Case Name
* Search results should display in descending order (newest to oldest) by docket number
* Court user should be able to hyperlink into case through search results
* If no case(s) meet the search criteria, the system should notify the user that "no results found"
* Search results should display both open and closed cases

## Security Considerations
* Does this work make you nervous about privacy or security?
Flagging this story for security review for by CISO due to elastic search. Team has no current concerns. 
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] 1. Global Nav Search UI Updates (Kris #2981)
   - [x] 1a. Sequence & actions connecting "Advanced" link to search page
 - [x] 2. Create Advanced Search Page (Rachael #2981)
   - [x] 2a. Create route at `/search` (Rachael #2981)
     - [x] note: for sake of testing and more, can we allow search terms in query strings in addition to state, such as `/search?name=Smith&yearStart=2017` (etc)? (Rachael #2996)
   - [x] 2b. Create advanced search form for Domestic and International (Rachael #2981)
   - [x] 2c. Create Search Results table & 'no matches' message (Rachael/Kris #2990)
   - [x] 2d. Create computed for formatting search results (Rachael #2993)
 - [x] 3. Update "Search for a Case" (CaseSearchBox) per figma (Rachael #2973)
   - [x] 3a. If no match found, send to "Search Results" page with "no matches found" message and link to advanced (Rachael #2973)
  - [x] 4 Search backend research (Rachael)
  - [x] 5 validate advanced search form (Kris #2998)
  - [x] 6 default to United States in advanced search form (Rachael #3007)
  - [x] 7 hide state field on advanced search form when international country type is selected (Rachael #3007)
  - [x] 8 in the search results table, display only the petitioner name(s) and state which match the user's search - discussion with Kristen 9/9: we're going to show both petitioners and both states in the table (if they are different) (Rachael #3018) 
  - [x] 9 "load more" functionality when there are more than 25 results (set this to 5 for testing) (Rachael #3021)
  - [x] 10 research other search solutions
  - [x] 11 Use DynamoDB streams to populate ElasticSearch index for searching (Team mob #3112)
  - [x] 12 Fix year filed search (Rachael #3139)
  - [x] 13 Fix credentials issue with search endpoint on us-west-1 (Team mob #3164)
  - [x] 14 Change processStreamRecordsInteractor for loop await to a promise.all (possibly) (Rachael #3157)

## Notes:
* The Court's current search functionality can be found at: https://www.ustaxcourt.gov/docket.htm
* For docket number search:
   * Make sure inclusion of leading zeros does not prevent results
   * Make sure inclusion of suffix does not prevent results
* This story does not include the "public" search -- that will be handled in #2839

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
@JessicaMarine 

Questions: 

**Docket Number**
- How are the docket numbers stored (is the year (XXXXX-19) stored as part of the docket number? 
- Allow partial docket number matches? Show multiple results for 12345 (12345-18, 12345-19, etc.)
- Allow exact match without the suffix (L, W, S, etc.) - this is current functionality 


**Petitioner Name** 
- Exact matches 
    - exactly as entered in name field? [Name Name}
    - Do we parse text as separated by space and search? = [David Bryan] OR [Bryan David}?
- Allow partial matches?
    -  [Bob] = returns Bob, Bobby, Bobbit
    - Only allow partial matches for the first letters? [Ash] = Ashford, Ashington NOT Bashful, etc.
- Case sensitive?
- Only query [contactPrimary] and [contactSecondary] ?
    - For example, case “Estate of Ocean Stafford, Deceased, Ferdinand Velasquez, Executor” - Ferdinand Velasquez is not searchable? 

**Multiple Results**
- Always show results in Docket number order? Or is there some relevancy factor? 
- How to handle large result sets? Pagination? Lazy loading?

**Comment by klohman** [comment]
# Preliminary Design Notes 

## 2828 Search Docket Number and Name 

#### Global Nav- Search Bar 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e5f13a58-d153-4134-bf4f-b27def4205d2)


**UI Updates**
* Decrease width of search bar 
* Add placeholder text [ Enter docket number ]
* Add link = “Advanced” 
* On click of “Advanced”, navigate to Advanced Search page 

**Docket Search**
* Exact matches only 
* Format must be [XXXX-YY]
* Accept leading zeros 
* Accept suffix (123-19SL)

#### Practitioner / Respondent Dashboards - Search Widget

￼![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/16770c9c-c0e3-4ee5-9367-a025e0d0ce15)

**UI Updates**
* Decrease width of search bar 
* Add placeholder text [ Enter docket number ]
* Add link = “Advanced Search” 
* On click of “Advanced Search”, navigate to Advanced Search page 

**Docket Search**
* Exact matches only 
* Format must be [XXXX-YY]
* Accept leading zeros 
* Accept suffix (123-19SL)


#### Advanced Search 

￼![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f75c9d3-fad7-4306-9722-67dcc23c33ba)

**Petitioner name**
* Name searches should query fields
    * Name 
    * Secondary-name 
*  Matching results 
    * Full [name] matches only 
    * Name fields may include several [name] [name] separated by space  

**Country**
* Dropdown includes - United States, International 
* Defaulted to “United States” 
* On select of “International” - hide “State” field 
* On select of United States, show State field 
* Country search should query fields 
    * contactPrimary.countryType
    * contactSecondary.countryType

**State**
* Display only when US is country selected 
* Includes full list of states/territories (Same as address form) 
* State search should query fields 
    * contactPrimary.state
    * contactSecondary.state

**Year filed**
* “FromYear” to “ToYear” range 
* Accept years 1986 - current 
* “To” year - cannot be prior to the “From” year 
* Year search query fields 
    * Filed date ??


#### Search Results 
￼
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/25349273-77fd-411d-a588-4f5aac0d6110)

**Result heading**
* Display as format =  “([total number of results]) matching cases”

**Results displayed**
* Display 25 results on search 
* Display button “Load 25 More” below table 
* On click of “Load 25 More”
    * display 25 more results in table 
    * Display “Load 25 More” below table 

**Table Columns**
* Sequence number
    * display ordered number of results 
    * Results are always displayed in docket number order (oldest to newest) 
* Petitioner(s)
    * Display petitioner parties on the case 
* Docket Number 
    * Results are always displayed in docket number order (oldest to newest) 
    * Docket number links to Case Detail page 
* Date Filed 
* Case Name 
* State
    * Display  - contactPrimary.state
    * How to handle two parties with two states?????


#### No Results 
￼
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8e92be76-9cb6-40c3-9ec1-07979aeab108)

* Display header - No matching cases found 
* Display text : “Check your search terms and try again.”

**Comment by uxforgood** [comment]
@kkoskelin I don't see this as a strong use case, and if it is we can add to backlog to handle it.

**Comment by klohman** [comment]
#2828 UX Review 

* If there is an exact match, results should only display the exact match. Currently, any matching case is being displayed - so if you enter “Luke Skywalker” - all the Skywalker matches are shown  

* Advanced search form and results are currently retained when you navigate away from page, but the search term is cleared. We should retain BOTH the search criteria and the results.  We need to add a way to easily clear out the previous search 

* On trigger of Error, we should clear the results: Currently, if you try a new search that triggers an error, the previous search results are still displayed. 


**UX Note**
* Cannot search by non-party names -an  Executor will not be found. I believe this was removed from scope for this story. If we want to implement it for MVP, should probably make a new story.
