### ISSUE TITLE
Member of the Public: Perform Case Search

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2839]
As a member of the public, in order to locate the information I am looking for, I need the ability to search for cases by keyword & docket number.

## Pre-requiste:
* Member of the public (unauthenticated user or authenticated) comes to the site

## Acceptance criteria:
* Member of the public is able to perform a keyword & docket number search (same as #2828)
* Consider including some additional instructional text re: docket number format and clearing docket # when clearing search.  Add whatever design changes are made to internal search as well.
* Only return data that's in the table, nothing else

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Decide if we should use a separate elasticsearch instance (if so, set up) - or maybe a decorator for the response? use current ES instance for now, and we can decide this later (Discussed 11/26/19 - decided on using same elasticsearch instance and index for now unless we can find a compelling reason not to)
- [x] 2 Endpoint for public search (interactor, serverless - separate stack for public, proxy, lambda) (Matt #3706)
- [x] 3 Update search form view and include on public search page (Rachael #3707)
  - [x] 3a Mobile view for search form and results (Cody)
  - [x] 3b Separate sequences and actions for public search
- [x] 4 Remove search capabilities completely for petitioner role (Cody #3703)
- [x] 5 When user hits search on name or docket number in advanced search, the global search in the header should be cleared of any inputs (authed app) (Cody)
- [x] 6 Add router to public build and stub case detail page (Cody)

## Notes: 
* This story is intended to include development of the public-facing part of the system. 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael #3730)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael #3730)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mlissner** [comment]
Hi, I introduced myself and provided a longer comment over on https://github.com/flexion/ef-cms/issues/40, but I wanted to raise the question here as well, as well as share some experience I have with docket search from building CourtListener.com. 

First, I just want to ask/highlight/mention that the `T.C. Memo` numbers should be searchable via this interface. They're important numbers, and the public should be able to look them up. Note that because they are used as references in *other* opinions, just using full text search for these provides pretty bad results. 

As for the technical design of this, I'll just note — and I apologize if you've already worked through this — that it's challenging because you're mixing object types in your search results. People can search for *dockets* and they can do full text search for *documents*. Which type of result you return is tricky! For example, do you return a docket when somebody searches for a phrase in a PDF? That might not be very helpful. Do you return *documents* when somebody searches for a case name? Also not helpful! 

We solved this by grouping results using Solr's grouping operators. So we put *documents* into our search index, and then when those documents are part of a response, we group the documents by docket, and indent the results. [Here's an example][ex1]:

![Screenshot from 2019-11-07 13-33-41](https://user-images.githubusercontent.com/236970/68429586-3b823300-0163-11ea-84e6-5af6c8e69e70.png)

So that shows two *dockets* each of which has numerous responsive *documents.*

I hope this helps. I think I saw you're using elastic search, but if it's helpful to see how we do this with Solr (it ain't pretty), our code is open source, and I can dig up a link. 

Thank you again for your work on this important project! 

Mike

[ex1]: https://www.courtlistener.com/?type=r&q=unicorn

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d200c7a7-a5d6-4957-a5a5-7863fc7f330a)

## Docket Search 
* Exact matches only
* Format must be [XXXX-YY]
* Accept leading zeros
* Accept suffix (123-19SL)


## Search by Name 
**Petitioner name**
* Name is required field for search (user cannot search ONLY by state, country, or year)
* Name searches should query fields
  * Name
  * Secondary-name

Matching results
* Partial word match (So a search for "Bob" would match results for Bobby, Bobbie, Bob's, etc)
* Name search might include multiple words, like "Bob Marley," which would only net results that have both those in them (matches could include "Bobby Marley," "Bobby Marleyville" etc)

**Country**
* Dropdown includes - United States, International
* Defaulted to “United States”
* On select of “International” - hide “State” field
* On select of United States, show State field
* Country search should query fields
  * contactPrimary.countryType
  * contactSecondary.countryType

**State**
* Display only when US is country selected
* Includes full list of states/territories (Same as address form)
* State search should query fields
  * contactPrimary.state
  * contactSecondary.state

**Year filed**
* “FromYear” to “ToYear” range
* Accept years 1986 - current
* “To” year - cannot be prior to the “From” year
* Year search query fields
  * Filed date

**Comment by mlissner** [comment]
Sorry to raise this again, but is there any plan to have the `T.C. Memo` numbers indexed for search? Doesn't look like it from your prototype?

**Comment by klohman** [comment]
### 2839 Test Scenarios 

Test Data 
* Case 1 
    * Docket number xxx-xx 
* Case 2 
    * Petitioner : Luke Skywalker 
    * State - TX
    * Year filed - 2018
* Case 3 
    * Petitioner : John Skywalker
    * State - MD
    * Year filed - 2019
* Case 4 
    * Petitioner - Leia Skywalker 
    * State: TX
    * Year filed - 2019
* Case 5 
    * Petitioner - Harry Updike 
    * State - TN
    * Petitioner - Sue Updike 
    * State - NY
* Case 6 Petitioner - John Updike 
    * State - NY
    * Case Status - Closed 
* Case 7  Petitioner - Sam Updike 
    * International - Argentina 
* Case 8  Petitioner - George Updike 
* Case 9  Petitioner - Ulysses Updike 
* Case 10  Petitioner - Roger Updike 
* Case 11
    * Party type - Estate with Executor ..
    * Decedent Name - Steven Ochoa
    * Executor Name - Taylor Whitaker


#### 1) User searches for docket number with exact match
* Login as docketclerk1
* Search for Case 1 
Expected Results
- [ ] User is taken to docket xxx-xx

#### 2) User searches for docket number with no matches
* Search for “104”
Expected Results
- [ ]  User sees new “No matches found” page

#### 3) User searches for petitioner name with single, exact match
* Click on “Advanced search” link
* User sees “United States” defaulted as selection in Country
* Enter “Luke Skywalker”in Petitioner name field
* Click Search button
Expected Results
- [ ] user sees case detail page for Case 2 

#### 4) User searches for petitioner name with under [5] multiple matches
* Click on “Advanced search” link
* Enter “Skywalker”in Petitioner name field
* Click Search button
Expected Results
- [ ] User sees search result for “Skywalker” with 3 matches (Case 2, 3, 4) 
- [ ] User sees search term retained in search field

#### 5) User searches for petitioner name with over [5] multiple matches
* Login as petition clerk
* Click on Advanced Search
* Enter [Updike] in petitioner name field
* Click search
* Click “Load 5 More” button
Expected Results 
- [ ] User sees search results for “Updike” with 6 matches 
- [ ] Cases 5-9 display in table 
- [ ] User sees search term retained in name field
- [ ] User sees button “Load 5 More”
- [ ] On click of “Load 5 More”, Case 10 matches display in search results table and “Load 5 More” button is hidden

#### 6) User searches for petitioner name and state with multiple matches
* Click on “Advanced search” link
* Enter “Skywalker”in Petitioner name field
* Select "TX" from state dropdown
* Click Search button
Expected Results
- [ ] User sees search result for “Skywalker” in TX with 2 matches (case 2 and Case 4) 
- [ ] User sees search terms/selections retained in search field

#### 7) User searches for petitioner name and international with matches
* Click on “Advanced search” link
* Enter “Updike” in Petitioner name field
* Select International from country dropdown
* Click Search button
Expected results 
- [ ] User sees search results with 1 matching result (Case 7)
- [ ] Search terms are retained in fields 

#### 8) User searches for petitioner spouse’s name and state with matches
* Click on “Advanced search” link
* Enter “Harry Updike”in Petitioner name field
* Select NY from state dropdown
* Click Search button
Expected Results
- [ ] User sees search results with 1 matching result (Case 5)
- [ ] Search terms are retained in fields 


#### 9) User searches for petitioner name by [executor name] with matches
* Click on Advanced search
* Enter “Whitaker” in Petitioner Name field
* Search
Expected results 
- [ ] User see search result for “Whitaker” with 1 match- Case 11

#### 10a) User searches for petitioner name and year with matches
* Click Advanced Search
* Enter “Skywalker” in petitioner name field
* Enter year filed “2017” to “2018”
* Search
Expected results 
- [ ] User sees search results for 1 case (Case 2) 

#### 10b) User searches for petitioner name and year with matches
* Click Advanced Search
* Enter “Skywalker” in petitioner name field
* Enter year filed “2019” to “2019”
* Search
Expected results 
- [ ] User sees search results for 3 cases (Case 3-4)  


#### 11a) User clears search results 
* Scenario 10b
* Click “Clear Search” button in “Search by Name” section
Expected Results 
- [ ] All fields under Search by Name are empty 
- [ ] Results are hidden 

#### 11b) User clears search results 
* Scenario 2
* Click “Clear Search” button in “Search by Docket Number” section
Expected Results 
- [ ] Docket number field is empty 
- [ ] Results are hidden 

#### 12) User searches with blank petitioner name field
* Click Advanced Search
* Select “Alabama” as state
* Click search
Expected results 
- [ ] Error is trigger on petitioner name field 

#### 13) Users sees search results sorted by docket number
* [scenario 5]
Expected results 
- [ ] Search results display in order of docket number (oldest to newest)

#### 14) User can access case from search results
* Scenario 4
* Click on Case 2
Expected results 
- [ ] User navigates to Case Detail for Case 2

#### 15) User sees results for open and closed cases
* Scenario 5 
Expected results 
- [ ] Search results includes Case 6 (case status = closed)

**Comment by klohman** [comment]
## Mobile Views 

#### Default View - Search by Name 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bca6c270-ce38-4576-a9c7-845ee747c5f4)

* Docket Search and Name Search treated as tabs, controlled by dropdown 
* Search by Name is selected by default 

#### Search by Docket 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dea0eb8a-19db-4703-879d-0fb489cc710e)

#### Search Results 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1612af93-660c-462b-9d36-88ea2e4a9459)

* Display results below search fields 
* Hide these columns from mobile search results 
  - Petitioner Name 
  - State

**Comment by mlissner** [comment]
This *looks* great, but I'm still wondering if the citations (`T.C. Memo` and the like) will be searchable. They're very important pieces of metadata for people that are actually practicing in the court. 

I've raised this a few times now...is there any internal deliberation happening around this, perhaps? This ticket is flagged as "Member of the Public" — I think that means me? A response would be really appreciated.

Thank you.

**Comment by mlissner** [comment]
Great to hear, @JessicaMarine. Thank you for the update! If there's a way I can be looped into that issue as well, I'd really appreciate that (though I can't think of a good way except for creating the stub for that story now). Thank you again.

**Comment by waldoj** [comment]
I'll try to remember to tag you in when that story is added to the backlog, @mlissner.
