### ISSUE TITLE
Court Users: Ability to sign a court-issued document

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#2875]
As a Court User, in order to easily sign a document whenever I need to, I need the ability to apply a signature to a document in any case at any time.

## Pre-Conditions
Internal User is in a case.

## Acceptance Criteria
* All Court Users need the ability to apply a signature to court-issued document and stipulated decisions while it's being created or in draft state
* Court User can reapply the signature if they placed it incorrectly
* Court User can cancel signature process
* Court User can preview the document with the signature
* Case services (docket, petitions, calendar, sr attorneys) have access to only the Chief Judge's signature
* Chambers has access to only their Judge's signature
* All signed documents should end up in the Draft folder
* Sending a message with the signed document is optional (change signed stip message to optional as well)
* User has the ability to edit the original document and reapply the signature

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* We need to retain the original draft of the document so the user has the ability to edit the doc without a signature.

## Tasks
 - [x]  Refactor PDFSigner Component (Matt #3183)
 - [x]  Load order into signer (Matt #3194)
 - [x]  Save signed order (Matt)
 - [x]  Add signature added column to draft docs table (Cody #3178)
 - [x] Editing this document - remove signature modal (Cody #3186)
 - [x] Remove signature on document details page, button and modal (Cody)
 - [x] Apply signature button on doc detail page (Cody)
 - [x] Signature added alert message

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Jojo #3226)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody #3211)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Jojo #3210)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo #3210)
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
As a Court User, in order to provide final authorization of an order, I need the ability to add a judge's signature to a system-generated order.

## Pre-Conditions
* An order or decision has been generated in the system and is in draft state

## Acceptance Criteria
* A Court User can apply an electronic signature of the Chief Judge anywhere on the Order or Decision
* Court User can reapply the signature if they placed it incorrectly
* Court User can cancel signature process
* Court User can confirm signature
* Court User MUST generate a message to another court user during the signature process
* Message should that appear on the doc detail page, and in the sender's sent box
* Once signed, the draft document is viewable by all internal users, but not public or parties in the case.
* After the signature is applied, court user needs the ability to correct the document and reapply the signature if there's an error (IS THIS THE RIGHT PLACE FOR THIS AC?)

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 11.35.30 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/f6236a68-be8b-44df-9b51-aeede86af779)

**Comment by alsmith1** [comment]
[Uploading... Screen Shot 2019-10-02 at 11.35.40 AM.png ]

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 11.35.56 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/05c57a19-534b-4d54-ba25-273a5d6346b3)

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 11.36.12 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/cdfe8e4d-c029-4a8e-aabd-7d935ab36f5d)

**Comment by alsmith1** [comment]
## Test scenarios

#### Scenario 1 - Court Users need the ability to apply a signature to court-issued document and stipulated decisions while in draft state
1. log in as petitions clerk
2. navigate to draft documents
3. Click on document link under Filings and Proceedings 
4. Click on Apply Signature  and place signature 

Expected result
- [x] See Orders needed summary page listing all orders that were checked on petition qc
- [x] See success message for petition batched for IRS
- [x] Orders are listed in alpha order

**Comment by alsmith1** [comment]
[Uploading... Screen Shot 2019-10-02 at 12.36.05 PM.png ]

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 12.36.16 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/ce597bcc-034d-4da9-bfe1-e7fdd58074ed)

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 12.36.24 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/549d8bef-0fb8-46ac-9fca-4a2f62f4cdae)

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 12.36.33 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e1288bbd-5b3c-4b5c-a753-3fd64672f619)

**Comment by alsmith1** [comment]
[Uploading... Screen Shot 2019-10-02 at 12.36.42 PM.png ]

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-02 at 12.36.50 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/14af886e-9697-4db2-8b6c-b239182e0c74)
