### ISSUE TITLE
Parties: Review, Submit, and Confirm File Upload

### ISSUE THREAD

**Issue by tjcurington** [flexion/ef-cms#302]
As a Petitioner, Practitioner and IRS attorney, in order to make sure I complete the eFiling process and successfully file my document, I need to review, submit, and confirm file upload.

To avoid a Party uploading the wrong document, or not providing accurate information about the document to be filed, the Party should be able to review the document and all data before submitting to the Court.  Upon submission to the Court, the Party should be able to confirm the document was properly uploaded by viewing it on the docket record.

## Pre-Conditions:
* Party has selected a document type and uploaded a file
* Party has entered all required information
* Party indicates they want to file the document

## Acceptance Criteria:
* Party can review the uploaded .pdf document and all other data provided before filing it
* Party can submit/file the document in the selected case
* Party sees success message
* Party can view and access it on the docket record upon submission
* If a supporting document is provided in support of the primary document, that supporting document should appear on the docket record as a separate docket entry.
* If a secondary document is provided (in the case of a Motion for Leave or Motion for Leave to File Out of Time), the secondary document must display on the docket record as a separate docket entry.
* If a supporting document is provided in support of a secondary document, that supporting document should appear on the docket record as a separate docket entry.
* When external filing(s) are submitted/filed in a case, a new work item should be created on the Docket Section work queue and be viewable as a pending message in the case detail and document detail pages.

Notes:
* There is the possibility that a single transaction could result in up to 4 docket entries: main document; supporting doc for main doc; secondary doc; supporting doc for secondary doc.

## Tasks
Design:
- [x] Design review screen [Sarah]
- [x] Create docket record view with success state [Sarah]

Code:
- [x] 1. Create review view (Rachael #1388)
- [x] 2. Create fileExternalDocument interactor to upload documents to S3 (Rachael #1390)
  - [x] 4. Create submit sequence to call fileExternalDocument (William #1403)
- [x] 3. Create service endpoint/ interactor that updates Case and Docket Record with uploaded documents (William/Cody #1403)
- [x] 5. Create modal for cancel button (kris/Rachael #1386)
- [x] 6. Fix service date bug on FileDocument form - after all data is entered and you click the review button, there is an error that service date is not entered; click in one of the date fields and unfocus it and the error goes away (William #1393)
- [x] 7. Fix date format on service date on review screen to match design (MM/DD/YYYY) (Rachael/Kris #1399)
- [x] 8. Update review screen with updated document type labels and file icon (in tech channel on Slack) (Rachael/Kris #1394)
- [x] 9. Load data from state on FileDocument form (for Edit functionality from FileDocumentReview page) (Cody/Rachael #1404)
- [x] 10. Show Success Message on completed upload. (William / Cody #1403)
- [x] 11. Add Work Item for each uploaded document (William / Cody #1403)
~~12. Verify saved metadata for primary document~~ Handled by #937
- [x] 13. Verify supporting document title generation (Rachael #1406)
- [x] 14. Address that gotoCaseDetailSequence runs clearAlertsAction which doesn't allow alert message to show up. (Kris #1414)
- [x] 15. Clean up old code/tests for respondents filing documents (the "old way") (Rachael #1411)
  - [x] Update respondent case journey tests with new sequences (Rachael #1411)
- [x] 16. Case journey test for filing a document from start to finish (this was started on a previous story - petitionerFilesADocument.test.js) (William #1417)
- [x] 17. [Updated Exhibits/Attachments/Certificate/ Objections Section](https://github.com/flexion/ef-cms/issues/302#issuecomment-484152030) (Rachael #1418)
- [x] 18. Ensure supporting-document metadata is cleared when "no" is selected (Kris, William #1420 )
- [x] 19. [UX Review Items](https://github.com/flexion/ef-cms/issues/302#issuecomment-484593903)
  - [x] 19a. Loading overlay to show progress and stop multiple submissions. (William #1435)
  - [x] 19b. Supporting Documents - We need to show the selection if they say no to supporting documents - display under “Filing Does Not Include” (Rachael #1438)
    - [x] 19ba. This should occur for Secondary documents as well. (Rachael #1438)
~~19c. Docket entries not ordering correctly - -Docket Number: 802-19W (Rachael)~~ can't recreate
  - [x] 19d. secondary document for Motion for Leave to File is optional, yet when i submitted the form without uploading a secondary document - app broke (white screen) (William/Kris #1436)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required) (Rachael #1423, Kris #1422)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by tjcurington** [comment]
This is placeholder and needs to be integrated into a larger scenario.

**Comment by sarahridgway** [comment]
Test comment

**Comment by sarahridgway** [comment]
Designs approved by Jessica on 3/29/19
Ready for Engineering

*Review Filing*

- User has clicked "Review Filing" button from Filing Form (#980)
- User may review filing information before submitting the filing to the Court

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/cd29368e-72f2-4740-999e-d8f1f3c517ba)

*Document / PDF Review*

- Review form shows user compiled document names
- User may click on hyperlinked document name to open the uploaded PDF in a new window / tab

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/258a1045-e535-4bd4-93d8-d0343df92b80)

*Edit*

- All "Edit" buttons return the user to the top of the Filing Form with all data pre-loaded

*Submit* 

- "Submit Filing" button commits the filing to the case

* Cancel / Abandon Funnel*

- Clicking "Cancel" button will invoke the confirmation modal
- Clicking away from the Filing funnel (such as the docket number link, back button, or global navigation) will invoke the confirmation modal

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/f91a28e9-300f-44a5-b39c-06fb9b16bd05)

*Docket Record*

- User has clicked "Submit Filing" button on Review Filing page
- Success message is displayed
- Uploaded files are committed to the docket record (see #937 for docket entry format)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/b3a861b3-5ae2-4c25-b392-108f75f9a2b2)

**Comment by sarahridgway** [comment]
Please note that "Exhibits" and "Attachments" (as shown in the above wireframes) should display on the UI as "Exhibit(s)" and "Attachment(s)"

**Comment by sarahridgway** [comment]
*Edit - Return to Form*

User has clicked on an "Edit" link and returns to the form 

- All entered data has been retained and fields are pre-filled
- Selected file data has been retained

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/5e5ff374-72e4-4a94-b42a-83fce120dced)

**Comment by sarahridgway** [comment]
Updated above wireframes to remove pdf links.

**Comment by klohman** [comment]
## Updated Exhibits/Attachments/Certificate/ Objections Section 

- If ‘yes’ for exhibits/attachments /certificate

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1162ed49-3765-430b-84c5-bde99bc66971)


- If ‘no’ for exhibits/attachments /certificate

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/53c550c2-4b96-4309-92c4-ce3cd3d5e549)

- If ‘yes’ and ‘no’ for exhibits/attachments/certificate

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/70da4f2c-5b39-44ad-a934-e3cf3729498d)

### Objections 

- Show objections fields ONLY when document type requires it (i.e. all motions and Application to Take Deposition)

**Comment by klohman** [comment]
@rachaelparris @kkoskelin @wbyoko 

**UX Review Notes**
* Supporting Documents - We need to show the selection if they say no to supporting documents
- If they select ‘no’- display under “Filing Does Not Include” 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cbf763e2-a1de-48a3-a0b5-6f70e8df0ad4)

- If they select ‘ yes’ for supporting document, leave as is 

**Docket Record**
* Seeing multiple entries for each document when I submit -Docket Number: 802-19W
* Docket entries not ordering correctly - -Docket Number: 802-19W
* Was able to submit two filings and they did order correctly on record - Docket Number: 821-19

**On Submit**
- When I click submit- nothing happens for a while (10 secs) and there is no loading/progress indicator 

**Secondary Document**
- secondary document for Motion for Leave to File is optional 
- when i submitted the form without uploading a secondary document - app broke (white screen)
- if they do not attach a secondary document, the primary and any primary supporting documents should be submitted, but there should be NO docket entry for the secondary document **per Jessica 04/18/2019**
