### ISSUE TITLE
Court User: Creating a case on behalf of paper-filing petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#311]
As a Court User, in order to start a new case for a paper-filed Petition, I need the ability to create a new case in the System.   

When a Petitioner submits a Petition in paper form, an internal Petitions Clerk must upload that Petition into the CMS.  This includes entering all contact information and case metadata, as well as uploading any documents provided by the Petitioner.  Once the internal Court User is done entering everything, the case should be treated just as if an external filer uploaded the Petition electronically.

## Pre-Conditions
* Court User is logged into the System

## Acceptance Criteria
* Court User must be able to indicate that they are starting a case for a Petitioner
* Court User must enter all contact information for Petitioner
* Court User must enter all case metadata for the Petitioner
* Court User must upload any required documents for the Petitioner
* Court User must be able to overwrite date that petition was received by Court for case creation/document upload
* System must store that this case was started as a paper petition (metadata stored for later reporting needs, but not displayed in UI)
* Court User must be able to confirm that a new case has been successfully started for a Petitioner
* When the case is created in the system issues the next sequential docket number
* When an internal user (Petitions Clerk or Docket Clerk) starts a new case from a paper petition, the new case is added to the user's work queue and to the user's section work queue as a work item.  The work item should be assigned to the internal user who started it.
* The work item in the individual queue and section queue should contain the following message: "Petition filed by [Petitioner's name -- everything before the v. in the caption] is ready for review."

## Notes
* Same interface as petitioner except doesn't need notifications and warnings

## Tasks
- [x] Design: Update petition's clerk dashboard
- [x] Design: Modify form design
- [x] Design: Update case info tab on case detail page
- [x] Code: Add "Create a Case" button to petition clerk dashboard/work queue (William #1219)
- [x] Code: Create "Create a Case" page for internal users (William #1236)
- [x] Code: Sequence and Tests for Petition from Paper (William #1232)
- [x] Code: Reduce validation requirements for a Petition Clerk on the Start a Case page (Kris & Eric #1221)
- [x] Code: Interactors, Lambda, Swagger (Eric #1231)
- [x] Code: Interactor tests (Cody)
- [x] Code: Update Petition QC Document Info tab for paper petitions (add Date Received, etc.) (Rachael #1228)
- [x] Code: Add ability for Docket Clerk to Start a Case in the same manner. (Rachael #1233)
- [x] Code: Interactor for Uploading files when submitting a Petition without Paper (Eric #1236)
- [x] Code: UI Integration
- [x] Code: make file selection icons consistent (Rachael)
- [x] Code: fix createdAt time
- [x] Code: take the user directly to document detail after case is created (William #1240)
- [x] Code: add isPaper and dateReceived to Case entity and store that info when case is created (Rachael, Cody #1243)
- [x] Code: add work item for user who created the case (Rachael, Cody)
- [x] Email of Internal User showing for Primary Contact on case detail page (Rachael)
- [x] Size of Caption Field changing in error state (Rachael)
- [x] Fee Payment Date Not Displaying when "Batched for IRS" (Rachael)
- [x] Notice /Case Type not showing in read-only view or case info tab (Rachael)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by uxforgood** [comment]
## Petition's clerk dashboard

- Add "Start a Case" button that takes user to the Start a Case form for internal Court users

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/447ce198-b66e-4576-bcb0-67588318cb2f)

## Start a Case form

Internal Court users will see a modified view of the start a case form that petitioners currently see. 

- Remove "All fields required" text
- Remove all hint text (yellow boxes) 
- Change "Upload Your Petition to Start Your Case" heading to "Petition Documents" 
- Add "Date Received" fields
- Change "Upload Your Statement of Taxpayer Identification" heading to "Statement of Taxpayer Identification" 
- Change "Who is Filing This Case" heading to "Party Information" 
- Replace "filing on behalf of" radio button groups with a single dropdown that contains all possible party types (will note in a separate comment)
- Same logic around ODS upload remains - only show this field if the corporation party types are selected
- For party information, change all headings that reference the petitioner such as "Tell us about yourself as a ..." (will provide specific changes and list in separate comment) 
- 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/6977fd29-04a2-4dc2-b32b-fc96d7ef90a6)

**Comment by uxforgood** [comment]
@JessicaMarine please correct if any of these are incorrect for how we want them to appear in the dropdown. 

We talked about using Married Couple instead of Petitioner & Spouse since they are both petitioners. If we do that, engineers will need to map that entry so it shows as "Petitioner & Spouse" on the Case Information tab of the case detail page. @ericsorenson 

## Party types list for internal court users

* Petitioner
* Married Couple  
* Corporation
* Partnership (as the Tax Matters Partner)
* Partnership (as a Partner Other Than Tax Matters Partner)
* Partnership (BBA Regime)
* Estate with an Executor/Personal Representative/Fiduciary/etc.
* Estate without an Executor/Personal Representative/Fiduciary/etc.
* Trust
* Conservator
* Guardian
* Custodian
* Minor (Without a Guardian, Conservator, or other like Fiduciary)
* Incompetent Person (Without a Guardian, Conservator, or other like Fiduciary)
* Surviving Spouse
* Petitioner and Surviving Spouse
* Transferee
* Donor

**Comment by uxforgood** [comment]
@JessicaMarine LMK if this is incorrect... 

## Type of Case Dropdown list

This is for the internal users and is what should show on the Case Information tab of the case detail page as well. 

* Deficiency
* CDP (Lien/Levy)
* Innocent Spouse
* Partnership (Section 6226)
* Partnership (Section 6228)
* Partnership (BBA Section 1101)
* Whistleblower
* Worker Classification
* Declaratory Judgment (Retirement Plan)
* Declaratory Judgment (Exempt Organization)
* Passport
* Interest Abatement
* Other

**Comment by uxforgood** [comment]
## Content changes for contact info for each party type 
This is how this petition's clerk text differs from the petitioner's start a case form based on the party type that is selected. 

### If Petitioner is selected... 
- Change "Tell Us About Yourself" to "Petitioner Information" 

### If Petitioner and Spouse is selected... 
- Change "Tell Us About Yourself" to "Petitioner 1 Information" 
- Change "Tell Us About Your Spouse" to "Petitioner 2 Information" 

### Petitioner and Deceased Spouse... 
- Change "Tell Us About Yourself" to "Petitioner Information" 
- Change "Tell Us About Your Deceased Spouse" to "Deceased Spouse's Information"

**Comment by JessicaMarine** [comment]
You can do it as either “Married couple” or “Petitioner & Spouse”. I don’t feel strongly either way and I think Petitions will understand what it means.

**Comment by JessicaMarine** [comment]
This looks good.

**Comment by JessicaMarine** [comment]
This looks good to me.

**Comment by klohman** [comment]
@JessicaMarine Updated designs for internal case creation 

## Petition's clerk dashboard

- Add "Create a Case" button that takes user to the Create a Case form for internal Court users

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b27dcaa2-02d1-456e-8be8-6786ee6a4193)

## Create a Case form

Internal Court users will see a form to upload documents to create a case. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/49a06e7b-85d5-4baf-a30f-011e6301c439)

Required Fields 
- Date Received 
- Case Caption 
- Upload Petition 

All other fields are optional. 

Field-level validation for correct date inputs and not being in the future are for:
- Date Received

On click of Cancel button - discard all uploads and return user to their work queue. 

On click of Create Case button:
- the new case is assigned the next sequential docket number
- the new case is added to the user's work queue and to the section work queue showing assigned to the user
- the new case is flagged as a paper petition (does not show in UI)
- the user is taken directly to the Document Detail page for the new petition 

## Document Detail Page 
- caption displayed is the caption manually entered from previous page 

### Date Received 
- Add Date Received field to the Case Info tab 
- Date received field is only displayed for paper petitions 
- Date received will be pre-populated with date entered in previous page but is editable 
- Date must be in correct format and cannot be in the future 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97e35685-1e45-4d4c-bf22-74e39dd8bfc4)

### Ownership Disclosure Statement 
For party type of  Corporation, Partnership (Tax Matters Partner), Partnership (other than Tax Matters Partner), and Partnership (BBA Regime): 

Display Ownership Disclosure Statement field 
- if the ODS was uploaded on previous screen, display link (same functionality as on electronic petitions) 
- If no ODS was uploaded, show "No file uploaded." message. 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/41840832-8ced-4bb7-ab5b-157b3c657820)

**Comment by mariahkannenberg** [comment]
Per slack ustcux  discussion with Rachael and Jessica on 3/27 @ 4:21 p.m.

 - When petitions section creates a new case for a paper-filing petitioner, new case is added to the user's work queue and to the petitions section work queue

**Comment by klohman** [comment]
@rachaelparris 

# UX Review Notes 

### Email of Internal User showing for Primary Contact 
* Email of the internal user who created the case is displaying under Primary Contact - for paper petitions, no email should display 

![Screen Shot 2019-03-29 at 8.43.56 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f2687b20-2446-4fd3-937b-c746a2fa44a5)

### Size of Caption Field changing in error state 

![Screen Shot 2019-03-29 at 8.26.26 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/012c442d-0785-47c1-9986-509b8debcb8d)

(not related to this AC) 
### Fee Payment Date Not Displaying when "Batched for IRS" 
- correct payment date displays in docket record 
![Screen Shot 2019-03-29 at 8.34.24 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2d28da3b-96bd-444b-bdfa-45b051a24f1b)

- no date is showing on Petition Document Detail page in read-only state
![Screen Shot 2019-03-29 at 8.37.26 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/05e3c0ed-d639-414a-bc6f-42fe59c17404)

### Notice /Case Type 
- case type not showing on Document Detail when in read-only mode or on Case Info tab 

![Screen Shot 2019-03-29 at 8.41.30 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/079f2eaa-4f76-40bf-9e84-ec7d1407f14a)

![Screen Shot 2019-03-29 at 8.43.15 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1bde1839-4a84-4449-b497-cdc9240fe0ea)

**Comment by mariahkannenberg** [comment]
### Petitions Clerk - Time showing up instead of date in inbox received field. Happening in section queue as well. 
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/270c27bc-022f-4ae4-aaec-40db820e78b3)
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/d83ca6cc-4352-4f28-a800-d17489262023)

**Comment by JessicaMarine** [comment]
PO review comments:
1. The flow is off.  We need to "Start/Generate the case" only after *ALL* of the information is in.  When a Petitions Clerk is changing the caption of case type on the QC screen, it should not auto-generate docket entries summarizing the changes.  They are basically doing data entry at this point, and could need to correct it before the case data is corrected.  This is different from when the Petitions Clerk is reviewing and correcting a case that has already been created electronically by a Petitioner.

**Comment by JessicaMarine** [comment]
I believe the idea is that if it came in today, it would display the time.  But, after that day has passed, it would roll to the date of receipt.
