### ISSUE TITLE
UX Usability Tests

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3111]
On September 17-19, 2019, the UX team conducted on-site usability tests with various user groups: Petitions, Docket, Calendar, Judges, IRS and Petitioners. https://docs.google.com/presentation/d/1dRmjUKiWYvdZAgxsXNvnXT_JGm8_H_PQey_u7oEIsVM/edit?usp=sharing

The output of those tests are captured here.

#### ACCEPTANCE CRITERIA: New MVP Recommendations: 
* [x] 1) Add case status, sender to Judge’s messages inbox (MVP - New)- (Amy) (Matt #3228)
* [x] 2) Add Application for Waiver of Filing Fee as document included during case creation (MVP -New)- (Amy) (Matt #3232)
* [x] 3) Add “Batched By” information to the Petition QC Section Served tab (MVP - New) - (Amy) (Cody #3234)
* [x] 4) Update language and priority of the “Add Batch” action; options include updating language to “Start Scan” or “Add Document”, changing the style to a primary button, co-locating the action with the scan selector (MVP - New) - (Amy) (Cody #3234)
* [x] 6) Update language and consider changing visual treatment of the session detail toggle to clarify that this will open the official (complete) trial session case list (MVP - New) - (Kristen) (Cody #3235)
* [x] 7) Include printable receipt for all document filings, with unique identifier (MVP - New) - (Kristen) (Matt)
* [x] 8) Add helper text regarding typeahead to Document Type field (MVP - New) - (Kristen) (Cody #3243)
* [x] 10) Change the “Additional Info” fields on the Add Docket Form to text area fields to allow more visible characters (MVP- New) - No design (Rachael #3246)

BELOW NOT IN THIS STORY________

#### MVP - New Stories Needed
* Additional testing for filing a petition with pro-se petitioners (#3286)
* Update the list of trial statuses to include statuses that are meaningful and beneficial to judges prior to calendar call (#3287)
* Consider a redesign of the Case Detail page after core functionality is implemented (#3288)
* Add functionality for flatbed and two-sided scanning (MVP- New) - No design (#3290)
* Redesign message view on Document Detail screen to prioritize the selected message; allow access to other user messages as a secondary action (#3306)

#### MVP - Add to Existing Stories 
* Consider wayfinding queues for workflows with deeper structures; considering breadcrumbs, in-app “Back” functionality, etc. (#1925)
* Add indicator for docket entries that are awaiting QC; these could be treated the same or similar to   incomplete docket entries ( #991)
* Allow users to mark if a case has been reviewed and is ready to set for trial; show indicator cases that have been reviewed versus cases that are awaiting review (#1925)
* Allow users to remove cases that should not be set for trial from the eligible cases list; this could be automated based on case status (#1188, #1196)
* Allow visibility into when trial notices should/will be sent, and indicators for sessions that have been issued notices  (#1193)

#### Post-MVP - New Stories  (#3291)
* Add tooltip for icons (Post-MVP - New Story)
* Consider draft-state/in-progress state for petitions where QC has been updated (Post-MVP - New Story)
* Add ability to sort messages by read/unread (Post-MVP)
* Add direct “Reply” ability to messages (Post-MVP)
* Retain data in contact information fields when party type is changed (Post-MVP)
* Add a general summary screen with all petition information (and orders needed) prior to adding to batch (Post-MVP) 
* Add details on what is included in the petition batch: other documents included with petition, number of pages within each document (Post-MVP)
* Update the scan review panel to show a scrollable list of thumbnails for scanned pages (Post-MVP)
* Add ability for user to enter the expected number of pages a scan should contain (to verify the scan is complete) (Post-MVP)
* Investigate need for multiple document scans and individual page deletion/replacement. While this was expressed as a concern by all users,  their stated QC process does not indicate an actual need for these features. (Ongoing- Post-MVP) 
* Consider adding the timeliness date (date the petition was due) along with the IRS Notice date (Post-MVP)
* Add additional sort and filter options for the docket record (Post-MVP)
* Add tooltip for icons (Post-MVP)
* Allow users to more easily navigate between documents on the docket record, without having to go back to the Case Detail and select another document (Post-MVP)
* Add known court addresses to database to support prepopulation of trial locations (Post-MVP)
* Provide easy access to court contact information for external users (Post-MVP) 
* Add service information where relevant in the File a Document form; consider including it with the filing parties or COS (Post-MVP)
* Include additional instructions around supporting documents on File a Document form  for external users (Post-MVP) 

#### Post- MVP - Add to Existing Stories 
* Include pending motions on Judge’s Dashboard (#2764)
* Allow users to customize the Working Copy by additional sort and filter options (#2767)
*Allow judge users to select their note privacy preferences and opt in/opt out of sharing notes with other users (#338)
* Indicate on external dashboard  if a case has deadlines and if case has been set for trial (#534)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
Item 1) Add case status, sender to Judge’s messages inbox ![Screen Shot 2019-10-08 at 10.23.23 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7b256523-6a7a-4dc9-862f-83cbc23a4763)

**Comment by alsmith1** [comment]
4) Update language and priority of the “Add Batch” action; options include updating language to “Start Scan” or “Add Document”, changing the style to a primary button, co-locating the action with the scan selector ![Screen Shot 2019-10-08 at 10.27.37 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/f07d1093-cbcb-4936-84c9-76cd91cdc06e)![Screen Shot 2019-10-08 at 10.27.45 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/1aaabd4e-8777-4ef0-b4a8-37e7ab381541)![Screen Shot 2019-10-08 at 10.27.55 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e375b777-e08d-4991-bba3-c639f3aeb720)

**Comment by klohman** [comment]
#### AC- 6

**Session Working Copy**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/07cbe8fe-6c45-4f39-86d6-a397533ba16a)

* Update page title to include Judge's name - format is "[Judge Name] - Session Copy"
* Update link text to "View All Session Info" 
* On click of "View All Session Info" - open standard Trial Session Detail screen 

**Trial Session Detail**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57a15feb-7e8f-4c5e-8eb2-6da82e5581e0)

* Update link text to "View Judge Session Copy" 
* On click of "View Judge Session Copy" - open assigned Judge's Working Copy of session
* "View Judge Session Copy" is only visible to the assigned judge 


#### AC - 7 

* Applies to all external filings electronically submitted 
* Upon submission of electronic filing, app navigates to Case Detail with success message displayed

**Updated Success Message**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/18544f6e-a483-45ff-b7de-d432a5ecc396)

* On click of "print a receipt" link, open Receipt PDF in new tab

**Printable Receipt PDF**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bac9eb39-f410-49df-8d3c-0ffd63bed7ee)

#### AC- 8 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a0f846a7-23ef-400a-b71b-49c999a79089)

* Add helper text to "Document type" field (all instances)

**Comment by alsmith1** [comment]
## Test scenarios

#### Scenario 1 - Case status, sender added to Judge’s messages inbox
1. log in as a Judge
2. On the Dashboard Recent Messages table confirm Case status and From have been added to the table after Document

Expected result
- [ ] Case Status Column has been added to the table
- [ ] From Column has been added to the table

#### Scenario 2 - Application for Waiver of Filing Fee as document included during case creation
1. Log in as a petitions clerk
2. Navigate to Document QC and click Create a Case
3. Locate and click on the Filling Fee Waver Tab
4. Upload a document in filing fee waver.

Expected result
- [ ] New tab displays in case detail for Filing Fee Waver
- [ ] A document can be scanned or uploaded in the Filing Fee Waver Tab

#### Scenario 3 - “Batched By” information added to the Petition QC Section Served tab
1. Log in as a petitions clerk
2. Navigate to Document QC 
3. Click the served tab
4. Confirm Batched By has been added to the table between Document and Served

Expected result
- [ ] Batched By Column has been added to the table

#### Scenario 4 - “Start Scan” button replaces Add Batch link and is located in top right of tab 
1. Log in as a petitions clerk
2. Navigate to Document QC and click Create a Case
3. In the Petitions tab choose the scan radio button and locate the "start scan" button (it will be located at the top right of the tab

Expected result
- [ ] Start Scan button is a primary button located to the right of " how do you want to add in this document" text

#### Scenario 5 - Functionality for flatbed and two-sided scanning 
1. Log in as a petitions clerk
2. Navigate to Document QC and click Create a Case
3. Choose the scan radio button and click the "start scan"
4. Check the scanner prompt for the addition of flatbed and 2-sided scanning options

Expected result
- [ ] Flatbed and two-sided scanning options are available

#### Scenario 6 - Update language and consider changing visual treatment of the session detail toggle to clarify that this will open the official (complete) trial session case list 
1. Log in as a judge
2. Navigate to Trial Sessions and choose a trial session in the table below
3. Choose the scan radio button and click the "start scan"
4. Check the scanner prompt for the addition of flatbed and 2-sided scanning options
5. Click on View All Session info link

#### Scenario 6a - Update language and consider changing visual treatment of the session detail toggle to clarify that this will open the official (complete) trial session case list 
1. On the session information page link next to the title should read: "View Judge Session Copy"
2. Click on "View Judge Session Copy" - opens assigned Judge's Working Copy of session
"View Judge Session Copy" is only visible to the assigned judge

Expected result
- [ ] Link next to the title reads "View Judge Session Copy"
- [ ] link opens assigned Judge's Working Copy of session "View Judge Session Copy" 

#### Scenario 6b - Update language and consider changing visual treatment of the session detail toggle to clarify that this will open the official (complete) trial session case list 
1. Log in as a petitions clerk
2. Navigate to Trial Sessions

Expected result
- [ ] Pages does not have link to  "View Judge Session Copy

#### Scenario 7 - Printable receipt for all document filings, with unique identifier
1. Log in as a petitioner
2. Click the File a Petition button
3. Fill out the form and submit the petition
4. Check the Case Detail page for a success message
5. Click on print a receipt link in success message
(Applies to all external filings electronically submitted)

Expected result
- [ ] Upon submission of electronic filing, app navigates to Case Detail with success message 
        displayed
- [ ] On click of "print a receipt" link, open Receipt PDF in new tab

**Comment by JessicaMarine** [comment]
10.15.19 PO Review:
* On the Petitions Clerk QC Box (both individual and section) -- there doesn't need to be a "Filed by" column on either; the "Case name" column is sufficient
