### ISSUE TITLE
Court User: Ability to make procedural notes on a case

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#317]
As a court user, in order to share procedural case information across the court, I need the ability to make procedural notes at the case level. 

## Acceptance Criteria
* Court users can make procedural notes about a case and have it be easily seen by all users (no permissions)
* Any user can edit any other person's notes or make their own and save (no permission)
* One big text box will be sufficient

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add proceduralNote to case entity (Rachael #3891)
- [x] 2 Endpoints for adding, editing, deleting procedural notes (Kris, Cody #3894)
- [x] 3 Add Case Notes card to Notes tab of case detail (Rachael #3891)
- [x] 4 Create Add/Edit Case Notes and delete note confirm modals (sequences and actions for showing/hiding and submitting) (Rachael, Kris #3901)
- [x] 5 Add case note button to case detail header action menu (Rachael, Kris #3901)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Rachael)
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Case Detail > Actions dropdown 
* add "Add Case Note" option 
* option is available to all internal users 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2e3ec426-7e*b3-4217-b864-2a50594a8ce6)

### Add Case Note modal 
* on click of "Add Case Note" from action dropdown, display modal 
* Display docket number and case caption (minus the ", Petitioner....")
* Note field is required 
* Error message if incomplete: "Enter case note" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cae80eeb-9a5d-4824-bbf9-d51927a18a7f)

**On Save**
* Modal closes 
* success message displays at top of page
* Note displays in Case Notes card on Notes tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0f50edfc-f8f2-4e05-963d-956e3c5b0ec5)

### Notes Tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7af66ed0-6424-4804-8836-642301f2b418)

**Case Notes card - Default**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c92cdcb-b8a0-4b08-acd9-6bb9e211f7df)
* On click of "Add Case Note" button, display Add/Edit Case Note Modal 

**Case Notes card - With Note**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8610d6d4-f892-4b42-bcce-870e4472007f)
* Display text entered in case notes field 
* On click of Edit button, display Add/Edit modal with note text populated 
* On click of Delete button, display Delete Confirmation - on Yes, Delete, 
   - modal closes and note is deleted 
   - Note card displays as default 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/38381061-ab3d-404a-af2d-bbc61f3aaf6c)

**Comment by klohman** [comment]
### 317 Test Scenarios 

#### 1) Internal user sees Add Case note action available on Case Detail 
* Login as internal user 
* Navigate to Case 
* Click on Actions dropdown 
Expected results 
- [ ] “Add Case Note” displays in dropdown

#### 2) Internal user adds case note to case 
* Scenario 1 
* Click Add Case Note 
* Complete Add Case Note form 
* Click “Save” 
Expected results 
On click of Add Case Note 
- [ ] Add/Edit Case Note modal displays 
- [ ] Docket number and case caption (minus , Petitioner…) displays in modal 
On Click of Save 
- [ ] Modal closes, and success message displays 

#### 3) Internal user edits case note 
* Scenario 2 
* Click on Notes tab 
* Click Edit 
* Update note 
* Click Save  
Expected results 
On click of Edit
- [ ] Add/Edit Case Note modal displays 
- [ ] Docket number and case caption (minus , Petitioner…) displays in modal 
- [ ] Current note text is displayed in Case notes field 
On Click of Save 
- [ ] Modal closes, and success message displays 

#### 4) Internal user deletes case note 
* Scenario 3
* Click “Delete” 
* Confirm deletion 
Expected results 
On click of Delete
- [ ] Delete confirmation modal displays 
On click of yes, Delete 
- [ ] Modal closes and success message displays 
- [ ] Note is removed from Case Notes card
- [ ] Add Case Note button displays on Notes card
