### ISSUE TITLE
Court User: Adding a case to an "upcoming" not-yet Calendared trial session

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3254]
As a Court User, in order to comply with a Judge's instructions, I need the ability to manually add a case to an "upcoming" not-yet calendared trial session.

There are occasions where a Judge will issue an Order directing a case to be calendared on a future calendar that has been identified, but not yet "cut".  The Court needs the ability to add a case to an "upcoming" not-yet calendared session.

## Pre-Conditions: ##
* Trial session exists in the system but has not yet been cut/automatically scheduled -- still in "upcoming" status

## Acceptance Criteria: ##
* Court User has the ability to manually add a case to an "upcoming" not-yet calendared trial session
* Case remains added to the trial session after the session is automatically scheduled regardless if the case would otherwise have been included
* Case can be added (and changed to Calendared) when the session is set, but we need to make sure that it doesn't get picked up on any intervening trial session as eligible

## Tasks: ##
- [x] 1 Add hint to modal (Matt #3430)
- [x] 2 Refactor interactor to allow an uncalendared trial session to be set for case (Matt #3430)
- [x] 3 Ensure case is in eligible cases for uncalendared session, and no others (Matt #3430)
- [x] 4 Create `Trial - Scheduled` card layout for the trial session card on case detail case info tab (Rachael #3436) 
- [x] 5 Do not set cases to calendared status when they're manually added if the trial session is not calendared (Rachael #3436)
- [x] 6 If a case becomes eligible after it has already been manually added, it should not be shown twice in the eligible case list (don't create the trial sort records) (Rachael #3436)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
Preliminary Designs 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1f5ea3cd-d716-432b-8eb9-a820ef50807d)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cba8a3bf-316b-4465-a932-e2ea2790429f)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3e53b75d-6a51-4729-8068-eb2534181c51)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e19066b-3ea4-4b63-a5ad-b00fa113857b)

**Comment by klohman** [comment]
#### Case Detail 

* User clicks "Add to Trial" button 

### Add to Trial Modal (Updated) 
**User selects a trial session that has not been set**
* Display alert message in modal 

 ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/10157d21-926e-4e14-b406-baca48d1b591)

**On click of "Add case"**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/869089a0-e73c-4edf-9bf4-95b3fcf9bcd2)

* Modal closes and success message displays
* Case status does change  
* Trial card displays as "Scheduled" 
* Place of Trial populates with selected trial session location
* Trial Date populates with selected trial session date
* Assigned Judge populates with selected trial session judge 
* Remove from trial session button displays 
* Case displays as first priority on eligible case list for the selected trial session 
* Case does not display as eligible for any other trial sessions 

**When trial session calendar is set**
* Case is first priority to be calendared when the trial session is set 
* Case status updates to Calendared 
* Case Trial card displays as Calendared

**Comment by klohman** [comment]
### 3254 Test Scenarios 

Test Data: 
* Create Trial Sessions 
    * Denver, CO 
        * 12/01/2019
        * Regular 
        * Judge Buch 
        * Not Calendared 
    * Denver, CO 
        * 12/15/2019
        * Regular 
        * Judge Ashford
        * Not Calendared  
* Create Cases 
    * Case 1 
        * Place of Trial - Denver, CO 
        * Regular procedure
        * CDP 
        * General Docket - At Issue - Ready for Trial  
    * Case 2 
        * Place of Trial - Denver, CO 
        * Regular 
        * Deficiency
        * General Docket - At Issue - Ready for Trial 
    * Case 3 
        * Place of Trial - Denver, CO 
        * Regular 
        * Deficiency
        * General Docket - Not at Issue 
    * Case 4 
        * Place of Trial - Washington, DC
        * Regular 
        * Deficiency
        * General Docket - At Issue - Ready for Trial

#### 1) User selects trial session that has not been scheduled 
- Login as docket clerk 
- Navigate to Case 1
- Click Add to trial 
- Select Denver, CO 12/01/19 session 
Expected results 
- [ ] Add to trial modal displays alert message when session that is not calendared is selected  

#### 2) User adds case with status General Docket (at Issue) Ready for Trial  to trial session that has not been scheduled 
* Navigate to Case 2
* Click “Add case” on modal 
* View Case Info > Trial Information
Expected results 
- [ ] Modal closes and success message displays 
- [ ] Trial Info card displays as “Scheduled” 
- [ ] Place of Trial populates with Denver, CO 
- [ ] Trial date populates with 12/01/19
- [ ] Assigned Judge populates with Judge Buch 
- [ ] Remove from trial session button displays 
- [ ] Case status remains General Docket - At Issue - Ready for Trial

#### 3) User adds case with status General Docket- Not at Issue  to trial session that has not been scheduled 
- Login as docket clerk 
- Navigate to Case 3 
- Click Add to trial 
- Select Denver, CO 12/15/19 session
- Click Add case
Expected results 
- [ ] Modal closes and success message displays 
- [ ] Trial Info card displays as “Scheduled” 
- [ ] Place of Trial populates with Denver, CO 
- [ ] Trial date populates with 12/15/19
- [ ] Assigned Judge populates with Judge Buch 
- [ ] Remove from trial session button displays 
- [ ] Case status remains General Docket - Not at Issue

#### 4) User sees case in the eligible list for the selected trial session 
* Scenario 3
* Navigate to Trial Session - Denver, CO 12/15/19
* View eligible cases 
Expected results 
- [ ] Case 3 is listed first priority in eligible cases 

#### 5) User does not see the added case in the eligible list for any other trial session in the requested city 
* Scenario 3
* Navigate to Denver, CO 12/01/19
* View eligible cases 
Expected results 
- [ ] Case 3 does not display in eligible cases 


#### 6) User removes case from trial session that is not calendared
* Scenario 2 
* Navigate to Case 2
* Click Remove from Trial Session 
* Navigate to Denver, CO 12/01/19 session 
* Navigate to Denver, CO 12/01/19
Expected results 
- [ ] On click of remove button, modal displays 
- [ ] on click of Yes, remove, modal closes and success message displays 
- [ ] Case status remains General Docket - At Issue - Ready for Trial  
- [ ] Trial info card displays as Trial - Not Set 
- [ ] Add to Trial, Mark High Priority, Block from Trial buttons display 
- [ ] Case 2 displays in regular priority in eligible list for Denver, CO 12/01/19 session
- [ ] Case 2 displays in regular priority in eligible list for Denver, CO 12/15/19 session


#### 7) User sees case as calendared when trial session is set 
* Scenario 4 
* Set Calendar for Denver 12/15/19 session 
* View Open cases for trial session 
* Navigate to Case 3 
Expected results 
- [ ] Case 3 displays in Open Cases for trial session
- [ ] Case 3 status changes to Calendared 
- [ ] Trial Info card displays as “Calendared” 
- [ ] Place of Trial populates with Denver, CO 
- [ ] Trial date populates with 12/15/19
- [ ] Assigned Judge populates with Judge Buch 
- [ ] Remove from trial session button displays 


#### 8) User adds case to a trial session that has not been calendared outside the requested place of trial 
* Login as docket clerk 
* Navigate to Case 4
* Click Add to Trial 
* Select Denver, CO 12/01/19
* Click add case
* Navigate to Denver, CO 12/01/19 trial session detail  
Expected results 
- [ ] On click of Add case, modal closes and success message displays 
- [ ] Case status remains General Docket - At Issue - Ready for Trial
- [ ] Requested Place of Trial displays as Washington, DC 
- [ ] Trial Info card displays as Scheduled
- [ ] Place of Trial populates with Denver, CO 
- [ ] Trial date populates with 12/01/19
- [ ] Assigned Judge populates with Judge Buch 
- [ ] Remove from Trial session button displays 
- [ ] Case 4 displays as first priority in eligible list o Denver, CO 12/01/19 session
