### ISSUE TITLE
Clean-Up: Redesign Case Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3288]
Consider a redesign of the Case Detail page (internal and for parties) after core functionality is implemented

## Acceptance Criteria ##
* Revisit design for case detail page
* Combine Due Dates and Actions Needed

## Tasks
- [x] 1 Tab component addition for top-level tabs (Rachael #3849)
- [x] 2 Case detail header view/button placement updates (Rachael, Kris #3858)
- [x] 3 Case detail internal view updates (Rachael #3849)
- [x] 4 Case detail external view updates (Rachael #3850)
- [x] 5 Case detail public view updates (Rachael, Kris #3858)
- [x] 6 Misc cleanup (add header to deadlines table, move docket record sort, move File Document button, etc) (Rachael #3865 #3867)
- [x] 7 Mobile design updates (Rachael, Kris #3873)
- [x] 8 UX review comments (Rachael #3875)
  - [x] Update all table header labels to sentence case 
  - [x] Deadlines - change “Remove” to “Delete” and change icon and placement of Edit and Delete buttons (match Draft Documents) 
  - [x] Pending Report - get rid of “remove” header in table 
  - [x] On hover state on Tabs - thicken line  
  - [x] Petition Details - change Print receipt to Print Confirmation 
  - [x] Add Counsel - should be sentence case 
  - [x] Enter bar no or name - change to sentence case 
  - [x] Docket record - right align icon in column
  - [x] Docket record - Sort - change to sentence case 
  - [x] Add hover state to Actions button (see style guide) 
  - [x] In Progress - change “Add signature” to “Apply Signature” and add icon (see Order Draft screen) 
- [x]  UX review comment question
  - [x] On tab- always scroll to top 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Internal Case Detail Page 

#### Docket Record tab 
* is default tab when user navigates to Case Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7bbc5f3a-e5f3-45c9-917b-4554f42f1383)

#### Deadlines 
* Display deadlines table 
* UPDATE: Adding table heading row and labels 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9e66539d-f5f4-4370-acda-5c3d6834cf1e)

#### In Progress > Draft Documents 
* Draft Documents is secondary tab under In Progress 
* Is default tab 
* Display Draft Documents table 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c93a9363-c3bc-4bb5-bcfd-c513a48ac42e)

#### In Progress > Messages 
* Display "Pending Messages" table 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9d86c5c2-d0c6-4aaf-ae7e-da32ea292180)

#### In Progress > Pending Report 
* Display "Pending Report" table 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/001af4b6-5f14-494b-bada-ccba1e6b8800)


#### Case Information > Overview
* Overview tab is default 

**Petition Details Card**
* Add "Party Type" field (shown in red only for mockup) 

**Trial Info Card**
* For Trial - Not Scheduled, update location of the trial actions (Add to Trial, High Priority, Block) 

**Consolidated Cases Card** 
* No change to current design / functionality 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e80b95aa-2e0d-49c2-a17c-dcabbb662c89)

#### Case Information > Petitioner 
* Nest Petitioner card and Petitioner Counsel card under Petitioner tab 
* Separate Petitioner and Spouse into two cards 
* No changes to Petitioner Counsel card design or functionality 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eacd120c-c6e2-4407-b48c-19dbe0c23248)

#### Case Information > Respondent 
* Nest "Respondent Counsel" card under Respondent tab 
* No changes to card design or functionality 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/02e94a16-c62b-4d85-8f29-0c7cdff40786)

#### Notes 
* Nest "Judge's Note" card under "Notes" 
* No changes to design/ functionality 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d24bf7b9-4701-409a-8df9-0485cb2b0516)

**Comment by klohman** [comment]
### External Parties Case Detail 

**These designs apply when an external party (petitioner/practitioner/respondent) is associated with a case**

#### Docket Record 
* Move "File a Document" button to header 
* Update styling on File a Document button
* Left align Sort dropdown 
* Right align "Printable Docket Record" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ec50cc3f-48
fa-466d-9c5b-9d576db07222)

#### Case Information > Overview 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e34733a0-3fab-4fb9-bc2d-61da71022369)

**Petition Details**
* Display same fields that are displayed for internal users 

**Trial Information**
If case status does not equal Calendared:
* Display message "This case is not scheduled for trial" 

If case status equals Calendared: 
* Display Place of trial, Trial Date, and Judge fields 

**Consolidated Cases** 
* No changes to card design/functionality 

#### Case Information > Petitioner 
* Nest Petitioner card and Petitioner Counsel card under Petitioner tab
* Separate Petitioner and Spouse into two cards
* Display "Edit" button for Petitioner info 
* Display "Why can't I edit this?"
* No changes to Petitioner Counsel card design 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9fa60267-7dcd-4150-832d-7ac8e711b967)

#### Case Information > Respondent 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0b0376ae-63eb-4d17-97c4-343074755e41)

* Nest "Respondent Counsel" card under Respondent tab
* No changes to card design or functionality

**Comment by klohman** [comment]
### Public Case Detail / Unassociated Counsel 

#### Public View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eb03465e-24eb-4090-9d8b-5a7e6744e5b6)

#### Unassociated Practitioner 
* Display Public Case Detail view 
* Display "Request Access" button in header 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/10955988-6c22-432f-a640-7670e96a94c8)

#### Unassociated Respondent 
* Display Public Case Detail view 
* Display "File First IRS Document" button in header (if no respondent counsel exists on case) 
* Display "Request Access" button in header (if respondent counsel exists on case) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d6811004-012d-4150-8fc0-3e9413833dab)

**Comment by klohman** [comment]
## 3288 Test Scenarios 


#### 1) Internal User sees updated case detail view 
* Login as Petitions Clerk 
* Navigate to Case 
Expected Results 
- [ ] Docket record tab is displayed by default 
- [ ] New tabbed navigation is present (see design) 
- [ ] Action dropdown button displays in header 

#### 2) External party sees updated case detail view
* Login as petitioner 
* Navigate to case 
Expected results 
- [ ] Docket record tab is displayed by default 
- [ ] New tabbed navigation is present (see design) 
- [ ] File a Document button is displayed in header 

#### 3) Public user sees updated case detail view 
* Navigate to unauthenticated site 
* Navigate to case 
Expected result 
- [ ] Docket Record tab is displayed 
- [ ] All other tabs are hidden 

#### 4) Practitioner not associated with case sees updated case detail view 
* Login as practitioner 
* Navigate to case not associated with 
Expected result 
- [ ] Public case detail view is displayed for Docket Record
- [ ] Request Access button is displayed in header 

#### 5) Respondent not associated with case sees updated case detail view 
* Login as respondent1  
* Navigate to case not associated with 
* Login as respondent2
* Navigate to case ^^
Expected result 
For respondent 1 
- [ ] Public case detail view is displayed for Docket Record
- [ ] File First IRS Document button is displayed in header 
For respondent 2 
- [ ] Public case detail view is displayed for Docket Record
- [ ] Request Access button is displayed in header 

#### 6) Internal Users adds deadline to case 
* Login as Calendar Clerk 
* Navigate to case 
* Click “Actions” and “Add Deadline” 
* Save deadline 
* Navigate to Deadlines tab 
Expected result
- [ ] On click of Add Deadline, modal displays (current functionality) 
- [ ] On save of Deadline, modal closes and success message displays on original page 
- [ ] Saved deadline displays on Deadlines tab  

#### 7) Internal user creates order on case 
* Login as docket clerk 
* Navigate to case
* Click on Deadlines tab
* Click Actions and “Create Order” 
* Create and save order (currently functionality) 
Expected results 
- [ ] On click of Create Order, modal displays 
- [ ] On “continue” in modal, user navigates to Create Order page 
- [ ] on save, user navigates back to Docket Record tab with success message displayed 

#### 8) Docket clerk adds docket entry on case 
* Login as docket clerk 
* Navigate to Case 
* Click Actions and “Add Docket Entry” 
* Add Docket Entry and Save 
Expected results
- [ ] On click of Add Docket Entry, user navigates to Add Docket Entry screen
- [ ] On save of entry, user navigates back to Docket Record tab with success message displayed 

#### 9) Docket clerk edits case status on case 
* Login as docket clerk 
* Navigate to case 
* Click Actions and “Edit Case Status/caption” 
* Save changes 
Expected results 
- [ ] On click of Edit Case Status/caption,  modal displays 
- [ ] on save, user navigates back to Docket Record tab with success message displayed 

##### 10) External party sees trial information for an unscheduled case 
* Login as petitioner 
* Navigate to case not set for trial 
* Click on Case Information tab 
Expected results 
- [ ] Trial Information card displays message “This case is not scheduled for trial” 

#### 11) External party sees trial information for a calendared case 
* Login as petitioner 
* Navigate to case with status = Calendared 
* Click Case Information tab 
Expected results 
- [ ] Trial information card displays Place of Trial, Trial date, and Judge fields 

#### 12) Internal user (not judge or chambers) sees Notes tab without Judge’s Notes card
* Login as docket clerk 
* Navigate to case 
* Click Notes tab 
Expected results 
- [ ] Judge’s Note card is hidden 

#### 13) Judge/ chambers sees Notes tab with Judge’s Notes card 
* Login as Judge Buch
* Navigate to case 
* Click Notes tab 
* Login as Judge Buch’s chambers user 
* Navigate to case 
* Click Notes tab 
Expected results 
- [ ] Judge’s Note card displays

**Comment by klohman** [comment]
Some notes on 3288….
- Update all table header labels to sentence case 
- Deadlines - change “Remove” to “Delete” and change icon and placement of Edit and Delete buttons (match Draft Documents) 
- Pending Report - get rid of “remove” header in table  


- On hover state on Tabs - thicken line 
- On tab- always scroll to top 

- Petition Details - change Print receipt to Print Confirmation 
- Add Counsel - should be sentence case 
- Enter bar no or name - change to sentence case 
- Docket record - right align icon in column 
- Docket record - Sort - change to sentence case 
- Add hover state to Actions button (see style guide) 
- In Progress - change “Add signature” to “Apply Signature” and add icon (see Order Draft screen)
