### ISSUE TITLE
Docket Clerk: Serve Orders and Decisions (paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3345]
As a Petitions or Docket Clerk, so that I may serve internally created court documents to parties with a paper service indicator, I need the ability to print the documents for any party that receives paper service.

## Acceptance Criteria
* Petitions and Docket Clerk can serve court-issued documents in paper form to parties that have a paper service indicator
* Service is noted within the system/docket record (already done)
* Served document is available within the system with the served date on it (already done)
* System prints the served date on the paper document being served (already done)
* System prints the name and address of the party on a blank first sheet so that a window envelope can be used (see comment below for placement of address -- same at #653) 

Notes:
* Follow up with Rhonda to confirm that the court NEVER serves externally filed documents to parties with paper indicator
* Regular mail versus certified/registered [Jessica needs to find out which docs get sent certified/registered]

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update `aggregateElectronicallyServedParties` to also return paper service parties (Rachael #3801)
- [x] 2 Add alert to service modal and update confirm button text if any parties have paper service (Cody #3807)
- [x] 3 Trigger print dialog when submitting the service modal if any parties have paper service (Kris #3834)
- [x] 4 Add address page to document that is printed only and return the pdf data from the interactor (Team mob #3810)
- [x] 5 Fix PDF spacing/styling issues with address and header (Cody #3835)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/741a3752-f589-44b2-8f95-82794c0fd22b)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/cbefee35-5662-47c3-a7c9-ca9abf882f35)

**Comment by klohman** [comment]
### On click of "Serve to parties" 

**If no parties on the case have service preference = paper**

* Display service confirmation modal (already implemented) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bd5c0eef-2ec5-4248-8c59-8382ed69bd3e)

**If ANY party on the case has service preference=paper**
* Display service confirmation modal with paper service warning
* List any petitioners that have paper service 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0a83f001-44ca-4a78-94aa-0be37d8cedc5)

### On click of "Serve and Print" 

* Served date is placed on document PDF  (already implemented) 
* Docket entry displays Served date (today's date) and Filed Date (same as served date)  (already implemented) 
* Docket entry displays "B" in Parties column  (already implemented) 
* Any parties receiving electronic service are sent email notification  (already implemented) 
* Copy of document PDF with address page is printed for each party receiving paper service 

### Address Page 

* Address page is printed for each party with paper service
* Includes docket number, petitioner name, address 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/530bd2e6-9ab0-48e9-ab81-ab3280770c08)

**Comment by klohman** [comment]
3345 Serve Orders and Decisions Paper 

### 3345 Test Scenarios 

**Case 1**
* Create case (e-file)
* Create Draft Order of Dismissal 
* All parties have electronic service 

**Case 2**
* Create Case (e-file)
* Create draft Decision 
* Party type - Petitioner(electronic service) and Spouse (paper service) 

**Case 2**
* Create Case (Paper Petition) 
* Create draft Decision 
* Party type - Petitioner(paper service) and Spouse (paper service) 


#### 1) Docket clerk does not see service warning for case without paper service party
* Login as docket clerk 
* Navigate to Case 1 
* Click on Draft Order of Dismissal
* Click Add Docket Entry and complete form 
* Click Serve to Parties 
Expected results 
- [ ] Modal display “are you ready to initiate service”
- [ ] Paper service warning is hidden on modal 

#### 2) Docket clerk sees service warning with single paper service party
* Login as docket clerk 
* Navigate to Case 2 
* Click on Draft Decision
* Click Add Docket Entry and complete form 
* Click Serve to Parties 
Expected results 
- [ ] Modal display “are you ready to initiate service”
- [ ] Paper service warning is displayed 
- [ ] Petitioner spouse’s name displays in paper service warning 

#### 2) Docket clerk sees service warning with multiple paper service parties
* Login as docket clerk 
* Navigate to Case 3 
* Click on Draft Decision
* Click Add Docket Entry and complete form 
* Click Serve to Parties 
Expected results 
- [ ] Modal display “are you ready to initiate service”
- [ ] Paper service warning is displayed 
- [ ] Petitioner’s name displays in paper service warning 
- [ ] Petitioner spouse’s name displays in paper service warning 

#### 3) Docket clerk serves and prints court-issued document copy for single paper service party 
* Scenario 2 
* Click “Yes, serve and print” 
Expected results: 
- [ ] One copy of Decision is printed   
- [ ] First printed page includes Petitioner Spouse’s name and address 
- [ ] Docket entry displays as served with today’s date and “B” in parties column 
- [ ] Decision PDF has served date displayed in first page 

#### 4) Docket clerk serves and prints court-issued document copy for multiple paper service parties 
- [ ] Two copies of Decision is printed   
- [ ] First copy printed page includes Petitioner’s name and address  
- [ ] Second copy printed page includes Petitioner Spouse’s name and address  
- [ ] Docket entry displays as served with today’s date and “B” in parties column 
- [ ] Decision PDF has served date displayed in first page

**Comment by klohman** [comment]
### Updated Designs 

* If a case has any paper service parties, display warning on service confirmation modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8af354b8-2a40-4c6f-b816-e434d92acb30)

**On Click of "Yes Serve"**
* If a case has a paper service party, user is navigated to "Print Paper Service Documents" screen 
* On click of Print Documents, full PDF with address page(s) prints 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/106d8f2f-a425-4f43-aac0-2fc893760ccb)

**Comment by klohman** [comment]
UX Review #3345 

- “No Take me Back” button isn’t working on Serve Modal 
- “Yes, Serve” and “No, Take Me Back” should be title case 
- Decrease space above Paper service warning and the document title (margin-bottom-2) 
- Increase space above buttons (should be about 40px) 
- Serve stamp didn’t apply to served documents (170-19, 171-19) (when viewed on Print paper Service Document screen) - stamp is displaying when you access PDF from docket record

**Comment by JessicaMarine** [comment]
PO Review 12/13/19:
* The `No, take me back` button and the `Close` button don't work on the "Are you ready to initiate service?" modal on staging

**Comment by JessicaMarine** [comment]
PO Review 12/13/19 (12:15pm):
* The "No, take me back" button is still not working because it overlays the PDF viewer underneath.  We will need to deal with substituting the PDF view out with something else (like the Firefox PDF viewer) that will allow a modal to over-lay it
