### ISSUE TITLE
Search: Allow unauthenticated users to access a public version of the site

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3516]
## Pre-requiste:
* Member of the public (unauthenticated user) comes to the site https://ui-public-dev.ustc-case-mgmt.flexion.us/

## Acceptance criteria:
* Unauthenticated user can access the case management system to perform a search

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

##Tasks
- [x] 1 Public site terraform config (#3675)
- [x] 2 Create new build target for public version of the site (#3677)
- [x] 3 Create public search view with instructional text for desktop and mobile (Rachael #3687)
  - [x] 3a Public template header/footer (Matt #3693)
- [x] 4 Deploy public version of the site (Rachael #3688)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachel)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Matt)
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Unauthenticated Access 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea5c56b4-03f0-4e76-990d-8d151b9438cc)

* unauthenticated user sees USTC Case Management System search page 
* Login button - on click, navigate to Cognito log in 

### Search by Name 
**Petitioner name**
* Name is required field for search (user cannot search ONLY by state, country, or year)
* Name searches should query fields
   * Name
   * Secondary-name
* Matching results
   * Partial word match (So a search for "Bob" would match results for Bobby, Bobbie, Bob's, etc)
   * Name search might include multiple words, like "Bob Marley," which would only net results that have both those in them (matches could include "Bobby Marley," "Bobby Marleyville" etc)

**Country**
* Dropdown includes - United States, International
* Defaulted to “United States”
* On select of “International” - hide “State” field
* On select of United States, show State field
* Country search should query fields
  * contactPrimary.countryType
   * contactSecondary.countryType

**State**
* Display only when US is country selected
* Includes full list of states/territories (Same as address form)
* State search should query fields
   * contactPrimary.state
   * contactSecondary.state

**Year filed**
* “FromYear” to “ToYear” range
* Accept years 1986 - current
* “To” year - cannot be prior to the “From” year
* Year search query fields
   * Filed date

**On Search**
* TBD for next story 

### Search by Docket Number 
* Exact matches only
* Format must be [XXX-YY]
* Accept leading zeros
* Accept suffix (123-19SL)

**On Search**
* TBD for next story

**Comment by klohman** [comment]
### 3516 Test Scenarios 

#### 1) Unauthenticated user sees search page 
* User navigates to [url]
Expected results 
- [ ] User is navigated to USTC Case Management System search screen 

#### 2) Unauthenticated user accesses login screen 
* User navigate to [url] 
* Click on Login 
Expected results 
- [ ] user is navigated to cognito login screen 

#### 3) Unauthenticated user logs into site via Cognito
* User navigate to [url] 
* Click on Login 
* Enter username / password for petitioner 
* Login
Expected results 
- [ ] User is logged into system 
- [ ] App displays My Cases page for petitioner
