### ISSUE TITLE
Court User: Unlink Consolidated Cases

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3573]
As a court user, so that I may remove a case from a consolidated group, I need the ability to unlink one or more cases.

## Pre-Conditions ##
* Two or more cases are consolidated

## Acceptance Criteria
* Court user can unlink one or more cases from a consolidated group
* After being unconsolidated, the unconsolidated case looks and behaves just as it did before it was consolidated 
   * There should be no consolidated icon on case
   * The case should not be listed on the consolidated card in any case
   * The case should be removed from the consolidated group on party dashboard(s); if the user is a party to the case, the case would now show up as a stand-alone case on the dashboard; if the user is not a party to the case, the case would not show on the dashboard
* All activity/filings/etc. that took place in the case when it was consolidated remains and is not "undone"
* If the lowest number case in a consolidated group is unconsolidated, the next lowest docket number becomes the lead case for the group

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- [x] 1 Add Remove cases button to Consolidated Cases card under Case Information (Cody #4136)
- [x] 2 Create Unconsolidate Cases modal (sequence for opening) (Cody #4136)
- [x] 3 Submit sequence, actions for modal (Kris, Rachael, Cody #4146)
  - [x] 3a Success confirmation message appears at the top to the screen stating that cases were unconsolidated from the group (Kris)
- [x] 4 Endpoint for unconsolidating (interactor, serverless, lambda) (Rachael #4137)
- [x] 5 Hide Remove button if the case isn't already consolidated (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
----DRAFT WIREFRAMES----

![Screen Shot 2020-01-10 at 11.17.48 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/4f46945e-6dbe-4f05-9b13-fccee64b32f7)![Screen Shot 2020-01-10 at 11.17.56 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/00913ad5-b48f-4fc4-81ad-6fd40cd3a399)

**Comment by alsmith1** [comment]
---DRAFT---

## Test scenarios
#### Scenario 1 - Court user can unlink one or more cases from a consolidated group (court user)
1. Login as any internal user
2. Search for a case which is part of a consolidated group
3. Navigate to the Case information
4. In the consolidated cases tile click on the unlink cases link
5. Verify Modal displays asking what cases you would like to unconsolidated
6. Select one or multiple cases to unconsolidated in the modal
7. Click unconsolidated cases button
8. Verify the success confirmation message appears at the top to the screen stating that cases were unconsolidated from the group
9. Verify in the case information tile the case(s) unconsolidated no longer appear in the tile

Expected result
- [ ] Case searched for is part of a consolidated group
- [ ] case header displays a yellow 2 paper icon 
- [ ] consolidated case tile on case information displays unlink cases link
- [ ] modal displays asking what cases you would like to unconsolidated
- [ ] success message displays confirming that cases have been unconsolidated from group
- [ ] case(s) unconsolidated in the modal do not appear in the consolidated cases tile


#### Scenario 2 - All activity/filings/etc. that took place in the case when it was consolidated remains and is not "undone" (court user)
1. Login as any internal user
2. Search for a case which is part of a consolidated group
3. Navigate to the docket record of “searched for” consolidated case
4. Take note of any filings on the docket record
5. Navigate to the Case information
6. In the consolidated cases tile click on the unlink cases link
7. Verify Modal displays asking what cases you would like to unconsolidated
8. Select the case in which you just checked the docket record and unconsolidate in the modal
9. Verify the success confirmation message appears at the top to the screen stating that cases were unconsolidated from the group
10. Verify in the case information tile the case(s) unconsolidated no longer appear in the tile
11. Navigate to the “searched for” case’s docket record
12. Verify that the same filing and proceeding appear in the docket record

Expected result
- [ ] Case searched for is part of a consolidated group
- [ ] note taken of the filings and proceedings in the docket record
- [ ] consolidated case tile on case information displays unlink cases link
- [ ] modal displays asking what cases you would like to unconsolidated
- [ ] success message displays confirming that cases have been unconsolidated from group
- [ ] case(s) unconsolidated in the modal do not appear in the consolidated cases tile
- [ ] filings and proceedings in the “searched for” /unconsolidated case have not been removed


#### Scenario 3 - If the lowest number case in a consolidated group is unconsolidated, the next lowest docket number becomes the lead case for the group (court user & external user)
1. Login as any internal user
2. Search for a case which is the lead case of a consolidated group
3. Navigate to the Case information
4. In the consolidated cases tile click on the unlink cases link
5. Verify Modal displays asking what cases you would like to unconsolidated
6. Select the case in which you just checked the docket record and unconsolidate in the modal
7. Verify the success confirmation message appears at the top to the screen stating that cases were unconsolidated from the group
8. Verify on the consolidated cases tile the case no longer displays 
9. Login as an external user
10. Verify on your dashboard that the case unconsolidated does not display a yellow 2 page paper icon in the header or  in the cases table
11. Verify that in the case list that the case unconsolidated does not display as consolidated and the group that remains consolidated has the next lowest docket number displayed as the lead case (lowest case with any other consolidated case indented under it)

Expected result
- [ ] Case searched for is part of a consolidated group
- [ ] consolidated case tile on case information displays unlink cases link
- [ ] modal displays asking what cases you would like to unconsolidated
- [ ] success message displays confirming that cases have been unconsolidated from group
- [ ] case unconsolidated in the modal does not appear in the consolidated cases tile
- [ ] on the external parties dashboard the case removed does not display a yellow 2 page paper icon in the header on the cases list next tot he docket number
- [ ] the case list that the case unconsolidated does not display as consolidated and the group that remains consolidated has the next lowest docket number displayed as the lead case (lowest case with any other consolidated case indented under it)


#### Scenario 4 - After being unconsolidated, the unconsolidated case looks and behaves just as it did before it was consolidated,  if the user is a party to the case, the case would now show up as a stand-alone case on the dashboard
1. Log in as a court user
2. Remove 1 case from a consolidated group
3. Verify case has been removed from consolidated case tile
4. Log out
5. Login as an external user
6. Verify on the dashboard that the case unconsolidated does not display a yellow 2 page paper icon in the cases table next to the docket number
7. Verify that in the case list that the case unconsolidated displays separately from the consolidated group and not as part of it

Expected result
- [ ] verify that one case has been removed from the consolidated cases group
- [ ] verify on the dashboard that the case unconsolidated does not display a yellow 2 page paper icon in the cases table next to the docket number
- [ ] verify the case unconsolidated displays separately from the consolidated group and not as part of it


#### Scenario 5 - After being unconsolidated, the unconsolidated case looks and behaves just as it did before it was consolidated,  if the user is not a party to the case, the case would not show on the dashboard
1. Log in as a court user
2. Remove 1 case from a consolidated group
3. Verify case has been removed from consolidated case tile
4. Log out
5. Login as an external user
6. Verify on the dashboard that the case unconsolidated does not display a yellow 2 page paper icon in the cases table next to the docket number
7. Verify that in the case list that the case unconsolidated displays separately from the consolidated group and not as part of it

Expected result
- [ ] verify that one case has been removed from the consolidated cases group
- [ ] verify on the dashboard that the case unconsolidated does not display a yellow 2 page paper icon in the cases table next to the docket number
- [ ] verify the case unconsolidated does not display in the cases list
