### ISSUE TITLE
Clean-Up: Redesign Document Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#3580]
As a court user, in order to easily access multiple documents on the docket record, I need the ability to toggle documents from the document detail page. 

This story also includes various clean-up items. 

 ## Pre-Conditions

## Acceptance Criteria
* All documents on the docket record display on the left of the document
* User should be able to view a full-page PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update Docket Record on case detail to H1 tab, and add Document View as second H1 tab (Document View link only displayed for internal users) (Cody #5711)
- [x] 2 Create Document View view
  - [x] 2a Left panel with documents listed,  sorted oldest to newest by date (same sort as docket record) (Matt #5716)
  - [x] 2b Right panel with document viewer (Matt #5716)
  - [x] 2c only display documents that are on the docket record - not draft docs or minute entries (Matt #5716)
  - [x] 2d Display Sealed in Blackstone for legacy data (Matt)
  - [x] 2e Document actions bar, View Full PDF link (Matt #5716)
- [x] 3 On click of the document link from the Docket Record, display the "Document View" tab with the clicked document selected and visible in the PDF viewer (Matt #5716)
- [x] 4 Update document links to redirect to correct page (see story comment) (Rachael #5712)
- [x] 5 Display document that was clicked on when navigating to case detail view from qc boxes or pending report (Rachael)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
This will be part of messaging flow user stories.

**Comment by klohman** [comment]
## Updated Case Detail > Docket Record tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bf53d43a-90ff-44fd-8187-908f5ff00693)

* update Docket Record to H1 tab
* Add "Document View" as second H1 tab

**Accessing Documents from the Docket Record**
* On click of the document link from the Docket Record, display the "Document View" tab with the clicked document selected and visible in the PDF viewer 

#### Document View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/106ccbc9-20cb-4494-93d4-06f30ea9cafd)

#### Document List 
* Includes all document docket entries on the Docket Record,  sorted oldest to newest by date 
* Does not include minute entries (i.e., entries that do not have a document link) 
* Displays a subset of information about each entry: Index, Filed Date, Filings and Proceedings 
* On click of a document row, the selected document PDF displays in PDF Viewer 

#### PDF Viewer 
* Displays a subset of information about the document: Document Title (displayed as header), Filed By,  Served date,  Served Parties 

#### Document actions 
* In Document toolbar, "View PDF" link displays 
* On click of "View Full PDF", open PDF in new tab 

## Document Links 
If clicked from: 
Docket Document QC Inbox (Individual and Section) = navigates to Document QC screen 
Docket Document QC In Progress (individual and Section) = navigates to Document QC screen 
Docket Document QC Processed (Individual and Section) = navigates to Case Detail > Document View with selected document displayed 
Pending Report = navigates to Case Detail > Document View with selected document displayed

**Comment by klohman** [comment]
## 3580 Redesign Document Detail 

* Create e-file case xx1-20
    * Docket entries: 
        * Petition
        * Filing Fee Paid 
        * Request for Place of Trial
        * Answer 

#### 1) Internal users sees new tabbed Docket Record screen 
* Login as an internal user 
* Navigate to case xx1-20
Expected results 
- [ ] Case detail displays with. Docket Record tab displayed 
- [ ] Document View tab displays 

#### 2) Internal user sees only docket record documents in Document View 
* Scenario 1 
* Click on Document View tab 
Expected results 
- [ ] Document list displays all documents on docket record: 
    - Petition
    - Answer 
- [ ] Minute entries on docket record do not display in document list 
    - Filing Fee Paid 
    - Request for Place of Trial 
- [ ] Document list is sorted oldest to newest by filed date 
- [ ] Petition is selected and visible in PDF viewer 

#### 3) Internal user accesses Document View from docket entry link 
* Scenario 1 
* Click on “Answer” link from docket record 
Expected results 
- [ ] App navigates to Document View tab with “Answer” selected in. List 
- [ ] Answer PDF displays in PDF viewer

#### 4) Internal user toggles between documents in Document View 
* Scenario 3
* Click “Petition” from document list 
Expected results
- [ ] Petition displays as selected in document list 
- [ ] Petition PDF displays in PDF Viewer 

#### 5) Internal user views full PDF from Document View 
* Scenario 4
* Click “View Full PDF” for Petition 
Expected results 
- [ ] Petition PDF opens in new tab 

#### 6) Docket clerk navigates to Document View from Document QC > Processed box 
* Login as docket clerk 
* Navigate to My Document QC > Processed box / Section Document QC > Processed box
* Click on a document link
Expected results 
- [ ] App navigates to Case Detail > Document View with the selected document displayed in PDF Viewer

#### 7) Internal user navigates to Document View from Pending Report 
* Login as docket clerk 
* Navigate to Pending Report 
* Click on document link 
Expected results 
- [ ] App navigates to Case Detail > Document View with the selected document displayed in PDF Viewer

**Comment by klohman** [comment]
UX feedback on 3580:

* Links on docket record should open Document View tab with the clicked document selected (it’s still going to the old Document Detail page currently)
* For court-issued documents, the Document View is showing “Filed by [undefined] - we should just hide the filed by portion of this for court-issued documents since they have no filing party
