### ISSUE TITLE
Court User: Serve Automated Notices

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3676]
As a court user, in order to notify parties that an automated notice has been issued, I need the system to serve all automated noticed on parties when the notice is generated.

## Pre-Conditions
* The system has generated an automated notice that gets added to the Docket Record (Notice of Change of Address, Notice of Change of Phone Number, Notice of Change of Address and Phone Number, Notice of Docket Change) -- ANY OTHERS?

## Acceptance Criteria
* System/user serves an automated notice on parties after it's generated [Note: need to account for both paper and electronic service]
* Parties in the case receive the service

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* When notices are served, they are still not visible to public users ( should not be hyperlinked on docket record) 
* Make sure the notice of docket change "docket entry text" is correct for parties/external public view
* This story does not include editing practitioner information/service related to editing practitioner information

## Tasks
- [x] 1 Create paper service modal (Team mob #4092)
- [x] 2 Create helper method for serving a notice (Team mob #4092)
- [x] 3 Notice of Docket Change flow (Team mob #4092)
- [x] 4 Notice of Change of Address/Phone/Address&Phone (internal) flow (Rachael #4101)
- [x] 5 Notice of Change of Address/Phone/Address&Phone (external) flow (#4096)
  - [x] 5a Create a work item
  - [x] 5b Update docket QC screen with alert and redirect to print preview page when completing if there are any paper service parties (Rachael #4107)
- [x] 6 Fix issue with routing on the print preview page - should we be navigating to a separate route? When on the print preview page, you can't click on the docket number in the case detail header to go back to the case detail page (because you're already on the case detail route) (Rachael #4112)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#3676 Test Scenarios 

Case 1 
- Create case with testpetitionerustc1@gmail.com
- Add respondent to case 
- File Motion for Summary Judgment 

Case 2 
- Create case from paper 
- File Motion for New Trial

Case 3 
- Create case with testpetitionerustc1@gmail.com
- Party type- petitioner and spouse 

#### 1) Notice of Docket Change is automatically served on electronic parties 
* Login as docket clerk 
* Navigate to Case 1 > Motion for Summary Judgement QC 
* Change document type 
* Complete QC 
Expected results 
- [ ] Notice of Docket Change is generated on docket record 
- [ ] Notice of Docket Change entry includes service date and parties “B”
- [ ] Petitioner receives service email
- [ ] Respondent receives service email 

#### 2) Notice of Change of Address is automatically served on electronic parties 
* Login as docket clerk 
* Navigate to Case 1 > Case Information 
* Edit petitioner address 
* Save
Expected results 
- [ ] Notice of change of address is generated on docket record 
- [ ] Notice of Change of Address entry includes service date and parties “B”
- [ ] Petitioner receives service email
- [ ] Respondent receives service email 

#### 3) Notice of Change of Telephone Number is automatically served on electronic parties 
* Login as docket clerk 
* Navigate to Case 1 > Case Information 
* Edit petitioner telephone number 
* Save
Expected results 
- [ ] Notice of change of telephone number is generated on docket record 
- [ ] Notice of Change of telephone number entry includes service date and parties “B”
- [ ] Petitioner receives service email
- [ ] Respondent receives service email 

#### 4) Notice of Change of Address and Telephone Number is automatically served on electronic parties 
* Login as docket clerk 
* Navigate to Case 1 > Case Information 
* Edit petitioner address and telephone number 
* Save
Expected results 
- [ ] Notice of change of address is generated on docket record 
- [ ] Notice of Change of Address entry includes service date and parties “B”
- [ ] Petitioner receives service email
- [ ]Respondent receives service email 

#### 5) Notice of Docket Change is automatically served for case with paper service parties 
* Login as docket clerk 
* QC Motion for Summary Judgement for Case 2 
* Edit document type 
* Complete QC 
Expected results 
On complete of QC: 
- [ ] Modal displays “Paper service required” 
- [ ] On click of “Print Now” - navigates to Print Paper Service Documents screen 
- [ ] Notice displays as PDF with address cover page 
- [ ] Notice of Docket Change is generated on docket record 
- [ ] Notice of Docket Change entry includes service date and parties “B”

#### 6) Notice of Change of Address is automatically served for case with paper service parties 
* Login as docket clerk 
* Navigate to Case 2 > Case Info 
* Edit petitioner address 
* Save 
Expected results 
- [ ] [ ] Modal displays “Paper service required” 
- [ ] On click of “Print Now” - navigates to Print Paper Service Documents screen 
- [ ] Notice displays as PDF with address cover page 
- [ ] Notice of Change of Address is generated on docket record 
- [ ] Notice of Change of Address entry includes service date and parties “B”

#### 7) Notice of Change of Telephone Number is automatically served for case with paper service parties 
* Login as docket clerk 
* Navigate to Case 2 > Case Info 
* Edit petitioner telephone number 
* Save 
Expected results 
- [ ] [ ] Modal displays “Paper service required” 
- [ ] On click of “Print Now” - navigates to Print Paper Service Documents screen 
- [ ] Notice displays as PDF with address cover page 
- [ ] Notice of Change of Telephone Number is generated on docket record 
- [ ] Notice of Change of Telephone Number entry includes service date and parties “B”
- 
#### 8) Notice of Change of Address and Telephone Number is automatically served for case with paper service parties 
* Login as docket clerk 
* Navigate to Case 2 > Case Info 
* Edit petitioner address and telephone number 
* Save 
Expected results 
- [ ] [ ] Modal displays “Paper service required” 
- [ ] On click of “Print Now” - navigates to Print Paper Service Documents screen 
- [ ] Notice displays as PDF with address cover page 
- [ ] Notice of Change of Address and Telephone number is generated on docket record 
- [ ] Notice of Change of Address and Telephone number entry includes service date and parties “B”

#### 9) Petitioner changes address on case with paper service 
* Login as testpetitionerustc1
* Navigate to Case 3
* Edit address 
* Save 
* Login as docket clerk 
* Navigate to Document QC > Notice of Change of Address 
* Complete QC 
Expected results 
- [ ] Document QC for Notice displays paper service warning 
- [ ] On complete of QC, navigates to Print Paper Service screen

#### 9) Petitioner changes address on case with paper service 
* Login as testpetitionerustc1
* Navigate to Case 3
* Edit address 
* Save 
* Login as docket clerk 
* Navigate to Document QC > Notice of Change of Address 
* Complete QC 
Expected results 
- [ ] Document QC for Notice displays paper service warning 
- [ ] On complete of QC, navigates to Print Paper Service screen


#### 10) Petitioner changes telephone on case with paper service 
* Login as testpetitionerustc1
* Navigate to Case 3
* Edit telephone number 
* Save 
* Login as docket clerk 
* Navigate to Document QC > Notice of Change of Telephone Number
* Complete QC 
Expected results 
- [ ] Document QC for Notice displays paper service warning 
- [ ] On complete of QC, navigates to Print Paper Service screen

#### 11) Petitioner changes address and telephone number on case with paper service 
* Login as testpetitionerustc1
* Navigate to Case 3
* Edit address and telephone number 
* Save 
* Login as docket clerk 
* Navigate to Document QC > Notice of Change of Address and Telephone Number
* Complete QC 
Expected results 
- [ ] Document QC for Notice displays paper service warning 
- [ ] On complete of QC, navigates to Print Paper Service screen

**Comment by klohman** [comment]
### Design 

#### Paper service required modal 
**Notice of Docket Change (only when a notice of docket change is generated)**
* on complete of QC, navigate to Case Detail > Docket Record with success message displayed 
* Display modal 

**Notice of Change of Address**
* On save of address updates, navigate to Case Detail > Case Info with success message displayed 
* display modal 

**Notice of Change of Telephone Number**
* On save of telephone updates, navigate to Case Detail > Case Info with success message displayed 
* display modal 

**Notice of Change of Address and Telephone Number**
* On save of updates, navigate to Case Detail > Case Info with success message displayed 
* display modal 

* On click of "Print Now", navigate to Print Paper Service Documents screen 

#### Petitioner Initiated Notices 

* Petitioner edits address and/or phone number under their account 
* Notice of Change of Address, Notice of Change of Telephone Number, or Notice of Change of Address and Telephone Number is automatically generated and added to docket record 

**UPDATE: QC work item is created for Notice and Notice displays in Docket Document QC Inbox**
* Create work item only if case has party with paper service 
 
**Document QC - For Automated Notices with Paper Service)**
 * Display warning message 
* On complete of QC, navigate directly to Print Paper Service screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dbc39797-0a7e-47a3-be3b-cc2c31e90974)

**Comment by klohman** [comment]
UX Review Comments 
- Notice of Change of Address entry when initiated by docket clerk should not have a Filed by - should be blank but I’m seeing the docket clerk’s name (122-20, 123-20) 
- Service email for Notice of Change of Address shows Document : undefined (122-20)
- Notice of Change of Telephone Number entry when initiated by docket clerk should not have a Filed by - should be blank but I’m seeing the docket clerk’s name (122-20, 123-20) 
- Service email for Notice of Change of Telephone Number shows Document : undefined (122-20)
- Notice of Change of Address and Telephone Number entry when initiated by docket clerk should not have a Filed by - should be blank but I’m seeing the docket clerk’s name (122-20) 
- Service email for Notice of Change of Address and Telephone Number shows Document : undefined (122-20)
- Notice of Change of Address docket entry is showing duplicate name - Notice of Change of Address for Colton Garrison for Colton Garrison (124-20)
- Notice of Change of Telephone Number and Notice of Change of Address and Telephone Number for 124-20 did  not show Filed by (should show Petitioner) when the entry was originally created but added the filed by after Docket completed QC - it should always show the filed by when the petitioner / practitioner changes the address
- Docket 122-20- the docket record is out of order - Notice of Docket Change for Entry 4 is showing above entry 4 even though it was created after
- 122-20 - there is a blank entry on the docket record - happened when I changed the doc type on #4 and completed the QC (Amy also put in a Trello ticket for this - it has happened several times)
