### ISSUE TITLE
Court User: Ability to record postmark date and display on petition coversheet

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3804]
As a court user, in order to know if a paper petition was timely mailed, I need the ability to note the postmark dated in the system so it's legible.  

## Acceptance Criteria
* Court user can record "Mailing Date" information for paper-filed documents (1 free text field)
* One line of free text is sufficient
* Text entered in the field displays on the coversheet above the docket record [Note: in the same place as "Filed Electronically" appears for an electronic Petition]
* Mailing Date field should be *required* as part of "Start a Case" for a paper petition
* Text entered during the "Start a Case" flow for a paper petition should show on the Petitions QC screen
* If electronic Petition, no Mailing Date field is displayed on the Petitions QC screen
* Mailing Date field should be *optional* as part of the "File a Document" flow for a paper document processed by Docket

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Court doesn't currently have on cover sheet, so we can discuss placement

## Tasks
- [x] update create paper case flow to allow the optional mailing date field, includes UI / Interactors changes (Cody #3871)
- [x] update add docket entry flow to allow the optional mailing date field, includes UI / Interactors changes (Cody #3880)
- [x] update the coversheet code to display the mailing date if provided (Cody #3871)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Create Case Form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d6eb0032-4018-4213-aa56-e188f22861f1)

* Add "Mailing Date" field 
* Field is required 
* Error message if blank on submit: "Enter a mailing date" 
* Free text field : max 25 characters 

### Updated Petition QC Form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/687a10bc-e6db-407c-acc1-ce89834c43d1)

**Mailing Date field**
* Display only for paper-filed petition (hide for electronically filed)
* Field is populated with text entered on Create Case form
* Field is required for paper petitions 
* Error message if blank on submit: "Enter a mailing date" 
* Free text field : max 25 characters

### Updated Add Docket Entry form
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1fd393fb-64ef-4271-b73f-5bdc8a2ddf2d)

* Add "Mailing Date" field 
* Field is optional 
* Free text field : max 25 characters 

### Updated Edit Docket Entry form 
[Uploading... image.png ]

* Add "Mailing Date" field below Date Received field  
* Field is optional 
* Free text field : max 25 characters 

### Updated Document Cover Sheet 
**Electronically filed documents**
* Electronically filed is displayed on cover sheet (current functionality, no changes) 

**Paper Documents**
* Text entered in Mailing date field is displayed on cover sheet 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dd19f63f-43e5-4549-9974-f71fd7ee9b62)

**Comment by klohman** [comment]
## 3804 Postmark Date 

#### 1) Petitions clerk enters mailing date when creating paper case 
* Login as petitions clerk 
* Navigate to Document QC and click Create Case 
Expected results 
- [ ] Mailing date displays on Create Case form 

#### 2) Petitions clerk must enter mailing date on Create Case form to submit 
* Scenario 1 
* Complete form without entering Mailing date 
* Click “Create Case” button 
Expected results 
- [ ] Form is not submitted 
- [ ] Mailing date error displays : Enter a mailing date 

#### 3) Petitions clerk views/edits mailing date when QCing a paper petition 
* Scenario 2
* Enter “Postmarked 12/11/19” in the Mailing date field 
* Click Submit form 
Expected results 
- [ ] User navigates to Petition QC screen  
- [ ] Mailing date field displays 
- [ ] Mailing date field is populated with “Postmarked 12/11/19” 

#### 4) Petitions clerk does not see mailing date field when QCing an electronically filed petition 
* Login as petitions clerk 
* Navigate to Document QC 
* Click on an electronically filed petition 
Expected results 
- [ ] User navigates to Petition QC screen 
- [ ] Mailing date field is hidden 

#### 5) Petitions clerks sees mailing date displayed on paper Petition cover sheet 
* Scenario 3
* View Petition PDF cover sheet 
Expected results 
- [ ] “Postmarked 12/11/19” displays on cover sheet 

#### 6) Docket clerk enters mailing date when adding docket entry 
* Login as docket clerk 
* Navigate to a case 
* Click Add Docket Entry 
Expected results 
- [ ] User navigates to Add Docket Entry screen
- [ ] Mailing date field displays as optional 

#### 7) Docket clerk sees mailing date displayed on paper document cover sheet
* Scenario 5
* Enter “Postmarked 12/10/19” in Mailing Date field 
* Complete docket entry
* Click on document link from docket record  
Expected results 
- [ ] “Postmarked 12/10/19” displays on document cover sheet 

#### 8) Petitions clerk see “Electronically Filed” on the cover sheet for electronically filed petitions 
* Scenario 4 
* View PDF document 
Expected results 
- [ ] “Electronically filed” displays on document cover sheet 


#### 9) Docket clerk see “Electronically Filed” on the cover sheet for electronically filed documents 
* Login as docket clerk 
* Navigate to Document QC 
* Click on electronically filed document  
* View PDF document 
Expected results 
- [ ] “Electronically filed” displays on document cover sheet
