### ISSUE TITLE
Petitions Clerk: Issuing Orders (by 1/8)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3897]
As a petitions clerk, in order to issue orders, I need the ability to create and serve orders.

## Acceptance Criteria
* Petitions Clerk can generate an Order (done)
* Petitions Clerk can sign an Order with the Chief Judge's signature (done)
* Petitions Clerk can create a docket entry for the Order
* Petitions Clerk can serve the Order on the parties
   * Parties (petitioner only, not respondent) with electronic service get an email
   * Parties with paper service get paper

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Not transmitting files to IRS at this time
* Not adding the doc to the ZIP file at this point, since we don't know actual solution for transmitting docs to IRS
* Decision made to serve generic IRS email if no attorney attached. That work is not part of this story. 

## Tasks
- [x] create a new permission and attach it to the petitions clerk to allow them to create & serve a court issued order (Cody #3925)
- [x] Filter out draft documents whee creating the zip (Rachael #3930)
- [x] petitionsclerk should only be able to create the generic order (Cody #3925)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Test Scenarios 3897 

#### 1) Petitions clerk generates order 
* Login as petitions clerk 
* Navigate to Case 
* Click Create Order 
* Select “O” and enter Order Title 
* Enter Order text 
* Save 
Expected results 
- [ ] navigates back to Docket Record tab with success message displayed 
- [ ] Draft Order displays in Draft Documents 

#### 2) Petition clerk signs order 
* Scenario 1
* Click on Order from Draft Documents 
* Click Apply Signature 
* Apply Signature and Save  
Expected results 
- [ ] navigates Draft Order screen (with Add Docket Entry button)
- [ ] Success message displays 
- [ ] Chief Judge signature is attached to Order 

#### 3) Petitions clerk adds docket entry for order 
* Scenario 2 
* Click Add Docket Entry 
* Select “Served” under Service Stamp 
* Click Save Entry 
Expected results 
- [ ] Order no longer displays in Draft Documents 
- [ ] Docket entry displays as “Not served” 

#### 4) Petitions clerk serves order without paper service parties 
* Scenario 3 
* Click on Order from Docket Record 
* Click Serve to Parties 
* Click Yes, Serve 
Expected results 
- [ ] navigates back to Docket Record with success message displayed 
- [ ] Docket entry displays Filed date, Served date, and parties “B”
- [ ] Order PDF displays “Served” stamp and date 

#### 5) Petitions clerk serves order with paper service parties 
* Scenario 3 
* Click on Order from Docket Record 
* Click Serve to Parties 
* Click Yes, Serve
Expected results 
- [ ] navigates to Print Paper Service Documents screen 
- [ ] Docket entry displays Filed date, Served date, and parties “B”
- [ ] Order PDF displays “Served” stamp and date

**Comment by JessicaMarine** [comment]
PO Review 12/22/19:
* (1) On the create docket entry page, the word "Order" is auto-populating in the "What is this order for?" field -- that is causing the docket entry to read: Order Order ... Can we make it so one of those Orders goes away?  Whatever solution is easiest. And apply fix to Docket clerk version as well. 
* (2) Petitions Clerk will never "Enter and Serve" an Order, so we can hide that option for them.
* (3) I really like the flow where after the Petitions Clerk SAVES the Order, it immediately routes them into the draft Order page so they can immediately sign the order, create the docket entry, and serve.  We need to fix the flow for other Court users so that once they SAVE the order, they are routed to the draft order page rather than back to the Docket Record (as they are now). Should #3 be part of this story, or made separate?
