### ISSUE TITLE
Make transcripts unavailable to parties for 90 days

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3909]
As a court user, in order to comply with contractual obligations with our Court reporting vendor, we need to make transcripts unavailable to parties within a case for 90 days.

The Court has a contract with a reporting company to transcribe our Court proceedings.  One term of our contract is that the Court will not make any transcripts publicly available (even to parties) for 90 days.

## Pre-Conditions: ##
* Court has uploaded a transcript in a case

## Acceptance Criteria: ##
* All transcripts should only be viewable to internal Court users for the first 90-days [Note: 90-day period runs from the date of trial/hearing.  This information should be gathered when Docket Clerk enters information while creating docket entry.]
* After 90 days, transcripts should then be viewable to parties in the case
* Transcripts are never viewable to the public
* Provide a way to test without waiting 90 days

## Notes
* the document type required fields for TRAN needs to be updated to add the date- the spreadsheet is now updated
*** for testing purposes we need to set the timer to 1 day at first then can update after testing to 90 days**

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Figure out what restrictions are on the date the transcript is filed - should it be in the past? If so, fix validation to allow date in the past. (Rachael #4335)
~~- [ ] 2 Add permission for viewing all transcripts at any time~~
- [x] 3 Update getDownloadPolicyUrlInteractor to retrieve the document, check the event code for TRAN, and check if 90 days have passed (if the user doesn’t have transcript permission) (Kris, Rachael #4350)
- [x] 4 Update getFormattedCaseDetail with a new computed value to hide the document link (Kris, Rachael #4350)
- [x] 5 Hide transcript links for public users (Rachael #4351)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
- should the transcripts display as OST - Order of Service of Transcript and TRAN - Transcript  for internal for 90 days before releasing to external parties?
- 2 seperate docket records?

**Comment by alsmith1** [comment]
####DRAFT####

## Test scenarios
#### Scenario 1 - All transcripts should only be viewable to internal Court users for the first 90-days [Note: 90-day period runs from the date of trial/hearing. This information should be gathered when Docket Clerk enters information while creating docket entry.]
1. Log in as a internal court user
2. Navigate to a docket record
3. Verify the record for transcripts is on the docket record 
4. Verify the record for transcripts is clickable

Expected result
- [ ] User can get to the docket record
- [ ] User can see an entry on the docket record for a transcript
- [ ] User can access the transcript document


#### Scenario 2 - All transcripts should not be viewable to external users/viewers for the first 90-days [Note: 90-day period runs from the date of trial/hearing. This information should be gathered when Docket Clerk enters information while creating docket entry.]
1. Log in as a external user
2. Navigate to a docket record
3. Verify the record for transcripts is on the docket record 
4. Verify the record for transcripts is not clickable

Expected result
- [ ] User can get to the docket record
- [ ] User can see an entry on the docket record for a transcript
- [ ] User can not access the transcript document

#### Scenario 3 - After 90 days, transcripts should then be viewable to parties in the case
1. Log in as a external user
2. Navigate to a docket record
3. Verify the record for transcripts is on the docket record 
4. Verify the record for transcripts is clickable

Expected result
- [ ] User can get to the docket record
- [ ] User can see an entry on the docket record for a transcript
- [ ] User can access the transcript document

#### Scenario 4 - Transcripts are never viewable to the public
1. Search a case as a non logged in user
2. Navigate to a docket record
3. Verify the record for transcripts is on the docket record 
4. Verify the record for transcripts is not clickable

Expected result
- [ ] User can search for the case
- [ ] User can get to the docket record
- [ ] User can see an entry on the docket record for a transcript
- [ ] User can not access the transcript document

**Comment by alsmith1** [comment]
![Screen Shot 2020-01-28 at 9.17.00 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/618063dd-9907-43da-8bfd-d6348f22bea0)![Screen Shot 2020-01-28 at 9.17.12 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/7d626d00-e1a8-4ab7-a40d-b7552a5f3709)

**Comment by klohman** [comment]
### Design 

#### Add Docket Entry (Court-Issued)
When TRAN event code is selected:
* Display "Enter description" field (required)
* Display "Date of trial/hearing" field (required) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/77df869e-9a1a-40eb-8315-d2cdf659feec)

#### Internal View Docket Record 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d989a161-4010-4e5d-af9b-fd03d43af69c)

#### External Party View Docket Record (Before 90 days) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e753cc9a-f7c9-4090-8835-980f4b36185a)

**Comment by klohman** [comment]
### 3909 Making transcripts unavailable to parties before 90 days 

Test Data 
* Case 1 
    * Create with petitioner1
    * Add practitioner1
    * Add respondent1
    * Create Order (O) as draft 
* Case 2 
    * Create with petitioner1
    * Add practitioner 
    * Add respondent 
    * Create Order (O) as draft 


#### Scenario 1) Docket clerk adds transcript to the docket record 
* Login as docket clerk 
* Navigate to case 1
* Navigate to draft Order 
* Click Add Docket Entry 
* Complete entry using TRAN code and trial/hearing date  of 1/14/20
Expected result 
- [ ] Concatenated document title displays on docket record as “Transcript of [anything] on [date]”

#### Scenario 2) Internal user views transcript before 90 days 
* Scenario 1 
* Click on Transcript docket entry 
Expected results 
- [ ] User is navigated to Document Detail screen for Transcript

#### Scenario 3) Party cannot view transcript before 90 days 
* Login as petitioner1 / practitioner1 / respondent1
* Navigate to Case 1 
* View docket record 
Expected results 
- [ ] Concatenated document title displays on docket record as “Transcript of [anything] on [date]”
- [ ] Transcript is not linked 

#### Scenario 4) Docket clerk views transcript after 90 days 
* Login as docket clerk 
* Navigate to Case 2 
* Navigate to draft Order 
* Click Add Docket Entry 
* Complete entry using TRAN code and trial/hearing date [91 days before current date]
* Click on transcript from docket record 
Expected result 
- [ ] Concatenated document title displays on docket record as “Transcript of [anything] on [date]”
- [ ] User is navigated to Document Detail screen for Transcript

#### Scenario 5) Party can view transcript after 90 days 
* Login as petitioner1 / practitioner1 / respondent1
* Navigate to case 2 
* View docket record 
* Click on transcript from docket record 

Expected results 
- [ ] Concatenated document title displays on docket record as “Transcript of [anything] on [date]”
- [ ] Transcript PDF opens in new tab 

#### Scenario 6) Public user cannot view transcript before or after 90 days 
* Access site as public user 
* Search for Case 1 
* View docket record 
* Search for Case 2 
* View docket record 
Expected results 
- [ ] Concatenated document title displays on docket record as “Transcript of [anything] on [date]”
- [ ] Transcript is not linked

**Comment by klohman** [comment]
UX Review 

- Trial/hearing date format on Docket record is inconsistent - all displayed dates should be formatted mm/dd/yy

![Screen Shot 2020-02-06 at 11.06.59 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b5f6713a-06bf-4041-824d-6165f8c6079f)
