### ISSUE TITLE
Allow Primary Petitioner to change the contact info for secondary Petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3916]
## Acceptance Criteria
* Allow primary Petitioner to change contact info for the secondary Petitioner
* If primary Petitioner changes the contact information for the secondary Petitioner, a Notice of Change of Address, Notice of Change of Phone Number, and/or Notice of Change of Address and Phone Number should be automatically generated and served on the parties

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Can we add some additional ACs?
* Allow Petitioner Counsel to change contact info for the secondary Petitioner
* Serve automated notices on paper and electronic parties when Petitioner Counsel updates Primary or Secondary Petitioner address and/or telephone number 

## Tasks

- [x] 1) on case info petitioner and practitioner views (NOT respondent): (Kris #4393)
  - remove "why can’t I edit this” link
  - add “edit” link to secondary contact info card, available to petitioner and petitioner counsel
- [x] 2) create/update sequence to edit secondary contact info (Matt #4397, #4401)
- [x] 3) display secondary contact name, non-editable on form. (Rachael #4395)
- [x] 4) in the interactor: If address and/or phone number is updated, a "Notice of Change of Address/ Notice of Change of Telephone Number/ Notice of Change of Address and Telephone Number" should be generated (same functionality as #2146 and #3676) (Matt #4397)
 - [x] 5) update 'cancel' links to show the cancel modal when editing primary *or* secondary contact info (Rachael #4395)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Case Detail > Case Information > Petitioner tab  
* Applies to the Petitioner and Practitioner views only (not Respondent) 
* Remove "Why can't i edit this?" link 
* Add "Edit" link to Spouse's Contact Information 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eb69179f-07cc-4bcd-8054-4232b9c0b47f)


#### Edit Contact Information 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/08efb0f1-bc24-42b2-a193-c84d14174c2f)

**Contact Name**
* Display secondary contact name 

**Address and Telephone Changes**
* If address and/or phone number is updated, a "Notice of Change of Address/ Notice of Change of Telephone Number/ Notice of Change of Address and Telephone Number" should be generated (same functionality as #2146 and #3676)

**on Cancel** 
* Display cancel Modal 
![Screen Shot 2020-02-04 at 11.02.17 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1caca50f-4548-4581-9cd7-c76372d64799)

**On Save**
* Navigate back to Case Detail with success message displayed 
* Updated contact information is displayed in Case Information > Petitioner > Spouse Contact info card 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9ee995ee-77f2-403a-9084-546ef24eafbc)

#### Petitioner Contact Info (Bugs) 
**Edit Petitioner Contact Info screen**
* If Party type = "Petitioner and Spouse" or "Petitioner and Deceased Spouse" - Contact name should display Primary Contact 

**On Cancel**
* Display cancel modal

**Comment by klohman** [comment]
### 3916 Test Scenarios 

Test Data 

* Case 1 
    * Create as user = petitioner1
    * Party Type = Petitioner and Spouse 

* Case 2 
    * Create as practitioner1
    * Party type= Petitioner and Deceased Spouse 


#### Scenario 1) Petitioner updates Spouse’s [Secondary Contact] address 
* Login as petitioner1
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update address 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s address is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Address for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Address for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Address for [Secondary Contact] work item displays in Docket Section Document QC 

#### Scenario 2) Petitioner updates Spouse’s [Secondary Contact] telephone number
* Login as petitioner1
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s telephone number is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] work item displays in Docket Section Document QC 


#### Scenario 3) Petitioner updates Spouse’s [Secondary Contact] address and telephone number
* Login as petitioner1
* Navigate to Case 1 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update address and telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s ddress and telephone number  is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] work item displays in Docket Section Document QC 
 
#### Scenario 4) Practitioner updates Spouse’s [Secondary Contact] address 
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update address 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s address is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Address for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Address for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Address for [Secondary Contact] work item displays in Docket Section Document QC 

#### Scenario 5) Practitioner updates Spouse’s [Secondary Contact] telephone number
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s telephone number is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Telephone Number for [Secondary Contact] work item displays in Docket Section Document QC 

#### Scenario 6) Practitioner updates Spouse’s [Secondary Contact] address and telephone number
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Spouse’s Contact Info 
* Update address and telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Spouse’s address and telephone number is updated on Case Information > Petitioner > Spouse Contact Info card 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] is generated on the docket record 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] is served on electronic parties 
- [ ] Notice of Change of Address and Telephone Number for [Secondary Contact] work item displays in Docket Section Document QC 

#### Scenario 7) Practitioner updates Petitioner [Primary Contact] address 
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Petitioner Contact Info 
* Update address 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Petitioner address is updated on Case Information > Petitioner > Petitioner Contact Info card 
- [ ] Notice of Change of Address for [Primary Contact] is generated on the docket record 
- [ ] Notice of Change of Address for [Primary Contact] is served on electronic parties 
- [ ] Notice of Change of Address for [Primary Contact] work item displays in Docket Section Document QC 

#### Scenario 8) Practitioner updates Petitioner [Primary Contact] telephone number
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Petitioner Contact Info 
* Update telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Petitioner telephone number is updated on Case Information > Petitioner > Petitioner Contact Info card 
- [ ] Notice of Change of Telephone Number for [Primary Contact] is generated on the docket record 
- [ ] Notice of Change of Telephone Number for [Primary Contact] is served on electronic parties 
- [ ] Notice of Change of Telephone Number for [Primary Contact] work item displays in Docket Section Document QC 

#### Scenario 6) Practitioner updates Petitioner [Primary Contact] address and telephone number
* Login as practitioner1
* Navigate to Case 2 > Case Information > Petitioner 
* Click Edit link under Petitioner Contact Info 
* Update address and telephone number 
* Save 
Expected results 
- [ ] App navigates back to Case Detail with success message displayed 
- [ ] Petitioner address and telephone number is updated on Case Information > Petitioner > Petitioner Contact Info card 
- [ ] Notice of Change of Address and Telephone Number for [Primary Contact] is generated on the docket record 
- [ ] Notice of Change of Address and Telephone Number for [Primary Contact] is served on electronic parties 
- [ ] Notice of Change of Address and Telephone Number for [Primary Contact] work item displays in Docket Section Document QC

**Comment by JessicaMarine** [comment]
PO Review 2/13/2020:
* When a P changes P1 or P2's contact information, after hitting save, you are routed back to the Docket Record w/ a confirmation message that says "Please confirm your info below".  I think you should be kept on the Case Info tab for this.
