### ISSUE TITLE
Seal a case - Make entire case hidden from public view

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3922]
As the Court, in order to protect a party or filing in a case from disclosure, we need the ability to "SEAL" a case.

The Court needs the ability to SEAL a case.  That means make the entire case (except for Docket Number) hidden from public view.

## Acceptance Criteria: ##
* A Docket Clerk [permissions based] has the ability to mark a case as SEALED
* Once a case is SEALED, it needs to be:
   * Prominently marked as SEALED for all internal Court users.
   * Prominently marked as SEALED for all parties to the case.
   * Completely hidden from public view (as well as practitioners and respondents that aren't part of the case) except for the docket number.  [Design suggestion from Jessica -- if a non-party searches for a SEALED case, it should only return the docket number and "This case is sealed."  Name search should not return anything.] 
* Unsealing a case is not part of this story -- that can be post-MVP.
* Ensure data is not in network response
 * Add messaging for how to enter a case if your a counsel

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 create endpoint, lambda, interactor to seal a case (Rachael #4163)
  - [x] 1a add a property to the case entity for sealing a case (Kris  #4159)
  - [x] 1b add utility function that scrubs cases of all but a whitelist of attributes if it is sealed AND to be hidden from the user performing the query (Kris #4190)
- [x] 2 create action, sequence, proxy to seal a case (Rachael #4165)
- [x] 3 Add 'Seal Case' button to Case Detail Overview card (Rachael #4160) 
  - [x] 3a visible to docketclerk, clerkofcourt roles (Rachael #4160)
- [x] 4 create 'Seal This Case' modal component, sequence to open (Rachael #4161)
- [x] 5 create 'This case is sealed' banner component for docket header (Kris #4159)
- [x] 6 ensure when a case is sealed, the public case detail: (Kris #4159)
  - [x] 6a hides caption from docket header (Kris  #4159)
  - [x] 6b hides docket record (Kris #4190)
- [x] 7 update case search so that cannot be found with search on name (Kris #4190)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Case Detail (Internal) 

* Seal case button is displayed for Docket Clerk, Clerk of the Court roles 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b02b6612-bfac-4a65-b591-4012f1309632)

* On click of "Seal case", display confirmation modal 

#### Confirmation Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a9d59e59-9b82-40db-b05c-cf9be9b1b6b7)

* Display [Docket number] [Case title]

On click of "Yes, Seal Case" 
* Close modal and display success message 
* Display Sealed banner in docket header 

#### Docket Header Updates
* include Sealed banner in docket header on all pages where the docket header is displayed (for internal and external users) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d28dd401-b610-4977-b4bc-868a9b9d623f)

#### Public Case Detail for Sealed Case 
If public user searches for a docket number for a sealed case 
* Navigate to Case Detail 
* Display Sealed banner in Docket Header 
* Hide caption from Docket header 
* Hide docket record 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2be75819-497f-4c7c-886d-8a88eb08599e)

**Comment by klohman** [comment]
### 3922 Test Scenarios 

Test Data: 

Case 1 
* Create case as petitioner 
* Add practitioner 
* Add respondent 

#### 1) Docket clerk views option to seal a case 
* Login as docket clerk 
* Navigate to case detail > case information 
Expected results 
- [ ] Seal case button displays 

#### 2) Docket clerk can seal a case 
* Scenario 1 
* Click on Seal case 
* Click “Yes, Seal Case” 
Expected results 
On click of Seal case,
- [ ] confirmation modal displays  

On click of “yes Seal” button 
- [ ] Modal closes 
- [ ] Success message displays 
- [ ] Sealed banner displays in docket header 
- [ ] Seal case button is hidden 

#### 3) Internal user sees indicator that a case is sealed 
* Login as calendar clerk 
* Navigate to sealed case
Expected results 
- [ ] Sealed banner displays in docket header 

#### 4) External party sees indicator that a case is sealed 
* Login as petitioner / practitioner / respondent 
* Navigate to sealed case 
Expected results 
- [ ] Sealed banner displays in docket header 

#### 5) Public user sees indicator that a case is sealed 
* Access public search 
* Enter docket number for Case 1 
Expected results 
- [ ] Navigates to Case detail screen 
- [ ] Sealed banner displays in docket header 
- [ ] Case caption is hidden 
- [ ] Docket record is hidden 

#### 6) Public user does not see sealed case in name search results 
* Accèss public search 
* Search for Case 1 by petitioner name 
Expected results 
- [ ] Displays “No matching results”
