### ISSUE TITLE
Basic Search for Orders (system-created)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3926]
As a CMS user, in order to locate a relevant Order, I need the ability to perform a basic search of Court orders.

## Pre-Conditions: ##
* System generated order is created and served

## Acceptance Criteria ##
* All CMS users have the ability to search all system-created Court Orders by keyword (basic search) [Note: uploaded orders will be handled in different story]
* Only court orders that have been served are indexed and searchable
* The search only returns documents with the codes for orders 
* Keyword search will match the contents of the document 
* Mobile design needs to be reconsidered for order (and opinion) search. Design is not optimal for public and parties in the case. Story backlogged to reconsider overall design for mobile search. #5025

Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)

## Notes ##
* Court's current public Order search is below in comments
* Consider splitting into three stories - past judges (legacy data); basic search filter (keyword); advanced search filters
* Dealing w/sealed cases will happen in a different story. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? Yes.
 - [ ] Does this work make major changes to the system? No.
 - [ ] Does this work implement new authentication or security controls? Kind of.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features? Yes. 

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (#4947)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (#4947)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (#4947)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Court's current public search for Orders:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/6a8f2bf5-e2e1-4f0b-8942-6d19a7e33f1b)

**Comment by waldoj** [comment]
Regarding the security concern on this — ensuring that sealed cases are not inadvertently surfaced via this search process — I agree that it's a concern. I'd like to see unit and e2e tests that specifically ensure that this does not happen, and I'll look for those during the review process.

I do not believe that any further accommodation is necessary.

**Comment by alsmith1** [comment]
####DRAFT TEST SCENARIOS####

## Test scenarios
#### Scenario 1 - All CMS users have the ability to search all Court Orders
1. Log in as an user
2. Click on the Advanced Search link
3. Verify when the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
4. Click in the search by order tab
5. Verify the following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
6. Enter search terms in one or multiple of the search fields
7. Click search
8. Verify that results display below the search box
9. Verify the table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge

Expected result
- [ ] When the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
- [ ] The following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
- [ ] Results display below the search box
- [ ] The table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge

## Test scenarios
#### Scenario 2 - The public should not see any documents or data that are part of a sealed case
1. Log in as a non authenticated user
2. Verify when the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
1. Click in the search by order tab
2. Verify the following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
3. Enter search terms in one or multiple of the search fields
4. Click search
5. Verify that results display below the search box
6. Verify the table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge
7. Click on each of the search results
8. Verify there is no icon/indicator displaying the cases are sealed

Expected result
- [ ] When the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
- [ ] The following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
- [ ] Results display below the search box
- [ ] The table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge
- [ ] there is no icon/indicator displaying the cases are sealed


## Test scenarios
#### Scenario 3 - Only court orders that have been served are indexed and searchable
1. Log in as an user
2. Verify when the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
1. Click in the search by order tab
2. Verify the following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
3. Enter search terms in one or multiple of the search fields
4. Click search
5. Verify that results display below the search box
6. Verify the table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge
7. Click on each of the search results
8. Verify 
Can we display when the doc was served in results?

Expected result
- [ ] When the page loads there are 3 tabs under the advanced search bar, Search by name, search by docket number and search by order
- [ ] The following fields appear:
    1. Keyword(s)
    2. Case Title
    3. Judge
    4. Date Range
- [ ] Results display below the search box
- [ ] The table displays the following columns
    1. Code
    2. Order
    3. Docket
    4. Date filed
    5. Case name
    6. Judge
- [ ] there is no icon/indicator displaying the cases are sealed

**Comment by alsmith1** [comment]
![Screen Shot 2020-02-26 at 8.41.05 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/f07ac35f-0398-461e-adde-8ce5fd5dc2c3)![Screen Shot 2020-02-26 at 8.41.12 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/b4297579-c6ce-4079-b658-cf17a61ef36e)![Screen Shot 2020-02-26 at 8.41.17 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5f7ff5cc-bd62-4fd8-a0b5-60180d9e6028)![Screen Shot 2020-02-26 at 8.41.22 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/0ecdca3c-537e-477e-8a88-0d35d89c6b5f)![Screen Shot 2020-02-26 at 8.41.29 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/386ca950-6bb3-440c-88eb-ea58fd7f7e48)

**Comment by alsmith1** [comment]
List of Current and Past judges from USTC site
Aarons
Armen
Ashford
Beghe
Buch
Buckley
Cantrel
Carluzzo
Chabot
Chiechi
Clapp
Cohen
Colvin
Copeland
Couvillion
Dawson
Dean
Dinan
Drennen
Fay
Featherston
Foley
Gale
Galloway
Gerber
Goeke
Goffw
Goldberg
Greaves
Gussis
Gustafson
Guy
Haines
Halpern
Hamblen
Holmes
Jacobs
Jones
Kerrigan
Korner
Kroupa
Laro
Lauber
Leyden
Marvel
Morrison
Nameoff
Nega
Nims
Pajak
Panuthos
Paris
Parker
Parr
Pate
Peterson
Powell
Pugh
Raum
Ruwe
Scott
Shields
Simpson
Sterrett
Swift
Tannenwald
Thornton
Toro
Urda
Vandervort
Vasquez
Wells
Whalen
Wherry
Whitaker
Wilbur
Wiles
Williams
Wolfe
Wright

**Comment by klohman** [comment]
### Additional Tests Scenarios 
'#### -) User searches by keyword and case name with exact match
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause - signed by Judge Pugh 
        * Include keyword “affirmative” 

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 


#### -) User searches by keyword and case name with partial matches
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause 
        * Filed by date 12/20/19
        * Include keyword “affirmative” 
* Create case - estate with executor - Estate of John Baxter, Deceased, Wade Baxter, Executor, Petitioner(s) (case xxb-20)
    * Create, sign and Serve - Order for Dismissal - signed by Judge Buch 
        * Filed by date - 03/20/20
        * Include keyword “affirmative”  

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ ] Order for Dismissal for case xxb-20 displays in results

#### -) User searches by keyword and case name (no matches) 
**Test data**
* Same as above  

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “Bob”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 
- [ ] Order for Dismissal for case xxb-20 does not displays in results 
- [ ] “No matching results” message displays 

#### -) User searches by keyword, case name (exact match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### -) User searches by keyword, case name (partial match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Buch from Judge dropdown
* Click Search 
Expected results 
- [ ] Order for Dismissal for case xxb-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### -) User searches by keyword, case name (exact match), judge, and date range 
**Test Data** 
* Same as above 
* Case xxx-20 (John Smith and Mary Jones) 
    * Create, sign and serve Order for Filing Fee - signed by Judge Pugh 
        * Include word - “affirmative” 
        * Filed date - 01/1/20
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### -) User searches by keyword, case name (partial match), judge, and date range 
**Test Data** 
* Same as above 

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 

#### -) User searches by keyword, case name (exact match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### -) User searches by keyword, case name (partial match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ [ Order for Dismissal for case xxb-20 displays in results

**Comment by alsmith1** [comment]
Design notes:
Order list
O	ORDER *ANYTHING*	
O - Order
OAJ	ORDER that case is assigned to *JUDGE* . *ANYTHING*	
OAJ - Order that case is assigned
OAL	ORDER that the letter "L" is added to the Dkt. No. *ANYTHING*	
OAL - Order that the letter "L" is added to Docket number
OAP	ORDER for Amended Petition on *DATE*. *ANY*	
OAP - Order for Amended Petition
OAPF	ORDER for Amended Petition and Filing Fee on *DATE*. *ANY*	
OAPF - Order for Amended Petition and Filing Fee
OAR	ORDER that the letter "R" is added to the Dkt. No. *ANYTHING*	
OAR - Order that the letter "R" is added to the Docket number
OAS	ORDER that the letter "S" is added to the Dkt. No. *ANYTHING*	
OAS - Order that the letter "S" is added to the Docket number
OASL	ORDER that the letters "SL" are added to the Dkt. No. *ANY*	
OASL - Order that the letters "SL" are added to the Docket number
OAW	ORDER that the letter "W" is added to the Dkt. No. *ANYTHING*	
OAW - Order that the letter "W" is added to the Docket number
OAX	ORDER that the letter "X" is added to the Dkt. No. *ANYTHING*	
OAX - Order that the letter "X" is added to the Docket number
OCA	ORDER that caption of case is amended. *ANYTHING*	
OCA - Order that caption of case is amended
OD	ORDER OF DISMISSAL Entered,, *JUDGE*. *ANYTHING*	
OD - Order of Dismissal Entered,
ODD	ORDER OF DISMISSAL AND DECISION Entered,, *JUDGE*. *ANYTHING*	
ODD - Order of Dismissal and Decision Entered,
ODL	ORDER that the letter "L" is deleted from the Dkt. No. *ANY*	
ODL - Order that the letter "L" is deleted from the Docket number
ODP	ORDER that the letter "P" is deleted from the Dkt. No. *ANYTHING*	
ODP - Order that the letter "P" is deleted from the Docket number
ODR	ORDER that the letter "R" is deleted from the Dkt. No. *ANY*	
ODR - Order that the letter "R" is deleted from the Docket number
ODS	ORDER that the letter "S" is deleted from the Dkt. No. *ANY*	
ODS - Order that the letter "S" is deleted from the Docket number
ODSL	ORDER that the letters "SL" are deleted from the Dkt. No. *ANY*	
ODSL - Order that the letters "SL" are deleted from the Docket number
ODW	ORDER that the letter "W" is deleted from the Dkt. No. *ANY*	
ODW - Order that the letter "W" is deleted from the Docket number
ODX	ORDER that the letter "X" is deleted from the Dkt. No. *ANY*	
ODX - Order that the letter "X" is deleted from the Docket number
OF	ORDER for Filing Fee on *DATE*. *ANYTHING*	
OF - Order for Filing Fee
OFAB	ORDER fixing amount of bond at *ANYTHING*	
OFAB - Order fixing amount of bond
OFFX	ORDER time is extended to *DATE* for petr(s) to pay the Filing Fee .	
OFFX - Order time is extended for petr(s) to pay the filing fee
OFWD	ORDER for Filing Fee on *DATE*. Appl. waiver of Filing Fee is Dn.	
OFWD - Order for Filing Fee. Application waiver of Filing Fee is denied.
OFX	ORDER time is extended to *DATE* for petr(s) to pay Filing Fee or submit an Application for Waiver of Filing Fee .	
OFX - Order time is extended for petr(s) to pay filing fee or submit an Application for Waiver of Filing fee
OIP	ORDER that the letter "P" is added to the Dkt. No. *ANYTHING*	
OIP - Order that the letter "P" is added to the Docket number
OJR	ORDER that jurisdiction is retained by *JUDGE* *ANYTHING*	
OJR - Order that jurisdiction is retained
OODS	ORDER for Ownership Disclosure Statement by *DATE*.	
OODS - Order for Ownership Disclosure Statement
OPFX	ORDER time is extended to *DATE* for petr(s) to file Amended Petition and pay the Filing Fee or submit an Application for Waiver of Filing Fee .	
OPFX - Order time is extended for petr(s) to file Amended Petition and pay the Filing Fee or submit an Application for Waiver of Filing Fee
OPX	ORDER time is extended to *DATE* for petr(s) to file Amended Petition.	
OPX - Order time is extended for petr(s) to file Amended Petition
ORAP	ORDER for Amendment to Petition by *DATE*. *ANYTHING*	
ORAP - Order for Amendment to Petition
OROP	ORDER for Ratification of Petition by *DATE*. *ANYTHING*	
OROP - Order for Ratification of Petition
OSC	ORDER *ANYTHING*	
OSC - Order
OSCP	ORDER petr(s) by *DATE* show cause why "S" should not be removed *ANYTHING*	OSCP - Order petr(s) to show cause why "S" should not be removed
OST	ORDER of Service of Transcript (Bench Opinion) *ANYTHING*	
OST - Order of Service of Transcript (Bench Opinion)
OSUB	ORDER that case is submitted to *JUDGE*. *ANYTHING*	
OSUB - Order that case is submitted
DEC	DECISION Entered,, *JUDGE* *ANYTHING*	DEC - Decision Entered,
OAD	ORDER AND DECISION Entered,, *ANY* *JUDGE*. *ANYTHING*	
OAD - Order and Decision Entered,
ODJ	ORDER OF DISMISSAL FOR LACK OF JURISDICTION Entered,, *JUDGE*. *ANYTHING*	
ODJ - Order of Dismissal for Lack of Jurisdiction Entered,
SPTO	Standing Pre-Trial Order

**Comment by alsmith1** [comment]
dev has been set up with test cases for this story as of 4-13-2020

xx1-20 --> 105-20
xx2-20 --> 107-20
xx3-20 --> 108-20
xx4-20 --> 109-20
xx5-20 --> 110-20
xx8-20 --> 114-20
xx9-20 --> 113-20
x10-20 --> 115-20

**Comment by alsmith1** [comment]
dev has been set up with test cases for this story as of 4-17-2020

xx1-20 --> 102-20
xx2-20 --> 103-20
xx3-20 --> 107-20
xx4-20 --> 104-20
xx5-20 --> 105-20
xx6-20 --> 109-20
xx8-20 --> 108-20
extra- 109-20
