### ISSUE TITLE
IRS Superuser

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3927]
As the Court, in order to properly serve the IRS, we need an IRS Superuser to be associated with each case once the Petition is served.

## Acceptance Criteria ##
* IRS Superuser is created as a separate role
* IRS Superuser is associated with each case as soon as the Petition is served
* IRS Superuser has log-in credentials to the CMS
   * Email address to be used: service.agent.test@irs.gov
* IRS Superuser's information is not displayed as "Respondent" on any case 
* IRS super user can log into the system and access all cases

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* View of dashboard does not need to be the same as other practitioners; search/return case
* IRS's actual email address - service.agent@irs.gov

## Tasks
- [x] 1 Create IRS superuser role, set permissions in authorizationClientService (can access all cases, but cannot edit anything), create local and cognito logins (Rachael #4821)
- [x] 2 IRS superuser can only see full case information after a petition has been served in a case - create separate endpoint for IRS superuser getCase (for data for case detail page) (Rachael #4823)
- [x] 3 Create IRS superuser dashboard view (Advanced search VIEW should be the same as for a privatePractitioner), sequence and action to submit search (Rachael #4826)
- [x] 4 Update caseSearchFilter for caseAdvancedSearchInteractor to allow IRS superuser access to all cases in advanced search (look into refactoring this, code is a little messy) (Rachael #4823)
- [x] 5 Setup IRS user script (Matt #4832)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### IRS Superuser dashboard 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7f6c9251-c644-4874-9b96-84e9fdca2cfe)

**Comment by klohman** [comment]
### 3927 Test Scenarios 


#### 1) IRS Superuser can log into the system with a Cognito account 
* Login to system with email: service.agent@example.com 
Expected results 
- [ ] User is authenticated and able to access the system 
- [ ] App navigates to the IRS Superuser Search dashboard 

#### 2) IRS Superuser is associated with each case when the Petition is served and has full access to all information
* Login as petitioner 
* File a Petition (case 1) 
* Login as IRS Superuser 
* Search for case 1
Expected results 
- [ ] IRS Superuser sees public view of case 1 

#### 1) IRS Superuser is associated with each case when the Petition is served and has full access to all information
* Login as petitions clerk 
* Navigate to case 1 
* QC and serve Petition 
* Login as IRS Superuser 
* Search for case 1
Expected results 
- [ ] IRS Superuser has full access to Case 1 information 

#### 3) IRS Superuser's information is not displayed as "Respondent" on any case
* Login as internal user 
* Navigate to Case 1 
* View Case Information > Respondent 
Expected results 
- [ ] IRS Superuser information does not appear under Respondent
