### ISSUE TITLE
Direct court user to signature page after saving a draft order

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#3958]
Currently, after a petitions clerk or docket clerk saves a draft order from the actions dropdown, the user is directed to the docket record.  Instead, the user should be directed to the page where they can add a signature and send the draft Order to another Court user. It better supports the workflow.

## Acceptance Criteria
* When a Court user generates and saves an anything other than a Notice from the actions dropdown, he/she should be directed immediately to the sign order page [Note: The flow works this way if the user generates an Order from the "Summary of Orders" page after a Petitions QC]
* When a court user generates and saves a notice from the actions dropdown he/she should be directed immediately to the document detail for the draft notice.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update submit sequence from Create Order page to redirect to the sign document page (only when submitting anything other than a notice) (Matt #4364)
- [x] 2 Update submit sequence from Create Order page to redirect to the document detail page (only when submitting a notice) (Matt #4364)
- [x] 3 Add page title to Apply Signature page; update link to “Back to Draft Document” (Matt #4364)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Flow / Design 

#### Create Order screen - Orders 
* On save, navigate to Apply Signature page 

#### Apply Signature screen (updated) 
* Add page title 
* update link to "Back to Draft Document" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ad19de6-47a4-4b1a-bd33-8135cfbeab7e)

**On click of Save**
* Navigate to Draft Order screen with success message displayed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/880d92fb-cf6e-4982-91aa-e88ade96feb7)

**On click of "Back to Draft Document"**
* Navigate to Draft Order screen (Default)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5ec960f0-e6a3-43a5-b683-bfacdd60b977)

#### Create Notice 
* On save, navigate to Draft Order screen with success message displayed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/768c5f42-af69-4b5e-93a1-6fb630e933d5)

**Comment by klohman** [comment]
### 3958 Test Scenarios 

#### Scenario 1) On save of order, user is navigated to Apply Signature page 
* Login as judge 
* Navigate to case 
* Click Create Order and select an Order doc type 
* Enter order text and click Save Order
Expected results 
- [ ] App navigates to Apply Signature screen 
- [ ] Saved order PDF displays in PDF viewer

#### Scenario 2) On save of signature, user is navigated to Draft Order screen 
* Scenario 1 
* Apply signature to PDF 
* Click Save Signature 
Expected results 
- [ ] App navigates to Draft Order screen with success message displayed 
- [ ] Signature is captured on Order PDF 

#### Scenario 3) On click of “Back to Draft Documents”, user is navigated to Draft Order screen 
* Scenario 1 
* Click “Back to Draft Document” 
Expected results 
- [ ] App navigates to Draft Order screen - default view

#### Scenario 4) On save of Notice (NOT), user is navigated to Draft Order screen 
* Login as docket clerk 
* Navigate to case 
* Click Create Order or Notice and select the Notice (NOT) doc type
* Enter text and click “Save Order” 
Expected results 
- [ ] App navigates to Draft Order screen with success message displayed 
-
