### ISSUE TITLE
Member of the Public: Public-facing Case Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#40]
As a Member of the Public, to protect the privacy of the parties, only Court-issued documents will be viewable by Members of the Public through the public-facing docket record.

## Pre-Requisite:
* A member of the public (unauthenticated user) has accessed a case

## Acceptance Criteria:
* Only the Docket Record is displayed on the Case Detail page for a Member of the Public and no other case information
* Only Court-issued documents are able to be opened by a Member of the Public from the Docket Record
* Remove all search for logged in petitioner

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes:

* Whole separate elastic search instance for public
* Docket entry should display even though document can't be linked to
* Consider how to handle sealed docs/docket entries -- perhaps change text to "SEALED DOCKET ENTRY"
* Document titles on public docket record should be semi-bold, with the additional docket entry info regular weight
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9fab28c6-5ddc-4ab3-a456-06bbf1280a82)

## Tasks
- [x] 1 Public case detail header (Cody #3737)
- [x] 2 Public docket record view (Matt #3742, #3746)
- [x] 3 Endpoint / entity for public docket record (Cody #3743)
- [x] 4 Integrate docket record data with view (Rachael #3749)
- [x] 5 change link in header to just plain text (Rachael, Kris #3750)
- [x] 6 double check the order is in chronological order (Rachael, Kris #3750)
- [x] 7 double check security; verify that a public user can’t figure out the document ID and directly access the petition document (Team mob #3752)
- [x] 8 spacing between case caption and docket number needs to be expanded (Rachael, Kris #3750)
- [x] 9 bring in the full text of the docket entry (Rachael, Kris #3750)
- [x] 10 filter draft documents out of response from api (Team mob #3757)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mlissner** [comment]
Hi, I'm the executive director of [Free Law Project][flp], a non-profit organization that gathers immense quantities of legal data and provides it to the public for research, journalism, or legal activities. 

We've been watching the work here with interest, and wanted to just chime in with a quick question/comment. When opinions are written by the Tax Court, they get `T.C. Memo` numbers in addition to the docket/case numbers they normally have. Here's an example from [a case][case] on our website. You can see the `T.C. Memo` number at the top and the docket number at the bottom:

![Screenshot from 2019-11-07 10-19-36](https://user-images.githubusercontent.com/236970/68424802-a464ad80-0159-11ea-8a82-e32240d632c5.png)

Is it part of the design/plan to make these numbers available in the API and HTML docket pages? We scrape content from the current website, where this information is difficult to get. Given that practitioners use these numbers to cite these opinions ([as described here][cite]), it would be wonderful if the new systems made them more easily available. 

Thank you,

Mike Lissner
mike@free.law

[flp]: https://free.law/
[case]: https://www.courtlistener.com/pdf/2014/06/11/jose_l._uribe__maria_e._uribe_v._commissioner.pdf
[cite]: https://www.ustaxcourt.gov/taxpayer_info_after.htm#AFTER2

**Comment by JessicaMarine** [comment]
@mlissner Thank you for your interest in the US Tax Court's project.  We value your input and will certainly consider your suggestion when developing the new system.  Please feel free to provide further recommendations in the future.

**Comment by klohman** [comment]
### 40 Public-facing Docket Record Test Scenarios 

#### 1) Unauthenticated user accesses case from search results 
* Navigate to public search screen 
* Search for Case xxx-xx
Expected results 
- [ ] Navigates to Case xxx-xx - Case Detail 

#### 2) Unauthenticated user views public version of Case Detail 
* Scenario 1
* View Case Detail 
Expected results 
- [ ] Docket number and case name display in header 
- [ ] Docket record tab displays 
- [ ] Case Information tab is hidden 

#### 3) Unauthenticated user accesses court-issued document on docket record 
* Scenario 2
* Click on Order 
Expected result 
- [ ] Order PDF opens in new tab 

#### 4) Unauthenticated user cannot access externally filed documents from docket record 
* Scenario 2 
* View Motion 
Expected results 
- [ ] Motion docket entry does not have a link

**Comment by klohman** [comment]
### Public View - Case Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1c4ac062-122e-4c98-815e-eb797aa026a3)

* Docket record is sorted chronologically by date 
* Externally filed documents are not hyperlinked 
* Court-Issued documents are hyperlinked - open PDF in new tab

**Comment by matthopson** [comment]
@klohman Since we can return closed cases in search, should we have the case status in the header?
