### ISSUE TITLE
Docket Clerk: Seal an individual document from the public

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#4252]
As the Court, in order to protect the contents of a filing, we need the ability for a Docket Clerk to seal a individual document within a case from the public.

#5384 -- back-end work to allow the sealed flag at the document level

#9147 -- companion story to develop to seal a document from all users who are not Court employees

## Pre-Conditions:
#4251
#8998

## Acceptance Criteria:
* Docket Clerk has the ability to seal an individual document within a case.
* When sealing the document, the Docket clerk must explicitly indicate they are sealing the document from the public
* When a document is "Sealed from the public," it is only sealed (non-viewable) from the public.  Parties/practitioners/IRS counsel on the case can still view it.
* Court users can view "Sealed from the public" documents.
* Sealing an individual document does *not* seal the whole case.
* Docket record indicates whether or not a particular document is sealed, and to whom
* Sealing an Order from the public removes it from being returned as a result in an Order Search for the public
* Opinions cannot be sealed.

## Notes
* [User research study on sealing.](https://drive.google.com/file/d/1MhGcaIpT7TDfEO1t9HoZrQl1iv6F8lvX/view?usp=sharing)
* What is the desired visibility on the Docket Record for a sealed document w/r/t a public view? Do we display the entry with a sealed indicator, or omit the entry entirely? --- *The former*
* Are there other exceptions to what can be sealed other than Opinions? - *no*
* Deploy alongside #9147
* Need to test w/ IRS

## Tasks
- [x] Add Seal button - mob #9374
- [x] Add Seal Document Modal - mob #9374
- [x] Add tooltip on hover of the status column (sealed to the public) - mob #9382
- [x] Seal document permission - mob #9374
- [x] Seal Document endpoint - mob #9375
- [x] Migration?
  - [x] delete `hasSealedDocuments` off all Case entities - mob #9393 
  - [x] set `sealedTo` for `isLegacySealed` docket entries - mob #9393 
- [x] Fix externalUserOrderAdvancedSearch integration test  - mob #9393 
- [x] Remove hasSealedDocuments  - mob #9393 
- [x] Replace `isSealed` with `isDocketEntrySealed` and `isCaseSealed` in InternalDocumentSearchResult to make searchClient results clearer  - mob #9393 
- [x] Require `sealedTo` when `isSealed` is true - mob #9393 

## Test Cases
* Docket clerk seals document from public for a Case which is sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is sealed
* Docket clerk seals document from public for a Case which is not sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is not sealed
* Docket clerk seals Order from public for a Case which is sealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is sealed
* Docket clerk seals Order from public for a Case which is unsealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is not sealed

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
Reverse logic that if any document is "Sealed in Blackstone", the whole case is sealed. [Should this be it's own story? Maybe with the unseal a case story] - edited from original story

**Comment by swongCO** [comment]
![USTC Docket Record Seal Doc.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4f10d5f6-773c-4438-b7df-875906109c4e)

**Comment by swongCO** [comment]
![USTC Docket Record Seal modal.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e60d4920-c099-48b7-a1f8-ef39205c56f1)

- When Seal link is clicked, display modal
- The modal will have two options to choose from
- The first option (Seal to the public) will be selected by default

**Comment by swongCO** [comment]
![USTC Docket Record hover tips.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/2852ed38-2698-49be-8f22-1cd957404f81)

- When the user hovers over the Unseal link, display text to indicate the action and type of seal applied:
Unseal to the public and parties of this case
Unseal to the public
- **If this doesn't conflict with the current functionality,** in the status column, add hover text on the lock icon to indicate the type of seal applied:
Sealed to the public and parties of this case
Sealed to the public
- NOTE: only one hover tip will display at a time

**Comment by ttlenard** [comment]
**### Test Cases**


- Log in as docket clerk
- Navigate to a Sealed Case (ex: 11288-21)
- Click the blue "Seal" link on the far right column of docket index #1.
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- The first option "Seal to the Public" will be auto-selected by default - keep the default selection
- Select "Seal"

Expected results

- [ ] The modal will close, and a red lock icon will appear next to the document name on docket index #1
- [ ] The far right column will now have the text "Unseal" displayed as a Red link
- [ ] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public"
- [ ]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public"

**1. Docket clerk seals document from public for a Case which is sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is sealed**


**2. Docket clerk seals document from public for a Case which is not sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is not sealed**

**3. Docket clerk seals Order from public for a Case which is sealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is not sealed**

**4. Docket clerk seals Order from public for a Case which is unsealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is not sealed**

**Comment by rachelschneiderman** [comment]
After discussing with Chris and Tenille, legacy sealed docket entries will be migrated to be marked as sealed from the public.
