### ISSUE TITLE
Court: Send case message without document

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4293]
As a Court Employee, so that I can send a message that's case-related, I need the ability to send a message that's not tied to a document.

## Pre-Conditions

- #4294 completed - prototype and testing

## Acceptance Criteria
* Court user can create a message that's not tied to a document
* Court user can create a message that's tied to a case
* Court user can send the message to another court user
* Receiver of message can see the message sent to them
* Section the receiver is in can see the message that was sent

## Notes
* Launch create message modal, w/ free text subject line
* Don't need document section of modal
* Launch create message from the case level actions
* Add case detail tabs
* We discussed something related to the completed section, but would that come later (in the "complete" story?)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create new entity for new messages (Rachael #5389)
- [x] 2 Create persistence method to create a new message associated with a case (Rachael #5397)
- [x] 3 Create endpoint to create a new message (Rachael #5393)
- [x] 4 Add “Create New Message” to the actions dropdown on case detail header (Cody #5391)
- [x] 5 Create “Create New Message” modal (Cody #5391)
  - [x] 5a Dropdown functionality (select a section and recipient fills in) (Cody #5391)
  - [x] 5b Validation (Cody #5391)
- [x] 6 Sequences and actions to submit modal (Rachael #5397)
- [x] 7 Create Message Detail view and route (Rachael #5405)
- [x] 8 Create new tab at the top level navigation for new messaging (Rachael #5401)
- [x] 9 Create endpoint to retrieve a single message for message detail screen (Rachael #5398)
- [x] 10 Sequences, actions, computed for message detail screen (Rachael #5405)
- [x] 11 Create new messaging inbox, sent box, completed box views (Rachael #5401)
  - [x] 11a Tables, computeds (Matt #5412, #5416)
- [x] 12 Create endpoints to retrieve messages for new messaging boxes (Rachael #5409)
  - [x] 12a get user inbox
  - [x] 12b get section inbox (Rachael)
  - [x] 12c get user outbox (Rachael)
  - [x] 12d get section outbox (Rachael)
- [x] 13 Create new stack for messages (Rachael #5393)
- [x] 14 Create new elasticsearch index for messages (Rachael #5409)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### User Flow 
https://www.lucidchart.com/invitations/accept/e5ba5b28-1357-4b35-a1bc-465f5946dad3

#### Actions Dropdown 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8c7b62df-8721-4543-a671-c25ed06e4671)
* Add "Create New Message" to the actions dropdown on Case Detail header 


#### Create New Message modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/294beda9-c025-48e8-befa-637a0912ce8e)

* On click of Create New Message, the Create New Message modal displays 

**Select section**
* is required - no changes from current design/functionality 

**Select recipient**
* is required - no changes from current design/functionality 

**Subject line**
* is required 
* Error message if incomplete: "Enter a subject line" 
* Free text field 

**Add message**
* is required 
* Error message if incomplete: "Enter a message" 
* Free text field

**On Save**
* Modal closes and success message displays "Your message has been sent."
* Message is saved and associated with case 
* Message Detail screen is created 
* Message appears in Sent box for sending user and Section Sent box 
* Message appears in the recipient's My Messages Inbox, and the Section Messages Inbox 

#### Message Detail screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5acc7990-6597-4ad6-bcae-15c6945774aa)

**Comment by klohman** [comment]
### 4293 Test Scenarios 

#### 1) Internal user sees Create New Message in Actions dropdown 
* Login as internal user 
* Navigate to a case 
* Click on the “Actions” dropdown in header  
Expected results 
- [ ] Create New Message displays in Actions dropdown 

#### 2) Internal user is able to enter and view a subject line for a message 
* Login as ADC
* Navigate to case 
* Click Create New Message from Actions dropdown 
* Select docketclerk1 as recipient 
* Enter subject line
* Enter message 
* Click Send Message
* Navigate to My Messages > Sent 
Expected results 
- [ ] On click of Send Message, Modal closes and success message displays 
- [ ] Message with subject line entered by user displays in My Messages> Sent box 

#### 3)Internal user sends message without document attached to another internal user 
* Login as Judge Buch
* Navigate to case 
* Click Create New Message from Actions dropdown 
* Select docketclerk2 as recipient 
* Enter subject line
* Enter message 
* Click Send Message
* Navigate to My Messages > Sent 
Expected results 
- [ ] Modal closes and success message displays
- [ ] Message displays in Sent box 
- [ ] Message is associated at the case level and has no document attached

#### 4) Internal user sees received message in My Messages Inbox 
* Scenario 2 
* Login as docket clerk1
* View My Messages Inbox 
Expected results 
- [ ] New message from ADC to docketclerk1 displays in Section Messages Inbox 
- [ ] New message from Judge Buch to docketclerk2 displays in Section Messages Inbox
- [ ] Messages in inbox are sorted oldest to newest 

#### 5) Internal user sees received messages for all users in section in the Section Messages Inbox 
* Scenario 2 and 3
* Login as docket clerk3
* View Section Messages Inbox 
Expected results 
- [ ] New message from ADC displays in My Messages Inbox 
- [ ] Messages in inbox are sorted oldest to newest 

#### 5) Internal user views message details 
* Scenario 4
* Click on subject line link for new message from ADC 
* View message 
Expected results 
- [ ] App navigates to Message Detail screen 
- [ ] Sender, recipient, date/time, subject, and message text is displayed 
- [ ] No document is associated with message
