### ISSUE TITLE
Docket Clerk: Service for paper-scanned documents

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4295]
As a docket clerk, so that I can provide paper service for a paper-scanned document, I need the ability to print and mail the document. 

## Acceptance Criteria
* Docket Clerk can provide service (electronic and paper) for documents that are submitted in paper by parties in a case
* When serving a paper document, cover sheet should not be added until it's served
* If a docket entry has not been served, the docket record should say "Not Served"
* Docket Clerk has ability to save and serve a paper document immediately, or save for later
  * Implies that a Docket Clerk can come back to the document to serve it later

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- **Engineering**: see `followRedirectAction`
- The UI pieces are already present and computed in `shared/src/business/utilities/getFormattedCaseDetail.js` via `!result.isCourtIssuedDocument && result.isFileAttached === false;`-- double-check tests

## Tasks
- [x] Replace `Finish` with `Save and Serve` (Jojo #5805)
- [x] Replace `Save and Add Another` with `Save for Later` (Jojo #5805)
  - If no document present and click `Save and Serve`, show error message
- [x] Navigate to print paper receipt view on paper Docket Entry `Save and Serve` (Jojo/Kris #5805)
  - PDF note: address page first, coversheet, then document
- [x] Serve document on `Save and Serve`, add coversheet when the document is served (Jojo/Kris #5805)
  - Note: we have similar functionality somewhere
- [x] Remove `Add Another Entry` button (and its functionality)
- [x] Add `Save for Later` functionality
- [x] Add doc type to paper service preview view
- [x] UX feedback: save & serve bug on paper case (fails to complete QC on serve) (Jojo #5835)
- [x] UX feedback: show confirm modal for save & serve (Jojo #5870)
- [x] UX feedback: clear validation errors on submission on `save for later` (Jojo #5870)
- [x] UX feedback: no hyperlink on docket record for docket entry without document uploaded (Cody)
- [x] UX feedback: hyperlink for Internal Users on docket record for docket entry with document uploaded but not served; NO hyperlink for External parties for docket entry with document uploaded but not served (Cody)
- [x] UX feedback: Docket entry without document uploaded should NOT show in "Add Documents" dropdown for sending messages (Jojo #5882)
- [x] UX feedback: show served date and served parties on docket record for served documents (Jojo #5840)
- [x] UX feedback: show served stamp on pdf (Jojo #5840)
- [x] UX feedback: don't add coversheet on `save for later` (Jojo #5840)
- [x] UX feedback: Saved for Later - with document added- docket entry should show the yellow background and icon (same as incomplete entry without document uploaded (Jojo #5840)
- [x] UX feedback: Document should appear in the My Document /Section QC > In Progress box until it is served (it’s currently showing in the Processed box) (Jojo #5865)
- [x] UX feedback: Hyperlink from My Document/Section QC > Processed box should navigate to Case Detail > Document View (Cody)
- [x] UX feedback: If Saved for Later w/o Document then went back to add document and serve - Docket entry still shows the incomplete icon / color - should show as complete entry (Cody. #5858)
- [x] UX feedback - For pending docket entries, If a docket entry has not been served, the docket record should say "Not Served" - see design in comments (Cody #5847)
- [x] On save and serve - if paper parties are on the case, app should route to Print Paper Service Documents screen (Cody #5856)
- [x] UX feedback: preview document when editing/completing docket record (Jojo #5865)
- [x] UX feedback: remove warning when document is already attached (Jojo #5865)
- [x] UX feedback: verify functionality for documents that are not served is working correctly- see [url](https://github.com/flexion/ef-cms/issues/5525) (Jojo)
- [x] UX feedback: Date validation on save and serve for Received inconsistent (and annoying) (Jojo #5899)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo #5924)
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-02-17 at 8.30.53 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/5ae81b33-2929-4dc4-bca6-fc72686b51d8)![Screen Shot 2020-02-17 at 8.31.00 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/560bdc66-2031-44f5-acb3-041d1e8c5d5c)![Screen Shot 2020-02-17 at 8.31.08 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/1ccda3d0-afff-434a-8d7e-6f429dbbb4ab)![Screen Shot 2020-02-17 at 8.31.34 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/3d8363af-53ed-4b55-99fe-9154e95fd935)

**Comment by alsmith1** [comment]
####DRAFT TEST SCENARIOS####

## Test scenarios
#### Scenario 1 - Docket Clerk can provide service (electronic) for documents that are submitted in paper by parties in a case
1. Log in as a docket clerk
2. Navigate to an electronically filed Case
3. From the Actions button select add docket entry
4. Fill in the document information as usual from the paper document
5. Scan in the paper document
6. After Scans are complete click create PDF
7. Verify that the paper document has been scanned and page displays a pdf
8. Click Save and Serve
9. Verify page is redirected to the docket record and a success message displays
10. Verify that under served and parties on the document line in the docket record date and parties are entered

Expected result
- [ ] the paper document has been scanned and page displays a pdf
- [ ] page is redirected to the docket record and a success message displays
- [ ]  under served and parties on the document line in the docket record date and parties are entered


#### Scenario 2 - Docket Clerk can provide service (paper) for documents that are submitted in paper by parties in a case
1. Log in as a docket clerk
2. Navigate to a paper filed Case
3. From the Actions button select add docket entry
4. Fill in the document information as usual from the paper document
5. Scan in the paper document
6. After Scans are complete click create PDF
7. Verify that the paper document has been scanned and page displays a pdf
8. Click Save and Serve
9. Verify a modal displays stating paper service is required for the document
10. Click print now
11. Verify that a pdf screen displays with the document to be printed
12. From your browser print the document
13. Click the back button
14. Verify page is redirected to the docket record and a success message displays
15. Verify that under served and parties on the document line in the docket record date and parties are entered

Expected result
- [ ] the paper document has been scanned and page displays a pdf
- [ ] a modal displays stating paper service is required for the document
- [ ] a pdf screen displays with the document to be printed
- [  ] pdf can be printed
- [ ] page is redirected to the docket record and a success message displays
- [ ]  under served and parties on the document line in the docket record date and parties are entered

**Comment by alsmith1** [comment]
![Screen Shot 2020-07-07 at 9.44.11 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/566f236e-c819-4a6a-b0c9-d4902d7cab92)![Screen Shot 2020-07-07 at 9.44.18 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/903f3d7e-9c23-4be4-808d-1c4c8548089c)![Screen Shot 2020-07-07 at 9.44.24 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/d9647ca5-79ad-4d0a-aca1-acbfaae31b08)

**Comment by alsmith1** [comment]
![Screen Shot 2020-07-07 at 9.44.11 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/138bdeec-e0e5-494b-a421-8082edc2fc09)
![Screen Shot 2020-07-07 at 9.44.18 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/cc06ae08-c0c4-4d58-b25d-ed9ffae955a0)![Screen Shot 2020-07-07 at 9.44.24 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/e6efa0fd-3f20-44f9-9e82-e344d624ebc4)

**Comment by klohman** [comment]
UX feedback
- Incomplete docket entry - when “Saved for Later” without document uploaded
    - the docket entry should not be hyperlinked 


- Saved for Later - with document added
    - docket entry should show the yellow background and icon (same as incomplete entry without document uploaded
    - docket entry should not be hyperlinked until served.
    - Document should appear in the My Document /Section QC > In Progress box until it is served (it’s currently showing in the Processed box) 
    - Cover sheet should not be applied until the document is served 

- On Save and Serve 
    - getting an error message when serving (but the document is still showing on the docket record) 
    - On click of Save and Serve, we should display the service confirmation modal and make the user confirm before actually serving  (use the “Are You Ready to Initiate Service?” Modal)
    - Served date and served Parties should populate on docket entry when served 
    - Served stamp should be applied to cover sheet 
    - Unable to test service emails and the navigation to “Print” screen because of errors 

Saved for Later w/o Document
    - Should not trigger error “Upload a Document” (if you click Save and Serve and get error and then click Save for Later, displaying error still)


- Saved for Later w/o Document then went back to add document and serve 
    - Docket entry still shows the incomplete icon / color
    - Document link from Processed box should navigate to Case Detail > Document View (it’s currently still navigates to Edit)

**Comment by klohman** [comment]
## Updated Test Scenarios 
Test data 
* Case xx1-20
    * Petitioner = paper service 
* Case xx2-20
    * Petitioner = electronic service 


#### 1) Docket clerk adds docket entry for paper document without PDF uploaded and saves
* Login as docket clerk 
* Navigate to case xx1-20
* Click Add Docket Entry from Actions menu
* Select “Administrative Record” as doc type 
* Complete form but do not upload PDF 
* Click Save for Later 
Expected results 
- [ ] App navigates to Case Detail > Docket Record with success message displayed 
- [ ] Administrative Record displays on Docket Record as pending entry (yellow icon, etc.)
- [ ] Administrative Record entry displays “Not Served” under Served column 
- [ ] Administrative Record is not hyperlinked 
- [ ] Administrative Record displays in My Document / Section Document QC > In Progress

#### 2) Docket clerk adds docket entry for paper document with PDF uploaded and saves 
* Login as docket clerk 
* Navigate to case xx1-20
* Click Add Docket Entry from Actions menu
* Select “Motion for New Trial” as doc type 
* Complete form and upload PDF 
* Click Save for Later 
Expected results 
- [ ] App navigates to Case Detail > Docket Record with success message displayed 
- [ ] Motion for New Trial displays on Docket Record as pending entry 
- [ ] Motion for New Trial entry displays “Not Served” under Served column 
- [ ] Motion for New Trial is hyperlinked for internal users and navigates to Document View 
- [ ] Motion for New Trial entry is visible for external parties but not hyperlinked
- [ ] Motion for New Trial displays in My Document / Section Document QC > In Progress
- [ ] Motion for New Trial PDF does not display cover sheet 

#### 3a) Docket clerk adds docket entry for paper document (PDF uploaded) in case with paper service parties and saves and serves 
* Login as docket clerk 
* Navigate to case xx1-20 
* Click Add Docket Entry from Actions menu
* Select “Motion for Continuance” as doc type 
* Complete form and upload PDF 
* Click Save and Serve 
* Confirm service on modal 
Expected results 
On click of Save and Serve, 
- [ ] display “Are you sure you want to initiate service” modal 
On click of “Yes,  Serve”
- [ ] App navigates to Print Paper Service Document screen with PDF in viewer 
- [ ] PDF on Print Paper Service screen displays Address Page, Cover Sheet, and original document 
- [ ] Cover sheet includes Served stamp with date 
- [ ] Motion for Continuance entry displays served date and parties (“B”) on docket entry
- [ ] Motion for Continuance entry displays blue “paper document” icon
- [ ] Motion for Continuance is hyperlinked on docket entry and navigates to Document View
- [ ] Motion for Continuance displays in My Document / Section Document QC > Processed 

#### 3b) Docket clerk adds docket entry for paper document (PDF uploaded) in case with paper service parties and saves and serves (after print)
* Scenario 3a
* Click “Done” on Print Paper Service Documents screen 
Expected results: 
- [ ] App navigates to Case Detail> Docket Record with success message displayed 

#### 4) Docket clerk adds docket entry for paper document (PDF uploaded) in case without paper service parties and saves and serves 
* Login as docket clerk 
* Navigate to case xx2-20 
* Click Add Docket Entry from Actions menu
* Select “Answer” as doc type 
* Complete form and upload PDF 
* Click Save and Serve 
* Confirm service on modal 
Expected results 
On click of Save and Serve, 
- [ ] display “Are you sure you want to initiate service” modal 
On click of “Yes,  Serve”
- [ ] App navigates to Case Detail> Docket Record with success message displayed  
- [ ] Cover sheet is added to PDF and includes Served stamp with date 
- [ ] Answer entry displays served date and parties (“B”) on docket entry
- [ ] Answer entry displays blue “paper document” icon
- [ ] Answer is hyperlinked on docket entry and navigates to Document View 
- [ ] Answer displays in My Document / Section Document QC > Processed 

#### 5) External parties can view docket entries for un-served documents but cannot access PDF
* Login as privatePractitioner 
* Search for case xx1-20 
* Click Request Access 
* Complete Form
* View Docket Record 
Expected results 
- [ ] Administrative Record entry displays on docket record with “Not Served” 
- [ ] Administrative Record is not hyperlinked 
- [ ] Motion for New Trial entry displays on docket record with “Not Served”
- [ ] Motion for New Trial is not hyperlinked 

#### 6) Docket clerk serves a document that was saved for later (without document uploaded) 
* Scenario 1 
*  Navigate to My Document QC > In Progress 
* Click on Administrative Record 
* Upload PDF 
* Click Save and Serve 
* Click Yes, Serve from modal
* Click “Done” on Print Document screen
Expected results 
On click of Administrative Record from My Document QC > In Progress:
- [ ] App navigates to Edit Docket Entry screen with warning message displayed 
On click of Yes, Serve on modal:
- [ ] App navigates to Print Paper Documents screen 
On click of Done: 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Administrative Record docket entry no longer displays as pending (with yellow icon, etc.) or Not Served message
- [ ] Administrative Record entry displays served date and parties (B) 
- [ ] Administrative Record entry is hyperlinked and navigates to Document View 
- [ ] Administrative Record PDF includes cover sheet with served stamp applied 
- [ ] Administrative Record no longer displays in My. Document QC/ Section Document QC > In Progress
- [ ] Administrative Record displays in My. Document QC/ Section Document QC > Processed 

#### 7) Docket clerk serves a document that was saved for later (with document uploaded) 
* Scenario 2 
*  Navigate to My Document QC > In Progress 
* Click on Motion for New Trial  
* Click Save and Serve 
* Click Yes, Serve from modal
* Click “Done” on Print Document screen
Expected results 
On click of Motion for New Trial  from My Document QC > In Progress:
- [ ] App navigates to Edit Docket Entry screen without warning message displayed 
- [ ] PDF preview displayed the uploaded document 
On click of Yes, Serve on modal:
- [ ] App navigates to Print Paper Documents screen 
On click of Done: 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Motion for New Trial docket entry no longer displays as pending (with yellow icon, etc.) or Not Served message
- [ ] Motion for New Trial entry displays served date and parties (B) 
- [ ] Motion for New Trial entry is hyperlinked and navigates to Document View 
- [ ] Motion for New Trial PDF includes cover sheet with served stamp applied 
- [ ] Motion for New Trial no longer displays in My. Document QC/ Section Document QC > In Progress
- [ ] Motion for New Trial displays in My. Document QC/ Section Document QC > Processed 

#### 8) External parties can view docket entries for served documents but cannot access PDF
* Scenario 7
* Login as privatePractitioner 
* Search for case xx1-20 
* View Docket Record 
Expected results 
- [ ] Motion for New Trial entry displays on docket record with served date and parties (B)
- [ ] Motion for New Trial is hyperlinked and opens PDF in new tab
