### ISSUE TITLE
Upload PDF documents to the system

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#436]
As a Judge or other Court User, in order to issue an order or other document that I've generated outside of the system, I need the ability to upload a PDF document to the system.

## Pre-Conditions
* Court person has created a document in PDF format outside of the system

## Acceptance Criteria
* Court User can upload a PDF document to the system
* Uploaded PDF document should be uploaded to the "Draft Documents" tab of the system
* Once uploaded, a PDF document should be treated the same as a document created in the system (be signed, send messages, create docket entry, served, etc.)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Allow all functionality that we have for draft documents to remain
* For MVP, don't worry about direct scanning

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical  (all functionality internal)
 - [x] New screens have been added to pa11y scripts (William/Rachel #4373)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (William/Rachel/Kris #4373)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (William/Rachel #4373)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (all screens internal)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
--- draft wireframes ![Screen Shot 2020-01-14 at 2.57.40 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/ea5ece76-bac9-4fb8-89cd-fbc490a88bc2)![Screen Shot 2020-01-14 at 4.37.21 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/06b65292-fcbf-40a8-bfaa-6378ff03edcc)----

**Comment by alsmith1** [comment]
---DRAFT---

## Test scenarios
#### Scenario 1 - Court User can upload a PDF document to the system
1. Login as an internal user
2. Choose a case in which to add a notice/order etc
3. Click on the actions button and select create order or notice
4. Verify that create order or notice modal displays
5. Select an option from the modal drop down
6. Verify that the Create Order/Notice page displays
7. Verify on the left side New header “ Document info” displays
8. Verify under document info a box with two tabs displays showing create document and upload document
9. Verify that in the Create document tab you are able to copy and paste copy or freeform enter text
10. Verify that while entering in text it appears in the quick preview on refresh
11. On the upload document tab choose a document to upload and click save
12. Verify after save the quick preview displays the uploaded pdf.

Expected result
- [ ] create order or notice modal displays
- [ ] the Create Order/Notice page displays
- [ ] on the left side New header “ Document info” displays
- [ ] under document info a box with two tabs displays showing create document and upload document
- [ ] in the Create document tab you are able to copy and paste copy or freeform enter text
- [ ] while entering in text it appears in the quick preview on refresh
- [ ] Document is uploaded
- [ ]  document displays in the quick preview pane


#### Scenario 2 - Uploaded PDF document should be uploaded to the "Draft Documents" tab of the system
1. Login as an internal user
2. Choose a case in which to add a notice/order etc
3. Click on the actions button and select create order or notice
4. Verify that create order or notice modal displays
5. Select an option from the modal drop down
6. Verify that the Create Order/Notice page displays
7. Verify on the left side New header “ Document info” displays
8. Verify under document info a box with two tabs displays showing create document and upload document
9. Verify that in the Create document tab you are able to copy and paste copy or freeform enter text
10. Verify that while entering in text it appears in the quick preview on refresh
11. On the upload document tab choose a document to upload and click save
12. Verify after save the quick preview displays the uploaded pdf.
13. Navigate to the docket record and click on the in progress tab
14. Verify that the notice/order… appears under draft documents

Expected result
- [ ] create order or notice modal displays
- [ ] the Create Order/Notice page displays
- [ ] on the left side New header “ Document info” displays
- [ ] under document info a box with two tabs displays showing create document and upload document
- [ ] in the Create document tab you are able to copy and paste copy or freeform enter text
- [ ] while entering in text it appears in the quick preview on refresh
- [ ] Document is uploaded
- [ ]  document displays in the quick preview pane
- [ ] notice/order… appears under draft documents


#### Scenario 3 - Once uploaded, a PDF document should be treated the same as a document created in the system (be signed, send messages, create docket entry, served, etc.)
1. Login as an internal user
2. Choose a case in which to add a notice/order etc
3. Click on the actions button and select create order or notice
4. Verify that create order or notice modal displays
5. Select an option from the modal drop down
6. Verify that the Create Order/Notice page displays
7. Verify on the left side New header “ Document info” displays
8. Verify under document info a box with two tabs displays showing create document and upload document
9. Verify that in the Create document tab you are able to copy and paste copy or freeform enter text
10. Verify that while entering in text it appears in the quick preview on refresh
11. On the upload document tab choose a document to upload and click save
12. Verify after save the quick preview displays the uploaded pdf.
13. Navigate to the docket record and click on the in progress tab
14. Verify that the notice/order… appears under draft documents
15. Verify that you are able to apply signature, send messages, create docket entry and serve the document


Expected result
- [ ] create order or notice modal displays
- [ ] the Create Order/Notice page displays
- [ ] on the left side New header “ Document info” displays
- [ ] under document info a box with two tabs displays showing create document and upload document
- [ ] in the Create document tab you are able to copy and paste copy or freeform enter text
- [ ] while entering in text it appears in the quick preview on refresh
- [ ] Document is uploaded
- [ ]  document displays in the quick preview pane
- [ ] notice/order… appears under draft documents
- [ ] apply signature, send messages, create docket entry and serve the document are all accessible
