### ISSUE TITLE
Court User: Ability to search and return results for attorneys

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4365]
As a court user, so that I may determine if attorneys are registered with the court, I need the ability to search for attorneys and see their data.

## Acceptance Criteria
* Court user can search for an attorney by name and by bar number- discuss combined name field + elastic search
* Court user can see attorney data in the system (one of the fields admitted/not admitted)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create search results table view, paging (Rachael #4855)
- [x] 2 Create endpoint to get search results by name (using elasticsearch) (Rachael #4854)
- [x] 3 Sequences, actions to submit a search (Rachael #4855)
- [x] 4 Create practitioner detail view, route, sequence, computed for formatting (Matt, Cody #4865)
- [x] 5 Create endpoint to get practitioner details (Matt #4865)
- [x] 6 Sequences, actions to get practitioner details and route to page (Matt #4865)
- [x] 7 Add valid admissions statuses to Attorney entity and validation (Rachael #4857)
- [x] 8 Fix Clear Search buttons on practitioner search (Rachael #4859)
- [x] 9 Refactoring: rename Attorney -> Practitioner throughout (createAttorneyUser, updateAttorneyUser, etc) (Rachael #4863)
- [x] 10 Case-sensitivity in bar number search (Rachael #4874)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html  (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Matt)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Search for Attorney 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c0634418-29d6-4df1-a50f-ad03cc085f71)

**Search by name**
*  should search First Name and Last Name fields 
* matching results should be sorted by relevancy 
* display matching results even if there is an exact match 

**Search by bar number** 
* if there is exact match, navigate to Practitioner Info page (design to be implemented in 4365)
*if there is no exact match, display "No matching results"

**Comment by klohman** [comment]
### 4365 Test Scenarios 

#### 1) Internal user searches for attorney by name with matching results 
* Login as internal user 
* Navigate to Advanced Search > Practitioner 
* Enter [practitioner name] in search field and click Search 

Expected results 
- [ ] Matching attorneys display in table, sorted by relevancy 

#### 2) Internal user searches for attorney by bar number with exact match 
* Login as internal user 
* Navigate to Advanced Search > Practitioner 
* Enter [bar number] in search field and click Search 

Expected results 
- [ ] App navigates to Practitioner Detail screen 

#### 3) Internal user searches for attorney by bar number without exact match 
* Login as internal user 
* Navigate to Advanced Search > Practitioner 
* Enter [bar number] in search field and click Search 
 Expected results 
- [ ] “No matching results” message displays 
- [ ] entered bar number remains in search field 

#### 4) Internal user views attorney information 
* Scenario 1 
* Click on bar number link

Expected results 
- [ ] App navigates to Practitioner Detail screen 
- [ ] Practitioner Detail screen displays attorney information from database 

#### 5) Internal user clears search terms on name 
* Login as internal user 
* Navigate to Advanced Search > Practitioner 
* Enter [practitioner name] in search field and click Search 
* Click “Clear search” button on Search by Name section 

Expected results 
- [ ] Name field is set back to default  
- [ ] Matching results are hidden 

#### 6) Internal user clears search terms on bar number 
* Login as internal user 
* Navigate to Advanced Search > Practitioner 
* Enter [bar number with no exact match] in search field and click Search 
* Click “Clear search” button on Search by Bar Number section 

Expected results 
- [ ] Bar number field is set back to default  
- [ ] No matching results message is  hidden

**Comment by klohman** [comment]
UX review comments 
- Practitioner name is not displaying “Middle name” or “Suffix” in search results or on Practitioner Detail - we need to display [First Name] [Middle Name[ [Last Name] [Suffix] - see MM20012 - I entered name as Mickey Bob Mouse Sr. 
- Sort multiple exact matches by bar number (oldest to newest) 
- Partial matches aren’t displaying- search for “Don” does not bring back “Donald Duck” - I believe this was the way case search was working previously?

**Comment by matthopson** [comment]
**UX Feedback**
- [ ] 1 - Practitioner name is not displaying “Middle name” or “Suffix” in search results or on Practitioner Detail - we need to display [First Name] [Middle Name[ [Last Name] [Suffix] - see MM20012 - I entered name as Mickey Bob Mouse Sr. 
- [ ] 2 - Sort multiple exact matches by bar number (oldest to newest) 
- [ ] 3 - Partial matches aren’t displaying- search for “Don” does not bring back “Donald Duck” - I believe this was the way case search was working previously?
