### ISSUE TITLE
Admissions Clerk: Update Attorney data in Attorney Database

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4366]
As an Admissions Clerk, so that I may ensure the data in the practitioner/respondent database is accurate, I need the ability to edit and save practitioner data.

## Acceptance Criteria
* New Admissions Clerk role is created
* Admissions Clerk can edit and save Attorney data within the database
* Where attorney data currently displays, updated data displays in all open cases and any case that has been closed for 6 months or less
* When an attorney makes a change to their contact information on their dashboard, it updates the database [this is already done]
* When either the Admissions Clerk or Attorney updates their data, a notice of change of address is generated, added to docket record and served to parties in the case (only on open cases or those closed for 6 mo or less)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Don't allow editing of email address
* Only data that displays is address and phone number
* Just updating what displays in the UI for this story. Any ties to Cognito or login are not part of this story. 

## Tasks
- [x] 1 Add Edit link to practitioner detail view for admissions clerks only (Rachael #4926)
- [x] 2 Move form elements from Add Practitioner form into separate component to be reused for editing (Rachael #4927)
- [x] 3 Create Edit Practitioner Details view and route (Rachael #4927)
- [x] 4 Create endpoint for editing practitioner details (Cody)
- [x] 5 Sequences, actions for validating and submitting the form (Rachael #4927)
- [x] 6 If address and/or phone number are changed, create a Notice of Change of Address/Phone on associated cases; also update practitioner data on all associated cases (#4928 Cody)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Practitioner Detail - Edit view 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c1e29dc-68d9-45fd-86b3-287bb86aa723)

* Edit link displays for Admissions clerk role only 
* Edit link is hidden for all other user roles 

#### Edit Practitioner Details in Database
* on click of Edit link, navigate to Edit Practitioner Detail screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/245e2f9f-6f38-4534-87f9-ad8a23b704b0)

* All current practitioner metadata from DB should display in fields 
* All fields should be editable except Email address and Bar number 

**Email address**
* Display primary email address read-only 

**Admission status** 
* Options include Active, Suspended, Disbarred, Resigned, Deceases, Inactive 

**If admission status is changed to Suspended, Disbarred, Resigned, Deceases, or Inactive**
* Practitioner role changes to "inactive practitioner" in Cognito
* Practitioner is not visible in "Add Petitioner Counsel" or "Add Respondent Counsel" searches 

**if admission status is changed to "Active"**
* Practitioner role changes to "practitioner" in Cognito 
* Practitioner is not visible in "Add Petitioner Counsel" or "Add Respondent Counsel" searches 

**Address and Phone Number (primary)**
If Address is changed in DB: 
* a Notice of Address Change is generated and displays on docket record for all cases associated with the practitioner 
* Updated address displays on "Practitioner Dashboard" and "Edit Contact Information" form 

If primary Phone number is changed in DB: 
* a Notice of Telephone Number is generated and displays on docket record for all cases associated with the practitioner 
* Updated phone number displays on "Practitioner Dashboard" and "Edit Contact Information" form 

If Address and primary Telephone number are changed in DB: 
* a Notice of Address and Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner 
* Updated address and phone number displays on "Practitioner Dashboard" and "Edit Contact Information" form 

#### Practitioner User - Edit Contact Info 

If Address is changed by practitioner user on Edit Contact Information screen: 
* a Notice of Address Change is generated and displays on docket record for all cases associated with the practitioner 
* Updated address displays in Practitioner DB 

If primary Phone number is changed by practitioner user on Edit Contact Information screen: 
* a Notice of Telephone Number is generated and displays on docket record for all cases associated with the practitioner 
* Updated phone number displays on Practitioner DB 

If Address and primary Telephone number are changed by practitioner user on Edit Contact Information screen 
* a Notice of Address and Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner 
* Updated address and phone number displays on Practitioner  Database

**Comment by klohman** [comment]
### Test Cases 4366 

#### 1) Admissions clerk can edit practitioner details in database 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Click Edit 
* Update admission date
* Save 
Expected results
- [ ] Edit button displays on Practitioner Detail 
- [ ] On click of Edit, app navigates to Edit Practitioner form 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed 
- [ ] Updated information displays on Practitioner Detail screen 

#### 2) Admissions clerk cannot edit practitioner primary email 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
Expected	Results 
- [ ] Primary email address is displayed as read-only and cannot be edited 

#### 3) Admissions clerk changes practitioner admission status from active to suspended, disbarred, signed, deceased, or inactive 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Update admission status to [suspended, disbarred, signed, deceased,  inactive]
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed 
- [ ] Updated admission status displays on Practitioner Detail screen 
- [ ] Practitioner user role is updated to “inactive practitioner” in Cognito 
- [ ] Practitioner user is directed to Inactive Practitioner landing page when logged in and cannot access any case information

#### 4) Admissions clerk changes practitioner admission status from suspended, disbarred, signed, deceased, or inactive to “active” 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Update admission status to Active
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed 
- [ ] Updated admission status displays on Practitioner Detail screen 
- [ ] Practitioner user role is updated to “practitioner” in Cognito 
- [ ] Practitioner user is directed to dashboard on login

#### 5) Admissions clerk changes practitioner address in database 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Update practitioner address
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed
- [ ] a Notice of Address Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated address displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 6) Admissions clerk changes practitioner primary telephone number in database 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Update practitioner primary telephone number
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed
- [ ] a Notice of Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated phone number displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 7) Admissions clerk changes practitioner address and primary telephone number in database 
* Login as Admissions clerk 
* Navigate to Advanced Search > Practitioner tab 
* Search for an existing practitioner 
* View Practitioner Details
* Update practitioner address and primary phone number
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner Detail screen with success message displayed
- [ ] a Notice of Address and Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated address and phone number displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 8) Practitioner user changes their address from their dashboard 
* Login as practitioner user 
* Click Edit under My Contact Information
* Update address 
* Save 
Expected results 
- [ ] on save, app navigates back to Dashboard with success message displayed 
- [ ] a Notice of Address Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated address displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 9) Practitioner user changes their phone number from their dashboard 
* Login as practitioner user 
* Click Edit under My Contact Information
* Update phone number 
* Save 
Expected results 
- [ ] on save, app navigates back to Practitioner dashboard screen with success message displayed
- [ ] a Notice of Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated phone number displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 10) Practitioner user changes their address and phone number from their dashboard 
* Login as practitioner user 
* Click Edit under My Contact Information
* Update address and phone number 
* Save 
Expected results 
- [ ] a Notice of Address and Telephone Number Change is generated and displays on docket record for all cases associated with the practitioner
- [ ] Updated address and phone number displays on "Practitioner Dashboard" , "Edit Contact Information" form, and on the Case Detail > Petitioner Counsel section of all cases the practitioner is associated with

#### 11) Docket clerk cannot add inactive practitioner to a case 
* Login as docket clerk 
* Navigate to Case Detail > Case Information> Petitioner 
* Under Petitioner Counsel, search for an inactive practitioner in DB
Expected results 
- [ ] no matching results are displayed
