### ISSUE TITLE
Admissions Clerk: Ability to add Attorneys to the Attorney Database

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4367]
As an Admissions Clerk,  so I can ensure the accuracy of the Attorney Database, I need the ability to add new Attorneys to the database. 

## Acceptance Criteria
* Admissions Clerk can add a new Attorneys to the database
* New Attorneys are assigned an auto-generated Bar No. 
* Auto-generated Bar No. needs to be unique for each attorney 
* Adding an Attorney to this stand-alone database will create an active user in Cognito

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Admission date - date they were admitted to the tax court bar, not the date they were added to the system
* Bar Number Format -----  {Last_Initial}{First_Initial}{YY}{count}; where count is a 3-digit number that resets and starts at 001 each year and is the cumulative number of new practictioners for a given for that year.
   * Example: Matt Hopson is the 10th new practitioner created in 2021, his bar number would be `HM21010`

## Tasks
- [x] 1 Add Practitioner button (Admissions Clerk only) and Add Practitioner form view (modify / reuse current create practitioner flow?) (Cody #4884)
- [x] 2 Submit add practitioner (use existing if possible? Cody #4897)
- [x] 3 Generate bar number and make required on practitioner? (Matt #4880)
- [x] 4 Create practitioner validation (Team mob #4892 #4894)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Advanced Search > Practitioner tab 
* Add button "Add New Practitioner" 
* Button is displayed for users with Admissions Clerk role only 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e38549ea-6857-45cd-b29d-25ea165eb4f6)

#### Add New Practitioner form 
* On click of "Add New Practitioner" button, navigate to Add New Practitioner Form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b5574871-8883-4085-b0ab-f77c5086bde0)

**Practitioner Name**
* for input only, practitioner name should be entered as First Name, Middle Name, Last Name, Suffix 
* First Name, Last Name are required 
* Required fields - if incomplete on submit, display error "Enter first name" ; "Enter last name";  
* Middle name - optional 
* Suffix field - optional 
* System should automatically assign a Bar number in format (TBD - need exact Court rules) 

**Birth year**
* Required field 
* Valid format - Four digit year 
* Error message if incomplete " Enter a valid birth year" 

**Practitioner type**
* Options are Attorney or Non-attorney 
* Required field 
* Error message if incomplete on submit : "Select a practitioner type" 

**Employer**
* Options are Private, IRS, or DOJ 
* Required field 
* Error message if incomplete on submit : "Select an employer" 

**Firm name** 
* Required field 
* Error message if incomplete on submit : "Enter a firm name" 

**Contact fields**
* use standard address, contact, and phone fields and functionality 

**Email** 
* required field 
* will be the login email for Cognito 

**Original bar state**
* Dropdown should include all options from standard State dropdown and a "N/A" option 

**Admission status**
* Field should display "Active" as read-only in form 

**Other admission statuses for Bulk Import**
Admission clerks will only be adding Active attorneys to the DB on an individual basis. When we do the initial import of attorneys, all attorneys will be created in the DB, but only active attorneys will be created in Cognito. 

* Active - attorney should be added to the DB and as an active user in Cognito 
* Suspended - attorney should be added to the DB only 
* Disbarred -  attorney should be added to the DB only 
* Resigned -  attorney should be added to the DB only 
* Deceased -  attorney should be added to the DB only 
* Inactive -  attorney should be added to the DB only 

**Admission date** 
* Field is required
* Error message if incomplete on submit: "Enter an admission date"  
* Date Cannot be in the future - error message "Date cannot be in the future. Enter valid admission date."

**On Submit** 
* new attorney is created in the DB with automated bar number generated 
* user is navigated to the Practitioner Detail screen with success message displayed 

#### Practitioner Detail screen 
* header displays practitioner name, bar number, and admission status (as label) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc09b6cb-be02-48bf-8a2b-59b923d8870c)

**Comment by klohman** [comment]
### Test Scenarios 4367 

#### 1) Admissions clerk adds new attorney to the Practitioner database 
* Login as admissions clerk 
* Navigate to Advanced Search > Practitioner 
* Click on “Add New Practitioner” 
* Complete form and click “Add Practitioner” 

Expected results 
- [ ] App navigates to Practitioner Detail screen with success message displayed 
- [ ] Practitioner info entered in form is displayed on Practitioner Detail screen 
- [ ] Auto-generated bar number is displayed on Practitioner Detail screen 

#### 2) New attorney is able to access the application
* Scenario 1 
* Access Cognito email as practitioner  
* Change password 
* Login to ef-cms 

Expected results 
- [ ]Upon account creation, Practitioner receives email from Cognito with username and temporary password 
- [ ] Practitioner is able to change password through Cognito interface 
- [ ] Practitioner logs into system and views dashboard 

#### 3) Internal users can search and view new attorney in Practitioner database 
* Scenario 1 
* Login as docket clerk 
* Search for [practitioner name]
* Search for [practitioner bar number] 

Expected results 
- [ ] Name search displays matching result for new practitioner 
- [ ] Bar number search navigates to new practitioner detail screen

**Comment by klohman** [comment]
UX review comments 
- Need to add the “optional” label to Firm name 
- On submit of Add Practitioner form, should route user to Practitioner Detail screen with success message - currently it’s routing back to Practitioner Search 
- New practitioner is not receiving Cognito confirmation email (used flexionustc@gmail.com for Donald Duck- no email)- unable to login in as new practitioner 
- Practitioner name is not displaying Middle name of Suffix in search results or on Practitioner Detail - we need to display [First Name] [Middle Name[ [Last Name] [Suffix] - see MM20012 - I entered name as Mickey Bob Mouse Sr. 
- Error message for Admission Date - if in future - “Admission date cannot be in the future. Enter a valid date.”
- Error message for Birth year - if in future - “Birth year cannot be in the future. Enter a valid year.”
- Updated design (confirmed with Jessica) 
    - If Private is selected as Employer - Firm name field is optional and free text field - displays on Practitioner detail with either “None” (if blank) or the entered text 
    - If DOJ is selected as Employer - Firm name field is hidden  - displays on Practitioner detail screen a “None” 
    - If IRS is selected as Employer - Firm name is hidden - displays on Practitioner detail screen a “None”

**Comment by matthopson** [comment]
**UX Feedback**

- [ ] 1 - Need to add the “optional” label to Firm name 
- [ ] 2 - On submit of Add Practitioner form, should route user to Practitioner Detail screen with success message - currently it’s routing back to Practitioner Search 
- [ ] 3 - New practitioner is not receiving Cognito confirmation email (used flexionustc@gmail.com for Donald Duck- no email)- unable to login in as new practitioner 
- [ ] 4 - Practitioner name is not displaying Middle name of Suffix in search results or on Practitioner Detail - we need to display [First Name] [Middle Name[ [Last Name] [Suffix] - see MM20012 - I entered name as Mickey Bob Mouse Sr. 
- [ ] 5 - Error message for Admission Date - if in future - “Admission date cannot be in the future. Enter a valid date.”
- [ ] 6 - Error message for Birth year - if in future - “Birth year cannot be in the future. Enter a valid year.”
- [ ] 7 - Updated design (confirmed with Jessica) 
- [ ] 8 - If Private is selected as Employer - Firm name field is optional and free text field - displays on Practitioner detail with either “None” (if blank) or the entered text 
- [ ] 9 - If DOJ is selected as Employer - Firm name field is hidden - displays on Practitioner detail screen a “None” 
- [ ] 10 - If IRS is selected as Employer - Firm name is hidden - displays on Practitioner detail screen a “None”
