### ISSUE TITLE
Petitions: Create Order in the system and save to docket record 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#437]
As a Petitions Clerk, in order to notify a Petitioner that they need to provide additional information, I need the ability to issue an order in the system.

When a Petitioner files a Petition, it is often missing some of the information that the Court needs.  To direct the Petitioner to file/submit the missing information, the Petitions Clerks will issue an Order to Petitioner.

## Pre-Conditions
* Petitions Clerk has received a petition that does not have all the information needed

## Acceptance Criteria
* Petitions Clerk can create an order in the system from a system-generated template
* Order template contains standard content derived dynamically from system data
* Petitions Clerk clerk type order content into a free form text field
* Petitions Clerk can perform basic content editing, such as bolding, underline and italics. {Need to define exactly what "basic" is so we're all on the same page}
* Petitions Clerk can preview the document while editing
* Petitions clerk can save completed order
* A docket entry (is created, can be created) for the newly created order (Can be simple language "Order"; Will be handled in another story).
* The docket entry should link to the PDF
* Need ability to copy and paste with out stripping formatting (formatting to be defined)

## Notes
* This story does not include save and continue function (Draft State). Save and continue/Draft state is needed, but will be handled in another story. 
* Court users cannot edit header content or order template
* Jessica will put together a list of the different types of Orders and decisions
https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing
* The order is generated as a PDF. This does not require a cover sheet
* With pasting from WP, it didn't retain the formatting. Court will be required to use Word. 

## Tasks
- [x] List of requirements from a tech text editors (Kristen)
- [x] List of rich text editors: feature compatibility 
- [x] Set of example order PDFs (Jessica)
- [x] POC of in-browser PDF generated from rich text editor content
- [x] Add Create Order button, route, and basic screen so we have somewhere to test possible text editors (Rachael #2150)
- [x] Customize toolbar for Quill editor (Rachael #2162)
- [x] Fix underline (Rachael, William)
- [x] Set default font on PDF to Times New Roman (Rachael #2167)
- [x] Test orders with and actual Word document (Mariah)
- [x] Isolate styles from rest of application (Kris)
- [x] Fix multiple new lines
- [x] Generate PDF server side (William #2176)
  - [x] Refactor Utility into Use Case (William #2176)
- [x] Get lambda layer configured correctly (William and Rachael)
- [x] Print - set up print media rules to produce headers on correct pages (Kris, Rachael #2178)
- [x] Integrate, so working on dev (William #2217)
- [x] Handle pdf binary type (William #2218)
- [x] Clean up PDF formatting (Rachael, Kris)
  - [x] insert spaces for tabs (#2187)
  - [x] increasing/decreasing font size is not working (#2187)
  - [x] footer margin on every page after the first (#2187)
  - [x] docket number dynamically generated from case detail (#2188)
  - [x] docket number on right side of first page header, clean up formatting on first page header
- [x] Clean up Create Order view (Rachael #2193)
- [x] Create entity for orders (Rachael #2197)
- [x] Create Order-Type Modal Dialog (Kris, Rachael #2222 #2224 #2226)
  - [x] validate modal using OrderWithoutBody entity (Rachael #2228)
- [x] Show form cancel modal when Cancel button is clicked from the Create Order page (Rachael #2206)
- [x] Create actions and sequence to submit order(William #2232)
- [x] Move order template into a separate html file that can be imported; fix associated jest issues (Rachael #2231)
- [x] On Refresh direct to case detail with modal (William #2236)
- [x] ~Update success alert if needed~
- [x] If form is not pristine regenerate on submission (William #2236)
- [x] Case journey test (Rachael #2244)
- [x] Fix font issues on generated PDF on dev (Rachael #2244 #2248 / William #2260)
- [x] Force order title to all caps in the PDF (Rachael #2234)
- [x] pa11y test (Rachael #2252)
- [x] "Filed By" column should be blank (William #2261)
- [x] Link from docket record to Order Document Detail page - the success message “Your filing has been successfully submitted” is showing on Document Detail (William #2261)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
### Text Editor User Functionality Needs 

**Must Haves**
* able to do basic formatting:
  * Bolding
  * Italics 
  * Underline
  * Bulleted list 
  * numbered list 
  * Indenting
* able to paste content from other program (MS Word/WordPerfect) 
* able to view system generated header AND user entered content in a print layout/preview
* able to save draft and return to edit 
* Must be able to export/save as PDF  

**Better to Have** 
* able to paste content from other program (MS Word/WordPerfect) AND retain formatting 
* able to view system generated header AND user entered content in print layout real-time 

## Security Needs 
* cannot store USTC data on external servers 
* cannot share USTC data with external programs 

## Technical Needs 
* integration...

**Comment by ericsorenson** [comment]
6/20 Meeting

2 panels - WYSIWYG editor and PDF preview
Review possible WYSIWYG editors against requirements
POC: Integrate the results on WYSIWYG editor into @matthopson 's PDF creation code

**Comment by rachaelparris** [comment]
Quill: https://quilljs.com/

- [x] Bolding
- [x] Italics
- [x] Underline
- [x] Bulleted list
- [x] numbered list
- [x] Indenting
- [x] able to paste content from other program (MS Word/WordPerfect)

**Comment by wbyoko** [comment]
TinyMCE: https://www.tiny.cloud/ https://github.com/tinymce/tinymce

- [x] Bolding
- [x] Italics
- [x] Underline
- [x] Bulleted list
- [x] numbered list
- [x] Indenting
- [x] able to paste content from other program (MS Word/WordPerfect)

**Comment by wbyoko** [comment]
froala / wysiwyg-editor https://github.com/topics/wysiwyg-html-editor
- [x] Bolding
- [x] Italics
- [x] Underline
- [x] Bulleted list
- [x] numbered list
- [x] Indenting
- [ ] able to paste content from other program (MS Word/WordPerfect)

**Comment by rachaelparris** [comment]
CKEditor: https://ckeditor.com/ckeditor-5/
- [x] Bolding
- [x] Italics
- [x] Underline
- [x] Bulleted list
- [x] numbered list
- [ ] Indenting
- [x] able to paste content from other program (MS Word/WordPerfect) (documentation says it's possible to retain Word formatting)

**Comment by rachaelparris** [comment]
React Draft Wysiwyg: https://github.com/jpuri/react-draft-wysiwyg 
(one of many React rich text editors built on top of Draft.js - this one looks the cleanest from what I can find)
- [x] Bolding
- [x] Italics
- [x] Underline
- [x] Bulleted list
- [x] numbered list
- [x] Indenting
- [x] able to paste content from other program (MS Word/WordPerfect)

**Comment by wbyoko** [comment]
PDF Generation 

jsPDF https://github.com/MrRio/jsPDF
- [ ] Page Breaks
- [ ] Line Breaks
- [ ] Client Side Generation
- [ ] Service Side Generation

**Comment by klohman** [comment]
## UI Designs 

### Case Detail screen  
* Add "Create Order" button to case header 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/33d7c879-fef1-4fcb-a365-f65a06bec7c7)

* on click, display "Select Order Type" modal 

### Select Order Type Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5a1e24a5-2915-4b8f-bfab-e7c6bee1611a)

Order Type dropdown includes the following options 
(Don't display the event code- it's listed here for reference)
* O - Order 
* ODJ - Order of Dismissal for Lack of Jurisdiction
* OD - Order of Dismissal
* ODD - Order of Dismissal and Decision
* OSC - Order to Show Cause
* OAD - Order and Decision
* DEC - Decision

If user selects "O" Order: 
* display "Order Title" text field below 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8ba9bac9-26dd-4984-9aec-db73db4b64e7)

* on click of Cancel, modal closes with no changes saved 

* on click of Continue button
* order type and title selections must be retained
* user is navigated to Create Order screen 








### Create Order screen

**Comment by klohman** [comment]
## Create Order screen 

**Left panel** 
* includes selected text editor 
* custom toolbar should include:
   - Font - Times New Roman (default)
   - Font size - 14 (default) 
   - Bold 
   - Italics 
   - Underline 
   - Unordered list 
   - Ordered list 
   - Left Indent
   - Right indent  

**PDF Preview**
on load, populate header:
* Case caption - pulled from case detail data 
* Docket number - case detail data
* Order title - pulled from order type selected in modal 
**Order title should display in ALL CAPS** 

**Full Preview** 
on click of Full Preview link, open full page PDF preview in new browser tab 

**Cancel button**
* on click, display Cancel modal (same functionality as other forms) 

**Complete Order button**
* on click, PDF of Order is generated 
* sequential docket entry is created
   * Filed date - date of order creation 
   * Event - display order event code 
   * Filing and Proceedings - display Order Title - in title case 
* Order Title will link to document detail page (same functionality as other documents)

**Comment by rachaelparris** [comment]
##PDF Generation Research

PhantomJS html-pdf: https://www.npmjs.com/package/html-pdf

Seems to work, except for bold text.

**Comment by mariahkannenberg** [comment]
Test Results - Copy and Paste from Word Doc into Editor and Generate PDF preview

Word Doc: https://drive.google.com/file/d/1YCeibDcwM63qULt16hlfGnnuQE9fZJF5/view?usp=sharing
Results of generated PDF view: https://drive.google.com/file/d/144YlQIN7a75i3r8jSLZ_GOqXLvenXwuu/view?usp=sharing
Screenshot of editor view alongside PDF view: https://drive.google.com/file/d/1_4-xM8Ri_rGPrUBAOZpt-VtJpv_fnxrv/view?usp=sharing


Observations:
* Underline not displaying
* Words running off on right side of page
* Strange "By" text displaying at beginning of some lines
* Spacing of letters and words is "off"
* Tabs/Indents not displaying
* Various font sizes (can't tell if this is true or if it's because of spacing issue)
* Usability issue with original text being long, causing editor field to grow vertically, putting the bottom far below the PDF generated view

**Comment by klohman** [comment]
## 437 Task Scenarios 

### AC: Petitions Clerk can create an order in the system from a system-generated template
### AC: Order template contains standard content derived dynamically from system data

**Scenario 1**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal for Lack of Jurisdiction” 
* Click Continue

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as Order of Dismissal for Lack of Jurisdiction


**Scenario 2** 
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order” - Order Title field displays 
* Enter “for testing” in the Order Title field
* Click Continue

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick View displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Order for testing” in the Quick Preview 

**Scenario 3**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal” 
* Click Continue 

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Order of Dismissal” in the Quick Preview

**Scenario 4**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal and Decision” 
* Click Continue

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Order of Dismissal and Decision” in the Quick Preview

**Scenario 5**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order to Show Cause” 
* Click Continue 

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Order to Show Cause” in the Quick Preview

**Scenario 6**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order and Decision” 
* Click Continue

Expected Result
*  Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Order and Decision” in the Quick Preview

**Scenario 7**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Decision” 
* Click Continue 

Expected Result
* Modal closes and user is navigated to Create Order screen
* PDF Quick Preview displays on load
* Caption on Quick Preview is correct
* Docket number on Quick Preview is correct 
* Order title displays as “Decision” in the Quick Preview


### AC: Petitions Clerk clerk type order content into a free form text field
### AC: Petitions Clerk can perform basic content editing, such as bolding, underline and italics. 

**Scenario 8**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal”  
* Click Continue - Modal closes and user is navigated to Create Order screen
* Enter bold text into text editor 
* Enter italicized text into the text editor 
* Enter underlined text into text editor 
* Select a block of text and change font size from default to 18px and 
* Create an unordered bulleted list 
* Create an ordered bulleted list 
* Select a block of text and indent right 
* Select a block of text and indent left 


Expected Results 
* Bolded text displays as bolded in text editor 
* Italicized text displays as italicized in text editor 
* Underlined text displays as underlined in text editor 
* Default font size is 14px for entered text 
* User is able to update font size to 18px for selected text 
* User is able to create an unordered bulleted list in text editor
* User is able to create an ordered bulleted list in text editor
* Indented text displays correctly (indented left or right) in text editor



### AC: Petitions Clerk can preview the document while editing


**Scenario 9**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal”  
* Click Continue - Modal closes and user is navigated to Create Order screen
* Enter bold text into text editor 
* Enter italicized text into the text editor 
* Enter underlined text into text editor 
* Select a block of text and change font size from default to 18px 
* Create an unordered bulleted list 
* Create an ordered bulleted list 
* Select a block of text and indent right 
* Select a block of text and indent left 
* Click Refresh link 


Expected Results 
* Bolded text displays as bolded in text editor AND Quick Preview 
* Italicized text displays as italicized in text editor AND Quick Preview 
* Underlined text displays as underlined in text editor AND Quick Preview 
* Font size changes in text editor display in Quick Preview 
* Unordered bulleted list displays in text editor AND Quick Preview 
* Ordered bulleted list displays in text editor AND Quick Preview 
* Indented text displays correctly (indented left or right) in text editor AND Quick Preview 


**Scenario 10**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal”  
* Click Continue - Modal closes and user is navigated to Create Order screen
* Enter bold text into text editor 
* Enter italicized text into the text editor 
* Enter underlined text into text editor 
* Select a block of text and change font size from default to 18px 
* Create an unordered bulleted list 
* Create an ordered bulleted list 
* Select a block of text and indent right 
* Select a block of text and indent left 
* Click Full Preview button 

Expected Results 
* Full Preview opens in new browser tab 
* Bolded text displays as bolded in text editor AND in Full Preview 
* Italicized text displays as italicized in text editor AND in Full Preview  
* Underlined text displays as underlined in text editor AND in Full Preview  
* Font size changes in text editor display in Full Preview 
* Unordered bulleted list displays in text editor AND in Full Preview 
* Ordered bulleted list displays in text editor AND in Full Preview  
* Indented text displays correctly (indented left or right) in text editor AND in Full Preview  


### AC: Petitions clerk can save completed order
### AC: A docket entry (is created, can be created) for the newly created order (Can be simple language "Order"; Will be handled in another story).

**Scenario 11**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order and Decision” 
* Click Continue - Modal closes and user is navigated to Create Order screen
* Enter text into text editor 
* Click Complete Order button 

Expected Results 
* User is returned to Case Detail page 
* A new sequential docket entry is created displaying “Order” 

### AC: The docket entry should link to the PDF

**Scenario 12**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order and Decision” 
* Click Continue - Modal closes and user is navigated to Create Order screen
* Enter text into text editor 
* Click Complete Order button - returns user to Case Detail page
* Click on document link in the Order Docket Entry 

Expected Results 
* User is navigated to the Document Detail page for the Order selected  


### AC: Need ability to copy and paste with out stripping formatting (formatting to be defined)

**Scenario 13**
Test Steps 
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order and Decision” 
* Click Continue - Modal closes and user is navigated to Create Order screen
* Paste bolded text from Microsoft Word document into text editor 
* Paste italicized text from Microsoft Word document into text editor 
* Paste underlined text from Microsoft Word document into text editor 
* Paste indented text from Microsoft Word document into text editor 
* Paste unordered list text from Microsoft Word document into text editor 
* Paste ordered list text from Microsoft Word document into text editor 

Expected Results 
* Bolded text displays as bolded in text editor AND Quick Preview 
* Italicized text displays as italicized in text editor AND Quick Preview 
* Underlined text displays as underlined in text editor AND Quick Preview 
* Font size changes in text editor display in Quick Preview 
* Unordered bulleted list displays in text editor AND Quick Preview 
* Ordered bulleted list displays in text editor AND Quick Preview 
* Indented text displays correctly (indented left or right) in text editor AND Quick Preview 


**Scenario 15**
Test Steps
* Login as petitions clerk 
* Navigate to Case Detail page 
* Click Create Order button - Create Order Modal displays
* Select “Order of Dismissal”  
* Click Continue - Modal closes and user is navigated to Create Order screen
* Paste a two-page Microsoft Word document text into text editor 
* Click Refresh 

Expected Results 
* Quick Preview displays text on multiple pages as entered into the text editor
* PDF Quick Preview displays correct page numbering in header

**Comment by wbyoko** [comment]
Note on accessibility for 437: In the html editor captures tabs within the editor.

Seemingly the only way to leave the editor is to press shift+tab from the first character position in the editor then press down to go around the editor and get the buttons beneath.

**Comment by JessicaMarine** [comment]
PO Review 7/10/19
* The text size of the case caption seems to be bigger than the text size of the Title and body type.  They should all be Size 14 font.
* When you click on the Order from the docket record (277-19W) the text looks wonky:
![image](https://user-images.githubusercontent.com/40871081/61007331-908b7500-a33a-11e9-96b9-40de917fead6.png)

**Comment by JessicaMarine** [comment]
PO Review 7/12/19:

* when you hit Tab to indent (or copy something that is indented), it only takes you in like 2 spaces -- I think our expectation would be that the indent would be 1/2 inch (basically the same as if the user hits the indent function in the header)
* when you click on the Order from the docket record, the type is still looking wonky to me
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/301f7781-1677-48a1-a147-d58fa82175b9)
"Kenneth A. Rosch, Decedent" on the last line doesn't have the same bottom alignment
