### ISSUE TITLE
Practitioner: Generate and serve Notice when Practitioner changes address

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4374]
As a practitioner, so that parties may be notified that my address has changed, I need a change of address notice generated and served. 

## Acceptance Criteria
* When practitioner changes their address in the system, a notice is generated in each case in which they are attorney of record (already done) and served to all parties in each case
* When a Practitioner and IRS attorney updates their contact information, a notice only needs to be generated in open cases and cases that have been closed for less than 6 months

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- [ ] Stress testing - from Jessica: "For an IRS attorney, this could kick off several hundred notices at one time"

## Tasks
- [x] 1 Fix bug with practitioners changing their address, and add integration tests (Rachael et al #4476)
- [x] 2 Verify that respondent can change their address
- [x] 3 After fixes, go through test scenarios and verify that everything is working as expected
- [x] 4 Stress testing (Rachael)
  * Create x quantity of cases, associate a practitioner/respondent to each, then change their address
- [x] 5 Automatically serve generated notices (Kris #4476)
- [x] 6 Only update address for counsel on cases that are not closed more than 6 months (Rachael, Kris #4487)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
PO Review 2/13/2020:
* I wasn't able to confirm whether this was still needed or not because when I tried to change a practitioner's (Practitioner2) information, it wouldn't let me make a change and save.  The save button wouldn't click.

**Comment by klohman** [comment]
### 4374 Test scenarios 

Test data 
- Login as flexionustc@gmail.com 
- Create Case 1 
- Create Case 2  
- Login as flexionustc+respondent@gmail.com
- File document in Case 1 
- File document I Case 2

#### 1) Practitioner changes their address and sees Notice of Change of Address generated on each case’s docket record 
* Login as practitioner (flexionustc@gmail.com)
* Click “Edit’ under “My Contact Information
* Update address 
* Save 
* Navigate to each case 
Expected results
- [ ] Notice of Change of Address for [Practitioner Name] displays on the docket record for Case 1 
- [ ] Notice of Change of Address for [Practitioner Name] displays on the docket record for Case 2

#### 2) Docket clerk sees work item for each practitioner Notice of Change of Address in their Document QC 
* Scenario 1 
* Login as docket clerk 
* Navigate to Document QC 
Expected results 
- [ ] A Notice of Change of Address for [Practitioner Name] for Case 1 appears in the Docket Section Document QC Inbox 
- [ ] A Notice of Change of Address for [Practitioner Name] for Case 2 appears in the Docket Section Document QC Inbox 

#### 3) Each practitioner Notice of Change of Address is served on electronically served parties immediately 
* Scenario 1 
* Practitioner receives service email for Case 1 
* Practitioner receives service email for Case 2 
* Respondent receives service email for Case 1 
* Respondent receives service email for Case 2 

 #### 4) Practitioner changes their telephone and sees Notice of Change of Address generated on each case’s docket record 
* Login as practitioner (flexionustc@gmail.com)
* Click “Edit’ under “My Contact Information
* Update telephone number  
* Save 
* Navigate to each case 
Expected results
- [ ] Notice of Change of Telephone Number for [Practitioner Name] displays on the docket record for Case 1 
- [ ] Notice of Change of Telephone Number for [Practitioner Name] displays on the docket record for Case 2


#### 5) Docket clerk sees work item for each practitioner Notice of Change of Telephone Number in their Document QC 
* Scenario 1 
* Login as docket clerk 
* Navigate to Document QC 
Expected results 
- [ ] A Notice of Change of Telephone NUmberfor [Practitioner Name] for Case 1 appears in the Docket Section Document QC Inbox 
- [ ] A Notice of Change of Telephone Number for [Practitioner Name] for Case 2 appears in the Docket Section Document QC Inbox 

#### 6) Each practitioner Notice of Change of Telephone Number is served on electronically served parties immediately 
* Scenario 1 
* Practitioner receives service email for Case 1 
* Practitioner receives service email for Case 2 
* Respondent receives service email for Case 1 
* Respondent receives service email for Case 2 

#### 7) Practitioner changes their address and phone number and sees Notice of Change of Address and Telephone Number generated on each case’s docket record 
* Login as practitioner (flexionustc@gmail.com)
* Click “Edit’ under “My Contact Information
* Update address and phone
* Save 
* Navigate to each case 
Expected results
- [ ] Notice of Change of Address and Telephone Number for [Practitioner Name] displays on the docket record for Case 1 
- [ ] Notice of Change of Address and Telephone Number for [Practitioner Name] displays on the docket record for Case 2


#### 8) Docket clerk sees work item for each practitioner Notice of Change of Address and Telephone Number in their Document QC 
* Scenario 1 
* Login as docket clerk 
* Navigate to Document QC 
Expected results 
- [ ] A Notice of Change of Address and Telephone Number for [Practitioner Name] for Case 1 appears in the Docket Section Document QC Inbox 
- [ ] A Notice of Change of Address and Telephone Number for [Practitioner Name] for Case 2 appears in the Docket Section Document QC Inbox 

#### 9) Each practitioner Notice of Change of Address and Telephone Number is served on electronically served parties immediately 
* Scenario 1 
* Practitioner receives service email for Case 1 
* Practitioner receives service email for Case 2 
* Respondent receives service email for Case 1 
* Respondent receives service email for Case 2
