### ISSUE TITLE
Petitions Clerk & Docket Clerk: Manually add a deadline to a case

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#438]
As a Petitions Clerk or Docket Clerk, in order to keep track of items that require follow up, I need the ability to add a deadline at the case level. 

Whenever the Court issues an order to the parties, that Order will contain some sort of due date.  The Petitions Clerk or Docket Clerk (whoever is serving the Order) needs the ability to enter a deadline in the system at the case level.  That deadline should be viewable when viewing the case, as well as somewhere in the aggregate with all other due dates on all cases.

## Pre-Conditions
* Something in a case has a deadline

## Acceptance Criteria
* Petitions Clerk or Docket Clerk can manually add a deadline at the case level
* Any CMS user can see within a case that a deadline exists
* Petitions Clerk or Docket Clerk can edit a previously entered deadline
* Petitions Clerk or Docket Clerk can remove a deadline from a case

## Notes
* Due dates should be viewable within a case, as well as somewhere in the aggregate with all other due dates on all cases. #439 

## Tasks
- [x] 1 dynamno persistence methods (William #2267)
- [x] 2 entity (William #2267)
- [x] 3 validation sequence (William #2267)
- [x] 4 create sequences (William #2267)
- [x] 5 update sequence (William #2267)
- [x] 6 delete sequence (William #2267)
- [x] 7 journey test for case deadlines (William #2267)
- [x] 8 case detail view of case deadlines (Rachael #2270)
- [x] 9 create case deadlline modal (Rachael #2270)
- [x] 10 update case deadline modal (Rachael #2270)
- [x] 11 delete case deadline modal (Rachael #2270)
- [x] 12 Case Deadline sort (William #2274)
- [x] 13 Store Case Deadlines away from case entity to prevent flash (Kris #2275)
- [x] 14 Success messages (William #2274)
- [x] 15 Case Deadlines view on external case detail view (Rachael #2277)
- [x] Updates to table column order and font (Kristen #2286)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (William #2283)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (#2271 #2279)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by sarahridgway** [comment]
Manual Management of Deadlines

*Default View* 

- displays message "There are no deadlines for this case."
- "Add Deadline" button launches Add Deadline Modal

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/12900f11-4e45-47e7-9d5a-b3030b4f74a6)

*Add Deadline Modal*

- internal date field
- text area field limited to 120 chars

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/25ed5891-5830-494a-b82a-b29b16651ffc)

*Saved Deadlines*

- display in chronological order, oldest first
- if overdue, display red "Overdue" text in left column
- "Remove" button launches Remove Deadline Confirmation Modal
- "Edit" button launches Edit Deadline Modal

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/691b03e4-b54e-47d4-a75b-29281068b95b)

*Edit Deadline Modal*

- internal date field, pre-populated with current deadline date
- text area filed, pre-populated with current deadline text
- "Save" button updates the deadline date and/or text and returns to the case detail page

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/0bb0fcc8-98d8-4cfb-b100-d4b878819e88)

*Remove Deadline Confirmation Modal*

- display deadline date and text to confirm which deadline is being removed
- "Yes, Remove" button removes the deadline from the list and returns to the case detail page

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/89217185-7b7a-4de1-a979-f66c59ff4e50)
