### ISSUE TITLE
Case Inventory Report

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#4382]
As a court user, in order to manage my workload, I need the ability to generate a print-out of my case inventory.

## Acceptance Criteria ##
* List of all cases that can be filtered by status and judge (can filter by either and both) 
* Can filter by more than once status at a time
* Default order should be by docket number, lowest to highest
* Closed cases can be excluded from report
* Status filtered list should include:
   * Docket number
   * Case title
   * Judge
  ~* Date on which the case was associated with Judge~
* Judge filtered list should include:
   * Docket number
   * Case title
   * Case status
  ~* Date on which the case was associated with Judge~
* User can print a view of their results (Print Optimized)
* No data displayed on page/report load

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Date associated with judge - Removed from AC (2/20 design meeting)
* Load More function will be used to manage number of load on page
* Stress testing - max cases 1000

## Tasks
- [x] 1 Create endpoint to get case inventory by status and/or judge (use elasticsearch) (interactor, proxy, serverless, lambda) (Rachael, Kris, Rae #4551)
- [x] 2 Add Case Inventory option to Reports dropdown (alpha order) (Matt #4552)
- [x] 3 Create Run Case Inventory Report modal (without multi-select for case status), sequences, validation, submit sequence and action (Rachael, Rae #4556)
- [x] 4 Case Inventory route and view, with filtering dropdowns (without table) (Matt #4552)
- [x] 5 Case Inventory data table and computed (Rachael #4575)
- [x] 6 Create endpoint to get case inventory printable report (template generator, interactor, proxy, serverless, lambda, sequence, action) - use websockets and block the UI until fully loaded (Rachael #4583)
- [x] 7 Case Inventory Report printable route/view, sequences, actions (Rachael #4588)
- [x] 8 Paging (25) (Matt #4598)
- [x] 9 Stress testing (Rachael - 200 cases added so far as of Friday afternoon)
~~- [ ] 10 Look into multi-select for case status~~
- [x] 11 Create reports cloudformation stack (Rachael #4577)
- [x] 12 Add entity name to Case entity to persist the entity type, so it can be filtered on for elasticsearch query (we are currently checking for existence of caseType field - fix this in other places too) (Rachael #4592)
- [x] 13 UI validation when both filters are cleared from the table (backend throws an error that needs to be handled on the frontend) (Rachael #4602)
~~- [ ] 14 Printable report - use websockets and block the UI until fully loaded (Rachael)~~ not needed

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by uxforgood** [comment]
# Design

## Report dropdown

* Add Case Inventory option to Reports dropdown (alpha order) 

![image](https://user-images.githubusercontent.com/43787395/74959187-c19f4e00-53cf-11ea-8413-79e7510d8397.png)

## Selection modal

* When user selects Case Inventory report, launch modal
* User can filter by Judge, Status (multiple at once), or both
* Trigger error if user tries to run report without making a selection
![image](https://user-images.githubusercontent.com/43787395/74959216-cbc14c80-53cf-11ea-8fc1-a965e513a6ce.png)

### Error
![image](https://user-images.githubusercontent.com/43787395/74959636-8ea98a00-53d0-11ea-8646-78dd57c06f51.png)

## Filter by Judge

* Display filter with Judge's name selected, results only show for cases assigned to that Judge
* Table data includes: 
   * Docket number (sorted by oldest/lowest to newest/highest)
   * Case title
   * Case status
* Include Printable Report link that launches PDF viewer or report
* Include total count of results returned
* User can change judge filter or add a status filter 

![image](https://user-images.githubusercontent.com/43787395/74959685-a97bfe80-53d0-11ea-8fb3-ea7bee839c7d.png)

# Filter by status

* Display filter with status(s) selected, results only show for cases with that status
* Table data includes: 
   * Docket number (sorted by oldest/lowest to newest/highest)
   * Case title
   * Judge
* Include Printable Report link that launches PDF viewer or report
* Include total count of results returned
* User can change status filter or add a Judge filter 

![image](https://user-images.githubusercontent.com/43787395/74959863-f4961180-53d0-11ea-9099-bcd4b6f84616.png)

# Filter by status and Judge

* Table data includes: 
   * Docket number (sorted by oldest/lowest to newest/highest)
   * Case title
* Include Printable Report link that launches PDF viewer or report
* Include total count of results returned
* User can change status filter or Judge filter 

![image](https://user-images.githubusercontent.com/43787395/74959979-214a2900-53d1-11ea-9b81-a506417b73db.png)

## Printable report view

* Under report title, display the filters that were selected when they clicked "Printable Report" [in image, it's "Judge Buch"]

![image](https://user-images.githubusercontent.com/43787395/74960017-31620880-53d1-11ea-911b-021fe03abed3.png)

**Comment by uxforgood** [comment]
# Test scenarios

#### 1) Any court user can see the cases assigned to a specific Judge 
* Login as court user
* Navigate to Reports > Case Inventory
* Select Judge Buch from dropdown in modal and Run Report
Expected results 
- [ ] Modal appears after selecting Case Inventory from Reports menu
- [ ] Report loads displaying only cases for Judge Buch 
- [ ] Results table includes fields: Docket, Case title, Case status
- [ ] Results are ordered from oldest Docket to newest
- [ ] Filter shows "Judge Buch" selected on results page

#### 2) Any court user can print the cases assigned to a specific Judge
* Scenario 1
* Click "Printable Report" 
Expected results 
- [ ] Print preview screen should display showing report with the filter displaying under the report title on the PDF
- [ ] "Back to Case Inventory" link appears and when clicked, takes user back to filtered report

#### 3) Any court user can see the cases with a specific case status 
* Login as court user
* Navigate to Reports > Case Inventory
* Select "General Docket - At Issue (Ready for Trial)" from dropdown in modal and Run Report
Expected results 
- [ ] Report loads displaying only cases for General Docket - At Issue (Ready for Trial)
- [ ] Results table includes fields: Docket, Case title, Judge
- [ ] Results are ordered from oldest Docket to newest
- [ ] Filter shows "General Docket - At Issue (Ready for Trial)" selected on results page

#### 4) Any court user can print the cases with a specific case status
* Scenario 3
* Click "Printable Report" 
Expected results 
- [ ] Print preview screen should display showing report with the filter displaying under the report title on the PDF
- [ ] "Back to Case Inventory" link appears and when clicked, takes user back to filtered report

#### 5) Any court user can see the cases associated with a specific Judge and with a specific case status 
* Login as court user
* Navigate to Reports > Case Inventory
* Select "Judge Buch" and "General Docket - At Issue (Ready for Trial)" from dropdown in modal and Run Report
Expected results 
- [ ] Report loads displaying only cases for Judge Buch that are also in General Docket - At Issue (Ready for Trial)
- [ ] Results table includes fields: Docket, Case title
- [ ] Results are ordered from oldest Docket to newest
- [ ] Filter shows "Judge Buch" and "General Docket - At Issue (Ready for Trial)" selected on results page

#### 3) Any court user can see the cases with a specific case status 
* Scenario 3
* Also select "Calendared" from filter (so 2 statuses are selected) 
Expected results 
- [ ] Report loads displaying only cases for EITHER General Docket - At Issue (Ready for Trial) or Calendar
- [ ] Results table includes fields: Docket, Case title, Judge
- [ ] Results are ordered from oldest Docket to newest
- [ ] Filter shows "General Docket - At Issue (Ready for Trial)" and Calendar selected on results page

**Comment by klohman** [comment]
### Printable PDF 

**Header (First page)**

* if filtered by status and judge, display [Status] - [Judge Name] in header 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97f9ab28-abf5-4db5-827e-42af2392b9c7)

* if filter by status only: 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d1b255de-f64f-4c39-b89e-b1402dc4bae9)

* if filtered by judge only: 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/00061614-3935-46e6-a2ed-df5e8eb39dad)

**Header (subsequent pages)**

* if filtered by status and judge, display Case Inventory Report - [Status] - [Judge Name] in header 
* display page number Page [current page] of [total number of pages]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/14e61638-1bc7-4f2a-8d54-c68ea5ac14f7) 

* if filter by status only, display Case Inventory Report - [Status] in header 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d12d0738-f416-41e5-b554-6f6dd182ba0f)

* if filtered by judge only, display Case Inventory Report - [Judge Name] in header 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/86b12ed9-ceb2-4659-aa6e-e0257336ab06)

**Footer**
* display printed date : Printed [mm/dd/yy] on all pages

**Comment by mariahkannenberg** [comment]
Going to try to test multiple statuses at one time and see what happens. If doesn't work, just one.

**Comment by JessicaMarine** [comment]
PO feedback 3/6/2020:  (1) when you filter by just status, the printable report should have "Judge" as the right column -- it has "status"; (2) can we increase the number of cases that load -- right now it's only 2 -- i'd prefer 25ish at a time
