### ISSUE TITLE
QC Boxes for ADC/Judges

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#4384]
As an ADC or Judge, in order to know what documents have come in on my cases and remain to be QC'd, I need to have my QC box only display items in cases I'm associated with.

## Acceptance Criteria ##
* An ADC's QC box should display all Docket QC items that have "Chief Judge" associated with case
* A Judge's (and everyone in the Judge's Chambers) QC box should display all Docket QC items that have that specific Judge associated with case

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? No.
 - [ ] Does this work make major changes to the system? No. 
 - [ ] Does this work implement new authentication or security controls? No.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features? No.

## Tasks
- [x] 1 Add associated judge to work items (make it required, default to chief judge) (Rachael #4496)
- [x] 2 Update judge on work items when the case is updated if the judge changes (see updateCase.js lines 50-86) (Rachael #4496)
- [x] 3 Filter work items in judge/ADC qc boxes by the appropriate judge (Matt #4498)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Design 

**ADC Role**
* Document QC should be filtered by associated judge 
* Display only cases with "Chief Judge" as associated judge  


**Judge/Chambers roles **
* Document QC should be filtered by associated judge 
* Display only cases with [judge] as associated judge
 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/70d8a1c2-60bb-4204-a0fc-b5d3b0e8175d)

**Comment by klohman** [comment]
### 4384 QC Boxes for ADC/Judges

#### 1) ADC user sees only cases associated with Chief Judge in their Document QC Inbox 
* Login as adc1
* Navigate to Document QC 
Expected results 
- [ ] Document QC Inbox displays only Docket QC items on cases with “Chief Judge” associated 

#### 2) Judge user sees only cases associated with them in their Document QC Inbox 
* Login as Judge Buch 
* Navigate to Document QC 
Expected results 
- [ ] Document QC Inbox displays only Docket QC items on cases with Judge Buch associated

#### 3) Chambers user sees only cases associated with their judge in their Document QC Inbox 
* Login as buchschambers 
* Navigate to Document QC 
Expected results 
- [ ] Document QC Inbox displays only Docket QC items on cases with Judge Buch associated

#### 4) Internal users (other than ADC and Judge/chambers) see all cases in their Document QC Inbox 
* Login as calendar clerk 
* Navigate to Document QC 
Expected results 
- [ ] Document QC Inbox displays all cases regardless of associated judge

**Comment by mariahkannenberg** [comment]
#4384 QA tested and just one item to report on! There is a case assigned to judge buch 147-20 that has a doc in QA and it's not displaying the the chambers admin (CA)

**Comment by JessicaMarine** [comment]
PO Review 2.24.2020

On staging, I assigned 141-20 to Judge Buch and then filed a document in the case.  That document was correctly showing up in Judge Buch QC box. I then re-assigned the case from Judge Buch to Chief Judge Foley.  After re-assignment, the item remained in Judge Buch's QC box and did not move to CJ Foley's box.  I would expect it to display in the current associated Judge.
