### ISSUE TITLE
Trial Clerks: Working copy of trial session

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#4385]
As a Trial Clerk, in order to prepare for a trial session, I need a working copy of any trial session to which I am assigned, separate from the working copy of the Judge.

## Acceptance Criteria 
*  Trial Clerk who is assigned to a trial session needs a working copy of the trial session

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? No.
 - [ ] Does this work make major changes to the system? No.
 - [ ] Does this work implement new authentication or security controls? No.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?  No. 

## Notes
* Separate from judges working copy
* Judges notes don't display; it's the trial clerks copy to do what they want

## Tasks
- [x] 1 Modify createTrialSessionInteractor and updateTrialSessionInteractor to create a working copy for the trial clerk if one is assigned (Matt #4450)
- [x] 2 Update isUserAssociatedWithTrialSessionAction to allow for an associated trial clerk (update jsdoc description) (Matt #4452)
- [x] 3 Rename judgesNotes to userNotes and allow trial clerks to add their own notes (not viewable on case detail as the judge's notes are) (Rachael #4455)
  - [x] 3a Create migration script to change judgesNotes -> userNotes (Rachael #4455)
- [x] 4 Update trial session list to link to working copy for sessions a trial clerk is assigned to (see formattedTrialSessions line 128) (Matt #4452)
- [x] 5 Update trial session detail page to allow trial clerks to switch between the detail page and their working copy - also the working copy is displaying the judge's name instead of the trial clerk's in the header (Errybody #4465)
- [x] 6 Look into why past trial sessions are throwing an error locally (Rachael #4467)
- [x] 7 Change "Judge's notes" label in notes modal to "Notes" for trial clerk only (Rachael #4467)
- [x] 8 Remove "Judge" from "View Judge Session Copy" link (Rachael #4467)

Refactoring:
- [x] 1 Update user case note endpoints to be named better and/or pass in the userId (currently `case-notes/user/{caseId}`) (Rachael #4468)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### 4385 Trial clerk working copy 

- Create Trial Session - set Calendar 
    - Washington, DC 
    - Start date 4/01/20 
    - Judge Buch 
    - Trial Clerk1
- Create Trial Session - set Calendar 
- 
    - New York, NY
    - Start date 3/20/20
    - Judge Ashford 
    - Trial Clerk 2 
	

#### 1) Trial clerk sees working copy for session they are assigned to 
* Login as trial clerk 1 
* Navigate to Washington DC session 
Expected results 
- [ ] Working Copy displays 

#### 2) Trial clerk does not see working copy for session they are not assigned to 
* Login as trial clerk 1 
* Navigate to New York, NY session 
Expected results 
- [ ] Standard Trial session detail displays  

#### 3) Trial clerk adds/ edits / deletes note on case in working copy 
* Login as trial clerk 1 
* Navigate to Washington DC session 
* Add note to case 
* Edit note 
* Delete note 
Expected results 
- [ ] Added notes display on working copy 
- [ ] Edited notes display on working copy 
- [ ] Deleted notes do not display on working copy 

#### 4) Trial clerk notes do not display on case detail screen 
* Login as trial clerk 1 
* Navigate to Washington DC session 
* Add note to case 
* Navigate to Case Detail > Notes 
Expected results 
- [ ] Note does not display on Case detail 

#### 5) Trial clerk can filter cases on working copy by trial status 
* Login as trial clerk 1 
* Navigate to Washington DC session 
* Filter case by trial status
Expected results 
- [ ] Filtered case list displays based on selected filters 

#### 6) Trial clerk can add/edit/delete session note on working copy 
* Login as trial clerk 1 
* Navigate to Washington DC session 
* Add note to case 
* Edit note 
* Delete note 
Expected results 
- [ ] Added session notes display on working copy 
- [ ] Edited session notes display on working copy 
- [ ] Deleted session notes do not display on working copy 

#### 7) Trial clerk updates to working copy do not display on Judge’s Working Copy 
* Login as trial clerk 1 
* Navigate to Washington DC session 
* Add note to case 
* Filter cases by trial status 
* Login as Judge Buch 
* Navigate to Washington DC session 
Expected results 
- [ ] Judge’s working copy is not affected by changes to trial clerk working copy

**Comment by JessicaMarine** [comment]
PO Review 2/19/2020:
I'm logged in as msmith@example.com He is the Trial Clerk on the 1/30/2020 DC session.  When I am in his working copy, I can add and edit notes, but on save, it takes me back to a completely unfiltered view of the trial session:
https://files.slack.com/files-pri/TD3DSU09Y-FU6NMBBL4/image.png
Then, if I check "Show All" it does show all cases, but I also get an error message:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/185fcc5d-87b4-40f5-beab-f6d80dee32f1)

**Comment by mariahkannenberg** [comment]
Tested. Jessica's comments resolved. Working as expected!
