### ISSUE TITLE
Court User: Aggregate of deadlines

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#439]
As a court user, so that I can have a broad overview of all deadlines in the system, I need a place where I can see all deadlines aggregated. 

## Pre-Conditions:
* A deadline exists in at least 1 case

## Acceptance Criteria:
* A Court User can see in one place all of the due dates in all of the cases system-wide
* The information displayed in this aggregated area should include: docket number, due date, text of what's due [Note: Text should match what's displayed on case detail page]
* Events with the same due dates should be grouped together by date, and then displayed in docket number order (oldest to newest)
* User should be able to hyperlink from due date to the case detail page (maybe through hyper-linked docket number?)

## Tasks
- [x] 1 Add Reports tab to global navigation header and update computed to show it for correct users (Rachael, Kris #2850)
  - [x] 1a Add hover state and Deadlines link to header Reports tab (Rachael, Kris #2850)
- [x] 2 Create new route and empty view for all case deadlines (William #2849)
- [x] 3 Find React calendar component with option to choose a date range and add to the view (Rachael #2859)
- [x] 4 Create all case deadlines table view (William #2852)
- [x] 5 Create persistence method, endpoint, and interactor for getting all case deadlines (William #2849)
- [x] 6 Create sequences and actions to get the case deadlines from the backend into the view (William #2849)
- [x] 7 Create computed to filter all case deadlines by date and format deadlines and date header  (William #2852)
- [x] 8 Add multiple case deadlines on different dates to seed data (Rachael #2861)
- [x] 9 Refactor nav header to use USWDS components/styles (Kris, William, Rachael #2869)

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable)

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael #2884)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael #2884)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Reports link in global navigation 

**Unselected**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/edd4ec65-3e74-4e02-acbd-70f3457806ce)

**On hover or click**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/945cd6fe-cf8c-475b-a1f5-64a83cfe7c2b)

**On hover of sub-navigation link**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4b63249e-2bb3-4848-8155-d830dbd05d57)

* on click of "Deadlines" link, navigate to Deadlines page 

### Deadlines page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a6f779c9-a0f8-414f-80c9-48082ebd2c52)

**Date Picker**
* On load, default date is today 
* On click of another date, deadline list displays all case deadlines for selected date 
* On select of date range (dependent on the date picker OOTB functionality), display all case deadlines for all dates within the selected date range  

**Deadlines Table**
* Display selected date as table title (example August 16, 2019)
* Display total count of deadlines displayed (example Count: 33)
* If a single date is selected, display deadlines in docket record order (oldest to newest)
* If a date range is selected, display deadlines in chronological order, then order by docket number (oldest to newest) 
* On click of Docket Number link, navigate to selected Case Detail page

**Comment by klohman** [comment]
### 439 Aggregate of Deadlines Test Scenarios 

#### 1) User navigates to Deadlines page 
* Login as internal court user 
* Add a deadlines for 3 cases 
    * Case 1  Deadline 1- Today 
    * Case 1 Deadline 2 - Tomorrow 
    * Case 2 Deadline 1- Today 
    * Case 3 Deadline 1- Tomorrow 
    * Case 3 Deadline 2 - Day after tomorrow 
* Click on Reports from global navigation 
* Click on Deadlines link 
Results 
- [ ] On click of Reports, sub-categories (Deadline) display 
- [ ] On click of Deadlines, navigate to Deadlines page 

#### 2) User views Deadlines for today 
* [ Scenario 1] 

Results 
- [ ] Deadlines table displays today’s date as title 
- [ ] Count displays as 2 
- [ ] Case 1 Deadline 1 displays 
- [ ] Case 2 Deadline 1 displays 
- [ ] Deadlines display in docket record order (oldest to newest) 


#### 3) User views Deadlines for selected date other than today 
* [ Scenario 1 ] 
* Click on tomorrow’s date from date picker 

Results 
- [ ] Deadlines table displays tomorrow’s date as title 
- [ ] Count displays as “2”
- [ ] Case 1 Deadline 2 displays 
- [ ] Case 3 Deadline 1 displays 
- [ ] Deadlines display in docket record order (oldest to newest) 

#### 4) User views deadlines for a selected date range
* [scenario 1] 
* Select date range [ Today through Day after Tomorrow ] 

Results 
- [ ] Deadlines table displays date range as title 
- [ ] Count displays as “5”
- [ ] Case 1 Deadline 1 displays 
- [ ] Case 1 Deadline 2 displays 
- [ ] Case 2 Deadline 1 displays 
- [ ] Case 3 Deadline 1 displays 
- [ ] Case 3 Deadline 2 displays 
- [ ] Deadlines display in chronological order by due date 
- [ ] Deadlines with the same date are listed in order by docket record (oldest to newest) 

#### 5) User accesses Case Detail page from selected deadline 
* [ scenario 1 ] 
* Click on docket number of Case 1 Deadline 1 
Results 
- [ ] Navigated to Case Detail page for Case 1 
- [ ] Case 1 Deadline 1 displays 
- [ ] Case 1 Deadline 2 displays
