### ISSUE TITLE
Ability to easily reference case details while generating an order and QCin

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4533]
As a court user, in order to easily reference case details while drafting an order or QC'ing a document, I need the ability to view the work i'm doing on an order or QC a doc while viewing other case details at the same time. 

## Acceptance Criteria
* User needs to be able to easily reference the docket record (or other parts of the Case Info) when drafting an Order or QC'ing a document. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider easier method to create split-screen views, especially for docket record navigation, order creation, and document QC
[Note: The idea of being able to open in new tab/window?]

## Tasks
- [x] 1 New Tab Button - Mrinalini #6004  
  - [x] 1a Add New Tab button to header visible only to internal users
  - [x] 2a Open Case Detail in new tab with Docket Record tab displayed 
- [x] 2 On click of "Continue" from Create Order modal, open Case Detail in new tab with Docket Record tab displayed on the previous tab and navigate to Create Order screen - Mrinalini #6009

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Case header update
* Add "Quick View" to CaseDetailHeader
* Quick View is visible for internal users only 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6ad4a734-0ce2-4baf-8a50-529f371a2bfc)

### Quick View 

* On click of Quick View, open Quick View case copy in new browser window 
* Docket Record is displayed by default 

#### Quick View Case Header 
* global navigation is hidden 
* yellow warning message displays 
* Actions menu is hidden 
* Docket Number is not hyperlinked

#### Docket Record 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc2913d0-cb42-44a0-bc4d-03d39e0be12e)
- “Printable Docket Record” link is hidden 
- “Edit” link on docket entries is hidden 

#### Document View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2c2b6bee-8270-4736-9f75-5504648501ae)
- “View. Full PDF” link displays 
- on click of View Full PDF, selected PDF opens in new tab in Quick View window

#### Case. Information > Overview
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/653b6777-9459-4313-b5b3-d1f2b706c2dd) 
- [ ] “Edit” link on Petition Details is hidden 
- [ ] “Seal case” link is hidden 
- [ ] “Print Confirmation” link is hidden 
- [ ] “Add Cases” link on Consolidated Case card is hidden 
- [ ] Consolidated Cases - docket numbers are not hyperlinked
- [ ] “Add Manual Block” link is hidden
- [ ] “Add to Trial” link is hidden 
- [ ] “Mark High Priority” link is hidden 

#### Case Information >. Petitioner 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/00498e0d-e2f8-4622-837c-c0bbdf00c603)
- [ ] “Edit” link on Petitioner Contact Info card is hidden 
- [ ] “Edit” link on Petitioner Counsel card is hidden 
- [ ] “Add Counsel” search bar is hidden 

#### Case Information > Respondent 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cdea1d49-1f3c-41ab-a417-b0b870354949)
- [ ] “Edit” link on Respondent Counsel card is hidden 
- [ ] “Add Counsel” search bar is hidden 

#### Case Information >. Statistics 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3663408e-67f5-4ed0-94df-73e9c4cc9df3)
- [ ] All links are hidden 

#### Tracked Items >. Deadlines
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8a2ddb86-b7a3-41ba-a035-a1e705be6512)
- [ ] All links are hidden 

#### Tracked Items> Pending Report 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2fa1914d-e226-4341-b1b0-0ae5bc94ad96)
- [ ] Printable Report link is hidden 
- [ ] Remove  link is hidden 
- [ ] on click of document link, navigate to Document View with clicked document selected 

#### Drafts 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c4a3f3ef-4b16-4cee-ac1a-3cb9a38b5785)
- [ ] View Full PDF link is displayed 
- [ ] on click of View Full PDF, open PDF in new tab in Quick View window
- [ ] All other PDF action links are hidden 

#### Correspondence
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5ccdce16-0e9c-4fb8-be4b-1cbb734b53df)
- [ ] View Full PDF link is displayed 
- [ ] on click of View Full PDF, open PDF in new tab in Quick View window
- [ ] All other PDF action links are hidden 
- [ ] Add Correspondence File link is hidden

#### Messages. - In Progress 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cb3b4622-c59c-4e62-a0f6-9f25b2f14292)
- [ ] Message subject line is not hyperlinked 
- [ ] Attached documents are hidden 

#### Messages - Completed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea78724f-13a3-4970-b9e3-5718d15ba467)
[ ] Message subject line is not hyperlinked

**Comment by klohman** [comment]
### 4533 Tests Scenarios

#### 1)  Internal user sees “Quick View” option on Case Detail header 
* Login as internal user
* Navigate to Case Detail 
* View header 
Expected results 
- [ ] “Quick View” button is displayed in header 

#### 2) External users and public do not see Quick View option in Case Detail header 
* Go to public site 
* Search for case xx1-20
* View header 
* Login as petitioner 
* Navigate to case 
* View header
Expected results 
- [ ] “Quick View” button is not displayed in header for public or external parties 

#### 3) Internal user launches Quick View from Order flow 
* Login as internal user 
* Navigate to case xx1-20
* Click Create Order from Actions menu
* Select order type and Continue
* Click “Quick View” from Create Order screen
Expected results 
- [ ] Quick View opens in new browser window 
- [ ] Quick View displays Docket record as default view 
- [ ] Create Order screen remains open and unchanged

#### 4) Docket clerk user launches Quick View from Docket Document QC 
* Login as docket clerk 
* Navigate to Document QC > Inbox 
* Click on document link from Inbox
* Click “Quick View” from Document QC screen
Expected results 
- [ ] Quick View opens in new browser window 
- [ ] Quick View displays Docket record as default view 
- [ ] Document QC screen remains open and unchanged

#### 5) Internal user sees limited view of case on Quick View 
* Scenario 3 
* View Quick View window 
Expected results 
- [ ] Global navigation is hidden 
- [ ] Tracked Items tab is hidden 
- [ ] Drafts tab is hidden
- [ ] Correspondent tab is hidden
- [ ] Case Messages tab is hidden 
- [ ] Notes tab is hidden 
- [ ] Actions menu in header is hidden 
- [ ] Docket Number in header is not hyperlinked

#### 6) Internal user views Docket Record on Quick View 
* Scenario 4
* View Docket Record on Quick View 
Expected results 
- [ ] “Printable Docket Record” link is hidden 
- [ ] “Edit” link on docket entries is hidden 

#### 7) Internal user views Document View on Quick View 
* Scenario 4
* Click Document View tab on Quick View 
Expected results 
- [ ] “View. Full PDF” link displays 
- [ ] on click of View Full PDF, selected PDF opens in new tab in Quick View window

#### 8) Internal user views Case Overview on Quick View 
* Scenario 4 
* Click Case Information tab in Quick View window
* View “Overview” tab in Quick View 
Expected results 
- [ ] “Edit” link on Petition Details is hidden 
- [ ] “Seal case” link is hidden 
- [ ] “Print Confirmation” link is hidden 
- [ ] “Add Cases” link on Consolidated Case card is hidden 
- [ ] Consolidated Cases - docket numbers are not hyperlinked
- [ ] “Add Manual Block” link is hidden
- [ ] “Add to Trial” link is hidden 
- [ ] “Mark High Priority” link is hidden 

#### 9) Internal user views Petitioner information on Quick View 
* Scenario 4 
* Click Case Information tab in Quick View window 
* Click Petitioner tab 
Expected results 
- [ ] “Edit” link on Petitioner Contact Info card is hidden 
- [ ] “Edit” link on Petitioner Counsel card is hidden 
- [ ] “Add Counsel” search bar is hidden 

#### 10) Internal user views Respondent information on Quick View 
* Scenario 4 
* Click Case Information tab in Quick View window 
* Click Respondent tab 
Expected results 
- [ ] “Edit” link on Respondent Counsel card is hidden 
- [ ] “Add Counsel” search bar is hidden 

#### 11) Internal user views Statistics on Quick View 
* Scenario 4 
* Click Case Information tab in Quick View window 
* Click Statistics tab 
Expected results 
- [ ] All links are hidden 

#### 12) Internal user views Deadlines in Quick View 
* Scenario 4 
* Click Tracked Items on Quick View 
* Click Deadlines tab 
Expected results 
- [ ] All links are hidden 

#### 12) Internal user views Pending Report in Quick View 
* Scenario 4 
* Click Tracked Items on Quick View 
* Click Pending Report tab 
Expected results 
- [ ] Printable Report link is hidden 
- [ ] Remove  link is hidden 
- [ ] on click of document link, navigate to Document View with clicked document selected 

#### 13) Internal user views Drafts in Quick View 
* Scenario 4 
* Click Drafts on Quick View 
* Click on a draft document
Expected results 
- [ ] View Full PDF link is displayed 
- [ ] on click of View Full PDF, open PDF in new tab in Quick View window
- [ ] All other PDF action links are hidden 

#### 14) Internal user views Correspondence in Quick View 
* Scenario 4 
* Click Correspondence on Quick View 
* Click on a draft document
Expected results 
- [ ] View Full PDF link is displayed 
- [ ] on click of View Full PDF, open PDF in new tab in Quick View window
- [ ] All other PDF action links are hidden 
- [ ] Add Correspondence File link is hidden 

#### 15) Internal user views Messages > In Progress in Quick View 
* Scenario 4 
* Click Case Messages on Quick View 
* Click on In Progress tab
Expected results 
- [ ] Message subject line is not hyperlinked 
- [ ] Attached documents are hidden 


#### 16) Internal user views Messages > Completed in Quick View 
* Scenario 4 
* Click Case Messages on Quick View 
* Click on In Progress tab
Expected results 
- [ ] Message subject line is not hyperlinked

**Comment by klohman** [comment]
### 4533 Tests Scenarios

#### 1)  Internal user sees “New Tab” option on Case Detail header 
* Login as internal user
* Navigate to Case Detail 
* View header 
Expected results 
- [ ] “New Tab” button is displayed in header 

#### 2) Internal user launches case detail in new tab from Document QC screen 
* Login as Docket Clerk
* Navigate to Document QC > Inbox 
* Click document link for case xx1-20
* On Document QC screen, click “New Tab” button 
Expected results 
- [ ] New tab opens displaying Case Detail > Docket Record for case xx1-20
- [ ] Current tab remains on QC screen for document

#### 3) Internal user views case detail in new tab automatically from Create Order flow 
* Login as internal user
* Navigate to case xx1-20
* Click Create Order or Notice from Actions menu
* Select order type
* Click continue  
Expected results 
- [ ] New tab opens displaying Case Detail > Docket Record for case xx1-20
- [ ] Current tab navigates to Create Order screen
