### ISSUE TITLE
Court: Send case message with a document "attached"

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4607]
## Pre-Conditions
* #4293

## Acceptance Criteria
* Court user can create a message that's tied to one or more documents from the docket record and/or draft documents
* Subject line of the message pre-populates with the name of the first attached document but can be edited by the user 
* Court user can send the message to another court user
* Receiver of message can see the message sent to them
* Section the receiver is in can see the message that was sent
* From the message, the receiver and section can view the documents the message is tied to

## Notes
* Design / tech question - Should we allow attached documents to be changed/removed from a message? What is the technical complexity of this? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add “Add documents” section to Create New Message modal
  - [x] 1a Fetch documents from the case to fill dropdown (Matt #5476)
  - [x] 1b Add dropdown / button UI (Matt #5464)
  - [x] 1c Sequences / actions for updating form attachments (Matt #5473)
  - [x] 1d Display current attachments (Matt #5473)

- [x] 2 Update interactor for creating a message to accept array of document ids (Matt #5488)
- [x] 3 Add Attachments section to My Messages -> Inbox, My Messages -> Sent boxes (Matt #5490)
  - [x] 3a Links should open PDF in a new tab (not document detail page - straight up PDF) (Matt #5490)
- [x] 4 Update Message Detail screen with attachments section (Matt #5495)
- [x] 5 Verify that all tables have a blank state “There are no messages.” (Matt)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt #5505)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael #5503)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Create New Message modal with attachments 
* on click of Create New Message from Actions dropdown 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc99fefd-1a30-44e2-b43e-85211f2da4ae)

**Add document dropdown**

* Dropdown includes all draft documents on the case, sorted in order of created date
* Dropdown includes all document entries on the case docket record, sorted in order of Filed date 
* Dropdown excludes any minute entries (non-documents) on the docket record 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/887ba3f8-fc56-477b-9f7e-b1ffb9a4c3d9)

**User attaches first document**
When first document is selected: 

* Concatenated Document Title is populated in Subject Line 
* Subject line remains editable as free text 
* Concatenated Document Tile displays under Attachments
* Add More Document(s) link displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97e6c774-670e-46c8-ac78-e58b4a932b63)

**User attaches multiple documents to a message**
* on click of Add More Document(s), display second Add Document(s) dropdown 
* Add More Document(s) link displays 
* User can add up to five total attachments to a message 

* When five documents have been attached, Add More Document(s) link is hidden 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d52ca095-38e3-4dd8-8e58-c34f7bdb86b9)

* Modal displays Add Document

**Comment by klohman** [comment]
#### User sends message with attachment
* On click of Send, modal closes and success message displays 

**Sent message displays in My Messages > Sent box**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b969b628-55d4-4f64-8aa2-61215d35ad45)

* Concatenated Document titles for all attached documents display in the "Attachments" column 
*  Concatenated Document titles should be truncated after two lines of text
* On click of Document title link, open PDF in new tab

**Send message displays in Section Messages > Sent 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3a9494c9-5941-46d7-a93b-4beaef8d5aea)

* Attachments column is not displayed in Section Messages Sent Box 

#### User receives message with attachment 

**My Messages Inbox**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/89d4da25-f40e-400d-a656-458d47342576)

* Concatenated Document titles for all attached documents display in the "Attachments" column 
*  Concatenated Document titles should be truncated after two lines of text
* On click of Document title link, open PDF in new tab

**Section Messages Inbox**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e9d619b2-4f14-48a5-a680-4b2d0cdb1b08)

* Attachments columns does not display in Section Messages Inbox 


#### Message Detail screen with attachment(s) 

* on click of the Subject Line from the message boxes, app navigates to the Message Detail screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cbfd3f1e-93d7-479b-a37d-b2ce467fdf13)

**Attachments**
*Concatenated Document title for all attached documents display in left panel 
* Documents are sorted in the order they were attached to message 
* PDF Preview of first document is displayed in PDF viewer by default
* If user selects a different document from the list, the PDF viewer updates to display the selected document

**Comment by klohman** [comment]
### 4607 Test Scenarios 

**Test data**
Create Case 1 
- E-filed Petition 
- Requested Place of Trial - Washington DC 
- Create Order of Dismissal - save as draft 
- Upload Minute Sheet to draft documents 
- File documents 
    - Answer 

Create Case 2 
- Add 5 document to docket record 

#### 1) Internal user sees option to attach any draft documents and all docket record documents to a message 
* Login as internal user 
* Navigate to Case 1 
* Click Create New message from Actions dropdown 
* Click into Add Documents field and view options 
Expected results 
- [ ] Order of Dismissal displays under Draft Documents in dropdown options 
- [ ] Minute Sheet displays under Draft Documents in dropdown options 
- [ ] Petition displays under Docket Record in dropdown options 
- [ ] Answer displays under Docket Record in dropdown options 

#### 2) Internal user does not see option to attach a minute entry from docket record to a message 
* Scenario 1 
* View options in Add Documents dropdown
Expected results 
- [ ] Request for Place of Trial Washington DC docket entry does not display as dropdown option

#### 3)  Internal user attaches first document to a new message 
* Login as internal user 
* Navigate to Case 1 
* Click Create New message from Actions dropdown 
* Select “Answer” from Add Document’s dropdown 
Expected results 
- [ ] Subject line is populated with “Answer” 
- [ ] Attachments read only field displays “Answer” 
- [ ] Add More Documents link is displayed 

#### 4) Internal usert edits system-populated subject line for message 
* Scenario 3 
* Edit Subject Line to “Answer - need clarification” 
* Add message 
* Click Send 
* View message in Sent box
* Click subject line link 
* View Message Detail screen
Expected results
- [ ] Populated subject line is editable on Create New Message form
- [ ] Subject line in Sent box displays updated subject line 
- [ ] Subject line on Message Detail displays updated subject line 

#### 5) Internal user attaches multiple documents to a new message 
* Scenario 3 
* Click Add More Documents
* Select Petition from Add Documents dropdown
Expected results 
- [ ] Attachments read only field displays “Answer” and “Petition” 
- [ ] Add More Documents link is displayed 

#### 6) Internal user cannot attach more than five documents to a message 
* Login as internal user 
* Navigate to Case 2 
* Add five documents from docket record as attachments
Expected results 
- [ ] Subject is populated by the first document added 
- [ ] Attachments read only field displays all five document titles added 
- [ ] Add More Documents link is hidden 

#### 7) Internal user sees sent message with attachment in My Messages > Sent box 
* Scenario 6 
* Click Send 
* Navigate to My Messages > Sent box 
Expected results 
- [ ] New message displays in Sent box
- [ ] Five documents display as “Attachments” for new message 

#### 8) Internal users sees sent message in Section Messages > Sent box 
* Scenario 7 
* Navigate to Section Messages > Sent box 
Expected results 
- [ ] New message displays in Section Messages > Sent box 
- [ ] Attachments are not displayed in Section Messages- Sent box

#### 9) Internal user sees received message with attachment in My Messages > Inbox 
* Login as recipient from Scenario 7 
* View My Messages Inbox 
Expected results 
- [ ] New message displays in My Messages Inbox as unread message 
- [ ] New message displays five attachments in Attachments column 

#### 10) Internal user sees received message in Section Messages > Inbox 
* Scenario 9 
* Navigate to Section Messages > inbox 
Expected results 
- [ ] New message displays in My Messages Inbox 
- [ ] New message does not display attachments

#### 11) Internal user views attached documents from My Messages > Inbox
* Scenario 9
* Click on attachment for new message 
Expected result 
- [ ] Selected document PDF opens in a new tab 

#### 12) Internal user views attached documents from My Messages > Sent 
* Scenario 7
* Click on attachment for new message 
Expected result 
- [ ] Selected document PDF opens in a new tab 

#### 13) Internal user views message information and attached documents 
* Scenario 9
* Click on new message subject line link
Expected results 
- [ ] App navigates to Message detail screen 
- [ ] Message metadata displays 
- [ ] All attached document titles are displayed in left panel 
- [ ] First attached document displays as selected in left panel 
- [ ] First attached document PDF displays in PDF preview

#### 14) Internal user toggles between PDF preview for each attached document 
* Scenario 13 
* Select the second attached document 
Expected results 
- [ ] Second attached document displays as selected in left panel 
- [ ] Second attached document displays in PDF preview

**Comment by klohman** [comment]
UX Comments 
- Attachment(s) - label should be same font as field label (it currently looks bold, should be semi-bold)
- When first document is attached, the Subject line should populate with the document title (currently is remaining blank)

**Comment by klohman** [comment]
UX Comments 

* Need additional line space and alignment when subject line wraps 
![Screen Shot 2020-06-16 at 12.28.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c585e042-bdc3-4504-9c81-5c33fb4d9f06)

* Sent messages aren't always sorting correctly- the message sent 12:27pm on 176-20 should be below the one sent at 12:25pm - it sorted in the middle of older messages 
![Screen Shot 2020-06-16 at 12.27.38 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/46178047-80c1-4b0a-ac39-6fc226616fc3)

* Need to add the blank state on Inbox/Sent box for attachments column : "No attachments"

**Comment by matthopson** [comment]
Feedback updates in #5505
