### ISSUE TITLE
Court: Message complete, forward and reply 

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4609]
## Pre-Conditions
#4607 

## Acceptance Criteria
* Court user can reply to a message sent to them
* Message can be forwarded to another court user
* Message is removed from inbox once it's been replied to, forwarded or completed
* Message can be completed
* Once message is completed, the court user knows no further action is needed, but the message is still accessible to the user (from completed tab and at case level)
* A message that's forwarded or replied to creates a thread that's available for all court users to see
* A message that's been replied to forwarded displays in the sent box
* Any court user can access any message and take action on the message

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Complete redesign of Case Detail  and  Case Messages tables in this story 

## Tasks
- 1 Message Detail
  - [x] 1a Add message action buttons to message detail (Rachael #5521)
  - [x] 1b Sequences for displaying modals (Rachael #5521)
  - [x] 1c Updates for threaded message display (Rachael)
- 2 Reply to message
  - [x] 2a Reply modal (Rachael #5528)
  - [x] 2b Sequences / Actions for submitting reply (Rachael, Matt)
  - [x] 2c Persistence methods for updating inbox/outbox records (Rachael, Matt)
- 3 Forward message
  - [x] 3a Forward modal (Rachael #5542)
  - [x] 3b Sequences / Actions for forwarding message (Rachael, Cody #5553)
  - [x] 3c Persistence methods for updating inbox/outbox records (Rachael, Cody #5553)
- 4 Complete message
  - [x] 4a Complete message modal (Rachael, Cody)
  - [x] 4b Sequences / Actions for completing message (Rachael, Cody)
  - [x] 4c Persistence methods for updating inbox/outbox records (Rachael, Cody #5555)
- [x] 5 Dynamo records / entity updates for threaded messages (Rachael, Matt)
- 6 Case Detail (Matt #5543)
  - [x] 6a Add Tracked Items tab with pending report and deadlines (default)
  - [x] 6b Add Drafts with Draft Documents table
  - [x] 6c Add Case Messages tab with In Progress and Completed tab
- [x] 7 Add Case Title to case message tables (Matt #5523, #5535)
- [x] 8 Change Docket to Docket Number on message tables (Matt #5523)
- [x] 9 Completed box (Rachael, Cody #5558)
  - [x] 9a Route, table view, computed (Rachael, Cody #5558)
  - [x] 9b Endpoint to retrieve data (Rachael, Cody #5558)
- [x] 10 Message detail alert for completed message thread (Rachael)
- [x] 11 Case Detail -> Case Messages -> In Progress and Completed boxes
- [x] 12 completed and sent boxes - filter out anything older than 7 days (Rachael #5571)
- [x] 13 stay on message detail screen when replying/forwarding/completing, but update the messages displayed with the new one (Matt #5572)
- [x] 14 case detail case messages is not displaying the latest message sent from the case detail actions menu (Rachael #5571)

- [x] Need to align Message Subject line link with table header and left align wrapping text (Cody)
- [x] Add padding to blank state messages on Message Detail > Attachments (Cody)
- [x] Sent box > Section is not displaying the correct section for the “To” user (Cody)
- [x] Example, message was sent to petitions clerk 1 - “To” displays as Petitions clerk 1; “Section” displays as docket 
- [x] Success message on Message Detail should clear when user navigates away from screen (currently it’s still displaying when I click back to Case Messages > Inbox (Matt #5585)
- [x] When completing message, do not show the "Message has been sent" success message. Only display the "message completed ...." (Matt #5585)
- [x] Correct sorting on Messages > Completed box - should be newest to oldest by completed date (Matt #5585)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Message Detail - Actions 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a2cbb9ab-df14-4ed1-a05f-1e84fbb146b4)

* display message actions on Message Detail screen 


### User replies to message 

* On click of Reply, display Reply to Message modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b9bbd60b-cf53-4f62-8f1e-b0f2a839ae5f)

**Recipient**
* original sender is displayed read-only as recipient 

**Subject line**
* current subject is displayed (i.e. the subject line sent in the original message)
* subject line field is editable 

**Attachments**
* Displays all documents attached to message in read-only 

**Add More Documents**
* on click, displays Add Documents dropdowns 
* User is able to add up to five document total to message

**On Send**
* App navigates to My Messages > Inbox with success message displayed 
* Sent message displays in My Messages > Sent and Section Messages > Sent box
* Message displays in My Messages > Inbox / Section Messages > Inbox of the recipient 
* Message thread displays on Message Detail screen

**Comment by klohman** [comment]
#### User forwards a message to another internal user 

* On click of Forward link, Forward Message modal displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f4dbe50-4eff-4197-ad9e-5182567fdf3e)

**Select section/ Select recipient**
* current functionality 

**Subject Line**
* current subject is displayed (i.e. the subject line sent in the original message)
* subject line field is editable

*Attachments**
* Displays all documents attached to message in read-only

**Add More Documents**
* on click, displays Add Documents dropdown
* User is able to add up to five document total to message

**On Send**
* App navigates to My Messages > Inbox with success message displayed
* Sent message displays in My Messages > Sent and Section Messages > Sent box
* Message displays in My Messages > Inbox / Section Messages > Inbox of the recipient
* Message thread displays on Message Detail screen

#### User completes message 
* On click of Complete link, Complete Message modal displays 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57b880f1-2fac-4247-b5d5-e053e62a92db)

**Add Comment** 
* Optional field - current functionality 

**On Complete**
* App navigates to My Messages > Inbox with success message displayed 
* Message no longer displays in any user Inbox 
* Completed message displays in My Messages > Completed and Section Messages > Completed 
* Message thread displays as Completed on Message Detail screen 

#### My Messages > Completed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1486fff3-a80c-4d87-820b-ca30f6dd808f)

**Completed**
*displays the date/time the message was completed 
* messages sorted newest to oldest by date/time completed 

**Last Message**
* Displays Subject Line link and message from most recent message in this thread (the last message before the message thread was completed)
* On click of Subject Link link, navigate to Message Detail screen 

**Comment**
* Displays text from "Add Comment" field (if applicable) 

#### Section Messages > Completed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6101a524-ea2b-4f65-88c0-2c84ced053c5)

**Completed by and Section **
*Displays user who completed the message 


#### Message Detail - Completed

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d4bd2e08-0317-41e1-b23e-94bb4673ff36)

* Displays alert message 
* Message thread is retained 
* All attachments are retained

**Comment by klohman** [comment]
### Case Detail Updates 

#### Tracked Items 
* add "Tracked Items" tab 
* Tracked Items tab includes Deadlines table and Pending Report table 
* Displays Deadlines as default tab

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c1e9631c-c82c-45c5-b72f-c35f4be5d174)

#### Drafts 
* add "Drafts" tab 
* Includes Draft Documents table 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d578a21c-4621-4c31-9fd7-0beba3c75609)

#### Case Messages 
* Add Case Messages tab 
* Includes In Progress and Completed tabs 

**In Progress**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f77a1dbd-1346-47e4-ad93-84db75ff05c0)
* table includes all active messages on a case- any message that appears in a user's inbox 
* Messages are sorted newest to oldest 
* Subject line link - navigates to Message Detail screen

**Completed**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0bd40b91-6a8a-433e-8f96-29818075c802)

* table includes all message threads on a case that have been completed 

**Completed**
*displays the date/time the message was completed
* messages sorted newest to oldest by date/time completed

**Last Message**
* Displays Subject Line link and message from most recent message in this thread (the last message before the message thread was completed)
* On click of Subject Link link, navigate to Message Detail screen

**Comment**
* Displays text from "Add Comment" field (if applicable)

**Completed by**
* displays user who completed the message thread

**Comment by klohman** [comment]
### 4609 Test Scenarios 

#### 1) Internal users sees actions available on a message 
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Complete Create New Message form without attachment 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link 
Expected results 
- [ ] Reply, Forward, and Complete links display on Message Detail screen 

#### 2) Internal user replies to a message without a document attached 
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Enter “Question for review” in Subject Line 
* Enter message 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link 
* Click Reply 
* Enter message 
* Click Send
Expected results 
On click of Reply,
- [ ] Reply to Message modal displays 
- [ ] Recipient field displays “petitionclerk1” and is read-only
- [ ] Subject link displays as “Question for review” and is editable 
On click of Send, 
- [ ] Reply to Message modal closes 
- [ ] App navigates to My Messages> Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox for docket clerk 1
- [ ] Original message is removed from docket Section Messages > Inbox 
- [ ] Replied message displays in My Messages > Inbox of petitionclerk1 
- [ ] Replied message displays in Section Messages > Inbox of petitions section
- [ ] Replied message displays in My Messages > Sent of docket clerk 1 
- [ ] Replied message displays in Docket Section Messages > Sent 
- [ ] Replied message displays in Case Detail> Case Messages > In-Progress 
- [ ] Replied message is displayed as current message in thread on Message Detail screen 

#### 3) Internal user replies to a message with a document attached
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Attach “Petition” to message
* Enter message 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link 
* Click Reply 
* Enter message 
* Click Send
Expected results 
On click of Reply,
- [ ] Reply to Message modal displays 
- [ ] Recipient field displays “petitionclerk1” and is read-only
- [ ] Subject link displays as “Petition” and is editable 
On click of Send, 
- [ ] Reply to Message modal closes 
- [ ] App navigates to My Messages> Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox for docket clerk 1
- [ ] Original message is removed from docket Section Messages > Inbox 
- [ ] Replied message displays in My Messages > Inbox of petitionclerk1 with attached document PDF link displays  
- [ ] Replied message displays in Section Messages > Inbox of petitions section
- [ ] Replied message displays in Case Detail> Case Messages > In-Progress with attached document PDF link displays  
- [ ] Replied message displays in My Messages > Sent of docket clerk 1 
- [ ] Replied message displays in Docket Section Messages > Sent 
- [ ] Replied message is displayed as current message in thread on Message Detail screen 
- [ ] Attached document preview displays on Message Detail screen 


#### 4) Internal user updates subject line when replying to a message with/without a document attached 
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Attach “Petition” to message
* Enter message 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link 
* Click Reply 
* Edit Subject line to “Petition - Check Jurisdiction” 
* Enter message 
* Click Send
Expected results 
On click of Reply,
- [ ] Reply to Message modal displays 
- [ ] Recipient field displays “petitionclerk1” and is read-only
- [ ] Subject link displays as “Petition - Check Jurisdiction” and is editable 
On click of Send, 
- [ ] Reply to Message modal closes 
- [ ] App navigates to My Messages> Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox for docket clerk 1
- [ ] Original message is removed from docket Section Messages > Inbox 
- [ ] Replied message displays in My Messages > Inbox of petitionclerk1 with attached document PDF link displays  
- [ ] Replied message displays in Section Messages > Inbox of petitions section
- [ ] Replied message displays in My Messages > Sent of docket clerk 1 with subject line “Petition- Check Jurisdiction” 
- [ ] Replied message displays in Docket Section Messages > Sent with subject line “Petition- Check Jurisdiction” 
- [ ] Replied message displays in Case Detail> Case Messages > In-Progress with attached document PDF link displays  with subject line “Petition- Check Jurisdiction” 
- [ ] Replied message is displayed as current message in thread on Message Detail screen with subject line “Petition- Check Jurisdiction” 
- [ ] Original message displays in message thread on Message Detail with subject line “Petition”
- [ ] Attached document preview displays on Message Detail screen 


#### 5) Internal user replies to a message sent to another user 
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Attach “Petition” to message
* Enter message 
* Click Send 
* Login as docket clerk 2 
* Navigate to Section Messages > Inbox 
* Click on new message subject link of message sent to docketclerk1
* Click Reply 
* Enter message 
* Click Send
Expected results 
On click of Reply,
- [ ] Reply to Message modal displays 
- [ ] Recipient field displays “petitionclerk1” and is read-only
- [ ] Subject link displays as “Petition” and is editable 
On click of Send, 
- [ ] Reply to Message modal closes 
- [ ] App navigates to My Messages> Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox for docket clerk 1
- [ ] Original message is removed from docket Section Messages > Inbox 
- [ ] Replied message displays in My Messages > Inbox of petitionclerk1 with attached document PDF link displays  
- [ ] Replied message displays in Section Messages > Inbox of petitions section
- [ ] Replied message displays in My Messages > Sent of docket clerk 2 
- [ ] Replied message displays in Docket Section Messages > Sent 
- [ ] Replied message displays in Case Detail> Case Messages > In-Progress with attached document PDF link displays  
- [ ] Replied message is displayed as current message in thread on Message Detail screen 
- [ ] Attached document preview displays on Message Detail screen 

#### 5) Internal user attaches a new document when replying to a message 
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Enter subject line “For Review” 
* Enter message 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link
* Click Reply 
* Attach “Petition” to message
* Enter message 
* Click Send
Expected results 
On click of Reply,
- [ ] Reply to Message modal displays 
- [ ] Recipient field displays “petitionclerk1” and is read-only
- [ ] Subject link displays as “For Review” and is editable 
- [ ] “Petition” displays read-only as attached document
On click of Send, 
- [ ] Reply to Message modal closes 
- [ ] App navigates to My Messages> Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox for docket clerk 1
- [ ] Original message is removed from docket Section Messages > Inbox 
- [ ] Replied message displays in My Messages > Inbox of petitionclerk1 with attached document PDF link displays  
- [ ] Replied message displays in Section Messages > Inbox of petitions section
- [ ] Replied message displays in My Messages > Sent of docket clerk 2 
- [ ] Replied message displays in Docket Section Messages > Sent 
- [ ] Replied message displays in Case Detail> Case Messages > In-Progress with attached document PDF link displays  
- [ ] Replied message is displayed as current message in thread on Message Detail screen 
- [ ] Replied message subject link displays as “For Review’ 
- [ ] Attached document preview displays on Message Detail screen 


#### 6) Internal user forwards a message to another internal user without a document attached 
* Login as docket clerk1
* Navigate to case 
* Click Create New Message 
* Select Judge Buch as recipient 
* Enter subject line as “For Review” 
* Complete Create New Message form without attachment 
* Click Send 
* Login as Judge Buch
* Click on new message subject link 
* Click Forward 
* Select buchsChambers1 as recipient 
* Enter message
* Click Send
Expected results 
On click of “Forward”, 
- [ ] Forward a Message modal displays
- [ ] “For Review” displays in Subject Line and is editable  
On click of “Send” 
- [ ] Forward a Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox of Judge Buch 
- [ ] Original message is removed from Buch’s Chambers Section Messages > Inbox 
- [ ] Forwarded message displays in My Messages > Sent for Judge Buch
- [ ] Forwarded message displays in Buch’s Chambers Section Messages > Sent 
- [ ] Forwarded message displays in My Messages > Inbox for buchsChambers1 
- [ ] Forwarded message displays in Buch’s Chambers> Section Messages > Inbox 
- [ ] Forwarded message displays in Case Detail> Case Messages > In-Progress
- [ ] Forwarded message is displayed as current message in thread on Message Detail screen 

#### 7) Internal user forwards a message to another internal user with a document attached 
* Login as docket clerk1
* Navigate to case 
* Click Create New Message 
* Select Judge Buch as recipient 
* Attached “Petition” document to message 
* Enter message 
* Click Send 
* Login as Judge Buch
* Click on new message subject link 
* Click Forward 
* Select buchsChambers1 as recipient 
* Enter message
* Click Send
Expected results 
On click of “Forward”, 
- [ ] Forward a Message modal displays
- [ ] “Petition” displays in Subject Line and is editable  
On click of “Send” 
- [ ] Forward a Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox of Judge Buch 
- [ ] Original message is removed from Buch’s Chambers Section Messages > Inbox 
- [ ] Forwarded message displays in My Messages > Sent for Judge Buch with attached document PDF link
- [ ] Forwarded message displays in Buch’s Chambers Section Messages > Sent with attached document PDF link
- [ ] Forwarded message displays in My Messages > Inbox for buchsChambers1 with attached document PDF link
- [ ] Forwarded message displays in Buch’s Chambers> Section Messages > Inbox with attached document PDF link
- [ ] Forwarded message displays in Case Detail> Case Messages > In-Progress with attached document PDF link
- [ ] Forwarded message is displayed as current message in thread on Message Detail screen 
- [ ] Attached document displays in preview on Message Detail screen 

#### 8) Internal user forwards a message that was sent to another user 
* Login as docket clerk1
* Navigate to case 
* Click Create New Message 
* Select Judge Buch as recipient 
* Enter subject line as “For Review” 
* Complete Create New Message form without attachment 
* Click Send 
* Login as docket clerk 2
* Navigate to Case Detail > Case Messages 
* Click on new message subject link to Judge Buch 
* Click Forward 
* Select buchsChambers1 as recipient 
* Enter message
* Click Send
Expected results
On click of Forward  
- [ ] Forward a Message modal displays
- [ ] “For Review” displays in Subject Line and is editable  
On click of Send,
- [ ] Forward a Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox of Judge Buch 
- [ ] Original message is removed from Buch’s Chambers Section Messages > Inbox 
- [ ] Forwarded message displays in My Messages > Sent for docket clerk 2 with attached document PDF link
- [ ] Forwarded message displays in Docket Section Messages > Sent with attached document PDF link
- [ ] Forwarded message displays in My Messages > Inbox for buchsChambers1 
- [ ] Forwarded message displays in Buch’s Chambers> Section Messages > Inbox 
- [ ] Forwarded message displays in Case Detail> Case Messages > In-Progress 
- [ ] Forwarded message is displayed as current message in thread on Message Detail screen 

#### 9) Internal user updates subject line when forwarding a message
* Login as petition clerk1 
* Navigate to case 
* Click Create New Message 
* Select docket clerk 1 
* Attach “Petition” to message
* Enter message 
* Click Send 
* Login as docket clerk 1 
* Click on new message subject link 
* Click Forward 
* Select Judge Buch as recipient
* Edit Subject line to “Petition - Check Jurisdiction” 
* Enter message 
* Click Send
Expected results 
On click of Forward 
- [ ] Forward a Message modal displays 
- [ ] “Petition” is displayed as subject line and is editable 
On click of Send, 
- ] Forward a Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Original message is removed from My Messages > Inbox of docket clerk 1 
- [ ] Original message is removed from Docket Section Messages > Inbox 
- [ ] Forwarded message displays in My Messages > Sent for docket clerk 1 with subject line “Petition - Check Jurisdiction” 
- [ ] Forwarded message displays in Docket Section Messages > Sent with subject line “Petition - Check Jurisdiction” 
- [ ] Forwarded message displays in My Messages > Inbox for Judge Buch with subject line “Petition - Check Jurisdiction” 
- [ ] Forwarded message displays in Buch’s Chambers> Section Messages > Inbox with subject line “Petition - Check Jurisdiction” 
- [ ] Forwarded message displays in Case Detail> Case Messages > In-Progress with subject line “Petition - Check Jurisdiction” 
- [ ] Forwarded message is displayed as current message in thread on Message Detail screen with subject line “Petition - Check Jurisdiction” 
- [ ] Original message displays in message thread on Message Detail screen with subject line “Petition - Check Jurisdiction”
- [ ] Petition document displays in preview on Message Detail screen 


#### 10) Internal user views message thread for replied message 
* Scenario 3 
* Login as adc1 
* Navigate to case (from scenario 3) 
* Navigate to Case Messages > In-Progress 
* Click into message from docket clerk 1 (from scenario 3)
* Expand message thread accordion 
Expected results 
- [ ] Message thread accordion is collapsed on page load 
- [ ] Replied message is displayed as current message in thread on Message Detail screen 
- [ ] Expanded accordion displays original message from petition clerk 1 
- [ ] Petition document PDF displays in preview on message detail screen 

#### 12) Internal user views message thread for forwarded message 
* Scenario 6 
* Login as add1 
* Navigate to case (from scenario 6)
* Navigate to Case Messages > In-Progress 
* Click into message from Judge Buch (from scenario 6)
* Expand message thread accordion 
Expected results 
- [ ] Message thread accordion is collapsed on page load 
- [ ] Forwarded message from Judge Buch is displayed as current message in thread on Message Detail screen 
- [ ] Expanded accordion displays original message from docket clerk1
- [ ] No document PDF displays in preview on message detail screen 

#### 13) Internal user sees message thread history newest to oldest 
* Scenario 3 
* Login as petition clerk 
* Click on message from docket clerk 
* Click Forward 
* Forward message to Judge Copeland 
* Click Send 
* Navigate to My Messages > Sent 
* Click on the forwarded message 
* Expand message thread accordion 
Expected results 
- [ ] Forwarded message (to Judge Copeland) displays as accordion header 
- [ ] Expanded accordion displays message thread history sorted newest to oldest 

#### 14) Internal user completes a message that was sent to them 
* Scenario 2
* Login as petition clerk 1
* Click on message from docket clerk 1 (from scenario 1) 
* Click Complete 
* Enter a comment 
* Click Complete button 
Expected results 
On click of Complete from Message Detail, 
- [ ] Complete Message modal displays 
On click of Complete button on modal 
- [ ] Complete Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Message is removed from My Messages > Inbox for petition clerk 1 
- [ ] Message is removed from Petition Section Messages > Inbox 
- [ ] Message displays in petition clerk 1 My Messages > Completed with comment displayed  
- [ ] Message displays in Petition Section Messages > Completed with comment displayed 
- [ ] Message displays in Case Detail > Case Messages > Completed with comment displayed 
- [ ] Completed message displays as current message in message thread accordion on Message Detail
- [ ] Message detail displays “Completed” warning 


#### 15) Internal user completes a message that was not sent to them 
* Scenario 3 
* Login as adc1
* Navigate to Case Detail > Case Messages > In Progress 
* Click on message sent to petition clerk 1 
* Click Complete 
* Enter a comment 
* Click Complete button 
Expected results 
On click of Complete from Message Detail, 
- [ ] Complete Message modal displays 
On click of Complete button on modal 
- [ ] [ ] Complete Message modal closes 
- [ ] App navigates to My Messages > Inbox with success message displayed 
- [ ] Message is removed from My Messages > Inbox for petition clerk 1 
- [ ] Message is removed from Petition Section Messages > Inbox 
- [ ] Message displays in adc1 My Messages > Completed with comment displayed 
- [ ] Message displays in ADC Section Messages > Completed with comment displayed 
- [ ] Message displays in Case Detail > Case Messages > Completed with comment displayed 
- [ ] Completed message displays as current message in message thread accordion on Message Detail 
- [ ] Message detail displays “Completed” warning 

#### 16) Internal views completed message thread 
* Scenario 15 
* Login as docket clerk 1 
* Navigate to case (from Scenario 15) 
* Navigate to Case Messages > Completed
* Click on completed message (from Scenario 15)
* Expand message thread 
Expected results 
- [ ] Completed message displays as accordion header 
- [ ] Completed “warning” displays on Message Detail 
- [ ] Expanded accordion displays message history sorted newest to oldest 

#### 17) Internal views completed message thread in My Messages > Completed queue/ Section Messages> Completed for seven days 
* Scenario 15 
* Login as adc1 
* Navigate to My Messages > Completed 
* Navigate to adc Section Messages > Completed 
Expected results 
- [ ] Message completed by adc1 (scenario 15) displays in My Messages > Completed 
- [ ] Message completed by adc1 (scenario 15) displays in adc Section Messages > Completed 
- [ ] Most recent message displays in completed message line item under “Last Message” column
- [ ] Comment entered in Complete Message modal displays under “Comment” column 
- [ ] “Completed by” displays as “adc1” in Section Messages > Completed 
- [ ] “Section” displays as “ADC” in Section Messages > Completed 

#### 18) Internal user views Tracked Items for a case 
* Login as docket clerk 1
* Navigate to a case 
* Click “Tracked Items” 
* Click Pending Report tab
Expected results 
- [ ] Tracked Items tab displays on Case Detail screen 
On click of Tracked Items:
- [ ]  Deadlines tab is selected by default 
- [ ] Deadlines tab displays deadlines table
On click of Pending Report tab:
- [ ] Pending Report tab is selected 
- [ ] Pending Report table displays 

#### 19) Internal user views Drafts for a case 
* Scenario 18
* Click on Drafts tab 
Expected results 
- [ ] Drafts tab displays on Case Detail screen 
- [ ] Draft documents table displays 

#### 21) Internal user views all In Progress messages for a case 
* Scenario 2 
* Login as docket clerk 
* Navigate to case (from scenario 2) 
* Create New Message to Judge Buch 
* Send 
* Navigate to Case Detail > Case Messages > In Progress 
Expected results 
- [ ] New message to Judge Buch displays under In Progress tab 
- [ ] Message to petition clerk 1 (from scenario 2) displays in In Progress tab 
- [ ] Messages in In-Progress tab are sorted newest to oldest 

#### 22) Internal user views all Completed messages for a case
* Login as petition clerk
* Navigate to Case 
* Create send message to Judge Buch
* Create and send message to docket clerk 1
* Login as Judge Buch and complete message 
* Login as docket clerk 1 and complete message 
* Navigate to Case Detail > Case Messages 
Expected results
- [ ] Completed message by Judge Buch displays under Completed tab 
- [ ] Completed message by docket clerk 1 displays under Completed tab 
- [ ] Completed messages display sorted by newest to oldest by date/time completed

**Comment by JessicaMarine** [comment]
PO feedback 6/24/2020:
* The messages are still staying in the Inbox after you fwd or reply until you navigate somewhere else or hit refresh.  They need to clear immediately.
