### ISSUE TITLE
Court: Create an order tied to a message thread

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4611]
As a court employee, so I can create an order in response to an open message thread, I need the ability to create an order that's associated to the thread.

## Acceptance Criteria
* Court user can create an order from a messaging thread
* The new order is "attached" to the message
* When the order is saved, user is routed back to the message page
* Order should appear in draft documents

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Update Apply Signature screen for the Create Order flow to include "Skip Signature" 

## Tasks
- [x] 1 Add “Create Order” link to message actions - should open modal (Rachael #5597)
- [x] 2 Add Skip Signature button and functionality to Apply Signature screen (Cody #5605)
- [x] 3 Navigate back to Message Detail with success message displayed after skipping or saving signature (Rachael #5608)
- [x] 4 Update create order endpoint - send messageId in props; submitted Order is attached to the latest message in the thread (Rachael #5599)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Updated Message Detail screen 

* Add "Create Order" link to message actions 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/76212906-1394-4ca4-9a9a-2b0f3b41d341)

*On click of "Create Order"

**Comment by klohman** [comment]
4611 + 4612 


## 4611 Test Scenarios 

#### 1) Internal user launches order flow from Message Detail 
* Login as docket clerk 1
* Navigate to Case xx1-20
* Create New message w/o attachments - subject line: Need Order 
* Send to docket clerk 2 
* Login as docket clerk 2 
* Click on message “Need Order” 
* Click “Create Order” on Message Detail screen 
Expected results 
- [ ] Create Order or Notice modal displays 

#### 2a) Internal user skips signature in order flow from Message Detail 
* Scenario 1 
* Select “Order” as order type 
* Click Continue 
* Enter Order Text 
* Save 
* Click Skip Signature
Expected results 
On click of Save: 
- [ ] App navigates to Apply Signature screen with “Skip Signature” button displayed 

On click of Skip Signature: 
- [ ] App navigates to Message Detail with success message displayed
- [ ] Order is attached to Message 
- [ ] Order is saved into Draft Documents without signature 

#### 2b) Internal user skips signature in order flow from Case Detail 
* Login as docket clerk 1
* Navigate to Case xx1-20
* Click “Create Order or Notice” from case Actions dropdown
* Select “Order for Dismissal” as order type
* Enter Order text 
* Save 
* Click Skip Signature 
Expected results 
On click of Save: 
- [ ] App navigates to Apply Signature screen with “Skip Signature” button displayed 

On click of Skip Signature: 
- [ ] App navigates to Draft Documents tab with success message displayed
- [ ] Order is saved into Draft Documents without signature 

#### 3a) Internal user adds signature in order flow from Message Detail   
* Scenario 1 
* Select Notice as order type 
* Enter Order text 
* Save 
* Apply signature to PDF 
Expected results: 
- [ ] Skip Signature button is hidden 
- [ ] Save Signature button displays 
- [ ] Delete Signature button displays 

#### 3b) Internal user adds signature in order flow from Case Detail 
* Login as docket clerk 1
* Navigate to Case xx1-20
* Click “Create Order or Notice” from case Actions dropdown
* Select “Order to Show Cause” as order type
* Enter Order text 
* Save 
* Apply signature to PDF 
Expected results 
- [ ] Skip Signature button is hidden 
- [ ] Save Signature button displays 
- [ ] Delete Signature button displays 

#### 4a) Internal user saves signature in order flow from Message Detail 
* Scenario 3a
* Click Save Signature button
- Expected results 
- [ ] App navigates to Message Detail with success message displayed
- [ ] Notice is attached to Message 
- [ ] Notice is saved into Draft Documents with signature 

#### 4b) Internal user saves signature in order flow from Case Detail
* Scenario 3b 
* Click Save Signature
Expected results 
- [ ] App navigates to Draft Documents tab with success message displayed
- [ ] Order is saved into Draft Documents with signature 

#### 5) Internal user sees new order attached to original message on Message Detail
* Scenario 4a
* View Notice PDF 
Expected results 
- [ ] Notice is displayed as attachment to message 
- [ ] On select of Notice, Notice PDF is displayed in the PDF viewer 

#### 6) Internal user sees new order attached to message when replying to message 
* Scenario 5 
* Click Reply 
Expected results 
- [ ] Notice displays in Reply to Message modal under Attachments 

#### 7) Internal user sees new order attached to message when forwarding message 
* Scenario 5 
* Click Forward 
Expected results 
- [ ] Notice displays in Forward Message modal under Attachments

**Comment by klohman** [comment]
## UX feedback

-[ ] When creating a Notice from the Message Detail - on Save, app should navigate back to the Message Detail screen with notice attached (I didn’t specifically outline this but have now added a text scenario) 
- [ ] Order Flow from Case Detail > On Save of Signature should navigate to Drafts screen (currently it’s going to the Draft Document Detail)
