### ISSUE TITLE
Court: Take action on a document from the message thread

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4612]
## Acceptance Criteria
* Court user can take action on a draft document from the message view (edit, apply/edit signature, add docket entry for petitions and docket, view Full PDF)
* For externally filed documents and served court-issued documents, court users should be able to view full PDF
* If an action is initiated from the message view, the user will return back to that message after the action is complete. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add Actions bar to document display on message detail (Matt #5635)
  - [x] 1a Computed for which buttons to show/hide on the bar based on document type and user role (Matt #5641)
- [x] 2 Edit Order navigation updates (Rachael #5649)
- [x] 3 Apply Signature navigation updates (Cody #5650)
- [x] 4 Add Docket Entry navigation updates (Matt #5653)
- [x] 5 View Full PDF link (Rachael #5652)
- [x] 6 Edit Signature updates (Rachael #5657)
- [x] 7 Refactoring - always get parentMessageId from the same place in state (sometimes it's in state.modal.parentMessageId, state.form.parentMessageId, or state.parentMessageId) (Cody #5655 5655)
- [x] 8 Update navigation to use `followRedirectAction` (Rachael)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Unsigned Draft Document attached to message (Docket/Petitions/Clerk of the Court) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5f6da71b-000b-4972-99ae-197e150068dc)

#### Edit
* On click, navigates to "Edit Order" screen (see example screenshot below) 
* on click of "Save" on Edit Order screen, app navigates to Apply Signature screen 

![Screen Shot 2020-06-17 at 2.38.13 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b596a19c-a1ad-4573-a3d9-12d5e4c8b475) 

## Apply Signature
* On click of Apply Signature, app navigates to Apply Signature screen 
* On click of "Skip Signature", app navigates back to Message Detail with success message displayed: 
"[Order/Notice title] updated."
* On click of "Save Signature", app navigates back to Message Detail with success message displayed: 
"[Order/Notice title] updated." 

## Add Docket Entry
* Link is only visible to Docket / Petitions / Clerk of the Court 
* On click of Add Docket Entry, navigate to Add Court Issued Docket Entry screen 

**On Save Entry from Add Court Issued Docket screen**
* On click of "Save entry", app navigates to Message Detail with success message displayed: "Entry added to Docket Record" 
* Document is removed from Draft Documents table 
* Docket entry is saved on the docket record as "not served" 
*.Document displays attached to message as docket record document 

**On Save and Serve from Add Court Issued Docket screen**
* On click, app navigates to Message Detail with success message displayed: "Document served."
* Document is removed from Draft Documents table 
* Docket entry is saved on the docket record with service information applied 
*.Document displays attached to message as docket record document 
* Service emails are sent to parties 

#### View Full PDF 
* On click, open selected document PDF in new tab

**Comment by klohman** [comment]
## 4612 Test Scenarios 

#### Create test data 

**Case xx1-20**
* Create and save as unsigned draft “Order to Show Cause” 
* Create and save signed draft “Order for Dismissal” 
* File “Answer” 

* Login as docket clerk1 
* Navigate to Case xx1-20 
* Create message to petitions clerk 1
* Attached Order to Show Cause, Order for Dismissal, and Answer 
* Send message 

#### 1) Docket/petition/clerk of court sees document actions for draft documents attached to message
* Login as petitions clerk 1 
* Navigate to message Inbox and click on message from docket clerk 1 
* Select the Order to Show Cause attachment 
Expected results 
- [ ] Action bar displays with draft document actions 
    - Edit 
    - Apply Signature 
    - Add Docket Entry
    - View Full PDF 

#### 2) Other internal user sees document actions for draft documents attached to message
* Login as admissions clerk 1 
* Navigate to Case xx1-20 > Case Messages > In Progress and click on message from docket clerk 1 
* Select the Order to Show Cause attachment 
Expected results 
- [ ] Action bar displays with draft document actions 
    - Edit 
    - Apply Signature 
    - View Full PDF 

#### 3) Internal user edits draft document from message 
* Scenario 1 
* Click Edit link 
* Update Order text 
* Click Save 
Expected results
- [ ] On click of Edit link, app navigates to Edit Order screen 
- [ ] On click of Save, app navigates to Message Detail with success message displayed “Order to Show Cause updated” 

#### 4) Internal user applies signature on draft document from message 
* Scenario 1 
* Click “Apply Signature” link 
* Add signature to Order to Show Cause 
* Click Save Signature 
Expected results 
- [ ] On click of Apply Signature, app navigates to Apply Signature screen 
- [ ] on click of Save Signature, app navigates to Message Detail with success message displayed “Signature added.” 
- [ ] “Apply Signature” link in document actions updates to “Edit Signature”

#### 5) Internal user edits signature on draft document from message
* Scenario 2
* Click “Edit Signature” link
* Click Delete Signature 
* Add new signature 
* Click Save Signature 
Expected results 
- [ ] On click of Edit Signature, app navigates to Apply Signature screen
    - Delete Signature button displays 
    - Save Signature button displays 
- [ ] on click of Save Signature, app navigates to Message Detail with success message displayed “Signature added.” 
- 
#### 6) Internal user views full PDF of draft document from message 
* Scenario 1
* Click View Full PDF 
Expected results 
- [ ] Order to Show Cause PDF opens in new tab 

#### 7)  Docket/petitions/CoC adds docket entry for draft document and saves entry from message 
* Login as docket clerk1 
* Navigate to Case xx1-20 > Case Messages > In Progress and click on message from docket clerk 1 
* Select Order for Dismissal 
* Click Add Docket Entry 
* Complete form 
* Click Save Entry 
Expected results 
On click of Add Docket Entry
- [ ] app navigates to Add Court-Issued Docket Entry screen

On click of Save Entry: 
- [ ] app navigates to Message Detail with success message displayed 
- [ ] Order for Dismissal displays action: View Full PDF 
- [ ] Order for Dismissal does not display actions: Edit, Apply Signature, Edit Signature, Add Docket Entry 
- [ ] Order for Dismissal displays on docket record as “not served”


#### 8) Docket/petitions/CoC adds docket entry for draft document and serves document from message 
* Login as docket clerk1 
* Navigate to Case xx1-20 > Case Messages > In Progress and click on message from docket clerk 1 
* Select Order to Show Cause 
* Click Add Docket Entry 
* Complete Form 
* Click Save and Serve 
Expected results 
On click of Add Docket Entry
- [ ] app navigates to Add Court-Issued Docket Entry screen

On click of Save and Serve: 
- [ ] app navigates to Message Detail with success message displayed 
- [ ] Order to Show Cause displays action: View Full PDF 
- [ ] Order to Show Cause does not display actions: Edit, Apply Signature, Edit Signature, Add Docket Entry 
- [ ] Order to Show Cause displays on Docket record with service information 
- [ ] Served stamp is applied to Order to Show Cause 
- [ ] Parties receive service email 

#### 9) Internal user views actions for docket record document attached to message 
* Login as adc1
* Navigate to Case xx1-20 > Case Messages > In Progress and click on message from docket clerk 1 
* Click on Answer 
Expected results 
- [ ] Answer displays document action : View Full PDF 
- [ ] Answer does not display document actions : Edit, Apply Signature, Edit Signature, Add Docket Entry  

#### 10) Internal user views full PDF of docket record document attached to message 
* Scenario 9 
* Click View Full PDF 
Expected result 
- [ ] Answer PDF opens in new tab

**Comment by JessicaMarine** [comment]
PO Review 7/2/2020:
* When I tried to edit the content of an Order from the message detail screen, it erased the document title: 
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/5ab1f244-7e7f-44be-a33d-104e7c22c3f0)
