### ISSUE TITLE
Court: Draft view of document detail

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4613]
## Acceptance Criteria
* All documents on the docket record display on the left of the document
* User should be able to view a full-page PDF
* User can edit, apply signature, edit signature, add docket entry for docket clerks and petitions clerks

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add Draft Document view to Drafts tab on case detail (only for internal users) - Mrinalini #5731
- [x] 2 Draft Document view left panel (display all drafts sorted by created date) - Mrinalini #5731 
- [x] 3 Draft Document view right panel (PDF viewer, sequences to update which document is displayed) - Mrinalini #5735
- [x] 4 Draft Document view action bar, computed to determine which actions to display (Rachael #5736)
~- [ ] 5 Delete old Drafts Document view (Rae, Mrinalini)~ Will instead be completed in a devex task (https://trello.com/c/4a1r9ZF2/668-remove-references-to-documentdetail-view)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Flow 
* On click of a draft document link from Drafts table, navigate to the updated Draft Document View 


### Draft Document View (Internal users not Docket/Petitions/Clerk of the Court) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/05140c59-8636-431a-b443-900ad07a5c8f)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/91331880-f3fe-4ea6-a42f-095057d138af)

#### List of Draft documents (left panel) 
* Display all draft documents sorted by Created date (oldest to newest) 
* Displays [Document Title] and Created by [User name who created the draft]
* the first (oldest) draft should be selected 

#### Draft PDF (right panel) 
* PDF viewer displays selected draft document PDF 
* On select of another draft document from left panel, PDF viewer updates to display selected document

#### Draft Document Actions  
**Edit**
* On click, navigates to "Edit Order" screen (if document has already been signed, displays "Editing. this document will remove signature" modal, and then navigate to Edit Order screen)
* on click of "Save" on Edit Order screen, app navigates to Apply Signature screen

**Delete**
* On click of Delete, display "Are you sure you want to delete this document?" modal 
* On "Yes", modal closes and page refreshes with success message displayed and deleted draft document removed from list 

**Apply Signature**
Action displays if the document has not yet been signed 

* On click of Apply Signature, app navigates to Apply Signature screen
* On click of "Skip Signature", app navigates back to Draft Document View with success message displayed:"[Order/Notice title] updated."
On click of "Save Signature", app navigates back to Draft Document View with success message displayed: "[Order/Notice title] updated."

**Edit Signature**
Action displays. if the document has been signed 
* Navigate to Apply Signature screen with Save Signature and Delete Signature buttons displays

* when user completes action (Deletes, Saves, or Skips signature), navigate back to Draft Document View with success message displayed: "[Order/Notice title] updated."

**Comment by klohman** [comment]
### 4613 Test Scenarios

Create Case xx1-20
- Create “Order for Dismissal” (unsigned)
- Create “Order to Show Cause” (unsigned)
- Upload “Minute Sheet”


#### 1)  Internal user sees all draft documents in draft view 
* Login as internal user 
* Navigate to case xx1-20 
* Click the “Drafts” tab 
Expected results 
- [ ] List of draft documents is displays in left panel 
    - Order for Dismissal 
    - Order to Show Cause 
    - Minute Sheet
- [ ] Order for Dismissal is selected by default 
- [ ] Order for Dismissal PDF is displayed in PDF preview 

#### 2) Internal user toggles between draft document PDF views 
* Scenario 1 
* Click “Minute Sheet” 
Expected results 
- [ ] Minute Sheet displays as selected from Drafts list 
- [ ] Minute Sheet PDF is displays in PDF preview 

#### 3a) Internal user (not petitions/docket) sees actions for draft document in draft view 
* Login as ADC 
* Navigate to Case xx1-20
* Click “Drafts’ tab
* Click Order to Show Cause 
Expected results 
- [ ] Order to Show Cause displays actions 
    - Edit 
    - Apply Signature 
    - View PDF 

#### 3b) Petitions/docket/CoC sees actions for draft document in draft view 
* Login as docket clerk 
* Navigate to Case xx1-20
* Click “Drafts’ tab
* Click Order to Show Cause 
Expected results 
- [ ] Order to Show Cause displays actions 
    - Edit 
    - Apply Signature 
    - View PDF 
    - Add Docket Entry 

#### 4) Internal user edits draft document from Drafts screen 
* Login as ADC 
* Navigate to Case xx1-20
* Click “Drafts’ tab
* Click “Edit” link for Order for Dismissal 
* Update Order text 
* Save 
* Skip signature
Expected results 
On click of Edit:
- [ ] App navigates to Edit Order screen 
On click of Skip Signature 
- [ ] App navigates back to Draft view with “Order for Dismissal” selected and success message displayed 

#### 5) Internal user deletes draft document from Drafts screen 
* Login as ADC 
* Navigate to Case xx1-20
* Click “Drafts’ tab
* Click “Delete” link for Order for Dismissal 
* Confirm delete on modal 
Expected results 
On click of “Delete”:
- [ ] Delete confirmation modal displays 
On click of “Yes, Delete” from modal:
- [ ] Modal closes 
- [ ] Success message displays “Document deleted” 
- [ ] Order for Dismissal is removed from draft list 
- [ ] Order to Show Cause is selected in draft list
- [. ] Order to Show Cause PDF displays in PDF viewer 

#### 6) Internal user applies signature to draft from Drafts screen 
* Login as ADC 
* Navigate to Case xx1-20
* Click “Drafts’ tab
* Click Order to Show Cause 
* Click Apply Signature 
* Add signature 
* Save Signature 
Expected result	
- [ ] App navigates back to Drafts view with Order to Show Cause selected and success message displayed 
- [ ] Order to Show Cause PDF displays in PDF viewer with Chief Judge signature added 
- [ ] “Edit Signature” action replaces “Apply Signature” link in document actions toolbar

#### 7) Internal user edits signature on draft from Drafts screen 
* Scenario 6 
* Login as judge Buch
* Click “Edit Signature” link for Order to Show Cause 
* Click Delete Signature
* Add new signature  
* Click Save Signature 
Expected results 
- [ ] App navigates back to Drafts view with Order to Show Cause selected and success message displayed 
- [ ] Order to Show Cause PDF displays in PDF viewer with Judge Buch signature added 
- [ ] “Edit Signature” action replaces “Apply Signature” link in document actions toolbar

#### 8) Internal user views full PDF of draft document from Drafts screen 
* Login as admissions clerk 
* Navigate to Case xx1-20 
* Click Drafts tab 
* Click “View Full PDF” on Order to Show Cause 
Expected results 
- [ ] Order to Show Cause PDF opens in new tab 

#### 9) Docket/petitions clerk adds docket entry for draft and saves entry from Drafts screen 
* Login as docket clerk 
* Navigate to case xx1-20
* Click Drafts tab 
* Click Minute Sheet 
* Click Add Docket Entry 
* Complete form 
* Click Save Entry 
Expected results 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Entry for Minute Sheet is added to docket record with “not served” indicated 
- [ ] Minute Sheet is removed from Drafts list 


#### 10) Docket/petitions clerk adds docket entry for draft and serves from Drafts screen 
* Login as docket clerk 
* Navigate to case xx1-20
* Click Drafts tab 
* Click Order to Show Cause 
* Click Add Docket Entry 
* Complete form 
* Click Save and Serve 
Expected results 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Entry for Order to Show Cause is displayed on docket record with service information 
- [ ] Order to Show Cause is removed from Drafts list

**Comment by klohman** [comment]
## Unsigned Draft - from Upload PDF 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/af42c127-1802-4a2d-a793-0fa5e322efac)

* Displays Apply Signature option
* Displays Add Docket Entry (for users w/ permission) 

## Unsigned Draft - Orders, Notices, Decisions
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1f22ae2f-d883-40dd-9f37-b96b0a407c23)

* Display Apply Signature 
* Hide Add Docket entry action
* Display message "Signature required for this document."


## Add Court-Issued Docket Entry

**Document type**
* On click of Serve and Save or Save Entry
If Document type  requires a signature + document has not been signed 
* Display error message : Signature required for this document."
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/965bc4dd-43f7-433e-9f0f-81391b1c6e71)
