### ISSUE TITLE
Court: Tweaks to Document Codes

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4651]
As a court, so that we can go-live with accurate filing codes, we need to clean-up the document codes.

## Acceptance Criteria: ##
* `MISL` when an external parties lodges a document should be `MISCL`- Done 
* The code for Notice of Trial should be `NTD` not `NDT
* Confirm event code for: Oral *anything* [internal only] -- see comment below
* Confirm event code for: Redacted *anything* [internal and external] -- see comment below
* Confirm event code for: Unredacted *anything* [internal and external] -- see comment below
* Options for Petitions/Calendar in Order/Notice generator needs to include: - (done in #5715)
   * Order (already have)
   * Notice (already have)
   * Order of Dismissal for Lack of Jurisdiction
   * Order to Show Cause
* Fix Transcript codes 
TRAN      Transcript of [date] *anything*
RTRA       Revised Transcript of [date] *anything*
CTRA       Corrected Transcript of [date] *anything*

Separate story:
* Docket drop-down -- shouldn't have code and title -- same as magic selector for eFiled docs

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] The code for Notice of Trial should be `NTD` not `NDT` (Rae, Mrinalini #5797)
- [x] Fix Transcript codes (Kristen [#5789](https://github.com/flexion/ef-cms/pull/5789))

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written (
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
@JessicaMarine Please review and let me know if we need to make changes regarding these codes. 

**Confirm event code for: Oral anything [internal only]**
 - we got rid of this when we reviewed codes with Cheryl + Rhonda and only have Motion for Oral Argument with event code "ORAL" - it's currently accessible to file for external parties and internal (paper) 

 ![Screen Shot 2020-07-07 at 1.00.05 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/40c63179-36f5-4a4a-a643-44c67ddcf493)

**Confirm event code for: Redacted anything [internal and external]**
- "Redacted" doc type has event code "REDC"
- In UI the concatenated name will be "Redacted [Document Name]" 
![Screen Shot 2020-07-07 at 1.05.36 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2dbf8cae-c15f-4242-ad4e-f5a391ca3e90)

**Confirm event code for: Unredacted anything [internal and external]**
* removed from list when we reviewed codes with Chery + Rhonda 
![Screen Shot 2020-07-07 at 1.07.17 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c9a7e969-9b90-4e4a-85db-989f7d6bbe0f)

**Comment by klohman** [comment]
#### 1) Docket clerk enters docket entry for Corrected Transcript
* Login as docket clerk 
* Navigate to case 
* add a draft document
* Navigate to draft document
* Click Add Docket Entry 
* Select Corrected Transcript as Document Type
* Complete Form 
* Click Save Entry 
Expected results 
On select of Corrected Transcript 
- [ ] Date field displays and is required 
- [ ] Enter description field displays and is required 
On save entry
- [ ] Docket entry is created and concatenated as "Corrected Transcript of [description] on [date]

#### 2) Docket clerk enters docket entry for Revised Transcript
* Login as docket clerk 
* Navigate to case 
* add a draft document
* Navigate to draft document
* Click Add Docket Entry 
* Select Revised Transcript as Document Type
* Complete Form 
* Click Save Entry 
Expected results 
On select of Reviseed Transcript 
- [ ] Date field displays and is required 
- [ ] Enter description field displays and is required 
On save entry
- [ ] Docket entry is created and concatenated as "Revised Transcript of [description] on [date]

#### 3) Petition clerk creates Order 
* Login as petitions clerk 
* Navigate to case 
* Click Create Order or Notice 
* View dropdown options  
expected results 
- [ ] Order type dropdown contains 
   * Order (already have)
   * Notice (already have)
   * Order of Dismissal for Lack of Jurisdiction
   * Order to Show Cause

#### 4) User sees docket entry for Notice of Trial 
* Login as docket clerk 
* NAvigate to cas 
* Add docket entry for Notice of Trial 
* View Docket record 
expected results 
- [ ] Notice of Trial event code displays as "NTD"

#### 5) User sees docket entry for Miscellaneous document  
* Login as petitioner
* NAvigate to cas 
* File Motion for Leave to File Administration Record" with Administrative Record uploaded
* View Docket record 
expected results 
- [ ] Administrative Record (Lodged) event code displays as "MISCL"

**Comment by JessicaMarine** [comment]
PO Review 7/10/2020:
* Filed a motion for leave to file a motion for summary judgment in Docket No. 101-20.  The motion for summary judgment is LODGED and should have the doc code MISCL -- it doesn't:
image.png 
image.png

* Same issue when I uploaded a paper filed document in 101-20 and "lodged" it:
image.png 
image.png
