### ISSUE TITLE
Docket Clerk: Can complete and send message from the QC screen

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4655]
As a Docket Clerk, so that I can send a message related to a document, I need the ability to complete and send a message from the QC screen.

## Acceptance Criteria
* Docket Clerk can complete document QC and send a message to another court user.
* QC document is automatically attached to the message
* Subject line of message is auto-populated with the document name
* Once the message is sent, the clerk is routed back to their MydocQC box

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] Add ‘Complete and Send Message’ modal - Rachael, Mrinalini, Matt, Rae #5766
 - [x] Submit message sequence - Rae, Mrinalini #5773

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Complete and Send Message 

**From the Docket -  Document QC screen**
On click of "Complete and Send Message" button
* Display "Complete and Send Message" modal (new) 
* Document being QC'd is automatically attached to message 
* Document being QC'd title is displayed as Subject Line and is editable 
* Clerk can attach up to 4 additional documents 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8fec02ac-4b8b-43b5-a77f-3a6c4ad740e1)

On click of "Send" button: 
* App navigates to My Document QC > Inbox with success message displayed: "[Document title] QC completed and message sent."
* Message displays in My Messages > Inbox for recipient 
* Message displays in Section Messages > Inbox for recipient section
* Message displays in My Messages > Sent for sender 
* Message displays in Section Messages > Sent for sender 
* Document displays in My Document QC > Processed and Section Document QC > Processed

**Comment by klohman** [comment]
## 4655 Test Scenarios 	

#### 1) Docket clerk sees new message modal when completing QC and sending message
* Login as docket clerk 1
* Navigate to Document QC > Inbox 
* Click on document link  
* Click Complete and Send Message 
Expected results 
- [ ] Complete and Send Message modal displays 
- [ ] Subject Line is populated with document title 
- [ ] Document title is displayed under “Attachment(s)”

#### 2) Docket clerk sends message from QC screen 
* Scenario 1 
* Select section = Petitions
* Select recipient = Petitions clerk1
* Add message text 
* Click Send  
Expected results 
- [ ] App navigates to My Document QC > Inbox with success message displayed "[Document title] QC completed and message sent."
- [ ] Message displays in My Messages > Sent for docket clerk 1
- [ ] Message displays in docket Section Messages > Sent
- [ ] Message displays in My Messages > Inbox for petitions clerk 1
- [ ] Message displays in petitions Section Messages > Inbox 
- [ ] Document no longer displays in My Document QC > Inbox 
- [ ] Document no longer displays in docket Section Document QC > Inbox 
- [ ] Document displays in My Document QC > Processed
- [ ] Document displays in docket Section Document QC > Processed
