### ISSUE TITLE
Petitions/Calendar Clerk: Add statistics during petition entry and QC

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4657]
As a Petitions/Calendar Clerk, so that I can capture statistics on a case, I need the ability to add data during the Petition QC process.

## Acceptance Criteria
* For **deficiency** cases, where there IS an IRS notice, a Petitions/Calendar Clerk- must have the ability to capture the following information for each tax year while entering a paper case or performing an electronic petition QC.  
   (1) Deficiency amount proposed by IRS 
   (2) Individual penalties
   (2) Aggregate penalty amount (not broken out by type), which are calculated from the individual entries

[Note: For all other case types (CDP, Whistleblower, Passport, Partnership, etc.), we will not capture any amounts at issue or amounts determined by the Court.]

* These case statistics should be viewable to all Court employees
* Case statistics are not viewable by external users

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add array of statistics to Case entity (include in block of data that is filtered out for external users) (Rachael, Matt #5189)
  - [x] 1a Add Statistic entity (Rachael, Matt #5189)
- [x] 2 Create StatisticsForm UI component and include in StartCaseInternal and PetitionQC screens (Rachael #5214 #5216)
  - [x] 2a Only display if case type is Deficiency and hasVerifiedIrsNotice is true
  - [x] 2b Create a computed just for this component
- [x] 3 Create Calculate Penalties modal (Matt #5215)
- [x] 4 Sequences, actions to calculate penalties (Matt #5223)
- [x] 5 Add Statistics to ReviewSavedPetition view (Rachael #5221)
- [x] 6 Validation (make first statistic required) (Cody #5227 #5233)
- [x] 7 Find a component to use for formatting currency during data input (Rachael #5229)
- [x] 8 Use currency component for penalty modal (Rachael)
- [x] 9 Validation bug fix - period date (Rachael)
- [x] 10 Update validation error messages in the error notification for statistics (Rachael)

Refactoring
- [x] 1 Look at how we compute dates for submitting a paper petition vs qc'ing a petition (Rachael)
- [x] 2 Convert statistics on Review Petition screen into a table for accessibility (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment (Due to staging freeze, Jessica tested in dev)

**Comment by klohman** [comment]
### Create Case (Paper Petition) / Petition QC > IRS Notice tab  
**Deficiency is selected as case type**
* Display "Statistics Proposed by IRS" fields (one set) 

**Year/Period**
* is optional 
* numeric values only 
* max characters = 4 

**Deficiency**
* is optional 
* numeric values only 
* format for US currency during input = $XX,XXX.XX  

**Total penalties**
* is optional 
* numeric values only 
* format for US currency during input = $XX,XXX.XX  

#### Calculate penalties 
* On click of Calculate penalties, display modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fb47addc-c3f8-4592-9480-e2d3b949ad30)

**Penalty 1**
* is required
* Error message if blank or invalid on Save: "Enter a valid penalty amount" 
* numeric values only 
* format for US currency during input = $XX,XXX.XX 

**Penalty 2-5**
* Optional 
* numeric values only 
* format for US currency during input = $XX,XXX.XX 

**Add another penalty**
* On click, display one more "Penalty # (IRS)" field up to a maximum of 10 
* On display of Penalty 10 (IRS) filed, hide "Add another penalty" link

**On click of Calculate button**
* Modal closes 
* Total penalties field = sum of Penalty 1 (IRS) through Penalty 10 (IRS) fields 
* Total penalties field is editable 

#### Add Another Year/Period
* On click of Add Another Year/Period button, display one more set of Statistyics fields up to a maximum of 12 
   * Year/Period
   * Deficiency 
   * Total Penalties 
   * Calculate penalties link
* On display of 12 statistics field sets, hide Add Another Year/Period button
 
### Review Your Petition screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6f5609df-5f80-4592-9453-b6c4a22f22f0)

* Add statistics fields to IRS Notice card 
* Year/Period 
* Deficiency 
* Total penalties

**Comment by klohman** [comment]
## Case Detail > Case Information > Statistics tab 
* Create new tab nested under Case Information - Statistics 

**No statistics added**
 ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/076b260a-3c9b-497c-82f3-3b2a147c9c03)

* If no statistics have been added to the case, display message "There are no statistics for this case."
* Display "Add Year/Period" button 
* on click of "Add Year/Period" button, navigate to Add Statistics screen 

### Statistics table
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a140ecab-d896-472f-91b4-d8c6b8f1b4d0)

#### Deficiency
Table displays if: 
* Case type = Deficiency
* at least 1 year/period has been added 

**Year/Period**
* displays the Year/Period entered on the Petition QC form or Add/Edit Statistics screen 

**IRS Notice** 
Displays data entered: 
* Petition QC form > Deficiency field 
* Add/Edit Statistics form > Deficiency (IRS Notice)  

**Determination** 
Displays data entered: 
* Add/Edit Statistics form > Deficiency (Determination)
  
#### Penalties
**Year/Period**
* inherited from Deficiency table, not displayed

**IRS Notice** 
Displays data entered: 
* Petition QC form > Total penalties field 
* Add/Edit Statistics form > Total penalties (IRS Notice)  

**Determination** 
Displays data entered: 
* Add/Edit Statistics form > Total penalties (Determination)

#### Other 
Table displays if: 
* "Litigation costs" field or "Damages" field has been entered on Add/Edit Statistics screen 

**Litigation costs**
Displays data entered: 
* Add/Edit Statistics > Litigation costs 

**Damages (IRC §6673)**
Displays data entered: 
* Add/Edit Statistics > Damages (IRC §6673) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c534cc4f-2e34-4d6e-ba53-bdc456214362)

**Comment by klohman** [comment]
## Add Statistics screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97dfe655-cb5d-4d8b-a89d-30a16fda39f8)

**Year/Period**
* Required field 
* If blank or invalid, display error message on save : "Enter a valid year/period"
* Numeric values only 
* Max characters = 4 

**Deficiency (IRS Notice)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Total penalties (IRS Notice)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Calculate IRS penalties**
* On click of Calculate IRS penalties, display Calculate IRS Penalties modal (Same functionality as on Petition QC screen) 
* Saved sum value of all penalties is displayed in Total penalties (IRS Notice) field 

**Deficiency (Determination)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Total penalties (Determination)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Calculate Court penalties**
* On click of Calculate Court penalties, display Calculate Court Penalties modal 
* Saved sum value of all penalties is displayed in Total penalties (Determination) field 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/22f3449c-c058-4676-a1a2-bc0d135ad851)
 
**On click of "Add Year/Period" button from Statistics tab**
* On save, app navigates to Case Information > Statistics tab with success message displayed

**Comment by klohman** [comment]
## Edit Deficiency stats 

* On click of Edit link on Deficiency table on Statistics, navigate to Edit Deficiency screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57adcb29-f5b5-4865-90ba-94d5633b718d)

#### Year tabs 
* Each year/period added displays as a different tab 

Tab contains fields:
* Deficiency (IRS Notice) - displays data entered on Petition QC or Add Deficiency screen 
* Deficiency (Determination) - displays data entered on Add Deficiency screen 
* Total penalties (IRS Notice) - displays data entered on Petition QC or Add Deficiency screen 
* Total penalties (Determination) - displays data entered on Add Deficiency screen 

**Calculate IRS/Court Penalties**
* functionality should mimic the Add Deficiency screen 
* Values entered in Penalty fields should be retained and editable (TBD question to Jessica)

**Add Deficiency link**
* On click, navigate to Add Deficiency screen 

#### On save 
* App navigates to Case Information> Statistics tab with success message displayed 
* updated data displays on Deficiency/Penalties tables 


## Edit Other Statistics screen 
* On click of Edit link on Other table on Statistics, navigate to Edit Other Statistics screen 

Contains fields: 
* Litigation costs 
* Damages 

#### On Save 
* App navigates to Case Information> Statistics tab with success message displayed 
* updated data displays on Other tables 

**If both Litigation and Damages fields are blank**
 * Other statistics table is hidden on Statistics screen 
* Add Other Stats link displays on Statistics screen

**Comment by klohman** [comment]
### 4657 Test Scenarios 

### Create Case form (Paper cases)
#### Scenario 1a) Create Case form: Petitions clerk sees deficiency statistics for paper petition before case creation when case type is Deficiency 
* Login as petitions clerk 
* Click Create Case > IRS Notice tab 
* Select case type = Deficiency
Expected results 
- [ ] Statistics Proposed by IRS displays 
- [ ] Year/Period field displays as optional
- [ ] Deficiency field displays as optional 
- [ ] Total penalties field displays as optional 

#### Scenario 1b) Create Case form: Petitions clerk does not see deficiency statistics for paper petition before case creation when case type is not Deficiency
* Scenario 1a
* Select case type = any other besides Deficiency 
Expected results 
- [ ] Statistics Proposed by IRS displays 
- [ ] Year/Period field is hidden 
- [ ] Deficiency field is hidden
- [ ] Total penalties field is hidden

#### Scenario 2) Create Case form: Petitions clerk enters Deficiency amount 
* Scenario 1a
* Enter Deficiency = 5000.67
Expected results 
- [ ] Deficiency field displays as formatted $5000.67

#### Scenario 3) Create Case form: Petitions clerk can enter total penalty manually
* Scenario 1a
* Enter Total penalties = $450.80
Expected results 
- [ ] Total penalties field displays as formatted $450.80

#### Scenario 4a) Create Case form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 1a 
* Click Calculate penalties 
* Enter Penalty 1 = 100.00
* Enter Penalty 2 = 50.50
* Click Calculate 
Expected results 
On click of Calculate penalties link
- [ ] Calculate Penalties modal display

On click of Calculate from modal
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $150.50

#### Scenario 4b) Create Case form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 1a 
* Click Calculate penalties 
* Enter Penalty 1-5 = 100.00
* Click Add Another Penalty 
* Enter Penalty 6 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 7 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 8 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 9 = 100.00 
Expected results 
On click of Add Another Penalty 
- [ ] Next sequential Penalty field displays 

#### Scenario 4c) Create Case form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 4b
* Click Add Another Penalty 
Expected results 
- [ ] Penalty 10 (IRS) field displays 
- [ ] Add Another Penalty button is hidden 

#### Scenario 5) Create Case form: Petitions clerk sees calculated total penalties on Create case form 
* Scenario 4c 
* Enter Penalty 10 = 100.00
* Click Calculate button 
Expected results 
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $1,000

#### Scenario 6) Create Case form: If petitions clerk enters manual entry of total penalties and then calculates penalties, the calculated total displays on Create case form 
* Scenario 1a
* Enter total penalties = 450.99
* Click Calculate penalties 
* Enter Penalty 1 = 450.99
* Enter Penalty 2 = 100.00 
* Click Calculate button 
Expected results 
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $550.99

#### Scenario 7) Create Case form: Petitions clerk can manually edit a calculated penalty total 
* Scenario 5
* Enter Total Penalties = 2200.88
Expected results 
- [ ] Total penalties field is editable 
- [ ] Total penalties displays as formatted $2,200.88

#### Scenario 8) Create Case form: Petitions clerk adds up to 12 years/periods of deficiency statistics before case creation 
* Scenario 1a
* Enter year = 2010
* Enter deficiency = 4000
* Enter Total penalties = 550.77
* Click Add Another Year/Period  (up to 11 times) 
Expected results 
- [ ] On click of Add Another Year, a new set of Statistics fields (Year/Period, Deficiency, Total penalties) displays
- [ ] After 12 year/periods are visible, Add Another Year/Period button is hidden 

#### Scenario 9) Create Case form: Petitions clerk views entered deficiency stats on Review Your Petition screen 
* Scenario 8 
* Enter 2nd year = 2011
* Enter 2nd Deficiency = 10000
* Enter 2nd Total penalties = 660.99
* Click Create Case 
Expected results 
- [ ] Case is created and app navigates to Review Your Petition screen 
- [ ] IRS Notice tab displays 
    - [ ] Year/ Term = 2010 
        * deficiency = $4,000.00
        * Total penalties = $550.77
    - [ ] Year/ Term = 2011 
        * deficiency = $10,000.00
        * Total penalties = $660.99

### Petition QC (Paper and Electronic)
#### Scenario 10) Petition QC form: Petitions clerk adds deficiency statistics during QC when case type is Deficiency 
* Login as petitions clerk 
* Navigate to Section Document QC > Inbox 
* Select Petition
* Navigate to IRS Notice  
* Select case type = Deficiency
Expected results 
- [ ] Statistics Proposed by IRS displays 
- [ ] Year/Period field displays as optional
- [ ] Deficiency field displays as optional 
- [ ] Total penalties field displays as optional 

#### Scenario 11) Petition QC form: Petitions clerk does not see deficiency statistics for paper petition before case creation when case type is not Deficiency
* Scenario 10a
* Select case type = any other besides Deficiency 
Expected results 
- [ ] Statistics Proposed by IRS displays 
- [ ] Year/Period field is hidden 
- [ ] Deficiency field is hidden
- [ ] Total penalties field is hidden

#### Scenario 12) Petition QC form: Petitions clerk can enter deficiency amount
* Scenario 1a
* Enter Deficiency = 5000.67
Expected results 
- [ ] Deficiency field displays as formatted $5000.67

#### Scenario 13) Petition QC form: Petitions clerk can enter total penalty manually
* Scenario 10
* Enter Total penalties = $450.80
Expected results 
- [ ] Total penalties field displays as formatted $450.80

#### Scenario 14a) Petition QC form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 10 
* Click Calculate penalties 
* Enter Penalty 1 = 100.00
* Enter Penalty 2 = 50.50
* Click Calculate 
Expected results 
On click of Calculate penalties link
- [ ] Calculate Penalties modal display

On click of Calculate from modal
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $150.50

#### Scenario 4b) Petition QC form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 10
* Click Calculate penalties 
* Enter Penalty 1-5 = 100.00
* Click Add Another Penalty 
* Enter Penalty 6 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 7 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 8 = 100.00 
* Click Add Another Penalty 
* Enter Penalty 9 = 100.00 
Expected results 
On click of Add Another Penalty 
- [ ] Next sequential Penalty field displays 

#### Scenario 4c) Petition QC form: Petitions clerk can enter up to 10 penalties and calculate total 
* Scenario 14b
* Click Add Another Penalty 
Expected results 
- [ ] Penalty 10 (IRS) field displays 
- [ ] Add Another Penalty button is hidden 

#### Scenario 15) Petition QC form: Petitions clerk sees calculated total penalties on form 
* Scenario 14c 
* Enter Penalty 10 = 100.00
* Click Calculate button 
Expected results 
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $1,000

#### Scenario 16) Petition QC form: If petitions clerk enters manual entry of total penalties and then calculates penalties, the calculated total displays on form 
* Scenario 10
* Enter total penalties = 450.99
* Click Calculate penalties 
* Enter Penalty 1 = 450.99
* Enter Penalty 2 = 100.00 
* Click Calculate button 
Expected results 
- [ ] Modal closes 
- [ ] Total penalties displays as formatted $550.99

#### Scenario 17) Petition QC form: Petitions clerk can manually edit a calculated penalty total 
* Scenario 16
* Enter Total Penalties = 2200.88
Expected results 
- [ ] Total penalties field is editable 
- [ ] Total penalties displays as formatted $2,200.88


#### Scenario 18) Petition QC form: Petitions clerk adds up to 12 years/periods of deficiency statistics before case creation 
* Scenario 10
* Enter year = 2010
* Enter deficiency = 4000
* Enter Total penalties = 550.77
* Click Add Another Year/Period  (up to 11 times) 
Expected results 
- [ ] On click of Add Another Year, a new set of Statistics fields (Year/Period, Deficiency, Total penalties) displays
- [ ] After 12 year/periods are visible, Add Another Year/Period button is hidden 

#### Scenario 19) Petition QC form: Petitions clerk views entered deficiency stats on Review Your Petition screen 
* Scenario 18 
* Enter 2nd year = 2011
* Enter 2nd Deficiency = 10000
* Enter 2nd Total penalties = 660.99
* Click Review Petition 
Expected results 
- [ ] App navigates to Review Your Petition screen 
- [ ] IRS Notice tab displays 
    - [ ] Year/ Term = 2010 
        * deficiency = $4,000.00
        * Total penalties = $550.77
    - [ ] Year/ Term = 2011 
        * deficiency = $10,000.00
        * Total penalties = $660.99

#### Scenario 20) Petition QC form: Petitions clerk enters deficiency stats during QC, reviews Petition and updates stats 
* Scenario 19 
* Click Edit on IRS Notice card 
* Update 2nd Deficiency = 12000
* Update 2nd Total penalties = 700.00
* Click Review Petition 
Expected results 
- [ ] App navigates to Review Your Petition screen 
- [ ] IRS Notice tab displays 
    - [ ] Year/ Term = 2010 
        * deficiency = $4,000.00
        * Total penalties = $550.77
    - [ ] Year/ Term = 2010
        * deficiency = $12,000.00
        * Total penalties = $700.00

**Comment by klohman** [comment]
#4657 UX Review 

* Year field - should be limited to 4 characters and only accept numeric values

* Calculate penalties modal - do we always anchor back to top of page when closing a modal? It’s jarring here since the fields are farther down the screen- may need to reconsider ? 

* Radio set -  fields are not clearing when you select a different option for year/period; year, last date of period, deficiency and total penalties should clear when a different selection is made

* Errors are being triggered when visible fields are blank (I think it’s related to the data not clearing in the year/period fields when you select a different option) 

* When one field of the “Statistics” set is blank and triggers error, it’s only displaying the page level error and nothing at the field level. 
    * Use same error message as first statistics set for this situation: “Enter year, deficiency amount, and total penalties” for both page level and field level- the use of “Statistics #1” in page level message is good
