### ISSUE TITLE
Petitions Clerk: Revamp - QC E-Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4668]
As a Petitions Clerk, so that I may review and edit an electronically filed petition, I need the petition workflow revamped to accommodate my needs. 

## Acceptance Criteria
* Make sure all Petition links direct to the right places 
* E-filed petition and associated documents receive coversheet when filed
* Petition clerk can copy address and phone for petitioner and spouse 
* Petition clerk views documents uploaded with Petition in tabbed view 
* Any court user should be able to view paper-filed and e-filed Petitions (and associated documents) when case status = NEW 
* Petition clerk can review petition details during QC (Review Your Petition screen) 
* Once they click “Review Petition” - QC’d petition should go into In Progress tab 
* Petitions clerk can edit after Reviewing 
* Need to update Petition QC "Orders Needed" to "Orders/Notices Needed" - change on form and review screen
* See other notes below - do we need?
* Make sure that the Petitions Clerk can enter case statistics during the QC process (same logic as paper petition should apply -- required if Deficiency and "yes" to notice)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Per Jessica (5/18/20) - e-filed petitions receive coversheet when filed; on serve, they receive served date applied to original coversheet (not a duplicate coversheet) 
* if there are changes to the docket number suffix or case caption for e-filed petitions during QC, a minute entry noting the change is added to the docket record when served (in second story)

## Tasks
- [x] 1 Update petition links (see story comment) (Rachael #5340)
- [x] 2 Update Orders Needed titles to Orders/Notices Needed (Cody #5339)
- [x] 3 Case Info tab of petition QC screen updates (see story comment) (Cody #5339)
- [x] 4 Make sure document tabs work on petition qc for e-filed petitions (Cody)
- [x] 5 Verify that petition is removed from document qc inbox and moved to In Progress when Review Petition is clicked (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
Electronic Petition Flow

#### Scenario 1- Petitions clerk can access a new e-filed petition
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
Expected result
- [ ] app navigates to QC (edit) screen 

#### Scenario 2-Petition clerk can copy primary contact info to secondary (if relevant)
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Change the petitioner type to petitioner and spouse/ deceased spouse
6. Reenter the petitioner info
7. Check the box to copy the primary address and phone
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ]  Verify the primary address and phone number are copied to the secondary
- [ ] Verify edits can be made to secondary phone or address and do NOT update the primary
- [ ] Verify if edits made to primary address or phone number update the secondary 
- [ ] Verify after clicking copy box Primary/Secondary contact names do not change

#### Scenario 3- Petition clerk can edit Petitioners name and Case Caption field updates 
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Make a change to the petitioners name
6. Verify that the case caption under the Case info tab displays the petitioners information entered 
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Petitioner information is entered
- [ ] Case caption displays under case information tab
- [ ] Petitioner Name displays in the case caption

#### Scenario 4- Petition clerk can edit caption and sees the contact info is not updated
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Make changes to the case caption
6. Verify that the Contact Name under parties tab does not change
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Petitioner information is entered
- [ ] Case caption displays under case information tab
- [ ] Petitioner Name displays in the case caption
- Paper Petition Flow

 #### Scenario 5- Petition clerk can edit caption and sees the contact info is not updated
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Petitions clerk enters in the petitioners information
5. Verify that the case caption under the Case info tab displays the petitioners information entered
6. Make changes to the case caption
7. Verify that the Contact Name under parties tab does not change
Expected result
- [ ] Verify form displays parties tab as default
- [ ] Petitioner information is entered
- [ ] Case caption displays under case information tab
- [ ] Petitioner Name displays in the case caption
- [ ] Petitioner Name does not change in the parties tab

#### Scenario 6- Petitions Clerk reviews the petition data 
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition
6. Verify Review screen Displays
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays

#### Scenario 7- Petitions Clerk reviews the petition data before submitted to the IRS  
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify Serve to IRS button appears below the tiles
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Serve to IRS button appears below the tiles

 #### Scenario 8- Petitions Clerk reviews the petition data before Saving for Later  
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify Save for Later button appears below the tiles
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Save for Later button appears below the tiles

 #### Scenario 9- Petitions Clerk reviews the petition data and Saves for Later  
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify Save for Later button appears below the tiles
11. Verify all data on the review screen is correct
12. Click Save for later button
13. Verify User is redirected to their My Document QC Inbox
14. Verify Success message displays
15. Click on the in progress tab
16. Verify that the petition that was just entered displays in the In Progress tab of My Document QC and in Section Document QC
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Save for Later button appears below the tiles
- [ ] All data is correct
- [ ] User is redirected to their My Document QC Inbox
- [ ] Success message displays
- [ ] The petition that was just entered displays in the In Progress tab of My Document QC and in Section Document QC


#### Scenario 10- Petitions Clerk reviews the petition data and clicks to edit data
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify all data on the review screen
11. Click on the edit link in the Parties title
12. Verify page is directed to the edit page displaying the Parties Tab
13. Make an edit in the parties tab
14. Click on Review Petition button
15. Verify Review page displays and information just changed is updated
16. Preform step 12-16 for the remaining titles verifying that each redirects to their specific tab, edits are made and verified on the review page after clicking review button
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Page is directed to the edit page displaying the Parties Tab
- [ ] Page is directed to the edit page displaying the Case Information Tab
- [ ] Page is directed to the edit page displaying the IRS Notice Tab
- [ ] Review page displays and information just changed is updated


#### Scenario 11- Petitions Clerk reviews the pdf document displays a modal
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition
6. Verify Review screen Displays
7. Click on one of the document links in the attachments tile
8. Verify each open up a modal and display the document which was uploaded/scanned
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] Each of the documents open up a modal and display the document which was uploaded/scanned

#### Scenario 12- Petitions Clerk review the pdf documents and go back to edit before Saving for Later or Serving to IRS
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition
6. Verify Review screen Displays
7. Click on one of the document links in the attachments tile
8. Verify each open up a modal and display the document which was uploaded
9. Click on the edit link in the Attachments tile
10. In the Upload/Scan Document tabs click delete pdf on the Petition document
11. Verify it is removed
12. Upload/Scan a new petition in
13. Click the Review Petition button
14. Verify Review screen Displays
15. Click on the Petition Document and verify the new petition displays
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] Each of the documents open up a modal and display the document which was uploaded
- [ ] Document is removed
- [ ] Review screen Displays
- [ ] The new petition displays

#### Scenario 13- Orders needed are displayed on review screen (if applicable) 
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. In the Case info tab select at least 1 order needed for the petition
6. Click on Review Petition
7. Verify Review screen Displays
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] Yellow Warning Message displays above the tiles displaying what orders are needed


#### Scenario 14- Petitions clerk can print out review page for later use via browser print functionality 
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. In the Case info tab select at least 1 order needed for the petition
6. Click on Review Petition
7. Verify Review screen Displays
8. From the browser go to File> Print 
9. Verify Print Dialog Displays
10. Verify all information on the page displays in the print preview
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] Yellow Warning Message displays above the tiles displaying what orders are needed
- [ ] Print Dialog Displays
- [ ] All information on the page displays in the print preview

#### Scenario 15 Petition clerk can serve a saved paper petition
1. Login as petitions clerk 
2. Navigate to Document QC In Progress tab 
3. Click into a saved Petition
4. Click “Serve to IRS” 
5. Confirm to Serve on confirmation modal
Expected results 
On select of saved Petition
- [ ] app navigates to Petition Review screen 
On click of Serve to IRS 
- [ ] Serve paper document modal displays with print option 
- [ ] Once serve paper document modal is closed or Back button is clicked from Printable Document page, app navigates to Case Detail > Docket Record with success message displayed 
- [ ] Petition and any associated documents (RQT, APW, ODS) display on docket record as Served with current date and parties displayed as “B”
- [ ] Coversheet is applied to Petition and any associated documents (RQT, APW, ODS) 
- [ ] Petition no long displays in Document QC > In Progress tab 
- [ ] Petition displayed in My Document QC > Served tab and Section Document QC > Served tab
- [ ] Petition clerk’s name who served the petition displays on the Petition Document Detail page and on Section QC Served tab 
 #### Scenario 16 Petitions clerk can save for later a previously saved for later petition
( reword? - Petition clerk can edit a saved petition and save for later again )
1. Login as petitions clerk 
2. Navigate to Document QC In Progress tab 
3. Click into a saved Petition
4. Edit petition metadata 
5. Click Review Petition 
6. Click Save for Later 
7. Navigate to Document QC In Progress tab 
8. Click into the saved petition again
Expected results 
On click of “Save for Later” 
- [ ] App navigates to My Document QC Inbox with success message displayed 
- [ ] Petition remains in My/Section Document QC > In Progress tab 
On click into saved petition after editing 
- [ ] Petition Review screen displayed updated metadata 
 #### Scenario 17 Petitions clerk can serve a paper petition directly to the IRS after entering/reviewing data (create/serve)
1. Login as petitions clerk 
2. Navigate to Document QC and click Create Case 
3. Complete Petition form 
4. Click Review Petition 
5. Click Serve to IRS 
Expected results 
- [ ] Case is created in system and assigned the next sequential docket number 
- [ ] App navigates to Case Detail > Docket Record tab with success message displayed 
- [ ] Petition and any associated documents (RQT, APW, ODS) display on docket record as Served with current date and parties displayed as “B”
- [ ] Coversheet is applied to Petition and any associated documents (RQT, APW, ODS) 
- [ ] Petition is displayed in My Document QC > Served tab and Section Document QC > Served tab
- [ ] Petition clerk’s name who served the petition displays on the Petition Document Detail page and Section Document QC > Served 
 #### Scenario 18 Petitions clerk can review but not edit a served petition
1. Login as petitions clerk 
2. Navigate to Document QC and click Create Case 
3. Complete Petition form 
4. Click Review Petition 
5. Click Serve to IRS 
6. Click on Petition from docket record 
Expected results 
- [ ] App navigates to Petition Document Detail 
- [ ] Petition Detail displays the Petition clerk’s name who served the petition 
- [ ] Petition Detail displays Served date on screen 
- [ ] PDF preview displays Petition with coversheet applied 
- [ ] Petition Detail screen does not include Edit functionality 
- [ ] Petitioner Name does not change in the parties tab

#### Scenario 19- Petitions Clerk reviews a New petitions data 
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Click on Review Petition
6. Verify Review screen Displays
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays

#### Scenario 20- Petitions Clerk reviews  a NEW petition data before submitted to the IRS  
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Review the data provided
6. Click on Review Petition button
7. Verify Review screen displays
8. Verify that the blue header says Create Case
9. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
10. Verify that each tile has an edit link
11. Verify Serve to IRS button appears below the tiles
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Correct Petitioner data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Serve to IRS button appears below the tiles

 #### Scenario 21- Petitions Clerk reviews  a NEW  petition data before Saving for Later  
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Review the data provided
6. Click on Review Petition button
7. Verify Review screen displays
8. Verify that the blue header says Create Case
9. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
10. Verify that each tile has an edit link
11. Verify Save for Later button appears below the tiles
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Correct Petitioner data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Save for Later button appears below the tiles


#### Scenario 22- Petitions Clerk reviews a New petition data and clicks to edit data
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Review the data provided
6. Click on Review Petition button
7. Verify Review screen displays
8. Verify that the blue header says Create Case
9. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
10. Verify that all but the Attachments tile has an edit link
11. Verify all data on the review screen
12. Click on the edit link in the Parties title
13. Verify page is directed to the edit page displaying the Parties Tab
14. Make an edit in the parties tab
15. Click on Review Petition button
16. Verify Review page displays and information just changed is updated
17. Preform step 12-16 for the remaining titles verifying that each redirects to their specific tab, edits are made and verified on the review page after clicking review button
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Correct Petitioner data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Page is directed to the edit page displaying the Parties Tab
- [ ] Page is directed to the edit page displaying the Case Information Tab
- [ ] Page is directed to the edit page displaying the IRS Notice Tab
- [ ] Review page displays and information just changed is updated

#### Scenario 22- Petitions clerk can serve a New petition directly to the IRS after Q/C  
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Review the data provided
6. Click on Review Petition button
7. Verify Review screen displays
8. Click the Serve to IRS button 
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Correct Petitioner data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Serve to IRS button appears below the tiles
- app navigates to Case Detail > Docket Record with success message displayed 
- [ ] Petition and any associated documents (RQT, APW, ODS) display on docket record as Served with current date and parties displayed as “B”
- [ ] Coversheet is applied to Petition and any associated documents (RQT, APW, ODS) 
- [ ] Petition no long displays in Document QC > In Progress tab 
- [ ] Petition displayed in My Document QC > Served tab and Section Document QC > Served tab
- [ ] Petition clerk’s name who served the petition displays on the Petition Document Detail page and on Section QC Served tab

#### Scenario 24- Petition clerk can serve a saved electronic petition
1. Login as petitions clerk 
2. Navigate to Document QC In Progress tab 
3. Click into a saved Petition
4. Click “Serve to IRS” 
5. Confirm to Serve on confirmation modal
Expected results 
On select of saved Petition
- [ ] app navigates to Petition Review screen 
On click of Serve to IRS 
- [ ] app navigates to Case Detail > Docket Record with success message displayed 
- [ ] Petition and any associated documents (RQT, APW, ODS) display on docket record as Served with current date and parties displayed as “B”
- [ ] Coversheet is applied to Petition and any associated documents (RQT, APW, ODS) 
- [ ] Petition no long displays in Document QC > In Progress tab 
- [ ] Petition displayed in My Document QC > Served tab and Section Document QC > Served tab
- [ ] Petition clerk’s name who served the petition displays on the Petition Document Detail page and on Section QC Served tab

**Comment by alsmith1** [comment]
Efile petitions flow Lucid chart
https://www.lucidchart.com/documents/edit/df93421d-299d-4ea9-b96b-948724c58d7a/0_0

**Comment by klohman** [comment]
### Petition QC Updates for E-Filed Documents 

#### Parties tab 
* No changes from Petition QC for paper filed petitions 

#### Case Info 
![Screen Shot 2020-05-22 at 1.07.14 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ff5b20d3-59e6-4016-90c9-aa31c81b52e3)

**Date received**
* if e-filed, date received displays read-only and is populated by date received into system 

**Mailing date**
* If e-filed, mailing date field displays read-only and is populated with "Electronically filed" 

**Trial location** and **Order Designating Place of Trial**
* If e-filed, trial location is displayed read-only and populated with user selection from Petition form 
* Order Designating Place of Trial checkbox is hidden 
![Screen Shot 2020-05-22 at 1.12.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9ed5cdbe-c457-4196-9c2c-55a301fbf106)

#### IRS Notice tab 
* no changes from Petition QC for paper petitions

**Comment by klohman** [comment]
Electronic Petition Flow

#### Scenario 1- Petitions clerk can access a new e-filed petition
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
Expected result
- [ ] app navigates to QC (edit) screen 

#### Scenario 2-Petition clerk can copy primary contact info to secondary (if relevant)
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Change the petitioner type to petitioner and spouse/ deceased spouse
6. Reenter the petitioner info
7. Check the box to copy the primary address and phone
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ]  Verify the primary address and phone number are copied to the secondary
- [ ] Verify edits can be made to secondary phone or address and do NOT update the primary
- [ ] Verify if edits made to primary address or phone number update the secondary 
- [ ] Verify after clicking copy box Primary/Secondary contact names do not change

#### Scenario 3- Petition clerk can edit Petitioners name and Case Caption field updates 
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Make a change to the petitioners name
6. Verify that the case caption under the Case info tab displays the petitioners information entered 
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Petitioner information is entered
- [ ] Case caption displays under case information tab
- [ ] Petitioner Name displays in the case caption

#### Scenario 4- Petition clerk can edit caption and sees the contact info is not updated
1. Log in as a petitions clerk
2. Navigate to My Document QC Inbox
3. Click on a New e-filed petition
4. Verify page directs to QC (edit) screen
5. Make changes to the case caption
6. Verify that the Contact Name under parties tab does not change
Expected result
- [ ] QC (edit) screen displays with parties tab as default
- [ ] Petitioner information is entered
- [ ] Case caption displays under case information tab
- [ ] Petitioner Name displays in the case caption

#### Scenario 5- Petitions Clerk reviews the petition data before submitted to the IRS  
* Log in as a petitions clerk
* Navigate to My Document QC > Inbox
* Click on a new e-filed petition 
* Click on Review Petition button
Expected result
- [ ] App navigates to Review and Serve Petition screen 

#### Scenario 6 - Petitions clerk sees e-filed petition that is not served in their Document QC > In Progress after QC
* Scenario 5 
* Navigate to My Document QC > Inbox 
* Navigate to My Document QC > In Progress
Expected results 
- [ ] After clicking “Review Petition”, e-filed petition is no longer in the Document QC > Inbox 
- [ ] After clicking “Review Petition”, e-filed petition is displayed in the Document QC > in Progress tab 

#### Scenario 7) Petitions clerk sees all documents associated with the e-filed Petition on the Petition QC screen 
* Login as petitioner1 
* Create case for corporation 
* Login as petitions clerk 
* Navigate to petition for corporation case 
* Click on ODS tab 
Expected results 
- [ ] Petition QC screen displays Petition, STIN, ODS, RQT, APW 
- [ ] ODS tab displays PDF preview of uploaded ODS 
- [ ] RQT, APW tabs display blank state message : “No document added” 

#### Scenario 8a) Petitions clerk can review e-filed petition and edit before petition is served 
* Scenario 5 
* Click “Edit” link on Parties tab 
* Update petitioner phone number 
* Click Review Petition button 
Expected results 
- [ ] On click of Edit, app navigates to Petition QC form > Parties tab 
- [ ] On click of Review Petition, app navigates to Review and Serve Petition screen with updated phone number displayed 

#### Scenario 8b) Petitions clerk can review e-filed petition and edit before petition is served 
* Scenario 5 
* Click “Edit” link on IRS tab 
* Update IRS Notice type to “CDP” 
* Click Review Petition button 
Expected results 
- [ ] On click of Edit, app navigates to Petition QC form > IRS notice tab 
- [ ] On click of Review Petition, app navigates to Review and Serve Petition screen with updated case type = CDP displayed

#### Scenario 8c) Petitions clerk can review e-filed petition and edit before petition is served 
* Scenario 5 
* Click “Edit” link on Case Info tab 
* Update case procedure from Regular to Small
* Click Review Petition button 
Expected results 
- [ ] On click of Edit, app navigates to Petition QC form > Case Info tab 
- [ ] On click of Review Petition, app navigates to Review and Serve Petition screen with updated case procedure = Small displayed
- [ ] On click of Review Petition, docket number displays “S” suffix  

#### Scenario 9) Internal users view Petition document when case status = New 
* Login as petitioner1 
* Create case 
* Login as petition clerk
* Navigate to Case detail > Docket Record 
* Click on Petition 
* Login as admissions clerk 
* Navigate to Case detail > Docket Record 
* Click on Petition 
Expected results 
- [ ] Petition document is hyperlinked from Docket Record 
- [ ] Petition link on Docket Record navigates to Petition Document Detail screen 

#### Scenario 10) Petitions clerk navigates to Petition QC form from Document QC > Inbox 
* Scenario 9 
* Login as petitions clerk 
* Navigate to Document QC > Inbox 
* Click on Petition link  
Expected results 
- [ ] App navigates to Petition QC form > Parties tab 

#### Scenario 11) Petitions clerk navigates to Review and Serve Petition from Document QC > In Progress 
* Scenario 9 
* Login as petitions clerk 
* Navigate to Document QC > Inbox 
* Click on Petition link  
* Click Review Petition 
* Navigate to Document QC> In Progress 
* Click on. Petition link
Expected results 
- [ ] App navigates to Review and Serve Petition screen 


#### Scenario 12) Petitions clerk sees Date received as read-only for e-filed petitions 
* Scenario 9
* Navigate to Petition QC> Case Info 
Expected results 
- [ ] Date received displays as read-only 

#### Scenario 13) Petitions clerk sees Mailing date as read-only for e-filed petitions 
* Scenario 9
* Navigate to Petition QC> Case Info 
Expected results 
- [ ] Mailing displays “Electronically filed” as read-only 

#### Scenario 14) Petitions clerk sees Trial location as read-only for e-filed petitions Scenario 9
* Navigate to Petition QC> Case Info 
Expected results 
- [ ] Trial location displays selected trial location as read-only
