### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *CREATE CASE & REVIEW* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4758]
As a Petitions Clerk, so that I can ensure the data I'm entering into the system is correct, I need the ability to review all of that data I entered to create a paper petition in the system. 

## Acceptance Criteria
* Petitions clerk can create a case from a paper petition
* Petitions clerk can review "at a glance" all of the data entered into the create a petition form
* Petitions clerk can access the documents they uploaded to the form

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* need to update STIN PDF upload to an optional field 

## Tasks
- [x] 1 Update create paper case form (Rachael #5085) 
  - [x] 1a Make STIN upload optional (Rachael #5085) 
  - [x] 1b Update submit button text to “Create Case” (Rachael #5085) 
- [x] 2 Update Create Case button to submit the actual case instead of just going to the review page (Rachael #5087)
- [x] 3 Update review page to pull data from caseDetail instead of the form (Cody)
- [x] 4 Update review page header to use case detail header
- [x] 5 Case should appear in Petitions Section Document QC > In Progress tab after case is created
- [x] 6 Verify that all data displayed on the review petition screen is correct (see story comments)
- [x] 7 Update Attachments section of review screen; STIN should not be viewable (Cody)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Review the Petition - Pull in the Petition Data
Review the Petition - User Can View PDFs (Remove and Re-Add)

**Comment by alsmith1** [comment]
Draft Test Scenarios

### Reviewing New Petition - Parties

[Create Case] steps 
Login as petition clerk 
Navigate to Document QC 
Click Create Case 
Submit form after filling out required fields
Review Petition Page loads
Verify page header says Create Case
Verify page displays a warning banner for orders if any have been marked in the form entry as needed
Verify 4 tiles display:
Parties
Case Info
IRS Notice
Documents
Verify each tile has an edit link
Verify buttons at the bottom of the page display
Serve to IRS
Save for Later
Cancel
#### 1) Review of Petitioner and Spouse petition 
Navigate to Case Info tab 
Select “Petitioner and Spouse” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify party type is listed as petitioner and spouse and displays in the first column
Verify Petitioner contact information displays in the second column
Verify contact information lists any entered field including required fields
Name
Mailing address 1
City
State
Zip
Verify Spouse contact information displays in the third column
Verify contact information lists any entered field including required fields
Name
Mailing address 1
City
State
Zip
Expected results 
[ ] Entered values are validated for format on submit (Review Petition)
[ ] Page Navigates to the Review Petition Screen
[ ] Page Displays with values entered in form
[ ]  Party type is listed in the first column as petitioner and spouse
[ ]  Petitioner contact information is listed in second column and displays all info entered in form along with required fields:
Name
Mailing address 1
City
State
Zip
[ ]  Spouse contact information is listed in third column and displays all info entered in form along with required fields:
Name
Mailing address 1
City
State
Zip
#### 2) Review of Corporation petition 
Navigate to Case Info tab 
Select “Corporation” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify party type is listed as corporation and displays in the first column
Verify Petitioner contact information displays in the second column
Verify contact information lists any entered field including required fields
Business Name
In Care of
Mailing address 1
City
State
Zip
Verify no information displays in third column
Expected results 
[ ] Entered values are validated for format on submit (Review Petition)
[ ] Page Navigates to the Review Petition Screen
[ ] Page Displays with values entered in form
[ ]  Party type is listed in the first column as corporation
[ ]  Petitioner contact information is listed in second column and displays all info entered in form along with required fields:
Business Name
In Care of
Mailing address 1
City
State
Zip
[ ]  no spouse information is displayed in the third column
#### 3) Review of Petitioner petition 
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify party type is listed as Petitioner and displays in the first column
Verify Petitioner contact information displays in the second column
Verify contact information lists any entered field including required fields
Name
Mailing address 1
City
State
Zip
Verify no information displays in third column
Expected results 
[ ] Entered values are validated for format on submit (Review Petition)
[ ] Page Navigates to the Review Petition Screen
[ ] Page Displays with values entered in form
[ ]  Party type is listed in the first column as Petitioner
[ ]  Petitioner contact information is listed in second column and displays all info entered in form along with required fields:
Name
Mailing address 1
City
State
Zip
[ ]  no spouse information is displayed in the third column
[ ]  no spouse information is displayed in the third column
#### 3) Review of Trust petition 
Navigate to Case Info tab 
Select “Trust” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify party type is listed as Trustee and displays in the first column
Verify Petitioner contact information displays in the second column
Verify contact information lists any entered field including required fields
Name of trust
Name of trustee
Mailing address 1
City
State
Zip
Verify no information displays in third column
Expected results 
[ ] Entered values are validated for format on submit (Review Petition)
[ ] Page Navigates to the Review Petition Screen
[ ] Page Displays with values entered in form
[ ]  Party type is listed in the first column as Trustee
[ ]  Petitioner contact information is listed in second column and displays all info entered in form along with required fields:
Name of trust
Name of trustee
Mailing address 1
City
State
Zip
[ ]  no spouse information is displayed in the third column





### Review New Petition - Case Info 
#### 1) User sees entered Date received on Review screen 
Navigate to Case Info tab
Enter 03/01/2020 as Date received 
Complete form
Click Review Petition 
Expected results 
[ ] Date received displays as 03/01/20
#### 2) Users sees entered Mailing date on Review screen 
Navigate to Case Info tab
Enter “Hand-delivered 03/01/2020” as Mailing date
Complete form
Click Review Petition
Expected results 
[ ] Mailing date displays as  “Hand-delivered 03/01/2020”
#### 3) User sees system-generated case caption on Review screen 
Navigate to Parties tab 
Enter party information 
Navigate to Case Info tab 
Complete form
Click Review Petition
Expected results 
[ ] On Case Info tab, entered party information displays in system-generated case caption 
[ ] System-generated case caption displays under Case caption on Review screen 

#### 4) User sees edited system-generated case caption on Review screen 
Navigate to Parties tab 
Enter party information 
Navigate to Case Info tab
Edit system-generated case caption 
Complete form
Click Review Petition
Expected results 
[ ] Edited system-generated case caption displays in Case caption field on Case Info tab 
[ ] Edited system-generated case caption displays under Case caption field on Review screen
#### 5) User sees selected Trial location as Requested trial location on Review screen 
Navigate to Case Info tab 
Select Case Procedure (Regular or Small)
Select Trial location from dropdown 
Upload RQT PDF 
Complete form
Click Review Petition 
Expected results 
[  ] Selected Trial location displayed under Requested trial location on Review screen

#### 6) User sees blank state for Requested trial location when no trial location is selected 
Navigate to Case Info tab
Select Case Procedure 
Leave Trial location empty 
Do not upload RQT PDF
Complete form
Click Review Petition 
Expected results 
[  ] “No requested place of trial” is displayed under Requested trial location on Review screen

#### 7) User sees Case procedure on Review screen 
Navigate to Case Info tab
Select Case Procedure 
Complete form
Click Review Petition 
Expected results 
[ ] Selected case procedure is displayed under Case Procedure on Review screen

#### 8) User sees “Paid” info selected under Filing fee on Review screen 
Navigate to Case Info 
Select “Paid”
Enter 03/13/20 in Payment date field 
Enter check in Payment method field 
 Complete form
Click Review Petition
Expected results 
[ ] Filing fee field on Review screen displays “Paid 03/13/20 check” 

#### 9) User sees “Waived” info selected under Filing fee on Review screen 
Navigate to Case Info 
Select “Waived”
Enter 03/10/20 in Payment date field 
Complete form
Click Review Petition
Expected results 
[ ] Filing fee field on Review screen displays “Waived 03/10/20” 
#### 10) User sees “Not paid” info selected under Filing fee on Review screen 
Navigate to Case Info 
Select “Not paid”
Complete form
Click Review Petition
Expected results 
[ ] Filing fee field on Review screen displays “Not paid” 

#### 11) User sees all orders checked under Orders Needed on Review screen 
Navigate to Parties tab
Select Corporation as party type 
Check Order for Ownership Disclosure Statement 
Navigate to Case Info tab 
Check Order to Show Cause 
Leave Order Designating Place of Trial checked 
Select “Not Paid” for Fee Paid field 
Leave ORder for Filing Fee checked 
Check each order under Orders Needed 
Complete form 
Click Review Petition
Expected results 
[ ] Orders Needed alert message displays 
[ ] Order for Ownership Disclosure Statement is listed in alert
[ ] Order to Show Cause is listed in alert 
[ ] Order Designating Place of Trial is listed in alert 
[ ] Order for Filing Fee is listed in alert 
[ ] Order for Ratification of Petition is listed in alert 
[ ] Notice of Attachments in the Nature of Evidence is listed in alert 
[ ] Order for Amended Petition is listed in alert 
[ ] Order for Amended Petition and Filing Fee is listed in alert 

#### 12) User does not see Orders Needed alert message if no orders are selected 
Create Case 
Uncheck/leave unchecked any Orders needed 
Complete form 
Click Review Petition 
Expected results 
[ ] Orders Needed alert message does not display on Review screen



### Review New Petition: IRS Notice 

#### 1) User sees “No” displayed under Notice attached to petition field when No was selected on IRS Notice tab
Click Create Case 
Navigate to IRS Notice tab 
Select “No” for Notice attached to petition field 
Complete form 
Click Review Petition
Expected results 
[ ] “No” is displayed under “Notice attached to petition” on Review screen 

#### 2) User sees “Yes” displayed under Notice attached to petition field when No was selected on IRS Notice tab
Click Create Case 
Navigate to IRS Notice tab 
Select “Yes” for Notice attached to petition field 
Complete form 
Click Review Petition
Expected results 
[ ] “Yes” is displayed under “Notice attached to petition” on Review screen 

#### 3) User sees Date of notice displayed on Review screen when “Yes” is selected for Notice attached to petition field 
Scenario 2
Enter 03/02/2020 under Date of notice field 
Complete form 
Click Review Petition
Expected results 
[ ] “Yes” is displayed under “Notice attached to petition” on Review screen 
[ ] Date of notice displays as “03/02/20” on Review screen 

#### 4) User does not see Date of notice displayed on Review screen when “Yes” is selected for Notice attached to petition field 
Scenario 1
Complete form 
Click Review Petition
Expected results 
[ ] “No” is displayed under “Notice attached to petition” on Review screen 
[ ] Date of notice is hidden on Review screen

#### 4) User sees selected Case type displayed on Review screen
Create Case 
Navigate to IRS Notice tab 
Select case type 
Complete form 
Click Review Petition 
Expected results 
[ ] Selected case type displays under Case type on Review screen 


Reviewing New Petition - Documents

Create Case] steps 
Login as petition clerk 
Navigate to Document QC 
Click Create Case 
Submit form after filling out required fields
Review Petition Page loads
Verify page header says Create Case
Verify page displays a warning banner for orders if any have been marked in the form entry as needed
Verify 4 tiles display:
Parties
Case Info
IRS Notice
Documents
Verify each tile has an edit link
Verify buttons at the bottom of the page display
Serve to IRS
Save for Later
Cancel 
#### 1) Review the Documents Tile
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that all documents that were uploaded in the entry process are listed as a link with a descriptive header above the link in the tile
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] Each document is a link which opens a modal/pdf preview of the document being submitted with the petition









#### 2) Review the Documents Tile- Petition Document (required document)
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that there is a petition PDF link with a descriptive header labeling the pdf in the tile
Verify when clicking on the petition PDF a modal displays with a preview of the Petition PDF
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] Petition PDF displays as a link which opens a modal/pdf preview of the document being submitted
#### 2) Review the Documents Tile- STIN Document
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the stin document was scanned/uploaded in the form the STIN PDF link with a descriptive header labeling the pdf in the tile
STIN PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the STIN document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 3) Review the Documents Tile- RQT document
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the RQT document was scanned/uploaded in the form the RQT PDF link with a descriptive header labeling the pdf in the tile
RQT PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the RQT document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 4) Review the Documents Tile- ODS document
Navigate to Case Info tab 
Select “Corporation” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the ODS document was scanned/uploaded in the form the ODS PDF link with a descriptive header labeling the pdf in the tile
ODS PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the ODS document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 5) Upload a APW (optional)
Navigate to Case Info tab 
Select “petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the APW document was scanned/uploaded in the form the APW PDF link with a descriptive header labeling the pdf in the tile
APW PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the APW document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### Scenario 1- Petitions clerk can print out review page for later use via browser print functionality 
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. In the Case info tab select at least 1 order needed for the petition
6. Click on Review Petition
7. Verify Review screen Displays
8. From the browser go to File> Print 
9. Verify Print Dialog Displays
10. Verify all information on the page displays in the print preview
Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] Yellow Warning Message displays above the tiles displaying what orders are needed
- [ ] Print Dialog Displays
- [ ] All information on the page displays in the print preview

**Comment by klohman** [comment]
**On click of Review Petition button**
* Navigate to Review the Petition screen 

### Review the Petition screen
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0b6a6fd4-36c7-4e0b-8362-11e98dcf3216)

**Orders Needed**
* Displays list of all Orders checked on Petition form 
* List orders alphabetically 

**Party type**
* Displays selected party type 

**Petitioner contact information**
Displays 
* Primary contact name 
* Primary contact mailing address line 1 
* Primary contact Address line 2
* Primary contact Address line 3
* Primary contact City, State, Zip code 
* Primary contact phone number 

**Spouse's contact information**
* Displays only when Party type =- Petitioner & Spouse or Petitioner & Deceased Spouse 
* Displays 
* Secondary contact name 
* Secondary contact mailing address line 1 
* Secondary contact Address line 2
* Secondary contact Address line 3
* Secondary contact City, State, Zip code 
* Secondary contact phone number 

**[Parties] Edit link**
* on click, navigate to Petition form, Parties tab selected 

**Date received**
* Displays date received entered 

**Mailing date**
* Displays Mailing date entered 

**Case caption**
* Displays caseTitle entity 

**Case procedure**
* Displays selected case procedure 

**Trial location**
* Displays selected trial location

**Filing fee**
* If "Not Paid" selected, display "Not paid" 
* If "Paid" selected, display "Paid [payment date] [payment method]
* If Waived selected, display "Waived [date waived]

**[Case Information] Edit link**
* on click, navigate to Petition form > Case Info tab selected 

**Notice attached to Petition**
* Display selected option (yes, no) 

**Date of Notice**
* If Yes selected for Notice attached, display entered date of notice 
* If Yes selected for Notice attached, display "Not provided" 

**[IRS Notice] Edit link**
* on click, navigate to Petition form > IRS Notice selected 

**Attachments**
* Displays all uploaded documents 
* On click of PDF link, open PDF viewer modal 
![Screen Shot 2020-04-16 at 12.22.09 PM.png]
(https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4d451f37-a525-44f7-8e8a-48aa4f32f5d5)

**"Attachments" Edit link**
* on click, navigate to Petition form with default tab selected 

**Serve to IRS button**
On click, confirmation modal displays

**On click of Yes, Serve**
* Case is created in system 
* All attached documents are entered onto Docket Record 
* All attached documents are served to IRS - electronic email to IRS Super User 
* If no parties require paper service, modal closes, and app navigates to Case Detail > Docket record with success message displayed "Petition served to IRS."
* If parties require paper service, app navigates to Case Detail > Docket record with success message displayed "Petition served to IRS." with Paper Service modal displayed.

**Paper service modal**
* On click of Print Now button, navigate to Print Paper Service documents screen 
* On click of 
https://github.com/flexion/ef-cms/blob/develop/docs/entities/Case.md

**On click of Save for Later**
* App navigates to My Document QC > Inbox with success message displayed : "Petition saved for later service."
* Case is created 
* All documents are entered onto the docket record without service information 
* Petition displays in My Document QC > In Progress and Petition Section Document QC > In Progress

**Comment by klohman** [comment]
### 4758 Test Scenarios 

* Login as petitionsclerk1
* Navigate to Document QC 
* Click Create Case 

#### 1) User reviews entered petition data from Parties tab for [petitioner] 
* Select “Petitioner” party type from dropdown menu 
* Enter Petition name = John Woods 
* Enter petitioner address = 123 Main St, Baltimore, MD 21224
* Enter phone number 333-388-3333
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Party type displays as “Petitioner”
- [ ] Petitioner contact information displays as 
    * John Woods
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333
* [ ] Spouse’s contact information is hidden 

#### 2) User reviews entered petition data from Parties tab for [petitioner & Spouse] 
* Select “Petitioner & spouse” party type from dropdown menu 
* Enter Petition name = John Woods 
* Enter petitioner address = 123 Main St, Baltimore, MD 21224
* Enter phone number 333-388-3333
* Enter spouse’s name = Betty Woods 
* Check “Use same address & phone number as above” checkbox
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Party type displays as “Petitioner & Spouse”
- [ ] Petitioner contact information displays as 
    * John Woods
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333
- [ ] Spouse contact information displays as 
    * Betty Woods
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333

#### 3) User reviews entered petition data from Parties tab for [petitioner & deceased Spouse] 
* Select “Petitioner & deceased spouse” party type from dropdown menu 
* Enter Petition name = John Woods 
* Enter petitioner address = 123 Main St, Baltimore, MD 21224
* Enter phone number 333-388-3333
* Enter spouse’s name = Betty Woods 
* Enter In Care of = John Woods 
* Check “Use same address & phone number as above” checkbox
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Party type displays as “Petitioner & Spouse”
- [ ] Petitioner contact information displays as 
    * John Woods
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333
- [ ] Spouse contact information displays as 
    * Betty Woods
    * c/o John Woods
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333

#### 4) User reviews entered petition data from Parties tab for [estate without executor…] 
* Select “Estate without an executor…” party type from dropdown menu 
* Enter Name of decedent = Damon Salvatore 
* Enter In Care of name = Stephan Salvatore
* Enter petitioner address = 123 Main St, Baltimore, MD 21224
* Enter phone number 333-388-3333
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Party type displays as “Estate without an executor….”
- [ ] Petitioner contact information displays as 
    * Damon Salvatore 
    * c/o Stephan Salvatore
    * 123 Main St
    * Baltimore, MD 21224
    * 333-388-3333
- [ ] Spouse contact information is hidden 


#### 5) User reviews entered petition data from Case Information tab with filing fee “Not paid” 
* Scenario 4
* Navigate to Case Information tab
* Enter Date received = 04/16/2020 
* Enter Mailing date = Hand Delivered 
* Enter case procedure = Regular 
* Select trial location = Washington, DC
* Select “Not Paid” for Filing fee field 
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Date received displays 04/16/20
- [ ] Case caption displays “Estate of Damon Salvatore, Deceased, Petitioner”
- [ ] Mailing date displays “Hand Delivered”
- [ ] Case procedure displays “Regular”
- [ ] Requested trial  Location displays “Washington, DC”
- [ ] Filing fee displays “Not Paid”

#### 5) User reviews entered petition data from Case Information tab with filing fee “Paid” 
* Scenario 2
* Navigate to Case Information tab
* Enter Date received = 04/16/2020 
* Enter Mailing date = Hand Delivered 
* Enter case procedure = Small 
* Select trial location = Birmingham, AL
* Select “Paid” for Filing fee field 
* Enter Payment date = 04/16/2020
* Enter Payment method = check
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Date received displays 04/16/20
- [ ] Case caption displays “John Woods & Betty Woods, Petitioner”
- [ ] Mailing date displays “Hand Delivered”
- [ ] Case procedure displays “Small”
- [ ] Requested trial  Location displays “Birmingham, AL”
- [ ] Filing fee displays “Paid 04/16/20 check” 

#### 6) User reviews entered petition data from Case Information tab with filing fee “Waived” 
* Scenario 1
* Navigate to Case Information tab
* Enter Date received = 04/16/2020 
* Enter Mailing date = Hand Delivered 
* Enter case procedure = Small 
* Select trial location = Birmingham, AL
* Select “Waived” for Filing fee field 
* Enter Date waived = 04/17/2020
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition
Expected results 
- [ ] Date received displays 04/16/20
- [ ] Case caption displays “John Woods, Petitioner”
- [ ] Mailing date displays “Hand Delivered”
- [ ] Case procedure displays “Small”
- [ ] Requested trial  Location displays “Birmingham, AL”
- [ ] Filing fee displays “Waived 04/17/20” 
#### 6) User reviews entered petition data from Case Information tab with no requested place of trial 
* Scenario 1
* Navigate to Case Info 
* Enter Date received = 04/16/2020 
* Enter Mailing date = Hand Delivered 
* Enter case procedure = Small 
* Select trial location = empty
* Select “Waived” for Filing fee field 
* Enter Date waived = 04/17/2020
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition 
Expected results 
- [ ] Date received displays 04/16/20
- [ ] Case caption displays “John Woods, Petitioner”
- [ ] Mailing date displays “Hand Delivered”
- [ ] Case procedure displays “Small”
- [ ] Requested trial  Location displays “No requested place of trial”
- [ ] Filing fee displays “Waived 04/17/20”

#### 7) User reviews entered petition data from IRS Notice tab with notice attached 
* Navigate to IRS Notice tab 
* Select Notice attached = “Yes’ 
* Enter Date of Notice =  01/02/2020
* Enter Type of case = Deficiency 
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition 
Expected results 
- [ ] “Yes” is displayed under “Notice attached to petition” on Review screen 
- [ ] Type of case displays as “Deficiency” 
- [ ] Date of Notice displays as 01/02/20

#### 8) User reviews entered petition data from IRS Notice tab with notice not attached 
* Navigate to IRS Notice tab 
* Select Notice attached = “No’ 
* Enter Type of case = CDP Lien/Levy 
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition 
Expected results 
- [ ] “No” is displayed under “Notice attached to petition” on Review screen 
- [ ] Type of case displays as “CDP Lien/Levy ” 
- [ ] Date of Notice is hidden 

#### 9) User reviews attached Petition and STIN 
* Select “Petitioner” party type from dropdown menu 
* Enter All required fields including upload/scans of all documents submitted
* Upload Petition and STIN PDFs
* Click on Review Petition
 Expected results 
- [ ] Petition is listed in Attachments card with PDF link 
- [ ] STIN is listed in Attachments card with PDF link 

#### 10) User reviews attached Petition, STIN, RQT, ODS and APW 
* Select “Corporation” party type from dropdown menu 
* Enter All required fields including upload/scans of all documents submitted
* Upload Petition, STIN, RQT, ODS, APW PDFs
* Click on Review Petition
 Expected results 
- [ ] Petition is listed in Attachments card with PDF link 
- [ ] STIN is listed in Attachments card with PDF link 
- [ ] RQT is listed in Attachments card with PDF link 
- [ ] ODS is listed in Attachments card with PDF link 
- [ ] APW is listed in Attachments card with PDF link 


#### 11) User views PDF preview for attached PDFs 
* Scenario 10
* Click on Petition PDF link 
* Close PDF Preview modal 
* Click on STIN PDF link 
* Close PDF Preview modal 
* Click on RQT PDF link 
* Close PDF Preview modal 
* Click on ODS PDF link 
* Close PDF Preview modal 
* Click on APW PDF link 
* Close PDF Preview modal 
Expected results 
- [ ] On click of Petition link, PDF preview modal displays with uploaded Petition displayed
- [ ] On click of STIN link, PDF preview modal displays with uploaded STIN displayed
- [ ] On click of RQT link, PDF preview modal displays with uploaded RQT displayed
- [ ] On click of ODS link, PDF preview modal displays with uploaded ODS displayed
- [ ] On click of APW link, PDF preview modal displays with uploaded APW displayed

#### 12) User reviews orders needed from petition form 
* Navigate to Parties tab 
* Select Party type = Corporation 
* Leave Order for Ownership Disclosure Statement checked 
* Navigate to Case Info tab 
* Check Order to Show Cause 
* Select Filing fee = Not Paid 
* Leave Order for Filing Fee checked 
* Leave Order Designating Place of Trial checked
* Check Order for Ratification of Petition
* Check Order for Ratification of Petition
* Check Order for Amended Petition
* Check Order for Amended Petition and Filing Fee
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition 
Expected results 
- [ ] Orders Needed warning message displays 
- [ ] Checked orders display in warning message in alphabetical order 
    - Notice of Attachments in the Nature of Evidence
    - Order for Amended Petition
    - Order for Amended Petition and Filing Fee
    - Order for Filing Fee
    - Order for Ownership Disclosure Statement
    - Order for Ratification of Petition
    - Order Designating Place of Trial
    - Order to Show Cause

#### 13) User does not see orders needed if no orders are selected 
* Navigate to Parties tab 
* Select Party type = Petitioner 
* Navigate to Case Info tab 
* Uncheck Order to Show Cause 
* Select Filing fee = Paid
* Select trial location 
* Enter All required fields including upload/scans of all documents submitted
* Click on Review Petition 
Expected results 
- [ ] Orders Needed warning message does not display
