### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *EDIT In-Progress Petition (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4759]
As a Petitions Clerk, so that I may fix any mistakes I see while reviewing the petition I''m uploading, I need the ability to edit the data from the review page. 

## Acceptance Criteria
From the review page, the Petitions Clerk can:
* Edit the party information
* Edit case information
* Edit IRS notices

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Remove and re-add PDFs (to be implemented in [#4654](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4654) )

## Tasks
- [x] 1 Fix Edit links on petition review screen to navigate to petition qc with specified tab open (Rachael #5101)
- [x] 2 Check petition qc screen for updates (see story comment) (Rachael #5111)
- [x] 3 Update petition QC PDF preview to tabbed view (if no document exists, display “no document added” (Rachael, Matt #5127)
- [x] 4 On click of Petition link from In Progress work queue, navigate to Review Petition screen (Rachael)
- [x] 5 On click of non-petition document links from Review page or docket record, navigate to document detail page with Review & Serve Petition button (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Edit from Review Screen/Parties
Edit from Review Screen/Case Info
Edit from Review Screen/IRS Notice
Edit from Review Screen/Scan PDFs

**Comment by alsmith1** [comment]
Draft Test Scenarios 
### Edit/Re-Review New Petition - Parties

#### 1) Edit/re-Review of Petitioner and Spouse petition 
Follow steps from review new petition-parties
Click on the edit link
Verify when page loads it opens to the parties tab
Update the petitioner’s address
Verify that the Spouse’s address updates
Make a change to the Spouse’s phone number
Verify the Petitioner’s phone number does not change
Click review petition
Verify the updated petitioner contact information displays in the second column of the parties tile
Verify the updated spouse contact information displays in the third column of the parties tile
Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Petitioner’s address is updated, spouse’s address is updated
[ ] Spouse’s phone number is updated, Petitioner’s phone number stays the same
[ ] Page Navigates to the Review Petition Screen
[ ] Petitioner and Spouse's address display new information entered
[ ] Spouse’s phone number is updated but Petitioner’s phone stays same as before
#### 2) Edit/re-Review of Corporation petition 
Follow steps from review new petition-parties
Click on the edit link
Verify when page loads it opens to the parties tab
Make a change to the business name
Add in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (business name and address line 2) displays in the second column of the parties tile
Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Business Name and address line 2 display new information entered

#### 3) Edit/re-Review of Petitioner petition 
Follow steps from review new petition-parties
Click on the edit link
Verify when page loads it opens to the parties tab
Make a change to the city
Sdd in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (Address line 2 and City) displays in the second column of the parties tile
Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Address line 2 and city display new information entered

#### 4) Review of Trust petition 
Follow steps from review new petition-parties
Click on the edit link
Verify when page loads it opens to the parties tab
Make a change to the Name of Trust
Add in Suite 101 in Address line 2
Click review petition
Verify the updated petitioner contact information (Name of trust and address line 2) displays in the second column of the parties tile
Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Name of trust and address line 2 display new information entered
#### 5) Edit/re-Review of Petitioner and Spouse petition to Petitioner
Follow steps from review new petition-parties
Click on the edit link
Verify when page loads it opens to the parties tab
Update the party type to Petitioner
Verify that the Spouse’s information disappears from the form
Add in Suite 101 in Address line 2
Click review petition
Verify Party type is now listed as Petitioner and not Petitioner and Spouse in column 1
Verify the updated (address line 2) petitioner contact information displays in the second column of the parties tile
Verify the third column in the tile does not display, there is no spouse on this case.
Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab
[ ] Page Navigates to the Review Petition Screen
[ ] Party type display’s Petitioner
[ ] Address line 2 display new information entered
[ ] Spouse no longer displays on the review screen

### Edit/Review of New Petition - Case Info 

#### 1) User edits Date received and views updated Review screen
Navigate to Case Info tab
Enter 03/01/2020 as Date received 
Complete form
Click Review Petition 
Click Edit 
Update Date received to 03/02/2020
Click Review Petition
Expected results 
[ ] Date received displays as 03/02/20 on Review screen after edit 
#### 2) User edits Mailing date and view updated Review screen
Navigate to Case Info tab
Enter “Hand-delivered 03/01/2020” as Mailing date
Complete form
Click Review Petition
Click Edit 
Update Mailing date to “Postmarked 03/01/2020”
Click Review Petition
Expected results 
[ ] Mailing date displays as “Postmarked 03/01/20” on Review screen after edit 

#### 3) User edits case caption field and views updated Review screen 
Navigate to Parties tab 
Enter party information 
Navigate to Case Info tab 
Complete form
Click Review Petition
Click Edit 
Update Case caption field directly 
Click Review Petition 
Expected results 
[ ] Case caption on Review screen displays edits made on Case Info tab 

#### 4) User edits party information and views updated case caption on Review screen
Navigate to Parties tab 
Enter party information 
Navigate to Case Info tab 
Complete form
Click Review Petition
Click Edit 
Navigate to Parties tab 
Edit Petitioner name
Click Review Petition 
Expected results 
[ ] Updated petitioner name displays under Petitioner’s Contact info on Review screen 
[ ] Updated petitioner name displays under Case caption on Review screen 
#### 5a) User edits case procedure and views updated Review screen
Navigate to Case Info tab
Select Case Procedure > Regular
Complete form
Click Review Petition 
Click Edit 
Select Case procedure > Small
Click Review Petition
Expected results 
[ ] Case procedure displays as “Small” on Review screen 

#### 5b) User edits case procedure and views updated Review screen
Navigate to Case Info tab
Select Case Procedure > Small
Complete form
Click Review Petition 
Click Edit 
Select Case procedure > Regular
Click Review Petition
Expected results 
[ ] Case procedure displays as “Regular” on Review screen 

#### 6a) User edits Trial location and views updated Review screen 
Navigate to Case Info tab 
Select Case Procedure (Regular or Small)
Select Trial location from dropdown 
Upload RQT PDF 
Complete form
Click Review Petition 
Click Edit 
Select a different Trial location 
Click Review Petition 
Expected results 
[ ] updated Trial location displays under Requested trial location on Review screen
#### 6b) User edits Trial location and views updated Review screen
Navigate to Case Info tab 
Select Case Procedure (Regular or Small)
Select Trial location from dropdown 
Upload RQT PDF 
Complete form
Click Review Petition 
Click Edit 
Remove RQT PDF 
Remove Trial location selection
Click Review Petition 
Expected results 
[ ] Requested place of trial field displays “No requested place of trial” on Review screen 
[ ] Order Designating Place of Trial displays in Orders Needed alert 
#### 7) User edits Filing fee to “Paid” and views updated Review screen 
Navigate to Case Info 
Select “Not paid”
Complete form
Click Review Petition
Click Edit 
Change “Not paid” to “Paid” 
Enter 03/18/20 as Payment date 
Enter “money order” as Payment method 
Click Review Petition 
Expected results 
[ ] Filing fee field displays as “Paid 03/18/20 money order” on Review screen after edit 

#### 8) User edits Filing fee to “Waived” and views updated Review screen 
Navigate to Case Info 
Select “Not paid”
Complete form
Click Review Petition
Click Edit 
Change “Not paid” to “Waived” 
Enter 03/09/20 as Date waived
Click Review Petition
Expected results 
[ ] Filing fee field displays as “Waived 03/09/20” on Review screen after edit 

#### 9) User edits Filing fee to “Not paid” and views updated Review screen 
Navigate to Case Info 
Select “Waived”
Enter 03/10/20 in Payment date field 
Complete form
Click Review Petition
Click Edit 
Change “Waived” to “Not paid” 
Click Review Petition
Expected results 
[ ] Filing fee field displays “Not paid” on Review screen after edit 

#### 10) User edits Orders Needed and views Review screen
Click Create Case 
Check Order for Ratification of Petition
Check Notice of Attachments in the Nature of Evidence 
Check Order for Amended Petition
Check Order for Amended Petition and Filing Fee
Complete form
Click Review Petition
Click Edit 
Navigate to Case Info 
Uncheck Order for Amended Petition
Uncheck Order for Amended Petition and Filing Fee
Click Review Petition 
Expected results 
[ ] Orders Needed alert message displays on Review Screen 
[ ] Order for Ratification of Petition displays in alert 
[ ] Notice of Attachments in the Nature of Evidence displays in alert 
[ ] Order for Amended Petition does not display in alert 
[ ] Order for Amended Petition and Filing Fee does not display in alert 


### Edit/Review of New Petition - IRS Notice 

#### 1) User edits Notice attached to petition from “No” to “Yes” and views updated Review screen
Click Create Case 
Navigate to IRS Notice tab 
Select “No” for Notice attached to petition field 
Complete form 
Click Review Petition
Click Edit 
Change “No” to “Yes” for Notice attached to petition field 
Enter 03/18/2020 for Date of Notice 
Click Review Petition
Expected results 
[ ] Notice attached to petition field displays as “Yes”  on Review screen after edit 
[ ] Date of Notice displays as “03/18/20” on Review screen after edit 


#### 2) User edit Notice attached to petition from “Yes” to No” and views updated Review screen
Click Create Case 
Navigate to IRS Notice tab 
Select “Yes” for Notice attached to petition field 
Enter 03/18/2020 for Date of Notice 
Complete form 
Click Review Petition
Click Edit 
Change “Yes” to “No” for Notice attached to petition field 
Click Review Petition
Expected results 
[ ] Notice attached to petition field displays as “No” on Review screen after edit 
[ ] Date of Notice field is hidden on Review screen after edit 

#### 4) User edits Case type and views updated Review screen 

Create Case 
Navigate to IRS Notice tab 
Select case type 
Complete form 
Click Review Petition 
Click Edit 
Change case type 
Click Review Petition
Expected results 
[ ] Updated case type displays on Review screen after edit 

Edit/Re-Reviewing New Petition - Documents

#### 1) Edit/Re-Review the Documents Tile- Petition Document (required document)
Follow steps from review new petition-documents
Click on the edit link
Verify when page loads it opens with the documents displaying and Petition open
Click the Delete PDF button
Upload a new Petition
Verify the new petition displays in the preview
Click review petition
Verify the link for petition displays in the documents tile
Click on the link and verify the modal opens and displays the newly uploaded Petition PDF
 Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab and documents displaying
[ ] Page Navigates to the Review Petition Screen
[ ] Updated Petitions Document displays in modal
#### 2) Edit/Re-Review the Documents Tile- STIN Document
Follow steps from review new petition-documents
Click on the edit link
Verify when page loads it opens with the documents displaying and Petition open
Click on the STIN tab
Verify the STIN PDF preview (if STIN has not been uploaded skip next step)
Click the Delete PDF button
Upload a new STIN
Verify the new STIN displays in the preview
Click review petition
Verify the link for STIN displays in the documents tile
Click on the link and verify the modal opens and displays the newly uploaded STIN PDF
 Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab and documents displaying
[ ] STIN Document displays if previously uploaded
[ ] STIN document is deleted and freshly uploaded/ STIN document is uploaded
[ ] Page Navigates to the Review Petition Screen
[ ] Updated STIN Document displays in modal



#### 3) Edit/Re-Review the Documents Tile- RQT document
Follow steps from review new petition-documents
Click on the edit link
Verify when page loads it opens with the documents displaying and Petition open
Click on the RQT tab
Verify the RQT PDF preview (if RQT has not been uploaded skip next step)
Click the Delete PDF button
Upload a new RQT
Verify the new RQT displays in the preview
Click review petition
Verify the link for RQT displays in the documents tile
Click on the link and verify the modal opens and displays the newly uploaded RQT PDF
 Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab and documents displaying
[ ] RQT Document displays if previously uploaded
[ ] RQT document is deleted and freshly uploaded/ RQT document is uploaded
[ ] Page Navigates to the Review Petition Screen
[ ] Updated RQT Document displays in modal
#### 4) Edit/re-Review the Documents Tile- ODS document
Follow steps from review new petition-documents
Click on the edit link
Verify when page loads it opens with the documents displaying and Petition open
Click on the ODS tab
Verify the ODS PDF preview (if ODS has not been uploaded skip next step)
Click the Delete PDF button
Upload a new ODS
Verify the new ODS displays in the preview
Click review petition
Verify the link for ODS displays in the documents tile
Click on the link and verify the modal opens and displays the newly uploaded ODS PDF
 Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab and documents displaying
[ ] ODS Document displays if previously uploaded
[ ] ODS document is deleted and freshly uploaded/ ODS document is uploaded
[ ] Page Navigates to the Review Petition Screen
[ ] Updated ODS Document displays in modal

#### 5) Upload a APW (optional)
Follow steps from review new petition-documents
Click on the edit link
Verify when page loads it opens with the documents displaying and Petition open
Click on the AWS tab
Verify the AWS PDF preview (if AWS has not been uploaded skip next step)
Click the Delete PDF button
Upload a new AWS
Verify the new AWS displays in the preview
Click review petition
Verify the link for AWS displays in the documents tile
Click on the link and verify the modal opens and displays the newly uploaded AWS PDF
 Expected results 
[ ] Page Displays with values entered in form
[ ] After click page redirects to the petition form parties tab and documents displaying
[ ] AWS Document displays if previously uploaded
[ ] AWS document is deleted and freshly uploaded/ AWS document is uploaded
[ ] Page Navigates to the Review Petition Screen
[ ] Updated AWS Document displays in modal


Reviewing New Petition - Documents

Create Case] steps 
Login as petition clerk 
Navigate to Document QC 
Click Create Case 
Submit form after filling out required fields
Review Petition Page loads
Verify page header says Create Case
Verify page displays a warning banner for orders if any have been marked in the form entry as needed
Verify 4 tiles display:
Parties
Case Info
IRS Notice
Documents
Verify each tile has an edit link
Verify buttons at the bottom of the page display
Serve to IRS
Save for Later
Cancel 
#### 1) Review the Documents Tile
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that all documents that were uploaded in the entry process are listed as a link with a descriptive header above the link in the tile
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] Each document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 2) Review the Documents Tile- Petition Document (required document)
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that there is a petition PDF link with a descriptive header labeling the pdf in the tile
Verify when clicking on the petition PDF a modal displays with a preview of the Petition PDF
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] Petition PDF displays as a link which opens a modal/pdf preview of the document being submitted
#### 2) Review the Documents Tile- STIN Document
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the stin document was scanned/uploaded in the form the STIN PDF link with a descriptive header labeling the pdf in the tile
STIN PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the STIN document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 3) Review the Documents Tile- RQT document
Navigate to Case Info tab 
Select “Petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the RQT document was scanned/uploaded in the form the RQT PDF link with a descriptive header labeling the pdf in the tile
RQT PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the RQT document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 4) Review the Documents Tile- ODS document
Navigate to Case Info tab 
Select “Corporation” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the ODS document was scanned/uploaded in the form the ODS PDF link with a descriptive header labeling the pdf in the tile
ODS PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the ODS document is a link which opens a modal/pdf preview of the document being submitted with the petition

#### 5) Upload a APW (optional)
Navigate to Case Info tab 
Select “petitioner” party type from dropdown menu 
Enter All required fields including upload/scans of all documents submitted
Click on Review Petition
Verify Documents tile displays
Verify that if the APW document was scanned/uploaded in the form the APW PDF link with a descriptive header labeling the pdf in the tile
APW PDF displays as a link which opens a modal/pdf preview of the document being submitted with the petition
 Expected results 
[ ] Review page displays
[ ] Documents tile displays with all documents scanned/uploaded from form
[ ] the APW document is a link which opens a modal/pdf preview of the document being submitted with the petition
