### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *SAVE for LATER or SERVE* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4760]
Story for paper petition - save for later

## Acceptance Criteria
* Petitions clerk is able to save a new petition to serve at a later time 
* Petitions clerk is able to serve a petition and all associated documents 
* When processing a paper document, cover sheet should not be added until it's served
* Consider how much of #3923 to implement here

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* I have some questions about case creation to discuss before finalizing test scenarios (Kristen)

## Tasks
- [x] 1 Update Save for Later button on Review Petition to navigate to My Document QC -> Inbox with success message displayed (Matt #5139)
- [x] 2 Serve to IRS button - ensure that confirmation modal displays, petition is served, and removed from In Progress queue (read through story comment - most of this is probably already working) (Rachael #5140)
- [x] 3 After serving, navigate to Print Paper Petition Receipt screen (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
- Creates the case
- Route to QC
  - Success message
 - Review the saved petition

**Comment by alsmith1** [comment]
Draft Test Scenarios 

#### Scenario 1- Petitions Clerk reviews the petition data and Saves for Later  (Done)
1. Log in as a petitions clerk
2. Navigate to My Document QC
3. Click on Create a Case
4. Enter the field data and upload/scan all included documents
5. Click on Review Petition button
6. Verify Review screen displays
7. Verify that the blue header says Create Case
8. Verify 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
9. Verify that each tile has an edit link
10. Verify Save for Later, serve to IRS and cancel buttons appear below the tiles
11. Verify all data on the review screen is correct
12. Click Save for later button
13. Verify User is redirected to their My Document QC Inbox
14. Verify Success message displays
15. Click on the in progress tab
16. Verify that the petition that was just entered displays in the In Progress tab of My Document QC and in Section Document QC
17. Verify that docket number and case caption now are assigned to saved for later petition
18. Verify that documents uploaded, besides STIN are on the docket record but not served

Expected result
- [ ] Verify Form displays parties tab as default
- [ ] Petition data is entered into the correct fields
- [ ] Review page displays
- [ ] The blue header says Create Case
- [ ] 4 tiles display (Parties, Case Information, IRS Notice, and Attachments)
- [ ] Each tile has an edit link
- [ ] Save for Later button appears below the tiles
- [ ] All data is correct
- [ ] User is redirected to their My Document QC Inbox
- [ ] Success message displays
- [ ] The petition that was just entered displays in the In Progress tab of My Document QC and in Section Document QC
- [ ] docket number and case caption now are assigned to saved for later petition
- [ ] documents uploaded, besides STIN are on the docket record but not served

#### 2) User accesses a saved petition from the Document QC > In Progress 
Scenario 1 
Navigate to My Document QC > In Progress tab 
Click on saved Petition 
Expected results 
[ ] App navigates to saved Petition Review screen  

#### 3) User access a saved petitions from the Docket Record 
Scenario 1 
Navigate to My Document QC > In Progress tab 
Click on Docket number for saved Petition 
Click on Petition link from Docket Record 
Expected results 
[ ] App navigate to Petition QC form

**Comment by klohman** [comment]
**On click of Save for Later**
* App navigates to My Document QC > Inbox with success message displayed : "Petition saved for later service."
* Case is created 
* All documents are entered onto the docket record without service information 
* Petition displays in My Document QC > In Progress and Petition Section Document QC > In Progress 


#### Reviewing Saved Petition
* On click of Petition link from Document QC > In Progress, navigate to Review Saved Petition screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea6e00ed-9dbe-4711-be55-5681778c3c2c)

**Review Saved Petition screen**
* Orders Needed warning displays on load 
* Saved data displays (same as Review Petition screen) 

**Attachments**
* “Edit” link is hidden 
* On click of PDF links, PDF preview modal displays

**Comment by klohman** [comment]
**Save for Later**
On click: 
* App navigates to My Document QC > Inbox with success message displayed: "Petition saved for later service." 
* Petition remains in My Document QC > In Progress box and Section Document QC > In Progress box 

**Serve to IRS button**
On click, confirmation modal displays

**On click of Yes, Serve**
* All attached documents (except STIN) are entered as served on Docket Record
    - Served column = current date 
    - Parties column = "R"
* Petition is appears in My Document QC > Served and Section Document QC > Served for 7 days 
* On Document Detail for all attached documents (except STIN), display: 
  - QC completed on [date served] by [user name who served]
  - Served [date served]
* Petition Receipt PDF is generated 
* App Navigates to "Print PaperPetition Receipt" screen 

#### Print Paper Petition Receipt screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/07018edc-6b41-4e2b-8502-6c4dee485da3)
* Petition Receipt displays in PDF viewer 

**On click of "Done"**
* App navigates to My Document QC > Inbox with success message displayed "Petition served to IRS"

**Comment by klohman** [comment]
Draft Test Scenarios 

#### 1)- Petitions Clerk reviews the petition data and Saves for Later 
* Login as petitions clerk1 
* Navigate to Document QC 
* Click Create Case on Document QC screen
* Upload RQT and select trial location
* Complete Create Case form 
* Click Create Case button on form 
* Click Save for Later on Review Petition screen 
Expected result
- [ ] User is redirected to their My Document QC Inbox with success message displayed "Petition saved for later service" 
- [ ] The petition that was just entered displays in the In Progress tab of My Document QC and in Section Document QC

#### 2) Petition clerk access a saved petitions from the Docket Record 
* Scenario 1 
* Navigate to My Document QC > In Progress tab 
* Click on Docket number for saved Petition 
* Click on Petition link from Docket Record 
Expected results 
[ ] App navigate to Review Petition screen

#### 3a) Petitions clerk serves Petition to IRS 
* Scenario 1 
* Navigate to My Document QC > In Progress 
* Click on Petition link to navigate to Review Petition screen
* Click "Serve to IRS" button to prompt modal
* Click "Yes, Serve" 
expected results 
- [ ] On click of "Serve to IRS", modal displays 
On click of "Yes, Serve"
- [ ] Modal closes 
- [ ] App navigates to Print Paper Petition Receipt page 
- [ ] Paper Petition Receipt displays in PDF viewer
- [ ] Served date and served parties (R) are entered on Petition and all attached documents 
- [ ] Case status updates to "General Docket (Not At Issue)
- [ ] Petition displays in My Document QC > Served and Section Document QC > Served

#### 3b) Petitions clerk serves Petition to IRS and prints receipt
* Scenario 3b
* Click Done 
Expected results 
- [ ] App navigates to My Document QC > Inbox  with success message displayed "Petition served to IRS." 

#### 4) internal user sees QC and service information on Document Detail for all Petition and attached documents 
* Scenario 3b
* Login as [internal user]
* Navigate to case (from scenario 1) 
* Click on Petition link from Docket Record 
* Navigate to case > Docket Record 
* Click on Request for Place of Trial link from Docket Record 
Expected results 
* Petition document detail displays:
- [ ] QC completed on [today's date] by [petition clerk 1]
- [ ]Served [today's date]
* RQT document detail displays:
- [ ] QC completed on [today's date] by [petition clerk 1]
- [ ] Served [today's date]

#### 5) User can search and discover a case after Petition is served 
* Scenario 1 
* Login as docket clerk 
* Enter case [docket number]in search bar 
Expected results 
- [ ] App navigates to Case Detail > Docket Record

**Comment by JessicaMarine** [comment]
PO Review 5.13.2020:

(1) when the Notice of Receipt of Petition is generated after serving the Petition, there is no need to generate a "mailing" cover sheet for that.  The mailing address is already on the bottom of the Notice of Receipt of Petition so that one page can go in the envelope by itself.  There's no need for the extra mailing cover sheet. (2) On the docket record, these documents are only served on R
