### ISSUE TITLE
Judge Drop-Downs: System-wide

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#4830]
As a CMS user, in order to locate a correct order or opinion, I need the Judge drop-down to include current and past (legacy) judges.. 

## Acceptance Criteria ##
* Before we start work, confer w/ Mark to align on strategy re: legacy judges (e.g., UUID; loading order; etc.) 
* When a CMS user performs an opinion search with a judge's name, the system returns all opinions associated with that judge (current or past)
* When a CMS user performs an order search with a judge's name, the system returns legacy data that are associated with that judge (current or past)
* Judge's names can display in UI as last name only *except* for Messages (see note below) and signatures (need full name and title)
* Ensure that all judge drop-downs (system-wide) contain the correct judges:
  * **Legacy AND Current Judges should display**
    * Associated Judge (in Case Header) 
    * Trial Sessions (Closed, All) - Judge filter 
    * Advanced Search - Order - Judge filter  
    * Advanced Search - Opinion - Judge filter  
  * **Current judges ONLY should display**
    * Messages - Select Recipient [Note: Display last name only for first selection "Buch's Chambers" -- Judge [Last Name] for second selection "actual recipient]
    * Add Trial Session form - Judge select
    * Add Court Issued Docket Entry - “Judge’s Name” select 
    * Trial Sessions (New, Open) - Judge filter 
    * Pending Report - Judge filter 
    * Case Inventory - Judge filter 
    * Trial Session Planning Report (past sessions) 
    * Deadlines Report - Judge filter 
    * Judge’s Note - Once a judge is no longer active, his/her notes should not be retained.

Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)

## Notes ##
* If we need to keep Judge Foley separate from Chief Judge Foley to make things easier for MVP, we can. 
* Consider format of legacy judges being passed into CMS (associated judge is allowed as a string; should it be exact values).
* What happens if Judge's "name" changes -- Judge Foley is current "Chief Judge Foley", but that will change in 2 years -- may also apply to tag on case.
* possible solution, add a unique judge ID that will never change and allow display name to be editable 
- What data should be/should not be included in the API call?
* Will be about 80 judges total
* When judge retires and is no longer a user, you don't need to have a chambers section for the judge. Many of the users in their chambers would likely be assigned to a different role in the court. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] add legacyJudge role (Mrin, Jojo #6580)
- [x] add local legacyJudge user and auth-gate (Mrin, Jojo #6580) 
- [x] add `judgeUserId` (optional uuid) to Case and DocketEntry since judge names will change (Mrinalini #6583)
  - Note: `pk = case|abcdef123, sk = user|${case.judgeUserId}` in Dynamo for aggregatedCaseItems?
  - Double check ES indexes (judge name searches) -- not required as search dropdown is populated from back end
- [x] separate bash script for creating legacy judge users imported via CSV (Matt, Jojo, Mrinalini #6619)
  - [x] script to bulk import judges (Matt, Jojo #6619)
  - [x] endpoint for adding judges from script (Mrinalini #6612)
- [x] (internal) sequence/actions for getting current _and_ legacy judges (Mrinalini and Matt #6593)
- [x] (internal) sequence/actions for getting _only_ current judges (Mrinalini and Matt #6593)
- [x] (public) sequence/actions for getting current _and_ legacy judges (Mrinalini and Matt #6593)
- [x] (public) sequence/actions for getting _only_ current judges (Mrinalini and Matt #6593)
- [x] hook up correct sequences to associated drop-downs (defined above) (Mrinalini and Matt #6593)
- [x] add seed data for order/opinion associated to test legacy judge (Mrinalini, Matt, Jojo #6609)
- [x] create cognito users for each judge, disable/archive legacy judges (Matt, Jojo #6671)
- [x] local env: generate userId upon import (Matt, Jojo #6671)
  - **maybe**: append new json file (`judge_users.json`) with user entries (`users.json`) after import and .gitignore
- [x] output lastname and judgeUserId map after import (Matt, Jojo #6671)
  - e.g. `{ buch: '1f1aa3f7-e2e3-43e6-885d-4ce341588c76', ... }`
- [x] ~modify case migration code~ (field already in `Case` entity)
  - include `judgeUserId` 
- [x] update migration documentation to reflect `judgeUserId` in updated schema (Matt, Jojo #6671)
- [x] double check: places where we use linked judges to include `judgeUserId` (e.g. orders)
- [x] add signedJudgeUserId to DocketEntry (for future) (Matt #6707)
- [x] format judge name with title on Create Message modal (Matt #6707)
- [x] import legacy judge users to dev env (Matt / JoJo)
- [x] Replace legacy judge Armen in unit tests w/ current Judge (Matt #6753)
- [x] Replace endpoint with users endpoint for password consistency (Matt / Jojo #6768)

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by alsmith1** [comment]
List of Current and Past judges from USTC site
Aarons
Armen
Ashford
Beghe
Buch
Buckley
Cantrel
Carluzzo
Chabot
Chiechi
Clapp
Cohen
Colvin
Copeland
Couvillion
Dawson
Dean
Dinan
Drennen
Fay
Featherston
Foley
Gale
Galloway
Gerber
Goeke
Goffw
Goldberg
Greaves
Gussis
Gustafson
Guy
Haines
Halpern
Hamblen
Holmes
Jacobs
Jones
Kerrigan
Korner
Kroupa
Laro
Lauber
Leyden
Marvel
Morrison
Nameoff
Nega
Nims
Pajak
Panuthos
Paris
Parker
Parr
Pate
Peterson
Powell
Pugh
Raum
Ruwe
Scott
Shields
Simpson
Sterrett
Swift
Tannenwald
Thornton
Toro
Urda
Vandervort
Vasquez
Wells
Whalen
Wherry
Whitaker
Wilbur
Wiles
Williams
Wolfe
Wright

**Comment by alsmith1** [comment]
![Screen Shot 2020-03-27 at 12.53.32 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/2a1ed558-4872-42d9-848f-62218df9997c)![Screen Shot 2020-03-27 at 12.53.36 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/024b5f37-8577-445d-812b-f1e4536980de)![Screen Shot 2020-03-27 at 12.53.42 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c7c83f23-b0af-4699-8f8f-bc02f15462f3)![Screen Shot 2020-03-27 at 12.53.48 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/78314322-cb2c-4661-b4f8-d2a2ecaae8bb)![Screen Shot 2020-03-27 at 12.53.54 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/c9fcceb0-7dd3-4459-baaf-e47e962f885b)

**Comment by alsmith1** [comment]
Test Scenarios


#### Scenario 11 User can narrow search by a past judge 
Test data 
- Case xxc-20 
- Order for Filing Fee signed by past judge [Vandervort]
* Login as [internal user] 
* Navigate to Advanced Search > Orders 
* Enter keyword “Fee” 
* Select “Judge Vandervort” from judge dropdown 
* Click Search 
Expected results 
- [ ] Judge’s dropdown includes all judges (see list in story) 
- [ ] Order for Filing Fee for case xxc-20 signed by Judge Vandervort displays in result

**Comment by alsmith1** [comment]
#### Scenario 1 - All users searches by keyword 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal
4. Navigate to Search
5. Click on the Order tab
6. Enter in a keyword Dismissal
7. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Verify the table displays with the following columns
- Docket number
- Case Name
- Order
- Pages
- Date
- Judge
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for Dismissal Entered (listed as full concatenated title)
- [ ] load 25 more button displays below the table if header displays over 25 results

### Scenario 10 - User can narrow search by a current judge 
* Login as Judge Buch 
* Navigate to case xxa-20
* Create Order and Decision, sign, and save as draft
* Login as docket clerk 
* Navigate to case xxa-20 
* Serve Order and Decision
* Login as [internal user] 
* Navigate to Advanced Search > Orders 
* Enter keyword “Decision” 
* Select “Judge Buch” from judge dropdown 
* Click Search 
Expected results 
- [ ] Judge’s dropdown includes all judges (see list in story) 
- [ ] Order and Decision for case xxa-20 signed by Judge Buch displays in results 

#### Scenario 2 - User searches by keyword and docket number with exact match 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for both Keyword (filing fee) and docket number (xxx-20)

#### Scenario 2a - User searches by keyword and docket number with no exact match (no matches found message displays)
1. Login as Judge Cohen 
2. Navigate to Case xxxa-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxxa-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxxb-20)
11. Click search

Expected result
- [ ] Message displays below search area with the header “No Matches found”
- [ ] Message displays below search area with test “Check your search terms and try again.” 

#### Scenario 3 - User searches by keyword, docket number and judge 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20) and Judge (Cohen)

#### Scenario 4 - User searches by keyword, docket number, judge, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter judge (Cohen)
12. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20), Judge (Cohen) and date range (10/04/1980-03/27/2020)

#### Scenario 5 - User searches by keyword, docket number, and date range 
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Filing Fee
7. Navigate to Search
8. Click on the Order tab
9. Enter in keyword Filing Fee
10. Enter in docket number (xxx-20)
11. Enter Date range(10/04/1980-03/27/2020)
12. Click search

Expected result
- [ ] Results Count displays number of results found from search
- [ ] Only documents with “Order” in the title are listed in the table
- [ ] Order column displays "Order for [Something] Entered Judge [Judge Name]
- [ ] Results that display in table are exact matches for Keyword (filing fee), docket number (xxx-20),  and date range (10/04/1980-03/27/2020)
 
#### Scenario 6 - User searches by keyword and case name with exact match
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause - signed by Judge Pugh 
        * Include keyword “affirmative” 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 7 - User searches by keyword and case name with partial matches
**Test data**
* Create case - petitioner and spouse John Smith and Mary Jones (case xxx-20)
    * Create, sign and serve order - Order to Show Cause 
        * Filed by date 12/20/19
        * Include keyword “affirmative” 
* Create case - estate with executor - Estate of John Baxter, Deceased, Wade Baxter, Executor, Petitioner(s) (case xxb-20)
    * Create, sign and Serve - Order for Dismissal - signed by Judge Buch 
        * Filed by date - 03/20/20
        * Include keyword “affirmative”  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ ] Order for Dismissal for case xxb-20 displays in results

#### Scenario 8 - User searches by keyword and case name (no matches) 
**Test data**
* Same as above  
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “Bob”
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 
- [ ] Order for Dismissal for case xxb-20 does not displays in results 
- [ ] “No matching results” message displays 

#### Scenario 9 - User searches by keyword, case name (exact match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 10 - User searches by keyword, case name (partial match)and judge 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Buch from Judge dropdown
* Click Search 
Expected results 
- [ ] Order for Dismissal for case xxb-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 11 - User searches by keyword, case name (exact match), judge, and date range 
**Test Data** 
* Same as above 
* Case xxx-20 (John Smith and Mary Jones) 
    * Create, sign and serve Order for Filing Fee - signed by Judge Pugh 
        * Include word - “affirmative” 
        * Filed date - 01/1/20
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 does not display in results 


#### Scenario 12 - User searches by keyword, case name (partial match), judge, and date range 
**Test Data** 
* Same as above 

**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Select Judge Pugh from Judge dropdown
* Enter Date range - 01/1/20 - 03/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 

#### Scenario 13 - User searches by keyword, case name (exact match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John Smith and Mary Jones”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 

#### Scenario 14 - User searches by keyword, case name (partial match) and date range 
**Steps**
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter Case Name “John”
* Enter Date range - 1/1/19 - 04/01/20
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results 
- [ [ Order for Dismissal for case xxb-20 displays in results 

#### Scenario 15 - User searches by keyword, docket number and case name (exact match)
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John Smith and Mary Jones” 
* Click Search 
Expected results 
- [ ] Order for Filing Fee for case xxx-20 displays in results 
- [ ] Order to Show Cause for case xxx-20 displays in results

#### Scenario 16 - User searches by keyword, docket number, and case name (not exact match) 
* Navigate to Advanced Search > Orders 
* Enter keyword “affirmative” 
* Enter docket number xxx-20
* Enter case name “John” 
* Click Search 
Expected results 
- [ ] form is not submitted
- [ ] Page-level error message displays
- [ ] Field-level error message displays on docket number and case name fields “Enter either a Docket number or a Case name/Petitioner name, not both”

**Comment by alsmith1** [comment]
#### Scenario 1 - All CMS internal or external users can see the search functionality of Court issued Orders
1. Log in as an internal/external user
2. Click on the Advanced Search link
3. Verify when the page loads there are 3 tabs under the advanced search bar (Case, Orders, and Practitioner)
4. Click on the Order tab

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Form is broken down into 2 sections
     1. Keyword(s) Required field
     2. Narrow your search filters
    - Docket Number
    - Case Name
    - Judge
    - Date  (MM/DD/YYYY to MM/DD/YYYY)

#### Scenario 2 - Public can see the search functionality of Court issued Orders
1. Navigate to the public site’s Search page
3. Verify when the page loads there are 2 tabs under the advanced search bar (Case, and Orders)
4. Click on the Order tab

Expected result
- [ ] Order tab displays on advanced search screen
- [ ] Form is broken down into 2 sections
     1. Keyword(s) Required field
     2. Narrow your search filters
    - Docket Number
    - Case Name
    - Judge
    - Date  (MM/DD/YYYY to MM/DD/YYYY)

#### Scenario 3 - Internal Court Users should see results with any documents or data that are part of a sealed case
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Show Cause
7. Navigate to Case Information tab 
8. Seal case
9. Navigate to Search 
10. Click on the Order tab
11. Enter in keyword (Show Cause)
12. Click search
13. Check table for case (xxx-20)

Expected result
[ ]  Order  to show cause docket number (xxx-20) displays in results with a red lock next to the docket number

#### Scenario 4 - External Court Users should see results with any documents or data that are part of a sealed case if they are associated with that case Break down with docket number
1. Login as Judge Cohen 
2. Navigate to Case xxx-20
3. Create, and sign
4. Log in as a docket clerk
5. Navigate to Case xxx-20 
6. Serve Order for Dismissal
7. Log in as an external user that is associated with case (xxx-20)
8. Click on the Advanced Search link
9. Click on the Order tab
10. Enter in a keyword
11. Click search

Expected result
- [ ]  Order for Dismissal docket number (xxx-20) displays in results with a red lock next to the docket number


#### Scenario 5 - The public should not see any documents or data that are part of a sealed case
* Login as docket clerk 
* Navigate to Case xxx-20
* Create, sign, and serve Order for Dismissal 
* Navigate to Case Information tab 
* Seal case 
* Access site as public user 
* Enter keyword “Order for Dismissal” and docket “xxx-20” 
* Click Search 
Expected results 
- [ ] Order for Dismissal for Case xxx-20 does not display in results 
- [ ] “No Matches Found” message displays 

#### Scenario 6 - External Users should not see any documents or data that are part of a sealed case if they are not associated with that case
* Create case as petitioner1 (xxx-20)
* Login as docket clerk 
* Navigate to case (xxx-20)
* Create, sign, and  serve Order for Filing Fee 
* Seal case 
* Login as petitioner2 / privatePractitioner1 / irsPractitioner
* Navigate to Advanced Search > Orders tab 
* Enter “Order for Filing Fee” and docket “xxx-20”
Expected results 
- [ ] Order for Filing Fee for Case xxx-20 does not display in results 
- [ ] “No Matches Found” message displays

#### Scenario 7 - Court orders that have been served and added to docket record are indexed and searchable
* Login as docket clerk 
* Navigate to case xxa-20
* Create, sign, and serve Order to Show Cause
* Navigate to case xxb-20
* Create, sign, and serve Order to Show Cause  
* Navigate to Advanced Search > Orders tab 
* Enter “Show Cause” in keyword 
* Click Search 
Expected results 
- [ ] Order to Show Cause for case xxa-20 is displayed in results 
- [ ] Order to Show Cause for case xxb-20 is displayed in results 

#### Scenario 8 -Court orders that are in draft documents are not searchable
* Login as Judge Buch 
* Navigate to case xxa-20
* Create Order and Decision, sign, and save as draft
* Login as docket clerk 
* Navigate to Advanced Search > Orders tab 
* Enter “Decision” in keyword and docket “xxa-20” 
Expected results 
- [ ] Order and Decision for case xxa-20 does not display in search results 

#### Scenario 9 -Court orders that are added to docket record but have not been served are not searchable
* Scenario 8 
* Login as docket clerk 
* Navigate to Case xxa-20 - Case Detail > In Progress > Draft Documents
* Click on Order and Decision  
* Click Add Docket Entry 
* Complete Add Docket Entry Form 
* Click Save Entry button 
* Login as [internal user] 
* Navigate to Advanced Search > Orders tab 
* Enter “Decision” in keyword and docket “xxa-20” 
Expected results 
- [ ] Order and Decision for case xxa-20 does not display in search results 

#### Scenario 12 Search for order with keyword in title 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal
4. Log in as Judge Cohen
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Dismissal
8. Click search

Expected result
- [ ] Documents with keyword “Dismissal” in the title are listed in the table

#### Scenario 13 Search for order with keyword in body copy 
1. Login as docket clerk 
2. Navigate to Case xxx-20
3. Create, sign, and serve Order for Dismissal with keyword “Star” in the body copy
4. Log in as an ADC
5. Navigate to Search
6. Click on the Order tab
7. Enter in a keyword Star
8. Click search

Expected result
- [ ] Documents that have keyword “Star” in the body copy are listed in the table

#### Scenario 14) User views Order PDF from search results 
* Scenario 12 
* Click on Order for Dismissal link from results table 
Expected results 
- [ ] Order PDF opens in new tab

**Comment by sutt0n** [comment]
OCR'd list of active judges:
```
Ashford	
Buch	
Carluzzo	
Cohen	
Colvin	
Copeland	
Foley	
Gale	
Goeke	
Greaves	
Gustafson	
Guy	
Halpern	
Holmes	
Jones	
Kerrigan	
Lauber	
Leyden	
Marshall	
Marvel	
Morrison	
N ega	
Panuthos	
Paris	
Pugh	
Ruwe	
Thornton	
Toro	
Urda	
Vasquez	
Weiler	
Wells
```

OCR'd list of legacy judges:
```
Aarons	
Armen	
Beghe	
Buckley	
Cantrel	
Chabot	
Chiechi	
Clapp	
Couvillion	
Dawson	
Dean	
Dinan	
Drennen	
Fay	
Featherston	
Galloway	
Gerber	
Goffe	
Goldberg	
Gussis	
Haines	
Hamblen	
Jacobs	
Korner	
Kroupa	
La ro	
Nameroff	
Nims	
Pajak	
Parker	
Parr	
Pate	
Peterson	
Powell	
Raum	
Scott	
Shields	
Simpson	
Sterrett	
Swift	
Tannenwald	
Vandervort	
Whalen	
Wherry	
Whitaker	
Wilbur	
Wiles	
Williams	
Wolfe	
Wright	

```

**Comment by mariahkannenberg** [comment]
Chief Judge title is not important for search; but is important for some of the filters. 
For search, if it makes sense to treat the Judge Foley separate from Chief Judge Foley for search purposes, that's fine for MVP. 

F/Jojo - we’ll prolly have to start persisting the chambers/sections in dynamo since these will change regarding current/legacy judges

**Comment by klohman** [comment]
## Test Scenarios

#### 1a) Users can select from legacy and current judges in Order filter 
* Login as docket clerk 
* Go to Advance Search > Orders 
* Enter search term
* Open judge filter options
Expected results 
- [ ] Dropdown contains all legacy and current judges 

#### 1b) Users filters by legacy judges in Order search 
* Scenario 1 
* Select legacy judge from dropdown 
* Search 
Expected results 
- [ ] App displays Order matches for keyword and legacy judge 

#### 1c) Users filters by current judges in Order search 
* Scenario 1 
* Select current judge from dropdown 
* Search 
Expected results 
- [ ] App displays Order matches for keyword and current judge 

#### 2a) Users can select from legacy and current judges in Opinions filter 
* Login as docket clerk 
* Go to Advance Search > Opinions 
* Enter search term
* Open judge filter options
Expected results 
- [ ] Dropdown contains all legacy and current judges 

#### 2b) Users filters by legacy judges in Opinion search 
* Scenario 1 
* Select legacy judge from dropdown 
* Search 
Expected results 
- [ ] App displays Opinion matches for keyword and legacy judge 

#### 2c) Users filters by current judges in Opinion search 
* Scenario 1 
* Select current judge from dropdown 
* Search 
Expected results 
- [ ] App displays Opinion matches for keyword and current judge 

#### 3a) Users sees legacy judge associated with case in Case Header
* Go to case with legacy judge associated (need migrated/test data)
Expected results 
- [ ] Legacy judge name displays in Case Header 

#### 3b) Users sees current judge associated with case in Case Header
* Go to case with current judge associated
Expected results 
- [ ] current judge name displays in Case Header

#### 4a) Users can filter by legacy judge associated with session in Trial Session list (Closed, All)
* Go to Trial Sessions 
* Click Closed tab 
* Filter by legacy judge (need migrated/test data for legacy trial session)
Expected results 
- [ ] Judge filter contains legacy and current judges
- [ ] Trial sessions display that match selected legacy judge

#### 4b) Users can filter current judge associated with session in Trial Session list (Closed, All)
* Go to Trial Sessions 
* Click Closed tab 
* Filter by current judge 
Expected results 
- [ ] Judge filter contains legacy and current judges
- [ ] Trial sessions display that match selected current judge

#### 5) Users can only select from current judges for messages 
* Go to a case 
* Click Create and “Message” 
* Select section “Chambers” 
* View Select chambers options
Expected results 
- [ ] Chambers dropdown only contains current judges

#### 6) Users can only select from current judges when adding a new trial session
* Go to Trial Session 
* Click Add Trial Session 
* View “Select judge” options 
Expected results 
- [ ]  dropdown only contains current judges

#### 7) Users can only select from current judges  when adding a court-issued docket entry
* Go to case 
* Create Order / Sign/ Save 
* Add Docket Entry 
* View Judge’s Name options
Expected results 
- [ ] dropdown only contains current judges

#### 8a) Users can only filter from current judges for Trial Session list (New, Open)
* Go to Trial Sessions 
* Click New tab 
* Filter by current judge 
Expected results 
- [ ] Judge filter contains current judges
- [ ] Trial sessions display that match selected current judge

#### 8b) Users can only filter from current judges for Trial Session list (New, Open)
* Go to Trial Sessions 
* Click Open tab 
* Filter by current judge 
Expected results 
- [ ] Judge filter contains current judges
- [ ] Trial sessions display that match selected current judge

#### 9a) Users can only filter from current judges and “Chief Judge” for Pending Report 
* Click Reports > Pending Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Documents display that match selected current judge

#### 9b) Users can only filter from current judges and “Chief Judge” for Pending Report 
* Click Reports > Pending Report 
* Select Chief Judge
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Documents display that match selected current judge

#### 10a) Users can only filter from current judges for Case Inventory Report 
* Click Reports > Case Inventory Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Cases display that match selected current judge

#### 10b) Users can only filter from current judges and “Chief Judge” for Case Inventory Report 
* Click Reports > Case Inventory Report 
* Select Chief Judge
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Documents display that match selected current judge

#### 11a Users can only filter from current judges for Deadlines Report 
* lick Reports > Deadlines Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Cases display that match selected current judge

#### 11b) Users can only filter from current judges and “Chief Judge” for Deadlines Report 
* Click Reports > Deadlines Report 
* Select Chief Judge
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Cases display that match selected current judge

#### 12) User searches for Order signed by Chief Judge [Foley] using judge filter [Foley]
* Login as docket clerk 
* Go to Advanced Search > Orders 
* Enter search term
* Select Foley as judge filter 
Expected results 
- [ ] Orders with keyword and signed by Judge Foley and Chief Judge Foley display in results 

#### 13) User searches for Opinion signed by Chief Judge [Foley] using judge filter [Foley]
* Login as docket clerk 
* Go to Advanced Search > Opinion 
* Enter search term
* Select Foley as judge filter 
Expected results 
- [ ] Opinion with keyword and signed by Judge Foley and Chief Judge Foley display in results

**Comment by matthopson** [comment]
These are some notes from discussions in Slack, that I wanted to put here so they stay with the story - this is mostly related to fields for data migration and searches.

#### Document Search Associations
```
Opinion - judge: judgeFullName
Order - signedJudgeName: judgeFullName
Today's Opinions - judge: judgeFullName
Opinion Public Search - judge: judgeFullName
Order Public Search - signedJudgeName: judgeFullName
```

#### Entity Judge Associations
```
Case:
  associatedJudge - name of assigned judge based on trial session: defaults to Chief Judge
DocketEntry:
  judge - judge associated with the document filing (NOT signatory)
  signedJudgeName: - the full name of the judge who signed the document
WorkItem:
  associatedJudge: - name of assigned judge: defaults to Chief Judge
TrialSession:
  judge - obj containing {name, userId} for associated judge
```

##### Future-proof fields that are not currently not being used, but likely will with a refactor, so important for legacy migrations.
```
Case.judgeUserId (associated judge id)
DocketEntry.judgeUserId (associated judge id)
DocketEntry. signedJudgeUserId (id of judge whose signature is on the document)
```
