### ISSUE TITLE
Practitioner: Ability to create case on behalf of a petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#488]
As a Practitioner, in order to file a Tax Court Petition on behalf of my client, I need the ability to create a case on behalf of a Petitioner.

Practitioners who are admitted to practice before the Court need to be able to initiate a case on behalf of a client.  As a result, the system should allow a Practitioner to create a case on behalf of a Petitioner.

## Pre-Conditions
* Practitioner is logged into the system

## Acceptance Criteria
* Practitioner can see how to start a case on their dashboard [Note: need Practitioner dashboard]
* Practitioner can create a case on behalf of taxpayer(s)
* After submitting a case, the practitioner information (name, address, email, phone, bar number) associated with the case is able to be viewed by the parties and internal court user
* After submitting a case, a practitioner can access the case and all of the case details

## Tasks
 - [x] Create practitioner users in Cognito (with hardcoded bar numbers, contact info) (Cody #1203)
 - [x] Create practitioner dashboard view (same as petitioner but no sidebar) (Cody #1206)
 - [x] Modify start case form view to change labels based on user (Rachael #1212)
 - [x] Create/Modify the createCaseInteractor to save the practitioner info (Cody #1210)
 - [x] Add petitioner counsel to the contacts views (William #1209)
 - [x] Trial Information and Petition Details is supposed to show up for the Practitioner and Petitioner (Cody #1207)
- [x] The email address field for the primary contact needs to be hidden throughout - It would be the practitioner's email since they are the logged in user - and not necessarily the petitioner (Rachael #1223)
- [x] Estate without an Executor / PR and Corporation - In Care Of - need to remove the helper text - (Your Name) (Rachael #1223)
- [x] Can we hide the Secondary Contact header on Case Info tab if it is blank? (Rachael #1223)
- [x] Practitioner info not populating on Case Detail page; I logged in as Practitioner 2- the address and phone number didn't populate on Case info tab, only the name and email address (Rachael, Cody)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Practitioner Dashboard - Default 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d3ae9960-a3f8-4425-b1a2-753ea5dec8c8)

- on click of Start a New Case button, open the Start a Case form 

## Practitioner View of Start a Case Form 
- Update language shown in red
- See figma file for updated language for each party type 
- Remove email address field for all party types 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/70e8754b-7dcb-4627-8d02-cc5e32b2fd5e)

## Practitioner Dashboard - With Cases 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/249ec008-f8fa-45da-ba90-aa0d5116f828) 

## Updated Case Detail- Case Information Tab

When a practitioner starts a case, display the practitioner information under "Petitioner Counsel" on the Case Info tab 
- Display name and bar number in the format "Practitioner Name (bar number)"

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/be89c887-bae4-4212-a06f-50de1f95a879)

**Comment by klohman** [comment]
@ericsorenson 

Couple things I noticed while reviewing: 

- The email address field for the primary contact needs to be hidden throughout - It would be the practitioner's email since they are the logged in user - and not necessarily the petitioner 

- Estate without an Executor / PR - 
	- In Care Of - need to remove the helper text - (Your Name)

- Corporation- 
	- In Care Of - need to remove the helper text - (Your Name)

- Can we hide the Secondary Contact header on Case Info tab if it is blank?

- Practitioner info not populating on Case Detail page 
  - I logged in as Practitioner 2- the address and phone number didn't populate on Case info tab, only the name and email address 

![Screen Shot 2019-03-25 at 5.20.04 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8607725c-9016-48f3-b5dc-8e76a91ed93d)

**Comment by JessicaMarine** [comment]
PO review comments:
1. I can't get logged in to test.  What sign-in creditentials are we using for a Practitioner?
