### ISSUE TITLE
CMS User: View and print case record. 

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#49]
As a Party or Court User, in order to see what has transpired in a case, I want to be able to view and print a copy of the docket record.

The docket record is a official record of everything that has happened in a case. A Party or Court User may need to print a copy of the docket record for a variety of reasons.  If someone wishes to print the docket record, a print optimized view should be created that includes the docket number, case caption, party information, as well as the docket record.

## Pre-Conditions:
* A case exists in the system.

## Acceptance Criteria (Post-Conditions):
* Any party or Court user can view and produce a print optimized view of the docket record that includes the docket number, case caption, party information, docket record, and date. [Sample provided below]
* Docket record should print in chronological order (oldest to newest); not on sort
* Print optimized view should be for 8.5x11 paper

## Notes:
* Users may print to paper or to a PDF (via print to PDF)
* The preview of the print-optimized version will be seen via print preview
* The print button should reset the sort order to default
* The public will also need a version of this, but without Petitioner's contact information.  That will be handled in a different story #1624 .

## Tasks:
- [x] create print stylesheet (#2503 -> #2538)
- [x] print styled header (#2503 -> #2538)
- [x] print styled party information (#2503 -> #2538)
- [x] print styled docket record table (#2503 -> #2538)
- [x] add print button to docket record (#2503 -> #2538)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by JessicaMarine** [comment]
Sample of current printable case record.
[https://app.zenhub.com/files/152320868/b101ef96-6b94-4a5d-8a7d-7e436102a332/download](https://app.zenhub.com/files/152320868/b101ef96-6b94-4a5d-8a7d-7e436102a332/download)

**Comment by sarahridgway** [comment]
[https://app.zenhub.com/files/152320868/af224d45-163c-474e-a08d-3e98162d5bb5/download](https://app.zenhub.com/files/152320868/af224d45-163c-474e-a08d-3e98162d5bb5/download)

**Comment by sarahridgway** [comment]
*Case Detail with Print Button*

* Click "Print" in docket record tool bar to invoke a print-friendly docket record layout in a new tab or window

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/15490fbc-429e-49e5-81ae-d8e1f654cf79)

*Print-Friendly Docket Record Layout*

Example with 2 pages: 

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/fa09346a-add7-4ba8-954e-176ce667c5ac)

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/5ace09d9-cb45-4989-b8c0-0d4d39d7629f)

** Note: Party Information table will be updated in story #1324 Manually Add Counsel [THEMIS]

**Comment by sarahridgway** [comment]
*Printable Docket Record Index PDF Example*

[https://app.zenhub.com/files/152320868/dbeb5de2-ad05-492c-ae87-6a71b3774980/download](https://app.zenhub.com/files/152320868/dbeb5de2-ad05-492c-ae87-6a71b3774980/download)

**Comment by uxforgood** [comment]
## Test Scenarios

### Scenario 1

1. Log in as petitioner2
2. Navigate to case 418-19SL
3. Click "Print" to print the docket record
4. Printable docket record view/page should load showing the document in the format it will print
5. Click the print icon the system print modal should display
6. Click print on the system modal and document should print

### Scenario 2
1. Log in as petitioner2
2. Navigate to case 418-19SL
3. Click "Print" to print the docket record
4. Printable docket record view/page should load showing the document in the format it will print
5. Click "Back to Case" 
6. Should return back to the case detail page in the default state (no sorting maintained, etc) 

### Scenario 3
