### ISSUE TITLE
Petitions Clerk: Review/QC of Petition (2.8)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#514]
As a Petitions Clerk, I need the ability to review/QC a Petition that has been assigned to me, so that I can ensure that the metadata associated with the case is accurate.

When a Petition is assigned to a specific Petitions Clerk, the work item will show up in that individual’s work queue.  From their individual work queue, the Petitions Clerk can go into the case and see the Petition.  As part of the review/QC process, the Petitions Clerk reviews, corrects, and saves, any metadata entered by Petitioner.  The Petitions Clerk also enters and saves additional case metadata, such as:
* Year(s) at issue
* Amount(s) at issue
* Fee paid Y/N (how paid?)
* Date of payment

## Pre-Conditions:
* Petitions Clerk is logged into the System
* Petitions Clerk can see in their individual work queue that a new work item is ready for review
* Petitions Clerk can access the case/document from the work queue item

## Acceptance Criteria:
* Petitions Clerk can review/correct/save any metadata entered by Petitioner EXCEPT case type, case procedure selection and Place of Trial selection
* Petitions Clerk can enter the year(s) at issue
* Petitions Clerk can enter the amount(s) at issue
* Document information tab is shown only when status is "New", "Batched for IRS", "Recalled"
* All updated and new metadata is saved in the system 
* All actions that updated and added new metadata is saved in the "Audit Log"
* All metadata is viewable by internal users
* Metadata is not viewable to parties
* Data is auto-saved as a user leaves each field set (d/m/y is a single field set) 
* Any invalid data entered by the user is identified by the system (Non-Happy)
* Server error - user saves and there's a server error - presented with message

## Note:
* Does not include Petitioner personal contact information for this story
* (1/18) **Do you want to add wider screen view to this story?** Yes. Let's do it.
* (1/14) **Do we need explicit yes/no option for payment fee?** No. Not at this time.  
* (1/14) **Will the caption be automatically generated?** Yes. 
* (1/14) No restrictions on decimals for now. Open question to court around how they handle. Mariah added to open questions spreadsheet.
* (1/11) **Can they have the same year in there twice?** No, should only be one amount per year. However, there could be a case type when there's not a case type or an amount at issue. E.g.)  Was someone a contractor? There wouldn't be year or amount. Eventually, there will be a third column of resolved amount.  (Year, amount at issue, resolved amount)
* (1/11) **Are you going to have totals - an amount for the entire decision?** It's not something we currently have, but worth considering. Judges like to know if more than 1M+ at issue. 
* (1/11) **Do we want a dollar sign in or near amount boxes?** We want to make sure they don't type it into the box. 
* (1/11) **Clerk to document Fee payment?** Not int his story. 

## Research/Analysis Notes
Petitions clerk task summary
* Petitions clerks receive 30 items at one time each day. If they complete their 30 items they may go to the mail bin and get more items to work on.
* Petitions clerks work with paper and electronic documents throughout the day
* Electronic petitions are received in priority (date) order
* Items received each day must be completed on that day. Sometimes work does carry over to the next day, but those items are not high priority items
* Petitions clerks need to figure out what orders are needed with a petition
* Clerks enter due dates from the notice, not the petition
* Petitions clerks also spend quite a bit of time on the phone answering questions from petitioners, giving out information
* Clerks must check to see if fees have been paid with the filed petition
* Clerks also receive important alerts/memos regarding rule changes that they must apply to the processing of petitions. They may receive 2-3 rule change memos per week
* If Admissions determines an attorney representing a petitioner is not admitted, they will send the petition back to the petitions clerk, and the clerk will place a service indicator for Pro Se. When this happens, petitions must also serve an order of ratification of petition before IRS service. 

Petitions Clerk Needs:
•	Work queue prioritization
•	Identification of high-priority items, like amended petitions
•	Notifications for rule changes that affect work
•	Efficient data entry
•	Easy document upload
•	The ability to review work prior to IRS service

Petitions Clerk Challenges
•	Scanning and uploading multiple documents connected to a petition
•	Searching for cases
•	Running reports for fees, separating the fee type to create individual reports for more accurate tracking
•	Connecting multiple orders with a case
•	Ensuring service addresses are correct
•	Recalling documents with incorrect information prior to service
•	Correcting information after IRS service

Petitions Clerk Goals
•	Ensuring priority items receive needed attention
•	Ensuring petitions are accurate and completed in a timely manner
•	Ensuring the work of the clerks doesn’t get backed up
•	Ensuring clerks are updated on new processing rules

## Tasks:
- [x] 1. Design Petitions Clerk view of submitted metadata (Natalie, Kristen, Sarah)- Design in comments and For Devs Figma file 
- [x] 2. Design confirmation modal (Kristen) 
- [x] 3. Design capture of history in system (will/cody)
- [x] 4. Add Year amounts collection to case entity (will/cody)
- [x] 5. Create business tests (will)
- [x] 6. Modify design of Petitions Clerk view to integrate modified margins (eric)
- [x] 7. Create new Petitions Clerk view (eric)
- [x] 7b. Integrate view with presenter (eric)
- [x] 8. add "are you sure?" message when user leaves without saving (kris)
- [x] 8b. implement autosave [Eric/Kris]
- [x] 9. filter all case meta-data fields from all db requests not from internal court users (cody)
- [x] 10. design how server errors display (validation) and generic server errors (need language too)
- [x] 11. implement server side field validation error handling (server errors) (will)
- [x] 12. implement field level validations (client side) (computed? plus jsx/html/css)
- [x] 13. create an action and use case which can be ran for validating the form inputs for the review form (cody)
- [x] 14. implement wide screen view
- [x] 15. add little green "save" message (remove on subsequent field update) (eric / Kris)
- [x] 16. money formatting on amounts (cody)
- [x] 17. load casedetail into form in gotToDocumentDetailSequence (will)
- [x] 18. computed for formatting validation errors in the alert on separate lines
- [x] 19. Hide the petitionedit view when on a non-petition document in the documentdetail view. (cody / will)
- [x] 20. implement error classes in view when validation fails (how to validate dates in groups?) (Eric / Kris)
- [x] 21. add + and delete for yearAmounts (cody)
- [x] 22. amount is not required in year (will)
- [x] 23. CSS cleanup (Eric / Kris) (pr out)
- [x] 24. add .00 to amount per design (eric - with #23) (pr out)
- [x] 25. do not show alertBox on field level validation, only on save button (page) validation. (will)
- [x] 26. default to document info when loading the view
- [x] 27. change css logic in CaseDetailEdit view to use computed (replace 
    caseDetailErrors.yearAmounts &&
                caseDetailErrors.yearAmounts[idx] &&
                caseDetailErrors.yearAmounts[idx].year)
etc. (will)
- [x] 28. enter key while in year/amount inputs causes new year/amount row to create (eric)
- [x] 29. year amount error messages aren't associated to correct year/amount row (cody/will)
- [x] 30. amount on year amount needs to be a number? field level validation for '101x' not firing. (eric)
- [x] 31. remove green alert from save action. (cody)
- [x] 32. fee payment id has auto increment control (eric)
- [x] 33. input mask numeric inputs to add commas (eric)
- [x] 34. "Add Another" button not yet working on first click when empty row there (kris)
- [x] 35. remove  margins on top of the error message and the usa-input-error (kris)

## Business tests
When a petition clerk is viewing a petition:
(some of these are same as the metadata entry stories for the petitioner)
- [x]  petitions clerk sees the selected case type, case procedure, and place of trial but cannot edit them
- [x] petitions clerk can modify the irs date of notice month, day, and year using current validations
- [x] petitions clerk can input a year and amount at issue (not required)
- [x] petitions clerk can add multiple years and amounts at issue to the case metadata but each year must be unique
- [x] petitions clerk can remove all but the first year and amount (fields stay but no entries required)
- [x] petitions clerk can enter the fee payment date - month/day/year
- [x] petitions clerk can enter a fee payment id
- [x] all fields are saved to the case and the petitions clerk can view the newly updated case and metadata
- [x] when the case metadata is saved the prior case metadata will be retained in the system 

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by klohman** [comment]
@JessicaMarine @sadlerw 

Error Messaging

- field level error messaging will be displayed when focus is removed from a field (tab out, mouse out) 

See previous comment for field validation rules 

![Document - Petition Clerk View - Errors.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5270d336-9b4e-4123-8ee1-631884f5bd2f)

**Comment by klohman** [comment]
@JessicaMarine @sadlerw 

When a user attempts to navigate away from the Document Detail page with unsaved changes to the petition metadata, display the following modal confirmation message. ![Document - Petition Clerk View - Save.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f49645b1-9acb-438f-af2b-6bc9d742cbac)

On click of Save and Quit, save all the changes and navigate to where the user has selected. On click of Quit without Saving, discard all unsaved changes, and navigate to where the user has selected.

**Comment by klohman** [comment]
@JessicaMarine @dubharmonic @sadlerw 

Updated designs per today's conversations. 

Default - Document Detail Page 
![Document - Petition Clerk View.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f6e2e55e-9e6f-49b0-87e4-71681f37d945)

On Save:
![Document - Petition Clerk View-1.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/46409e37-29b1-4fbe-81fa-e5c66bb309b6)

Unsaved changes modal : 
![Document - Petition Clerk View- Save Modal.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/99d401e6-0fb1-47f8-bdfc-1fb79c70c6d0)

Field level error: 
![Document - Petition Clerk View - Errors.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ee06fb42-4466-4179-901a-6d0109ce1082)

**Comment by uxforgood** [comment]
@JessicaMarine @dubharmonic @sadlerw 

# Server errors # 

When a server error occurs, user will see an error alert on the page between the document metadata (date filed and filed by) and the tabs. 

Message goes away when: 
- User clicks on "Dismiss" link or icon
- User interacts with the page (clicks into a field, scrolls the PDF, etc) 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/d7ab3ec1-e4b1-4e4a-80d6-1a8725a28839)

**Comment by dubharmonic** [comment]
Possible server errors we'll need to handle:

400: Validation error
401: User isn't logged in
403: User is logged in, but doesn't have permission
404: Not found
4XX: Unexpected request from the client
5XX: Something went wrong, we made a mistake in our code or configuration

**Comment by klohman** [comment]
@JessicaMarine @uxforgood @sadlerw @dubharmonic 

# Server Validation Errors on Save  #

On click of Save, check validation on all fields- and if any server validation errors are found, display page-level message.

## Page level error text 
Page level error text "There's an error with this page" will be displayed for all errors. 
- Display bulleted list of fields with errors using format "Enter valid [field label]" 

## Field level error 
Field level error state and messaging should display on any fields with an error. 

### For date of notice ###
If not valid, display a field level error that says "Please enter a valid date"
If in the future, display a field level error that says "That date's in the future. Please enter a valid date."

### Year of notice ###

If not valid (4 digits), display a field level error that says "Please enter a valid year"
If in the future, display a field level error that says "That year's in the future. Please enter a valid year."


### Fee Payment Date ###
If not valid, display a field level error that says "Please enter a valid date"
If in the future, display a field level error that says "That date's in the future. Please enter a valid date."

The page-level error message and all field-level errors will display until the user clicks "Save" again, and another validation check occurs. 

![Screen Shot 2019-01-22 at 1.31.25 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c83016e0-fa52-469e-bf99-091b9cb767af)

**Comment by JessicaMarine** [comment]
Jessica's review comments 1/24/19:
(1) I'm not sure if that little green message by the Save button is happening or not because when I hit save, it takes me to a top of the page Success Msg. 
(2) If you change the date of the IRS notice in the "Document Info" tab, the date does not update on the "Case Info" tab on the case detail page.  That "Case Info" tab is where the itnernal user is viewing all the case metadata, so any changes to metadata has to carry through to there.  
(3) Were we going to change the design of the "Amount" box to be $ [box].00 ? I thought I saw a design by @Kristen Lohman to that effect.  

Also, this is a small UX design issue -- the fee info is showing up in two separate places in the "Case Info" tab.  It should only be displayed one place and it should have form of payment, date of payment, and ID (if Pay.gov).
