### ISSUE TITLE
Petitions/Calendar Clerk & Docket Clerk: Add and display statistics after petition served

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#5164]
As a Petitions/Calendar Clerk and/or Docket Clerk, so that I can record the outcome of the case, I need the ability to add statistics to the case metadata.

## Acceptance Criteria
* For **deficiency** cases, a Petitions/Calendar Clerk and/or Docket Clerk must have the ability to capture the following information for each tax year after the petition is served:  

   (1) Deficiency amount determined by Court; and
   (2) Aggregate penalty amount determined by Court.

[Note: For all other case types (CDP, Whistleblower, Passport, Partnership, etc.), we will not capture any amounts at issue or amounts determined by the Court.]
 
* For all cases, a Petitions/Calendar Clerk or Docket Clerk must have the ability to capture after the petition is served:
   (1)  Litigation costs; and
   (2)  Damages under IRC §6673

* These case statistics should be viewable to all Court employees
* Case statistics are not viewable by external users

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Updates to entities (Rachael #5276)
  - [x] 1a Add determination amount for deficiency and penalties to Statistics entity (Rachael #5276)
  - [x] 1b Add other statistics to Case entity (not an array, just the 2 additional fields) (Rachael #5276)
- [x] 2 Add Statistics tab to case detail page - Case Information tab (only displays for internal users) (Rachael #5278 #5279)
  - [x] 2a If no statistics, display message
  - [x] 2b Add table display of statistics (Rachael)
  - [x] 2c Edit buttons for tables (check user role) (Rachael)
- [x] 3 Display Add Deficiency Statistics and Add Other Statistics buttons if correct user role and case type (Rachael #5284)
- [x] 4 Add route and view for Add Deficiency Statistics form (Cody #5282)
  - [x] 4a Sequences and actions for submitting the form (Matt #5298)
  - [x] 4b Endpoint for submitting the form (Rachael #5293)
  - [x] 4c Calculate penalties as determined by court modal (Cody #5282)
  - [x] 4d Validation (Cody #5294)
  - [x] 4e Fix Styles (Cody #5294) 
- [x] 5 Add route and view for Add Other Statistics form (Rachael)
  - [x] 5a Sequences and actions for submitting the form (Matt #5292)
  - [x] 5b Endpoint for submitting the form (Rachael #5288)
  - [x] 5c Validation

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Case Detail > Case Information > Statistics tab 
* Create new tab nested under Case Information - Statistics 

**No statistics added**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fc4034a3-3cd0-4585-a7b7-b607bfd99f79)

* If no statistics have been added to the case, display message "There are no statistics for this case."

**Add Deficiency" link**
* Displays only if case type = Deficiency
* On click of "Add Deficiency" link, navigate to Add Deficiency Statistics screen  
* Only displays for Docket Clerk, Petitions Clerk, Clerk of the Court roles

**Add Other Stats link**
* Displays for all case types 
* On click of "Add Other Stats" link, navigate to Add Other Statistics screen 
* Only displays for Docket Clerk, Petitions Clerk, Clerk of the Court roles

### Statistics table
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ed72998e-bf75-465a-877d-35eff7ff7107)

#### Deficiency
If Deficiency stat have been added
* Deficiency table displays 
* "Edit" link displays (Only displays for Docket Clerk, Petitions Clerk, Clerk of the Court roles)

* "Add Deficiency" link is displayed 

**Year/Period**
* displays the Year/Period entered on the Petition QC form or Add/Edit Statistics screen 

**IRS Notice** 
Displays data entered: 
* Petition QC form > Deficiency field 
* Add/Edit Statistics form > Deficiency (IRS Notice)  

**Determination** 
Displays data entered: 
* Add/Edit Statistics form > Deficiency (Determination)
  
#### Penalties
If penalty stats have been added
* Deficiency and Penalty tables displays 
* "Edit" link displays (Only displays for Docket Clerk, Petitions Clerk, Clerk of the Court roles)

**Year/Period**
* inherited from Deficiency table, not displayed

**IRS Notice** 
Displays data entered: 
* Petition QC form = Total penalties field 
* Add/Edit Statistics form = Total penalties (IRS Notice)  

**Determination** 
Displays data entered: 
* Add/Edit Statistics form = Total penalties (Determination)

#### Other 
If Other stat have been added
* Other table displays 
* "Edit" link displays (Only displays for Docket Clerk, Petitions Clerk, Clerk of the Court roles)
* "Add Other Stats" link is hidden 

**Litigation costs**
Displays data entered: 
* Add/Edit Statistics = Litigation costs 

**Damages (IRC §6673)**
Displays data entered: 
* Add/Edit Statistics = Damages (IRC §6673)

**Comment by klohman** [comment]
## Add Deficiency Statistics screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ae189f61-a9f6-49e2-baaa-af5d35be655c)

**Year/Period**
* Required field 
* If blank or invalid, display error message on save : "Enter a valid year/period"
* Numeric values only 
* Max characters = 4 

**Deficiency (IRS Notice)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Total penalties (IRS Notice)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Calculate IRS penalties**
* On click of Calculate IRS penalties, display Calculate IRS Penalties modal (Same functionality as on Petition QC screen) 
* Saved sum value of all penalties is displayed in Total penalties (IRS Notice) field 

**Deficiency (Determination)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Total penalties (Determination)**
* is optional
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Calculate Court penalties**
* On click of Calculate Court penalties, display Calculate Court Penalties modal 
* Saved sum value of all penalties is displayed in Total penalties (Determination) field 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/22f3449c-c058-4676-a1a2-bc0d135ad851)
 
### On Save 
* Data is saved to system on case entity (?)
* Data is displayed on Case Information > Statistics tab 

**If initiated from Case Information > Statistics screen** 
* On save, app navigates to Case Information > Statistics tab with success message displayed 

**If initiated from Edit Statistics screen**
* On save, app navigates to Edit Statistics screen with success message displayed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/94b9f00b-2ff1-407a-b252-f62b77cd1810)

## Add Other Statistics screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/da8504b1-de5c-4767-8b9e-7693e3b404ae)

**Litigation costs**
* Is optional 
* numeric values only
* format for US currency during input = $XX,XXX.XX

**Damages**
* Is optional 
* numeric values only
* format for US currency during input = $XX,XXX.XX

#### On Save 
* Data entered is saved to case entity(?)
* App navigates to Case Information > Statistics tab screen with success message displayed 
* Other stats table displays on Statistics screen with entered data 
* "Add Other Stats" link on Statistics tab is hidden

**Comment by klohman** [comment]
## Edit Deficiency stats 

* On click of Edit link on Deficiency table on Statistics, navigate to Edit Deficiency screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57adcb29-f5b5-4865-90ba-94d5633b718d)

#### Year tabs 
* Each year/period added displays as a different tab 

Tab contains fields:
* Deficiency (IRS Notice) - displays data entered on Petition QC or Add Deficiency screen 
* Deficiency (Determination) - displays data entered on Add Deficiency screen 
* Total penalties (IRS Notice) - displays data entered on Petition QC or Add Deficiency screen 
* Total penalties (Determination) - displays data entered on Add Deficiency screen 

**Calculate IRS/Court Penalties**
* functionality should mimic the Add Deficiency screen 
* Values entered in Penalty fields should be retained and editable (TBD question to Jessica)

**Add Deficiency link**
* On click, navigate to Add Deficiency screen 

#### On save 
* App navigates to Case Information> Statistics tab with success message displayed 
* updated data displays on Deficiency/Penalties tables 


## Edit Other Statistics screen 
* On click of Edit link on Other table on Statistics, navigate to Edit Other Statistics screen 

Contains fields: 
* Litigation costs 
* Damages 

#### On Save 
* App navigates to Case Information> Statistics tab with success message displayed 
* updated data displays on Other tables 

**If both Litigation and Damages fields are blank**
 * Other statistics table is hidden on Statistics screen 
* Add Other Stats link displays on Statistics screen

**Comment by klohman** [comment]
## 5164 Test Scenarios 


#### Scenario 1) Court user views deficiency statistics added during case creation/Petition QC on the Case Detail screen > Case Information > Statistics tab
* Login as petition clerk 
* Create Case 
* Select case type = Deficiency  
* Enter year/period = 2010 
* Enter deficiency = = $4,000.00
* Enter Total penalties = $550.77
* Complete Create Case form 
* Click Create Case (xxx-20)
* Serve petition to IRS
* Login as [court user]
* Navigate to case (xxx-20)
* Click on Case Information Tab
* Click on Statistics tab 
Expected results 
- [ ] Statistics tab is displayed nested under Case Information 
- [ ] Deficiency table displays 
    - [ ] Year/ Term = 2010 
        * deficiency = $4,000.00
- [ ] Penalties table displays 
        * Total penalties = $550.77
- [ ] “Add Deficiency” button is hidden 
- [ ] Edit Link is hidden 

#### Scenario 2a) Parties/public do not see deficiency statistics on the Case Detail screen 
* Scenario 1 
* Login as IRS attorney and file Answer in case xxx-xx 
* Navigate to Case Detail > Case Information 
Expected results 
- [ ] Statistics tab is hidden 

#### Scenario 2b) Parties/public do not see deficiency statistics on the Case Detail screen 
* Scenario 1 
* Logout 
* Go to public site and search for case xxx-20 
Expected results 
- [ ] Case Information and Statistics tab is hidden 

#### Scenario 3a) Petitions/docket/CoC adds deficiency statistics by year (from Statistics tab) and views on Statistics screen
* Login as petitions/docket clerk 
* Navigate to Case Detail (Case type = Deficiency_
* Navigate to Statistics tab 
* Click “Add Deficiency Statistics”
* “Select Year or period” = Year 
* Enter Year = 2018
* Enter deficiency (IRS)= 100.00
* Enter deficiency (Determination)= 200.00
* 
* Click Save 
Expected results 
On Add Deficiency statistics screen 
- [ ] “year” radio is selected by default on Add Deficiency Statistics
ON save
- [ ] App navigates to Statistics tab with success message : “Year/period added.”
- [ ] Deficiency table displays 
- [ ] 2010 displays under Year/Period 
- [ ] $100.00 displays under Deficiency(IRS)
- [ ] $200.00 displays under Deficiency(Determination)
- [ ] Penalties table displays with null values : “TBD” 
- [ ] Add Deficiency Statistics link displays 
- [ ] Add Other Statistics link displays 

#### Scenario 3b) Petitions/docket/CoC adds deficiency statistics by year (from Edit Statistics screen) and views updates
* Scenario 3a
* Click “edit” on Deficiency table 
* Click “Add Deficiency Statistics”
* “Select Year or period” = Year 
* Enter Year = 2019
* Enter deficiency = 100.00
* Click Save 
Expected results 
On click of “Edit”, 
- [ ] App navigates to Edit Deficiency Statistics screen 
ON save
- [ ] App navigates to Edit Deficiency screen with success message : “Year/period added.”
- [ ] “2019” displays as new tab 
- [ ] On 2019 tab, 2019 displays under Year/Period 
- [ ] On 2019 tab, $100.00 displays under Deficiency
- [ ] Add Deficiency Statistics link displays 

#### Scenario 4a) Petitions/docket/CoC adds deficiency statistics by period and view on Statistics screen 
* Login as petitions/docket clerk 
* Navigate to Case Detail (Case type = Deficiency)
* Navigate to Statistics tab 
* Click “Add Deficiency Statistics”
* “Select Year or period” = Period 
* Enter Last date of period = 03/31/2019
* Enter total penalties = 50.00
* Click Save 
Expected results 
On Add Deficiency statistics screen 
- [ ] “year” radio is selected by default on Add Deficiency Statistics
ON save
- [ ] App navigates to Statistics tab with success message : “Year/period added.”
- [ ] Deficiency table displays 
- [ ] Deficiency amounts display null value = “TBD”
- [ ] 03/31/18  displays under Year/Period 
- [ ] Penalties table displays 
- [ ] total penalties displays as $50.00
- [ ] Add Deficiency Statistics link displays 
- [ ] Add Other Statistics link displays 

#### Scenario 4b) Petitions/docket/CoC adds deficiency statistics by period (from Edit Statistics screen) and view updates
* Scenario 4a
* Navigate to Statistics tab 
* Click Edit on Deficiency table
* Click “Add Deficiency Statistics”
* “Select Year or period” = Period 
* Enter Last date of period = 06/30/19
* Enter total penalties = 50.00
* Click Save 
Expected results 
On Add Deficiency statistics screen 
- [ ] “year” radio is selected by default on Add Deficiency Statistics
- [ ] On click of “Period” radio button, “Last Date of period” field displays
ON save
- App navigates to Edit Deficiency screen with success message : “Year/period added.”
- [ ] “06/30/19” displays as new tab 
- [ ] On “06/30/19” tab, “06/30/19” displays as Last date of period 
- [ ] On “06/30/19” tab, $50.00 displays as Total penalties
- [ ] Add Deficiency Statistics link displays 

#### Scenario 5) Petitions/docket/CoC cannot add deficiency statistics to a non-Deficiency case type  
* Login as docket clerk 
* Navigate to Case detail (case type is not Deficiency)
* Navigate to Statistics tab 
Expected results 
- [ ] “Add Deficiency Statistics” link is not displayed 
- [ ] “Add Other Statistics” link displays 

#### Scenario 6) Petitions/docket/CoC adds Other statistics and views on Statistics screen 
* Login as petitions/docket clerk 
* Navigate to Case (Case type = any)
* Navigate to Statistics tab 
* Click “Add Other Statistics” 
* Enter litigation costs = 5000.00
* Enter damages = 3000.00
* Click Save 
Expected results 
- [ ] On Save, app navigates to Statistics screen with success message displayed: “Other statistics added.” 
- [ ] Other statistics table displays with “Edit” link 
- [ ] Litigation costs displays as $5,000.00
- [ ] Damages displays as $3,000.00
- [ ] “Add Other Statistics” link is hidden 

#### Scenario 7) Petitions/docket/CoC edits Other statistics and views on Statistics screen 
* Scenario 6 
* Click the “Edit” link on the Other Statistics table 
* Update litigation costs = 5500.00
* Click save 
Expected results 
- [ ] On Save, app navigates to Statistics screen with success message displayed: “Other statistics updated.” 
- [ ] Other statistics table displays with “Edit” link 
- [ ] Litigation costs displays as $5,500.00
- [ ] Damages displays as $3,000.00
- [ ] “Add Other Statistics” link is hidden

#### Scenario 8) Edit Other Statistics Form: Petitions/docket clerk deletes other statistics 
* Scenario 6 
* Click “Edit” on Other Statistics table 
* Click Delete Other Statistics 
* Click “Yes, Delete” on confirmation modal 
Expected results 
On Delete of year/period 
- [ ] app navigates to Statistics screen with success message “Other statistics deleted."
- [ ] Other Statistics table is hidden 
- [ ] Add Other Statistics link is displayed 

#### Scenario 9a) Add Deficiency form: Petitions/docket clerk can enter total penalty manually (IRS Notice) and view on Statistics screen 
* Login as docket clerk
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year =2012
* Enter Total penalties (IRS Notice)= $450.80
* Save
Expected results 
On Add Deficiency form: 
- [ ] Total penalties (IRS penalties) field displays as formatted $450.80
On Save 
- [ ] Add navigate to Statistics tab with success message displayed 
- [ ] Total penalties for year 2012 = $450.80

#### Scenario 9b) Add Deficiency form: Petitions/docket clerk can enter total penalty manually (Determination) and view on Statistics screen 
* Login as docket clerk
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year =2012
* Enter Total penalties (IRS Notice)= $450.80
* Enter Total penalties (Determination) = $400.00
* Save
Expected results 
On Add Deficiency form: 
- [ ] Total penalties (IRS penalties) field displays as formatted $450.80
- [ ] Total penalties (Determination) field displays as formatted $400.00
- 
On Save 
- [ ] Add navigate to Statistics tab with success message displayed 
- [ ] Total penalties (IRS)for year 2012 = $450.80
- [ ] Total penalties (Determination)for year 2012 = $400.00


#### Scenario 10a) Add Deficiency form: Petitions/docket clerk can enter up to 10 penalties and calculate total (IRS Notice) 
* Login as docket clerk
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year = 2012
* Click Calculate penalties on IRS  
* Enter Penalty 1- 5 = 100.00
* Click Add another penalty button (up to Penalty 10)
* Enter Penalty 6-10 = 100.00
* Click Calculate 
Expected results 
On click of Calculate penalties link
- [ ] Calculate Penalties modal display
On display of Penalty 10
- [ ] Add another penalty link is hidden 

On click of Calculate from modal
- [ ] Modal closes 
- [ ] Total penalties (IRS) for 2012 displays as formatted $1,000.00

#### Scenario 10b) Add Deficiency form: Petitions clerk can enter up to 10 penalties and calculate total (Determination) 
* Login as docket clerk
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year = 2012
* Click Calculate penalties as determined by Court  
* Enter Penalty 1- 5 = 100.00
* Click Add another penalty button (up to Penalty 10)
* Enter Penalty 6-10 = 100.00
* Click Calculate 
Expected results 
On click of Calculate penalties link
- [ ] Calculate Penalties modal display
On display of Penalty 10
- [ ] Add another penalty link is hidden 

On click of Calculate from modal
- [ ] Modal closes 
- [ ] Total penalties (Determination) for 2012 displays as formatted $1,000.00


###### Scenario 11) If petitions/docket clerk enters manual entry of total penalties and then calculates penalties, the calculated total overrides the manual entry 
* Login as docket clerk
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year = 2012
* Enter total penalties (IRS) = 450.99
* Click Calculate penalties 
* Enter Penalty 1 = 450.99
* Enter Penalty 2 = 100.00 
* Click Calculate button 
Expected results 
- [ ] Modal closes 
- [ ] Total penalties (IRS) displays as formatted $550.99

#### Scenario 12) Petitions/docket clerk can manually edit a calculated penalty total 
* Scenario 10b
* Enter Total Penalties (Determination = 2200.88
Expected results 
- [ ] Total penalties (Determination) field is editable 
- [ ] Total penalties (Determination) displays as formatted $2,200.88

#### Scenario 13a) Petitions/docket clerk adds up to 12 years of deficiency statistics 
* Login as docket clerk 
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Year = 2012
* Enter deficiency = 4000
* Enter Total penalties = 500.00
* Save 
* Click Edit Deficiency Statistics 
* Click Add Another Year/Period 
* Complete form and Save 
* Click Add Another Year/Period (x10) 
* Save 

Expected results 
On Add Deficiency screen > Save 
- [ ] On save of each year, a new tab is added to the Edit Deficiency screen 
- [ ] New tab label is the year entered 
- [ ] After 12 year are entered, Add Another Year/Period button is hidden 
On save from Edit Deficiency screen 
- [ ] App navigates to Statistics screen with success message “Deficiency statistics updated.” 
- [ ] All entered years display under Deficiency table 
- [ ] Years are sorted oldest to newest 

#### Scenario 13b) Petitions/docket clerk adds up to 12 periods of deficiency statistics 
* Login as docket clerk 
* Navigate to Case (case type = deficiency)
* Navigate to Statistics tab
* Click Add Deficiency Statistics 
* Enter Last date of period = 12/31/2009
* Complete form
* Save 
* Click Edit Deficiency Statistics 
* Click Add Another Year/Period 
* Enter another period
* Complete form and Save 
* Click Add Another Year/Period (x10) 
* Save 

Expected results 
On Add Deficiency screen > Save 
- [ ] On save of each period, a new tab is added to the Edit Deficiency screen 
- [ ] New tab label is the last date of period entered 
- [ ] After 12 periods are entered, Add Another Year/Period button is hidden 
On save from Edit Deficiency screen 
- [ ] App navigates to Statistics screen with success message “Deficiency statistics updated.” 
- [ ] All entered periods display under Deficiency table 
- [ ] Years are sorted oldest to newest 


#### Scenario 14a) Edit Deficiency form: Petitions/docket clerk can edit total penalty manually (IRS Notice) and view on Statistics screen 
* Scenario 9a
* Click Edit link on Deficiency table 
* Update Total Penalty (IRS) for 2012= 500.00
* Save 
Expected results 
- [ ] Add navigate to Statistics tab with success message displayed “Deficiency statistics updated.”
- [ ] Total penalties (IRS) for year 2012 = $500.00

#### Scenario 14b) Edit Deficiency form: Petitions/docket clerk can edit total penalty manually (Determination) and view on Statistics screen 
* Scenario 9b
* Click Add Edit link on Deficiency table
* Update Total penalties (Determination) for 2012 = $300.00
* Save
Expected results 
- [ ] Add navigate to Statistics tab with success message displayed “Deficiency statistics updated.”
- [ ] Total penalties (Determination)for year 2012 = $300.00

#### Scenario 15) Edit Deficiency form: Petitions/docket clerk can edit deficiency amounts (IRS and Determination) and view on Statistics screen) 
* Scenario 3a 
* Click Edit on Deficiency table 
* Update Deficiency (IRS) for 2010 = $200.00
* Update Deficiency (Determination) for 2010 = $100.00
* Save 
Expected results 
- [ ] App navigates to Statistics screen with success message : “Deficiency statistics updated.”
- [ ] $200.00 displays under Deficiency(IRS) for 2010
- [ ] $100.00 displays under Deficiency(Determination) for 2010

#### Scenario 16) Edit Deficiency form: Petitions/docket clerk can edit year or period and view on Statistics screen 
* Scenario 15
* Click Edit on Deficiency table 
* Update year 2010 = 2009
* Save 
* Click Edit on Deficiency table 
Expected results 
On save: 
- [ ] App navigates to Statistics screen with success message : “Deficiency statistics updated.”
- [ ] Deficiency year 2010 updated to “2009” 
On Edit 
- [ ] App navigates to Edit Deficiency screen 
- [ ] Tab label displays as “2009” 

#### Scenario 17a) Edit Deficiency Form: PEtitions/docket clerk deletes year or period from Deficiency statistics 
* Login as docket clerk 
* Navigate to Deficiency case 
* Add two years of deficiency stats (2010, 2011) 
* Click Edit on Deficiency table 
* Navigate to “2011” tab 
* Click Delete Year/Period
* Click “Yes, Delete” on confirmation modal 
* Click Edit on Deficiency table 
Expected results 
On Delete of year/period 
- [ ] app navigates to Statistics screen with success message "Year/period statistics deleted."
- [ ] 2011 no longer displays in Deficiency table
On click of Edit
- [ ] App navigates to Edit Deficiency table 
- [ ] 2010 tab displays 
- [ ] 2011 no longer displays  

#### Scenario 17b) Edit Deficiency Form: Petitions/docket clerk deletes year or period from Deficiency statistics 
* Login as docket clerk 
* Navigate to Deficiency case 
* Add two periods of deficiency stats (01/31/2018, 03/31/2019)
* Click Edit on Deficiency table 
* Navigate to “01/31/18” tab 
* Click Delete Year/Period
* Click “Yes, Delete” on confirmation modal 
* Click Edit on Deficiency table 
Expected results 
On Delete of year/period 
- [ ] app navigates to Statistics screen with success message "Year/period statistics deleted."
- [ ] 01/31/18 no longer displays in Deficiency table
On click of Edit
- [ ] App navigates to Edit Deficiency table 
- [ ] 03/31/19 tab displays 
- [ ] 01/31/18 no longer displays

**Comment by klohman** [comment]
## UX review 

* Year field - error message = “Enter a valid year.” 
* Last date of period field -error message = “Enter valid last date of period.” 
* “Last date of period” - Error message if blank   “Enter last date of period”
* Cancel button on Add Deficiency Statistics screen isn’t working on dev
* Update page title from “Add Deficiency Statistics” to “Add Year/Period” 
* For “Other Statistics” table, if only one has been entered, hide the other (for example, if only litigation costs are entered, hide the “Damages” column 
* Clerks can enter maximum 12 year/periods of deficiency statistics - after 12 are present, the “Add Year/Period” link should be hidden
* Deficiency stats table - sort oldest to newest 
* Deficiency (Determination) - if required and blank = Error message = “Enter deficiency as determined by Court.”
* Total penalties (Determination) - if required and blank = Error message = “Enter total penalties as determined by Court.”
