### ISSUE TITLE
Petitions Clerk: Revamp - Serve or Save for Later an E-Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#5224]
As a petitions clerk, so that I may serve a petition or save it in while in progress, I need the e-filed petition revamped. 

## Acceptance Criteria
* Petition clerk can save an e-filed petition to serve later 
* Save for Later - leaves petition in In Progress tab 
* Petition clerk can serve an e-filed petition and associated documents in real-time 

On serve:
* Coversheets for all Petition documents receive Served date ( not duplicate cover sheets and do not replace, just served stamp)
* IRS super user receives service email for Petition and other documents (separate email for each)
* IRS super user has party access to the case but does not display under respondent counsel
* Petition Notice of Receipt is generated and link is available on Case Info screen
* Docket entries display served date and “R” for parties 
* If changes were made to case caption, a minute entry is added to the docket record (delta between initial entry and when served)
* If changes were made to docket number suffix (by editing case procedure or case type), a minute entry is added to the docket record (delta between initial entry and when served)
* Petition and other documents are visible under Served tab 
* Case status changes to General Docket - Not at Issue 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 After serving petition, navigate to My Document QC => Inbox with success message (Rachael #5353)
- [x] 2 Check processed by column in Served box - why is it a uuid? (Rachael #5353)
- [x] 3 Coversheet fixes - should not have 2 coversheets (Rachael #5356)
- [x] 4 Verify create docket entry if changes were made to case caption
- [x] 5 Verify create docket entry if changes were made to docket number

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Review Your Petition screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/143c2052-0153-455d-8b1f-b1ea635015f4)

* Update order summary title to "Orders/Notices Needed"

#### On Save for Later 
* App navigates to My Document QC > Inbox with success message displayed "Petition saved for later service."
* Petition displays in My Document/Section Document QC > In Progress tab 

#### On Serve to IRS > Confirmation Modal > Yes, Serve
* App navigates to My Document QC > Inbox with success message displayed "Petition served to IRS."
* Petition displays in My Document / Section Document QC > Served 
* Coversheet on all e-filed Petition documents (Petition, ODS, etc.) includes Served stamp ("SERVED mm/dd/yy")
* IRS Superuser receives service email for Petition 
* IRS superuser receives separate service email for any other documents filed with the Petition (ODS) 
* Notice of Receipt of Petition PDF is created, and "Print Confirmation" link is displayed under Case Information > Overview> Petition Details 
* Docket entry for Petition displays "R" for parties 
* Docket entry for Petition displays current date for "Served" 
* Docket entry for documents e-filed with Petition displays "R" for parties 
* Docket entry for documents e-filed with Petition displays current date for "Served" 
* Case status is updated to "General Docket-Not at Issue"

#### On Serve **If changes were made to case caption** 
If an update was made to the Case Caption field in Petition QC,  or to the Primary and/or Secondary party names (automatically changing the case caption field) : 

* Case caption is updated in Case Detail header 
* Case title, where it displays in tables, Document QC queues, etc., is updated 
* Docket entry is added to the docket record: 
    * No.  = next in sequence 
    * Filed = Current date 
    * Filings and Proceedings = "Caption of case is amended from [old caption] to [new caption]"

#### On Serve **If changes were made to docket number** 
If a change was made to the case type or case procedure resulting in a change to the docket number suffixL 

* Docket number is updated in Case Detail header
* Docket number is updated where it appears in all tables, document queues, reports, etc.)
* Docket entry is added to the docket record: 
* No.  = next in sequence 
* Filed = Current date 
* Filings and Proceedings = "Docket number is amended from [old docket number] to [new docket number]"

**Comment by klohman** [comment]
## 5224 Test Scenarios : Petitions Clerk - Serve or Save for Later (E-filed petitions) 

Set up: Create cases (user petitioner1) 
- Case xx1-20
    * Party type = Corporation 
    * Case type = Deficiency 
    * Case procedure = Regular
* Case xx2-20 
    * Party type = Partnership Tax Matters Partner
    * Case type = Whistleblower
    * Case procedure = Small 
* Case xx3-20 
    * Party type= petitioner
    * Petitioner Name = Peter Giles
    * Case type = deficiency
    * Case procedure = regular 
* Case xx4-20 
    * Party type= petitioner
    * Petitioner name = John Smith 
    * Case type = deficiency
    * Case procedure = regular 
* Case xx5-20 
    * Case type = deficiency
    * Case procedure = regular 
* Case xx6-20SL 
    * Case type = CDP
    * Case procedure = small 


#### 1) Petitions clerk QC’s e-filed petition and saves for later service 
* Login as petitions clerk 
* Navigate to Section Document OC > Inbox
* Click on Petition link for case xx1-20
* Click Review Petition button on QC form
* Click Save for Later 
* Navigate to My Document QC > In Progress   
Expected results 
- [ ] On click of Save for Later, app navigates to My Document QC > Inbox with success message displayed 
- [ ] Petition for case xx1-20 is no longer displayed in My Document QC > Inbox
- [ ] Petition for case xx1-20 is displayed in My Document QC > In Progress tab 

#### 2a) Petitions clerk does not see Served stamp on the coversheet for Petition and associated documents before serve 
* Scenario 1 
* Click Petition link for case xx1-20 
* Click Petition PDF link from Review Your Petition screen 
* Click ODS PDF link from Review Your Petition screen
Expected results 
- [ ] Petition PDF includes system-generated cover sheet 
- [ ] Petition PDF does not include service stamp 
- [ ] ODS PDF includes system-generated cover sheet 
- [ ] ODS PDF does not include service stamp 

#### 2b) Petitions clerk sees Served stamp on the coversheet for Petition and associated documents on serve 
* Scenario 2 
* Click “Serve to IRS” and confirm “Yes, Serve” on modal 
* Navigate to case xx1-20 Docket Record
* Click Petition link from Docket Record 
* Navigate to case xx1-20 Docket Record
* Click ODS link from Docket Record 
Expected results 
- [ ] On click of Petition link, app navigates to Petition Document Detail screen
- [ ] Petition PDF includes one system-generated cover sheet with service stamp “SERVED [today’s date]
- [ ] On click of ODS link, app navigates to ODS Document Detail screen
- [ ] ODS PDF includes one system-generated cover sheet with service stamp “SERVED [today’s date]

#### 3) IRS super user receives separate service email for Petition and other documents on serve
* Scenario 2b
* Login to IRS super user email account 
Expected results 
- [ ] IRS super user received service email for Petition document with Petition service template
- [ ] IRS super user received service email for ODS document with document service template

#### 4) IRS super user has party access to the case but does not display under respondent counsel (cannot test until #4945)

#### 5a) Internal user do not see Notice of Receipt of Petition link before Petition is served 
* Login as petitions clerk 
* Navigate to case xx2-20 Case Detail > Case Information > Overview 
Expected results 
- [ ] “Print confirmation” link is hidden on Petition Details card 

#### 5b) Parties do not see Notice of Receipt of Petition link before Petition is served
* Login as petitioner1
* Navigate to case xx2-20 Case Detail > Case Information > Overview 
Expected results 
- [ ] “Print confirmation” link is hidden on Petition Details card 

#### 6a) Internal user sees Notice of Receipt of Petition link before Petition is served 
* Login as petitions clerk 
* Navigate to case xx2-20 Case Detail > Case Information > Overview 
* Click on Print Confirmation
Expected results 
- [ ] “Print confirmation” link is displayed on Petition Details card 
- [ ] On click of Print Confirmation, app navigates to PDF Viewer with Notice of Receipt of Petition PDF displayed 
- [ ] Notice of Receipt of Petitions displays served date as [today’s date]

#### 5b) Parties see Notice of Receipt of Petition link before Petition is served
* Login as petitioner1 
* Navigate to case xx2-20 Case Detail > Case Information > Overview 
* Click on Print Confirmation
Expected results 
- [ ] “Print confirmation” link is displayed on Petition Details card 
- [ ] On click of Print Confirmation, app navigates to PDF Viewer with Notice of Receipt of Petition PDF displayed 
- [ ] Notice of Receipt of Petitions displays served date as [today’s date]

#### 7) CMS users (internal, external, public) sees service information on docket entry for Petition after served
* Scenario 1 
* Login as docket clerk / petitioner 1 / irs attorney / public (not authenticated)
* Navigate to case xx1-20 Docket Record 
Expected results 
- [ ] Petition docket entry displays “R” under Parties column
- [ ] Petition docket entry displays [today’s date] under Served column
- [ ] ODS docket entry displays “R” under Parties column
- [ ] ODS docket entry displays [today’s date] under Served column

#### 8a) Petitions clerk makes change to case caption during QC and serves Petition (single change)
* Login as petitions clerk 
* Navigate to Section Document QC > Inbox 
* Click Petition link for case xx3-20
* Update Party Type to “Petitioner & Spouse” 
* Enter Petitioner name = Peter Giles 
* Enter Spouse name = Georgette Giles 
* Complete contact form 
* Click Review Petition 
* Click Serve to IRS
* Navigate to Document QC > Served 
* Click on xx3-20
Expected	results
- [ ] Case title displays on Document QC > Served table as “Peter Giles & Georgette Giles, Petitioner(s)”
- [ ] Case caption displays as “Peter Giles & Georgette Giles, Petitioner(s)” in Case Detail header 
- [ ] Docket entry displays on Docket Record as “Caption of case is amended from Peter Giles, Petitioner to Peter Giles & Georgette Giles, Petitioner(s)” 

#### 8b) Petitions clerk makes changes to case caption during QC and serves Petition (multiple changes)
* Login as petitions clerk 
* Navigate to Section Document QC > Inbox 
* Click Petition link for case xx4-20
* Update Petitioner name = John Smith-Reilly
* Click Review Petition 
* Click Save for Later
* Navigate to Document QC > In Progress 
* Click Petition link for case xx4-20
* Update Petitioner name = John Smith-Reilly Jr. 
* Click Review Petition
* Click Serve to IRS 
* Navigate to Document QC > Served 
* Click on xx4-20
Expected results 
- [ ] Case title displays on Document QC > Served table as “John Smith-Reilly Jr., Petitioner”
- [ ] Case caption displays as “John Smith-Reilly Jr., Petitioner” in Case Detail header 
- [ ] Docket entry displays on Docket Record as “Caption of case is amended from John Smith, Petitioner to John Smith-Reilly Jr., Petitioner” 

#### 9a) Petitions clerk changes docket number during QC and serves Petition (single change)
* Login as petitions clerk 
* Navigate to Section Document QC > Inbox 
* Click Petition link for case xx5-20 
* Update Case type = Whistleblower 
* Click Review Petition 
* Click Serve to IRS 
* Navigate to Document QC > Served 
* Click on xx5-20W
Expected results 
- [ ] Docket number displays on Document QC > Served table as “xx5-20W”
- [ ] Docket entry displays on Docket Record as “Docket number is amended from xx5-20 to xx5-20W” 

#### 9b) Petitions clerk changes docket number during QC and serves Petition (multiple changes)
* Login as petitions clerk 
* Navigate to Section Document QC > Inbox 
* Click Petition link for case xx6-20SL
* Update case type = Declaratory Judgment (Exempt Organization)
* Click Review Petition 
* Click Save for Later 
* Navigate to Document QC > In Progress 
* Click on xx6-20 Petition 
* Update case procedure = Regular 
* Click Review Petition 
* Click Serve to IRS 
* Navigate to Document QC > Served 
* Click on xx6-20X
Expected results 
- [ ] Docket number displays on Document QC > Served table as “xx6-20X”
- [ ] Docket entry displays on Docket Record as “Docket number is amended from xx6-20SL to xx6-20X” 
-

**Comment by JessicaMarine** [comment]
PO Review:
(1) For Petition Fee, "Not Paid" is auto-selected, but the box for Order for Filing Fee is not.  If you choose another option and then back to "Not Paid" it will auto-select the box, but it's not that way to start.  I think we should either not have anything pre-selected (my preference) or have "Not Paid" pre-selected and the box for the order checked. 
(2) On the cover sheet for the petition (and any other document filed -- like an ODS), the case caption and the docket number should be the original information, not the updated info.  The only thing that should change on the cover sheet from the time the P filed it is the application of the served stamp.
