### ISSUE TITLE
Petition Service Clean-Up

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5263]
As part of the Petition service flow, the following clean-up items are needed:

## Acceptance Criteria

1. For electronically filed petitions, the service email to the IRS should include "Electronically Filed [date]" instead of the mailing field used on paper petitions
2. For electronically filed petitions, eFiling of additional documents should not be permitted until the Petition has been served (make sure we have appropriate messaging for petitioners/practitioners)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update service email to IRS superuser for e-filed petitions to “Electronically Filed” instead of the mailing date field (Rachael #5513)
- [x] 2 If case status is New, hide “File a Document” button (and Request Access and File First IRS Document) and display message in warning box (Rachael #5513)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Case Detail (Petitioner View)
If case status = NEW 
* Hide "File a Document" button 
* Display message: "You will be able to file additional documents after your Petition is processed." 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1e6823cf-7a4d-4243-a6e3-bd61705080ea)

### Case Detail (Practitioner View - Applies to both Private Practitioners and IRS Attorneys) 
If case status = NEW 
* Hide "File a Document" button 
* Hide "Request Access" button 
* Hide "File First IRS Document" button 
* Display message "You will be able to file documents after the Petition is processed." 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/139df4ce-a2f5-4518-8c42-222806bcba4b)

**Comment by klohman** [comment]
## Test Scenarios 5263

1 ) IRS super user receives service email for electronically filed Petition displaying “Electronically Filed” and date 
* Login as petitioner1 and e-file Petition -xx1-20
* Login as petitions clerk
* Serve xx1-20 
* Login to IRS super user email
Expected results 
- [ ] Service email for Petition displays “Electronically Filed [current date]”

2 ) Party does not see “File a Document” button when case status = NEW
* Login as petitioner 1 
* Create case 
* Navigate to Case Detail 
Expected results 
- [ ] “File a Document” button is hidden 

3a ) Party sees alert message when case status = NEW
* Scenario 2
* Navigate to Case Detail 
Expected results 
- [ ] Alert message displayed “ You will be able to file additional documents after your Petition is processed.”

3b ) Private practitioner sees alert message when case status = NEW
* Login as private practitioner 
* Create a case 
* Navigate to Case Detail 
Expected results 
- [ ] Alert message displayed “ You will be able to file documents after the Petition is processed.”

3b ) IRS attorney sees alert message when case status = NEW
* Login as IRS attorney
* Create a case 
* Navigate to Case Detail 
Expected results 
- [ ] Alert message displayed “ You will be able to file documents after the Petition is processed.”

4 ) Private practitioner / its attorney associated with a case does not see “File a Document” button when case status = NEW
* Login as private practitioner / irs attorney
* Create a case 
* Navigate to Case Detail 
Expected results 
- [ ] “File a Document” button is hidden 

5 ) Private practitioner not associated with a case does not see “Request Access” button when case status = NEW 
* Login as petitioner 
* Create case xx2-20
* Login as private practitioner 
* Search for xx2-20
* Navigate to case detail
Expected results 
- [ ] “Request Access” button is hidden 

7 ) IRS attorney not associated with a case does not see “File First IRS Document” button when case status = NEW 
* Login as petitioner 
* Create case xx2-20
* Login as irs attorney
* Search for xx2-20
* Navigate to case detail
Expected results 
- [ ] “File First IRS Document” button is hidden 

8 ) Public users do not see “File a Document” or alert message when case status = NEW 
* Access CMS as public user 
* Search for xx2-20 
* Navigate to case detail 
Expected results 
- [ ] File a document button is hidden 
- [ ] Alert message does not display
