### ISSUE TITLE
Docket Clerk: Service on Parties of Signed Stipulated Decision

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#530]
As a Docket Clerk, in order to close a case, I want to serve the signed Stipulated Decision on the parties and close the case.

After signing the [Stipulated Decision,](https://www.ustaxcourt.gov/taxpayer_info_glossary.htm#STIPULATED_DECISION) the Senior Attorney then notifies the Docket Clerk that the Stipulated Decision is signed and ready to be served on the parties. The Docket Clerk updates the case metadata (as necessary), marks the served date on the document, and serves the signed Stipulated Decision on both parties.  The case status should automatically change to “Closed”. 

## Pre-conditions:
* Petition has been served on the IRS
* A signed Stipulated Decision is saved in the system in a particular case/docket #. #114
* ~The case has multiple parties associated with the case~
* Docket Clerk has received a message that a Signed Stipulated Decision is ready to be served

## Acceptance Criteria (Post-conditions):
* Only Docket clerks can see the "Serve" button
* Docket clerk can initiate electronic service for the signed stipulated decision to all parties in the case from within the system
* When the Docket clerk initiates service of the Signed Stipulated Decision, a docket record entry is created for the document.
* The docket record is updated with the date and time upon the service to the parties.
* Parties associated with the case receive an email notifying them to log into the system because there's been activity in the case.
* Parties can log into the system and see the signed stipulated decision.
* When parties are served, the case status is automatically changed to “Closed”.

## Notes
* This story does NOT include designing the email template that will be sent (it will remain a plain text email for now)
* Story DOES include writing content for that email, which will be the same content regardless of what document is being served - include dynamic docket number, case caption, and link to log in to system (login page)
* Serving a document does not generate any new Message / Document QC item
* Will need to create some real emails to test sending/receiving service emails
* Served stamp will not be applied to cover sheet in this story
* Served time will be captured when the docket clerk confirms the "serve" action
* 07/24/19 decision to allow authenticated users to pass through to dashboard / home page when using the log in link in the notification email. Unauthenticated users will be asked to login with valid credentials.

## Tasks
- [x] 1 Set up generic e-mail address (Matt)
- [x] 2 Set up account in Cognito (Joe)
- [x] 3 Distribute new account information (Sarah)
- [x] 4 Figure out how to set up SES in terraform (Joe #2441)
- [x] 5 Show "Serve" Button on Signed Stipulated Decision page only for docketclerk (Cody #2430)
- [x] 6 Hide "Serve" button after case is served (Cody #2430)
- [x] 7 Confirmation modal (Cody #2434)
- [x] 8 Success message displayed on document detail page upon case being served (Cody)
- [x] 9 Add served [date and time] stamp to doc detail page (Cody #2440)
- [x] 10 Change default doc name from "Signed stipulated decision" to "Stipulated Decision" (Cody #2447)
- [x] 11 Close case upon case being served (Matt #2436)
- [x] 12 Create docket entry upon case being served (Matt #2436)
- [x] 13 Add [time] to served column on the Stipulated Decision docket entry (Matt #2445)
- [x] 14 Stipulated Decision event code is SDEC - display in code column on docket entry (Cody #2463)
- [x] 15 Lambda & use cases (call to SES) (Joe #2458)
- [x] 16 Generate e-mail (with dynamic data) & send it via SES (Joe #2458)
- [x] 17 Create e-mail text (Sarah)
- [x] 18 UI Design (Sarah)
- [x] 19 Add backend support for capturing served parties for stip decisions (Matt #2452)
- [x] 20 Populate Parties column on docket record after stip decision has been served (Matt #2455)
- [x] 21 Add users for each party type in cognito under test emails (Joe)
- [x] 22 Fixed the served column of the docket record for the served stipulated decision (Matt)
- [x] 23 Email template name should probably be scoped via environment: `case_served_dev` (Cody #2468)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Matt #2474)
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt #2466)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment

**Comment by JessicaMarine** [comment]
@uxforgood @sarahridgway 

Here is the language that is currently sent out as the email notification:

Documents have been served today in your Tax Court case 13661-18.  Please log in to eAccess to view the served document(s).  Certain served documents may be found under "Miscellaneous Unfiled Documents" and may require action on your part.  Please be sure to check for documents under "Miscellaneous Unfiled Documents".

Do not reply to this message.  This e-mail is an automated notification which is unable to receive replies.

**Comment by sarahridgway** [comment]
##Serve Stipulated Decision##

* Limit permission-based display of "Serve Document" button to Docket Clerks
* Clicking on "Serve Document" button invokes a confirmation modal

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/737c1e8d-97f3-49eb-aeb9-e1e133024d13)

##Confirmation Modal##

* Modal requests docket clerk to confirm their action
* Use dynamic display of [document name] so modal can be re-used for other documents
* Clicking "No, take me back" cancels the action and closes the modal, returning to doc detail
* Clicking "Close" cancels the action and closes the modal, returning to doc detail
* Clicking "Yes, serve" takes the following actions:
- Closes the modal and returns to the doc detail
- Actions detailed under Document Served spec
- Actions detailed under Docket Record Entry spec
- Actions detailed under Email Notification spec

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/aac0003f-83b7-4381-ae7a-07c170132207)

##Document Served##

Serving the document takes the following actions:

* Displays served date and time stamp on the doc detail page
* Removes the "Serve Document" button from the doc detail page
* Displays a success message on the doc detail page
* Sets the case status to "Closed"

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/bfcdba8c-2b18-4be6-b8e8-037207e3820d)

##Docket Record Entry##

Serving the document takes the following actions: 

* Displays docket entry with date and time stamp on the docket record
* Docket entry reads "Stipulated Decision Entered, Judge Foley" where "Stipulated Decision" links to the doc detail page
* Event code for entry is SDEC

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/71c6ceb7-ae55-4d9f-9c95-7d3b23d8b80e)

##Email Notification##

Serving the document takes the following actions:

* Sends an email to the parties receiving electronic service
* Email template will be used for other service notifications and includes dynamic text
* Dynamic text for [Name] is the name of the user
* Linked text sends user to the USTC login page
* Pass user to their dashboard after login, not to the served document


Note: Email text is work in progress

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/5500ac3b-7e37-4fad-abb8-ebdb0ac44932)

**Comment by sarahridgway** [comment]
Codes for served parties column: 

R = Respondent
P = Petitioner
B = Both

**Comment by matthopson** [comment]
Just noting: The story includes adding served parties to docket record, but this functionality doesn't exist (not even for served petitions), so this will need to be addressed.

**Comment by sarahridgway** [comment]
Updated email text:

Dear [user name],

A document has been served on your Tax Court case.

Docket Number: [docket number]
 Case Name: [caption]

Document: [document title
 Served: [served date] at [served time][AM/PM] ET

To view this document, please [link]log in to the US Tax Court online[/link].

Certain documents may require your action.

Please do not reply to this message. This e-mail is an automated notification from an account which is unable to receive replies.

**Comment by sarahridgway** [comment]
Steps to test:

* Create a Petition under flexionustc+petitioner
* Submit an Entry of Appearance under flexionustc+practitioner
* Serve the Petition to the IRS under any petition clerk
* Submit a Proposed Stipulated Decision under the flexionustc+respondent
* Send the Proposed Stipulated Decision from any docket clerk to any senior attorney
* Sign the Proposed Stipulated Decision under any senior attorney account
* Serve the Stipulated Decision under any docket clerk account
* Check test email account for notification on your case number - there will be 1 for each party

**Comment by JessicaMarine** [comment]
7/27/19 PO Review:
* After the document is served, the parties should be able to log-in and view the document on the docket record.  In 412-19L, the Sti;ulated Decision is not viewable for the Petitioner, Practitioner or IRS Attorney after service.  It got hung up and still says "Loading"
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/09635c05-8c59-447e-b88a-bc575f150f73)
