### ISSUE TITLE
Practitioner: Filing an Entry of Appearance or Substitution of Counsel

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#531]
As a Practitioner, in order to have access to case records, I need to be associated to the case when I file an Entry of Appearance or Substitution of Counsel.

There are two main scenarios when a practitioner will file an Entry of Appearance:
1) Pro-Se to Represented. A Pro-Se Petitioner has filed, but then hires an attorney. Since the case is already started, the newly hired practitioner will file an Entry of Appearance.
2) Adding Counsel. A case may already have representation, but an additional attorney is being added. In this scenario, the newly hired counsel would file an Entry of Appearance.

Substituting Counsel (Substitution of Counsel)
When a Petitioner wants to substitute counsel (replace previous counsel with a new one), the new counsel should will file a "Substitution of Counsel." (Note: Post-MVP, counsel should be able to select who they are subbing in for. MVP is that we'll allow the Docket Section to do it manually)

## Pre-Conditions
* Practitioner files an Entry of Appearance or Substitution of Counsel

## Acceptance Criteria
* The filing appears on the Docket Section Queue
* When a practitioner files an Entry of Appearance or Substitution of Counsel, they are immediately associated to the case.
* Once associated with a case, the practitioner can see everything in the case 
* Once associated with the case, the practitioner’s data is viewable to other parties and internal Court Users on the Case Info tab
* Once associated with a case, the case should show up on the Practitioner's dashboard.
* Before association, practitioner should be able to see documents in a case, but not open/access them.

## Notes
* Processing of Substitution of Counsel by Docket and removing exiting attorney is addressed in separate story (#1325)

## Tasks
- [x] 1.  Search A Case
  - [x] 1a. Create Search Box View (Kris #1520)
  - [x] 1b. Create Search sequences and actions, connect to view (Kris #1520)
  - [x] 1c. Create/update computed to determine whether header-search shows (hidden from Practitioners) (Kris #1520)
 - [x] 1d. Ensure consistency of responsive design (kris #1529)
- [x] 2. Request a Case
  - [x] 2a.  Create Request a Case button (determine when to hide/show within computed) (Rachael/William #1516)
  - [x] 2b.  Create Request a Case form view and new route (Rachael #1518)
  - [x] 2c.  Create Request a Case Review screen (Rachael #1518)
  - [x] 2d.  Create Request a Case validation sequences/actions (William #1519)
  - [x] 2e.  Create association (new or updated interactor?) between practitioner and case (supports 2a) (William #1527 #1528)
  - [x] 2f.  Refactor determining whether a practitioner is associated with a case (currently calling getCasesByUserAction in gotoCaseDetailSequence) (Rachael)
  - [x] 2g.  Integrate validation sequences into views (Rachael #1521)
- [x] 3. Reveal Practitioner information on Case Info tab (kris)
- [x] 4. pa11y test (kris #1545 )
- [x] 5. Case journey test (Rachael #1531)
- [x] 6. Add petitioner names to docket record entry for Entry of Appearance (Rachael/William/Kris #1537)
- [x] 7. Change Filed By to counsel name for docket record entries (Rachael/William/Kris #1537)
- [x] 8. Change order of columns in dashboard for practitioners (William #1536)
- [x] 9. Disable document links before practitioner is associated with a case (Rachael #1547)
- [x] 10. Clear Certificate of Service date when unselected. (William #1549)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning (William #1554)
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt (William #1556)
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (PR #1551)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
@JessicaMarine 

## Practitioner Dashboard 

* Change order of columns in table to Docket Number, Petitioner Name, Date Filed 
* Remove Search bar from header 
* Add "Search For a Case" widget 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/59ba782f-e309-4a75-a96c-ea002f02d771)

* Search field - functions the same as the global search 
* On click of search button, if no match docket number is found, display error message : "No case was found. Check your docket number and try again."

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cc67adeb-44f5-4eb1-a5f5-caa90a115483)

* If a matching docket number is found, open the Case Detail page for that case 

## Case Detail (practitioner view for non-associated case)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4b790ae8-90ae-45b4-822e-0144da1d70a1)

* Add "Request Access to Case" button to Case Detail page For Practitioner View 
* On click of "Request Access to Case" button, open "Request Access" Form

## Request Access to Case Form 

### Type of Document You're Filing

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5c71dafd-3039-4b45-87ca-9ac8350ed7e6)

* Required field 
* Note: Additional documents may be added to this list- pending court decision

### Tell Us About This Document 
 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7ab51675-2b8f-4a48-8e6f-d7194f16d31c)

* Upload Your Document - required field 
* Certificate of Service - required field 
  - if yes, display "Service Date" field 
* Objections 
    - display field ONLY when Substitution of Counsel is selected as the document type
    - required field ONLY when Substitution of Counsel is selected as the document type

### Parties You're Representing 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ffe987e0-84a3-4e25-883a-2c8f2d79d371)

* Field is required 
* Options include all parties on the case EXCEPT the respondent 
* [Primary Contact Name] should be populated with the primary contact name on the case (same as case info page) 
* [Secondary Contact Name] should be populated with the secondary contact name - ONLY show when Party Type is "Petitioner and Spouse" or "Petitioner and Deceased Spouse" 

* On click of Cancel, discard all data and return user to Case Detail page 
* On click of Review Filing, display Review Your Filing page 

## Review Your Filing 

- same functionality as story #302 

* On click of Submit Your Filing, 
   - document is filed and will create a new entry on the case's docket record 
   - practitioner is associated as the petitioner counsel for the parties selected 
   - user is returned to Case Detail page, with success message displayed 

## Case Detail (practitioner view for associated case) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2554aba6-fee6-4d42-b983-c1f45cdbe326)

* Note: Once practitioner is associated with case, hide "Request Access to Case" button 
* Practitioner information is displayed under Case Information tab

**Comment by klohman** [comment]
## Mobile View Updates 

### Dashboard 
* Search box should appear above the Start a Case button and table on mobile 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fdf32ee4-f819-4cae-b263-cdac1f3f6f8c)

### Case Detail page 
* Request Access button should appear below the case caption and above the Action Required section and Tabs 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7bcee180-3b83-4d80-9795-96706a532719)

**Comment by klohman** [comment]
## Docket Format for Entry of Appearance 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f67d8a60-7dc9-413b-8862-dc9530d0ee73)

- Display Concatenated Document Name - Entry of Appearance for [Parties You Are Representing] 
- Filed By column should display as - Counsel [Practitioner's Name]

## Docket Format for Substitution of Counsel 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1a7de0ad-6fd8-4442-b194-f0fdaf949569)

- Display Document Name as "Substitution of Counsel" 
- Filed By column should display as - Counsel [Practitioner's Name]
