### ISSUE TITLE
Docket Clerk: Add petitioner(s) to existing case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#5386]
As a Docket Clerk, in order to proper manage the parties to a case, I need the ability to add one or more petitioners to an existing case.

Over the course of a case, petitioners may enter or leave the case for various reasons.  Docket Clerks need the ability to add one or more petitioners to an existing case. [Note: Removing Petitioners is covered in #5385]

## Pre-Condition: ##
* Case already exists with only 1 petitioner.
* Refactor primary, secondary and other petitioners into a simple list of petitioners on the case

## Acceptance Criteria: ##
* Docket Clerk needs the ability to add a second petitioners to an existing case.
* Once added to a case, the additional petitioner should be treated the same as a "contact secondary" petitioner.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Now may be the time to move away from primary/secondary/other petitioners and adopt a single array of petitioners.

## Tasks
- [x] Add petitioner button - mob #8123
- [x] new route on click of add petitioner button - mob #8124
- [x] Hide Add Petitioner button for non docket clerk users, or when the case has not been served - mob #8128
- [x] Add Petitioner form
    - [x] UI - mob #8127
    - [x] validation - mob #8130
    - [x] Add existing address logic when checked - mob #8143
    - [x] Add address logic when not checked - Mrinalini #8144
- [x] Submit sequence for add petitioner form - Mrinalini #8145
- [x] submit back end for add petitioner form - Rachael #8146 
    - [x] interactor, lambda etc - Rachael #8146 
    - [x] contactType - secondary - do the distinctions between contact types go away - Rachael #8153 
- [x] Display other petitioners in case information petitioners tab - Tom #8148
- [x] Edit link should display for newly added petitioner(s) - mob #8177
- [x] Display addres 1, 2 and 3 in dropdown, and only display unique addresses - mob #8182

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Cody & Mrin)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Cody & Mrin)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody & Mrin)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
UX research questions 
- What initiates this action? Why? 
- Does it matter that a petitioner wasn’t on the case initially? 
- Do we care when / why this person was added to the case? 
- Is this petitioner any different than the original petitioner? 
- How would you expect to perform this action?

**Comment by ericsorenson** [comment]
Notes: Now may be the time to move away from primary/secondary/other petitioners and adopt a single array of petitioners.

**Comment by klohman** [comment]
## Petitioner tab  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b2ae6e17-c41f-43ed-b2f5-f946d699aac8)

* add “Add Petitioner” button 

**Add Petitioner button**
* On click, navigate to Add Petitioner form 

## Add Petitioner form 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6345053a-3684-4109-816c-efd1ad56c5ff)

**Name** 
* is required 
* Error message if blank - “Enter name”

**Additional name** 
* is optional 

#### Use existing address checkbox 
**If checked**
* display dropdown 
* dropdown should include Mailing address line 1 for all existing petitioners on the case 
* when user selects address from dropdown, address (line 1-3), city, state, zip is populated with selected address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/812d27d2-52fc-424f-94d0-c1648f974155)


**if unchecked**
* dropdown is hidden 
* address fields (address (line 1-3), city, state, zip) are not pre-populated 

#### Login & Service 
* Options are Paper and None 

#### Case caption 
* Field is required 
* Field is pre-populated with current case title 
* on save, case caption is updated and displays updated in case header, and anywhere else case title appears

## On Save
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a68614e6-5c90-45f7-a673-4c362e3fd472)

- app routes back to Petitioner tab with success message displayed: “Petitioner [Name field] added to case.”  
- added petitioner information displays under Petitioner Contact Info 
- updated case caption displays in header and everywhere case title displays 
- added petitioner displays everywhere that lists the parties on the case 
   examples: 
        - Add Docket Entry - Service Parties 
        - File a Document - Who is filing this document? 
        - Add Paper Filing - Who is filing this document?

**Comment by JessicaMarine** [comment]
PO Feedback:
- c/o in Additional Name line shouldn't auto-populate
- Service preference needs to be required (not validating)
