### ISSUE TITLE
Filing Fee: Notate how and when paid or waived (by 1/8)

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#573]
As a court user, so that I may capture within the system that the filing fee has been paid, I need the ability to notate how and when the fee was paid. 

## Acceptance Criteria
* Court user needs ability at any time to indicate that the filing fee has been paid or if it was waived
* Court user needs ability to indicate at any time how the filing fee was paid
* Information regarding payment of filing fee (including null state) should display on Case Info tab for internal users, practitioners and petitioners (not respondent or any public view)
* When filing fee is paid, a Docket entry should be created as of the date of payment and display as "Filing Fee Paid"
* When filing fee is waived, a Docket entry should be created as of the date of waiver and display as "Filing Fee Waived"
* For fee paid: Implement date, code (FEE), filing and proceeding
* For fee waived: Implement date, code (FEEW), filing and proceeding

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] modify the entity (Cody / Kris) #3978
- [x] create the needed docket entries after the IRS Batch process runs (Cody #3980)
- [x] create the edit case information page, action, sequences (Cody #3991)
  ~create the edit button on case information (don't show the edit button until petition is served & processed)~ don't think this is needed. discussed on slack
- [x] create new endpoint for saving the new case information (lambda, serverless config, interactor, persistence) (Kris) #3982
- [x] modify the existing edit petition details view to match the new radio button design in figma (make PetitionPaymentForm component reusable in both places) (Rachael #4011)
- [x] add a new route / pseudo route for the edit petition details page so that users can press the browser back button (Kris) #4012 
- [x] only show Edit button on case detail -> case information -> petition details card for docket users (Rachael #3994)
- [x] clean up payGovDate and payGovId (replaced with new fields) (Rachael #4014)
- [x] add the title for the case info tab that says Petition Fee (Rachael #4016)
- [x] docket entry title needs to be fixed (Cody)
- [x] create the docket entry when changing from unpaid to either paid or waived (Cody)
- [x] fix validation issues (validating too early?) (Kris)
- [x] hide Order for Filing Fee checkbox on QC form when fee is paid or waived (Rachael #4016)
- [x] add filing fee section to case detail case information for petitioners and practitioners (Rachael #4018)
- [x] make petitionPaymentStatus required ~and create migration~ (Rachael #4018)
- [x] update validation error messages to match what was provided by Kristen (Rachael #4016)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Confirm docket entry is showing up where it belongs once we fix - ability to indicate fee has been paid.

**Comment by klohman** [comment]
### Petition QC Form 

**Default View**
https://www.figma.com/file/fCvjNGiDfDBSzYqwhOe91h/Sprint-30?node-id=23%3A1059

* Add radio set : Paid, Not Paid, Waived 

**Paid**
https://www.figma.com/file/fCvjNGiDfDBSzYqwhOe91h/Sprint-30?node-id=19%3A465

On select of "Paid": 
* display Payment date field 
* Payment date field is required when Paid is selected 
* Error message if blank : "Enter a payment date" 

* display "Payment method" field 
* free text field 
* field is required
*  error message if blank: "Enter payment method" 

**Not Paid**
https://www.figma.com/file/fCvjNGiDfDBSzYqwhOe91h/Sprint-30?node-id=23%3A1216

* Display checkbox for "Order for Filing Fee 

**Waived**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/964595d5-a8c6-4464-b6af-9896973e4cfa)

* Display "Date waived" 
* Field is required 
* Error message if blank: "Enter date of waiver" 

**On Serve of Petition** 
If Filing Fee was noted as "Paid", create docket entry:
* Filed date = Payment date field 
* Event code = FEE 
* Filing and proceeding = Paid [payment date] [payment method]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/76312284-d579-4ffd-93dd-9ff435c41c12)

If Filing fee is "Waived" , create docket entry: 
* Filed date = Date waived 
* Event code= FEEW
* Filing and proceeding = Waived [date waived]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ce620e08-e177-4d8c-80d7-89a5aa5c21ef)

### Updated Case Detail > Case Information 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c15fec42-b304-48da-acc5-def9f73f7e20)

* Add "Edit" button on Petition Details Card 
* Edit is displayed for internal users only 

* Update "Filing fee" read-only field 
   - If not paid, field displays as "Not Paid" 
   - If paid, field displays as "Paid [payment date] [payment method]"
   - If waived, field displays as "Waived [date waived]" 


### Edit Petition Details 
* On click of Edit, navigate to Edit Petition Details screen 
* Filing Fee radio selected and dynamic fields entered during Petition QC are displayed 

**On Save**
* On click of Save, save changes and navigate back to Case Information > Overview with success message displayed ("Your changes have been saved") 

If Filing Fee was changed to "Paid", create docket entry:
* Filed date = Payment date field 
* Event code = FEE 
* Filing and proceeding = Paid [payment date] [payment method]



If Filing fee was changed to "Waived" , create docket entry: 
* Filed date = Date waived 
* Event code= FEEW
* Filing and proceeding = Waived [date waived]

**Comment by klohman** [comment]
### Test Scenarios 537

#### 1) Petitions clerk indicates that no fee has been received during QC 
* Login as petitions clerk 
* Navigate to Document QC Inbox 
* Click on new petition 
* Select “Not Paid” radio under “Fee paid” field
Expected results 
- [ ] Fee paid radios are unselected by default
- [ ] On select of “Not Paid”,  Order for Filing Fee checkbox displays 

#### 2) Petitions clerk indicates that fee has been received during QC 
* Scenario 1 
* Select “Paid” radio 
Expected results 
- [ ] Order for Filing fee checkbox is hidden 
- [ ] Fee payment date field is displayed 
- [ ] Payment method field is displayed 

#### 3) Petitions clerk indicates that fee was waived during QC 
* Scenario 1 
* Select “Waived” radio 
Expected results 
- [ ] On select of Waived, Date waived field displays 

#### 4a) Petitions clerk sees payment info (Not paid) entered during QC on Case Detail page 
* Scenario 1
* Save 
* Navigate to Case Detail > Case Information 
Expected results 
- [ ] Fee paid field displays as “Not paid” 

#### 4b) Petitions clerk sees payment info (Paid) entered during QC on Case Detail page 
* Scenario 2
* Enter 12/19/19 as Payment date 
* Enter “check” as Payment method
* Save 
* Navigate to Case Detail > Case Information 
Expected results 
- [ ] Fee paid field displays as Paid 12/19/19 check 

#### 4c) Petitions clerk sees payment info (Waived) entered during QC on Case Detail page 
* Scenario 3
* Enter 12/20/19 as Date waived
* Save 
* Navigate to Case Detail > Case Information 
Expected results 
- [ ] Fee paid field displays as Waived 12/19/19 

#### 5) Docket clerk indicates that no fee has been received 
* Login as docket clerk 
* Navigate to case 
* Navigate to Case Information 
* Click “Edit” 
* Select “Not Paid” radio under Fee Paid field 
* Save 
Expected results 
- [ ] On click of Edit, navigates to Edit Petition Details screen 
- [ ] On save, navigates to Case Info > Overview with success message displayed 
- [ ] Fee paid field displays as “Not paid” 

#### 6) Docket clerk indicates that fee has been received 
* Login as docket clerk 
* Navigate to case 
* Navigate to Case Information 
* Click “Edit” 
* Select “Paid” radio under Fee Paid field 
* Enter 12/15/19 as Payment date 
* Enter pay.gov 12344555 as payment method 
* Save 
Expected results 
- [ ] On click of Edit, navigates to Edit Petition Details screen 
- [ ] On save, navigates to Case Info > Overview with success message displayed 
- [ ] Fee paid field displays as Paid 12/15/19 pay.gov 12344555

#### 7) Docket clerk can indicate fee has been waived
* Login as docket clerk 
* Navigate to case 
* Navigate to Case Information 
* Click “Edit” 
* Select “Waived” radio under Fee Paid field 
* Enter 12/19/19 as Date waived 
* Save
Expected results 
- [ ] On click of Edit, navigates to Edit Petition Details screen 
- [ ] On save, navigates to Case Info > Overview with success message displayed 
- [ ] Fee paid field displays as “Waived 12/19/19”

#### 8) Petitions clerk sees docket entry for Fee Paid on Docket Record after QC 
* Scenario 4b 
* Navigate to Case 
* View Docket Record 
Expected results 
- [ ] Docket entry is displayed for 12/19/19 - FEE - Paid 12/19/19 check 

#### 13) Docket clerk sees docket entry for Fee Paid on Docket Record when updated 
* Scenario 4a 
* Login as docket clerk 
* Navigate to Case Information 
* Click Edit 
* Update Filing Fee to Paid - 12/20/19 pay.gov 
* Save 
Expected results 
- [ ] [ ] Docket entry is displayed for 12/20/19 - FEE - Paid 12/20/19 check 

#### 14) Petitions clerk sees docket entry for Fee Waived on Docket Record after QC 
* Scenario 4c 
* Navigate to Docket Record 
Expected results 
- [ ] Docket entry is displayed for 12/19/19 - FEEW - Waived 12/19/19

#### 15) Docket clerk sees docket entry for Fee Waived on Docket Record when updated 
* Scenario 4a 
* Login as docket clerk 
* Navigate to Case Information 
* Click Edit 
* Update Filing Fee to Waived - 12/14/19
* Save 
Expected results 
- [ ] Docket entry is displayed as 12/14/19 - FEEW - Waived 12/14/19
