### ISSUE TITLE
Court User: Generate confirmation of case initiation

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#653]
As a Court User, in order to provide notice to Petitioner that their Petition has been processed, I need the system to generate a confirmation. 

When a Petitioner sends a paper Petition to the Court, they need to receive some sort of paper confirmation back from the Court indicating that their case was properly processed.  This confirmation should also provide them with their case caption and docket number that must be used on all future filings.  The Petitions Clerk should be able to print out this confirmation and mail it to a paper-filing petitioner.  The system should generate a confirmation for an electronic petition and allow the filer to print it.

## Pre-Conditions
* Case has been successfully created (either from paper or electronically)

## Acceptance Criteria
* The System must generate a confirmation that a case was created for both paper and electronically filed petitions
* Petitions Clerk should be able to print out and mail a copy of the confirmation to a paper-filing petitioner
* An electronic-filing petitioner should be able to self-print the confirmation
* Court Users should be able to access the Confirmation in the future as it existed at the time of issuance
* The confirmation is *not* included in the docket record
* The confirmation must be printable.
* The confirmation must include the case caption and docket number.
* Other content to add? (Jessica to confirm with Tina and Stephanie)
* Remove autosave capibility

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* A sample of our current receipt/confirmation is below in the comments.
* Possibly start the correspondence file? 
* Confirmation involves templated headers and inserting metadata into a printable page (PDF) and is likely similar to order creation
* Add printable receipt to electronically submitted petitions - can we add this as AC (KL)?
* Because communication from the court to petitioner. Need to keep a record. Court prints and mails paper confirmation to paper-filing petitioner. 
* Per Jessica 10/27/19: Need to figure out how Petitions Clerks are going to remember to go back and print-out any receipts for paper-filing petitioners *after* the petition has been served.  Need to discuss with Justine, but maybe (for MVP) she just keeps a daily list.

## Tasks
- [x] 1. Write PDF generation  (William #3365  #3377)
  - [x] 1a. pdf generation interactor
  - [x] 1b. (persistence?)
  - [x] 1c. "Case Confirmation - 101-19 Smith, Jane.pdf" (what's the name? exclude any suffixes)
- [x] 2. PDF Design Implementing PUG (Eric/Kris #3397)
- [x] 3. Add "Print" links to Case Information views for petitioner (William #3393)
- [x] 4. Petitioner shown Success message with link (note: re-engineer this component?) (William #3403)
- [x] 5. Add "Print" links to Case Information views for internal users  (William #3365)
- [x] 6. "Save & Print Confirmation" button on UI when editing petition  (William #3365)
- [x] 7. ~Create PDF view component for confirmation similar to Printable Docket Record, links back to case info~
- [x] 8. Generate Confirmation on Create Case (William #3402)
- [x] 9. Update process to generate confirmation after the petition has been served (William #3416 #3417)
- [x] 10. back button from the print confirmation should return user to where they came from and be labeled "Back"
what happens if/when we autosave? -- new PDF generated ONLY upon clicking save button

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Themis #3427)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

#### Scenario 1 - Petitions Clerk should be able to print out and mail a copy of the confirmation to a paper-filing petitioner after entering the petition and serving to IRS (force batch to run)
1. Log in as a Petitions Clerk
2. Navigate to My Document QC Inbox
3.  Click on Create a Case
4. Enter data and click Serve to IRS
5. Go to My Document QC and the batched for IRS tab, click Run, batch for IRS process button
6. When the run of the batch completes click on the served tab
7. Click into the document in which to print the confirmation
8. Click Print confirmation button

Expected result
- [x] Petition is placed in batch for IRS tab
- [x] Batch Runs and the petition displays in Served Tab
- [x] Verify on opening the served petition the print confirmation button
- [x] Message in inbox is created letting user know the doc is ready to print
- [x] PDF can be printed
- [x] Page redirects to the previous page

#### Scenario 2 - Petitions Clerk should be able to print out and mail a copy of the confirmation to a paper-filing petitioner after entering the petition and serving to IRS (wait for batch to be served to IRS)
1. Log in as a Petitions Clerk
2. Navigate to My Document QC Inbox
3.  Click on Create a Case
4. Enter data and click Serve to IRS
5. When the batch is served click on Messages Navigation
6. Click on the new message "Petition Served"
7.  Click Print confirmation button

Expected result
- [x] Petition is placed in batch for IRS tab
- [x] A new message displays in users inbox once document has been served
- [x] Clicking on the new message redirects to the petition.
- [x] Verify the print confirmation button displays
- [x] PDF Confirmation is generated
- [x] PDF can be printed
- [x] Page redirects to previous page
- [x] Complete message

#### Scenario 3 - Court Users should be able to access the Confirmation in the future as it existed at the time of issuance
1. Log in as a petitions clerk
2. Navigate to Docket
3.  Click on Case Information Tab
4.  Click on Print Confirmation

Expected result
- [x] PDF Confirmation is opened
- [x] PDF can be printed
- [x] Page redirects to the previous page

#### Scenario 4 - An electronic-filing petitioner should be able to self-print the confirmation (After Completing Petition)
1. Log in as a petitioner
2. Click File a Petition
3. Complete the Petition and click submit
4. Go to the docket and case information tab
5. Print your confirmation

Expected result
- [x] Petition has been submitted and user is redirected to home screen
- [x]At a later date... user confirms Print link displays on case info tab
- [x] User  can click on print receipt link
- [x] PDF Confirmation is opened
- [x] PDF can be printed

#### Scenario 5 - An electronic-filing petitioner should be able to self-print the confirmation (At a later time)
1. Log in as a petitioner
2.  Navigate to Docket
3.  Click on Case Information Tab
4.  Click on Print Receipt

Expected result
- [x] PDF Confirmation is opened
- [x] PDF can be printed

#### Scenario 6 - The confirmation must include the case caption and docket number. 
1. Log in as a petitions clerk
2.  Navigate to Docket
3.  Click on Case Information Tab
4.  Click on Print Receipt
5.  Verify case caption and docket number are displayed on the PDF receipt/confirmation

Expected result
- [x] PDF Opens
- [x] Case Caption and docket number is at the top of the PDF confirmation

**Comment by JessicaMarine** [comment]
Sample Notification of Receipt of Petition:
[https://app.zenhub.com/files/152320868/c8272e2c-1798-4bdd-ad00-e07216e31703/download](https://app.zenhub.com/files/152320868/c8272e2c-1798-4bdd-ad00-e07216e31703/download)

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-15 at 10.24.53 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/ccab1b3b-5464-46d1-b53b-273f4f140b44)![Screen Shot 2019-10-15 at 10.25.11 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/007d206b-e3fb-497c-8a9f-a42d4e17086d)![Screen Shot 2019-10-15 at 10.25.26 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/91fd3a8f-976e-45bd-8d16-99c47bed78bf)![Screen Shot 2019-10-15 at 10.25.39 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/547f8a97-bff6-4ffa-9625-aeb703c70d2a)![Screen Shot 2019-10-15 at 10.26.21 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/9c1460d3-661e-4d88-a55c-028327538270)

**Comment by alsmith1** [comment]
![confirmation-print-cordinates.jpg](https://images.zenhubusercontent.com/5d766a771251c6000116623d/43aa2395-ca35-4655-bfe7-409d974d1181)![printenvelope.jpg](https://images.zenhubusercontent.com/5d766a771251c6000116623d/f7a56371-8bb0-4bcd-ba21-9c3c3007c253)

**Comment by alsmith1** [comment]
652. if the petitions clerk files a new doc and then creates/prints the doc info link on the print page would go to the edit view with the save and save/print button
they should only see the create and create and print buttons on initial creat of case
and the link on the print page should be back to Case Detail

**Comment by alsmith1** [comment]
for the petitions detail card for external users. the only field present, right now should be the filing fee.

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-30 at 11.09.06 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/efbb011f-dd97-427e-b9c3-2b81658bf14c)

international address ex. 
if there are 3 address lines add in country after postal code. if less then 3 address lines country goes on its own line

**Comment by JessicaMarine** [comment]
PO review 11.2.19:
(1) the confirmation message for an electronic petition should read: "Your receipt will appear under the Case Information tab in your case once your petition is processed by the court."; and 
(2) on 128-19, I changed the case caption during the Petition QC process, but the new case name was not picked up on the QC table on the Batched for IRS tab or the Served tab -- if the case caption is changed, that should update the Case name wherever it appears (i.e., messages, QC, deadlines, etc.)
