### ISSUE TITLE
Performance Tuning: getDocketNumbersByUser

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#6830]
As the Court, in order to make sure that all cases needing a Notice of Change of Address/Phone/Both get one, we need to make sure that the system properly returns the user’s cases.

## Acceptance Criteria:
* All cases needing a Notice of Change of Address/Phone/Both get one
   * All open cases and any case closed for less than 6 months

## Notes:
* getDocketNumbersByUser is called when generating change of address
* these records are fairly small but could be a lot of them for some practitioners
* also includes closed cases in this response so this will get worse over time

## Tasks
- [x] create ES persistence method (Jojo / Eric #6976)
- [x] substitute new method for old (Jojo / Eric #6976)
- [x] seed script (Jojo / Eric)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by ericsorenson** [comment]
If this lambda won't reliably finish in 29 seconds with production scale, we'll no longer be able to use websockets to track progress for the user.

- Modify `generateChangeOfAddress` to only collect the docketNumbers of cases that need to be changed
- Create SQS queue for cases to update
- `generateChangeOfAddress` will send jobs to the queue for one case at a time
- a new lambda function will update a single case with Notice of Change of Address/Phone/Both
