### ISSUE TITLE
Petitions Clerk: Orders to be Issued following QC process

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#698]
As a Petitions Clerk, in order to keep track of what orders I need to issue, I need a way to note in the system what orders are required after a QC is performed. 

## Pre-Conditions:
* Petitioner has submitted a new case to the Court
* Petitions Clerk can access the new Petition for QC

## Acceptance Criteria
* User has a way to indicate which orders need to be issued during the QC process
* Update Petitions Clerk's QC view implemented during #699 to be read-only when status is "Batched for IRS" (see design below)

## Note:
* All of the metadata fields need to be editable on the QC screen
* List of orders issued by petitions section - https://drive.google.com/file/d/13VqXTvxwB0Cb8VbU3H_WPhy6n4Zzl9gZ/view?usp=sharing
* Need to use the QC metadata to determine the list of orders that could be issued at this point

### Feedback from Petitions Clerks 2/26  
- Clerks preferred tabs to be reordered; party information was the area most of them would focus first 
- Clerks preferred the order checkboxes in context to the information they related to; had no issues with the display of the other orders 
- Clerks all had questions related to the Fee Payment Date and Payment ID fields - we will address these fields in a later story 
- Clerks all had concerns about the timing of IRS batch service - their current process has IRS service happening in the morning for the previous days petitions
- Clerks did not find the summary screen beneficial- they all prefer to complete the orders immediately and would not likely print or return to the summary screen 
- Clerks and supervisor all had major concerns about petitions being served before completing the required orders 
- Want order generation to occur before the petition is batched for IRS service or prevent petitions with orders still required to be blocked from service somehow 

### Recommendations 
- Update tab order on Document Info to : Parties , Case Info, IRS Notice 
- Keep the order checkboxes in context with their related fields 
- Work with the Court to revisit the QC and order generation flow

## Tasks
- [x] 1. Design updates to petition QC screen (Kristen)
- [x] 2. Add checkboxes to views (Rachael) 
- [x] 3. Add validation for new fields to Case entity (Rachael)
- [x] 4. Add party information to read-only view of Document Info tab (Rachael) 

## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
-  [x] CI/CD - Code is deployed to DEV
- Other
  - [x] alerting and monitoring for new functionality in place and successfully exercised

**Comment by mariahkannenberg** [comment]
Confirmation summary screen
User can see confirmation message of the batching to IRS
Case can be seen as changed to "Batched for IRS"
User can see the summary of all changes made to the Petition
This is the delta of values between when the petitioner submitted the Petition and when it was batched to IRS (don't have to display any intermediary or temporary changes made between those two states)

"View Petition" button would take them to the document detail view of the Petition (now in "read only" mode with ability to recall from IRS batch)
"Back" breadcrumb returns user to Individual Work Queue
This Petition / work queue item is no longer in their individual queue Inbox, but now in their Sent box

**Comment by klohman** [comment]
## Order for Ownership Disclosure Statement 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4f8343c2-4fcd-45cb-a3d8-c3d640907232)

On Parties tab:
for Party types of Corporation, Partnership (as the tax matters partner), Partnership (as a partner other than a tax matters partner), and Partnership (as a partnership representative under BBA Regime) 

- display checkbox "Order for Ownership Disclosure Statement below the ODF link 


## Order to Show Cause 
On Case Info tab: 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0c65a9a4-470e-4ca3-b8da-9f54790334e5)

- Display checkbox labelled "Order to Show Cause" 


## Order for Filing Fee 
On Case Info tab: 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/728bdcc0-8a7a-42cc-ac7c-8d20b78c1fc1)

- display checkbox labelled "Order for Filing Fee" 


## Other Orders 
On Case Info tab: 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/39edd798-34c3-4cc6-b633-a24cfc23a485)

- display 4 checkboxes with the following labels:
  - Order for Ratification of Petition 
  - Notice of Attachments in the Nature of Evidence  
  -  Order for Amended Petition 
  - Order for Amended Petition and Filing Fee  

The order tied to any selected checkboxes should be saved in the system (data will be used in future stories)

**Comment by klohman** [comment]
## Document Info - Read Only View 

When case status is "Batched for IRS", the Document Info tab on the Petition is read-only. 

### Party Information (Read-only) 

- Display Party Type and the contact information for both party type - same format as on the Case Detail Page > Case Information tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/91eaa3fc-f697-4c11-990e-05a8f4ada388)
