### ISSUE TITLE
Practitioner: Ability to Edit Email Address

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#7406]
As a Practitioner, in order to keep all my information current with the Court and ensure I am getting service emails, I need the ability to edit my email address.

Related to #2223: Edit Petitioner's Email

## Pre-Conditions
* Practitioner exists in DAWSON with an email address

## Acceptance Criteria
* Practitioner has the ability to **edit** his/her email address
* Practitioner is provided new credentials to access DAWSON [See note below].
* When the email has changed, the practitioner is required to verify their new email address.
* Practitioner is able to log-in and access their cases
   * Ensure that the practitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
   * Practitioner can eFile documents in cases
* Practitioner's service preference remains as electronic
* Practitioner receives service emails at the new service email address
* ~~Editing email generates a Notice of Change of Email Address (create as own story w/petitioner??)~~New Story #7643
* Email updates in every case the practitioner is associated with 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider whether we have to create and link a new Cognito account or whether Cognito may allow an admin to just change email address
* Look at current rules around which cases are updated (open, closed for x days - was this just for notice?)
https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/signing-up-users-in-your-app.html

## Tasks

- [x] 1 Add My Account item - Team mob #7669
- [x] 2 on select of My Account, route to My Account screen  - Team mob #7670
- [x] 3 Move ‘My Contact Information’ to ‘My Account’ - Team mob #7670
- [x] 4 Add ‘Login & Service Email Address’ to ‘My Account’ - Team mob #7671
  - [x] Display current email - Team mob #7671
  - [x] On click of Change Email, route to Change Email screen - Team mob #7671
- [x] 5 Create Change Login & Contact Email Address page - Team mob #7671
  - [x] Validation - Team mob #7674
  - [x] If email exists in cognito, display error - Team mob #7676
- [x] 6 Create Verify Email modal - Team mob #7680
- [x] 7 On submit of change email
  - [x] Add global pending email banner - Team mob #7682
  - [x] old email still displays under Login & Service email & on cases
  - [x] Persistence of email update (interactor etc.) - Team mob #7684
  - [x] Add ‘emailPending’ to User entity - Team mob #7682
- [x] 8 Send verification email to UPDATED email address - Team mob #7689
- [x] 9 Create an endpoint to handle verification and email update - Team mob #7694
  - [x] If user is logged in, display verification success page - Team mob #7691
  - [x] If user is NOT logged in, redirect to instruction page. - Team mob #7691
- [x] 10 Update persistence of email update to be async - Team mob #7699
  - [x] Potentially display progress bar - Team mob #7706
- [x] Remove `My Contact Information` from Irs/Private practitioner dashboard - Team mob #7729

Refactoring: 
- [x] Update getCognitoUserByEmail to use adminGetUser instead of listUsers - Team mob #7699

Questions:
What happens in the UI after ‘please check your new email modal’?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
# UI Updates 

## Edit Practitioner Contact Info Screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/36212edd-ea8f-4aea-bc57-428523e596a4)

**Email address** 
* add Email address field 
* Field is required 
* field populates with user’s current Cognito email 
* error message is blank : “Enter email address.” 

**On click of Save when email address has changed**
* Display confirmation modal 

## Confirm email modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2f8da2fd-5178-4ec0-8a49-b621d6dc66ca)

* display updated email address (read-only) 

**On click of Cancel**
* Modal closes and remains on Edit screen 

**On click of Continue**
* Validate email 
      - if errors occur, display error message on email field
        - check for valid email format - Error message : “Enter a valid email address” 
        - check for duplicate email in Cognito - Error message: “An account with this email already exists. Enter a new email address.”

  -  Run Cognito workflow (TBD)

**Comment by klohman** [comment]
# 7406 Test Scenarios 

## 7406 

#### 1) Practitioner updates email and saves form with valid email address 
* Login as practitioner 
    * privatePractitioner10@example.com
    * irsPractitioner10@example.com
* Click Edit on Contact Info card 
* Update email address 
    * privatePractitionertest@example.com
    * irsPractitionertest@example.com
* Click Save 
* Re-enter matching email 
* Click Continue on modal 
Expected results 
On click of Save 
- [ ] Confirmation modal displays 
On click of Continue 
- [ ] App routes to Dashboard with success message displayed “Changes saved.” 
- [ ] Practitioner email is updated under Case Info > Petitioner Counsel on all cases 
- [ ] All Open and Closed cases associated with practitioner display on the dashboard 
- [ ] Updated email is displayed in My Contact Info card 

#### 2) Practitioner updates email and saves form with invalid email address 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field - “Enter a valid email address” 

#### 3) Practitioner updates email and saves form with duplicate email address 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Practitioner updates email and files a document 
* Login as practitioner 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
* Click Edit on Contact Info card 
* Update email address
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
* Go to case 
* File a Motion for New Trial 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address receives service email 
- [ ] Old email does not receive service email 

#### 5) Practitioner updates email and cannot login with old email address
* Scenario 4 
* Login as practitioner
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com 
Expected results 
- [ ] User sees error on login for invalid credentials 

#### 6) Practitioner updates email and logs in with new email 
* Scenario 4 
* Login as practitioner
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
Expected results 
- [ ] Login is successful 
- [ ] App displays Practitioner dashboard with all associated cases 
- [ ] Updated email is displayed in My Contact Info card 

#### 7) Practitioner updates email and receives service for court-issued document 
* Scenario 4 
* Login as docket clerk 
* Go to case 
    * Case has private practitioner flexionustc+emersongreen2@gmail.com 
    * Case has irs practitioner flexionustc+IRS2@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address receives service email 
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
- [ ] Old email does not receive service email 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com 


#### 8) Practitioner updates email and enters non-matching email on confirmation 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = firstemail@email.com
* Click Save 
* Re-enter non-matching email = secondemail@email.com
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field -  “Email addresses do not match.”

**Comment by klohman** [comment]
## Edit Practitioner Contact Information 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b913236a-8f47-4525-88e8-95adc00aeb08)]

* email is read-only 
* On click of edit, display email fields 

**Email address** 
* add Email address field 
* Field is required 
* field populates with user’s current Cognito email 
* error message is blank : “Enter email address.” 

**On click of Save when email address has changed**
* Display confirmation modal 



## Edit Practitioner Contact Information 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ac99cd9-078c-4979-bb20-066fd3397039)

**Email address** 
* add Email address field 
* Field is required 
* field populates with user’s current Cognito email 
* error message is blank : “Enter email address.” 

**On click of Save when email address has changed**
* Display confirmation modal

**Comment by klohman** [comment]
## Practitioner Dashboard 

* Add current email to My Contact Information

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/68b10692-876d-422a-8cc7-856aef734a32)


## Edit Contact Information
 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/647d970a-003f-4709-8663-56e590c91a1c)

**Current email address**
* Display current email in read-only format 


#### Change Login & Contact Email 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display Verify Email Modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* Old email is still valid
* New email is not yet valid 

## Verify New Email modal

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea335369-257e-4f6a-8ca7-38b7b76e0ff1)
* Display modal after save 
* Modal displays new email address in <placeholder> 
* on click of OK , navigate back to Dashboard 

## Dashboard with pending email

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d8dbd8aa-e9d2-4eb0-b914-20309c509a6a)
* app routes back to Dashboard with success message displayed

* display warning message under page header globally 

* old email still displays under My Contact Information 


## Edit Contact Information Screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e34dda5a-3766-4b17-9ad7-59812df6aed7)

* display warning under “Login & Contact Email Address section 

**Current email **
* displays current (old) email in read-only format

**Pending email**
* Displays new email in read-only format 

#### Change Login & Contact Email 
* same functionality as before

**Comment by klohman** [comment]
## Updated Email Flow 

* Edit Contact Information 
* Update email 
* App/cognito sends verification email to NEW email with a verification link

* Old email is still valid; user can log in with old email; service emails go to old email 
* new email is pending verification and user cannot log in with new email; service emails do not go to new email
* App displays warning message to verify new email 
* Old email is displayed as email in UI under Contact Information on dashboard and in all cases

**User clicks Verify Email**
* user clicks “Verify Email” link 
* if user is logged in, user is routed to a email verified success page (In DAWSON with link to log back in) 
* if user is not logged in, redirect to cognito login - they have to log with their old email, then we redirect them to the email verified success page 
 
* old email is now invalid; user cannot log in with old email; service emails do not go to old email 
* new email is valid and user can log in with new email; service emails now go to new email 
* New email displays in UI on dashboard and in all cases

**Comment by klohman** [comment]
## 7406 

#### 1) Practitioner updates email and saves form with valid email address 
* Login as practitioner 
    * privatePractitioner10@example.com
    * irsPractitioner10@example.com
* Update email address 
    * privatePractitionertest@example.com
    * irsPractitionertest@example.com
* Click Save 
* Re-enter matching email 
* Click Continue on modal 
Expected results 
On click of Save 
- [ ] Verify email modal displays 
- [ ] On click of OK on modal, App routes to Dashboard with success message displayed “New email has been added and is awaiting verification.”
- [ ] Verification email is sent to new email 
- [ ] Old email is still valid 
- [ ] Practitioner old email still displays under My Contact Information 
- [ ] Practitioner old email still displays under all cases
- [ ] Global warning message displays 

#### 2) Practitioner updates email and saves form with invalid email address 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [ ] Error displays on email field - “Enter a valid email address” 

#### 3) Practitioner updates email and saves form with duplicate email address 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Savel 
Expected results 
- [ ] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Practitioner updates email files a document before verifying new email 
* Login as practitioner 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
* Click Edit on Contact Info card 
* Update email address
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
* Go to case 
* File a Motion for New Trial 
Expected results 
- [ ] Motion for New Trial is added to Docket Record 
- [ ] New email address does not receives service email 
- [ ] Old email does receives service email 

#### 5) Practitioner updates email and cannot login with new email address before verifying email
* Scenario 4 
* Login as practitioner with new email 
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
Expected results 
- [ ] User sees error on login for invalid credentials 

#### 6) Practitioner updates email and can login with old email address before verifying new email
* Scenario 4 
* Login as practitioner with old email 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
Expected results 
- [ ] User is able to login 
- [ ] Global warning to verify email is displayed 
- [ ] Old email displays under contact info on dashboard and in all cases

#### 7) Practitioner updates email and receives service for court-issued document at old email before verifying new email 
* Scenario 4 
* Login as docket clerk 
* Go to case 
    * Case has private practitioner flexionustc+emersongreen@gmail.com 
    * Case has irs practitioner flexionustc+IRS@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [ ] order to show cause is added to Docket Record 
- [ ] New email address does not receive service email 
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
- [ ] Old email receives service email 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com 


#### 8) Practitioner updates email and enters non-matching email on confirmation 
* Login as private practitioner / irs practitioner 
* Click Edit on Contact Info card 
* Update email address = firstemail@email.com
* Click Save 
* Re-enter non-matching email = secondemail@email.com
* Click Continue on modal 
Expected results 
- [ ] Error displays on email field -  “Email addresses do not match.”

#### 9) Practitioner verifies new email and logs in with new email 
* Scenario 4 
* Go to gmail 
* Click Verify Email link 
* Click login on success page
* Login as practitioner
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
Expected results 
On click of verification link:
- [ ] User is routed to Email Verified success page 
On login: 
- [ ] Login is successful 
- [ ] App displays new email on  Practitioner dashboard with all associated cases 
- [ ] Global warning message is not displayed

#### 10) Practitioner verifies new email and files a document 
* Scenario 9 
* Go to case
* File a Document 
    * Administrative Record 
* Submit document
Expected results 
- [ ] Administrative Record is added to the docket record 
- [ ] new email receives service email 
- [ ] Old email does not receive service email 

#### 11) Practitioner verifies new email and receives service email for court-issued document 
* Scenario 9 
* Login as docket clerk 
* Go to case 
    * Case has private practitioner flexionustc+emersongreen2@gmail.com 
    * Case has irs practitioner flexionustc+IRS2@gmail.com
* Create, sign and serve Decision 
Expected results 
- [ ] Decision is added to the docket record 
- [ ] new email receives service email 
- [ ] Old email does not receive service email 

#### 12) Practitioner verifies new email and cannot log in with old email 
* Scenario 9 
* Login to system with old email
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
Expected results 
- [ ] Login is unsuccessful and error message is displayed

#### 13) Practitioner verifies email when not logged in to system 
* Scenario 1 
*  Log out of system 
* Go to email 
* Click verify email link
* Login 
Expected results 
On click of verify 
- [ ] user is routed to cognito log in
- [ ] user can log in with old email 
- [ ] user cannot log in with new email 
On login, 
- [ ] Verify email warning message is no longer displayed
- [ ] new email is displayed in UI on dashboard and in all cases 
- [ ] new email receives service emails 
- [ ] user can log in with new email

**Comment by klohman** [comment]
## Update to Global Warning 

* OK to move warning above page title bar so that it will appear on all screens

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/84c0688b-4b46-4cd0-86c3-c3a7dc536f5a)

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8e4701c0-c7eb-47cf-8f32-302b2d99fecc)

**Comment by JessicaMarine** [comment]
PO Review: 
* My Contact Info still showing on practitioner's dashboard:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a4e3f4ec-80e3-498e-8284-4fea51ab329e)
