### ISSUE TITLE
Quarterly Manual Testing - Tech Mob

### ISSUE THREAD

**Issue by klohman** [flexion/ef-cms#7758]
## Acceptance Criteria 

AC 1) Team has performed manual testing on the Court migration environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing

* Mobile - Rae + Mrin
* Stip Decision flow - Mrin
* Correspondence File - Rae
* Public Users - Rae

## Tasks (Draft)
- [ ] Complete steps in Test Matrix (as assigned)
- [ ] Document any test failures in Test Matrix
- [ ] Validate / reproduce bug (pair with Kristen) 
- [ ] Log bugs in Zenhub 

## Definition of Done 
- [ ] All tests cases have been performed on the Court's migration environment 
- [ ] All bugs discovered have been logged in Github
