### ISSUE TITLE
Party Redesign - Parties Tab - Docket / Petitions / Admissions View

### ISSUE THREAD

**Issue by klohman** [flexion/ef-cms#8112]
As DAWSON user, I need party information to be organized more intuitively so that I can locate information more easily.

## Pre-Conditions
* Case has multiple petitioners, an intervenor or participant, and petitioner counsel

## Acceptance Criteria
* Counsel (petitioner and intervenor/participant) should be visually tied to the representing petitioner. 
* Other filers (intervenor/participants) should be easily identifiable. 
* Existing functionality still exists and has been tested (List flows to test)

## Mobile Design/Considerations
* All information needs to be accessible on mobile 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- Consider potentially refactoring `OtherContactType` entity to use `Petitioner` and add 'participant' and 'intervenor to 'CONTACT_TYPES'
- Confirm that new view eliminates this bug https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7241

## Tasks
Internal only so far
- [x] Replace Petitioner, Respondent, and Other horizontal tabs with one Parties tab - Mob (#8242)
  - [x] Create Petitioner(s) & Counsel, Intervenor/Participants & Counsel, Respondent Counsel vertical tabs under new Parties horizontal tab
  - [x] Default to Petitioner(s) & Counsel tab
- [x] Petitioner(s) & Counsel - Mob (#8240, #8241)
  - [x] Move petitioner information to cards, move (abbreviated) petitioner counsel info to same cards
  - [x] Move add counsel search bar to top of page
  - [x] Move Add Petitioner button next to search bar, rename to Add Party
- [x] Intervenor/Participants & Counsel - Mob (#8246)
  - [x] Hide when there are no intervenors/participants on case
  - [x] Move intervenors/participants information (from Other) to cards, move (abbreviated) intervenors/participants counsel info to same cards 
  - [x] Move add counsel search bar to top of page
  - [x] Add Add Party button next to search bar
- [x] Respondent Counsel:
  - [x] Move respondent counsel info to cards (from Respondent tab)

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
## Parties Tab  (Docket & Admissions view) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/80fe3121-c02b-463d-be91-d0f2e266409d)

**Parties & Counsel tabs**
Display vertical tabs:
 Petitioner(s) & Counsel 
Intervenor/Participants & Counsel
Respondent Counsel 
Petitioner(s) tab is selected by default 
On click of a tab, display tab content 


### Petitioners & Counsel tab 
Display Add Counsel search bar at top 
Display “Add Party” button

**Add Party**
on click, route to Add Party form

#### Petitioner card 
Separate card for each petitioner 
Display Additional Name field (if applicable) above Mailing Address Line 1

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “Edit” link for each counsel 
On click of Edit link, app routes to Edit Counsel form

**Comment by klohman** [comment]
## Edit Petitioner Counsel form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/afc1563f-cd18-4eda-ae53-d1a523949aec)

**Replaces the current Edit Practitioner modal!**

Display Counsel information (read-only) 
Name (Bar number)
Address 
Phone number 
email 

**Representing**
Field is hidden for Respondent Counsel

For private practitioners:
Display all parties on the case (except Respondent) 
Represented parties are checked 

**Service preference** * Display current service preference 

#### On Save 
Changes are saved, and app routes back to Paarties tab with success message displayed 

#### Remove Counsel button 
On click, display Remove Counsel modal 


## Remove Counsel confirmation modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aad42fc2-7d46-4eb5-bbfd-4fc763afb1ea)

Display selected counsel Name (Bar number) in message

**On cancel**
 return to Edit Counsel screen

**On Yes, Remove**
Modal closes, app routes to Parties tab with success message 
Counsel is removed from case and no longer displays in UI 
Counsel no longer has party access to case and case does not display on counsel’s dashboard

**Comment by klohman** [comment]
## Add Party form 

**REPLACES “Add Petitioner” form** 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/045304ef-29e7-41d2-be3e-4c8937d6f9d6)

**Petitioner type**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a625665-cdd6-441f-8440-0fcd4ab84208)

Dropdown options include: 
Petitioner 
Intervenor (TBD #8132)
Participant (TBD 8133)

**Form content** * identical to current “Add Petitioner” 
 
#### On Save 
app routes to Parties screen with success message (no changes)
Party is added to case and displays in UI (no changes)

**Comment by klohman** [comment]
## Case Header Update- Represented Indicator 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7ca58f99-7e99-44c8-abf0-b4c40f6de6b5)

* Display "Represented" indicator if any party other than respondent (petitioner, intervenor, participant) is represented by counsel

**Comment by klohman** [comment]
## Parties Tab  (Non-Docket view) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e4c7faf0-9c05-4fcc-9201-030710e9a1f6)

**Parties & Counsel tabs**
Display vertical tabs:
 Petitioner(s) & Counsel 
Intervenor/Participants & Counsel
Respondent Counsel 
Petitioner(s) tab is selected by default 
On click of a tab, display tab content 


### Petitioners & Counsel tab 

#### Petitioner card 
Separate card for each petitioner 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/87a245b0-af68-4ffc-842c-80a5fe207845)


## Intervenor/Participants & Counsel tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9582bc59-9648-4a3d-a530-ac8b4a5745cf)#### Party card 
Separate card for each party 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays

## Respondent Counsel tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/50993694-a41a-4aa8-a54a-6eacf6c36d96)

#### Respondent Counsel card 
Separate card for each counsel 
Display info for counsel: 
Counsel name (Bar Number) 
Address 
Counsel phone number 
Counsel email 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]”

**Comment by klohman** [comment]
## 8112 Test Cases 

#### 1) Docket / admissions clerk views petitioner information 
* Login as docket clerk 
* Go to case 
    * Pro se 
    * With Counsel 
    * With c/o
    * With no email/ pending email / current email 
* Click Case Information > Parties 
Expected results 
- [ ] Petitioner & Counsel tab is selected by default
- [ ] UI displays updated design 
    * Pro se - Petitioner card displays “None” for counsel
    * With Counsel - Petitioner card displays counsel 
    * With c/o - Petitioner card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [ ] “Edit” links display for each petitioner 
* [ ] Add Party link displays 
* [ ] Add Counsel search box displays 
* [ ] Edit link displays for each counsel 

#### 2) Docket / admissions clerk views intervenor/participant information 
* Login as docket clerk 
* Go to case 
    * No intervenor/participant on case 
    * With intervenor/participant 
* Click Case Information > Parties 
* Click Intervenor / Participant tab 
Expected results 
No intervenor/participant on case 
- [ ] Intervenor/Participant tab is hidden 

With intervenor/participant on case 
- [ ] UI displays updated design 
    * Pro se - card displays “None” for counsel
    * With Counsel - card displays counsel name, email, phone
    * With c/o - card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [ ] “Edit” links display for each petitioner 
* [ ] Add Party link displays 
* [ ] Add Counsel search box displays 
* [ ] Edit link displays for each counsel 

#### 3) Docket / admissions clerk views respondent counsel information 
* Login as docket clerk 
* Go to case 
    * No respondent counsel 
    * With respondent counsel 
* Click Case Information > Parties > Respondent Counsel 
Expected results 
No respondent counsel 
-  [ ] Tab displays “There is no respondent counsel associated with this case.”

With respondent counsel 
- [ ] UI displays updated design 
    * card displays counsel name, address, phone, email, service
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [ ] “Edit” links display for each counsel

**Comment by JessicaMarine** [comment]
PO Review:
- The placement of the edit button seems to be off in 12738-18 in `mig`:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/4ab0008a-1342-457a-a1ff-217a4473fa4d)
- Were the test scenarios confirmed.  I don't see any of the boxes checked off?

**Comment by klohman** [comment]
Additional UX Review 

- When petitioner has a Pending email,  it displays in UI, but it also displays "No email provided". If email is pending, the pending email should display and the other state should be hidden
![Screen Shot 2021-05-12 at 11.57.42 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c0dc1c0a-0290-4c43-a7ee-8dadf9438435)
