### ISSUE TITLE
Docket Clerk: Add Intervenor to case

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#8132]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to add an intervenor to an existing case.
 
## Acceptance Criteria:
- Docket Clerk needs the ability to add an intervenor to a case. [Note: only 1 intervenor allowed per case]
- Once added to a case, the intervenor should be treated as a full party to the case.
  - Show in the UI
      - Under the "Parties" tab
      - Listed in the filing party list for eFiled documents and paper filings
      - Listed as a party to be represented in the "Request Case Access" screen
      - Shows under Parties to be Served on the "Add Docket Entry" screen
      - Paper service modal
~~- Printable docket record~~ (moved to separate story #8280)
     - Get paper service
 ~~- Have the party view of a case~~
   - Others?
- Once the intervenor is added to the case, they are "searchable" in the case, order and opinion searches

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add `Intervenor` party type to select on Add Party view
- [x] Add validation for `contactType.onChange`, if an Intervenor already exists on the case
- [x] After save, persist party tab (e.g. Petitioners/Counsel, Intervenor/Participants, etc.)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![Add Paper Filing.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/8704e300-f33d-436e-b6b0-ea7ccf1ff135)

Test case

- Logged in as docket clerk. Browse to a case
Create -> New Paper Filing

Expected results 
- [ ] Intervenor should appear under “Who is filing this document?” as (firstname lastname, Intervenor)

Additional UI Note
- [ ] To have the party(s) name treatment consistent, other parties should appear as (firstname lastname, partytype)
