### ISSUE TITLE
Order Search: Case Caption and Docket# section of DAWSON-generated/created content should be searchable content

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#8650]
As a user, in order to get consistent expected search results I would like the content in the Case Caption and Docket # portion of the Order document to be factored in when determining search results.

## Acceptance Criteria

- Text in the Case Caption portion of the Order document is searchable content
- Text in the Docket # portion of the Order document is searchable content
- Search remains performant
- Searching against this content does not require special operators or UI outside of standard Order search

Additional AC (per meeting with Chris 7/29/21)
* Locate an Order by an old case caption 
* Locate an Order by an old docket number 

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
When testing exact match search in the MIG environment, we noticed that legacy PDFs and uploaded/scanned Orders had their Caption and Docket # section indexed, and that content returned matches on keyword/phrase search. However, this is not the case for DAWSON-native or generated content. The Court would like Caption and Docket # content searchable as to make this uniform across all documentation.

Example: Docket 9261-17, search for the word "consolidated"; despite being in the Caption of all Orders on the docket, a search for that word only returns the documents NOT generated via DAWSON.

## Tasks
- [x] 1 Parse document contents from older system-generated orders - mob #8719
- [x] 2 Write test scenario setup - mob #8719

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Do users expect to search for newest caption or old captions?
Do users care about caption or are they wanting to search by party?

**Comment by mariahkannenberg** [comment]
Blocked - need to create test cases

**Comment by klohman** [comment]
## Draft Test Scenarios 

Order 1
- Welcome to flavortown - old case caption 
- Guy Fieri - new case caption 
- Order content does not contain Welcome to flavortown 
- Order title does not contain Welcome to flavortown 


Order 2
- 111-20 - old docket number 
- 111-20W - new docket number 
- Order content does not contain 111-20
- Order title does not contain 111-20 


- User searches for Order using exact match old case caption as keyword 

- User searches for Order using exact match current case caption as keyword 

- User searches for Order using a keyword and using exact match old case caption in Case title/Petitioner name field 

- User searches for Order using a keyword and using exact match new case caption in Case title/Petitioner name field 

- User searches for Order using old docket number as keyword 

- User searches for Order using current docket number as keyword 

- User searches for Order using a keyword and using old docket number in Case title/Petitioner name field 

- User searches for Order using a keyword and using new docket number in Case title/Petitioner name field 

- User searches for Order using non-exact match old case caption as keyword 

- User searches for Order using non-exact match current case caption as keyword 

- User searches for Order using a keyword and using non-exact match old case caption in Case title/Petitioner name field 

- User searches for Order using a keyword and using non-exact match new case caption in Case title/Petitioner name field

**Comment by klohman** [comment]
![Screen Shot 2021-08-05 at 4.19.56 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/069373e3-13d9-4482-b0c2-8689cd9e9b76)

**Test 2 & 6**
* "Guy Fieri" as keyword 
* returns Order 4 PDF Upload - PDF does not contain Guy Fieri. Guy Fieri is only in case title. 
* Does not return Order 3 PDF Upload - which does contain Guy Fieri 


![Screen Shot 2021-08-06 at 9.44.14 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1f5bb40-5e81-4ee0-89d0-54c7706db9bb)

**Test 3**
* Order on 1789-21 should not be returning. (Was this Order created before the last update? That may be the issue.)


![Screen Shot 2021-08-06 at 9.46.50 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/78042cc6-8aa1-4149-bf9a-81a249fc64eb)

**Test 11** 
* Order 8 should not be returning - 123-20W is on the PDF but the current docket number does not contain the W - is this how you want it to behave?

**Comment by klohman** [comment]
@cholly75 

Some info on the docket number field for searching: 

**Case Search - Docket number search**
- Strip offs all letters
- Strips out leading zeros 
- example: 123-20 will back 123-20W and vice versa

**Order Search - Docket number search**
- Does not strip off letters 
- Does not strip off leading zeros 
- Exact match only (123-20 will not bring back 123-20W orders)

**Comment by codyseibert** [comment]
While doing this work we found that some PDFs are scraped with additional spaces between the characters in words.  This is because the scrape code currently used is written to work well with a certain set of documents.  We saw that when Kristen created and order with word and tried to upload it, the contents was scraped like so:

{"documentContents":"\n\n Guy Fieri  \n      \n     , Petitioner               \n  \n V                                 10 3 - 21  \n  \n Commisioner of  inter nal re venue ,  \n  \n Respondent  \n  \n  \n  \n  \n  \n  \n  \n  \n ORDER   \n  \n T ha t magic  something  then  I   saw it. Welcome to flavortown, in bright lights.   103-21 Guy Fieri, Petitioner"}

attached are example orders created in word by Kristen which cause this strange parsing behavior.

[ORDER- 6 - 106-21 .pdf](https://github.com/flexion/ef-cms/files/6947767/ORDER-.6.-.106-21.pdf)
[ORDER- 7 - 106-21W .pdf](https://github.com/flexion/ef-cms/files/6947768/ORDER-.7.-.106-21W.pdf)
