### ISSUE TITLE
Notice of Change to In Person Proceeding

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9329]
As a docket clerk, so that I do not have to manually generate and serve needed documentation, I need DAWSON to generate and serve a Notice of Change to In Person Proceeding when a Trial Session with calendared cases has its proceeding type changed from Remote to In Person.

Depending on local circumstances, some calendared trial sessions are being changed from Remote to In Person. When this happens, docket clerks must create a docket entry and generate a Notice of Change To In Person Proceeding for all open cases that are currently assigned to that trial session, then serve said notice. We would like DAWSON to do this for them. 

[https://app.zenhub.com/files/152320868/8471202d-cd24-449e-ae75-a4a1d7d52de3/download](https://app.zenhub.com/files/152320868/8471202d-cd24-449e-ae75-a4a1d7d52de3/download)

## Acceptance Criteria
* When a calendared Trial Session with one or more active cases is edited to change the Proceeding Type from Remote to In Person, upon saving the changes to a Trial Session a Notice of Change to In Person Proceeding (NOIP) is generated for each open case currently attached to that Trial Session.
* The NOIP generated uses the template attached to this story and derives values from the Trial Session data:
  - Building Location: derived from the Courthouse Name data on the Trial Session
  - Address: derived from the Address 1 and Address 2 data on the Trial Session 
  - City, St, ZIP: derived from the City, State, and ZIP Code data on the Trial Session
  - Judge: derived from the Judge data on the Trial Session
  - [location]: derived from the Location data on the Trial Session
  - [date, graf 1]: derived from the Date of the Trial Session prior to the edit that changes the Proceeding Type to In Person
  - [time, graf 1]: derived from the Time of the Trial Session prior to the edit that changes the Proceeding Type to In Person
  - [day, date, graf 2]: derived from the current Date of the Trial Session
  - [time, graf 2]: derived from the current Time of the Trial Session 
* The NOIP is added as a docket entry to the docket record with the link text "Notice of Change to In Person Proceedings"
* The NOIP is immediately served via email to parties on the case with electronic service
* A print queue for NOIPs needing to be printed and served manually is presented to the clerk in the same way that the Notices Setting Case For Trial (NTDs) are upon calendaring a Trial Session

## Notes
* Event code: NOIP

## Tasks

- [x] Generate notice when trial session is changed from remote to in person
  - [x] Create notice document
  - [x] Add docket entry for document on cases
  - [x] Serve notice to parties
  - ~[ ] DOD: research and refactor the calendaredCases and userNotes that we removed from this PR (https://github.com/ustaxcourt/ef-cms/pull/2160/files)~ devex task

## Test Cases
* Case w/ parties receiving electronic service is calendared for Remote trial session; Trial Session is changed from Remote to IP; NOIP is generated and served electronically; NOIP appears on docket record
* Case w/ parties receiving paper service is calendared for In Person trial session; Trial Session is changed from Remote to IP; NOIP is generated and presented to clerk for printing and service; NOIP appears on docket record 
* Trial Session is changed from Remote to IP but the changes are not saved; no NOIP is generated for any cases
* Trial Session is changed from Remote to IP along with date/time values; NOIP is generated using all new values on Trial Session
* NOIPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
@cholly75 yeah that's fine to have it here

**Comment by ttlenard** [comment]
##Test Cases

#### 1) Case w/ parties receiving electronic service is calendared for Remote trial session; Trial Session is changed from Remote to IP; NOCIP is generated and served electronically; NOCIP appears on docket record

####2) Case w/ parties receiving paper service is calendared for In Person trial session; Trial Session is changed from Remote to IP; NOCIP is generated and presented to clerk for printing and service; NOCIP appears on docket record

####3) Trial Session is changed from Remote to IP but the changes are not saved; no NOCIP is generated for any cases

####4) Trial Session is changed from Remote to IP along with date/time values; NOCIP is generated using all new values on Trial Session

####5) NOCIPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session

**Comment by cholly75** [comment]
Updated template file to remove reference to time zone in notice text.
