### ISSUE TITLE
Parties: Upload doc and provide information about document at time of upload

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#936]
As a Petitioner, Practitioner or IRS Attorney, in order to provide the Court with additional information about the document I am filing, I need to provide specific information.

When a Party is filing a document in a case, they need to provide certain information to the Court about each filing.  That information includes: the party or parties filing the document, whether a certificate of service is included and the service date, whether attachments or exhibits are included, and whether there are objections by other parties or counsel.

## Pre-Conditions:
* Party has indicated they want to file a document

## Acceptance Criteria:
* Parties can see where to upload the document
* Parties can upload the document
* Parties are reminded to redact all PII from the document and that evidence should not be submitted until trial
* Parties must select the party or parties filing the document. 
* Parties must indicate whether a certificate of service is included and the service date.
* Parties must Indicate whether attachments or exhibits are included. [Note: Exhibits and attachments must be included in the same electronic file as the document being filed]
* For all motions, Application to Take Deposition, and Substitution of Counsel, Parties must Indicate whether there are objections by other parties or counsel. This question is **NOT** needed for any other documents.
* Parties must indicate where there are any supporting documents for the document(s) they are filing.  If so, the parties should be able to upload those supporting documents and they should upload as separate docket entries.

## Notes:
* Pages 55-61 of Guide to eFiling (publicly available) shows how the Court currently does this: https://ustaxcourt.gov/eaccess/Petitioners_Guide_to_eAccess_and_eFiling.pdf

## Tasks:
- [x] Validation
  - [x] 1 Code: Revisit entities for validations (William #1364, #1370)
  - [x] 2. Code: Validation Interactor (William #1365)
  - [x] 3. Code: Sequences for validation (William #1365)
  - [x] 8. Code: Validation for party selection requirement (William #1378)
  - [x] 9. Update error messages (William #1397, #1398)
- [x] 4. Code: Create Views (Rachael/Kris #1357)
- [x] 5. Code: Integrate Views with Sequences (Rachael/Kris #1368)
  - [x] 6. Code: Submission Sequence Integration (William #1375)
  - [x] 8. Code: Add Validation Sequence to the inputs (William #1372)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Add relevant fields to File a Document page [Kristen / Sarah]
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt (#1379)
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
# File a Document Form

## Type of Document You're Filing 

*Placeholder text is denoted in red*
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ca68c4e2-dfb4-49de-b939-85811068f2aa) 

- Display the full concatenated document name 
  * concatenation is based on the fields required as part of story #980 

## Tell Us About the [Name of Primary Document] 
* [Name of Primary Document] should be populated by the full concatenated document name 

#### Upload Your Document 
* Field is required 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f47902a3-ef5e-4fe6-a047-c52ea914512f)

#### Primary Supporting Document 
* Do You Have Any Supporting Documents for this FIling? 
   - unselected by default 

   - If ‘Yes’ is selected,  show the Select Supporting Document dropdown 

* “Select Supporting Document”
     - Field is required  
      - Dropdown is populated with the following options
![Screen Shot 2019-03-28 at 2.18.44 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/17700de7-cc51-4f19-a344-fb1d2dac4df0)

If "Memorandum" or "Brief" is selected, show the Upload Your Supporting Document field (required) 

If Affidavit, Declaration, Unsworn Declaration Under Penalty of Perjury is selected, show the Upload Your Supporting Document field (required) and the "Supporting Document Signed By" field (required) 

##### Supporting Document Concatenation 
- Supporting documents should display as [Document Type] [Text field] [ Primary Document Name] 
Examples: 

* “Affidavit of John Smith in Support of Motion for Leave to File a Proposed Stipulated Decision”
* “Brief in Support of Motion for Leave to File a Proposed Stipulated Decision”
* “Declaration of John Smith in Support of Motion for Leave to File a Proposed Stipulated Decision”
*“Memorandum in Support of Motion for Leave to File a Proposed Stipulated Decision”
*Unsworn Declaration of John Smith Under Penalty of Perjury in Support of Motion for Leave to File a Proposed Stipulated Decision

#### What Are You Including With Your [Primary Document]
* all fields in this section are required 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9b8e68bd-06b0-4f57-b16c-4aae4900b831)

**Certificate of Service** 
* If 'Yes' is selected for certificate of service, display the Date of Service field 
- Date field validation - validate for correct format and not in future 

**Exhibits, Attachments, Objections**
* Selections from these fields needs to be captured - to be used in docket entry 


#### Tell Us About the [Name of Secondary Document] 
* This section will only display for Nonstandard H documents 

* [Name of Secondary Document] is displayed as full concatenated document name for the selected secondary document 
* Uploaded secondary document should be captured as "LODGED" (will be used in docket entry)

**Motion for Leave to File**
If Motion for Leave to File is the primary document: 
* "Upload Your Document" for secondary document is OPTIONAL  
* Do You Have Any Supporting Documents for This Filing? radio set is OPTIONAL 

**Motion for Leave to File Out of Time**
* "Upload Your Document" for secondary document is REQUIRED 
* Do You Have Any Supporting Documents for This Filing? radio set is REQUIRED 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aaf551a4-3de0-4931-ab92-3bc1ec7c87a8)

 If ‘Yes’ is selected,  show the Select Supporting Document dropdown 

* “Select Supporting Document” , "Upload Your Supporting Document," and "Supporting Document Signed by" - see functionality documented in primary document section 
* Secondary Supporting Documents should be captured as "LODGED" (will be used in docket entry)

##### Tell Us About the Parties Filing This Document 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8bc414db-ddcd-48e9-8213-85e85c5dc489)  

* Selections should include all parties defined in the case (i.e. Primary and Secondary Contacts, and Respondent)
* Primary and Secondary Contacts should display as [Name of Secondary Contact] etc.
* Respondent should display as "Respondent" 
* Primary Contact is selected by default and is not editable 
* Selections made in this field needs to be captured to be displayed on docket entry 


#### Data Persistence

* In the next story for Review and Submit the user shall be able to click a link and view the uploaded PDFs BEFORE they have been committed to the Docket Record. See Story 302.
* Selections in Parties, Exhibits, Attachments, Certificate of Service date, and Objections are shown as discreet chunks of information in an aggregated docket entry string. See example and Story 937.
  
Docket Entry Example from Story 937
EXAMPLE ONLY

[Title of Document] by [Filing Party] [(Exhibit(s))] [(Attachment(s))] [(Objection/No Objection)] [Certificare of Service date] [(LODGED)]

Unsworn Declaration of John Smith Under Penalty of Perjury in Support of Motion for Leave to File a Proposed Stipulated Decision by Petr. John Smith, Petr. Patty Smith, Resp. (EXHIBIT(S)) (ATTACHMENT(S)) (NO OBJECTIONS) (C/S 09/30/2018) (LODGED)

**Comment by klohman** [comment]
# Updated Parties Info 4/10

## Tell Us About the Parties Filing This Document 

* Default view 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f1d1459e-e90d-4a82-b94f-7603a27710ae)

**Are Other Parties Filing This Document With You? - field** 
  * Field is required 
  * On 'yes' , display "Who Else is Filing This Document" field 

**Who Else is Filing This Document field**
  * Field is required ONLY if the above 'yes' radio is selected 
  * Checkbox options include 
     * Secondary Contact (displayed as Secondary Contact Name - same as on Case Info tab)
       - Secondary Contact is an option ONLY when the party type is "Petitioner and Spouse" or 
          "Petitioner and Deceased Spouse" 
    * Respondent - displayed as "Respondent"
