### ISSUE TITLE
Court: Docket entry format

### ISSUE THREAD

**Issue by JessicaMarine** [flexion/ef-cms#937]
As the Court, in order to maintain consistency across all filings in the docket record, I need the docket entry for a new document to include specific information in a specific format.

The Court currently uses a format of Concatenated Document Title (C/S 04/17/2019) (Exhibit(s)) (Attachment(s)) (Objection) (Lodged) on all external filings. Keeping the format consistent across all filings in the docket record makes it easy to read.

## Pre-Conditions
* A Party has successfully filed a document.

## Acceptance Criteria
* The docket entry is populated based on Court-provided rules [See below for sample docket entry format]
* Document title is a hyperlink to the actual document.
* Each docket entry should include a sequential docket entry number 
* Each docket entry has the associated event code (derived from document type)

## Notes
* Court is not bound to All caps for document title
* Court currently uses "Exhibit" or "Exhibits" to differentiate between one or more exhibits.  The Court is not bound to this current practice and "Exhibit(s)" is fine for all instances where one or more Exhibits are attached to a document.  Same thing for "Attachment(s)".

## Tasks

Engineering
- [x] 1. modify formattedCaseDetail for filings & proceedings strings, date formatting, filed by strings (Rachael #1450)
  - [x] 1a. add isPaper boolean to document (Rachael #1450)
- [x] 2. update view for desktop (Rachael #1442)
  - [x] 2a. update responsive view (Rachael #1422)
- [x] 3. Document Metadata (William, Kris #1440)
  - [x] 3a. Add event code to document metadata upon creation
  - [x] 3b. ~~Ensure petitions have event code~~ (save for #992)
  - [x] 3c. Add 'lodged' property 
  - [x] 3d. Normalize parties across documents
- [x] 4. verify functionality when docket record number change updates order of the docket record (William)
  - [x] 4a. assign numbers to docket record entries upon creation? (William #1454 #1456)
- [x] 5. make docket record table fixed height and scrollable - possibly with fixed header (Rachael #1452)
- [x] 6. Fix order in which Petition document and Request for Place of Trial are added to the docket record (Rachael #1455)
- [x] 7. Show 2 docket record table view options on mobile temporarily for practitioner usability testing (Rachael #1459)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
  - [x] Local Seed data up to date with latest changes (William #1463)

**Comment by JessicaMarine** [comment]
[Sample Docket Record.pdf](https://github.com/flexion/ef-cms/files/2962366/Sample.Docket.Record.pdf)

**Comment by sarahridgway** [comment]
Per Jessica, (LODGED) is appended to the end of the docket entry in which the file has been lodged (instead of filed).

Format: [Title of Document] by [who filed it] [(Exhibit(s))] [(Attachment(s))] [(Objection/No Objection)] [C/S date] [(LODGED)]

**Comment by klohman** [comment]
## Updated Docket Entry table and format 

**These changes applies to the docket record for all internal user views AND external users (petitioner, practitioner, respondent).**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dbb657d9-82a3-449b-a606-11914883cd52)

## Style/Formatting 
- Docket record table is 500px height with vertical scrolling if entries exceed that height
- Table border - ##D6D7D9;
- Header label font - 17px, #212121, weight-600 
- Regular table font - 14px, #212121, weight- normal 

**Sequence Number**
* each new docket entry receives a sequential number in the record 

**Date**
* External filings- date the document was submitted / filed 
* Internal - “Date Received” field (hold for #992)

**Event**
* event code for document type - see GoogleSheet (https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing)


**Icon Column- No Label** 
* fas.fa-file-alt ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e810b030-3a72-4a4b-9a77-5907e2ae5f39)
    * Show icon for documents received in paper (i.e. filed by docket clerk - see #311 and #992) 


**Filings and Proceedings** 
* Format for displaying filing: 
	[Concatenated Document Title (C/S 04/17/2019) (Exhibit(s)) (Attachment(s)) (Objection) (Lodged)

* Concatenated Document Title- full document name concatenated in #980- displayed as link
  - For internal users, on click of link, navigate to Document Detail page 
  - For external users, on click of link, open PDF document in new tab 
* C/S MM/DD/YYYY - Show ONLY if ‘yes’ to certificate of service question 
* Exhibits - Show ONLY if ‘yes’ to exhibits question
* Attachments - Show ONLY if ‘yes’ to attachments question
* Objection - Show ONLY if ‘yes’ to objections question 
* No Objection - Show Only if “no” to objection question 
* Lodged - Show ONLY for secondary documents and secondary supporting document 

**Filed By**
* Display the parties who filed the document 
* If filed by Petitioner- show Petr. [Primary Contact Name]
* If filed by Respondent - show Resp. 
* If filed by both petitioner and respondent- show Resp. & Petr. [Primary Contact Name]
* If filed by more than one petitioner (For party type Petitioner and Spouse and Petitioner and Deceased Spouse), show Petrs. [Primary Contact Name] [& Secondary Contact Name]

**Action**
* TBD in later story 

**Served**
- Displays service date (TBD in later story) 

**Parties**
- Displays indicator of the parties being served (TBD in later story)
    - “P” - petitioner(s) only 
    - “R” - respondent only 
    - “B”- all parties
