### ISSUE TITLE
Court: Offboard Judge 

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9480]
As a court user, so that information does not get incorrectly assigned, I need DAWSON to reflect that Judge Guy has retired.

Judge Guy has retired from the USTC effective 3/31/22. There are several places in the application that need to be updated to reflect this, so that new case information does not get incorrectly assigned or potentially ignored. We need to remove the ability to assign data to Judge Guy or his Chambers, while preserving data already associated with same.

## Acceptance Criteria
* Remove Judge Guy from the Judge dropdown menu on the Session Assignments section of the Create Trial Session screen
* Remove Judge Guy from the Judge dropdown menu on the Session Assignments section of the Edit Trial Session screen
* Remove "Guy's Chambers" from the Select Chambers dropdown menu on the Create Message screen (appears after selecting "Chambers" on the Select a Section dropdown)
* Remove "Guy" from the Select Judge dropdown menu on the Run Case Inventory Report screen
* Remove "Guy" from the Filter By menu on the Deadlines report screen
* Remove "Guy" from the Show Items For dropdown menu on the Pending Report screen
* Remove "Guy" from the Judge's Name dropdown menu that appears when adding a Decision, Stipulated Decision, Order and Decision, and Order of Dismissal and Decision as a docket entry
* Judge Guy SHOULD still be selectable on all advanced search screen dropdowns for filtering by Judge
* Do not remove Judge Guy's name from any data currently associated with him

## Tasks
- [x] Update judge_users.csv so Guy's roles and section are legacy - Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Remove Guy from persistence method `getJudgesChambers` - Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Add integration test - Mrinalini, Rachel, Rosie https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Add script to be run for `test`, `mig`, and `prod` to update Guy's role and section - Rosie, Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2097
- [x] Run script vs. `exp2` then `test` to ensure it works as intended - Rosie, Mrinalini
- [x] Update smoketest - Rosie https://github.com/ustaxcourt/ef-cms/pull/2097

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by rosiehsmith** [comment]
Since `test`, `migration`, and `prod` environments do not get the script `bulk-import-judge-users.sh` run on deploy, we created a script to be run to update the offboarded judge users's role and section.

This script to be manually run on these environments is called `scripts/dynamo/offboard-judge-user.sh` and requires passing in the userId of the judge to offboard. Happy to assist in grabbing this if needed!

**Comment by ttlenard** [comment]
Tests all pass! Thanks all!
