### ISSUE TITLE
Consolidation: Identify Lead Case in UI

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9485]
As as DAWSON user, so that I can accurately make filings in the lead case in a consolidated group, I need to be able to easily identify which case is the lead case.

Sometimes petitioners with multiple separate cases before the Court will have those cases consolidated into a single group for purposes of adjudication. When this happens, those cases are considered a consolidated group.

When a consolidated group (CG) is created, one case in particular is designated as the "lead" case. This is always the case with the lowest docket number in the group and is considered the primary case in which docket entries must be created/filed. Currently to identify the lead case in a CG the user must navigate to the Case Information tab to determine the lead case in the group. To make this more user-friendly and to facilitate further improvements in the area of consolidation, we want the "lead" designation for a lead case to be signified somehow on the case header portion of the screen. 

## Acceptance Criteria
* Lead case in a consolidated group indicates that it is the lead case in the header portion of the case screen.
* When the lead case in a consolidated group changes due to modification to the consolidated group, the lead case indicator appears on the new lead case and is removed from the prior lead case
* Lead case assignment is done automatically upon consolidation of a group of cases
* Lead case designation appears on all CGs currently in the system as well as new CGs going forward

## Notes
* See UX mockups for research/approach

## Tasks
- [x] Add icon to case detail header when case is consolidated and is the lead case - Rosie, Rachel (https://github.com/ustaxcourt/ef-cms/pull/2143)

## Test Cases
* New consolidated group of cases is formed; lead case designation displays in the case header for the lead case
* Existing consolidated group: lead case displays designation in the case header
* Existing consolidated group: consolidated group has a case added that is a lower docket number than the existing lead case; lead case designation displays in the new lead case. Lead case designation is removed from prior lead case
* Existing consolidated group: lead case is removed from the group. Lead case designation is removed from the case; lead case designation is applied to the new lead case in the group

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Docket record - Lead case.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/fe35ef80-a2a5-4090-96bc-45d04df85040)

1. Display <lead case> tag in header next to docket number
2. Use existing header tag style
3. Display <lead case> tag as the first one if there are 2+

**Comment by ttlenard** [comment]
## Test Cases

#### 1) New consolidated group of cases is formed; lead case designation displays in the case header for the lead case


#### 2) Existing consolidated group: lead case displays designation in the case header


#### 3) Existing consolidated group: consolidated group has a case added that is a lower docket number than the existing lead case; lead case designation displays in the new lead case. Lead case designation is removed from prior lead case


#### 4) Existing consolidated group: lead case is removed from the group. Lead case designation is removed from the case; lead case designation is applied to the new lead case in the group

**Comment by rachelschneiderman** [comment]
While implementing this functionality, we weren't sure if the tag should show only for internal users or for both internal and external users. Waiting for PO to return from OOO to confirm which users should be able to see the tag.

**Comment by rosiehsmith** [comment]
UX Feedback to address:
- Expand the width of the case detail header portion that contains the docket number and tags so that they don't wrap to the next line as much
- If tags do end up wrapping, add some vertical space between the lines
- Case title to match the width of the docket number/tags section
This might look like: 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/16403861/167173341-75419cff-226b-4338-8dca-a4cf6d89fcb4.png">
