### ISSUE TITLE
Sealing E-mail Address

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9619]
As a _______, so that ________, I need ________.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Does sealing address seal both petitioner email address and petition email address?
- Sealing only seals that case and not all cases for that petitioner, correct? They would manually go into each case to seal if necessary?

**Comment by katiecissell** [comment]
UX Notes:

Figma File

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk updates the contact information for a petitioner with electronic service whose contact information has no current seal; The text for the checkbox to seal address has been updated.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Case Information tab
- Click on the Parties Tab
- Click on the edit link for a Petitioner (be sure that the address for this petitioner has not been sealed prior to this story)
- Review the page:

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The checkbox that used to say "Seal address" now displays "Seal contact information"



#### 2) Docket Clerk checks the box for Seal contact information; new modal displays.

- Continuing from the previous test
- Check the box for Seal contact information

Expected Results:
- [ ] **NEW FUNCTIONALITY** - A new modal displays that is titled, "Seal the following information for [Petitioner Name]?
- [ ] **NEW FUNCTIONALITY** - Modal displays the current Address, Phone number, Email address and Petition Email for the user.



#### 3) Docket Clerk clicks on the Close link in the top right of the modal; Modal closes; contact information is not sealed.

- Continuing from the previous test
- Click on the Close link at the top right of the modal

Expected Results:
- [ ] The modal closes and the user is navigated back to the Edit Contact info screen.
- [ ] The Edit contact information checkbox is not checked
- [ ] The address/email address of the petitioner is not sealed.



#### 4) Docket Clerk checks the box to Seal contact information; Clicks on the "No, Cancel" button; Modal Closes; Contact information is not sealed.

- Continuing from the previous test
- Check the box for Seal Contact information
- From the modal, click on the "No, Cancel" button 

Expected Results:
- [ ] The modal closes and the user is navigated back to the Edit Contact info screen.
- [ ] The Edit contact information checkbox is not checked
- [ ] The address/email address of the petitioner is not sealed.



#### 5) Docket Clerk checks the box to Seal contact information; Clicks on the "Yes, Seal" button; Modal Closes; Checkbox for the Seal contact information is checked.

- Continuing from the previous test
- Check the box for Seal Contact information
- From the modal, click on the "Yes, Seal" button 

Expected Results:
- [ ] The modal closes and the user is navigated back to the Edit Contact info screen.
- [ ] **NEW FUNCTIONALITY** - The Edit contact information checkbox is checked, cannot be unchecked per current functionality.



#### 6) Docket clerk clicks save on the Edit contact info page; user is routed to the Parties tab; Updated display for sealed contact information.

- Continuing from the previous test
- Click on the Save button

Expected Results:
- [ ] User is routed to the Parties tab of the Case
- [ ] **NEW FUNCTIONALITY** - The Petitioner card now has the email address of the user displayed in red text and it is indented with the sealed address info (see mock)
- [ ] **NEW FUNCTIONALITY** - If there was a Petition email, it is displayed in red text next to the red lock icon
- [ ] **NEW FUNCTIONALITY** - If there wasn't a Petition email, it displays "Not Provided" under the Petition email address header.



#### 7) Docket Clerk views a case in the system that already has a sealed address and the Petitioner has eAccess; email is now also sealed.

- Log in to DAWSON as a docket clerk
- Navigate to a case in the system that already had a sealed address, and the Petitioner also has eAccess (See Tenille - she has a list of cases)
- Click on the Case information tab, and then select the Parties tab
- Review the Petitioner card

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Petitioner card now has the email address of the user displayed in red text and it is indented with the sealed address info (see mock)
- [ ] **NEW FUNCTIONALITY** - If there was a Petition email, it is displayed in red text next to the red lock icon
- [ ] **NEW FUNCTIONALITY** - If there wasn't a Petition email, it displays "Not Provided" under the Petition email address header.



#### 8) Petitioner with one case that has a sealed address (and email) changes their email; NOCE is generated on the docket record and has "Sealed by Court Order" in the text of the NOCE.

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that you have only a single case associated with your account, and the case has a sealed email
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a NOCE on the docket record
- [ ] **NEW FUNCTIONALITY** - The text of the NOCE matches the "NOCE 3" example that is attached to this story



#### 9) Petitioner has 2 cases; One case has a sealed address (and email), and the other case does not have a sealed address (or email); Petitioner changes their email; 2 different NOCE's are generated.

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that you have only at least two cases associated with your account, and one case has a sealed email, the other does not have a sealed address
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record of both cases (the one with the sealed address and the one without the sealed address)

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Both cases have a NOCE on the docket record
- [ ] **NEW FUNCTIONALITY** - On the sealed address/email case, the text of the NOCE matches the "NOCE 3" example that is attached to this story
- [ ] **NEW FUNCTIONALITY** - On the case that does not have the sealed address/email, the NOCE is the standard NOCE that shows the old email + the new email



#### 10) Regression test - Petitioner with no sealed address/email changes their email; Standard NOCE is generated

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that none of the cases you are associated with have a sealed address/email
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record

- [ ] Standard NOCE is generated as per normal



#### 11) Admissions clerk adds in a new email for a Petitioner whose address is currently sealed; Email is automatically sealed and new NOCE is generated.

**Part 1**
- Log in as an Admissions clerk
- Navigate to a case where a Petitioner is currently receiving paper service, and their address is sealed (see Tenille for an example case)
- Click the Edit link on the Petitioner card
- Add in a new email for the Petitioner (be sure that you have access to this email address)
- Save the page
- Review the Petitioner card

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The pending email is displayed as sealed

** Part 2**
- Next, log out as the admissions clerk
- Go to your Petitioners email and log in to DAWSON and change the temp pw
- Navigate to the case

Expected Results
- [ ] **NEW FUNCTIONALITY** - There is a NOCE on the docket record
- [ ] **NEW FUNCTIONALITY** - The text of the NOCE matches the "NOCE 2" example that is attached to this story

**Part 3**
- Click on Case information tab and then select the Parties tab
- Review the Petitioner Card

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The address and email are not displayed, and the text states, "Address, Phone and email sealed" (the text "no email provided" is no longer displayed.
- [ ] Petition email address header and data are never displayed to external users

*Repeat the test above, but have the admissions clerk add the same email to a case where the address of the Petitioner is NOT sealed.
- [ ] Normal process occurs, standard NOCE is generated on the case



#### 12) Complete the tests above, but with the following roles instead of a Docket Clerk

- [ ] Clerk of the Court
- [ ] Case Services Supervisor



#### 13) Regression Tests:

- [ ] Petitioner without a sealed address changes their address/phone - Standard Notice of change is generated as per normal
- [ ] Petitioner with a sealed address/phone changes their address/phone - No Notice of Change is generated as per normal
- [ ] Admissions clerk adds in an email to a case without a sealed address - Standard processes occur and normal NOCE is generated and added to the docket record
