### ISSUE TITLE
Petitions Clerk: Summary of Orders to Be Generated During QC Process

### ISSUE THREAD

**Issue by uxforgood** [flexion/ef-cms#981]
As a Petitions Clerk, in order to keep track of what orders I need to issue after the QC process is completed, I need to see a summary of orders.

## Pre-Conditions:
* Petitions Clerk has QC'd a new Petition

## Acceptance Criteria

* The Petitions Clerk can easily see and print a summary of all of the orders that need to be issued
* Court users can return to the system at a later date and see the summary of orders
* If petition is recalled and QC form edited the summary displays the new list of orders

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* List of orders issued by petitions section - https://drive.google.com/file/d/13VqXTvxwB0Cb8VbU3H_WPhy6n4Zzl9gZ/view?usp=sharing
* Need to use the QC metadata to determine the list of orders that could be issued at this point
* Reminder - review Read-only view of the Document Detail tab - may want to include list of orders there.
* Printing is vanilla browser based printing

## Tasks
 - [x] 1) create summary view (with create order link) (Jojo #3123)
 - [x] 2) create interactor and proxy for fetching the orders (Cody)
 - [x] 3) actions and sequence for fetching orders and adding them to the state
 - [x] 4) add the link to the petition view to summary screen (Jojo #3127)
 - [x] 5) print orders needed summary view (Jojo #3131)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Jojo #3151)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo #3151)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment (Jojo #3153)

**Comment by uxforgood** [comment]
[PREVIOUS ITERATION OF IDEA, NOT FINAL DESIGN]

## Confirmation summary screen

- User can see confirmation message of the batching to IRS
- Case can be seen as changed to "Batched for IRS"
- User can see the summary of all changes made to the Petition
   - This is the delta of values between when the petitioner submitted the Petition and when it was batched to IRS (don't have to display any intermediary or temporary changes made between those two states)
- "View Petition" button would take them to the document detail view of the Petition (now in "read only" mode with ability to recall from IRS batch)
- "Back" breadcrumb returns user to Individual Work Queue
   - This Petition / work queue item is no longer in their individual queue Inbox, but now in their Sent box

￼![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/ff60d03f-3e68-4743-b286-8d80920269f1)

**Comment by uxforgood** [comment]
## Design and functional notes

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/038aca37-9ca8-442c-a8e2-ea28af223295)

### If order reminders are checked on Petition QC page

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/c7060060-13c4-4426-b35e-5d40fea1dc23)

- When user serves Petition to IRS, they are taken to the Orders Needed screen and see the success message
- Page displays a list of the order names that correspond to the checkboxes the user checked on the QC screen
    - Orders should appear in alpha order
- User can create an order from this page with the primary button
- User can print this summary screen (just using browser printing function after clicking on print link) - Don't need a print optimized view of screen


### If order reminders AREN'T checked on Petition QC page

- When user serves Petition to IRS, they are taken back to their Messages screen and see the success message (CURRENT destination after clicking sent to IRS)

**Comment by uxforgood** [comment]
## Test scenarios

#### Scenario 1 - view orders summary
1. log in as petitions clerk
2. navigate to new petition [note docket number for scenario 4]
3. check boxes for orders to be served
4. serve to IRS 

Expected result
- [ ] See Orders needed summary page listing all orders that were checked on petition qc
- [ ] See success message for petition batched for IRS
- [ ] Orders are listed in alpha order 

#### Scenario 2 - print orders summary
1. Continue scenario 1... click print link on orders needed page

Expected result
- [ ] Launch browser print interface so user can successfully print page 

#### Scenario 3 - no orders needed
1. log in as petitions clerk
2. navigate to new petition [note docket number for scenario 5]
3. serve to IRS

Expected result
- [ ] Navigate back to QC box 
- [ ] See success message for petition batched for IRS

#### Scenario 4 - viewing orders needed at a later time
1. Go to docket number from Scenario 1 and view petition
2. Click on View Orders Needed link

Expected result
- [ ] View Orders Needed link is present on petition page
- [ ] Clicking on link takes user to orders needed page

#### Scenario 5 - petition doc detail page with no orders summary link
1. Go to docket number from Scenario 3 and view petition

Expected result
- [ ] View Orders Needed link is NOT present on petition page

**Comment by alsmith1** [comment]
For printing the order summary. After much review and submitting the bug to chrome we do have a workaround. users must go to https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm and install the add on. Chrome is currently working on their end to fix the issue and it should be resolved before launch. It is a hight lift in work to design a workaround at this time.

**Comment by JessicaMarine** [comment]
10.4.19 PO Review:  
* The link for "View Orders Needed" needs to be there when the Petition is in "Batched for IRS" status.  Right now, if you navigate away from the list of orders, there is no way to get back to it until the Petition is actually served on the IRS

**Comment by alsmith1** [comment]
![Screen Shot 2019-10-04 at 5.12.05 PM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/8e0232ad-499f-4d8d-960b-6f382758251b)

**Comment by mariahkannenberg** [comment]
Scenario #6 - tested and working as expected. When a petition is recalled, the orders summary should NOT display because the user can modify the orders needed.
