### ISSUE TITLE
Docket Clerk: Ability to upload/file paper-filed external filing

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#992]
As a Docket Clerk, in order to get a paper document into a case, I need the ability to upload and file a paper-filed document.

The Court will continue to receive paper documents/filings from the parties, especially from pro-se Petitioners.  In order to get those paper-filed documents into the proper case, a Docket Clerk will need the ability to scan and upload the paper document into the electronic case.

## Pre-Conditions
* Docket Clerk has a paper document that needs to be filed in a case

## Acceptance Criteria
* Docket Clerk has the ability to search for doc type by name or code (see note below)
* Docket Clerk has the ability to upload a document into a case record
* Docket Clerk must provide all of the other information required for filing a document (#936), including whether a document should be filed or lodged
* Docket Clerk must be able to manually provide the "filed" or "lodged" date for each document
* Docket Clerk is able to add additional text that will be added to the document title on the cover sheet
* Docket Clerk is able to add additional text that will be added to the end of the docket entry
*  A docket entry is populated in accordance with Court-provided rules (#937)
* ~~The Docket Clerk can upload the associated document at time of docket entry creation or anytime thereafter~~ [holding for another story]
* After the Docket Clerk uploads the document, it is viewable to all parties and internal Court users on the docket record

## Notes
* Per Tina - a Docket Clerk should not need the drill down approach we are building for the parties.  A Docket Clerk should either know the doc code or be able to search for a known doc title/type. BUT, per Rhonda - a Docket Clerk needs the drill-down approach.  Let's show them both and decide!
* Per Rhonda: the Docket Clerks will not need any of the "Turbo-tax" like questions we utilized for Petitioners.  As long as they have all the fields they need to upload/file the paper document, we can dispense with the extra messaging.
* Consider revamping or tweaking the public upload functionality (search, etc). (needs to be in another story)
* Archived design documentation for previous iterations here: https://drive.google.com/open?id=1M0llL3azVw5H5wRLSxn5A2ZFLTgoFGsXYoqoSSdasyI

## Tasks
- [x] 1. Create "Add Docket Entry" button, sequence, route (kris #1564 )
- [x] 2. Create "Add Docket Entry" views 
  - [x] 2a. First iteration: primary w/o secondary doc and hardcoded doc type (use StateDrivenInput) (Rachael)
  - [x] 2b. Supporting docs screen (Rachael #1578)
  - [x] 2c. Integrate dynamic event code / doc type (William #1583 #1590)
  - [x] 2d. Show nonstandard forms if needed based on document type selected (Rachael/Kris #1597)
  - [x] 2e. Show secondary doc form if needed (Rachael/Kris #1598)
- [x] 3. Create Event Code / Document Type lookup component interaction (develop independent of first screen) (kris #1576 )
  - [x] 3a. update styling for select-react component (Rachael #1580)
  - [x] 3b. alter select menu to prioritize eventCode matches first when sorting (kris #1585)
- [x] 4. Docket Entry Entity validation rules
  - [x] 4a. Create Docket Entry Entity validation rules (primary) (William #1570)
  - [x] 4b. entity validation rules for secondary, primary supporting, secondary supporting
- [x] 5. Cleanup
  - [x] 5a. unselecting primary doc type (with X) does not remove secondary document dropdown (William #1603 #1610)
  - [x] 5b. secondary nonstandard form isn’t showing up (William #1604 #1610)
  - [x] 5c. additional info 1 should be appended to document name in docket record (Rachael #1617)
  - [x] 5d. additional info 2 should be appended to entire docket record entry (Rachael #1617)
  - [x] 5e. verify that practitioners are showing under parties filing (Rachael/Kris #1611)
  - [x] 5f. switch text on secondary button on supporting documents page (Rachael #1615)
  - [x] 5g. on supporting documents page, Affidavit and Declaration should have a field for “Supporting Document Signed By” (William #1612)
  - [x] 5h. hide Inclusions section on supporting documents if “Which Document is This Supporting?” is the secondary document (William)
  - [x] 5i. supporting documents should inherit filing status, date received, filing parties from the primary document (William #1609﻿﻿)
  - [x] 5j. secondary document should inherit date received, filing status, and filing parties from primary document (William #1609)
  - [x] 5k. add isPaper to documents so the paper filed icon shows up on the docket record (William #1607)
  - [x] 5l. Kristen reported a bug from a previous story that needs to be verified/fixed when cleanup is complete - "I'm seeing what could be a bug on the docket entries filed by Practitioner. We saw this during usability testing and I just confirmed. When a practitioner files a primary doc and supporting doc and selects "Myself..." and "Petitioner Name" as filing parties- they both show for the primary document, but only Petitioner is showing in Filed By for the supporting document. Whatever filed by is selected for primary should apply to both. See docket 1119-19L- under practitioner1"
- [x] 6. UX Review Items to Address
  - [x] 6a. Create updated internalFilingEvents.json from spreadsheet (kris #1637)
  - [x] 6b. Create NonStandard I entity, tests, getDocumentTitle func (kris)
  - [x] 6c. Create NonStandard J entity, tests, UI updates, computed updates, getDocumentTitle func
- [ ] 7. PO Review Items to Address
  - [x] 1. The upload of a paper document by a Docket Clerk should not create a new message thread.  There are a lot of unnecessary messages on 231-19 because each new document/docket entry is creating a new message. (Rachael #1672)
  - [x] 2. If you start typing text in the Additional Info. boxes and then erase it because it was a mistake, it throws an error when you try to submit the filing.  It does this on both the main document and supporting doc page. And, the error is not clear; it doesn't tell you what the problem is.  It took me several attempts to realize that's what was causing it. (William #1671)
  - [x] 3. If the Court has a paper Request for Place of Trial, that docket entry should be hyperlinked to the PDF that was uploaded.  This is treated differently than an electronic petition submission where we just listed the entry without hyperlink.
  - [x] 6. Design question -- and if this is a lot of effort, please ignore -- when you are adding a supporting document, it asks you which doc you are filing it in support of.  If there is only 1 doc (as in most cases), is this question even necessary?  Maybe the drop-down is only necessary where there is a primary & secondary doc in the case of Motion to Leave & Motion for Leave to File Out of Time. - Discussed with Kristen having the dropdown with the previous doc already selected if there is only one option (a simpler solution that will still reduce unnecessary clicks). (Rachael #1676)
   - [x] 4. Remove timestamp on coversheets generated from paper documents (William #1675)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning (William #1623)
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised

**Comment by klohman** [comment]
## Case Detail 

* Add “ Add Docket Entry” button for all internal users On click of “Add Docket Entry” button, navigate to “Add Docket Entry” screen 

## Internal Docket Entry Flow 

![docket_entry.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57d7e478-1d4c-45a9-842e-6f4c5b0f5bd8)

Flowchart available: https://www.lucidchart.com/invitations/accept/adb0def6-ce9c-49f2-b469-f42452e634da


## Add Docket Entry screen 

**Date Received**
* Field is required 
* Validation rules 
* Must be in correct date format 
* Cannot be in the future 
* Error Message when incomplete: “Enter date received.”

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2836627b-171c-4b91-bc96-bb3cc4eb234d)

**Event Code**
* Field is optional
* User can type in code (could be single letter) and press Select button
* If an exact match is found, the corresponding Document Type gets populated in the next form field (event code entered can remain in the search box) 
* If no matching document type is found, display error message under event code field: “That event code doesn’t exist. Please try again or select document type below.”

**Document Type**
* Field is required 
* If they’ve entered a valid event code this field gets populated and validation criteria is met
* Field contains a full list of all document types (See sheet 2 for the internal version of the document list -https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing)

* Depending on the document type selected, display the required additional fields (see #980)
* Dropdown needs autocomplete functionality - ability to enter and find partial words 
   - Example: https://jedwatson.github.io/react-select/
   - https://alphagov.github.io/accessible-autocomplete/examples/
* User can select dropdown arrow and scroll through selection box for full list of document types
* User can start typing and selection box will filter down options based on what they type
* Error Message when incomplete: “Select a document type.”

* Based on the Document Type selected, display the additional required fields for concatenation - defined in #980

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2516b7c8-545b-41c1-9f05-63ca27bdba5e)

**Who is Filing This Document**
* Required field - at least one party must be selected 
* Options include all parties, including respondent 
* Secondary Contact is an option ONLY when the party type is Petitioner and Spouse or Petitioner and Deceased Spouse
* Error Message when incomplete: “Select a filing party.”

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c2cfe85-8393-4a68-92f3-6b86f5c5cc33)

**Additional Info 1** 
* Field is optional 
* Text entered in this field will be appended to the Document Name in the Docket Record
* i.e. [Concatenated Document Name] [Additional Line 1 Text] [Exhibits(s)] [Attachment(s)] [Objections] [Lodged] [Additional Line 2 Text]

**Add to Cover Sheet**
* Is optional 
* If checked, the Additional Line 1 Text should display on the docket record and also show on the document’s cover page (Same format as on Docket Record)
* If unchecked, the Additional Line 1 Text will display on the docket record but NOT display on the cover page 

**Additional Info 2**
* Is optional 
* Text entered in this field will be appended to the entire docket record entry
* i.e. [Concatenated Document Name] [Additional Line 1 Text] [Attachments][Exhibits] [Objections] [Lodged] [Additional Line 2 Text]
* Additional Line 2 Text will display on Docket Record but will NOT display on document’s cover page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/23893344-2d4d-4962-a6d7-5a2e7957c20f)


**Inclusions**
* Selections are Optional 

**Certificate of Service** 
* If checked, Service Date is required 
* Validation - date must be in valid format and not in the future 
* Date field style - new styling component - Internal Date Field (see Figma style guide) 
* Placeholder text inside the date field should be cleared when field takes focus

**Exhibits** 
* If checked, [Exhibit(s)] will be appended to the docket entry (see #937)

**Attachment(s)**
*If checked, (Attachment(s)) will be appended to the docket entry (see #937)

**Supporting Document** 
*If checked, on click of “Complete Entry” - display “Add Supporting Document for Primary Entry” page later in the workflow

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1dda7a81-0408-4111-aaa5-e4dac2c8c62e)

**Objections**
*Field is displayed ONLY when document type is 
  - Any document in the Motion category 
  - Motion to Withdraw Counsel 
  - Motion to Withdraw as Counsel 
  - Application to Take Deposition 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ecbe6c84-5d1e-42d3-b844-c282b5d8d862)

**Add Document**
- Is optional 
- PDF will be uploaded upon click of “Complete Entry” button 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1b85b9ec-d9cc-4f77-ac5a-4a3f1423273d)

**Complete Entry button**

* Primary Document ONLY 
   - On click, docket entry is added to the docket record with the next sequential number 
   - Return to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below. “

* See additional comments for more scenarios

**Comment by klohman** [comment]
## Primary Document AND Supporting Document 

**On Click of Complete Entry button on Primary Docket Entry screen**
* On click, docket entry is added to the docket record with the next sequential number 
* Navigate to “Add Supporting Document for Primary Entry” page 
* Display success message “ Your entry has been added to the docket record. Continue adding related docket entries below” at the top of the “Add Supporting Document for Primary Entry” page

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/579601b7-7778-4bcb-8d92-a659c0eaa931)

### Add Supporting Document for Primary Entry Page
**Hidden Fields - Copied from Primary Document But Not Displayed**
* Date Received 
* Who is Filing this Document 

**In Support Of**
* Display (read-only) the name of primary document
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/80be968d-2a17-464b-9385-f36d3dc26004)

**Select Supporting Document**
* Field is required 
* Dropdown options include: 
   - Affidavit 
   - Brief 
   - Declaration 
   - Memorandum 
   - Unsworn Declaration
 
**Supporting Document Signed By**
Field is displayed and required ONLY when document type is Affidavit, Declaration, or Unsworn Declaration 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2321e332-aca5-4b4e-b6f5-cc76d7348e97)

**Additional Info 1**- see notes for primary document 
**Additional Info 2**- see notes for primary document 
**Inclusions**- see notes for primary document 
**Add Document** - see notes for primary document 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c6a05f9c-1822-433d-85a0-93da19bad48f)

**Complete Entry button**
* On click, docket entry is added to the docket record with the next sequential number 
* Navigate to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below.”

**Comment by klohman** [comment]
## Primary Document AND Secondary Document 

**On click of Complete Entry on Primary Docket Entry screen**
* On click, docket entry is added to the docket record with the next sequential number 
* Navigate to the “Add Secondary Docket Entry” page
* Display success message “ Your entry has been added to the docket record. Continue adding related docket entries below” on “Add Secondary Docket Entry” page

### Add Secondary Docket Entry screen**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/63fcb411-40c8-417a-bdd9-02a10022da2a)

**Hidden Fields - Copied from Primary Document but not displayed**
* Date Received 
* Who is Filing this Document 

**Document Type**
* Display secondary document type (read-only)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/57c7501a-705a-4fc9-a6d5-2e9c20f6697c)

**Additional Info 1**- see notes for primary document 
**Additional Info 2**- see notes for primary document 

**Inclusions**
* Supporting Documents 
    - If checked, “Add Supporting Document for Secondary Entry” to the flow 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7881755a-091a-4135-b19b-27c4c9f6abb4)

**On click of Complete Entry**
*  Add the secondary docket entry to the docket record
* If no supporting documents were checked for EITHER the primary or secondary documents, return to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below. “
* if a supporting document was checked for the primary document (or primary AND secondary), navigate to the Add Supporting Document for Primary Docket Entry page 
* If a supporting document was checked for the secondary document ONLY, navigate to the Add Supporting Document for Secondary Docket Entry page

**Comment by klohman** [comment]
## Secondary Supporting Document 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7beecc7a-5d3d-4cf5-bc99-0fbcab1dfb7e)

**Hidden Fields - Copied from Primary Document but Not Displayed**
* Date Received 
* Who is Filing this Document 


**In Support Of**
* Display (read-only) the name of secondary document 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3c93ac2e-b574-4bad-9da4-796956012f70)

**Select Supporting Document**
* Field is required 
* Dropdown options include: 
   - Affidavit 
   - Brief 
   - Declaration 
   - Memorandum 
   - Unsworn Declaration 

**Supporting Document Signed By**
* Field is displayed and required ONLY when document type is Affidavit, Declaration, or Unsworn Declaration 

**Additional Info 1**- see notes for primary document 
**Additional Info 2**- see notes for primary document 
**Add Document**- see notes for primary document 

**Complete Entry button**
* On click, On click, docket entry is added to the docket record with the next sequential number 
* Navigate to  the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below.”

**Comment by kkoskelin** [comment]
Updated react-select component website: https://react-select.com/home

**Comment by klohman** [comment]
# Updated Design 5/1 

## Case Detail
* Add “ Add Docket Entry” button for all internal users On click of “Add Docket Entry” button, navigate to “Add Docket Entry” screen
Add Docket Entry screen

**Add Document**
* Is required 

**Filing Status**
* field is required
* selection is defaulted to "Filed"
* If selection is changed to Lodged,
    * the primary document is flagged as Lodged and the (Lodged) notation will be added to the docket entry
    * Any supporting document for the primary docket is flagged as Lodged and the (Lodged) notation will be added to the docket entry 

**Date Received**
    * Field is required
    * Validation rules
    * Must be in correct date format
    * Cannot be in the future
    * Error Message when incomplete: “Enter date received.”

**Event Code**
    * Field is optional
    * User can type in code (could be single letter) and press Select button
    * If an exact match is found, the corresponding Document Type gets populated in the next form field (event code entered can remain in the search box)
    * If no matching document type is found, display error message under event code field: “That event code doesn’t exist. Please try again or select document type below.”

**Document Type**
    * Field is required
    * If they’ve entered a valid event code this field gets populated and validation criteria is met
    * Field contains a full list of all document types (See sheet 2 for the internal version of the document list -https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing)
    * Depending on the document type selected, display the required additional fields (see #980)
    * Dropdown needs autocomplete functionality - ability to enter and find partial words
    * Example: https://jedwatson.github.io/react-select/
    * https://alphagov.github.io/accessible-autocomplete/examples/
    * User can select dropdown arrow and scroll through selection box for full list of document types
    * User can start typing and selection box will filter down options based on what they type
    * Error Message when incomplete: “Select a document type.”
    * Based on the Document Type selected, display the additional required fields for concatenation - defined in #980

**Who is Filing This Document**
    * Required field - at least one party must be selected
    * Options include all parties, including practitioners and respondent
    * Secondary Contact is an option ONLY when the party type is Petitioner and Spouse or Petitioner and Deceased Spouse
    * Error Message when incomplete: “Select a filing party.”
**Additional Info 1**
    * Field is optional
    * Text entered in this field will be appended to the Document Name in the Docket Record
    * i.e. [Concatenated Document Name][Additional Line 1 Text] [Exhibits(s)][Attachment(s)] [Objections][Lodged] [Additional Line 2 Text]

**Add to Cover Sheet**
    * Is optional
    * If checked, the Additional Line 1 Text should display on the docket record and also show on the document’s cover page (Same format as on Docket Record)
    * •	If unchecked, the Additional Line 1 Text will display on the docket record but NOT display on the cover page
**Additional Info 2**
    * Is optional
    * Text entered in this field will be appended to the entire docket record entry
    * i.e. [Concatenated Document Name][Additional Line 1 Text] [Attachments][Exhibits] [Objections][Lodged] [Additional Line 2 Text]
    * Additional Line 2 Text will display on Docket Record but will NOT display on document’s cover page
**Inclusions**
    * Selections are Optional
**Certificate of Service**
    * If checked, Service Date is required
    * Validation - date must be in valid format and not in the future
    * Date field style - new styling component - Internal Date Field (see Figma style guide)
    * Placeholder text inside the date field should be cleared when field takes focus
**Exhibits**
    * If checked, [Exhibit(s)] will be appended to the docket entry (see #937)
**Attachment(s)* *
*If checked, (Attachment(s)) will be appended to the docket entry (see #937)

**Objections* *
* Field is displayed ONLY when document type is
    * Any document in the Motion category
    * Motion to Withdraw Counsel
    * Motion to Withdraw as Counsel
    * Application to Take Deposition

## Add Secondary Document 
    * Section is displayed ONLY when the following document types are selected as the primary document 
    * Motion for Leave to File 
    * Motion for Leave to File Out of Time 

**Add Document (Secondary Document)**
    * Is required 
**Additional Info 1 and Additional Info 2**
* Same functionality as for primary document 

**Save and Finish Entry button**
    * On click for Primary Document ONLY
    * docket entry is added to the docket record with the next sequential number
    * Return to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below. “
    
* On click for Primary and Secondary Documents 
    * docket entry for primary document is added to the docket record with the next sequential number
    * docket entry for secondary document is added to the docket record with the next sequential number
    * Return to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below. “

**Save and Add Supporting Document(s) button**
    * On click for Primary Document ONLY
    * docket entry is added to the docket record with the next sequential number
    * navigate to the “Add Supporting Document” screen with success message displayed: “Your entry has been added to the docket record. Continue adding related docket entries below.”

    * On click for Primary and Secondary Documents 
    * docket entry for primary document is added to the docket record with the next sequential number
    * docket entry for secondary document is added to the docket record with the next sequential number
    * navigate to the “Add Supporting Document” screen with success message displayed: “Your entry has been added to the docket record. Continue adding related docket entries below.”

**Comment by klohman** [comment]
## Add Supporting Document 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/07d5e62e-7c2f-4f0c-8eeb-02f330426ede)

**Add Document**
* Is required 

**Select Supporting Document **
- Is required 
- Dropdown includes the following options: 
    - Affidavit 
    - Brief 
    - Declaration
    - Memorandum 
    - Unsworn Declaration 

**Which Document is This Supporting**
- Is required 
- Dropdown includes the primary and secondary documents (if applicable) that were created on previous page 


**Supporting Document Signed By**
- Is ONLY displayed and required for these document types 
    - Affidavit 
    - Declaration
    - Unsworn Declaration

**Additional Info 1** * Field is optional * Text entered in this field will be appended to the Document Name in the Docket Record   i.e. [Concatenated Document Name][Additional Line 1 Text] [Exhibits(s)][Attachment(s)] [Objections][Lodged] 

**Add to Cover Sheet** * Is optional * If checked, the Additional Line 1 Text should display on the docket record and also show on the document’s cover page (Same format as on Docket Record) • If unchecked, the Additional Line 1 Text will display on the docket record but NOT display on the cover page 
**Additional Info 2** * Is optional * Text entered in this field will be appended to the entire docket record entry i.e. [Concatenated Document Name][Additional Line 1 Text] [Attachments][Exhibits] [Objections][Lodged] [Additional Line 2 Text] * **Additional Line 2 Text will display on Docket Record but will NOT display on document’s cover page**

**Inclusions**
* Field is ONLY displayed if the “Which Document is This Supporting” field is the PRIMARY document 
* Field is hidden if the document selected is the secondary document 

**Filing Status** 
* Field is not displayed in UI 
* Supporting document will inherit the filing status (filed or lodged) of the document it supports- 
    * i.e. If user selects “File” for the status for the Primary document, the supporting document’s status will be “File”
    *  If user selects “Lodge” for the status for the Primary document, the supporting document’s status will be “Lodge”

**Date Received**
* Field is not displayed in UI 
* Supporting document will inherit the date received of the document it supports
* Date received will display in the docket record for the supporting document 

**Who is Filing This Document (Filed By)**
* Field is not displayed in UI 
* Supporting document will inherit the “filed by” of the document it supports
* Filed By will display in the docket record for the supporting document 



**Save and Finish Entry button** * 
* On click:  * docket entry is added to the docket record with the next sequential number * Return to the Case Detail page with success message displayed - “Your docket entry is complete. You can view your entries in the docket record table below. “

**Save and Add Another Supporting Document” button** * 
* On click
* docket entry is added to the docket record with the next sequential number
* navigate to the “Add Supporting Document” screen with success message displayed: “Your entry has been added to the docket record. Continue adding related docket entries below.”

**Comment by klohman** [comment]
Paper Document indicator on docket record 

- An icon indicator should display on the docket entry for all documents received by paper (i.e., entered by a docket clerk)

![image](https://user-images.githubusercontent.com/18366192/57234396-7b1e6580-6fee-11e9-9234-ac99231fa333.png)

**Comment by klohman** [comment]
## Updated Button Set 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/45547abe-432b-4f0e-8309-d796e7294490)

- Updated language on buttons 
- Added "Cancel" link - on click, the entry is discarded and user is returned to the Case Detail page

**Comment by klohman** [comment]
# UX Review Notes 

Document Type List for Internal Users 
- updated list https://docs.google.com/spreadsheets/d/1RYGSnHJDP8_sg8aFjPQb_BAji-TQjKlTq2yTebLV7R4/edit?usp=sharing

ADMT - needed to create another nonstandard document type (Nonstandard I) 
    - Requires - ordinal number field - What Iteration is This Filing? 
    - Required - free text field - What is This Amendment For? 


SDEC - Stipulated Decision Entered 
- Needed to create another nonstandard doc type (Nonstandard J) 
    - Needs two free text fields 
    - First field is labelled Judge’s Name 
    - Second field is labelled “Decision Notes” 
    - Concatenation is “Stipulated Decision Entered [first field] [second field]”


Entry of Appearance and Substitution of Counsel need to be added to doc type list for internal users (see updated spreadsheet) 



Supporting document should inherit the filing status of the document it supports 
- Filed a secondary document (which is automatically lodged) but the supporting document is not showing lodged (docket 1169-19S #16-19)
- I filed a primary document as lodged (docket 1169-19S #20) and it showed the supporting document as Lodged 

Supporting document should also inherit the filing parties- 
- I selected Counsel and Petr. And it’s only showing petitioner for the supporting documents (docket 1169-19S #16-19)

**Comment by JessicaMarine** [comment]
5/10/19 QA review notes:
1. The upload of a paper document by a Docket Clerk should not create a new message thread.  There are a lot of unnecessary messages on 231-19 because each new document/docket entry is creating a new message.
2. If you start typing text in the Additional Info. boxes and then erase it because it was a mistake, it throws an error when you try to submit the filing.  It does this on both the main document and supporting doc page. And, the error is not clear; it doesn't tell you what the problem is.  It took me several attempts to realize that's what was causing it.
3. If the Court has a paper Request for Place of Trial, that docket entry should be hyperlinked to the PDF that was uploaded.  This is treated differently than an electronic petition submission where we just listed the entry without hyperlink.
4. The time on receipt on the cover page seems to be off between AM and PM.  I submitted most of the documents in 231-19 around 8am and the cover pages all read 8PM.  
5. Also, the time seems to be stuck on 8:00PM regardless of when I filed.  The Stipulation of Facts was filed at 8:05am, but the cover sheet still says 8PM.
6. Design question -- and if this is a lot of effort, please ignore -- when you are adding a supporting document, it asks you which doc you are filing it in support of.  If there is only 1 doc (as in most cases), is this question even necessary?  Maybe the drop-down is only necessary where there is a primary & secondary doc in the case of Motion to Leave & Motion for Leave to File Out of Time.  Thoughts?

**Comment by JessicaMarine** [comment]
5/13/19 QA review notes:
(1) there is now a upload tracker for internal users -- was that intentional? 
(2) the sort order of the table is off -- I added entries 22, 23, 24, and 25 today.  When sorted "by oldest" they should be in order, but are reading 23, 24, 25, then 22 
(3) I added additional line #2 information to the declaration (docket index #25), but nothing appeared on the docket record
