### ISSUE TITLE
CMS: Auto-serve externally filed documents (electronic)

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#993]
As a party in the case, so that other parties in the case may be served with my documents electronically, I need the system to auto-serve my document to the other parties. 

## Acceptance Criteria
* When externally filed documents are filed electronically, the system auto-serves the document to all parties in the case that have a "electronic" indicator for service
* The system should *NOT* automatically serve any document with "Simultaneous" in the document title [Note: These are manually served by Docket once all documents are filed]
* A service date is captured on the cover sheet at the time of service and is placed in the bottom center of the first page of the document when served
* The service date and parties served is captured on docket record (already done)
* Parties in the case who receive electronic service receive a service email (already done)
* Parties in the case can access the served document via the docket record (already done)
* If a new cover sheet is generated after the QC, the SAME served date is reapplied to the new cover sheet and document is *not* re-served

## Notes:
* Email integration for service on parties is in Epic #441. 
* No need to consider paper service because the party will do that on their own.

## Tasks
- [x] 1 Add service emails and set documents served in interactors for filing external documents (Rachael #3790) 
- [x] 2 Verify If a new cover sheet is generated after the QC, the SAME served date is reapplied to the new cover sheet (Rachael)
- [x] 3 add “Served” to bottom of coversheet, check font size (too big?) (Rachael #3794)
- [x] 4 filter out “Simultaneous” docs from being auto-served (Rachael #3794)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by rachaelparris** [comment]
### 993 Test Scenarios
Test data
- Create Case 1 as petitioner 1
  - Party type: Petitioner and Spouse
  - Add respondent 1 to case
- Create Case 2 as petitioner 1
  - Party type: Petitioner and Spouse
  - Add practitioner 1 to case
  -  Add respondent 1 to case


1) Auto-serve the document to all parties in a case that have “electronic” service indicator (filing as petitioner)
* Login as petitioner
* Navigate to case 1
* File a new Motion for Leave to File with a secondary document
Expected results
- [ ] Docket entries for the two documents are marked as served with the date/time and B for both parties
- [ ] Petitioner and respondent each receive two emails with the fully concatenated document titles for each document
- [ ] Served date is added to the bottom of the coversheet for each of the documents

2) Auto-serve the document to all parties in a case that have “electronic” service indicator (filing as respondent)
* Login as respondent
* Navigate to case 1
* File a new single document (not a Simultaneous document)
Expected results
- [ ] Docket entry for the document is marked as served with the date/time and B for both parties
- [ ] Petitioner and respondent each receive an email with the fully concatenated document title for the document
- [ ] Served date is added to the bottom of the coversheet for the document

3) Auto-serve the document to all parties in a case that have “electronic” service indicator (filing as practitioner)
* Login as practitioner
* Navigate to case 2
* File a new single document (not a Simultaneous document)
Expected results
- [ ] Docket entry for the document is marked as served with the date/time and B for both parties
- [ ] Practitioner and respondent (and not petitioner) each receive an email with the fully concatenated document title for the document
- [ ] Served date is added to the bottom of the coversheet for the document

3) Do not auto-serve a document with “Simultaneous” in the title
* Login as petitioner
* Navigate to case 1
* File a new Motion for Leave to File with Simultaneous Answering Brief as the secondary document type
Expected results
- [ ] Docket entry for the documents are not marked as served and the parties column is empty
- [ ] Petitioner and respondent do not receive emails for the two documents
- [ ] Served date is not added to the bottom of the coversheet for the document

4) Do not change the served date on the coversheet if a new coversheet is generated after QC
* Login as docketclerk
* Navigate to case 1
* QC one of the documents filed in scenario 1 by updating Additional info 1 and checking Add to cover sheet
Expected results
- [ ] Additional info is added to the coversheet
- [ ] Served date at the bottom of the coversheet is still present and does not change
