### ISSUE TITLE
Epic 3 Clean-up

### ISSUE THREAD

**Issue by mariahkannenberg** [flexion/ef-cms#996]
Epic 3 Clean-up

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Acceptance Criteria

**Log out Behavior**
* ~~After auto logout / session timeout, user sees a page-level error for a few seconds before the cognito login screen loads (SLR)~~ (Cannot reproduce- removed)
* ~~Modals can be invoked from pages even after auto logout / session timeout (SLR)~~ (Cannot reproduce)

**Documents**
* ~~Consider adding design cues to indicate that the docket table is scrollable~~ (Removed per Jessica)
* ~~Consider indicating file size on document detail page~~ (Removed per Jessica) 
* Change text on "uploading" docket record tag to "processing" 
* Add a remove option for supporting docs once selected on File a Document form 
* Concatenated doc name is not displaying correctly on Doc Detail page (see example for First Amended Petition) 
![Screen Shot 2019-09-30 at 9.27.14 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/98903602-0f82-431a-8769-1190e5cfc558)

**Filed By Date/Time** 
- [ ] All times should be displayed as hh:mm am ET (need to add ET to all displayed times) and drop the leading 0 when the time is a single digit (EXCEPT the time on the Add Trial Session form and Trial Session Detail screen)
- [ ] Update "Received" label on message thread to "Sent on" 
![Screen Shot 2019-08-15 at 12.15.14 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bfb5a2e1-3ee3-424c-9f81-4897ec45437a)
- [ ] For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread. 

**Navigation / Docket Header**
- [ ] The header on the printable docket record PDF viewer page - the docket number should be hyperlinked back to the case detail page - THIS IS A GLOBAL BEHAVIOR AND SHOULD BE CREATED AS A GLOBAL COMPONENT SO WE DON'T HAVE TO REMEMBER TO DO IT EACH TIME
- [ ] Caption edit link falling to third line on long case names￼￼

## Tasks
- [x] 1 Change text on "uploading" docket record tag to "processing" (Kristen #2808)
- [x] 2 Add a remove option for supporting docs once selected on File a Document form (William #3179)
- [x] 3 Concatenated doc name is not displaying correctly on Doc Detail page (see example for First Amended Petition) (William #3172)
- [x] 4 All times should be displayed as hh:mm am ET (need to add ET to all displayed times) and drop the leading 0 when the time is a single digit (EXCEPT the time on the Add Trial Session form and Trial Session Detail screen) (Kris #3185 )
- [x] 5 Update "Received" label on message thread to "Sent on" (William #3173)
- [x] 6 For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread.  (William #3184)
- [x] 7 The header on the printable docket record PDF viewer page - the docket number should be hyperlinked back to the case detail page - THIS IS A GLOBAL BEHAVIOR AND SHOULD BE CREATED AS A GLOBAL COMPONENT SO WE DON'T HAVE TO REMEMBER TO DO IT EACH TIME (Cody #3077)
- [x] 8 Caption edit link falling to third line on long case names (Rachael #3189)
- [x] 9 For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread.  (Verify that petition works the same way) (William #3192)
- [x] 10 Refactor storage of supportingDocumentCount in state - mentioned in #3179 (Rachael #3193)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/8e7e08f4-4ba6-4d62-97e0-f0c002001d61)

**Comment by JessicaMarine** [comment]
Design concepts for this (May need updates when we work this story)

Individual queue

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/14cfac59-72fa-4278-8886-e0a2946b9df3)

Section queue

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/6d4a8993-5a00-4b59-ac1a-717f72edd46d)

**Comment by sarahridgway** [comment]
Unhelpful history
 ![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/840a4e89-8648-49ac-94ad-819fd64360cb)

**Comment by sarahridgway** [comment]
Shows briefly before login screen after auto logout 

![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/e0ba2a77-8642-4056-b4bd-e87e765bdc6a)

**Comment by uxforgood** [comment]
New issue discovered during #1567

For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. 

The "Received" on the message is pulling the correct date (the date the docket record was created). To help reduce confusion, I recommend changing the label on the message card to say "Sent on" 

![image.png](https://images.zenhubusercontent.com/5bc8eb638ff5515ac40d1d90/b4c2cebc-db2f-43e9-909a-183062e6a834)

**Comment by uxforgood** [comment]
Printable docket record
- [ ] The header on the printable docket record PDF viewer page - the docket number should be hyperlinked back to the case detail page - THIS IS A GLOBAL BEHAVIOR AND SHOULD BE CREATED AS A GLOBAL COMPONENT SO WE DON'T HAVE TO REMEMBER TO DO IT EACH TIME

**Comment by klohman** [comment]
No Longer Relevant 
~~* Petitioner Dashboard sidebar background color is changed to F1F1F1~~
~~* Add hover state to secondary tabs as global convention (example: Parties, Case Info, IRS Notice)~~
~~* Search box text does not clear after clicking search on Chrome as of 04/26/19 (SLR)~~
~~* Consider filing instructions page or pdf for non-petition filings (SLR)~~
~~* Consider mobile view of petition filing instructions and other filing instructions if applicable (SLR)~~
~~* Change text color on yellow form field reminders to #212121 (SLR)~~
~~* Remove case status label for external users on File Document screens~~
~~* Consider whether to add doc title/code search bar for external filers (already built for internal Docket clerks) -- post-MVP?~~
~~* Make all dates 2-digit instead of 4 in year dates.For example, 01/02/19 instead of 01/02/2019~~
~~* Progress indicator bar goes past 100%~~
~~* Take `Petition` off the list of documents that can be filed as stand-alone docs~~

**Comment by klohman** [comment]
## New Design 

#### File a Document (external users) 

**Supporting Documents**
* On click of "Add Supporting Document" button, display Supporting Document 1 section 
* Add "Remove" link next to section header 
* On click of "Remove" 
   - Supporting Document fields are cleared/reset
   - Supporting Document section is hidden 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/27c6e297-236a-40fe-a489-ebb4c7a1246d)

* Supporting Document functionality should still allow up to 5 supporting documents to be added 

**Mobile View**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/77dae8d2-2ec0-4b5d-ad39-435e56716dd7)

**Comment by klohman** [comment]
## 996 Test Scenarios 

#### 1) User (all) sees “Session Timeout” screen after automatic session logout  
* Login as docketclerk1
* Navigate to Case Detail page 
* Inactive in system for [60 minutes]  
Expected Results 
- [ ] After 1 hour of inactivity, timeout modal warning displays 
- After 5 additional minutes of inactivity
- [ ] User is logged out of the app 
- [ ] User is navigated to the “Session Timeout” screen  

#### 2) External user is able to add and remove supporting document from their filing
* Login as petitioner 
* Navigate to Case Detail 
* Click File a Document 
* Select Motion for Leave to File, then Motion to Dismiss and continue
* Click Add Supporting Document button 
* Click “Remove”  
Expected Results 
- [ ] On click of “Add Supporting Document”, the Supporting Document 1 section displays, including “Remove” link
- [ ] On click of “Remove” link, Supporting Document 1 section is hidden 
- [ ] On click of Continue, no Supporting Document errors are triggered 

#### 3) External user is able to add and remove secondary supporting documents from their filing
* [Scenario 2]
* Click Add Secondary Supporting Document button
* Click “Remove” link for Secondary Supporting Document 1
Expected Results 
- [ ] On click of “Add Secondary Supporting Document”, the Secondary Supporting Document 1 section displays, including “Remove” link
- [ ] On click of “Remove” link, Secondary Supporting Document 1 section is hidden 
- [ ] On click of Continue, no supporting document errors are triggered 

#### 4) User (internal) sees full concatenated document title on Document Detail page
* Login as docket clerk1
* Navigate to Case Detail page
* Add Docket Entry 
* Select “Response”, then select [previous document] 
* Complete entry and click “Finish” 
* Navigate to document detail page
Expected Results 
- [ ] Document title displays as “Response to [previous document]” 

#### 5) User sees time displayed in “hh:mm am ET” format on messages 
* Login as docket clerk 1
* Send message to docket clerk 2
* Navigate to Document Detail page with new message 
Expected results
- [ ] Message “Sent on” displays as current time in format “hh:mm am/pm ET” 

#### 6) User sees time displayed in “hh:mm am ET” format in Petition document QC boxes 
* Login as petitioner1
* File a new petition 
* Login as petition clerk and view new petition in Document QC 
* Batch new petition for IRS 
* Serve petition 
Expected results 
- [ ] New petition “Filed” displays in format “hh:mm am/pm ET” in Petition Individual and Section QC Inbox 
- [ ] Batched petition “Batched” displays in format “hh:mm am/pm ET” in Petition Individual and Section QC Inbox 
- [ ] Served petition “Served” date displays in format “hh:mm am/pm ET” in Petition Individual and Section QC Inbox 

#### 7) User sees time displayed in “hh:mm am ET” format in Docket document QC boxes 
* Login as petitioner1 and navigate to case 
* File a document (any) 
* Login as docket clerk and view new filing in this case in Document QC Inbox 
* Navigate to Case Detail 
* Add incomplete docket entry (without upload) 
* View Document QC - in Progress 
* Navigate to incomplete docket entry and add document  
* View Document QC - Processed 
Expected results 
- [ ] New document “Filed” displays in format “hh:mm am/pm ET” in Docket Individual and Section QC Inbox 
- [ ] Incomplete docket entry “Filed” displays in format “hh:mm am/pm ET” in Docket Individual and Section QC In Progress boxes
- [ ] Completed docket entry “Filed” displays in format “hh:mm am/pm ET” in Docket Individual and Section QC In Processed boxes

#### 8) User sees time displayed in “hh:mm am” on Trial Session Detail page 
* Login as docketclerk1 
* Add New Trial Session, with start time 1:00 pm 
* Navigate to Trial Session detail 
Expected results 
- [ ] Trial Session start time displays as “1:00 pm” and does not include timezone  

#### 9) Docket Clerk adds a new docket entry with received date other than today’s date 
* Login as docketclerk1 
* Navigate to case 
* Add Docket Entry, with received date 10/01/2019 
* Complete entry, with document upload, and finish 
* View document detail page for new document 
* View Completed messages 
Expected results 
- [ ] “Filed by” date on Document Detail page is 10/01/19
- [ ] Coversheet displays “Received” date as 10/01/19
- [ ] Coversheet displays “Filed” date as 10/01/19
- [ ] Completed message for new document displays “Sent on” date as [today’s date]
