### ISSUE TITLE
Docket Clerk: Record Motion Disposition

### ISSUE THREAD

**Issue by cholly75** [flexion/ef-cms#9976]
As a , I need ________.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- If you edit disposition on motion, after the order was associated, does it need to flow through?
- Should we create a work item for somethings like if they strike it? If the disposition was granted, is there more we can automate for the user? 
- As a regular person/petitioner, is there more we can do to notify them of the results of their motion? (Email something?)

**Comment by katiecissell** [comment]
In the add/edit docket entry field for all orders a new checkbox should be added above the inclusion/attachments checkbox. 
- checkbox should say "This order disposes of a motion"
- If checkbox is selected two new fields should appear below the checkbox.
- The first is a dropdown box with the label: "What motion is being disposed?" . The dropdown should show the docket number and the name of any motions on the docket. 
- The second is a dropdown with the label "What is the disposition of the motion?"  The dropdown options should be Granted, Granted in Part, and Denied.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk navigates to a draft Order; Adds Docket Entry; New checkbox is present to indicate if the Order disposes of a motion.

*Pre-Conditions - Be sure that the case you are on has a few motions on the docket record.

- Log in as a Docket clerk
- Navigate to a case that has a signed Order in Drafts
- Click Add Docket Entry

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new checkbox that states, "This order disposes of a motion" that is below the "What is this order for?" field and the Inclusions header.



#### 2) Docket Clerk checks the box indicating that the Order disposes of a motion, two additional fields appear.

- Continuing from the previous test
- Check the box for "This order disposes of a motion"

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Two new fields appear: "What motion is being disposed of?" and "What is the disposition of the motion?"


#### 3) Docket Clerk Clicks Save and Serve; receives validation error.

- Continuing from the previous test
- Be sure that you leave the two additional fields blank
- Click the Save and Serve button

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User receives validation errors indicating that they need to select a motion to displose of, and the disposition.



#### 4) Docket Clerk selects a motion and the disposition for the Order; Saves and Serves Order.

**Part 1**
- Continuing from the previous test
- Click on the dropdown menu to select a motion that is being disposed of

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu displays the index number and Motion Name for each motion on the docket record.

**Part 2**
- Click on the dropdown for the disposition of the motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Selections include Granted, Granted in Part, and Denied.

**Part 3**
- Docket Clerk clicks save and serve.

Expected Results:
- [ ] Order is served appropriately



#### 5) The text in the Filings and Proceedings column for the original Motion on the docket record is updated

- Continuing from the previous test
- You should have a green confirmation banner
- Scroll down on the docket record and review the entry for the original motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing
- [ ] **NEW FUNCTIONALITY** - There is no Notice of Docket Change for the updated text on the Original motion.



#### 6) Docket Clerk edits an existing Order that is on the docket record of a case; Checkbox for This Order disposes of a motion

*Pre-Conditions - Be sure that the case you are on has a few motions and Orders on the docket record.

- Log in as a docket clerk
- Navigate to a case with the pre-conditions above
- Click on the edit link to edit an order

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new checkbox that states, "This order disposes of a motion" that is below the "What is this order for?" field and the Inclusions header.
- [ ] **NEW FUNCTIONALITY** - If the checkbox is checked, two new fields appear: "What motion is being disposed of?" and "What is the disposition of the motion?"



#### 7) Docket Clerk Clicks Save; receives validation error.

- Continuing from the previous test
- Be sure that you leave the two additional fields blank
- Click the Save button

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User receives validation errors indicating that they need to select a motion to displose of, and the disposition.


#### 8) Docket Clerk selects a motion and the disposition for the Order; Saves edited Order.

**Part 1**
- Continuing from the previous test
- Click on the dropdown menu to select a motion that is being disposed of

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu displays the index number and Motion Name for each motion on the docket record.

**Part 2**
- Click on the dropdown for the disposition of the motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Selections include Granted, Granted in Part, and Denied.

**Part 3**
- Docket Clerk clicks save entry.

Expected Results:
- [ ] Order record is saved appropriately



#### 9) The text in the Filings and Proceedings column for the original Motion on the docket record is updated

- Continuing from the previous test
- You should have a green confirmation banner
- Scroll down on the docket record and review the entry for the original motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing
- [ ] **NEW FUNCTIONALITY** - There is no Notice of Docket Change for the updated text on the Original motion.



#### 10) Docket Clerk checks the box indicating that the Order disposes of a motion; No motions are present on the docket record; What motion is being disposed dropdown menu indicates that there are no motions.

- Log in as a docket clerk
- Navigate to a case that does not have any motions on the docket record, but has a draft order
- Click on the add docket entry button
- Check the box for "This order disposes of a motion"
- Click on the What motion is being disposed dropdown

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu states, "There are no motions on the docket record" 



#### 11) Repeat tests 1-10 with the Clerk of the Court and with the Case Services Supervisor

- [ ] Tests 1-10 pass with the CotC user
- [ ] Tests 1-10 pass with the Case Services Supervisor 



#### 12) When External parties view the case docket record, they can also see the appended text on the original motion.

- As an external user, navigate to the cases that you were testing with in the previous steps.
- Review the docket record

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing

*Repeat this test with other external users (Petitioner, IRS, Practitioner, Terminal user)
